### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable. (copy to bitsandbytes folder didnt help)

### ISSUE THREAD

**Issue by alex-shmidt** [bmaltais/kohya_ss#1000]
Already saw thread with problem looks like mine. Tried to copy 
the dll files and cextension.py to  .\venv\Lib\site-packages\bitsandbytes\
and main.py to .\venv\Lib\site-packages\bitsandbytes\cuda_setup\

There was NO bitsandbytes in my VENV folder (created this muanualy)
Now, i have this structure:
![image](https://github.com/bmaltais/kohya_ss/assets/83653180/d0ae44a2-332c-4021-bcd1-1b5dd03858e6)

But STILL have same issue
Faced this issue:

TypeError: argument of type 'WindowsPath' is not iterable
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\SD_Kohya_ss_Portable\python\lib\runpy.py:196 in _run_module_as_main                           │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\python\lib\runpy.py:86 in _run_code                                      │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\launch.py:918 in              │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\launch.py:580 in              │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\SD_Kohya_ss_Portable\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:/Stable diffusion/SD/stable-diffusion-webui/models/Stable-diffusion/deliberate_v2.safetensors', '--train_data_dir=D:/SD_LORA_tests/images', '--resolution=512,512', '--output_dir=D:/SD_LORA_tests/output',
'--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=JBStyle', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=90', '--train_batch_size=2',
'--max_train_steps=900', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--wandb_api_key=False']' returned non-zero exit status 1.

**Comment by sumire608** [comment]
pip install bitsandbytes-windows

Try this.

**Comment by bmaltais** [comment]
> pip install bitsandbytes-windows
> 
> Try this under venv.

Is this a new release of bitsandbytes? Never seen that one... Interesting

**Comment by FurkanGozukara** [comment]
> pip install bitsandbytes-windows
> 
> Try this under venv.

wow working amazing

added this to my tutorial : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/Generate-Studio-Quality-Realistic-Photos-By-Kohya-LoRA-Stable-Diffusion-Training-Full-Tutorial.md

I should make a new video

**Comment by bmaltais** [comment]
Good to know that this different version can help people that have not been able to use kohya_ss due to incompatibilities with the current bitsandbytes release specified.

**Comment by alex-shmidt** [comment]
didnt help for me. Tried pip instal in venv folder:
![image](https://github.com/bmaltais/kohya_ss/assets/83653180/def29888-e584-4b13-b0da-3760c1233398)
after this i deleted all my venv folder, rebuilt it, also tried instal newest pip (like wrote in screenshot), but still errors.. But looks like now it is different:

UnboundLocalError: local variable 'pipe' referenced before assignment
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\SD_Kohya_ss_Portable\python\lib\runpy.py:196 in _run_module_as_main                           │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\python\lib\runpy.py:86 in _run_code                                      │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\launch.py:918 in              │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\SD_Kohya_ss_Portable\venv\lib\site-packages\accelerate\commands\launch.py:580 in              │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\SD_Kohya_ss_Portable\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:\\Stable diffusion\\SD\\stable-diffusion-webui\\models\\Stable-diffusion/deliberate_v2.safetensors', '--train_data_dir=D:/SD_LORA_tests/images', '--resolution=512,512',
'--output_dir=D:/SD_LORA_tests/output', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=JBStyle', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--train_batch_size=1',
'--max_train_steps=1800', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--bucket_reso_steps=64', '--mem_eff_attn', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by alex-shmidt** [comment]
PIP upgrading gives me this error:

![image](https://github.com/bmaltais/kohya_ss/assets/83653180/d8ec3948-1b38-4683-b400-d2a6d0512c97)

**Comment by sumire608** [comment]
[alex-shmidt](https://github.com/alex-shmidt)

You forgot to do that **under venv**.

**Comment by sumire608** [comment]
run \venv\Scripts\activate.bat
😅

**Comment by alex-shmidt** [comment]
> run \venv\Scripts\activate.bat 😅

all the same. running this .bat file did not lead to anything and did not change anything (when I ran it, the command line did not open or something like that
