### ISSUE TITLE
DyLoRA extraction is not working.

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1002]
Traceback (most recent call last):
File "D:\kohya_ss\networks\extract_lora_from_dylora.py", line 125, in
split(args)
File "D:\kohya_ss\networks\extract_lora_from_dylora.py", line 78, in split
comment = metadata.get("ss_training_comment", "")
AttributeError: 'NoneType' object has no attribute 'get'

Nothing is ever created (the other extractions work fine).

**Comment by bmaltais** [comment]
Hummm... I suggest to open an issue directly with the author of the script at: https://github.com/KohakuBlueleaf/LyCORIS/issues

**Comment by DarkAlchy** [comment]
Well, I may be the one at fault but is there a difference between a regular model (trained with FT, or DreamBooth) and one trained as a DyLoRA?  I ask because the gui asks for the DyLoRA model while the others ask for the Finetuned model.

**Comment by DarkAlchy** [comment]
Ahhhh, and training one of those many have had the worst time with.

Thank you.
