### ISSUE TITLE
modules installed outside the virtual environment were found

### ISSUE THREAD

**Issue by omarbdri** [bmaltais/kohya_ss#1008]
When trying to start up the LORA training gui, the cmd window opens, then displays the following before quickly closing:

`========================================
modules installed outside the virtual environment were found.
this can cause issues. Please review the installed modules.

You can deinstall all the local modules with:

deactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
========================================`
![image](https://github.com/bmaltais/kohya_ss/assets/84662449/ccc7d8a5-e4de-4b35-8e33-dd7a534e592b)

Also, "uninstall.txt" doesn't exist in the kohya_ss folder. How can I start the gui?

**Comment by bmaltais** [comment]
The uninstall.txt will be created when you run the 3 commands listed to uninstall all local modules outside the venv

You can run the GUI.bat file from a terminal to get the list of errors, and then run the 3 commands if you want to uninstall the modules.

**Comment by FurkanGozukara** [comment]
> The uninstall.txt will be created when you run the 3 commands listed to uninstall all local modules outside the venv
> 
> You can run the GUI.bat file from a terminal to get the list of errors, and then run the 3 commands if you want to uninstall the modules.

I also didn't understand this message

I made a fresh install on a fresh venv of kohya

which are these modules installed? how do we see list? what effect they make?

**Comment by bmaltais** [comment]
That must have been installed outside a venv by other applications. I have seen those modules getting used instead of the ones supposed to be installed in the venv and causing issues in the past. I am therefore letting users know and let them decide how they want to deal with this situation.

If you just run `pip freeze` when the venv is not active (type `deactivate` to make sure it is not) you will get a list of everything installed outside the venv.

**Comment by thiagopasseri** [comment]
This issue happened to me when I changed the location of Kohya. 
I managed to solve it by changing the venv's path in the activate.bat as follows:

Edit the the activate.bat in located in ...\kohya_ss\venv\Scripts

in the line 11:
set VIRTUAL_ENV=C:\Stable Diffusion\kohya video\kohya_ss\venv

check if the location is right. If not, paste the right location. 
Solved!
