### ISSUE TITLE
How to use fp8?

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1010]
I have chosen fp8 from manual config

here

but there is no option in gui for fp8

```
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp8
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by bmaltais** [comment]
Don't think kohya_ss sd-scripts support it...

**Comment by FurkanGozukara** [comment]
> Don't think kohya_ss sd-scripts support it...

it is in the setup - 3. Manually configure accelerate

**Comment by bmaltais** [comment]
YEah... accelerate might offer support for it... but the sd-script repo created by kohya_ss does not support it at the moment.
