### ISSUE TITLE
does not run on linux

### ISSUE THREAD

**Issue by VeyDlin** [bmaltais/kohya_ss#1011]
ubuntu 22.04
AMD EPYC 
NVIDIA® Ampere® A100
CPU 28
RAM 120GB

install
```
root@ai:/home/veydlin# git clone https://github.com/bmaltais/kohya_ss.git
Cloning into 'kohya_ss'...
remote: Enumerating objects: 7679, done.
remote: Counting objects: 100% (2066/2066), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 7679 (delta 1921), reused 1968 (delta 1874), pack-reused 5613
Receiving objects: 100% (7679/7679), 5.74 MiB | 9.09 MiB/s, done.
Resolving deltas: 100% (5337/5337), done.
root@ai:/home/veydlin# cd kohya_ss
root@ai:/home/veydlin/kohya_ss# ./setup.sh
Attempting to clone https://github.com/bmaltais/kohya_ss.git.
git repo detected. Attempting to update repository instead.
Updating: https://github.com/bmaltais/kohya_ss.git
From https://github.com/bmaltais/kohya_ss
 * branch            master     -> FETCH_HEAD
Already on 'master'
Installing Python TK if not found on the system.
Ubuntu detected.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Failed to start apt-news.service: Unit apt-news.service not found.
Failed to start esm-cache.service: Unit esm-cache.service not found.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Switching to virtual Python environment.
Checking for pip updates before Python operations.
Installing python dependencies. This could take a few minutes as it downloads files.
If this operation ever runs too long, you can rerun this script in verbose mode to check.
Removing the temp requirements file.
Exiting Python virtual environment.
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
root@ai:/home/veydlin/kohya_ss#
```

run
```
root@ai:/home/veydlin/kohya_ss# ./gui.sh
The sudo command resets the non-essential environment variables, we keep the LD_LIBRARY_PATH variable.
23:56:16-198862 INFO     Version: eec7d05 Sat Jun 17 06:39:03 2023 -0400
23:56:16-202724 INFO     Verifying requirements
23:56:16-205114 WARNING  Package wrong version: gradio 3.32.0 required 3.23.0;
23:56:16-206087 INFO     Installing package: gradio==3.23.0; sys_platform == 'darwin'
23:56:19-522468 ERROR    Error running pip: install --upgrade gradio==3.23.0; sys_platform == 'darwin'
23:56:19-524065 WARNING  Package wrong version: gradio 3.32.0 required 3.32.0;
23:56:19-524941 INFO     Installing package: gradio==3.32.0; sys_platform != 'darwin'
23:56:22-281405 ERROR    Error running pip: install --upgrade gradio==3.32.0; sys_platform != 'darwin'
23:56:22-282968 WARNING  Package wrong version: huggingface-hub 0.13.3 required 0.13.3;
23:56:22-283929 INFO     Installing package: huggingface-hub==0.13.3; sys_platform == 'darwin'
23:56:24-070281 ERROR    Error running pip: install --upgrade huggingface-hub==0.13.3; sys_platform == 'darwin'
23:56:24-071889 WARNING  Package wrong version: huggingface-hub 0.13.3 required 0.13.3;
23:56:24-072803 INFO     Installing package: huggingface-hub==0.13.3; sys_platform != 'darwin'
23:56:25-874174 ERROR    Error running pip: install --upgrade huggingface-hub==0.13.3; sys_platform != 'darwin'
23:56:25-876600 INFO     Installing package: tensorboard==2.10.1 ; sys_platform != 'darwin'
23:56:27-729567 ERROR    Error running pip: install --upgrade tensorboard==2.10.1 ; sys_platform != 'darwin'
23:56:27-731196 WARNING  Package wrong version: tensorboard 2.10.1 required 2.12.1
23:56:27-732208 INFO     Installing package: tensorboard==2.12.1 ; sys_platform == 'darwin'
23:56:30-787209 ERROR    Error running pip: install --upgrade tensorboard==2.12.1 ; sys_platform == 'darwin'
23:56:30-788728 WARNING  Package wrong version: tensorflow 2.10.1 required 2.10.1;
23:56:30-789628 INFO     Installing package: tensorflow==2.10.1; sys_platform != 'darwin'
23:56:33-674775 ERROR    Error running pip: install --upgrade tensorflow==2.10.1; sys_platform != 'darwin'
Traceback (most recent call last):
  File "/home/veydlin/kohya_ss/kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "/home/veydlin/kohya_ss/dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "/home/veydlin/kohya_ss/library/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
root@ai:/home/veydlin/kohya_ss#
```

**Comment by FurkanGozukara** [comment]
runs i have a runpod tutorial watch it and you can fix the error : https://youtu.be/3uzCNrQao3o

**Comment by bmaltais** [comment]
Each release of Ubuntu have different requirements. I have kind of made it work under Ubuntu 20.04... but under 18.04 no luck. I have not tested it under 22.04.

**Comment by sivagaga** [comment]
I also had a similar problem on debian 11 linux.

_12:40:04-333162 INFO     Version: eec7d05 Sat Jun 17 06:39:03 2023 -0400
12:40:04-341291 INFO     Verifying requirements
12:40:04-347305 WARNING  Package wrong version: gradio 3.32.0 required 3.23.0;
12:40:04-349885 INFO     Installing package: gradio==3.23.0; sys_platform == 'darwin'
12:40:05-891706 ERROR    Error running pip: install --upgrade gradio==3.23.0; sys_platform == 'darwin'
12:40:05-892550 WARNING  Package wrong version: gradio 3.32.0 required 3.32.0;
12:40:05-892977 INFO     Installing package: gradio==3.32.0; sys_platform != 'darwin'
12:40:07-451076 ERROR    Error running pip: install --upgrade gradio==3.32.0; sys_platform != 'darwin'
12:40:07-451947 WARNING  Package wrong version: huggingface-hub 0.13.3 required 0.13.3;
12:40:07-452415 INFO     Installing package: huggingface-hub==0.13.3; sys_platform == 'darwin'
12:40:08-529752 ERROR    Error running pip: install --upgrade huggingface-hub==0.13.3; sys_platform == 'darwin'
12:40:08-530576 WARNING  Package wrong version: huggingface-hub 0.13.3 required 0.13.3;
12:40:08-531015 INFO     Installing package: huggingface-hub==0.13.3; sys_platform != 'darwin'
12:40:09-554654 ERROR    Error running pip: install --upgrade huggingface-hub==0.13.3; sys_platform != 'darwin'
12:40:09-556457 INFO     Installing package: tensorboard==2.10.1 ; sys_platform != 'darwin'
12:40:10-589281 ERROR    Error running pip: install --upgrade tensorboard==2.10.1 ; sys_platform != 'darwin'
12:40:10-590122 WARNING  Package wrong version: tensorboard 2.10.1 required 2.12.1
12:40:10-590566 INFO     Installing package: tensorboard==2.12.1 ; sys_platform == 'darwin'
12:40:20-618033 ERROR    Error running pip: install --upgrade tensorboard==2.12.1 ; sys_platform == 'darwin'
12:40:20-618889 WARNING  Package wrong version: tensorflow 2.10.1 required 2.10.1;
12:40:20-619344 INFO     Installing package: tensorflow==2.10.1; sys_platform != 'darwin'
12:40:22-245276 ERROR    Error running pip: install --upgrade tensorflow==2.10.1; sys_platform != 'darwin'
12:40:23-048870 INFO     headless: False
12:40:23-054999 INFO     Load CSS...
Running on local URL:  http://0.0.0.0:7861_

I am very puzzled, it is not darwin, why does it execute the update marked by darwin in requirements_unix.txt? Therefore, I updated requirements_unix.txt as follows and it worked fine.

_accelerate==0.19.0
albumentations==1.3.0
altair==4.2.2
bitsandbytes==0.35.0
dadaptation==3.1
diffusers[torch]==0.10.2
easygui==0.98.3
einops==0.6.0
fairscale==0.4.13
ftfy==6.1.1
gradio==3.32.0
huggingface-hub==0.13.3
lion-pytorch==0.0.6
lycoris_lora==0.1.6
opencv-python==4.7.0.68
prodigyopt==1.0
pytorch-lightning==1.9.0
rich==13.4.1
safetensors==0.2.6
tensorboard==2.10.1
tensorflow==2.10.1
timm==0.6.12
tk==0.1.0
toml==0.10.2
transformers==4.26.0
voluptuous==0.13.1
wandb==0.15.0
# for kohya_ss library_

**Comment by AsishKakumanu** [comment]
May be an issue with the new commits. Try cloning an old commit

**Comment by Markon101** [comment]
I am having the same issues. Deps are not installing correctly  and trying to manually resolve it has been a pain but I think I am getting somewhere. I cannot find a TensorFlow version for 2.10.0 on my install. I am running Python 3.11 and PyPi shows the package is available, but pip says it is not.

**Comment by bmaltais** [comment]
The whole linex / MacOS is a bit of a mess. There was an attempt to create a common install for all platform but the author is MIA. So perhaps keeping a clear deleniation between the different system is better as each can be independently evolved without risking causing issues for the other. I did update a few things to improve support on Ubuntu in WSL2 but I guess this must have broken support for previously working distro.

I will back out the change so things should get back to what they were... But clearly someone with an interest in using Linux should contribute code to improve the situation there.

I think the new Windows installer is doing a decent job so no need to touch that one for now.

**Comment by bmaltais** [comment]
You might want to try the new setup.sh solution I put together in the:

`git checkout refactor-setup`

branch

**Comment by VladislavNekto** [comment]
```
# Start OS-specific detection and work
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Check if root or sudo
 ```
 ```
 $ echo $OSTYPE
linux
```
No word more, fix it!

**Comment by bmaltais** [comment]
> ```
> # Start OS-specific detection and work
> if [[ "$OSTYPE" == "linux-gnu"* ]]; then
>   # Check if root or sudo
> ```
> 
> ```
> $ echo $OSTYPE
> linux
> ```
> 
> No word more, fix it!

What Linux distro? The one in the script matches Ubuntu. You must be using some other distro?

**Comment by future141** [comment]
I fixed similar problem by changing LD_LIBRARY_PATH. See https://github.com/bmaltais/kohya_ss/issues/1109.
