### ISSUE TITLE
Problem with CUDA versions of packages in Linux

### ISSUE THREAD

**Issue by chefexperte** [bmaltais/kohya_ss#1023]
Hey, I tried to run LORA training on my setup today. I freshly cloned and installed everything. 
I am using Fedora Linux. 

The error I get is the following: 
```
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your
PyTorch install.
```

The lines pip outputs before starting up the program that are relevent are those: 

```
Requirement already satisfied: torchvision in ./venv/lib/python3.10/site-packages (from timm==0.6.12->-r [path]/requirements_unix.txt (line 24)) (0.15.2+cu118)
[...]
Requirement already satisfied: torch>=1.4.0 in ./venv/lib/python3.10/site-packages (from accelerate==0.15.0->-r [path]/requirements_unix.txt (line 1)) (2.0.1+cu118)
```

From which I understood that both packages are using 11.8, but the error suggests otherwise. 
I do not have a global installation of either package.

**Comment by rdcoder33** [comment]
I got the same error. I used this to fix it:

`pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118`

**Comment by kieranxsomer** [comment]
Yep can confirm, that's exactly how to fix it - LOL as in: I wish i would've seen this sooner lol. A lot of old Stable Diffusion issues mention an older torch, so it gets confusing - you'll also need to install xformers to match: https://github.com/facebookresearch/xformers/issues/752

**Comment by etic4** [comment]
in `setup.sh` line 245, removing the `-I` from `pip install -U xformers==0.0.20` , which tells pip to ignore installed packages, works for me

**Comment by bmaltais** [comment]
Hi, let see if we can improve this experience. So for linux install... it look like you need the older torch 2.0.0 module and not 2.0.1?

`pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118`

And then `xformerx==0.0.19`?

If someone can share what make it tic on which Linux distro I could start to create custom requirements.txt files for each so there is a known to work config that is easy to troubleshoot. The current linux is overly complex for it's own good I think... Cramming too many options in something that should be rather simple and easy to maintain...

**Comment by etic4** [comment]
Hi, like I said I think the only problem is the argument -I passed to pip when installing xformers. 

`pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118`

 and then `pip install -U xformers==0.0.20` should work.

I will try to reinstall from the beginning tonight removing this argument to verify.

**Comment by bmaltais** [comment]
Sound good. I am refactoring the setup files under a new setup folder so we can keep things tidier... I will test on WSL2 22.04 to see how it goes with the -I as I don't think it is the actual issue... In a previous release there was an issue with the code re-installing darwin requirements... I made a quick fix for it but ultimatly I would like to split the requirements files for each distro/linux platforms to make it easier to manage...

**Comment by etic4** [comment]
I did a full reinstall on ubuntu 22.04 inside a Miniconda env. 
The miniconda folder is inside my HOME directory: $HOME/miniconda

before reinstalling, I did a "pip cache purge" to start from scratch.

Installation process:

```
conda create -n kohya
conda activate kohya
conda install -c anaconda cudatoolkit

# bitsandbytes doesn't find libcurand.so.10 in the miniconda env
# set de env var in the conda environnement level
conda env config vars set LD_LIBRARY_PATH=$HOME/miniconda/envs/kohya/lib

# set manually LD_LIBRARY_PATH for this session
LD_LIBRARY_PATH=$HOME/miniconda/envs/kohya/lib

# OR disable and re-enable the environment for the change to the environment variable to take effect
conda deactivate
conda activate

# clone commit 5eccb654 2023-06-21 17:29
git clone https://github.com/bmaltais/kohya_ss.git && cd kohya_ss

# remove pip's -I flag from setup.sh line 245. Gives: pip install -U xformers=0.0.20
# commit the modif
git commit -a -m "pip's ignore flag on xformers install removed"
# launch setup et gui
./setup.sh
./gui.sh
```

It works perfectly.

I think the "-U" in the xformers install line does anything. It seems strange to me to upgrade a package with a specific version number.
In my opinion the -U ("Upgrade all specified packages to the newest available version") can be deleted at the same time as the -I ("Ignore the installed packages, overwriting them") in the xformers installation line

**Comment by etic4** [comment]
Conclusion: it was the "-I" flag that was responsible for the message:

`RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.`

because it allows xformers to ignore the presence of the installed version of pytorch compiled with cuda 11.8 and install a version compiled with cuda 11.7
