### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by sterben0000** [bmaltais/kohya_ss#1024]
![image](https://github.com/bmaltais/kohya_ss/assets/136901069/fb449b67-2f56-4f2f-a84f-75c0e7e44691) 
when I try to install it stucks here

**Comment by bmaltais** [comment]
Might be a slow download. This torch module is HUGE... Give it a little of time... Possibly up to 1 hour

**Comment by sterben0000** [comment]
> Might be a slow download. This torch module is HUGE... Give it a little of time... Possibly up to 1 hour

yes i waited and it downloaded the files. and how can i download cudnn 8.6? I don't understand where I should put the cuddn_windows file.
