### ISSUE TITLE
How should I setup my configuration file (and training dir) to train a Lora of 4 concepts ?

### ISSUE THREAD

**Issue by by321** [bmaltais/kohya_ss#1025]
Hi,

I've already read various docs, and I'm still not sure how I should setup my training images and config files. I just can't find an example of config files.

I'm trying to train a lora with 4 concepts. Currently, I have put my images in 4 separate directories, and I already tagged the images. For each image, there's a corresponding .txt file containing the tags of the image.

If possible, I'd prefer not to use class tokens mentioned in various docs (for example "shsdog").

Thanks.

**Comment by bmaltais** [comment]
That is exactly how to do it. If you tag the images then the folder name is diregarded and the content of each txt file is used. Only the repeat part of the folder is used to calculate the number of total steps.

**Comment by by321** [comment]
But what about the configuration file ? In the GUI it asks me for a configuration file, and I don't really know what to put in it.

**Comment by bmaltais** [comment]
THere is no need for a configuration file. THe configuration you will set in the GUI can be saved to a configuration file you can use later on to reload the config for the training you did, and tweak it as needed. This is what the config files are for mostly.

**Comment by by321** [comment]
So, if I have my directories like this:

```
\main_dir : <no file>
\main_dir\a_30 : 1.png 1.txt 2.png 2.txt 3.png 3.txt ...
\main_dir\b_30 : 1.png 1.txt 2.png 2.txt 3.png 3.txt ...
\main_dir\c_30 : 1.png 1.txt 2.png 2.txt 3.png 3.txt ...
\main_dir\d_30 : 1.png 1.txt 2.png 2.txt 3.png 3.txt ...

```
Then I just use the main_dir as the top-level training image folder, and each subdir/concept would be repeated/trained 30 times ?

**Comment by bmaltais** [comment]
This is correct

**Comment by by321** [comment]
OK thanks.
