### ISSUE TITLE
Python runtime error, PyTorch/torchvision mismatch on recent release (Linux)

### ISSUE THREAD

**Issue by crotalidae75** [bmaltais/kohya_ss#1028]
I'm running Kubuntu 22.04, and with the recent release (v21.7.10), I get this Python error when trying to start training:

`RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.8. Please reinstall the torchvision that matches your PyTorch install.`
 
So far I've had to roll back to 21.7.7, because I can't figure out how to fix this, but there also seems to be a problem with the script installing the wrong PyTorch version (?) --  I've checked, and it seems to be an issue with the local PyTorch in ~/kohya_ss/venv/, and not my main Python install.

Any ideas on a quick fix? I'm relatively new to working with Python.

**Comment by bmaltais** [comment]
I have pushed fresh reworked setup.sh code in a new branch called refactor-setup, you could checkout that branch and see if it fixes the issue. I have tested in in Ubuntu 22.04 with success

**Comment by crotalidae75** [comment]
> I have pushed fresh reworked setup.sh code in a new branch called refactor-setup, you could checkout that branch and see if it fixes the issue. I have tested in in Ubuntu 22.04 with success
> 
> git checkout refactor-setup

Thanks, that solved the issue.  I appreciate the quick help.
