### ISSUE TITLE
Kohya's gui crashes after update

### ISSUE THREAD

**Issue by humongous74** [bmaltais/kohya_ss#1031]
I just updated to the latest Kohya_ss by using the upgrade.bat and as soon as I click on the Gui.bat  it crashes. Can somebody please help me with this situation?

**Comment by bmaltais** [comment]
Run the GUI.bat in a terminal so you can see the error. Should help troubleshoot the issue. Best solution is usually to delete the venv and redo setup.bat

**Comment by humongous74** [comment]
The best solution worked, now Kohya is back to normal. Thanks!!
