### ISSUE TITLE
BUG:  OSError: [Errno 22] Invalid argument:

### ISSUE THREAD

**Issue by thanhdogau** [bmaltais/kohya_ss#1039]
Hi, I have a bug after press "Caption Images" in BLIP:

To create a public link, set `share=True` in `launch()`.
17:48:09-691663 INFO     Captioning files in G:/Stable Diffusion/AI Train/...
17:48:09-692660 INFO     ./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1"
                         --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt"
                         "G:/Stable Diffusion/AI Train/GAME LORA/img/104_Fenrir"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/mode
                         l_large_caption.pth"
Current Working Directory is:  C:\AI\kohya_ss
load images from G:/Stable Diffusion/AI Train/GAME LORA/img/104_Fenrir
found 8 images.
loading BLIP caption: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\AI\kohya_ss\finetune\make_captions.py:200 in <module>                                         │
│                                                                                                  │
│   197 │   if args.caption_extention is not None:                                                 │
│   198 │   │   args.caption_extension = args.caption_extention                                    │
│   199 │                                                                                          │
│ ❱ 200 │   main(args)                                                                             │
│   201                                                                                            │
│                                                                                                  │
│ C:\AI\kohya_ss\finetune\make_captions.py:86 in main                                              │
│                                                                                                  │
│    83 │   print(f"found {len(image_paths)} images.")                                             │
│    84 │                                                                                          │
│    85 │   print(f"loading BLIP caption: {args.caption_weights}")                                 │
│ ❱  86 │   model = blip_decoder(pretrained=args.caption_weights, image_size=IMAGE_SIZE, vit="la   │
│    87 │   model.eval()                                                                           │
│    88 │   model = model.to(DEVICE)                                                               │
│    89 │   print("BLIP loaded")                                                                   │
│                                                                                                  │
│ C:\AI\kohya_ss\finetune\blip\blip.py:175 in blip_decoder                                         │
│                                                                                                  │
│   172                                                                                            │
│   173                                                                                            │
│   174 def blip_decoder(pretrained='',**kwargs):                                                  │
│ ❱ 175 │   model = BLIP_Decoder(**kwargs)                                                         │
│   176 │   if pretrained:                                                                         │
│   177 │   │   model,msg = load_checkpoint(model,pretrained)                                      │
│   178 │   │   assert(len(msg.missing_keys)==0)                                                   │
│                                                                                                  │
│ C:\AI\kohya_ss\finetune\blip\blip.py:98 in __init__                                              │
│                                                                                                  │
│    95 │   │   super().__init__()                                                                 │
│    96 │   │                                                                                      │
│    97 │   │   self.visual_encoder, vision_width = create_vit(vit,image_size, vit_grad_ckpt, vi   │
│ ❱  98 │   │   self.tokenizer = init_tokenizer()                                                  │
│    99 │   │   med_config = BertConfig.from_json_file(med_config)                                 │
│   100 │   │   med_config.encoder_width = vision_width                                            │
│   101 │   │   self.text_decoder = BertLMHeadModel(config=med_config)                             │
│                                                                                                  │
│ C:\AI\kohya_ss\finetune\blip\blip.py:189 in init_tokenizer                                       │
│                                                                                                  │
│   186 │   return model                                                                           │
│   187                                                                                            │
│   188 def init_tokenizer():                                                                      │
│ ❱ 189 │   tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')                         │
│   190 │   tokenizer.add_special_tokens({'bos_token':'[DEC]'})                                    │
│   191 │   tokenizer.add_special_tokens({'additional_special_tokens':['[ENC]']})                  │
│   192 │   tokenizer.enc_token_id = tokenizer.additional_special_tokens_ids[0]                    │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\transformers\tokenization_utils_base.py:1763 in            │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1760 │   │   │   │   elif is_remote_url(file_path):                                            │
│   1761 │   │   │   │   │   resolved_vocab_files[file_id] = download_url(file_path, proxies=prox  │
│   1762 │   │   │   else:                                                                         │
│ ❱ 1763 │   │   │   │   resolved_vocab_files[file_id] = cached_file(                              │
│   1764 │   │   │   │   │   pretrained_model_name_or_path,                                        │
│   1765 │   │   │   │   │   file_path,                                                            │
│   1766 │   │   │   │   │   cache_dir=cache_dir,                                                  │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\transformers\utils\hub.py:409 in cached_file               │
│                                                                                                  │
│    406 │   user_agent = http_user_agent(user_agent)                                              │
│    407 │   try:                                                                                  │
│    408 │   │   # Load from URL or cache if already cached                                        │
│ ❱  409 │   │   resolved_file = hf_hub_download(                                                  │
│    410 │   │   │   path_or_repo_id,                                                              │
│    411 │   │   │   filename,                                                                     │
│    412 │   │   │   subfolder=None if len(subfolder) == 0 else subfolder,                         │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\huggingface_hub\utils\_validators.py:120 in _inner_fn      │
│                                                                                                  │
│   117 │   │   if check_use_auth_token:                                                           │
│   118 │   │   │   kwargs = smoothly_deprecate_use_auth_token(fn_name=fn.__name__, has_token=ha   │
│   119 │   │                                                                                      │
│ ❱ 120 │   │   return fn(*args, **kwargs)                                                         │
│   121 │                                                                                          │
│   122 │   return _inner_fn  # type: ignore                                                       │
│   123                                                                                            │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py:1296 in hf_hub_download   │
│                                                                                                  │
│   1293 │   if os.name == "nt" and len(os.path.abspath(blob_path)) > 255:                         │
│   1294 │   │   blob_path = "\\\\?\\" + os.path.abspath(blob_path)                                │
│   1295 │                                                                                         │
│ ❱ 1296 │   with FileLock(lock_path):                                                             │
│   1297 │   │   # If the download just completed while the lock was activated.                    │
│   1298 │   │   if os.path.exists(pointer_path) and not force_download:                           │
│   1299 │   │   │   # Even if returning early like here, the lock will be released.               │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\filelock\_api.py:255 in __enter__                          │
│                                                                                                  │
│   252 │   │                                                                                      │
│   253 │   │   :return: the lock object                                                           │
│   254 │   │   """                                                                                │
│ ❱ 255 │   │   self.acquire()                                                                     │
│   256 │   │   return self                                                                        │
│   257 │                                                                                          │
│   258 │   def __exit__(                                                                          │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\filelock\_api.py:213 in acquire                            │
│                                                                                                  │
│   210 │   │   │   while True:                                                                    │
│   211 │   │   │   │   if not self.is_locked:                                                     │
│   212 │   │   │   │   │   _LOGGER.debug("Attempting to acquire lock %s on %s", lock_id, lock_f   │
│ ❱ 213 │   │   │   │   │   self._acquire()                                                        │
│   214 │   │   │   │   if self.is_locked:                                                         │
│   215 │   │   │   │   │   _LOGGER.debug("Lock %s acquired on %s", lock_id, lock_filename)        │
│   216 │   │   │   │   │   break                                                                  │
│                                                                                                  │
│ C:\AI\kohya_ss\venv\lib\site-packages\filelock\_windows.py:27 in _acquire                        │
│                                                                                                  │
│   24 │   │   │   │   | os.O_TRUNC  # truncate file if not empty                                  │
│   25 │   │   │   )                                                                               │
│   26 │   │   │   try:                                                                            │
│ ❱ 27 │   │   │   │   fd = os.open(self.lock_file, flags, self._context.mode)                     │
│   28 │   │   │   except OSError as exception:                                                    │
│   29 │   │   │   │   if exception.errno != EACCES:  # has no access to this lock                 │
│   30 │   │   │   │   │   raise                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 22] Invalid argument:
'C:\\Users\\ADMIN/.cache\\huggingface\\hub\\models--bert-base-uncased\\blobs\\W/"fb140275c155a9c7c5a3b3e0e77a9e839594a93
8.lock'
17:48:18-338520 INFO     ...captioning done

-----------------
It didn't create any .txt files after this. I'm using Window 11.

Do anyone have a solution for this bug?

**Comment by bmaltais** [comment]
I will check it this morning

**Comment by bmaltais** [comment]
Good morning,

I just tried it on my system running with torch 2 and wverything went fine:

```
07:02:45-327752 INFO     Captioning files in D:\dataset\blake_creates\img\10_cables retake artstyle...
07:02:45-328749 INFO     ./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search
                         --caption_extension=".txt2" "D:\dataset\blake_creates\img\10_cables retake artstyle"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Current Working Directory is:  D:\kohya_ss
load images from D:\dataset\blake_creates\img\10_cables retake artstyle
found 24 images.
loading BLIP caption: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
BLIP loaded
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:10<00:00,  2.25it/s] 
done!
07:03:18-745492 INFO     ...captioning done
```

Can you try to delete your venv folder and re-run setup.bat to install fresh? It might fix the issue as sometime venv can get out of whack.

**Comment by thanhdogau** [comment]
Hi, I did as you said, Delete venv folder, and re-run setup.bat to install fresh, then install torch 2 (Press 2). But It didn't work. It show this after I start gui.bat, then auto close the gui.bat:

181 ERROR Could not load torch: cuDNN version incompatibility: PyTorch was compiled against (8, 7, 0)
but found runtime version (8, 6, 0). PyTorch already comes bundled with cuDNN. One option to
resolving this error is to ensure PyTorch can find the bundled CuDNN.
