### ISSUE TITLE
DAdaptation not working

### ISSUE THREAD

**Issue by DiggyDre** [bmaltais/kohya_ss#1041]
Is there something special that needs to be done in order to run DAdaptation? I am on a 1070ti. I was trying to follow along with the video [Modeling The White Queen as a Stable Diffusion LoRA](https://youtu.be/etEo6Lf7QIc) There are some things different about the GUI in the video but I noticed that it was meant to run on DAdaptation but I am getting nowhere with it when I attempt to use it as an optimizer :(

**Comment by bmaltais** [comment]
I think you could try to manually run this command when the venv is active. It might help:

`pip install bitsandbytes-windows`

**Comment by DiggyDre** [comment]
Thank you for your reply. I gave that a shot and then attempted to use the DAdaptation according to the way that things were set in the video that I linked above, and this is what it returned to me.

![kohya_01](https://github.com/bmaltais/kohya_ss/assets/127576526/9b2db370-4519-4a9b-870b-643662a82849)
![kohya_02](https://github.com/bmaltais/kohya_ss/assets/127576526/cf8eeef9-22f6-472b-9798-35cad3a21ef3)

**Comment by bmaltais** [comment]
For dadaptation you need to set all LR fields to 1... give that a try.
