### ISSUE TITLE
There is no cudann_1.8_install.py in the tools folder

### ISSUE THREAD

**Issue by xathian** [bmaltais/kohya_ss#1045]
Installing on Windows, up to the point of installing CUDNN 8.6 but this step

`python .\tools\cudann_1.8_install.py`

Fails beacuse that file doesn't exist in the folder.

**Comment by bmaltais** [comment]
You don't need to run that anymore with the new setup.bat, It will do it via a new python code. I guess I need to update the README

**Comment by ruiboy1919** [comment]
Place the downloaded folder in the direct folder of Kohya_ss and run it.
The latest version will do it for you in the installation run.
