### ISSUE TITLE
Issue with new update in rupod

### ISSUE THREAD

**Issue by Norian11** [bmaltais/kohya_ss#1046]
In previous version i had this error: runtimeerror: detected that pytorch and torchvision were compiled with different cuda versions. pytorch has cuda version=11.7 and torchvision has cuda version=11.8. please reinstall the torchvision that matches your pytorch install.

Which i solved installing in the venv the correct version of torch and that worked perfectly.
Now in this new version i get this:

20:05:40-935266 INFO     Version: 4275c12 Fri Jun 23 13:23:25 2023 -0400                                                                                                         
20:05:40-943993 INFO     nVidia toolkit detected                                                                                                                                 
20:05:42-135906 INFO     Torch 2.0.0+cu118                                                                                                                                       
20:05:42-141592 ERROR    Could not load torch: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 5, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.one possibility is that there is a conflicting cuDNN in LD_LIBRARY_PATH.

No matter if i unistall and install the correct torch i dont know how make it work, so im using the git checkout and works with the other version

**Comment by bmaltais** [comment]
Yeah... I don't use runpod. If you ever figure out what make it tick let me know, I will create a runpod specific requirements file so the right versions are installed. I hope you can make it work and share the `pip freeze` output.

**Comment by bmaltais** [comment]
I just did a quick test on runpod pytorch 2.0.1 and I was able to train a test model... not sure why you can't train... I will make some more testing as I saw files were installed outside the workspace folder... not sure why.

**Comment by Norian11** [comment]
Oh then i suppose its because im using the pod with automatic1111 and maybe that conflicts with the things of Kohya, but i installed it with the venv activated so i dont know why it occurs, and is only with the new update. As you said i have seen that it starts using all the container storage like if it is not installing the things in workspace, but i just restart the pod and it starts using the normal volume as should be, im very new to runpod so i dont know why this problems happen sadly. I will use git checkout then if im in a pod with auto1111. Should i close this issue right?

**Comment by Norian11** [comment]
One thing, could you tell me your steps to run kohya? Dont write code, just to see if you do something extra that i dont

**Comment by bmaltais** [comment]
Just use the official pytorch 2.0.1 pod, then

```
cd /workspace
git clone https://github.com/bmaltais/kohya_ss.git
git checkout dev2
./setup.sh -p
```

Enjoy

**Comment by Norian11** [comment]
Okay thanks for your time, i will use the pytorch pod from now on
