### ISSUE TITLE
There is no requirements_macos.txt in the repository

### ISSUE THREAD

**Issue by mega01byte** [bmaltais/kohya_ss#1049]
After installing and running the ./gui.sh command i get error message that the file in reference does not exist.

I checked and in effect it is not in the folder.

Went to the repository and all other versions are available except for "requirements_macos.txt".

Can you pleas upload?

**Comment by bmaltais** [comment]
Try the dev2 branch. I pushed a fix for it there:

`git checkout dev2`
`git pull`

**Comment by mega01byte** [comment]
Thanks.

I am now getting the following warning:

Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.

Any suggestions?

I am running an M2 Mac.

**Comment by bmaltais** [comment]
I have never been able to run it on a Mac... If you ever figure out what make it work I could add it to the repo.
