### ISSUE TITLE
DOCKER INSTALL - LINUX (UNIVERSAL ISSUE + QUICK-FIX)

### ISSUE THREAD

**Issue by noxiouscardiumdimidium** [bmaltais/kohya_ss#1051]
requirement.txt files are located outside docker file system:

` ERROR [kohya-ss-gui  8/13] COPY requirements_linux.txt ./setup/setup.py ./ `

manually copy CORRECT req .txt to setup folder - rename "setup.py"
relaunch `docker compose build`

*EDIT* discovered followup error when i whent back.
The original reqs file is the one it ries to use for  `python3 -m pip install --use-pep517 -r requirements_linux.txt xformers`
becuse that first operation fails because of file ownership, it never stats the new file at `./` it has ownership of, to run the pip install
`
i ended up having manually create the requirement.txt in top layer, move copy to ./setup as setup.py, , and give linux_requirements requirement and setup read/write permissions for the docker user-group

**Comment by kieranxsomer** [comment]
Ok question: If i'm using terminal/ssh how do i do this LOL, I haven't used DOS or anything this extensive since i was like 12 lmao.

**Comment by noxiouscardiumdimidium** [comment]
> Ok question: If i'm using terminal/ssh how do i do this LOL, I haven't used DOS or anything this extensive since i was like 12 lmao.

cd into Kohya top layer, then YOU have to enter the command it failed on

`cp ./[reqs.txt] ./setup/setup.py ./` 
where [reqs.txt] is the exact name of the requirements file for you systems installation
(mine is requirements_linux.txt)

**Comment by xathian** [comment]
That helped it start, only for this to happen 5 minutes into the install

```
=> ERROR [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers                       1.5s
------
 > [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers:
#0 0.871 ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
------
failed to solve: process "/bin/sh -c python3 -m pip install --use-pep517 -r requirements_linux.txt xformers" did not complete successfully: exit code: 1
```

**Comment by noxiouscardiumdimidium** [comment]
> That helped it start, only for this to happen 5 minutes into the install
> 
> ```
> => ERROR [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers                       1.5s
> ------
>  > [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers:
> #0 0.871 ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
> ------
> failed to solve: process "/bin/sh -c python3 -m pip install --use-pep517 -r requirements_linux.txt xformers" did not complete successfully: exit code: 1
> ```

LOL, i JUST updated the post to reflect im getting that too now xP... and if you give the docker group read/write permissions of the file, you ge ta whole error later! yay!....

**Comment by xathian** [comment]
> > That helped it start, only for this to happen 5 minutes into the install
> > ```
> > => ERROR [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers                       1.5s
> > ------
> >  > [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers:
> > #0 0.871 ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
> > ------
> > failed to solve: process "/bin/sh -c python3 -m pip install --use-pep517 -r requirements_linux.txt xformers" did not complete successfully: exit code: 1
> > ```
> 
> LOL, i JUST updated the post to reflect im getting that too now xP... and if you give the docker group read/write permissions of the file, you ge ta whole error later! yay!....

Honestly about to just ditch this software entirely and move on soon. Spent more days fixing this shit than actually doing an AI generating.

**Comment by kieranxsomer** [comment]
> > > That helped it start, only for this to happen 5 minutes into the install
> > > ```
> > > => ERROR [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers                       1.5s
> > > ------
> > >  > [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers:
> > > #0 0.871 ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
> > > ------
> > > failed to solve: process "/bin/sh -c python3 -m pip install --use-pep517 -r requirements_linux.txt xformers" did not complete successfully: exit code: 1
> > > ```
> > 
> > 
> > LOL, i JUST updated the post to reflect im getting that too now xP... and if you give the docker group read/write permissions of the file, you ge ta whole error later! yay!....
> 
> Honestly about to just ditch this software entirely and move on soon. Spent more days fixing this shit than actually doing an AI generating.

It's not bmaltais's fault lol - most software is written for windows, and if i had the moeny and could swap to windows I WOULD - cause holyfriggen moly i'm SO BORED of trying to custom install stuff for mac - i mean i'm on an AMD mac of course, but even AMD gpu''s on windows ar easier to get software for XD

adn i'm onyl on a mac caues hand me downs XD

**Comment by xathian** [comment]
> > > > That helped it start, only for this to happen 5 minutes into the install
> > > > ```
> > > > => ERROR [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers                       1.5s
> > > > ------
> > > >  > [ 9/13] RUN python3 -m pip install --use-pep517 -r requirements_linux.txt xformers:
> > > > #0 0.871 ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
> > > > ------
> > > > failed to solve: process "/bin/sh -c python3 -m pip install --use-pep517 -r requirements_linux.txt xformers" did not complete successfully: exit code: 1
> > > > ```
> > > 
> > > 
> > > LOL, i JUST updated the post to reflect im getting that too now xP... and if you give the docker group read/write permissions of the file, you ge ta whole error later! yay!....
> > 
> > 
> > Honestly about to just ditch this software entirely and move on soon. Spent more days fixing this shit than actually doing an AI generating.
> 
> It's not bmaltais's fault lol - most software is written for windows, and if i had the moeny and could swap to windows I WOULD - cause holyfriggen moly i'm SO BORED of trying to custom install stuff for mac - i mean i'm on an AMD mac of course, but even AMD gpu''s on windows ar easier to get software for XD
> 
> adn i'm onyl on a mac caues hand me downs XD

I am on Windows. I've tried to install this the normal windows way, I've tried it on a native linux partition, I've tried it on Docker. Every single ones errors out and fails in a dozen different ways. Just google a youtube video tutorial for this software and sort the comments to Newest First, all the people commenting recently will be noting that nothing works. This entire thing is busted

**Comment by bmaltais** [comment]
No it is not. The latest setup.bat should work fine as long as you have the right prereqs installed. Most of the time the issue is around wrong prereqs version, drivers, etc.

**Comment by bmaltais** [comment]
I am working on updating the Dockerfile that does not understand the new setup solution I implemented... hoping it will be available soon...

**Comment by bmaltais** [comment]
OK, I have pushed an updated Dockerfile and other related files to make the docker build work. Hope it help fix things.

**Comment by noxiouscardiumdimidium** [comment]
> OK, I have pushed an updated Dockerfile and other related files to make the docker build work. Hope it help fix things.

we love you, remember that - thank you for your suppoort, and allowing us to "peruse your War3Z" x)

**Comment by kieranxsomer** [comment]
> OK, I have pushed an updated Dockerfile and other related files to make the docker build work. Hope it help fix things.

Exactly what the guy above said, as cranky and impatient as bug finders are - we respect you, we adore that you're giving us free toys to play with - I make things with kohya-ss (sadly not the bmaltais stuff YET) in colab usually and i'll be coming back to using bmaltais's gui when it's ready again :3 (mostly ti's probably ready soon lmao 0 just i have a raging headache after trying to do something dumb with training a full model XD)
