### ISSUE TITLE
Just fresh installed and it crashes. TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1053]
D:\kohya_ss2\library\train_util.py:3068 in prepare_accelerator                                   │
│                                                                                                  │
│   3065 │   │   │   if args.wandb_api_key is not None:                                            │
│   3066 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3067 │                                                                                         │
│ ❱ 3068 │   accelerator = Accelerator(                                                            │
│   3069 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3070 │   │   mixed_precision=args.mixed_precision,                                             │
│   3071 │   │   log_with=log_with,                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 'logging_dir'.  I removed the log directory and I still get that error.

**Comment by DarkAlchy** [comment]
Now I know why the new version zapped me as I rolled back to see this in cli

D:\kohya_ss2\venv\lib\site-packages\accelerate\accelerator.py:258: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.

**Comment by bmaltais** [comment]
Did setup.bat installed that version? Maybe I introduced a bug during the install?

**Comment by DarkAlchy** [comment]
It must have, and I even installed it on Colab and the exact same bug BUT when I installed the version from 4, or 5 days ago, loically the bug was gone only with that version I am getting an optim error with Prodigy optimiser.

**Comment by bmaltais** [comment]
Weird... I am pretty sure accelerate is pinned to a specific version...

**Comment by bmaltais** [comment]
Dans... I see the issue. I must have copy pasted the wrong version in the requirements... I will make an emergency fix

**Comment by DarkAlchy** [comment]
I tried that and something then complained it needed 0.19.  I hope you have better luck.

**Comment by bmaltais** [comment]
I backreved the linux requirements to 0.15.0... like it was bofore. Not sure why Linux has an issue with it now.
