### ISSUE TITLE
Can you fix the requirements conflicts

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1062]
I just made a fresh install on runpod

After restart of pod here the conflicted versions

Also if you update runpod requirements to cuda118 that is better

I updated my readme file (my tutorial) : https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/How-To-Install-Kohya-LoRA-Web-UI-On-RunPod.md

https://www.youtube.com/watch?v=3uzCNrQao3o

```
root@194a0f4396be:/workspace# bash /workspace/kohya_ss/gui.sh --share
20:03:18-802020 INFO     Version: 2b8a680 Sat Jun 24 11:12:24 2023 -0400                                                                 
20:03:18-815063 INFO     nVidia toolkit detected                                                                                         
20:03:21-082700 INFO     Torch 2.0.1+cu117                                                                                               
20:03:21-115340 INFO     Torch backend: nVidia CUDA 11.7 cuDNN 8700                                                                      
20:03:21-133568 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24260 Arch (8, 6) Cores 82                                     
20:03:21-136113 INFO     Verifying modules instalation status from /workspace/kohya_ss/requirements_linux.txt...                         
20:03:21-138357 INFO     Installing package: xformers==0.0.20 bitsandbytes==0.39.1                                                       
20:03:31-793050 WARNING  Package wrong version: accelerate 0.19.0 required 0.15.0                                                        
20:03:31-796234 INFO     Installing package: accelerate==0.15.0 tensorboard==2.12.1 tensorflow==2.12.0                                   
20:04:09-677718 INFO     Verifying modules instalation status from requirements.txt...                                                   
20:04:09-680607 INFO     Installing package: albumentations==1.3.0                                                                       
20:04:19-500479 WARNING  Package wrong version: altair 5.0.1 required 4.2.2                                                              
20:04:19-502348 INFO     Installing package: altair==4.2.2                                                                               
20:04:25-878590 INFO     Installing package: dadaptation==3.1                                                                            
20:04:31-774691 INFO     Installing package: diffusers[torch]==0.10.2                                                                    
20:04:37-916176 INFO     Installing package: easygui==0.98.3                                                                             
20:04:43-508170 WARNING  Package wrong version: einops 0.4.1 required 0.6.0                                                              
20:04:43-509964 INFO     Installing package: einops==0.6.0                                                                               
20:04:48-255784 INFO     Installing package: fairscale==0.4.13                                                                           
20:04:53-937460 WARNING  Package wrong version: gradio 3.32.0 required 3.33.1                                                            
20:04:53-940187 INFO     Installing package: gradio==3.33.1                                                                              
20:05:01-893908 INFO     Installing package: lion-pytorch==0.0.6                                                                         
20:05:07-579902 INFO     Installing package: lycoris_lora==0.1.6                                                                         
20:05:13-306755 WARNING  Package wrong version: opencv-python 4.7.0.72 required 4.7.0.68                                                 
20:05:13-308993 INFO     Installing package: opencv-python==4.7.0.68                                                                     
20:05:20-823432 INFO     Installing package: prodigyopt==1.0                                                                             
20:05:25-621152 WARNING  Package wrong version: pytorch-lightning 1.9.4 required 1.9.0                                                   
20:05:25-623956 INFO     Installing package: pytorch-lightning==1.9.0                                                                    
20:05:32-135700 WARNING  Package wrong version: rich 13.4.2 required 13.4.1                                                              
20:05:32-138510 INFO     Installing package: rich==13.4.1                                                                                
20:05:37-375464 WARNING  Package wrong version: safetensors 0.3.1 required 0.2.6                                                         
20:05:37-377971 INFO     Installing package: safetensors==0.2.6                                                                          
20:05:42-850153 INFO     Installing package: tk==0.1.0                                                                                   
20:05:48-582751 INFO     Installing package: toml==0.10.2                                                                                
20:05:54-646157 WARNING  Package wrong version: transformers 4.29.2 required 4.26.0                                                      
20:05:54-649107 INFO     Installing package: transformers==4.26.0                                                                        
20:06:09-396614 INFO     Installing package: voluptuous==0.13.1                                                                          
20:06:13-934721 INFO     Installing package: wandb==0.15.0                                                                               
20:06:27-153220 INFO     headless: False                                                                                                 
20:06:27-161002 INFO     Load CSS...                                                                                                     
Running on local URL:  http://127.0.0.1:7860


This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


```

**Comment by bmaltais** [comment]
What runpod template do you use? Torch 2.0.1? I saw it comes with cu117 so I just kept it as is instead of forcing a re-install... Is cu118 really better? I will poke at the things your tutorial does and see if I can automate the installation better... If you want we can work on making the runpod support better by updating the kohya-gui code...

**Comment by FurkanGozukara** [comment]
> What runpod template do you use? Torch 2.0.1? I saw it comes with cu117 so I just kept it as is instead of forcing a re-install... Is cu118 really better? I will poke at the things your tutorial does and see if I can automate the installation better... If you want we can work on making the runpod support better by updating the kohya-gui code...

well i am using automatic1111 web ui template

unfortunately runpod templates are not updated fast and frequently
so after each restart i tell people to execute below commands

```
apt update

apt-get install python3.10-tk

yes | apt install -y libcudnn8=8.7.0.84-1+cuda11.8 libcudnn8-dev=8.7.0.84-1+cuda11.8 --allow-change-held-packages
```

all apt commands are gone after each restart but rest stays remain

like cuda torch other things installed in venv

**Comment by rafstahelin** [comment]
It's great to use the webui template so we can test Kohya trainings straight up there. Would love to have a maintained runpod webui-Kohya template!

**Comment by bmaltais** [comment]
@FurkanGozukara is there a reason you use that auto1111 template vs other runpod templates? The runpod setup support is very rough at the moment and I wonder toward which template the setup should be best tailored.

**Comment by FurkanGozukara** [comment]
> @FurkanGozukara is there a reason you use that auto1111 template vs other runpod templates? The runpod setup support is very rough at the moment and I wonder toward which template the setup should be best tailored.

well i like it because it is like using on your pc. so i am able to cover more with 1 video. people can directly save output in web automatic template lora folder and use them directly after training with automatic1111 web ui

**Comment by bmaltais** [comment]
OK... I have been testing the runpod using auto1111 template and I think I have something that work pretty well

To try start the runpod then:

```
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
git checkout dev2
chmod +x setup-runpod.sh
./setup-runpod.sh
```

That should be it. The git checkout dev2 command is just temporary until this move to the master branch.

I kept cu117 because when I try to install cu118 there is a weird CUDA error reported... Give it a try.

**Comment by bmaltais** [comment]
Did a quick test and the PyTorch 2.0.1 appear to run better than auto1111 for the task.

**Comment by FurkanGozukara** [comment]
> Did a quick test and the PyTorch 2.0.1 appear to run better than auto1111 for the task.

well when i used latest cudnn i got double speed 

here shown in this video : https://youtu.be/c_S2kFAefTQ

ye torch 2.0.1 working

what error you got with cu118? working for me when installed properly

**Comment by rafstahelin** [comment]
installation is much faster, but i am still getting one error with accelerate:
ERROR    Error running pip: install --upgrade accelerate==0.15.0 tensorboard==2.12.1 tensorflow==2.12.0   

also ERROR    Error running pip: install --upgrade rich==13.4.1
and 
12:30:29-590140 ERROR    Error running pip: install --upgrade transformers==4.26.0

**Comment by bmaltais** [comment]
@rafstahelin what template do you use? Might be something specific to that template. Usually the bench should compartmentalize the modules...

I will do more testing today with cu118 @FurkanGozukara and report the error I am seeing

**Comment by rafstahelin** [comment]
@bmaltais 
I am using RunPod Stable Diffusion runpod/stable-diffusion :web-automatic-8.0.3

I am glad the install is a one-time command. It will make scaling of training with multiple nodes much more satisfying. Thanks for the push

**Comment by bmaltais** [comment]
@FurkanGozukara This is the error I get on the auto1111 template when running the GUI. No errors during install beside the harmless accelerate config:

```
root@14e3b1a28be1:/workspace/kohya_ss# ./gui.sh --share --headless
15:28:44-995986 INFO     Version: b0988a4 Sun Jun 25 11:21:22 2023 -0400
15:28:45-004555 INFO     nVidia toolkit detected
15:28:46-285599 INFO     Torch 2.0.1+cu118
15:28:46-301032 ERROR    Could not load torch: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0) but found runtime version (8, 5, 0). PyTorch already comes bundled with cuDNN. One option to
                         resolving this error is to ensure PyTorch can find the bundled cuDNN.one possibility is that there is a conflicting cuDNN in LD_LIBRARY_PATH.
```

There is no issues running the gui.sh in the Official Pytorch 2.0.1 template. Something is wrong with the auto1111 template. If you ever find how to fix it let me know. For now my recommendation is to stick to the Official PyTorch 2.0.1 template and forget auto1111.

**Comment by rafstahelin** [comment]
@bmaltais i tried the official PyTorch 2.0.1 but it was taking ages to install, so will keep using the auto1111 for now, hoping @FurkanGozukara will come up with something for the Cudnn issue. Thanks

**Comment by bmaltais** [comment]
Might have been the host. They both install the exact same thing. There is zero reason for pytorch 2.0.1 to take longer beside the internet/disk speed of the runpod host running your template.

**Comment by rafstahelin** [comment]
gotcha. thanks

**Comment by bmaltais** [comment]
One thing I could do is show the install progress instead of hiding it and only showing the module name... Might help see why it takes longer than expected... Maybe the download phase was taking a long time for some reasons.

**Comment by rafstahelin** [comment]
Yea, I think that could be useful, thanks for that

**Comment by ashleykleynhans** [comment]
>  For now my recommendation is to stick to the Official PyTorch 2.0.1 template and forget auto1111.

People typically prefer to use the Automatic1111 template because they can train their model/LoRA/etc using Kohya_ss and then test it using A1111 on the same pod without having to spin up multiple pods.

**Comment by bmaltais** [comment]
If you find a solution to the CUDA issue on the auto1111 when installing cu118 let me know and I will integrate it in the setup-runpod.sh code. U til a solution is found I will keep the instructions for the Official PyTorch 2.0.1 template.

**Comment by ashleykleynhans** [comment]
> If you find a solution to the CUDA issue on the auto1111 when installing cu118 let me know and I will integrate it in the setup-runpod.sh code. U til a solution is found I will keep the instructions for the Official PyTorch 2.0.1 template.

It should be solved by following Step 2 of the instructions at:
[nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04](https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/How-To-Install-Kohya-LoRA-Web-UI-On-RunPod.md#step-2)

Namely:

```bash
yes | apt install -y libcudnn8=8.7.0.84-1+cuda11.8 libcudnn8-dev=8.7.0.84-1+cuda11.8 --allow-change-held-packages
```

Because 8.5.0 is the version currently installed:

```bash
root@3c20ab2dcbcf:~# apt list -a libcudnn8-dev
Listing... Done
libcudnn8-dev/unknown 8.9.2.26-1+cuda12.1 amd64 [upgradable from: 8.5.0.96-1+cuda11.7]
libcudnn8-dev/unknown 8.9.2.26-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.9.1.23-1+cuda12.1 amd64
libcudnn8-dev/unknown 8.9.1.23-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.9.0.131-1+cuda12.1 amd64
libcudnn8-dev/unknown 8.9.0.131-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.8.1.3-1+cuda12.0 amd64
libcudnn8-dev/unknown 8.8.1.3-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.8.0.121-1+cuda12.0 amd64
libcudnn8-dev/unknown 8.8.0.121-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.7.0.84-1+cuda11.8 amd64
libcudnn8-dev/unknown 8.6.0.163-1+cuda11.8 amd64
libcudnn8-dev/unknown,now 8.5.0.96-1+cuda11.7 amd64 [installed,upgradable to: 8.9.2.26-1+cuda12.1]
```

By the way, I have also created a custom RunPod template especially for Kohya_ss, but @rafstahelin was having some issues with it, so I'm following this to get some ideas on how to improve it.

**Comment by bmaltais** [comment]
@ashleykleynhans Awesome find... I will update the runpod script to perform those actions as part of the install... this should take care of the issue!

**Comment by ashleykleynhans** [comment]
The RunPod devs have also confirmed that they will be upgrading the cudnn drivers in the `runpod/stable-diffusion:web-automatic-8.0.3` Docker image so that the changes will persist and not be lost when a pod is stopped/reset/etc.

**Comment by rafstahelin** [comment]
Oh wow nicely done Ashley

**Comment by bmaltais** [comment]
I have posted a new setup-runpod.sh in the runpod branch

You can test it with:

```
git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
git checkout runpod
./setup-runpod.sh
```

I think it should do everything discussed now... including displaying the full install output

**Comment by bmaltais** [comment]
Also... when you restart the runpod just re-run setup-runpod.sh and it will install all the missign apt packages to get up and running quickly.

**Comment by rafstahelin** [comment]
Thank you!

**Comment by ashleykleynhans** [comment]
Thank you very much @bmaltais , your hard work and amazing support are very much appreciated!

**Comment by bmaltais** [comment]
I have done a test, if you aff 7860 to the http port exposed by runpod and then start the GUI with:

`/gui.sh --listen=0.0.0.0 --headless`

You can connect using:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8c414b8e-26a2-4ae9-bebf-b7b80a7a0450)

**Comment by ashleykleynhans** [comment]
I have added the changes to my custom [Kohya_ss RunPod template](
https://runpod.io/gsc?template=51q837fywe&ref=w18gds2n), and am currently training a model successfully

**Comment by ashleykleynhans** [comment]
> I have done a test, if you add 7860 to the http port exposed by runpod and then start the GUI with:
> 
> `/gui.sh --listen=0.0.0.0 --headless`

Just remember to add the `.` in front of `/gui.sh`, ie. `./gui.sh`.

**Comment by bmaltais** [comment]
> I have added the changes to my custom [Kohya_ss RunPod template](https://runpod.io/gsc?template=51q837fywe&ref=w18gds2n), and am currently training a model successfully

I am starting it on runpod. What does it include? Auto1111? The fully installed kohya_ss repo with setup-runpod.sh already executed?

**Comment by ashleykleynhans** [comment]
> > I have added the changes to my custom [Kohya_ss RunPod template](https://runpod.io/gsc?template=51q837fywe&ref=w18gds2n), and am currently training a model successfully
> 
> I am starting it on runpod. What does it include? Auto1111? The fully installed kohya_ss repo with setup-runpod.sh already executed?

No, its only for Kohya_ss, not A1111, I have another template that includes both but still need to rebuild it.

**Comment by ashleykleynhans** [comment]
> I wonder if it would make sense to integrate the runpod docker image build process as part ok the kohya_ss repo? Or point to your repo where you publish it?

Standalone Kohya_ss template:
https://github.com/ashleykleynhans/kohya-docker

Combined template:
https://github.com/ashleykleynhans/stable-diffusion-docker

**Comment by bmaltais** [comment]
Nice... I should d reference to them in the README... I think it might help quite a few people. I think that if you can make a dockerfile image that can run both auto1111 and kohya_ss this would be killer!

**Comment by ashleykleynhans** [comment]
> Nice... I should reference to them in the README... I think it might help quite a few people. I think that if you can make a dockerfile image that can run both auto1111 and kohya_ss this would be killer!

I already have one, I am currently building it to include the latest changes and will advise once I've tested it.

**Comment by bmaltais** [comment]
OK... I have pushed the latest runpod code to the dev2 branch... will soon puch it to master

**Comment by bmaltais** [comment]
New release is pushed to master... You might want to consider adding 7860 and 7861 to the template exposed HTTP ports to allow both kohya_gui and auto1111 access directly via the runpod interface...

**Comment by ashleykleynhans** [comment]
> New release is pushed to master... You might want to consider adding 7860 and 7861 to the template exposed HTTP ports to allow both kohya_gui and auto1111 access directly via the runpod interface...

Thanks, @rafstahelin only needs to add 7860 for Kohya_ss because A1111 is already at 3000.

My custom template has A1111 at port 3000 and Kohya_ss at port 3010 through the RunPod interface.

**Comment by bmaltais** [comment]
Once it is tested I will update the readme to point the users to the new template.

**Comment by ashleykleynhans** [comment]
I've completed testing the combined template at https://runpod.io/gsc?template=ya6013lj5a&ref=w18gds2n.

I was able to train with Kohya_ss on port 3010 and run inference with A1111 on port 3000.

**Comment by bmaltais** [comment]
I was able to run the image, wow... it is a big one ;-) I noticed you do not install the tensorrt python module. Is there a reason? I saw other runpod setup were installing that... so I added it to the requirements file... but maybe it is not needed?

**Comment by rafstahelin** [comment]
@ashleykleynhans gonna test your template now

**Comment by ashleykleynhans** [comment]
> I was able to run the image, wow... it is a big one ;-) I noticed you do not install the tensorrt python module. Is there a reason? I saw other runpod setup were installing that... so I added it to the requirements file... but maybe it is not needed?

Yeah its pretty large mostly due to the SD 1.5 model and VAE being baked into the image, and also having a separate venv for A1111 and Kohya_ss.  They had some conflicting requirements which tended to cause issues when I tried to share the venv between them.

I don't actually know what purpose `tensorrt` serves to be honest, but I am actually getting really bad quality results training full Dreambooth with the latest Kohya_ss version.  I was getting amazing results a few weeks ago, and my models were better than the ones I trained with the A1111 Dreambooth extension, but since I upgraded to the latest, the preview images are VERY bad and the models are all totally unusable at every checkpoint.  I am not sure whether this is possibly because of `tensorrt` or something else.

**Comment by rafstahelin** [comment]
Same here. Did a quick test yesterday with lora and was getting bad results compared to ready good ones locally

**Comment by ashleykleynhans** [comment]
> Same here. Did a quick test yesterday with lora and was getting bad results compared to ready good ones locally

So the exact same version works perfectly under Windows?  Must be some Linux specific issue then.

**Comment by ashleykleynhans** [comment]
Kohya_ss v21.7.3 which is included in the 1.4.5 version of my template works perfectly, there is something that changed between v21.7.3 and v21.7.14 that has caused the training under RunPod to produce very bad quality results.  I will try to figure out what could be causing this.

**Comment by ashleykleynhans** [comment]
I upgraded cudnn driver to the latest (8.9) and it tested successfully.
I added the accelerate configuration file from the repo and it tested successfully.
I then upgraded the Kohya_ss code to v21.7.14.  When it started, it installed some dependencies, and then testing failed as you can see from the W&B screenshot below.

<img width="1117" alt="Screenshot 2023-06-26 at 19 29 43" src="https://github.com/bmaltais/kohya_ss/assets/886709/0d2944f9-af60-4c4d-8f26-90b2cc3f7b20">

* The image on the far right is a failed test from my newest 1.4.6 template.
* All other tests run using my 1.4.5 template, and as soon as the code was updated, the first image on the left failed again.

**Comment by ashleykleynhans** [comment]
The issue is caused by `bitsandbytes`.

Somewhere between v21.7.3 and v21.7.14 , it was upgraded from `0.35.0` to `0.39.1`.

Downgrading it back to `0.35.0` resolves the issue as shown in the screenshot from W&B below.

<img width="1165" alt="Screenshot 2023-06-26 at 19 50 57" src="https://github.com/bmaltais/kohya_ss/assets/886709/654ec261-0b85-4101-b384-5f03ac206440">

**Comment by ashleykleynhans** [comment]
I have checked the various requirements files and Windows still uses `bitsandbytes` version `0.35.0` for both Torch version 1 and Torch version 2, and Mac also uses version `0.35.0` for both amd64 and arm64, so its only the Linux requirements that have been bumped from `0.35.0` to `0.39.1` for some reason, and it doesn't appear to be working properly in Linux since RunPod is obviously Linux, so it should probably also be downgraded back to `0.35.0`, not only to resolve the broken training under Linux, but also to make it consistent with the other Operating Systems.

**Comment by bmaltais** [comment]
OK... I will rev the version back to 0.35.0

**Comment by bmaltais** [comment]
@ashleykleynhans I have been working on the Dockerfile to build the kohya_ss image. I found a couple of issues with it explaining why things are getting so huge. You install kohya_ss in /workspace... creating a 7GB layer... then you move it to /kohya creating another 7GB layer... You are much better to just install right into /kohya and skip the mv... saving 7GB in container size.

Here is a copy of my new Dockerfile:

```
# Stage 1: Base
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04 as base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Africa/Johannesburg \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=on \
    SHELL=/bin/bash \
    KOHYA_VERSION=runpod

# Install Ubuntu packages
RUN apt update && \
    apt -y upgrade && \
    apt install -y --no-install-recommends \
        apt-transport-https \
        bash \
        ca-certificates \
        curl \
        ffmpeg \
        git \
        htop \
        libcairo2-dev \
        libglib2.0-0 \
        libgl1 \
        libgoogle-perftools4 \
        libsm6 \
        libtcmalloc-minimal4 \
        libxext6 \
        libxrender1 \
        ncdu \
        net-tools \
        openssh-server \
        p7zip-full \
        pkg-config \
        psmisc \
        python3.10-venv \
        python3-tk \
        rsync \
        software-properties-common \
        unzip \
        vim \
        wget && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    update-ca-certificates && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Set Python and pip
RUN ln -s /usr/bin/python3.10 /usr/bin/python && \
    curl https://bootstrap.pypa.io/get-pip.py | python && \
    rm -f get-pip.py

# Stage 2: Install kohya_ss and python modules
FROM base as kohya_ss_setup

# Create workspace working directory
WORKDIR /

# Install Kohya_ss
ENV TZ=Africa/Johannesburg
RUN git clone https://github.com/bmaltais/kohya_ss.git

WORKDIR /kohya_ss
RUN git checkout $KOHYA_VERSION && \
    python3 -m venv --system-site-packages venv && \
    . venv/bin/activate && \
    pip3 install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 && \
    pip3 install xformers==0.0.20 bitsandbytes==0.35.0 accelerate==0.15.0 tensorboard==2.12.1 tensorflow==2.12.0 && \
    pip3 install -r requirements.txt && \
    # Fix Tensorboard
    pip3 uninstall -y tensorboard tb-nightly && \
    pip3 install tensorboard tensorflow && \
    deactivate

# # Stage 3: Final setup
# FROM base as final
# WORKDIR /workspace

# COPY --from=kohya_ss_setup /workspace/kohya_ss /kohya_ss

# Install runpodctl
RUN wget https://github.com/runpod/runpodctl/releases/download/v1.10.0/runpodctl-linux-amd -O runpodctl && \
    chmod a+x runpodctl && \
    mv runpodctl /usr/local/bin

# Install Jupyter
RUN . venv/bin/activate && \
    pip3 install \
        jupyterlab \
        ipywidgets \
        jupyter-archive \
        jupyter_contrib_nbextensions \
        gdown && \
    jupyter contrib nbextension install --user && \
    jupyter nbextension enable --py widgetsnbextension && \
    deactivate

WORKDIR /workspace

# Copy startup script and config file
COPY start.sh /start.sh
RUN chmod a+x /start.sh
COPY accelerate.yaml /accelerate.yaml

# Start the container
SHELL ["/bin/bash", "--login", "-c"]
CMD [ "/start.sh" ]
```

**Comment by bmaltais** [comment]
Also, the rsync command in start.sh was causing bad results so I fixed it also

`rsync -au /kohya_ss/ /workspace/kohya_ss/`

**Comment by ashleykleynhans** [comment]
@bmaltais thanks for the tips for improving the Dockerfile and rsync.
One of the RunPod devs reviewed my Dockerfile previously when I asked them to help me to reduce the size and they didn't offer this advice 🙈 .
I also copied the rsync command from one of their Dockerfile images, but people have been having problems with rsync and Network Volumes so its not surprising that there is an issue with the command, thanks for helping to fix it 👍

**Comment by ashleykleynhans** [comment]
@bmaltais the problem with creating the venv in `/kohya_ss` instead of `/workspace/kohya_ss` causes the venv not to work anymore when rsync copies the venv to `/workspace`.  I don't think its possible to move a venv, it usually has to be recreated.

I will try and work around this by using a symbolic link because its not ideal for the image to be twice its size just because of this.

**Comment by bmaltais** [comment]
Humm... this can be an issue... I have not observed a side effect. I don't know if there is any hardcoded path in the venv itself... would be strange... but maybe... I will check.

**Comment by ashleykleynhans** [comment]
It is affected though as can be seen here:

<img width="478" alt="Screenshot 2023-06-27 at 14 14 59" src="https://github.com/bmaltais/kohya_ss/assets/886709/d682603d-fa3f-45e9-a529-179afcab909a">

There are hacky work-arounds on Stackoverlow, but didn't really see a solution that I liked yet.

**Comment by ashleykleynhans** [comment]
I guess a sed command can be used to fix all this hard-coding:

```
testing/venv/bin on ☁️  (us-east-2) on ☁️  ashley.kleynhans@gmail.com took 25s
❯ grep testing *
activate:VIRTUAL_ENV="/Users/ashley/testing/venv"
activate.csh:setenv VIRTUAL_ENV "/Users/ashley/testing/venv"
activate.fish:set -gx VIRTUAL_ENV "/Users/ashley/testing/venv"
pip:#!/Users/ashley/testing/venv/bin/python3
pip3:#!/Users/ashley/testing/venv/bin/python3
pip3.9:#!/Users/ashley/testing/venv/bin/python3
```

**Comment by ashleykleynhans** [comment]
Thanks for the help @bmaltais , I have rebuilt both my images and applied the fix_venv.sh script to fix the venvs, and the combined image is almost 10GB smaller 🥳

**Comment by bmaltais** [comment]
Yeah... this is an issue indeed... I did not realise venv was hardcoding path like this... oh well... I guess this fix_venv.sh is needed then...

**Comment by ashleykleynhans** [comment]
Oops, had to fix the script because if a container was stopped and started again, it would try to fix the venv again and again and again on the persistent volume which completely broke everything.

I changed it as follows:

```
#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <OLD_VENV> <NEW_VENV>"
  echo "   eg: $0 /home/ubuntu/test/venv /home/ubuntu/test/venv2"
  exit 1
fi

OLD_PATH=${1}
NEW_PATH=${2}

if [ ! -f ${NEW_PATH}/fixed ]; then
  cd ${NEW_PATH}/bin
  sed -i "s|${OLD_PATH}|${NEW_PATH}|g" *
  touch ${NEW_PATH}/fixed
fi
```

**Comment by GisRookie** [comment]
> 

i meet this error, how can i resolve this?

**Comment by ashleykleynhans** [comment]
> > 
> 
> i meet this error, how can i resolve this?

What error? This issue is closed as the initial problem is now resolved.  Log a new issue if you have a new error.
