### ISSUE TITLE
TensorRT installing regardless of GPU manufacturer.

### ISSUE THREAD

**Issue by Blank256** [bmaltais/kohya_ss#1063]
I have an AMD graphics card and thus can not use CUDA. Is there already a way to disable TensorRT from installing? Afaik TensorRT is for NVIDIA graphics cards.

**Comment by bmaltais** [comment]
Depend... I don't think it is part of the requirements... So it must be installed by one of the module as a requirement.

If you come up with a requirement file specific to an AMD GPU it might be possible to use that instead.

**Comment by Blank256** [comment]
Seems like someone else caught the issue on line 59 in gui.sh. I guess it was after I cloned the repository.
