### ISSUE TITLE
died with <Signals.SIGKILL: 9>. Is this problem due to my lack of RAM?

### ISSUE THREAD

**Issue by HJ909** [bmaltais/kohya_ss#1065]
Hi I'm a very newbie at coding. Could you help me some?
I tried to train model, but this error code came up to me.

died with <Signals.SIGKILL: 9>

I tried to find out the reason of this error, and some of guide said lack of Memory.
But as I use 16GB Ram, and I think I have enough memory, 8.4GB, trying to train model.

Below is the full error code & traceback code.
I'll really thank you if you give me any advice.
thx.

---
CalledProcessError: Command '['/mnt/c/Users/andre/Desktop/Video/Lora/kohya_ss/venv/bin/python', 'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=/mnt/c/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors',
'--train_data_dir=/mnt/c/Users/andre/Desktop/Video/Lora/00.Lora_model/00.jww/img', '--resolution=512,512',
'--output_dir=/mnt/c/Users/andre/Desktop/Video/Lora/00.Lora_model/00.jww/model',
'--logging_dir=/mnt/c/Users/andre/Desktop/Video/Lora/00.Lora_model/00.jww/log', '--network_alpha=1', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=chillout_jww',
'--lr_scheduler_num_cycles=10', '--learning_rate=0.0001', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=125',
'--train_batch_size=1', '--max_train_steps=2500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16',
'--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers',
'--bucket_no_upscale']' died with <Signals.SIGKILL: 9>.
-----

and above this, by the recent call,

-----

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/c/Users/andre/Desktop/Video/Lora/kohya_ss/venv/bin/accelerate:8 in <module>                 │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /mnt/c/Users/andre/Desktop/Video/Lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/comm │
│ ands/accelerate_cli.py:45 in main                                                                │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /mnt/c/Users/andre/Desktop/Video/Lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/comm │
│ ands/launch.py:918 in launch_command                                                             │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ /mnt/c/Users/andre/Desktop/Video/Lora/kohya_ss/venv/lib/python3.10/site-packages/accelerate/comm │
│ ands/launch.py:580 in simple_launcher                                                            │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

-------

**Comment by kieranxsomer** [comment]
Are you using it on local, rented gpu or colab? 
I reserached it via this on stack:
https://stackoverflow.com/questions/16338884/what-does-exited-abnormally-with-signal-9-killed-9-mean
"33

It means that the application received a signal. Some signal could be handled by the applications, others, not. Signal 9 means that the application needs to be killed, it is not handled by the process, but by the Linux scheduler. The signal to terminate the process that is handled by the process is SIGTERM(15), but, if the process doesn't handle it property, then the process continues to live."

Likely you ran into a space that was buggy or ram overuse -- sometimes colab kills processess that are taking too much stuff - i've had killed processes even on runpod for other content

**Comment by HJ909** [comment]
I am using local gpu. btw I got clear by stopping processing on wsl, but on window cmd :) Thx!
