### ISSUE TITLE
RuntimeError, What can I do? Please help

### ISSUE THREAD

**Issue by fat111cat** [bmaltais/kohya_ss#1068]
19:21:42-339439 INFO     Start training LoRA LyCORIS/LoCon ...
19:21:42-340410 INFO     Valid image folder names found in: G:/Model/Ikeda_chitose\img
19:21:42-342404 INFO     Valid image folder names found in: G:/Model/Ikeda_chitose\reg
19:21:42-343401 INFO     Folder 50_ikeda chitose 1girl: 15 images found
19:21:42-344399 INFO     Folder 50_ikeda chitose 1girl: 750 steps
19:21:42-345397 INFO     Folder 80_Ikeda chitose 1girl: 15 images found
19:21:42-346394 INFO     Folder 80_Ikeda chitose 1girl: 1200 steps
19:21:42-347392 INFO     [94mRegularisation images are used... Will double the number of steps required...[0m
19:21:42-348388 INFO     Total steps: 1950
19:21:42-349410 INFO     Train batch size: 2
19:21:42-350383 INFO     Gradient accumulation steps: 1
19:21:42-351380 INFO     Epoch: 4
19:21:42-352377 INFO     Regulatization factor: 2
19:21:42-353376 INFO     max_train_steps (1950 / 2 / 1 * 4 * 2) = 7800
19:21:42-354372 INFO     stop_text_encoder_training = 0
19:21:42-356367 INFO     lr_warmup_steps = 0
19:21:42-357364 INFO     accelerate launch --num_cpu_threads_per_process=2 "train_network.py"
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="G:/Model/Ikeda_chitose\img" --reg_data_dir="G:/Model/Ikeda_chitose\reg"
                         --resolution="768,768" --output_dir="G:/Model/Ikeda_chitose\model"
                         --logging_dir="G:/Model/Ikeda_chitose\log" --network_alpha="4" --save_model_as=safetensors
                         --network_module=lycoris.kohya --network_args "conv_dim=18" "conv_alpha=1" "algo=lora"
                         --text_encoder_lr=0.4 --unet_lr=0.4 --network_dim=48 --output_name="Ikeda_chitose_LoLA"
                         --lr_scheduler_num_cycles="4" --learning_rate="1.0" --lr_scheduler="constant"
                         --train_batch_size="2" --max_train_steps="7800" --save_every_n_epochs="1"
                         --mixed_precision="bf16" --save_precision="bf16" --caption_extension=".txt" --cache_latents
                         --optimizer_type="DAdaptAdam" --optimizer_args decouple=True --max_data_loader_n_workers="1"
                         --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale --sample_sampler=euler_a
                         --sample_prompts="G:/Model/Ikeda_chitose\model\sample\prompt.txt" --sample_every_n_epochs="1"
[19:21:48] WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.                     redirects.py:27
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\t1019\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\t1019\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:909 in launch_command           │
│                                                                                                  │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   907 │   │   multi_gpu_launcher(args)                                                           │
│   908 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                                           │
│   910 │   elif args.tpu and not args.cpu:                                                        │
│   911 │   │   if args.tpu_use_cluster:                                                           │
│   912 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:604 in multi_gpu_launcher       │
│                                                                                                  │
│   601 │   )                                                                                      │
│   602 │   with patch_environment(**current_env):                                                 │
│   603 │   │   try:                                                                               │
│ ❱ 604 │   │   │   distrib_run.run(args)                                                          │
│   605 │   │   except Exception:                                                                  │
│   606 │   │   │   if is_rich_available() and debug:                                              │
│   607 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\run.py:785 in run                           │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:134 in __call__             │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:241 in launch_agent         │
│                                                                                                  │
│   238 │   try:                                                                                   │
│   239 │   │   metrics.initialize_metrics(metrics.MetricsConfig(config.metrics_cfg))              │
│   240 │   │                                                                                      │
│ ❱ 241 │   │   result = agent.run()                                                               │
│   242 │   │   # records that agent.run() has succeeded NOT that workers have succeeded           │
│   243 │   │   events.record(agent.get_event_succeeded())                                         │
│   244                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py:129 in wrapper       │
│                                                                                                  │
│   126 │   │   │   key = _get_metric_name(f)                                                      │
│   127 │   │   │   try:                                                                           │
│   128 │   │   │   │   start = time.time()                                                        │
│ ❱ 129 │   │   │   │   result = f(*args, **kwargs)                                                │
│   130 │   │   │   │   put_metric(f"{key}.success", 1, group)                                     │
│   131 │   │   │   except Exception:                                                              │
│   132 │   │   │   │   put_metric(f"{key}.failure", 1, group)                                     │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py:723 in run      │
│                                                                                                  │
│   720 │   │   start_time = time.monotonic()                                                      │
│   721 │   │   shutdown_called: bool = False                                                      │
│   722 │   │   try:                                                                               │
│ ❱ 723 │   │   │   result = self._invoke_run(role)                                                │
│   724 │   │   │   self._total_execution_time = int(time.monotonic() - start_time)                │
│   725 │   │   │   self._record_metrics(result)                                                   │
│   726 │   │   │   self._record_worker_events(result)                                             │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py:858 in          │
│ _invoke_run                                                                                      │
│                                                                                                  │
│   855 │   │   │   f"[{role}] starting workers for entrypoint: {spec.get_entrypoint_name()}"      │
│   856 │   │   )                                                                                  │
│   857 │   │                                                                                      │
│ ❱ 858 │   │   self._initialize_workers(self._worker_group)                                       │
│   859 │   │   monitor_interval = spec.monitor_interval                                           │
│   860 │   │   rdzv_handler = spec.rdzv_handler                                                   │
│   861                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py:129 in wrapper       │
│                                                                                                  │
│   126 │   │   │   key = _get_metric_name(f)                                                      │
│   127 │   │   │   try:                                                                           │
│   128 │   │   │   │   start = time.time()                                                        │
│ ❱ 129 │   │   │   │   result = f(*args, **kwargs)                                                │
│   130 │   │   │   │   put_metric(f"{key}.success", 1, group)                                     │
│   131 │   │   │   except Exception:                                                              │
│   132 │   │   │   │   put_metric(f"{key}.failure", 1, group)                                     │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py:692 in          │
│ _initialize_workers                                                                              │
│                                                                                                  │
│   689 │   │   # workers on different nodes to fail on a collective op before waiting             │
│   690 │   │   # on the rdzv barrier, this way we ensure that nodes enter rdzv                    │
│   691 │   │   # at around the same time and reduce false positive rdzv timeout errors            │
│ ❱ 692 │   │   self._rendezvous(worker_group)                                                     │
│   693 │   │                                                                                      │
│   694 │   │   log.info(f"[{role}] Starting worker group")                                        │
│   695 │   │   worker_ids = self._start_workers(worker_group)                                     │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\metrics\api.py:129 in wrapper       │
│                                                                                                  │
│   126 │   │   │   key = _get_metric_name(f)                                                      │
│   127 │   │   │   try:                                                                           │
│   128 │   │   │   │   start = time.time()                                                        │
│ ❱ 129 │   │   │   │   result = f(*args, **kwargs)                                                │
│   130 │   │   │   │   put_metric(f"{key}.success", 1, group)                                     │
│   131 │   │   │   except Exception:                                                              │
│   132 │   │   │   │   put_metric(f"{key}.failure", 1, group)                                     │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\agent\server\api.py:546 in          │
│ _rendezvous                                                                                      │
│                                                                                                  │
│   543 │   │                                                                                      │
│   544 │   │   spec = worker_group.spec                                                           │
│   545 │   │                                                                                      │
│ ❱ 546 │   │   store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()          │
│   547 │   │   self._store = store                                                                │
│   548 │   │                                                                                      │
│   549 │   │   workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)     │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py │
│ :55 in next_rendezvous                                                                           │
│                                                                                                  │
│    52 │   │   log.info("Creating TCPStore as the c10d::Store implementation")                    │
│    53 │   │   if not self._store:                                                                │
│    54 │   │   │   is_master = self.rank == 0                                                     │
│ ❱  55 │   │   │   self._store = TCPStore(  # type: ignore[call-arg]                              │
│    56 │   │   │   │   self.master_addr,                                                          │
│    57 │   │   │   │   self.master_port,                                                          │
│    58 │   │   │   │   self.world_size,                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
**RuntimeError: unmatched '}' in format string**

Please help me, Thanks.

**Comment by kieranxsomer** [comment]
Clearly it's windows, but beyond that it'd be nice to know the hardware but the format string isn't a hardware issue it's a } issue - it may have been something tehy forgot to type somewhere
