### ISSUE TITLE
Error running pip: install --upgrade rich

### ISSUE THREAD

**Issue by NMoebius** [bmaltais/kohya_ss#1069]
**Describe the bug**
When trying to run ".\setup.bat" always get into the error below, and I've trying to "python -m pip install rich" and "pip install rich --upgrade", but they still not work. Thanks.

**To Reproduce**
Error running pip: install --upgrade rich
Traceback (most recent call last):
  File "G:\SDRelated\kohya_ss\setup\setup_windows.py", line 201, in <module>
    setup_common.setup_logging()
  File "G:\SDRelated\kohya_ss\setup\setup_common.py", line 22, in setup_logging
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'

**Comment by bmaltais** [comment]
I am unable to reproduce the error on ym system... Make sure you have installed python 3.10.9 and that you select the option to add Python to the 'PATH' environment variable. Otherwise I have no idea why it is complaining about rich not being installed.

Also, try deleting the `venv` folder and re-run setup.bat

**Comment by NMoebius** [comment]
> I am unable to reproduce the error on ym system... Make sure you have installed python 3.10.9 and that you select the option to add Python to the 'PATH' environment variable. Otherwise I have no idea why it is complaining about rich not being installed.
> 
> Also, try deleting the `venv` folder and re-run setup.bat

Thank you for replay. SD could run successfully, so I thought I've added python ot the "PATH". Later I'll try delete `venv` folder and re-run it.

**Comment by wanderxuhq** [comment]
Just as a supplement, hope I did not disturb you.
I faced similar issue related to rich module. I was using tsinghua as my pip mirror, after I chaged to default mirror (try `pip config set global.index-url  https://pypi.org/simple`), it works.
Maybe some modules not synced to mirrors, if you faced same issue and not using default mirror, please try in this way.

**Comment by DragonQuix** [comment]
> Just as a supplement, hope I did not disturb you. I faced similar issue related to rich module. I was using tsinghua as my pip mirror, after I chaged to default mirror (try `pip config set global.index-url https://pypi.org/simple`), it works. Maybe some modules not synced to mirrors, if you faced same issue and not using default mirror, please try in this way.

This solve my problem. Thank you!
