### ISSUE TITLE
Torch 2 version installation is giving error

### ISSUE THREAD

**Issue by utsav1232002** [bmaltais/kohya_ss#1071]
tried installing the torch 2 version multiple times; it keeps giving error. torch 1 version installs fine.

**Comment by bmaltais** [comment]
What is the error with torch 2? Did you delete the bench before trying to install it?

**Comment by utsav1232002** [comment]
Error running pip: install --upgrade torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url

was trying fresh install. this error occurred. in case of torch 1 no such error occurs and the installation completes ok.

**Comment by bmaltais** [comment]
Hard to tell why torch 2 does not want to install on your system... you might have to manually install it to discover the true error:

```
.\venv\scripts\activate.bat
pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
```

Then you will see what is going on

**Comment by utsav1232002** [comment]
![Screenshot 2023-06-26 022825](https://github.com/bmaltais/kohya_ss/assets/122025114/1ad713cd-be29-4b68-a233-46aa36e279b2)
 this is what happened while i tried running the command in the main directory.

**Comment by bmaltais** [comment]
Look like one of the files that got downloaded is corrupted. You will need to delete the pip cache and run setup again.

**Comment by utsav1232002** [comment]
thanks a lot.....it solved it!!!! have a great day ahead!!!!
