### ISSUE TITLE
Installation breaks on rich.theme when trying to setup the venv

### ISSUE THREAD

**Issue by Beliriel** [bmaltais/kohya_ss#1073]
I run Win10 and installed the redistributables. But the installation stops at rich.theme (Possible duplicate of [this issue](https://github.com/bmaltais/kohya_ss/issues/1040))

Due to python conflicts I'm running kohya in it's own anaconda environment

```
(base) C:\random\path>conda activate kohya_ss

(kohya_ss) C:\random\path>cd /d F:\AI

(kohya_ss) F:\AI>git clone https://github.com/bmaltais/kohya_ss.git
Cloning into 'kohya_ss'...
remote: Enumerating objects: 8037, done.
remote: Counting objects: 100% (2431/2431), done.
remote: Compressing objects: 100% (357/357), done.
remote: Total 8037 (delta 2163), reused 2272 (delta 2071), pack-reused 5606
Receiving objects: 100% (8037/8037), 5.87 MiB | 9.32 MiB/s, done.
Resolving deltas: 100% (5575/5575), done.
Updating files: 100% (196/196), done.

(kohya_ss) F:\AI>cd kohya_ss

(kohya_ss) F:\AI\kohya_ss>python --version
Python 3.10.9

(kohya_ss) F:\AI\kohya_ss>setup.bat
Creating venv...
Traceback (most recent call last):
  File "F:\AI\kohya_ss\setup\setup_windows.py", line 201, in <module>
    setup_common.setup_logging()
  File "F:\AI\kohya_ss\setup\setup_common.py", line 22, in setup_logging
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
(kohya_ss) F:\AI\kohya_ss>
```

I'm running it locally on my own machine with an RTX3090 and AMD CPU Ryzen9.  
Any pointers?

**Comment by bmaltais** [comment]
Might be related to the fact that you run the bench inside an activated conda env. Try not activating conda and see if it help...

**Comment by kieranxsomer** [comment]
> I run Win10 and installed the redistributables. But the installation stops at rich.theme (Possible duplicate of [this issue](https://github.com/bmaltais/kohya_ss/issues/1040))
> 
> Due to python conflicts I'm running kohya in it's own anaconda environment
> 
> ```
> (base) C:\random\path>conda activate kohya_ss
> 
> (kohya_ss) C:\random\path>cd /d F:\AI
> 
> (kohya_ss) F:\AI>git clone https://github.com/bmaltais/kohya_ss.git
> Cloning into 'kohya_ss'...
> remote: Enumerating objects: 8037, done.
> remote: Counting objects: 100% (2431/2431), done.
> remote: Compressing objects: 100% (357/357), done.
> remote: Total 8037 (delta 2163), reused 2272 (delta 2071), pack-reused 5606
> Receiving objects: 100% (8037/8037), 5.87 MiB | 9.32 MiB/s, done.
> Resolving deltas: 100% (5575/5575), done.
> Updating files: 100% (196/196), done.
> 
> (kohya_ss) F:\AI>cd kohya_ss
> 
> (kohya_ss) F:\AI\kohya_ss>python --version
> Python 3.10.9
> 
> (kohya_ss) F:\AI\kohya_ss>setup.bat
> Creating venv...
> Traceback (most recent call last):
>   File "F:\AI\kohya_ss\setup\setup_windows.py", line 201, in <module>
>     setup_common.setup_logging()
>   File "F:\AI\kohya_ss\setup\setup_common.py", line 22, in setup_logging
>     from rich.theme import Theme
> ModuleNotFoundError: No module named 'rich'
> (kohya_ss) F:\AI\kohya_ss>
> ```
> 
> I'm running it locally on my own machine with an RTX3090 and AMD CPU Ryzen9. Any pointers?

Mine wasn't on windows, lol - Mine was running vast AI setup XD i'll be going in and testing it again soon just--- XD i gotta wake up first!

**Comment by moderatorman** [comment]
I appear to be having a similar issue. It's with the gui.sh script, but for the same reason w/ the same missing module.

Using Linux Mint with an RTX3050 and a Ryzen 5 3600.

WSL env path not configured because I'm not using WSL. I wasn't sure if there was somewhere I was supposed to get those for Linux or what, so I just left it.

<details><summary>Commands/Logs/Traceback</summary>
<p>

```
moderator_man@modman-mint:/opt/kohya_ss$ sudo bash setup.sh
[sudo] password for moderator_man:             
Attempting to clone https://github.com/bmaltais/kohya_ss.git.
git repo detected. Attempting to update repository instead.
Updating: https://github.com/bmaltais/kohya_ss.git
remote: Enumerating objects: 970, done.
remote: Counting objects: 100% (761/761), done.
remote: Compressing objects: 100% (269/269), done.
remote: Total 970 (delta 558), reused 665 (delta 488), pack-reused 209
Receiving objects: 100% (970/970), 890.33 KiB | 8.40 MiB/s, done.
Resolving deltas: 100% (625/625), completed with 28 local objects.
From https://github.com/bmaltais/kohya_ss
 * branch            master     -> FETCH_HEAD
Already on 'master'
Installing Python TK if not found on the system.
Ubuntu detected.
Python TK found! Skipping install!
Switching to virtual Python environment.
Checking for pip updates before Python operations.
Installing python dependencies. This could take a few minutes as it downloads files.
If this operation ever runs too long, you can rerun this script in verbose mode to check.
ERROR: xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl is not a supported wheel on this platform.
ERROR: Package 'library' requires a different Python: 3.8.10 not in '<3.11,>=3.9'
Removing the temp requirements file.
Exiting Python virtual environment.
Setup finished! Run ./gui.sh to start.
Please note if you'd like to expose your public server you need to run ./gui.sh --share
moderator_man@modman-mint:/opt/kohya_ss$ ./gui.sh
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.
 
If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/
 
Traceback (most recent call last):
  File "/opt/kohya_ss/setup/validate_requirements.py", line 19, in <module>
    from library.custom_logging import setup_logging
  File "/opt/kohya_ss/library/custom_logging.py", line 6, in <module>
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
```

</p>
</details>

**Comment by MichaelLeeHobbs** [comment]
pip install rich
Which led to No module named 'torch'
pip install torch

Seems to be working now
