### ISSUE TITLE
Training not working

### ISSUE THREAD

**Issue by bluray2** [bmaltais/kohya_ss#1076]
Too much letters so adding image version and .txt
Python installed - 3.10.9
Windows 11
RTX 4070, Ryzen 7 7700x
![image](https://github.com/bmaltais/kohya_ss/assets/64377769/707f7c0e-ca54-4bfa-9c84-49690683660d)
![image](https://github.com/bmaltais/kohya_ss/assets/64377769/4c277982-a7a5-47c8-840b-9032df49029e)
[Logs.txt](https://github.com/bmaltais/kohya_ss/files/11865144/Logs.txt)
![1](https://github.com/bmaltais/kohya_ss/assets/64377769/66cf0104-6926-4531-b229-c7e03bd2182b)
![2](https://github.com/bmaltais/kohya_ss/assets/64377769/bddfd09c-aab3-41b2-b332-c2517f95b19d)
![3](https://github.com/bmaltais/kohya_ss/assets/64377769/586fd4a3-feb7-4c48-8a87-ccb0cceec44e)
![4](https://github.com/bmaltais/kohya_ss/assets/64377769/d357af62-a06f-4b3b-ade4-a47867d55727)

**Comment by ruiboy1919** [comment]
Did you type .txt under "Caption Extension" in the Training Parameters tab?

**Comment by AllelujahNightingale** [comment]
I figured out my problem. I had a save state folder location set with no last save states that it was trying to pull from. removed the folder location and it started working. So that was my issue at least so my recommendation is check for any settings that might not be needed.

**Comment by bluray2** [comment]
> I figured out my problem. I had a save state folder location set with no last save states that it was trying to pull from. removed the folder location and it started working. So that was my issue at least so my recommendation is check for any settings that might not be needed.

Can you explain?

**Comment by AllelujahNightingale** [comment]
> > I figured out my problem. I had a save state folder location set with no last save states that it was trying to pull from. removed the folder location and it started working. So that was my issue at least so my recommendation is check for any settings that might not be needed.
> 
> Can you explain?

![image](https://github.com/bmaltais/kohya_ss/assets/83302597/3ea9066a-c860-45e4-8c7d-dfffd92c9bc1)
So this setting here where the file location is set, I had set it to a folder where it was trying to look for something that didnt exist. Which was throwing a similar error to the one you were getting. your issue might be different, however, so you might want to double check your training parameters again and see if something isnt working like it should.

**Comment by bluray2** [comment]
> > > I figured out my problem. I had a save state folder location set with no last save states that it was trying to pull from. removed the folder location and it started working. So that was my issue at least so my recommendation is check for any settings that might not be needed.
> > 
> > 
> > Can you explain?
> 
> ![image](https://user-images.githubusercontent.com/83302597/248852146-3ea9066a-c860-45e4-8c7d-dfffd92c9bc1.png) So this setting here where the file location is set, I had set it to a folder where it was trying to look for something that didnt exist. Which was throwing a similar error to the one you were getting. your issue might be different, however, so you might want to double check your training parameters again and see if something isnt working like it should.

i ignored that path, just left unfilled

**Comment by Stnf78** [comment]
I have the same problem, however the save training state was unchecked from the start...

**Comment by bluray2** [comment]
> I have the same problem, however the save training state was unchecked from the start...

Well, i reinstalled absolutely everything started from Stable Diffusion Automatic1111 right into the desktop. Chose Torch 1. instead of Torch 2 also installed Python 3.10.6 (read somewhere that its last version that supporting torch) 

Tried to make a model, made good descriptions with WD1.4 and started. Well, i just gonna attach description, one of 25 original arts i downloaded, and what i get with standart checkpoint and Anything v5 checkpoint using same prompt for this image that WD1.4 generated.
Thats one of originals
![photo_2023-06-27_02-19-47](https://github.com/bmaltais/kohya_ss/assets/64377769/f15a7b6f-527e-4632-b64c-352cea5c1b74)
That is standart checkpoint
![photo_2023-06-27_02-28-53](https://github.com/bmaltais/kohya_ss/assets/64377769/d818f02d-21b3-465b-a09c-01a091647fa2)
That is Anyhthing V5
![photo_2023-06-27_02-34-11](https://github.com/bmaltais/kohya_ss/assets/64377769/b5c42275-0f68-4c70-97fc-0aa80a7503ea)
Im not even sure my model was that useful....

**Comment by bluray2** [comment]
> > I have the same problem, however the save training state was unchecked from the start...
> 
> Well, i reinstalled absolutely everything started from Stable Diffusion Automatic1111 right into the desktop. Chose Torch 1. instead of Torch 2 also installed Python 3.10.6 (read somewhere that its last version that supporting torch)
> 
> Tried to make a model, made good descriptions with WD1.4 and started. Well, i just gonna attach description, one of 25 original arts i downloaded, and what i get with standart checkpoint and Anything v5 checkpoint using same prompt for this image that WD1.4 generated. Thats one of originals ![photo_2023-06-27_02-19-47](https://user-images.githubusercontent.com/64377769/248998708-f15a7b6f-527e-4632-b64c-352cea5c1b74.jpg) That is standart checkpoint ![photo_2023-06-27_02-28-53](https://user-images.githubusercontent.com/64377769/248998770-d818f02d-21b3-465b-a09c-01a091647fa2.jpg) That is Anyhthing V5 ![photo_2023-06-27_02-34-11](https://user-images.githubusercontent.com/64377769/248998803-b5c42275-0f68-4c70-97fc-0aa80a7503ea.jpg) Im not even sure my model was that useful.... I not resized any of images before start to make model but I checkmarked thing that ignores sizes. Also gonna tell that this is the one of the best pictures I attached....
