### ISSUE TITLE
I have a problem with training on MacStudio with M2Max

### ISSUE THREAD

**Issue by es1o** [bmaltais/kohya_ss#1077]
I have an error when I try train:

```
RuntimeError: Input type (MPSHalfType) and weight type (MPSFloatType) should be the same
```

I run gut with command:
```
./gui.sh --listen 127.0.0.1 --server_port 7860 --inbrowser --headless
```

How can I solve this issue?

**Comment by bmaltais** [comment]
Macos support is not really working. If someone ever find how to make it work I could update the solution... but I don't have the patience to make Macos work for the solution... not the needed hardware.

**Comment by kieranxsomer** [comment]
I'm ok with 0 macOS for now only cause i'm running a fairly potato machine compared to some - but i still havei t installed from a while back and the only issue i run into is the AMD issue - and that's ok XD i can tag stuff, i can thwack lyco to checkpoints i just can't train locally - but i woudln't dare try with only 8gb vram and 8 normal ram XD
