### ISSUE TITLE
I can't start training at all... just installed an older version of kohya

### ISSUE THREAD

**Issue by Stnf78** [bmaltais/kohya_ss#1078]
This is the log

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 27/27 [00:00<00:00, 3173.14it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 20
bucket 1: resolution (448, 448), count: 260
bucket 2: resolution (448, 512), count: 100
bucket 3: resolution (512, 384), count: 40
bucket 4: resolution (512, 448), count: 120
mean ar error (without repeats): 0.03247852223586732
prepare accelerator
C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: D:/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
  0%|                                                                                           | 0/27 [00:01<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\my_user\Documents\GitHub\kohya_ss\train_db.py:477 in <module>                             │
│                                                                                                  │
│   474 │   args = parser.parse_args()                                                             │
│   475 │   args = train_util.read_config_from_file(args, parser)                                  │
│   476 │                                                                                          │
│ ❱ 477 │   train(args)                                                                            │
│   478                                                                                            │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\train_db.py:128 in train                                │
│                                                                                                  │
│   125 │   │   vae.requires_grad_(False)                                                          │
│   126 │   │   vae.eval()                                                                         │
│   127 │   │   with torch.no_grad():                                                              │
│ ❱ 128 │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_laten   │
│   129 │   │   vae.to("cpu")                                                                      │
│   130 │   │   if torch.cuda.is_available():                                                      │
│   131 │   │   │   torch.cuda.empty_cache()                                                       │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\library\train_util.py:1399 in cache_latents             │
│                                                                                                  │
│   1396 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1397 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1398 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1399 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1400 │                                                                                         │
│   1401 │   def is_latent_cacheable(self) -> bool:                                                │
│   1402 │   │   return all([dataset.is_latent_cacheable() for dataset in self.datasets])          │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\library\train_util.py:812 in cache_latents              │
│                                                                                                  │
│    809 │   │   │   img_tensors = torch.stack(images, dim=0)                                      │
│    810 │   │   │   img_tensors = img_tensors.to(device=vae.device, dtype=vae.dtype)              │
│    811 │   │   │                                                                                 │
│ ❱  812 │   │   │   latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")              │
│    813 │   │   │                                                                                 │
│    814 │   │   │   for info, latent in zip(batch, latents):                                      │
│    815 │   │   │   │   if cache_to_disk:                                                         │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py:566 in   │
│ encode                                                                                           │
│                                                                                                  │
│   563 │   │   self.use_slicing = False                                                           │
│   564 │                                                                                          │
│   565 │   def encode(self, x: torch.FloatTensor, return_dict: bool = True) -> AutoencoderKLOut   │
│ ❱ 566 │   │   h = self.encoder(x)                                                                │
│   567 │   │   moments = self.quant_conv(h)                                                       │
│   568 │   │   posterior = DiagonalGaussianDistribution(moments)                                  │
│   569                                                                                            │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130  │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py:130 in   │
│ forward                                                                                          │
│                                                                                                  │
│   127 │                                                                                          │
│   128 │   def forward(self, x):                                                                  │
│   129 │   │   sample = x                                                                         │
│ ❱ 130 │   │   sample = self.conv_in(sample)                                                      │
│   131 │   │                                                                                      │
│   132 │   │   # down                                                                             │
│   133 │   │   for down_block in self.down_blocks:                                                │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130  │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:457 in  │
│ forward                                                                                          │
│                                                                                                  │
│    454 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    455 │                                                                                         │
│    456 │   def forward(self, input: Tensor) -> Tensor:                                           │
│ ❱  457 │   │   return self._conv_forward(input, self.weight, self.bias)                          │
│    458                                                                                           │
│    459 class Conv3d(_ConvNd):                                                                    │
│    460 │   __doc__ = r"""Applies a 3D convolution over an input signal composed of several inpu  │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:453 in  │
│ _conv_forward                                                                                    │
│                                                                                                  │
│    450 │   │   │   return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │
│    451 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │
│    452 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                         │
│ ❱  453 │   │   return F.conv2d(input, weight, bias, self.stride,                                 │
│    454 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    455 │                                                                                         │
│    456 │   def forward(self, input: Tensor) -> Tensor:                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\my_user\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\my_user\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_c │
│ li.py:45 in main                                                                                 │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:92 │
│ 3 in launch_command                                                                              │
│                                                                                                  │
│   920 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   921 │   │   sagemaker_launcher(defaults, args)                                                 │
│   922 │   else:                                                                                  │
│ ❱ 923 │   │   simple_launcher(args)                                                              │
│   924                                                                                            │
│   925                                                                                            │
│   926 def main():                                                                                │
│                                                                                                  │
│ C:\Users\my_user\Documents\GitHub\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:57 │
│ 9 in simple_launcher                                                                             │
│                                                                                                  │
│   576 │   process.wait()                                                                         │
│   577 │   if process.returncode != 0:                                                            │
│   578 │   │   if not args.quiet:                                                                 │
│ ❱ 579 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   580 │   │   else:                                                                              │
│   581 │   │   │   sys.exit(1)                                                                    │
│   582                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\my_user\\Documents\\GitHub\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py',
'--enable_bucket',
'--pretrained_model_name_or_path=D:/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV20_v20.safetensors',
'--train_data_dir=C:/Users/my_user/Desktop/lydia/image', '--resolution=512,512',
'--output_dir=C:/Users/my_user/Desktop/lydia/model', '--logging_dir=C:/Users/my_user/Desktop/lydia/log',
'--save_model_as=safetensors', '--output_name=lydia', '--max_data_loader_n_workers=0', '--learning_rate=1e-05',
'--lr_scheduler=cosine', '--lr_warmup_steps=54', '--train_batch_size=1', '--max_train_steps=540',
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents',
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Is the older version working better? What release is it?

**Comment by stefanosladopulos** [comment]
> 

hey! on another account here. i’m not sure of the version. it is around a month old. almost exactly one month. however this version gives me the same error i have with the current version even though i know for a fact that the old version worked perfectly

**Comment by bmaltais** [comment]
Try deleting the venv folder before re-installing... the venv contains newer modules that might be messing things up.

**Comment by stefanosladopulos** [comment]
> 

good point. i’ll try when i’ll get on

**Comment by bmaltais** [comment]
A bad venv can also cause the issue you originally observed. You can try both. THe new release (as of 40 minutes ago) after deleting the venv... and if that still does not work delete the venv again and try the older release.

**Comment by Stnf78** [comment]
I found the problem. When installing i entered gpu id '1' and i have only one gpu so for me my gpu id would be '0' and that's what has messed it up

**Comment by DiggyDre** [comment]
How did you get an older one installed? I recently had to install something new in my PC and reinstall windows and for some reason, kohya is not training like it used to, it is so frustrating.
