### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by godless1893** [bmaltais/kohya_ss#108]
My GPU is 2070s 8g, I used the configuration file in [https://www.youtube.com/watch?v=70H03cv57-o](url) which can be used by GPU less than 7GB of VRAM,but still out of memory when start training lora:
`RuntimeError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 8.00 GiB total capacity; 6.74 GiB already allocated; 0 bytes free; 6.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by developer90210brr** [comment]
Yea I get same with 8gb seems like pytorch is taking it all lol for me anyway

**Comment by godless1893** [comment]
> Yea I get same with 8gb seems like pytorch is taking it all lol for me anyway

Sorry I just found I made a stupid mistake that I chose dreambooth instead of Dreambooth Lora after solving all the problems. The options below the two tabs are almost the same so I hardly found it...

**Comment by Liujx47** [comment]
> 

hi godless, I also have this question。Could you show  me how to chose Dreambooth Lora?  Thanks a lot

**Comment by Liujx47** [comment]
@godless1893 Hi godless, I also have this question。Could you show me how to chose Dreambooth Lora? Thanks a lot

**Comment by Liujx47** [comment]
@godless1893 Hi godless ,thanks a looooooot! I also made this stupid mistake. you're my god
