### ISSUE TITLE
A problem with the location of the version number

### ISSUE THREAD

**Issue by yanhuifair** [bmaltais/kohya_ss#1081]
**Can display the version number at the bottom of the web page, like SD WebGUI will be much more beautiful**

<img width="1093" alt="Snipaste_2023-06-27_11-07-30" src="https://github.com/bmaltais/kohya_ss/assets/8871751/06e60de6-e28e-40da-95b3-2c8974e1ebbb">
<img width="1269" alt="Snipaste_2023-06-27_11-10-53" src="https://github.com/bmaltais/kohya_ss/assets/8871751/c3c7fbfb-5770-434e-867b-00fe6697a1e2">

**Comment by bmaltais** [comment]
I can see what I can do... Not much of a UX expert :-)

**Comment by yanhuifair** [comment]
> I can see what I can do... Not much of a UX expert :-)
> 
> 我可以看看我能做什么... 不是一个用户体验专家: -)

A good user experience will make others love your repository more, thank you for your great work
