### ISSUE TITLE
"System cannot find the path specified" when running setup.bat

### ISSUE THREAD

**Issue by DankaShu** [bmaltais/kohya_ss#1082]
Hello. When I run setup.bat I get this:
Warning: Python version 3.10.9 is recommended.
Creating venv...
Python The system cannot find the path specified.
Python The system cannot find the path specified.
Python
C:\Kohya\kohya_ss>

so I kinda din't know what to do with it
I use stable diffusion and it works fine and Python version is definitely 3.10. I also tried to reinstall it and it had no effect

**Comment by bmaltais** [comment]
If everything work don't worry about it.

**Comment by DankaShu** [comment]
> Make sure it is not python 3.11 or that is it at least 3.10.9

yeah sadly I've already checked this and it is 3.10.9
may be there is a way I can just write direct path for python in setup.bat?

**Comment by bmaltais** [comment]
If you hack it, probably. But there is most certainly an underlying issue on your system causing this. Might be preferable to fig that as it may cause other issues. Now... what is that issue? I have no idea.
