### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by Shwiftyrick435** [bmaltais/kohya_ss#1085]
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:196 in _run_module_as_main                                                                    │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:86 in _run_code                                                                               │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\fartl\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accele │
│ rate_cli.py:45 in main                                                                           │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\fartl\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch │
│ .py:918 in launch_command                                                                        │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\fartl\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch │
│ .py:580 in simple_launcher                                                                       │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\fartl\\OneDrive\\Desktop\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=C:/Users/fartl/OneDrive/Desktop/Ai/stable-diffusion-webui/models/Stable-diffusion/Best
of Ai art V.21.safetensors', "--train_data_dir=C:/Users/fartl/OneDrive/Desktop/Ai Tools n' Shit/LoRA Training
Data/Characters/Female/Rikka/Rikka LoRA/Image", '--resolution=512,512', "--output_dir=C:/Users/fartl/OneDrive/Desktop/Ai
Tools n' Shit/LoRA Training Data/Characters/Female/Rikka/Rikka LoRA/Model",
"--logging_dir=C:/Users/fartl/OneDrive/Desktop/Ai Tools n' Shit/LoRA Training Data/Characters/Female/Rikka/Rikka
LoRA/Log", '--network_alpha=1', '--training_comment=/Best of Ai art V.21.safetensors Training',
'--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001',
'--network_dim=8', '--output_name=Rikka', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001',
'--lr_scheduler=cosine', '--lr_warmup_steps=350', '--train_batch_size=1', '--max_train_steps=3500',
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents',
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 1.

I have no idea why this is happening. If anyone could help out it'd be much appreciated.

**Comment by dfghsderftgerdf** [comment]
try this it helped me, I had the same issue download the latest cuda toolkit:

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by Shwiftyrick435** [comment]
> try this it helped me, I had the same issue download the latest cuda toolkit:
> 
> https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

This worked! Thank you so much :)
