### ISSUE TITLE
FailedPreconditionError

### ISSUE THREAD

**Issue by RicGdlc** [bmaltais/kohya_ss#1086]
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\AI\kohya\kohya_ss\train_network.py:873 in <module>                                            │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\train_network.py:575 in train                                               │
│                                                                                                  │
│   572 │   prepare_scheduler_for_custom_training(noise_scheduler, accelerator.device)             │
│   573 │                                                                                          │
│   574 │   if accelerator.is_main_process:                                                        │
│ ❱ 575 │   │   accelerator.init_trackers("network_train" if args.log_tracker_name is None else    │
│   576 │                                                                                          │
│   577 │   loss_list = []                                                                         │
│   578 │   loss_total = 0.0                                                                       │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:564 in _inner              │
│                                                                                                  │
│    561 │   │   │   │   )                                                                         │
│    562 │   │                                                                                     │
│    563 │   │   def _inner(*args, **kwargs):                                                      │
│ ❱  564 │   │   │   return PartialState().on_main_process(function)(*args, **kwargs)              │
│    565 │   │                                                                                     │
│    566 │   │   return _inner                                                                     │
│    567                                                                                           │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:2093 in init_trackers      │
│                                                                                                  │
│   2090 │   │   │   │   if getattr(tracker_init, "requires_logging_directory"):                   │
│   2091 │   │   │   │   │   # We can skip this check since it was done in `__init__`              │
│   2092 │   │   │   │   │   self.trackers.append(                                                 │
│ ❱ 2093 │   │   │   │   │   │   tracker_init(project_name, self.logging_dir, **init_kwargs.get(s  │
│   2094 │   │   │   │   │   )                                                                     │
│   2095 │   │   │   │   else:                                                                     │
│   2096 │   │   │   │   │   self.trackers.append(tracker_init(project_name, **init_kwargs.get(st  │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\tracking.py:83 in execute_on_main_process │
│                                                                                                  │
│    80 │   @wraps(function)                                                                       │
│    81 │   def execute_on_main_process(self, *args, **kwargs):                                    │
│    82 │   │   if getattr(self, "main_process_only", False):                                      │
│ ❱  83 │   │   │   return PartialState().on_main_process(function)(self, *args, **kwargs)         │
│    84 │   │   else:                                                                              │
│    85 │   │   │   return function(self, *args, **kwargs)                                         │
│    86                                                                                            │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\tracking.py:190 in __init__               │
│                                                                                                  │
│   187 │   │   super().__init__()                                                                 │
│   188 │   │   self.run_name = run_name                                                           │
│   189 │   │   self.logging_dir = os.path.join(logging_dir, run_name)                             │
│ ❱ 190 │   │   self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)                │
│   191 │   │   logger.debug(f"Initialized TensorBoard project {self.run_name} logging to {self.   │
│   192 │   │   logger.debug(                                                                      │
│   193 │   │   │   "Make sure to log any initial configurations with `self.store_init_configura   │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py:247 in __init__    │
│                                                                                                  │
│    244 │   │   # Initialize the file writers, but they can be cleared out on close               │
│    245 │   │   # and recreated later as needed.                                                  │
│    246 │   │   self.file_writer = self.all_writers = None                                        │
│ ❱  247 │   │   self._get_file_writer()                                                           │
│    248 │   │                                                                                     │
│    249 │   │   # Create default bins for histograms, see generate_testdata.py in tensorflow/ten  │
│    250 │   │   v = 1e-12                                                                         │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py:277 in             │
│ _get_file_writer                                                                                 │
│                                                                                                  │
│    274 │   def _get_file_writer(self):                                                           │
│    275 │   │   """Returns the default FileWriter instance. Recreates it if closed."""            │
│    276 │   │   if self.all_writers is None or self.file_writer is None:                          │
│ ❱  277 │   │   │   self.file_writer = FileWriter(                                                │
│    278 │   │   │   │   self.log_dir, self.max_queue, self.flush_secs, self.filename_suffix       │
│    279 │   │   │   )                                                                             │
│    280 │   │   │   self.all_writers = {self.file_writer.get_logdir(): self.file_writer}          │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\torch\utils\tensorboard\writer.py:76 in __init__     │
│                                                                                                  │
│     73 │   │   # TODO: See if we can remove this in the future if we are                         │
│     74 │   │   # actually the ones passing in a PosixPath                                        │
│     75 │   │   log_dir = str(log_dir)                                                            │
│ ❱   76 │   │   self.event_writer = EventFileWriter(                                              │
│     77 │   │   │   log_dir, max_queue, flush_secs, filename_suffix                               │
│     78 │   │   )                                                                                 │
│     79                                                                                           │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\tensorboard\summary\writer\event_file_writer.py:72   │
│ in __init__                                                                                      │
│                                                                                                  │
│    69 │   │   │   pending events and summaries to disk.                                          │
│    70 │   │   """                                                                                │
│    71 │   │   self._logdir = logdir                                                              │
│ ❱  72 │   │   tf.io.gfile.makedirs(logdir)                                                       │
│    73 │   │   self._file_name = (                                                                │
│    74 │   │   │   os.path.join(                                                                  │
│    75 │   │   │   │   logdir,                                                                    │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\tensorflow\python\lib\io\file_io.py:513 in           │
│ recursive_create_dir_v2                                                                          │
│                                                                                                  │
│    510   Raises:                                                                                 │
│    511 │   errors.OpError: If the operation fails.                                               │
│    512   """                                                                                     │
│ ❱  513   _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))                        │
│    514                                                                                           │
│    515                                                                                           │
│    516 @tf_export("io.gfile.copy")                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FailedPreconditionError: C:/Users/ricgd/Desktop/StableDiffusion/Newfolder/New folder/ /training/slper/log is not a directory
steps:   0%|                                                                                                                                      | 0/9600 [00:00<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:196 in _run_module_as_main                                                                    │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:86 in _run_code                                                                               │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main     │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command  │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\AI\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\AI\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=C:/AI/stable-diffusion-webui/models/Stable-diffusion/absolutereality_v10.safetensors',
'--train_data_dir=C:/Users/ricgd/Desktop/StableDiffusion/Newfolder/New folder/\xa0/training/slper/images/full_medium', '--resolution=704,704',
'--output_dir=C:/Users/ricgd/Desktop/StableDiffusion/Newfolder/New folder/\xa0/training/slper/models', '--logging_dir=C:/Users/ricgd/Desktop/StableDiffusion/Newfolder/New
folder/\xa0/training/slper/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001',
'--network_dim=8', '--output_name=test', '--lr_scheduler_num_cycles=10', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=960', '--train_batch_size=1',
'--max_train_steps=9600', '--save_every_n_epochs=3', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW',
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Based on the information provided, it appears that the script is trying to create a directory for logging at the specified path (C:/Users/ricgd/Desktop/StableDiffusion/Newfolder/New folder/ /training/slper/log). However, the path contains an extra space and a forward slash, which might be causing the error.

**Comment by RicGdlc** [comment]
Thanks for your response. That worked.

This path worked before, but it seems that since I upgraded to Win 11 it no longer works.

Thanks for your time!
