### ISSUE TITLE
ModuleNotFoundError: No module named 'library'

### ISSUE THREAD

**Issue by McQuenji** [bmaltais/kohya_ss#1089]
I was receiving the following exception

![image](https://github.com/bmaltais/kohya_ss/assets/60017181/7fe0ece1-d949-402a-a205-4323a535b5fe)

Until I added these two lines in `finetune/make_captions.py`

```python
import inspect
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))) 
```

I haven't gotten past captioning with BLIP yet so this error may occur within multiple files but idk.

Thanks for the UI 👍

**Comment by bmaltais** [comment]
Hummm... This sound like the library module was not properly installed... You could try deleting the bench folder and re-run setup.bat and see if it fixes things

**Comment by McQuenji** [comment]
Sorry... I don't know what the bench folder is 😅

**Comment by Jotschi** [comment]
Got the same issue while on tag v21.7.16 using Debian Linux. I'll try an older release.

**Comment by Jotschi** [comment]
The problem is that the module 'library' can't be located. I assume this is due to the usage of venv. 

Afaik sys.path is used as search dirs to locate modules.

```python3
import sys
for path in sys.path:
  print(path)
```

My sys.path:
```
/extra/kohya_ss/finetune                                                                                                                                                                                                                    
/usr/lib/python311.zip                                                                                                                                                                                                              
/usr/lib/python3.11                                                                                                                                                                                                     
/usr/lib/python3.11/lib-dynload                                                                                                                                                                                                                                         
/extra/kohya_ss/venv/lib/python3.11/site-packages     
```

For me the resulting paths would not be able to locate the `library` folder/module (`/extra/kohya_ss/library`)

I was able to get my tagger running by appending "." to the path but I don't think that's a clean solution.

```python3
import sys
sys.path.append('.')
```

**Comment by bmaltais** [comment]
> Sorry... I don't know what the bench folder is 😅

Darn autocorrect... venv folder ;-)

**Comment by bmaltais** [comment]
@Jotschi It sound like you are possibly not using the venv approach and this is why the issue is arising?

**Comment by bmaltais** [comment]
Have you tried to manually run pip install --upgrade . when the venv is active?

Does it install Library 1.0.3?

**Comment by Jotschi** [comment]
@bmaltais That was helpful. `library` can't be installed due to a python version constraint issue. I bet that's the whole problem. I try to solve this on my side.

**Comment by McQuenji** [comment]
> > Sorry... I don't know what the bench folder is 😅
> 
> Darn autocorrect... venv folder ;-)

I've already cleared the venv folder multiple times and rerun the setup script, but the problem persists...

Running `pip install --upgrade .` just gives me this warning and freezes (I think).

![image](https://github.com/bmaltais/kohya_ss/assets/60017181/5be2c37e-92b6-4d88-98a4-f45e1433d27f)

However it works when i run the command outside of the venv...

**Comment by McQuenji** [comment]
Okay nvm just had to wait a bit longer 😅. After running the command it now works 👍

**Comment by Revmagi** [comment]
Hello, 

   I am running into this issue as well. I have removed the venv folder and reinstalled multiple times. I have also run the pip upgrade and I see the Library 1.0.3 is installed.

**Comment by McQuenji** [comment]
Hmmm.... have you tried adding these lines to the file that throws the error?

```python
import inspect
sys.path.insert(0,os.path.dirname(os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe()))))) 
```
