### ISSUE TITLE
config file does not save Sample images config settings

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#1090]
I've noticed config file does not keep the settings in json fyi
<img width="885" alt="chrome_IUCKAuKHef" src="https://github.com/bmaltais/kohya_ss/assets/64715158/48827f00-015b-4f72-8c51-4294bd7c2a99">

**Comment by bmaltais** [comment]
I just did a test on my side and the config file does load the sample images config properly... not sure why it does not work on your side... but I see that it does not save the actual prompt... is it that part you are refering to? I will add it to the config file...

**Comment by rafstahelin** [comment]
Ok. I'm on Windows. It's the Sample every N steps and the Sample every n epochs that doesn't seem retained when loading the config file. The prompt on the other hand is actually retained on config file. Strange. No big deal if you cannot reproduce it. I'm sure there are bigger issues. Thanks!
