### ISSUE TITLE
Buttons don't click

### ISSUE THREAD

**Issue by oxidizer05** [bmaltais/kohya_ss#1092]
I'm press the buttons but nothing happens (macOS Ventura 13.4.1)
I'm set paths manually but can't click finish buttons Train model(

<img width="1543" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/9698438/e3251ab2-253c-49d8-b400-3726158eedc2">

<img width="570" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/9698438/b5138e32-8887-48d8-b100-9e7f8e19809a">

**Comment by bmaltais** [comment]
Macos support is in rough shape. Hopefully a Macos user will eventually roll up it's sleeve and fix things for the community. I don't have a Mac so I can't do it.

**Comment by oxidizer05** [comment]
> Macos support is in rough shape. Hopefully a Macos user will eventually roll up it's sleeve and fix things for the community. I don't have a Mac so I can't do it.

No problem. Thx

**Comment by Astolatt** [comment]
I'm having the same problem, and I'm on Windows 11 with Python 3.10.9. Clicking on any browse folders icon does nothing, as well as Train model, so it's not a Mac-only problem.

**Comment by shynsky** [comment]
> I'm having the same problem, and I'm on Windows 11 with Python 3.10.9. Clicking on any browse folders icon does nothing, as well as Train model, so it's not a Mac-only problem. Besides that, there's a message "Modules installed outside the virtual environment were found." at the start.

Maybe this will help: https://www.reddit.com/r/StableDiffusion/comments/14q7pc3/kohya_buttons_not_working/

As for Mac, I'm confirming, buttons don't work.
