### ISSUE TITLE
training crashed with this error

### ISSUE THREAD

**Issue by utsav1232002** [bmaltais/kohya_ss#1093]
![Screenshot 2023-06-29 080241](https://github.com/bmaltais/kohya_ss/assets/122025114/47d18ef3-1a48-4372-a303-797f112824da)
training crashed with this error. and sometimes training gets stuck at certain random steps without any error.
running on rtx 3090 gpu. ryzen 7900x cpu. 2x16 ddr5 5200mhz ram on a windows 10 home system.

**Comment by bmaltais** [comment]
You could try to delete the bench and re-run setup and use the other torch version to see if it help... But on a 3090 there is no reason for torch 2 not to work... But still, try deleting the bench and set things up again.
