### ISSUE TITLE
Cleanest way to currently install?

### ISSUE THREAD

**Issue by gitihobo** [bmaltais/kohya_ss#1094]
I already have kohya installed but im running into issues, anyone have an updated step by step guide for installing this great software? preferably with anaconda env

**Comment by bmaltais** [comment]
Delete the venv folder the re-run setup

**Comment by gitihobo** [comment]
I used to follow youtube tutorials, what is current way of installing?

**Comment by bmaltais** [comment]
Clone the repo and run setup.bat... that is about it...

Make sure you have installed the prerequisites software as per the readme file.

**Comment by gitihobo** [comment]
I installed it and got some issues blipping the new version it said library module not found, my old install gets a pop up that says python.exe - Entry Point Not Found
The procedure entry point could
not be located in the dynamic link library torchvision\_C.pyd.
