### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by Yoimiyacat** [bmaltais/kohya_ss#1097]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████| 217/217 [00:00<00:00, 10583.67it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 768), count: 2170
mean ar error (without repeats): 0.0
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: C:/revAnimated_v122.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
import network module: None
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program Files\kohya_ss\train_network.py:873 in <module>                                       │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│ C:\Program Files\kohya_ss\train_network.py:178 in train                                          │
│                                                                                                  │
│   175 │                                                                                          │
│   176 │   sys.path.append(os.path.dirname(__file__))                                             │
│   177 │   print("import network module:", args.network_module)                                   │
│ ❱ 178 │   network_module = importlib.import_module(args.network_module)                          │
│   179 │                                                                                          │
│   180 │   if args.base_weights is not None:                                                      │
│   181 │   │   # base_weights が指定されている場合は、指定された重みを読み込みマージする          │
│                                                                                                  │
│ C:\Program Files\Python310\lib\importlib\__init__.py:117 in import_module                        │
│                                                                                                  │
│   114 │                                                                                          │
│   115 │   """                                                                                    │
│   116 │   level = 0                                                                              │
│ ❱ 117 │   if name.startswith('.'):                                                               │
│   118 │   │   if not package:                                                                    │
│   119 │   │   │   msg = ("the 'package' argument is required to perform a relative "             │
│   120 │   │   │   │      "import for {!r}")                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'startswith'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program Files\Python310\lib\runpy.py:196 in _run_module_as_main                               │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Program Files\Python310\lib\runpy.py:86 in _run_code                                          │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Program Files\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in     │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Program Files\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in            │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Program Files\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in            │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Program Files\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py',

**Comment by Yoimiyacat** [comment]
I have reinstalled kohya, but this error still exist.

**Comment by bmaltais** [comment]
Have you tried to manually configure accelerate via the setup.bat application?

**Comment by Yoimiyacat** [comment]
> Have you tried to manually configure accelerate via the setup.bat application?

yes,I have

**Comment by Yoimiyacat** [comment]
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by BuffMcBigHuge** [comment]
You may be missing `--network_module=networks.lora`

**Comment by mn359** [comment]
I use gui and had this problem, solved by changing output folder from this

`d:\some_dir\output\`

to this

`d:/some_other_dir/output`

**Comment by Ugleh** [comment]
> I use gui and had this problem, solved by changing output folder from this
> 
> `d:\some_dir\output\`
> 
> to this
> 
> `d:/some_other_dir/output`

this worked for me too.
