### ISSUE TITLE
Error when trying to train lora dreambooth

### ISSUE THREAD

**Issue by gitihobo** [bmaltais/kohya_ss#1099]
Im getting this issue, also what are the best settings for weak pcs?

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│**\train_network.py:873 in <module>              │
│                                                                                                  │
│   870 │   args = parser.parse_args()                                                             │
│   871 │   args = train_util.read_config_from_file(args, parser)                                  │
│   872 │                                                                                          │
│ ❱ 873 │   train(args)                                                                            │
│   874                                                                                            │
│                                                                                                  │
│**\train_network.py:662 in train                 │
│                                                                                                  │
│   659 │   │   │   │                                                                              │
│   660 │   │   │   │   # Predict the noise residual                                               │
│   661 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 662 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   663 │   │   │   │                                                                              │
│   664 │   │   │   │   if args.v_parameterization:                                                │
│   665 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│**\venv\lib\site-packages\torch\nn\modules\modul │
│ e.py:1130 in _call_impl                                                                          │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│**\venv\lib\site-packages\diffusers\models\unet_ │
│ 2d_condition.py:381 in forward                                                                   │
│                                                                                                  │
│   378 │   │   down_block_res_samples = (sample,)                                                 │
│   379 │   │   for downsample_block in self.down_blocks:                                          │
│   380 │   │   │   if hasattr(downsample_block, "has_cross_attention") and downsample_block.has   │
│ ❱ 381 │   │   │   │   sample, res_samples = downsample_block(                                    │
│   382 │   │   │   │   │   hidden_states=sample,                                                  │
│   383 │   │   │   │   │   temb=emb,                                                              │
│   384 │   │   │   │   │   encoder_hidden_states=encoder_hidden_states,                           │
│                                                                                                  │
│**\venv\lib\site-packages\torch\nn\modules\modul │
│ e.py:1130 in _call_impl                                                                          │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│**\venv\lib\site-packages\diffusers\models\unet_ │
│ 2d_blocks.py:612 in forward                                                                      │
│                                                                                                  │
│    609 │   │   │   │   )[0]                                                                      │
│    610 │   │   │   else:                                                                         │
│    611 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│ ❱  612 │   │   │   │   hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden  │
│    613 │   │   │                                                                                 │
│    614 │   │   │   output_states += (hidden_states,)                                             │
│    615                                                                                           │
│                                                                                                  │
│**\venv\lib\site-packages\torch\nn\modules\modul │
│ e.py:1130 in _call_impl                                                                          │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│**\venv\lib\site-packages\diffusers\models\atten │
│ tion.py:216 in forward                                                                           │
│                                                                                                  │
│   213 │   │                                                                                      │
│   214 │   │   # 2. Blocks                                                                        │
│   215 │   │   for block in self.transformer_blocks:                                              │
│ ❱ 216 │   │   │   hidden_states = block(hidden_states, context=encoder_hidden_states, timestep   │
│   217 │   │                                                                                      │
│   218 │   │   # 3. Output                                                                        │
│   219 │   │   if self.is_input_continuous:                                                       │
│                                                                                                  │
│**\venv\lib\site-packages\torch\nn\modules\modul │
│ e.py:1130 in _call_impl                                                                          │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│**\venv\lib\site-packages\diffusers\models\atten │
│ tion.py:484 in forward                                                                           │
│                                                                                                  │
│   481 │   │   if self.only_cross_attention:                                                      │
│   482 │   │   │   hidden_states = self.attn1(norm_hidden_states, context) + hidden_states        │
│   483 │   │   else:                                                                              │
│ ❱ 484 │   │   │   hidden_states = self.attn1(norm_hidden_states) + hidden_states                 │
│   485 │   │                                                                                      │
│   486 │   │   if self.attn2 is not None:                                                         │
│   487 │   │   │   # 2. Cross-Attention                                                           │
│                                                                                                  │
│**\venv\lib\site-packages\torch\nn\modules\modul │
│ e.py:1130 in _call_impl                                                                          │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│**\library\train_util.py:1939 in                 │
│ forward_xformers                                                                                 │
│                                                                                                  │
│   1936 │   │   q = q.contiguous()                                                                │
│   1937 │   │   k = k.contiguous()                                                                │
│   1938 │   │   v = v.contiguous()                                                                │
│ ❱ 1939 │   │   out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適な  │
│   1940 │   │                                                                                     │
│   1941 │   │   out = rearrange(out, "b n h d -> b n (h d)", h=h)                                 │
│   1942                                                                                           │
│                                                                                                  │
│**\venv\lib\site-packages\xformers\ops\fmha\__in │
│ it__.py:192 in memory_efficient_attention                                                        │
│                                                                                                  │
│   189 │   │   and options.                                                                       │
│   190 │   :return: multi-head attention Tensor with shape ``[B, Mq, H, Kv]``                     │
│   191 │   """                                                                                    │
│ ❱ 192 │   return _memory_efficient_attention(                                                    │
│   193 │   │   Inputs(                                                                            │
│   194 │   │   │   query=query, key=key, value=value, p=p, attn_bias=attn_bias, scale=scale       │
│   195 │   │   ),                                                                                 │
│                                                                                                  │
│**\venv\lib\site-packages\xformers\ops\fmha\__in │
│ it__.py:295 in _memory_efficient_attention                                                       │
│                                                                                                  │
│   292 │   │   )                                                                                  │
│   293 │                                                                                          │
│   294 │   output_shape = inp.normalize_bmhk()                                                    │
│ ❱ 295 │   return _fMHA.apply(                                                                    │
│   296 │   │   op, inp.query, inp.key, inp.value, inp.attn_bias, inp.p, inp.scale                 │
│   297 │   ).reshape(output_shape)                                                                │
│   298                                                                                            │
│                                                                                                  │
│**\venv\lib\site-packages\xformers\ops\fmha\__in │
│ it__.py:41 in forward                                                                            │
│                                                                                                  │
│    38 │   │   op_fw = op[0] if op is not None else None                                          │
│    39 │   │   op_bw = op[1] if op is not None else None                                          │
│    40 │   │                                                                                      │
│ ❱  41 │   │   out, op_ctx = _memory_efficient_attention_forward_requires_grad(                   │
│    42 │   │   │   inp=inp, op=op_fw                                                              │
│    43 │   │   )                                                                                  │
│    44                                                                                            │
│                                                                                                  │
│**\venv\lib\site-packages\xformers\ops\fmha\__in │
│ it__.py:323 in _memory_efficient_attention_forward_requires_grad                                 │
│                                                                                                  │
│   320 │   │   op = _dispatch_fw(inp)                                                             │
│   321 │   else:                                                                                  │
│   322 │   │   _ensure_op_supports_or_raise(ValueError, "memory_efficient_attention", op, inp)    │
│ ❱ 323 │   out = op.apply(inp, needs_gradient=True)                                               │
│   324 │   assert out[1] is not None                                                              │
│   325 │   return (out[0].reshape(output_shape), out[1])                                          │
│   326                                                                                            │
│                                                                                                  │
│**\venv\lib\site-packages\xformers\ops\fmha\cutl │
│ ass.py:175 in apply                                                                              │
│                                                                                                  │
│   172 │   │   if type(inp.attn_bias) not in FwOp.SUPPORTED_ATTN_BIAS_TYPES:                      │
│   173 │   │   │   raise NotImplementedError("Unsupported attn_bias type")                        │
│   174 │   │   seqstart_k, seqstart_q, max_seqlen_q, _ = _get_seqlen_info(inp)                    │
│ ❱ 175 │   │   out, lse, rng_seed, rng_offset = cls.OPERATOR(                                     │
│   176 │   │   │   query=inp.query,                                                               │
│   177 │   │   │   key=inp.key,                                                                   │
│   178 │   │   │   value=inp.value,                                                               │
│                                                                                                  │
│**\venv\lib\site-packages\torch\_ops.py:143 in   │
│ __call__                                                                                         │
│                                                                                                  │
│   140 │   │   # is still callable from JIT                                                       │
│   141 │   │   # We save the function ptr as the `op` attribute on                                │
│   142 │   │   # OpOverloadPacket to access it here.                                              │
│ ❱ 143 │   │   return self._op(*args, **kwargs or {})                                             │
│   144 │                                                                                          │
│   145 │   # TODO: use this to make a __dir__                                                     │
│   146 │   def overloads(self):                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 13
argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor?
cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)
steps:   0%|                                                                                   | 0/600 [00:01<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ **\kohya\lib\runpy.py:196 in _run_module_as_main                │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ **\kohya\lib\runpy.py:86 in _run_code                           │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│**\venv\lib\site-packages\accelerate\commands\ac │
│ celerate_cli.py:45 in main                                                                       │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│**\venv\lib\site-packages\accelerate\commands\la │
│ unch.py:1104 in launch_command                                                                   │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│**\venv\lib\site-packages\accelerate\commands\la │
│ unch.py:567 in simple_launcher                                                                   │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['**\kohya_ss\\venv\\Scripts\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=**/kohya_ss/SOURCE MODELS/v1-5-pruned - Copy
(2).ckpt', '--train_data_dir=C:\\Users\\**\\**\\Desktop\\\\images', '--resolution=512,512',
'--output_dir=C:\\Users\\**\\**\\Desktop\\**\\model', '--network_alpha=1', '--save_model_as=safetensors',
'--network_module=lycoris.kohya', '--network_args', 'conv_dim=1', 'conv_alpha=1', 'algo=lora',
'--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1',
'--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=60', '--train_batch_size=2',
'--max_train_steps=600', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=float', '--cache_latents',
'--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--save_every_n_steps=500',
'--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by future141** [comment]
I have the same problem in ubuntu 22.04 Nvidia 4090.

**Comment by future141** [comment]
It works with my windows, but when it comes to ubuntu, it breaks.

**Comment by gitihobo** [comment]
this is happening to me on windows

**Comment by PixelMelt** [comment]
same issue, Kubuntu 23.04 x86_64 3090

**Comment by bmaltais** [comment]
The issue appear to be related to xformers. Have you tried deleting the bench folder the re-run setup bat?

**Comment by gitihobo** [comment]
dont know how to do that, any tips?

**Comment by dfghsderftgerdf** [comment]
try this it helped me, I had the same issue download the latest cuda toolkit:  

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by gitihobo** [comment]
If I install the exe will it break other programs with different cuda toolkit versions?
