### ISSUE TITLE
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by Zetra-foilder** [bmaltais/kohya_ss#110]
i got this error when instaling the kohyass 

ERROR: Could not find a version that satisfies the requirement tensorflow<2.11 (from versions: none)
ERROR: No matching distribution found for tensorflow<2.11

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:15 char:1
+ accelerate config
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

any solution??

**Comment by bmaltais** [comment]
Did you follow the installation steps? It look like some of the python modules / libraries were not instlled.
