### ISSUE TITLE
.\setup.bat not working

### ISSUE THREAD

**Issue by JackleKat** [bmaltais/kohya_ss#1102]
Heya all,
i am running into a strange issue where i cant seem to open the [.\setup.bat] file.
I clone all the files fine and when i go into the [cd kohya_ss] everything is there but when i double click or open the Bat file as admin it opens then instantly closes the file.

my python, git and visual studio are on the right setting but I am still getting the same error is there a chance i am doing something wrong?

**Comment by JackleKat** [comment]
**follow up** 

I tried doing this through PowerShell and this is what i got

PS B:\kohya_ss> .\setup.ps1
& : The term '.\venv\Scripts\python.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At B:\kohya_ss\setup.ps1:3 char:20
+ $pythonVersion = & .\venv\Scripts\python.exe --version 2>$null
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\python.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Warning: Python version  is recommended.
Creating venv...
python : The term 'python' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At B:\kohya_ss\setup.ps1:10 char:5
+     python -m venv venv
+     ~~~~~~
    + CategoryInfo          : ObjectNotFound: (python:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

& : The term '.\venv\Scripts\deactivate.bat' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At B:\kohya_ss\setup.ps1:17 char:3
+ & .\venv\Scripts\deactivate.bat
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\deactivate.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

& : The term '.\venv\Scripts\python.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At B:\kohya_ss\setup.ps1:20 char:3
+ & .\venv\Scripts\python.exe .\setup\check_local_modules.py
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\python.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

& : The term '.\venv\Scripts\activate.bat' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At B:\kohya_ss\setup.ps1:22 char:3
+ & .\venv\Scripts\activate.bat
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

& : The term '.\venv\Scripts\python.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At B:\kohya_ss\setup.ps1:24 char:3
+ & .\venv\Scripts\python.exe .\setup\setup_windows.py
+   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\python.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

& : The term '.\venv\Scripts\deactivate.bat' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At B:\kohya_ss\setup.ps1:27 char:3
+ & .\venv\Scripts\deactivate.bat
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\deactivate.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bmaltais** [comment]
Have you installed the pre-requirements for Windows as instructed in the readme.md? Sound like python 3.10.9 has not been installed of the PATH option was not selected during the installation.

**Comment by JackleKat** [comment]
Heya!,

Yeah I have everything to the required level and I even did a fresh install of everything to be certain but I still have the same outcome.

**Comment by bmaltais** [comment]
Man I hate windows. It has those weird unpredictable issues. No idea why it is failing for you. Must be something particular to your setup.
