### ISSUE TITLE
'.\venv\Scripts\activate.bat' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by Johnny52590** [bmaltais/kohya_ss#1107]
hi so i come accross this issue when i try to insatll it, can anyone heklp to point out whats wrong?

PS C:\Users\Work\Documents\AI\kohya\kohya_ss> .\setup.bat
'.\venv\Scripts\deactivate.bat' is not recognized as an internal or external command,
operable program or batch file.
←[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

←[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
←[1;33m=============================================================←[0m

'.\venv\Scripts\activate.bat' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Work\Documents\AI\kohya\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\Work\Documents\AI\kohya\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
'.\venv\Scripts\deactivate.bat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Johnny52590** [comment]
actually i found what the issue is, i got another python insatll in other user in the same computer, once i deleted it.. erverthings working fine

**Comment by yzufardiansyah** [comment]
> actually i found what the issue is, i got another python insatll in other user in the same computer, once i deleted it.. erverthings working fine

thanks,b its working
