### ISSUE TITLE
Doesn't work on fresh installed ubuntu 22.04 NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by future141** [bmaltais/kohya_ss#1109]
╭────────────────────────────── Traceback (most recent call last) ───────────────────────────────╮
│ /home/future/kohya_ss/train_network.py:873 in <module>                                         │
│                                                                                                │
│   870 │   args = parser.parse_args()                                                           │
│   871 │   args = train_util.read_config_from_file(args, parser)                                │
│   872 │                                                                                        │
│ ❱ 873 │   train(args)                                                                          │
│   874                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/train_network.py:688 in train                                            │
│                                                                                                │
│   685 │   │   │   │   │   params_to_clip = network.get_trainable_params()                      │
│   686 │   │   │   │   │   accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)      │
│   687 │   │   │   │                                                                            │
│ ❱ 688 │   │   │   │   optimizer.step()                                                         │
│   689 │   │   │   │   lr_scheduler.step()                                                      │
│   690 │   │   │   │   optimizer.zero_grad(set_to_none=True)                                    │
│   691                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/accelerate/optimizer.py:134 in step    │
│                                                                                                │
│   131 │   │   │   │   xm.optimizer_step(self.optimizer, optimizer_args=optimizer_args)         │
│   132 │   │   │   elif self.scaler is not None:                                                │
│   133 │   │   │   │   scale_before = self.scaler.get_scale()                                   │
│ ❱ 134 │   │   │   │   self.scaler.step(self.optimizer, closure)                                │
│   135 │   │   │   │   self.scaler.update()                                                     │
│   136 │   │   │   │   scale_after = self.scaler.get_scale()                                    │
│   137 │   │   │   │   # If we reduced the loss scale, it means the optimizer step was skipped  │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:374 in   │
│ step                                                                                           │
│                                                                                                │
│   371 │   │                                                                                    │
│   372 │   │   assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were rec │
│   373 │   │                                                                                    │
│ ❱ 374 │   │   retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)       │
│   375 │   │                                                                                    │
│   376 │   │   optimizer_state["stage"] = OptState.STEPPED                                      │
│   377                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py:290 in   │
│ _maybe_opt_step                                                                                │
│                                                                                                │
│   287 │   def _maybe_opt_step(self, optimizer, optimizer_state, *args, **kwargs):              │
│   288 │   │   retval = None                                                                    │
│   289 │   │   if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):  │
│ ❱ 290 │   │   │   retval = optimizer.step(*args, **kwargs)                                     │
│   291 │   │   return retval                                                                    │
│   292 │                                                                                        │
│   293 │   def step(self, optimizer, *args, **kwargs):                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:69 in      │
│ wrapper                                                                                        │
│                                                                                                │
│     66 │   │   │   │   instance = instance_ref()                                               │
│     67 │   │   │   │   instance._step_count += 1                                               │
│     68 │   │   │   │   wrapped = func.__get__(instance, cls)                                   │
│ ❱   69 │   │   │   │   return wrapped(*args, **kwargs)                                         │
│     70 │   │   │                                                                               │
│     71 │   │   │   # Note that the returned function here is no longer a bound method,         │
│     72 │   │   │   # so attributes like `__func__` and `__self__` no longer exist.             │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/optim/optimizer.py:280 in        │
│ wrapper                                                                                        │
│                                                                                                │
│   277 │   │   │   │   │   │   │   raise RuntimeError(f"{func} must return None or a tuple of ( │
│   278 │   │   │   │   │   │   │   │   │   │   │      f"but got {result}.")                     │
│   279 │   │   │   │                                                                            │
│ ❱ 280 │   │   │   │   out = func(*args, **kwargs)                                              │
│   281 │   │   │   │   self._optimizer_step_code()                                              │
│   282 │   │   │   │                                                                            │
│   283 │   │   │   │   # call optimizer step post hooks                                         │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in      │
│ decorate_context                                                                               │
│                                                                                                │
│   112 │   @functools.wraps(func)                                                               │
│   113 │   def decorate_context(*args, **kwargs):                                               │
│   114 │   │   with ctx_factory():                                                              │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                 │
│   116 │                                                                                        │
│   117 │   return decorate_context                                                              │
│   118                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py:265 in │
│ step                                                                                           │
│                                                                                                │
│   262 │   │   │   │   if len(state) == 0:                                                      │
│   263 │   │   │   │   │   self.init_state(group, p, gindex, pindex)                            │
│   264 │   │   │   │                                                                            │
│ ❱ 265 │   │   │   │   self.update_step(group, p, gindex, pindex)                               │
│   266 │   │                                                                                    │
│   267 │   │   return loss                                                                      │
│   268                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py:115 in      │
│ decorate_context                                                                               │
│                                                                                                │
│   112 │   @functools.wraps(func)                                                               │
│   113 │   def decorate_context(*args, **kwargs):                                               │
│   114 │   │   with ctx_factory():                                                              │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                 │
│   116 │                                                                                        │
│   117 │   return decorate_context                                                              │
│   118                                                                                          │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py:506 in │
│ update_step                                                                                    │
│                                                                                                │
│   503 │   │   │   state["max1"], state["new_max1"] = state["new_max1"], state["max1"]          │
│   504 │   │   │   state["max2"], state["new_max2"] = state["new_max2"], state["max2"]          │
│   505 │   │   elif state["state1"].dtype == torch.uint8 and config["block_wise"]:              │
│ ❱ 506 │   │   │   F.optimizer_update_8bit_blockwise(                                           │
│   507 │   │   │   │   self.optimizer_name,                                                     │
│   508 │   │   │   │   grad,                                                                    │
│   509 │   │   │   │   p,                                                                       │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py:858 in      │
│ optimizer_update_8bit_blockwise                                                                │
│                                                                                                │
│    855 ) -> None:                                                                              │
│    856 │                                                                                       │
│    857 │   if g.dtype == torch.float32 and state1.dtype == torch.uint8:                        │
│ ❱  858 │   │   str2optimizer8bit_blockwise[optimizer_name][0](                                 │
│    859 │   │   │   get_ptr(p),                                                                 │
│    860 │   │   │   get_ptr(g),                                                                 │
│    861 │   │   │   get_ptr(state1),                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                             | 0/4000 [00:00<?, ?it/s]
╭────────────────────────────── Traceback (most recent call last) ───────────────────────────────╮
│ /home/future/kohya_ss/venv/bin/accelerate:8 in <module>                                        │
│                                                                                                │
│   5 from accelerate.commands.accelerate_cli import main                                        │
│   6 if __name__ == '__main__':                                                                 │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                       │
│ ❱ 8 │   sys.exit(main())                                                                       │
│   9                                                                                            │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py: │
│ 45 in main                                                                                     │
│                                                                                                │
│   42 │   │   exit(1)                                                                           │
│   43 │                                                                                         │
│   44 │   # Run                                                                                 │
│ ❱ 45 │   args.func(args)                                                                       │
│   46                                                                                           │
│   47                                                                                           │
│   48 if __name__ == "__main__":                                                                │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py:1104 in  │
│ launch_command                                                                                 │
│                                                                                                │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AM │
│   1102 │   │   sagemaker_launcher(defaults, args)                                              │
│   1103 │   else:                                                                               │
│ ❱ 1104 │   │   simple_launcher(args)                                                           │
│   1105                                                                                         │
│   1106                                                                                         │
│   1107 def main():                                                                             │
│                                                                                                │
│ /home/future/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py:567 in   │
│ simple_launcher                                                                                │
│                                                                                                │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                    │
│    565 │   process.wait()                                                                      │
│    566 │   if process.returncode != 0:                                                         │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)     │
│    568                                                                                         │
│    569                                                                                         │
│    570 def multi_gpu_launcher(args):                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/home/future/kohya_ss/venv/bin/python', 'train_network.py', 
'--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', 
'--train_data_dir=/home/future/图片/LORA/image', '--resolution=512,512', 
'--output_dir=/home/future/图片/LORA/model', '--logging_dir=/home/future/图片/LORA/log', 
'--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', 
'--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', 
'--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', 
'--lr_warmup_steps=400', '--train_batch_size=1', '--max_train_steps=4000', 
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', 
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', 
'--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

Install 535 driver manually. Then install kohya as instructed. Tried on two different computers. Computer 1: i9 13900HK Nvida 4060 Computer 2: i7 9700K 4090 + 2080Ti. Both have the same problem "NameError: name 'str2optimizer8bit_blockwise' is not defined". Tried on windows on both computer, both work.

**Comment by future141** [comment]
Problem solved. The problem is that the libcudart.so is not in the LD_LIBRARY_PATH. For me, I add "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu" to .bashrc to make sure that libcudart.so is in the LD_LIBRARY_PATH.

**Comment by joshgura** [comment]
> Problem solved. It is the a problem with bitsandbytes. The problem is that the libcudart.so (or something else I don't know) is not in the LD_LIBRARY_PATH. For me, I add "export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu" to .bashrc to make sure that libcudart.so is in the LD_LIBRARY_PATH. Then everything is fine. Hope this can help someone.

that only helps if libcudart.so and etc is at that location, for me it was in miniconda's lib directory, and the command i added to .bashrc is as follows, which fixed the bitsandbytes check:

`export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/username/miniconda3/lib"`

just search your systems until you find libcudart.so and try using that location instead of the exact .bashrc command i wrote above if this is the case for you as well. the formatting might matter too so maybe omit the trailing slash of the folder and use the double quotes like shown.
