### ISSUE TITLE
Quick pick models, where are they being saved?

### ISSUE THREAD

**Issue by GeneralAwareness** [bmaltais/kohya_ss#111]
Where are the quick pick models actually being saved at?

**Comment by bmaltais** [comment]
They are saved in the C:\Users\<username>\.cache folder

**Comment by GeneralAwareness** [comment]
Thank you as I couldn't find them as I am done with bf16 after 3+ weeks of testing.  For LoRA training I had a 3090, and a 4090 test training and they managed it, BUT ONLY if they used bf16 as fp16 will not work for SD V2.x.  My card doesn't have bf16, nor does the Colab's T4, so I can't use LoRA like this.  My final test will be to see if I can even use a model trained with bf16.

**Comment by bmaltais** [comment]
> Thank you as I couldn't find them as I am done with LoRA after 3+ weeks of testing. For LoRA training I had a 3090, and a 4090 test training and they managed it, BUT ONLY if they used bf16 as fp16 will not work with SD V2.x. My card doesn't have bf16, nor does the Colab's T4, so I can't use LoRA like this. My final test will be to see if I can even use a model trained with bf16.

You might have to "resize" them as fp16 for them to work... There is a tool to resize LoRA in the tools folder.

**Comment by GeneralAwareness** [comment]
These are all 768x768 images so no resizing is needed.  I really ran all of this through the paces for many weeks trying to figure it out so I even tried to make them 512x512 but no dice.  Those cards with bf16 has no problems with any of this, but when they tried everything I did (including the resize) LoRA failed.  As a few have said if this can't be trained on fp16 for 2.x for them, as well as for me, it is dead.  Deltas have the same issue where it trains the delta and the TI at the same time and the TI part works whereas the Delta part is rubbish.
