### ISSUE TITLE
Mac M1 GPU slower than CPU mode?

### ISSUE THREAD

**Issue by chrismelbourne** [bmaltais/kohya_ss#1111]
Hi, 

I finally managed to get Kohya to recognise the M1 GPU (confirmed on Activity), but sadly, it is running around 50% slower than previously (on CPU mode)? 

I used to take about 8 hours to run 4000 steps, now it shows it's going to take 12 hours. 

Any ideas? Or should I just give up and switch accelerate config to ignore "MPS"?

**Comment by Loneshade** [comment]
At the moment it sounds like you have gotten further with it running on MacOS than anyone else has. Most users are unable to get it running on any of their devices. Do you know which branch number you are using? 

Also which settings have you used so far to get it to work?

As they aren't able to work on a macOS device, the more info you provide to the community the better someone else might have of finding the issues and building the support for it.

**Comment by FullstackJack** [comment]
Have you seen this? Supposedly 1hr training Mac. I'm gonna to try it soon. I have M2 Max 64GB Unified Memory.

https://github.com/bmaltais/kohya_ss/discussions/1185

**Comment by mercury1989** [comment]
mbp m1pro 16G train:40 steps

--network_dim=32 cpu mode (229seconds)
--network_dim=32 gpu mode (110seconds)
