### ISSUE TITLE
Permission Error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by sTiKyt** [bmaltais/kohya_ss#1113]
![image](https://github.com/bmaltais/kohya_ss/assets/35602029/ccbb9335-a1c0-4ae4-a3c0-113f846319f7)
![image](https://github.com/bmaltais/kohya_ss/assets/35602029/95f6086d-4237-4384-bdd8-7d0320348b70)
![image](https://github.com/bmaltais/kohya_ss/assets/35602029/28e08a2d-1027-48c8-afa4-8e3b5e33408c)
![image](https://github.com/bmaltais/kohya_ss/assets/35602029/3292948f-0d04-45ec-9547-9ad4a7f6f44b)

**Comment by chrismelbourne** [comment]
Are you on a Mac? If so you shouldn't be running CUDA, or even bitsandbytes (which uses CUDA).

**Comment by sTiKyt** [comment]
> Are you on a Mac? If so you shouldn't be running CUDA, or even bitsandbytes (which uses CUDA).

No, i'm on Arch Linux

**Comment by TehNomad** [comment]
I have the same error with Arch Linux and I'm also using LightDM. It only happens to me with the Adam8Wbit optimizer, DAdaptAdam works fine for me.

**Comment by sTiKyt** [comment]
> I have the same error with Arch Linux and I'm also using LightDM. It only happens to me with the Adam8Wbit optimizer, DAdaptAdam works fine for me.

Dude, thanks a lot, you have no idea how much you just helped me xD

I'm just experimenting and don't really understand most of the things i'm doing so i would never try changing optimizer to fix that crap, now it seems to be training as expected
![image](https://github.com/bmaltais/kohya_ss/assets/35602029/fee15a74-675b-45c0-8d0b-e1198204ff2b)

**Comment by sTiKyt** [comment]
> > I have the same error with Arch Linux and I'm also using LightDM. It only happens to me with the Adam8Wbit optimizer, DAdaptAdam works fine for me.
> 
> Dude, thanks a lot, you have no idea how much you just helped me xD
> 
> I'm just experimenting and don't really understand most of the things i'm doing so i would never try changing optimizer to fix that crap, now it seems to be training as expected ![image](https://user-images.githubusercontent.com/35602029/250961684-fee15a74-675b-45c0-8d0b-e1198204ff2b.png)

Could you explain what does optimizer even do and what to look at while picking one?

**Comment by TehNomad** [comment]
The optimizer is the algorithm that adjusts the parameters of your model during training to improve its accuracy. Check out this document for how to use dAdapatation:
https://rentry.org/LazyDAdaptationGuide
