### ISSUE TITLE
Support svd_merge_lora.py

### ISSUE THREAD

**Issue by blooest** [bmaltais/kohya_ss#1117]
As opposed to the merge_lora.py which allows for merging into a checkpoint, svd_merge_lora.py is strictly for standalone merges. But, it supports both **mismatched dims**, and **LyCORIS merging**. Two things sorely lacking from merge_lora.py, and from this GUI.

To make things easier on you from a dev standpoint, it supports the same --precision, --save_precision, --models, --ratios, --save_to args as the normal merge_lora.py. It drops --sd_model for obvious reasons, as well as --v2, presumably also because it's not loading a checkpoint. It adds --new_rank and --new_conv_rank for LoRA rank and Conv2D rank respectively, which can work like your rank sliders in other tabs (e.g. fixed locon extraction), and --device, which can also work like it does in other tabs.

Thanks!

**Comment by bmaltais** [comment]
I will look at adding it to the tools for the next release.
