### ISSUE TITLE
Button to save configuration is not available when running with --headless on RunPod

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#1125]
When running with `--headless` on RunPod, the option to LOAD the configuration is available, but not the option to SAVE the configuration.

The LOAD configuration button is only useful if you have managed to successfully save your configuration previously, and its a bit tricky to try and create the JSON configuration file by hand if you don't have an example configuration file to copy from.

It would be really useful if users could SAVE their configuration when running with `--headless` like they are able to do without it.
Don't need to be able to browse to a folder to save it to, just enter the path and filename like you do with LOAD and then click the button to SAVE it.

**Comment by bmaltais** [comment]
Good point... I whould change that... the save button should be visible

**Comment by bmaltais** [comment]
It will be fixed in the next major release... currently in the sdxl branch.

**Comment by ashleykleynhans** [comment]
Ws a bit busy today and didn't get a chance to test earlier, but finally got a chance to test and can confirm that it is working perfectly, thank you so much @bmaltais!  You are the most active/responsive developer in any project that I log issues for, thank you!!

**Comment by bmaltais** [comment]
Thank you for raising the issue. I will also add a new feature that will save the training config in the destination model folder on train execution. I have lost too many training configs because I just forgot to save them... This will provide a safety net.

**Comment by bmaltais** [comment]
New auto save config added to the sdxl branch
