### ISSUE TITLE
ModuleNotFoundError: No module named 'library'

### ISSUE THREAD

**Issue by Revmagi** [bmaltais/kohya_ss#1126]
Hello, 

          This issue has not gone away. I have tried installing, rebuilding, and all the other suggestions of removing the venv folder, and running pip upgrade to get the library 1.0.3.  I am still unable to use the blip captioning. Any other suggestions would be helpful until this issue is fully fixed and works out of the box with the installer. Other than that, this code looks very promising and I look forward to working with it.

Thanks for your time.

**Comment by Revmagi** [comment]
Hello, 

    Ok, after all the hours and finally submitting the message I got it to work. On the latest install I found this in the original installation:    ERROR    Error running pip: install --upgrade -e .

I ran through the rest of the configuration, then installed the Cudann, and then used 6 to quit. 
I was then able to do the pip install --upgrade . and this time. After installing the library, everything is working. Maybe it is something in the installer with the -e?

**Comment by bmaltais** [comment]
Triton is normal... It does not exist for Windows and does not cause any issues.
