### ISSUE TITLE
The Web UI does nothing

### ISSUE THREAD

**Issue by SODDINGIT** [bmaltais/kohya_ss#1129]
The Web Interface does nothing. I can switch tabs in the menu but no button does anything. I cannot start training or open/select files or paths. The console stays like this until I close it. I have tried 3 different browsers and disabled all ad/script blocking. I have made the server public and accessed it with my phone. I guess I can rule out a browser issue. Something is wrong with the interface.

Editing this to reflect the fact that the issue actually manifsted on both Windows and Linux. The issue seems to have been with Gradio v.3.33.1

←[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

←[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
←[1;33m=============================================================←[0m

23:03:59-368512 INFO     Version: v21.7.16
23:03:59-374512 INFO     nVidia toolkit detected
23:04:01-364454 INFO     Torch 1.12.1+cu116
23:04:01-435115 INFO     Torch backend: nVidia CUDA 11.6 cuDNN 8700
23:04:01-438119 INFO     Torch detected GPU: NVIDIA GeForce RTX 2070 VRAM 8192 Arch (7, 5) Cores 36
23:04:01-440116 INFO     Verifying modules instalation status from requirements_windows_torch1.txt...
23:04:01-443118 INFO     Verifying modules instalation status from requirements.txt...
23:04:04-707490 INFO     headless: False
23:04:04-715490 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by toyssamurai** [comment]
I am on Ubuntu (on paperspace), and it does nothing, too. In fact, even typing into some of the fields would throw an "error" in the Web UI (such as, the configuration file field's location.)

**Comment by amarillosebas** [comment]
I'm getting the exact same issue. I've installed following [OlivioSarikas' instructions](https://www.youtube.com/watch?v=j-So4VYTL98).

**Comment by kaan36875** [comment]
Same issue, I didn't have an issue when I download it at morning. I was just trying to fresh install now, I saw the old one still works but new one is not.

**Comment by amarillosebas** [comment]
> Same issue, I didn't have an issue when I download it at morning. I was just trying to fresh install now, I saw the old one still works but new one is not.

What version of Torch did you install? I installed Torch 2.

**Comment by kaan36875** [comment]
I installed Torch 2, too.

**Comment by Thebogurtlen** [comment]
Same issue. I'm on windows 11. I just installed it an hour ago.

**Comment by martinobettucci** [comment]
Up, same here: it also broke our previous installation when rebuilt so it seams to me something coming from an upstream dependency @bmaltais

**Comment by kaan36875** [comment]
I managed to fix it. They will probably fix it soon, but here's a quick fix:

On main folder, you should open cmd and write those commands in order:

.\venv\Scripts\activate
pip uninstall fastapi
pip uninstall pydantic
pip install fastapi==0.99.1
pip install pydantic==1.10.11

**Comment by bux** [comment]
Still doesn't work with @kaan36875 's fix

**Comment by bmaltais** [comment]
Is there a k own issue with those two modules? I don't train on Linux so I never experience those issues there... But everything work fine for me on windows. Been training sdxl with the new code in the sdxl branch for a while with no issues. Maybe you could give that updated version a try? Major code rework in there.

**Comment by jimtalksdata** [comment]
Yes, Pydantic 2 incorporates some breaking changes compared to Pydantic 1. See:

https://docs.pydantic.dev/2.0/migration/
https://github.com/tiangolo/fastapi/releases/tag/0.100.0

**Comment by ashleykleynhans** [comment]
If this is related to starting the UI with `--share`, then its a gradio issue and is resolved by bumping gradio to the latest (3.36.1).  Seems they broke backwards compatibility in their tunnel or something.

**Comment by Pashahlis** [comment]
installing gradio v. 3.36.1 fixed the issues for me

python3 -m pip install gradio==3.36.1

**Comment by SODDINGIT** [comment]
> installing gradio v. 3.36.1 fixed the issues for me
> 
> python3 -m pip install gradio==3.36.1

i have done this and it did not work. Updated my initial post to indicate that the issue now persists across platforms. Linux as well as Windows (fresh install)

**Comment by CodR-2** [comment]
> I managed to fix it. They will probably fix it soon, but here's a quick fix:
> 
> On main folder, you should open cmd and write those commands in order:
> 
> .\venv\Scripts\activate pip uninstall fastapi pip uninstall pydantic pip install fastapi==0.99.1 pip install pydantic==1.10.11

Thanks for the fix, it worked for me.

**Comment by tkittich** [comment]
> I managed to fix it. They will probably fix it soon, but here's a quick fix:
> 
> On main folder, you should open cmd and write those commands in order:
> 
> .\venv\Scripts\activate pip uninstall fastapi pip uninstall pydantic pip install fastapi==0.99.1 pip install pydantic==1.10.11

This fixed the problem for me too. Thanks.

**Comment by timnetworks** [comment]
I am also seeing the same symptoms, `[HTTP/1.1 422 Unprocessable Entity 2ms]` when **POST**ing to `http://127.0.0.1:7861/run/predict` on latest Ubuntu/Mint. Not able to initiate training at all, and also getting the ERROR popups when entering anything into the DreamBooth LoRA folder paths. Thank you,

**Comment by studiomav** [comment]
I'm having this same issue, none of the fixes mentioned in this thread work for me. (M1 Mac)
