### ISSUE TITLE
kohya_ss  gui cant use,  http://127.0.0.1:7860/run/predict 422

### ISSUE THREAD

**Issue by gq-star** [bmaltais/kohya_ss#1132]
![image](https://github.com/bmaltais/kohya_ss/assets/135801177/3f3851ac-79ea-4795-9d5b-0bb87a23e04e)

**Comment by hassan-sd** [comment]
Same issue for me, can't really interact properly in the webui at all with the error showing in the console

![brave_i2RrsA7P6Z](https://github.com/bmaltais/kohya_ss/assets/119671806/d17384e5-5cc6-4fba-ae6a-e6f5ebdb6b9b)

**Comment by ShredRum** [comment]
Same.

**Comment by gq-star** [comment]
This is what I see no one has asked this, is this the latest version of the problem?

**Comment by kaan36875** [comment]
I managed to fix it. They will probably fix it soon, but here's a quick fix:

On main folder, you should open cmd and write those commands in order:

.\venv\Scripts\activate
pip uninstall fastapi
pip uninstall pydantic
pip install fastapi==0.99.1
pip install pydantic==1.10.11

**Comment by Pashahlis** [comment]
installing gradio v. 3.36.1 fixed the issues for me

python3 -m pip install gradio==3.36.1

**Comment by trogiar** [comment]
In my environment, the method presented by @Pashahlis solved this problem.
Change `gradio==3.33.1` to `gradio==3.36.1` in requirements.txt in the repository folder.

**Comment by soulduse** [comment]
I don't have .\venv\Scripts\activate
![image](https://github.com/bmaltais/kohya_ss/assets/11257459/76e9fa9e-40f8-4669-a936-74692bc8604e)
Is it difference mac os?

**Comment by soulduse** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/11257459/9f80fd9f-14b3-4978-877f-ae030cd8b92d)
I tried this one. but didn't work for me 😢 

In my case response was 200 but can't open directory
![image](https://github.com/bmaltais/kohya_ss/assets/11257459/ebd60687-8105-4e5f-a234-bb43617da556)
