### ISSUE TITLE
we need urgent gradio version bump for runpod

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1135]
please upgrade version to 3.36.1

otherwise not working

**Comment by ashleykleynhans** [comment]
To clarify, it works fine with just `--headless`, but the `--share` option to open a tunnel is not working anymore.

**Comment by FurkanGozukara** [comment]
> To clarify, it works fine with just `--headless`, but the `--share` option to open a tunnel is not working anymore.

With this version share and headless working

**Comment by Pashahlis** [comment]
installing gradio v. 3.36.1 fixed the issues for me

python3 -m pip install gradio==3.36.1

**Comment by bmaltais** [comment]
The new release has upgraded the gradio version. This should fix the issue and add sdxl training on top ;-) so maybe a whole bunch of new issues possible

**Comment by FurkanGozukara** [comment]
> The new release has upgraded the gradio version. This should fix the issue and add sdxl training on top ;-) so maybe a whole bunch of new issues possible

awesome
hopefully i will do a video for sdxl training this week
