### ISSUE TITLE
error when setting folders

### ISSUE THREAD

**Issue by DanangCode** [bmaltais/kohya_ss#1136]
on runpod under the dreambooth folders tab I select the input image folder and type anything. I get an error. happens with all for folders
![image](https://github.com/bmaltais/kohya_ss/assets/309460/9b78c628-e002-4d69-b1db-3e8df15d7542)

**Comment by ViliNeto** [comment]
They probably will update this soon.

Look this post, there're at least 2 temp. solutions for it now:
https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311
