### ISSUE TITLE
Non-Responsive UI in Windows 10

### ISSUE THREAD

**Issue by DiggyDre** [bmaltais/kohya_ss#1138]
For some reason, the GUI is not doing anything at all in Windows 10. No buttons react to anything now. Is there a way to revert to an older Kohya? I had an older one in here that was working just fine about a month back and then I rebuilt my computer and installed whatever version was out when I did that and for some reason, my LoRA training hasn't been coming out right since then.

**Comment by CodR-2** [comment]
I am having the exact same issue, but I am on windows 11... I was literally just about to make a post about this and saw yours. I have tried installing 3 different versions so far and so far version: v21.7.16, v21.7.15, v21.7.14 all dont work... I am still trying to find which is the next version that actually works...

**Comment by CodR-2** [comment]
I have went as far back as release version kohya_ss-21.3.9 and still have the issue.

**Comment by CodR-2** [comment]
I found the fix by another user: https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311

**Comment by DiggyDre** [comment]
> I found the fix by another user: [#1129 (comment)](https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311)

Thank you! That actually worked. I was starting to wonder what in the world is going on because it looks like many of us are having a problem across platforms. I even went as far as installing gradio, lol.

**Comment by CodR-2** [comment]
Haha, no problem, yeah I was trying so many different things and before that I was having a loss=nan issue. Now, I am trying to fix that again. If its not one thing, its another lol.

**Comment by bmaltais** [comment]
Give the latest release with sdxl support a try. I think it should fix this... fingers crossed.
