### ISSUE TITLE
Button press returning response code 422 Unprocessable Entity

### ISSUE THREAD

**Issue by slohth** [bmaltais/kohya_ss#1139]
Hi there,

After cloning, installing and running the setup.bat then the gui.bat file, any button press does not work and instead returns a 422 response code.

See attached gif:

![brave_cwmvCo3yNd](https://github.com/bmaltais/kohya_ss/assets/59024443/239d1a0b-79ee-4c01-b8cc-16a7b443d574)

index.js:170     POST http://127.0.0.1:7860/run/predict 422 (Unprocessable Entity)
$r @ index.js:170
(anonymous) @ index.js:396
Promise.then (async)
j @ index.js:385
pe @ Blocks.svelte:286
je @ Blocks.svelte:280
await in je (async)
(anonymous) @ Blocks.svelte:361
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
f @ Button.svelte:12
(anonymous) @ index.mjs:1170
Fr @ index.mjs:1170
v @ Button.svelte:11
Show 4 more frames

Is there any way I can fix this? Thanks

**Comment by coderzhoucf** [comment]
I also encountered this issue. The new computer system has this issue with Win11, while the old computer system did not have this issue with Win10.

**Comment by slohth** [comment]
For reference, I recorded a video of me downloading a completely fresh installation of koyha ss:
https://youtu.be/HLdZiF_HtUU

**Comment by CodR-2** [comment]
I'm also having the same issue and I am on windows 11. I have tried so many different release versions and none have worked. I use to use this before and it worked until I updated to the latest version. So far the releases I have tried to downgrade and still have the issues are:
1) v21.7.16 
2) v21.7.15 
3) v21.7.14
4) v21.3.9
System:
Operating System Windows 11
Python 3.10.9

**Comment by CodR-2** [comment]
I found the fix by another user: https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311

**Comment by amurorei01** [comment]
Also encountered almost the same problem.

**Comment by slohth** [comment]
> I found the fix by another user: [#1129 (comment)](https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311)

This seems to work as a temporary fix! 🙏
