### ISSUE TITLE
Error When Training Lora

### ISSUE THREAD

**Issue by oliverban** [bmaltais/kohya_ss#1147]
[Dataset 0]
loading image sizes.
  0%|                                                                                           | 0/43 [00:00<?, ?it/s]860 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 6
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Oliver\Pictures\LoRA Outputs\OliXL\img\20_OliXL style"
    image_count: 43
    num_repeats: 20
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: OliXL style
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 3276.09it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 120
bucket 1: resolution (384, 576), count: 60
bucket 2: resolution (384, 640), count: 80
bucket 3: resolution (448, 448), count: 80
bucket 4: resolution (448, 512), count: 20
bucket 5: resolution (512, 384), count: 60
bucket 6: resolution (512, 512), count: 260
bucket 7: resolution (576, 384), count: 40
bucket 8: resolution (640, 384), count: 140
mean ar error (without repeats): 0.03127894986031629
100%|████████████████████████████████████████████████████████████████████████████████| 43/43 [00:00<00:00, 3277.04it/s]

make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).

number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 120
bucket 1: resolution (384, 576), count: 60
bucket 2: resolution (384, 640), count: 80
bucket 3: resolution (448, 448), count: 80
bucket 4: resolution (448, 512), count: 20
bucket 5: resolution (512, 384), count: 60
bucket 6: resolution (512, 512), count: 260
bucket 7: resolution (576, 384), count: 40
bucket 8: resolution (640, 384), count: 140
mean ar error (without repeats): 0.03127894986031629
preparing accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:974 in <module>                       │
│                                                                                                  │
│   971 │   args = train_util.read_config_from_file(args, parser)                                  │
│   972 │                                                                                          │
│   973 │   trainer = NetworkTrainer()                                                             │
│ ❱ 974 │   trainer.train(args)                                                                    │
│   975                                                                                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:205 in train                          │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\library\train_util.py:3266 in prepare_accelerator      │
│                                                                                                  │
│   3263 │   │   │   if args.wandb_api_key is not None:                                            │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3265 │                                                                                         │
│ ❱ 3266 │   accelerator = Accelerator(                                                            │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3268 │   │   mixed_precision=args.mixed_precision,                                             │
│   3269 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361   │
│ in __init__                                                                                      │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:907 in init_process_group                                                                 │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:1013 in _new_process_group_helper                                                         │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:974 in <module>                       │
│                                                                                                  │
│   971 │   args = train_util.read_config_from_file(args, parser)                                  │
│   972 │                                                                                          │
│   973 │   trainer = NetworkTrainer()                                                             │
│ ❱ 974 │   trainer.train(args)                                                                    │
│   975                                                                                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:205 in train                          │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\library\train_util.py:3266 in prepare_accelerator      │
│                                                                                                  │
│   3263 │   │   │   if args.wandb_api_key is not None:                                            │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3265 │                                                                                         │
│ ❱ 3266 │   accelerator = Accelerator(                                                            │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3268 │   │   mixed_precision=args.mixed_precision,                                             │
│   3269 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361   │
│ in __init__                                                                                      │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:907 in init_process_group                                                                 │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:1013 in _new_process_group_helper                                                         │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
[23:53:34] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 3124) of binary:                                 api.py:672
                    C:\Users\Oliver\Documents\Github\kohya_ss\venv\Scripts\python.exe
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ c:\python\lib\runpy.py:196 in _run_module_as_main                                                │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ c:\python\lib\runpy.py:86 in _run_code                                                           │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_ │
│ cli.py:45 in main                                                                                │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:9 │
│ 09 in launch_command                                                                             │
│                                                                                                  │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   907 │   │   multi_gpu_launcher(args)                                                           │
│   908 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                                           │
│   910 │   elif args.tpu and not args.cpu:                                                        │
│   911 │   │   if args.tpu_use_cluster:                                                           │
│   912 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:6 │
│ 04 in multi_gpu_launcher                                                                         │
│                                                                                                  │
│   601 │   )                                                                                      │
│   602 │   with patch_environment(**current_env):                                                 │
│   603 │   │   try:                                                                               │
│ ❱ 604 │   │   │   distrib_run.run(args)                                                          │
│   605 │   │   except Exception:                                                                  │
│   606 │   │   │   if is_rich_available() and debug:                                              │
│   607 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\run.py:785 in │
│ run                                                                                              │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api. │
│ py:134 in __call__                                                                               │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api. │
│ py:250 in launch_agent                                                                           │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError:
============================================================
./train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-07-09_23:53:34
  host      : DESKTOP-H1GCOEJ.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 6640)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-09_23:53:34
  host      : DESKTOP-H1GCOEJ.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3124)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by oliverban** [comment]
FIXED IT! I started cmd and went into the folder, and started setup.bat with ".\setup.bat" and installed it again. This time I got options to choose NVIDIA and which gpu id and all that, which did not come up before. After this, went in and manually entered all my settings again and voila, now it moves. I suspect it has something to do with accelerator and if you choose bucket and 512,XXX (non default square value here). This f'uped my other tries I suppose.

**Comment by bmaltais** [comment]
OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again.

**Comment by oliverban** [comment]
> OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again.

Yes, training is working now, although it checks for Triton after each save of the checkpoint, causing a little delay, but nothing major. The problem is that A1111 doesn't seem to support the LORA for some reason. I get
LoRA weight_unet: 1, weight_tenc: 1, model: OliXL-000007(defd3ff02912)
dimension: {128}, alpha: {128.0}, multiplier_unet: 1, multiplier_tenc: 1
*** Error running process_batch: C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py
    Traceback (most recent call last):
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\modules\scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 244, in process_batch
        network, info = lora_compvis.create_network_and_apply_compvis(
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 153, in create_network_and_apply_compvis
        network = LoRANetworkCompvis(text_encoder, unet, multiplier_tenc, multiplier_unet, modules_dim, modules_alpha)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 341, in __init__
        comp_vis_lora_name = LoRANetworkCompvis.convert_diffusers_name_to_compvis(self.v2, du_lora_name)
      File "C:\Users\Oliver\Documents\Github\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\lora_compvis.py", line 302, in convert_diffusers_name_to_compvis
        assert cv_name is not None, f"conversion failed: {du_name}. the model may not be trained by `sd-scripts`."
    
AssertionError: conversion failed: lora_te1_text_model_encoder_layers_0_mlp_fc1. the model may not be trained by `sd-scripts`.

**Comment by bmaltais** [comment]
For the lengthy time between epoch set the workers to 0.

For the a1111 incompatibility I don't know. Are you training a LyCORIS or a LoRA?

**Comment by oliverban** [comment]
> For the lengthy time between epoch set the workers to 0.
> 
> For the a1111 incompatibility I don't know. Are you training a LyCORIS or a LoRA?

A Lora. I do believe that it's a problem with the Additional Networks extension and not the LORA itself. When used in the prompt, it works fine! I have written on their git page about it, awaiting answers there! Thanks for looking into it! <3
