### ISSUE TITLE
Error training with Lora

### ISSUE THREAD

**Issue by archimedesinstitute** [bmaltais/kohya_ss#1148]
I keep getting this or similar errors when trying to train SDXL on Lora. I am newer to this particular UI, however I am using the presets and running directly locally.

[18:25:53] WARNING  The following values were not passed to `accelerate launch` and had defaults used      launch.py:890
                    instead:
                            `--num_processes` was set to a value of `1`
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
ignore directory without repeats / 繰り返し回数のないディレクトリを無視します: illustration style
prepare images.
0 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (1024, 1024)
  enable_bucket: False

[Dataset 0]
loading image sizes.
0it [00:00, ?it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
C:\Users\Araminta\Work\kohya_ss\venv\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Araminta\Work\kohya_ss\venv\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります）

**Comment by bmaltais** [comment]
OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again.

**Comment by archimedesinstitute** [comment]
Ok will try!
