### ISSUE TITLE
RuntimeError: Calculated padded input size per channel: (386 x 2). Kernel size: (3 x 3). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by asthinasthi** [bmaltais/kohya_ss#1149]
Trying to train a LoRA. I see this error message.
```
RuntimeError: Calculated padded input size per channel: (386 x 2). Kernel size: (3 x 3). Kernel size can't be greater
than actual input size
```
Any idea how to fix this?

## Stack Trace
```
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\aniru\git\kohya_ss\train_network.py:974 in <module>                                     │
│                                                                                                  │
│   971 │   args = train_util.read_config_from_file(args, parser)                                  │
│   972 │                                                                                          │
│   973 │   trainer = NetworkTrainer()                                                             │
│ ❱ 974 │   trainer.train(args)                                                                    │
│   975                                                                                            │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\train_network.py:250 in train                                        │
│                                                                                                  │
│   247 │   │   │   vae.requires_grad_(False)                                                      │
│   248 │   │   │   vae.eval()                                                                     │
│   249 │   │   │   with torch.no_grad():                                                          │
│ ❱ 250 │   │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_l   │
│   251 │   │   │   vae.to("cpu")                                                                  │
│   252 │   │   │   if torch.cuda.is_available():                                                  │
│   253 │   │   │   │   torch.cuda.empty_cache()                                                   │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\library\train_util.py:1728 in cache_latents                          │
│                                                                                                  │
│   1725 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1726 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1727 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1728 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1729 │                                                                                         │
│   1730 │   def is_latent_cacheable(self) -> bool:                                                │
│   1731 │   │   return all([dataset.is_latent_cacheable() for dataset in self.datasets])          │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\library\train_util.py:911 in cache_latents                           │
│                                                                                                  │
│    908 │   │   │   img_tensors = torch.stack(images, dim=0)                                      │
│    909 │   │   │   img_tensors = img_tensors.to(device=vae.device, dtype=vae.dtype)              │
│    910 │   │   │                                                                                 │
│ ❱  911 │   │   │   latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")              │
│    912 │   │   │                                                                                 │
│    913 │   │   │   for info, latent in zip(batch, latents):                                      │
│    914 │   │   │   │   # check NaN                                                               │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py:46 in     │
│ wrapper                                                                                          │
│                                                                                                  │
│   43 │   def wrapper(self, *args, **kwargs):                                                     │
│   44 │   │   if hasattr(self, "_hf_hook") and hasattr(self._hf_hook, "pre_forward"):             │
│   45 │   │   │   self._hf_hook.pre_forward(self)                                                 │
│ ❱ 46 │   │   return method(self, *args, **kwargs)                                                │
│   47 │                                                                                           │
│   48 │   return wrapper                                                                          │
│   49                                                                                             │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoder_kl.py:164 in     │
│ encode                                                                                           │
│                                                                                                  │
│   161 │   │   if self.use_tiling and (x.shape[-1] > self.tile_sample_min_size or x.shape[-2] >   │
│   162 │   │   │   return self.tiled_encode(x, return_dict=return_dict)                           │
│   163 │   │                                                                                      │
│ ❱ 164 │   │   h = self.encoder(x)                                                                │
│   165 │   │   moments = self.quant_conv(h)                                                       │
│   166 │   │   posterior = DiagonalGaussianDistribution(moments)                                  │
│   167                                                                                            │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py:110 in forward        │
│                                                                                                  │
│   107 │                                                                                          │
│   108 │   def forward(self, x):                                                                  │
│   109 │   │   sample = x                                                                         │
│ ❱ 110 │   │   sample = self.conv_in(sample)                                                      │
│   111 │   │                                                                                      │
│   112 │   │   if self.training and self.gradient_checkpointing:                                  │
│   113                                                                                            │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward       │
│                                                                                                  │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                          │
│    464                                                                                           │
│    465 class Conv3d(_ConvNd):                                                                    │
│    466 │   __doc__ = r"""Applies a 3D convolution over an input signal composed of several inpu  │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward │
│                                                                                                  │
│    456 │   │   │   return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │
│    457 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                         │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                 │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Calculated padded input size per channel: (386 x 2). Kernel size: (3 x 3). Kernel size can't be greater
than actual input size
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\aniru\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in   │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in          │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\aniru\git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in          │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by bmaltais** [comment]
Look like a bug in the new trainer code. Not sure why you dataset is triggering it. You may want to go back to the previous release.

**Comment by dothere** [comment]
Getting that as well, it works if you disable caching of latents. (Changing it to cache latents to disk doesn't appear to make a difference)

**Comment by dothere** [comment]
> Getting that as well, it works if you disable caching of latents. (Changing it to cache latents to disk doesn't appear to make a difference)

Looks like that just delayed the inevitable, actually:

`
steps:   2%|▉                                                       | 774/48400 [14:50<15:13:15,  1.15s/it, loss=0.144]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ P:\kohya_ss\train_network.py:974 in <module>                                                     │
│                                                                                                  │
│   971 │   args = train_util.read_config_from_file(args, parser)                                  │
│   972 │                                                                                          │
│   973 │   trainer = NetworkTrainer()                                                             │
│ ❱ 974 │   trainer.train(args)                                                                    │
│   975                                                                                            │
│                                                                                                  │
│ P:\kohya_ss\train_network.py:726 in train                                                        │
│                                                                                                  │
│   723 │   │   │   │   │   │   │   latents = batch["latents"].to(accelerator.device)              │
│   724 │   │   │   │   │   │   else:                                                              │
│   725 │   │   │   │   │   │   │   # latentに変換                                                 │
│ ❱ 726 │   │   │   │   │   │   │   latents = vae.encode(batch["images"].to(dtype=vae_dtype)).la   │
│   727 │   │   │   │   │   │   │                                                                  │
│   728 │   │   │   │   │   │   │   # NaNが含まれていれば警告を表示し0に置き換える                 │
│   729 │   │   │   │   │   │   │   if torch.any(torch.isnan(latents)):                            │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py:46 in wrapper             │
│                                                                                                  │
│   43 │   def wrapper(self, *args, **kwargs):                                                     │
│   44 │   │   if hasattr(self, "_hf_hook") and hasattr(self._hf_hook, "pre_forward"):             │
│   45 │   │   │   self._hf_hook.pre_forward(self)                                                 │
│ ❱ 46 │   │   return method(self, *args, **kwargs)                                                │
│   47 │                                                                                           │
│   48 │   return wrapper                                                                          │
│   49                                                                                             │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoder_kl.py:164 in encode              │
│                                                                                                  │
│   161 │   │   if self.use_tiling and (x.shape[-1] > self.tile_sample_min_size or x.shape[-2] >   │
│   162 │   │   │   return self.tiled_encode(x, return_dict=return_dict)                           │
│   163 │   │                                                                                      │
│ ❱ 164 │   │   h = self.encoder(x)                                                                │
│   165 │   │   moments = self.quant_conv(h)                                                       │
│   166 │   │   posterior = DiagonalGaussianDistribution(moments)                                  │
│   167                                                                                            │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py:110 in forward                        │
│                                                                                                  │
│   107 │                                                                                          │
│   108 │   def forward(self, x):                                                                  │
│   109 │   │   sample = x                                                                         │
│ ❱ 110 │   │   sample = self.conv_in(sample)                                                      │
│   111 │   │                                                                                      │
│   112 │   │   if self.training and self.gradient_checkpointing:                                  │
│   113                                                                                            │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                 │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                       │
│                                                                                                  │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                          │
│    464                                                                                           │
│    465 class Conv3d(_ConvNd):                                                                    │
│    466 │   __doc__ = r"""Applies a 3D convolution over an input signal composed of several inpu  │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                 │
│                                                                                                  │
│    456 │   │   │   return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=sel  │
│    457 │   │   │   │   │   │   │   weight, bias, self.stride,                                    │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                         │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                 │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                         │
│    461 │                                                                                         │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Calculated padded input size per channel: (66 x 2). Kernel size: (3 x 3). Kernel size can't be greater
than actual input size
steps:   2%|▉                                                       | 774/48400 [14:52<15:14:56,  1.15s/it, loss=0.144]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\domin\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\domin\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ P:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['P:\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=P:/ComfyUI_windows_portable/ComfyUI/models/checkpoints/sd_v1-5_vae.ckpt',
'--train_data_dir=P:/kohya_ss/lora_formatted/img/ready', '--reg_data_dir=P:/kohya_ss/lora_formatted/reg/ground truth',
'--resolution=512,512', '--output_dir=P:/kohya_ss/lora_formatted/model', '--logging_dir=P:/kohya_ss/lora_formatted/log',
'--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_dim=8',
'--output_name=DAdapt BA Test', '--lr_scheduler_num_cycles=10', '--learning_rate=1.0', '--lr_scheduler=cosine',
'--train_batch_size=8', '--max_train_steps=18640', '--save_every_n_epochs=2', '--mixed_precision=fp16',
'--save_precision=fp16', '--caption_extension=.txt', '--optimizer_type=DAdaptAdam', '--optimizer_args', 'decouple=True',
'weight_decay=0.6', 'betas=0.9,0.99', 'use_bias_correction=True', 'growth_rate=1.02', '--max_data_loader_n_workers=0',
'--max_token_length=225', '--keep_tokens=1', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale',
'--min_bucket_reso', '320', '--max_bucket_reso', '1024', '--max_train_epochs=50']' returned non-zero exit status 1.
`

**Comment by dothere** [comment]
So I think this happens when images in your dataset are too small, could be wrong though. I finally got it working by disabling "Don't upscale bucket resolution"

![image](https://github.com/bmaltais/kohya_ss/assets/38864297/7202c266-02c2-42d6-98cd-801231b0723a)

@asthinasthi Give that a try on your end.

**Comment by drgrib** [comment]
I'm getting this error for a training set with small images. The proposed solution for unchecking "Don't upscale bucket resolution"  is no longer available in the UI. I also just upgraded to the latest version and the referencing commit has not fixed the issue.
