### ISSUE TITLE
Why do I need an internet connection to train LoRA models?

### ISSUE THREAD

**Issue by RandomInternetPreson** [bmaltais/kohya_ss#115]
If I disconnect from the internet after successfully training a LoRA model (and not even close down Kohya_ss), I can't train the same or different LoRA models (using the same base model).  Why does the software need a connection to the internet after all information is downloaded to train the first model?

**Comment by bmaltais** [comment]
Good question... I suggest you ask kohya_ss directly on his main code repo. The GUI is not the one requiring internet access.
