### ISSUE TITLE
Can't start training because of an error TypeError: Accelerator.__init__

### ISSUE THREAD

**Issue by c0yotte** [bmaltais/kohya_ss#1151]
Hello, I have a weird issue which appears after I press "train model". I'm trying to train a lora on 1.5 model, not on on SDXL. The training won't start and the console looks like this.
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/8232f5cd-95e3-4362-994f-abda1b99f018)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/5b0280bd-6f8b-407e-aa7e-751fe319c215)

I've already tried deleting and recloning the repo and it didn't help. What is the cause of the problem and how can I fix it? Thanks!

**Comment by stinbuaa** [comment]
I also encountered a similar problem, my error is as follows
`number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (576, 896), count: 45
bucket 1: resolution (704, 1024), count: 15
bucket 2: resolution (768, 1152), count: 150
bucket 3: resolution (768, 1216), count: 30
bucket 4: resolution (768, 1280), count: 45
bucket 5: resolution (768, 1344), count: 45
bucket 6: resolution (832, 1088), count: 540
bucket 7: resolution (832, 1152), count: 195
bucket 8: resolution (832, 1216), count: 2955
bucket 9: resolution (896, 512), count: 15
bucket 10: resolution (896, 576), count: 270
bucket 11: resolution (896, 640), count: 15
bucket 12: resolution (896, 1024), count: 90
bucket 13: resolution (896, 1088), count: 360
bucket 14: resolution (896, 1152), count: 45
bucket 15: resolution (960, 640), count: 15
bucket 16: resolution (960, 960), count: 45
bucket 17: resolution (960, 1088), count: 15
bucket 18: resolution (1024, 1024), count: 285
bucket 19: resolution (1088, 832), count: 15
bucket 20: resolution (1088, 896), count: 30
bucket 21: resolution (1152, 768), count: 420
bucket 22: resolution (1152, 832), count: 45
bucket 23: resolution (1216, 832), count: 360
bucket 24: resolution (1280, 768), count: 15
bucket 25: resolution (1344, 768), count: 15
mean ar error (without repeats): 0.016153476512153424
prepare accelerator
╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/kohya_ss/train_db.py:474 in <module>                                 │
│                                                                            │
│   471 │   args = parser.parse_args()                                       │
│   472 │   args = train_util.read_config_from_file(args, parser)            │
│   473 │                                                                    │
│ ❱ 474 │   train(args)                                                      │
│   475                                                                      │
│                                                                            │
│ /root/kohya_ss/train_db.py:99 in train                                     │
│                                                                            │
│    96 │   │   │   f"gradient_accumulation_stepsが{args.gradient_accumulati │
│    97 │   │   )                                                            │
│    98 │                                                                    │
│ ❱  99 │   accelerator = train_util.prepare_accelerator(args)               │
│   100 │                                                                    │
│   101 │   # mixed precisionに対応した型を用意しておき適宜castする          │
│   102 │   weight_dtype, save_dtype = train_util.prepare_dtype(args)        │
│                                                                            │
│ /root/kohya_ss/library/train_util.py:3266 in prepare_accelerator           │
│                                                                            │
│   3263 │   │   │   if args.wandb_api_key is not None:                      │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                 │
│   3265 │                                                                   │
│ ❱ 3266 │   accelerator = Accelerator(                                      │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_step │
│   3268 │   │   mixed_precision=args.mixed_precision,                       │
│   3269 │   │   log_with=log_with,                                          │
╰────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'project_dir'
╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/miniconda3/bin/accelerate:8 in <module>                              │
│                                                                            │
│   5 from accelerate.commands.accelerate_cli import main                    │
│   6 if __name__ == '__main__':                                             │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])   │
│ ❱ 8 │   sys.exit(main())                                                   │
│   9                                                                        │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelera │
│ te_cli.py:45 in main                                                       │
│                                                                            │
│   42 │   │   exit(1)                                                       │
│   43 │                                                                     │
│   44 │   # Run                                                             │
│ ❱ 45 │   args.func(args)                                                   │
│   46                                                                       │
│   47                                                                       │
│   48 if __name__ == "__main__":                                            │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:1104 in launch_command                                                   │
│                                                                            │
│   1101 │   elif defaults is not None and defaults.compute_environment == C │
│   1102 │   │   sagemaker_launcher(defaults, args)                          │
│   1103 │   else:                                                           │
│ ❱ 1104 │   │   simple_launcher(args)                                       │
│   1105                                                                     │
│   1106                                                                     │
│   1107 def main():                                                         │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:567 in simple_launcher                                                   │
│                                                                            │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                │
│    565 │   process.wait()                                                  │
│    566 │   if process.returncode != 0:                                     │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.retu │
│    568                                                                     │
│    569                                                                     │
│    570 def multi_gpu_launcher(args):                                       │
╰────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/root/miniconda3/bin/python', 'train_db.py', 
'--enable_bucket', 
'--pretrained_model_name_or_path=/root/autodl-tmp/sd_xl_refiner_0.9.safetensor
s', '--train_data_dir=/root/autodl-tmp/data/img', '--resolution=1024,1024', 
'--output_dir=/root/autodl-tmp/data/output', 
'--logging_dir=/root/autodl-tmp/data/log', '--save_model_as=safetensors', 
'--output_name=filmXL', '--max_token_length=225', 
'--max_data_loader_n_workers=0', '--learning_rate=4e-07', 
'--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=3038', 
'--train_batch_size=1', '--max_train_steps=60750', '--save_every_n_epochs=2', 
'--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', 
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=Adafactor', 
'--optimizer_args', 'scale_parameter=False', 'relative_step=False', 
'warmup_init=False', '--max_data_loader_n_workers=0', 
'--max_token_length=225', '--keep_tokens=1', '--bucket_reso_steps=64', 
'--min_snr_gamma=5', '--shuffle_caption', '--xformers', '--bucket_no_upscale',
'--multires_noise_iterations=6', '--multires_noise_discount=0.3', 
'--wandb_api_key=False', '--sample_sampler=k_dpm_2', 
'--sample_prompts=/root/autodl-tmp/data/output/sample/prompt.txt', 
'--sample_every_n_epochs=1']' returned non-zero exit status 1.`

**Comment by stinbuaa** [comment]
I also encountered a similar problem, my error is as follows
`number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (576, 896), count: 45
bucket 1: resolution (704, 1024), count: 15
bucket 2: resolution (768, 1152), count: 150
bucket 3: resolution (768, 1216), count: 30
bucket 4: resolution (768, 1280), count: 45
bucket 5: resolution (768, 1344), count: 45
bucket 6: resolution (832, 1088), count: 540
bucket 7: resolution (832, 1152), count: 195
bucket 8: resolution (832, 1216), count: 2955
bucket 9: resolution (896, 512), count: 15
bucket 10: resolution (896, 576), count: 270
bucket 11: resolution (896, 640), count: 15
bucket 12: resolution (896, 1024), count: 90
bucket 13: resolution (896, 1088), count: 360
bucket 14: resolution (896, 1152), count: 45
bucket 15: resolution (960, 640), count: 15
bucket 16: resolution (960, 960), count: 45
bucket 17: resolution (960, 1088), count: 15
bucket 18: resolution (1024, 1024), count: 285
bucket 19: resolution (1088, 832), count: 15
bucket 20: resolution (1088, 896), count: 30
bucket 21: resolution (1152, 768), count: 420
bucket 22: resolution (1152, 832), count: 45
bucket 23: resolution (1216, 832), count: 360
bucket 24: resolution (1280, 768), count: 15
bucket 25: resolution (1344, 768), count: 15
mean ar error (without repeats): 0.016153476512153424
prepare accelerator
╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/kohya_ss/train_db.py:474 in <module>                                 │
│                                                                            │
│   471 │   args = parser.parse_args()                                       │
│   472 │   args = train_util.read_config_from_file(args, parser)            │
│   473 │                                                                    │
│ ❱ 474 │   train(args)                                                      │
│   475                                                                      │
│                                                                            │
│ /root/kohya_ss/train_db.py:99 in train                                     │
│                                                                            │
│    96 │   │   │   f"gradient_accumulation_stepsが{args.gradient_accumulati │
│    97 │   │   )                                                            │
│    98 │                                                                    │
│ ❱  99 │   accelerator = train_util.prepare_accelerator(args)               │
│   100 │                                                                    │
│   101 │   # mixed precisionに対応した型を用意しておき適宜castする          │
│   102 │   weight_dtype, save_dtype = train_util.prepare_dtype(args)        │
│                                                                            │
│ /root/kohya_ss/library/train_util.py:3266 in prepare_accelerator           │
│                                                                            │
│   3263 │   │   │   if args.wandb_api_key is not None:                      │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                 │
│   3265 │                                                                   │
│ ❱ 3266 │   accelerator = Accelerator(                                      │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_step │
│   3268 │   │   mixed_precision=args.mixed_precision,                       │
│   3269 │   │   log_with=log_with,                                          │
╰────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'project_dir'
╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/miniconda3/bin/accelerate:8 in <module>                              │
│                                                                            │
│   5 from accelerate.commands.accelerate_cli import main                    │
│   6 if __name__ == '__main__':                                             │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])   │
│ ❱ 8 │   sys.exit(main())                                                   │
│   9                                                                        │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelera │
│ te_cli.py:45 in main                                                       │
│                                                                            │
│   42 │   │   exit(1)                                                       │
│   43 │                                                                     │
│   44 │   # Run                                                             │
│ ❱ 45 │   args.func(args)                                                   │
│   46                                                                       │
│   47                                                                       │
│   48 if __name__ == "__main__":                                            │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:1104 in launch_command                                                   │
│                                                                            │
│   1101 │   elif defaults is not None and defaults.compute_environment == C │
│   1102 │   │   sagemaker_launcher(defaults, args)                          │
│   1103 │   else:                                                           │
│ ❱ 1104 │   │   simple_launcher(args)                                       │
│   1105                                                                     │
│   1106                                                                     │
│   1107 def main():                                                         │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:567 in simple_launcher                                                   │
│                                                                            │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                │
│    565 │   process.wait()                                                  │
│    566 │   if process.returncode != 0:                                     │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.retu │
│    568                                                                     │
│    569                                                                     │
│    570 def multi_gpu_launcher(args):                                       │
╰────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/root/miniconda3/bin/python', 'train_db.py', 
'--enable_bucket', 
'--pretrained_model_name_or_path=/root/autodl-tmp/sd_xl_refiner_0.9.safetensor
s', '--train_data_dir=/root/autodl-tmp/data/img', '--resolution=1024,1024', 
'--output_dir=/root/autodl-tmp/data/output', 
'--logging_dir=/root/autodl-tmp/data/log', '--save_model_as=safetensors', 
'--output_name=filmXL', '--max_token_length=225', 
'--max_data_loader_n_workers=0', '--learning_rate=4e-07', 
'--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=3038', 
'--train_batch_size=1', '--max_train_steps=60750', '--save_every_n_epochs=2', 
'--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', 
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=Adafactor', 
'--optimizer_args', 'scale_parameter=False', 'relative_step=False', 
'warmup_init=False', '--max_data_loader_n_workers=0', 
'--max_token_length=225', '--keep_tokens=1', '--bucket_reso_steps=64', 
'--min_snr_gamma=5', '--shuffle_caption', '--xformers', '--bucket_no_upscale',
'--multires_noise_iterations=6', '--multires_noise_discount=0.3', 
'--wandb_api_key=False', '--sample_sampler=k_dpm_2', 
'--sample_prompts=/root/autodl-tmp/data/output/sample/prompt.txt', 
'--sample_every_n_epochs=1']' returned non-zero exit status 1.`

**Comment by stinbuaa** [comment]
`╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/kohya_ss/train_db.py:474 in <module>                                 │
│                                                                            │
│   471 │   args = parser.parse_args()                                       │
│   472 │   args = train_util.read_config_from_file(args, parser)            │
│   473 │                                                                    │
│ ❱ 474 │   train(args)                                                      │
│   475                                                                      │
│                                                                            │
│ /root/kohya_ss/train_db.py:99 in train                                     │
│                                                                            │
│    96 │   │   │   f"gradient_accumulation_stepsが{args.gradient_accumulati │
│    97 │   │   )                                                            │
│    98 │                                                                    │
│ ❱  99 │   accelerator = train_util.prepare_accelerator(args)               │
│   100 │                                                                    │
│   101 │   # mixed precisionに対応した型を用意しておき適宜castする          │
│   102 │   weight_dtype, save_dtype = train_util.prepare_dtype(args)        │
│                                                                            │
│ /root/kohya_ss/library/train_util.py:3266 in prepare_accelerator           │
│                                                                            │
│   3263 │   │   │   if args.wandb_api_key is not None:                      │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                 │
│   3265 │                                                                   │
│ ❱ 3266 │   accelerator = Accelerator(                                      │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_step │
│   3268 │   │   mixed_precision=args.mixed_precision,                       │
│   3269 │   │   log_with=log_with,                                          │
╰────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'project_dir'
╭──────────────────── Traceback (most recent call last) ─────────────────────╮
│ /root/miniconda3/bin/accelerate:8 in <module>                              │
│                                                                            │
│   5 from accelerate.commands.accelerate_cli import main                    │
│   6 if __name__ == '__main__':                                             │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])   │
│ ❱ 8 │   sys.exit(main())                                                   │
│   9                                                                        │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/accelera │
│ te_cli.py:45 in main                                                       │
│                                                                            │
│   42 │   │   exit(1)                                                       │
│   43 │                                                                     │
│   44 │   # Run                                                             │
│ ❱ 45 │   args.func(args)                                                   │
│   46                                                                       │
│   47                                                                       │
│   48 if __name__ == "__main__":                                            │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:1104 in launch_command                                                   │
│                                                                            │
│   1101 │   elif defaults is not None and defaults.compute_environment == C │
│   1102 │   │   sagemaker_launcher(defaults, args)                          │
│   1103 │   else:                                                           │
│ ❱ 1104 │   │   simple_launcher(args)                                       │
│   1105                                                                     │
│   1106                                                                     │
│   1107 def main():                                                         │
│                                                                            │
│ /root/miniconda3/lib/python3.10/site-packages/accelerate/commands/launch.p │
│ y:567 in simple_launcher                                                   │
│                                                                            │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                │
│    565 │   process.wait()                                                  │
│    566 │   if process.returncode != 0:                                     │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.retu │
│    568                                                                     │
│    569                                                                     │
│    570 def multi_gpu_launcher(args):                                       │
╰────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/root/miniconda3/bin/python', 'train_db.py', 
'--enable_bucket', 
'--pretrained_model_name_or_path=/root/autodl-tmp/sd_xl_refiner_0.9.safetensor
s', '--train_data_dir=/root/autodl-tmp/data/img', '--resolution=1024,1024', 
'--output_dir=/root/autodl-tmp/data/output', 
'--logging_dir=/root/autodl-tmp/data/log', '--save_model_as=safetensors', 
'--output_name=filmXL', '--max_token_length=225', 
'--max_data_loader_n_workers=0', '--learning_rate=4e-07', 
'--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=3038', 
'--train_batch_size=1', '--max_train_steps=60750', '--save_every_n_epochs=2', 
'--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', 
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=Adafactor', 
'--optimizer_args', 'scale_parameter=False', 'relative_step=False', 
'warmup_init=False', '--max_data_loader_n_workers=0', 
'--max_token_length=225', '--keep_tokens=1', '--bucket_reso_steps=64', 
'--min_snr_gamma=5', '--shuffle_caption', '--xformers', '--bucket_no_upscale',
'--multires_noise_iterations=6', '--multires_noise_discount=0.3', 
'--wandb_api_key=False', '--sample_sampler=k_dpm_2', 
'--sample_prompts=/root/autodl-tmp/data/output/sample/prompt.txt', 
'--sample_every_n_epochs=1']' returned non-zero exit status 1.`

**Comment by stinbuaa** [comment]
I also encountered a similar problem when training the SDXL dreambooth fine-tuning model on the linux system, and my error is as follows:
<img width="796" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/16369810/72fcbfcf-a55d-489b-91da-3dfe8fafcf7d">
Hope to get help to solve this problem

**Comment by bmaltais** [comment]
This is odd, you may want to go back to the previous release until this is fixed. I don't know what the cause might be. Kohya has not officially released the new SDXL code so it is possibly a bud.

Are you using torch 1 or 2? Make sure to use 2.

**Comment by bmaltais** [comment]
OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again.

**Comment by stinbuaa** [comment]
> OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again.好的，显然加速 0.15.0 不再适用于新的 sd-scripts 代码...我已经上传了修复程序。执行 git pull 并重试。

Thanks! I'll test the fixed version

**Comment by c0yotte** [comment]
It's now spitting out even more errors for some reason :(
<details>
  <summary>spoiler</summary>
  
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/d22b4037-710f-4e01-bcad-a0d2c80b19d3)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/26ba483d-38d7-43a8-b2f3-9fcdb2b0c052)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/33f22683-56de-4e5f-b428-0d5f3b22a437)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/a1158dcb-0496-4eba-ae8c-7c3668c0b71e)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/5edd70e0-fb74-457b-93f7-494ce4023ea0)
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/ed633705-e187-4f21-a9f5-8250e9ff1929)


</details>

**Comment by c0yotte** [comment]
> This is odd, you may want to go back to the previous release until this is fixed. I don't know what the cause might be. Kohya has not officially released the new SDXL code so it is possibly a bud.
> 
> Are you using torch 1 or 2? Make sure to use 2.

I've tried both, actually

**Comment by bmaltais** [comment]
Make sure to run torch 2. It should work. At least it work fine for me and many others that tested the sdxl code.

**Comment by c0yotte** [comment]
> Make sure to run torch 2. It should work. At least it work fine for me and many others that tested the sdxl code.

unfortunately it didn't help.
<details>
  <summary>Spoiler</summary>
![image](https://github.com/bmaltais/kohya_ss/assets/116996266/6ecce304-386a-4348-981a-62e3e2bd4bd2)

![image](https://github.com/bmaltais/kohya_ss/assets/116996266/8adfaec9-bc09-4ba0-bfb7-3e7384906a43)

</details>

**Comment by c0yotte** [comment]
The weird thing is that an old version, which I've been using in april and may, worked perfectly. I've git pulled it a couple of days ago and now it crashes every time I start training

**Comment by c0yotte** [comment]
> > 
> 
> can you use old version . my old version not working too . i though my hardware have problem so i delete it . now i don't know what version day to download .

No, i can't. I've tried git checkout to one of the older versions, but it doesn't work as it used to (i can't change model or training dataset paths, it just doesn't let me). Maybe it's because the new files from the current version are still there, they don't get deleted even after checking out to older commit. I really don't know what to do at this point

**Comment by maxryan02** [comment]
> > > 
> > 
> > 
> > can you use old version . my old version not working too . i though my hardware have problem so i delete it . now i don't know what version day to download .
> 
> No, i can't. I've tried git checkout to one of the older versions, but it doesn't work as it used to (i can't change model or training dataset paths, it just doesn't let me). Maybe it's because the new files from the current version are still there, they don't get deleted even after checking out to older commit. I really don't know what to do at this point

Don't try , i already install new win but still same error. Don't stupid like me :D

**Comment by c0yotte** [comment]
> Don't try , i already install new win but still same error. Don't stupid like me :D

You mean you've reinstalled windows and it didn't help?

**Comment by c0yotte** [comment]
I've found the reason of this bug - during the installation I've chosen "multi-gpu" instead of "no distributed training". That's it, it was THAT simple.

**Comment by maxryan02** [comment]
> I've found the reason of this bug - during the installation I've been chosing "multi-gpu" instead of "no distributed training". That's it, it was THAT simple.

no way bro.
i reinstall 3 times. 
i choose
this machine
first option
NO
NO
NO
all
fpp16

**Comment by maxryan02** [comment]
Update for who get this error : 
Delete entire folder kohya_ss.
Reinstall 

Choose Torch 2. It work.
