### ISSUE TITLE
Issue encountered when launching training with SDXL

### ISSUE THREAD

**Issue by archimedesinstitute** [bmaltais/kohya_ss#1154]
I'm newer to using Kohya, so I may be missing something. I am training LoRA using a preset. I have all the folders pointed to, running locally, and have been getting this 

<img width="1292" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/117551167/a2b3d210-733b-44e7-8ae7-a0729874e36a">

**Comment by bmaltais** [comment]
Lth latest code on the repo should fix the issue. git pull and run the gui again. Should work now. Also, make sure to install torch 2 instead of 1 as I think torch 1 might not work very well with the new sdxl code.

**Comment by archimedesinstitute** [comment]
Ok I will try an get back to you if it's not working

**Comment by Maki9009** [comment]
does the GUI work for SDXL training? if so is it on the sdxl branch or the master branch?

**Comment by bmaltais** [comment]
It is on the master branch but there have been updates done to it in the dev2 branch. Your best bet is to use the code in dev2 at the moment
