### ISSUE TITLE
Use trained Lora Model failed

### ISSUE THREAD

**Issue by YmanChris** [bmaltais/kohya_ss#1157]
I trained the Lora based on ghostmix model. But when I use the Lora model in Stable Diffusion WebUI, the error occured. Can anyone know how to resolve?
It shows:Failed to match keys when loading Lora ********
![image](https://github.com/bmaltais/kohya_ss/assets/18142592/a5e3be3f-d9f7-4745-845a-bea23e128f5b)

**Comment by InfluxOW** [comment]
I have the same problem after last update. LoRAs that were trained on previous version doesn't show an error. And despite an error LoRAs applies to the result but I'm not sure if they work correctly.

**Comment by InfluxOW** [comment]
Ok, so I performed some tests. I have a LoRA that has been trained on previous webui version which produces no errors in automatic1111. I made the same LoRA on the current webui version. And results on both LoRAs are the same either in XYZ plot and direct prompting. So I guess the error doesn't affect the result. Anyway would be good to see clean console without scarry messages :)

**Comment by YmanChris** [comment]
> Ok, so I performed some tests. I have a LoRA that has been trained on previous webui version which produces no errors in automatic1111. I made the same LoRA on the current webui version. And results on both LoRAs are the same either in XYZ plot and direct prompting. So I guess the error doesn't affect the result. Anyway would be good to see clean console without scarry messages :)

you are right.
