### ISSUE TITLE
RunPod PreBuilt template

### ISSUE THREAD

**Issue by Maki9009** [bmaltais/kohya_ss#1162]
Im running the prebuilt template, but having the 502 issue, even though GPU usage is 0 and i have waited awhile and it still hasn't started up yet

**Comment by FurkanGozukara** [comment]
I have auto installer and manual install guide

[**How To Install And Use Kohya LoRA GUI / Web UI on RunPod IO With Stable Diffusion & Automatic1111**](https://youtu.be/3uzCNrQao3o)

[![image](https://i.imgur.com/q7FPRIO.png)](https://youtu.be/3uzCNrQao3o)
