### ISSUE TITLE
5c44ba3 - RuntimeError: Input type (float) and bias type (struct c10::BFloat16) should be the same

### ISSUE THREAD

**Issue by vidiotgameboss** [bmaltais/kohya_ss#1167]
Happens when sampling image, I think it must be due to using BF16.
Error happens after pulling to 5c44ba3.

edit: Error occurs on fp16 too.

**Comment by keezinv2** [comment]
I have it exactly the same, tried to reinstall with Torch 1 and Torch 2, reselecting BF16, nothing works.

**Comment by vidiotgameboss** [comment]
> I have it exactly the same, tried to reinstall with Torch 1 and Torch 2, reselecting BF16, nothing works.

Disable sampling for now until this gets fixed and focus on Tensorboard graphs, sampling is kind of useless anyways as it is not representative of the real output.

**Comment by dareaker** [comment]
This is happening to me too. But skipping sampling has let me move past these errors

**Comment by abetteridea** [comment]
Same here when generating sample images! Selecting fp16 in Parameters results in a similar error

_Input type (float) and bias type (struct c10::Half) should be the same_

**Comment by mats4d** [comment]
try installing the dev release for the new xformers, this worked for me, and it's all good again (for now)

https://pypi.org/project/xformers/0.0.21.dev565/#history

**Comment by Lazer-AGF** [comment]
Hello all, having this issue as well with the latest release. Tried the new xformers as mentioned by mats4d. Unfortunately this didn't work for me. Running lora training without sample generation for now until a solution is found.

**Comment by mats4d** [comment]
Actually I still get the error if I train dreambooth.
But if I train Lora , zero issues, it renders the sample, I think the newest Kohya had only the Lora segment updated in the UI (with the new presets and l) maybe something was not updated for deambooth?

**Comment by Vghost161** [comment]
> Hello all, having this issue as well with the latest release. Tried the new xformers as mentioned by mats4d. Unfortunately this didn't work for me. Running lora training without sample generation for now until a solution is found.
> 
> EDIT Went back to a version of Kohya prior to the XL additions until a solution is found.

Good day, tell me how to install the necessary version of kohya_ss?

**Comment by M4X1K02** [comment]
> try installing the dev release for the new xformers, this worked for me, and it's all good again (for now)
> 
> https://pypi.org/project/xformers/0.0.21.dev565/#history

Updating to the dev version [0.0.21.dev573](https://pypi.org/project/xformers/0.0.21.dev573/) did not help in my case.
As of now I am sticking to training without samples.

**Comment by aftermath0703** [comment]
I adjusted the precision of the input and it worked.
Specifically, the following code of the \_\_call\_\_ function in library\lpw_stable_diffusion.py file `image = self.decode latents(latents)` is replaced with `image = self.decode_latents(latents.bfloat16())`

**Comment by atomantic** [comment]
make sure you are generating at 1024 rather than 512
