### ISSUE TITLE
We can't do DreamBooth training yet? someone claims he did from cli - TI training is not compatible with an SDXL model.

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1168]
Someone on reddit claims that he did from command line interface

But I am getting this error

`TI training is not compatible with an SDXL model.`

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/4cdfc684-eaa6-4195-8455-50e1f4ace2a1)

**Comment by kmacmcfarlane** [comment]
Seems like this if statement is where the issue stems from: https://github.com/bmaltais/kohya_ss/blob/d1fdce6af9b5f9417e29e1a49977ee807cc12d2b/dreambooth_gui.py#L397

**Comment by kmacmcfarlane** [comment]
For others interested, I was able to get full dreambooth (non-lora) training to start from the command-line, but got OOM errors even with 24GB VRAM
```
accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" \ 
--enable_bucket \ 
--pretrained_model_name_or_path="/home/rt/ai/models/stable-diffusion/checkpoints/sd_xl_base_0.9.safetensors" \ 
--train_data_dir="/home/rt/ai/training/stable-diffusion/psyart/kohya-sdxl-training/img" \ 
--resolution="1024,1024" \ 
--output_dir="/home/rt/ai/models/stable-diffusion/checkpoints" \ 
--logging_dir="/home/rt/ai/training/psyart/logging" \ 
--save_model_as=safetensors \ 
--output_name="sdxl_psyart_test" \ 
--lr_scheduler_num_cycles="10" \ 
--no_half_vae \ 
--learning_rate="0.0004" \ 
--lr_scheduler="constant" \ 
--train_batch_size="1" \ 
--max_train_epochs="100" \ 
--save_every_n_epochs="25" \ 
--mixed_precision="bf16" \ 
--save_precision="bf16" \ 
--cache_latents \ 
--cache_latents_to_disk \ 
--optimizer_type="Adafactor" \ 
--optimizer_args scale_parameter=False relative_step=False warmup_init=False \ 
--max_data_loader_n_workers="0" \ 
--bucket_reso_steps=64 \ 
--gradient_checkpointing \ 
--xformers \ 
--bucket_no_upscale
```

**Comment by FurkanGozukara** [comment]
> For others interested, I was able to get full dreambooth (non-lora) training to start from the command-line, but got OOM errors even with 24GB VRAM
> 
> ```
> accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" \ 
> --enable_bucket \ 
> --pretrained_model_name_or_path="/home/rt/ai/models/stable-diffusion/checkpoints/sd_xl_base_0.9.safetensors" \ 
> --train_data_dir="/home/rt/ai/training/stable-diffusion/psyart/kohya-sdxl-training/img" \ 
> --resolution="1024,1024" \ 
> --output_dir="/home/rt/ai/models/stable-diffusion/checkpoints" \ 
> --logging_dir="/home/rt/ai/training/psyart/logging" \ 
> --save_model_as=safetensors \ 
> --output_name="sdxl_psyart_test" \ 
> --lr_scheduler_num_cycles="10" \ 
> --no_half_vae \ 
> --learning_rate="0.0004" \ 
> --lr_scheduler="constant" \ 
> --train_batch_size="1" \ 
> --max_train_epochs="100" \ 
> --save_every_n_epochs="25" \ 
> --mixed_precision="bf16" \ 
> --save_precision="bf16" \ 
> --cache_latents \ 
> --cache_latents_to_disk \ 
> --optimizer_type="Adafactor" \ 
> --optimizer_args scale_parameter=False relative_step=False warmup_init=False \ 
> --max_data_loader_n_workers="0" \ 
> --bucket_reso_steps=64 \ 
> --gradient_checkpointing \ 
> --xformers \ 
> --bucket_no_upscale
> ```
> 
> Note: I had to upgrade a couple packages from what the requirements.txt brought in:
> 
> ```
> pip install bitsandbytes\>0.35
> pip install accelerate --upgrade
> ```

did you make lora work with 12 gb?

i should test dreambooth

**Comment by kmacmcfarlane** [comment]
I'm not interested in training LORAs at the moment, so I haven't tried. My understanding is LORAs use less ram than full dreambooth training.

**Comment by Osmodin** [comment]
> I'm not interested in training LORAs at the moment, so I haven't tried. My understanding is LORAs use less ram than full dreambooth training.

I am currently Dreambooth training using your command line script on 24GB (Nvidia A5000).  It seems to be using the full 24GB, or close to it, so if the card you are using is your display driver that might be the problem.  I'm using my second GPU with no displays connected which saves about 1.5GB.

**Comment by FurkanGozukara** [comment]
> Using --full_fp16 or --full_bf16 seems like the right way to go. Much less memory usage and significantly faster with good results for full Dreambooth training.

is dreambooth training supported already?

**Comment by FurkanGozukara** [comment]
> sdxl

very nice catch ty will check

**Comment by kieranxsomer** [comment]
Confirming i'm on vast and getting the same issue, but also i've seen local users use bmaltais (ones i connect with) get through - i was given their json file and everything.

Hmm, i'll see what happens, maybe i need to update stuff?

**Comment by kmacmcfarlane** [comment]
> > Using --full_fp16 or --full_bf16 seems like the right way to go. Much less memory usage and significantly faster with good results for full Dreambooth training.
> 
> is dreambooth training supported already?

I've been using caption keyword injection to try to put a keyword in there at the end, but either that method is ineffectual or SDXL doesn't keyword as hard as the 1.5/2.X versions, because my A/B comps with the keyword or not gives almost identical outputs

**Comment by kieranxsomer** [comment]
I find it funny because several people have gotten this to work, LAST NIGHT I ALMOST had it working - but i'm on a different machine same GPU today and the code's saying "NO TI TRAINING" :P 

I see Lastben's gotten theirs to work, and that's amazing but i'm --- stubborn and want to learn bmaltais XD i'm a big kid dag nabit I NEED TO LEARN THINGS! :P 

Gonna see if i can at least get lora training to work, XD

**Comment by kmacmcfarlane** [comment]
I have found that I need to kill my gnome window manager on linux or it OOM errors. It's weird but that's the final straw on the camel's back only using a few hundred MB of VRAM
