### ISSUE TITLE
which one the Install file cudaNN drivers  should i download for m1 mac ?

### ISSUE THREAD

**Issue by organicmind-pixel** [bmaltais/kohya_ss#1169]
where is the direct download file ... could anyone share the direct link it please  ?

- Distribution ?
- Version ?
- Installer Type ?

Install the cudaNN drivers by following the instructions provided in [this link](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64).

**Comment by bmaltais** [comment]
I don't think it exist for Mac anymore. Only supported under Linux and Windows.

**Comment by organicmind-pixel** [comment]
Thanks ... for the info
