### ISSUE TITLE
Extracting LoRA problem

### ISSUE THREAD

**Issue by mdlieber99** [bmaltais/kohya_ss#1181]
![Untitled](https://github.com/bmaltais/kohya_ss/assets/105756477/457dc8a5-7075-4cfa-9e4d-8ea2289f3b18)

I'm trying to extract a LoRA from a finetuned model using the parameters above.  I know I got this to work a month ago, but I must have forgot a step.  Now I get this error:

Traceback (most recent call last) ──────────────────────╮
│ /content/gdrive/MyDrive/sd/kohya_ss_colab/networks/extract_lora_from_models. │
│ py:189 in <module>                                                           │
│                                                                              │
│   186   parser = setup_parser()                                              │
│   187                                                                        │
│   188   args = parser.parse_args()                                           │
│ ❱ 189   svd(args)                                                            │
│   190                                                                        │
│                                                                              │
│ /content/gdrive/MyDrive/sd/kohya_ss_colab/networks/extract_lora_from_models. │
│ py:87 in svd                                                                 │
│                                                                              │
│    84 │   diff = diff.float()                                                │
│    85 │                                                                      │
│    86 │   if args.device:                                                    │
│ ❱  87 │     diff = diff.to(args.device)                                      │
│    88 │                                                                      │
│    89 │   diffs[lora_name] = diff                                            │
│    90                                                                        │
│                                                                              │
│ /usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:247 in        │
│ _lazy_init                                                                   │
│                                                                              │
│    244 │   │   # are found or any other error occurs                         │
│    245 │   │   if 'CUDA_MODULE_LOADING' not in os.environ:                   │
│    246 │   │   │   os.environ['CUDA_MODULE_LOADING'] = 'LAZY'                │
│ ❱  247 │   │   torch._C._cuda_init()                                         │
│    248 │   │   # Some of the queued calls may reentrantly call _lazy_init(); │
│    249 │   │   # we need to just return without initializing in that case.   │
│    250 │   │   # However, we must not let any *other* threads in!       

can you help?

**Comment by bmaltais** [comment]
Try setting the model filename in the save field. I see it is only a folder name... and this is not what it is looking for. Beside that all look good.

**Comment by mdlieber99** [comment]
That worked - thanks!

**Comment by mdlieber99** [comment]
I'm having trouble again with the extract lora function in the utilities.  Not sure, but it won't let me post a screenshot - asking for a jpg, but my screenshot is a jpg.  In any event here is what I have filled in:

Finetuned model: 
/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/RevcowPerfLev10_step_35000.ckpt

Stable diffusion base model:
/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/PerfectLevel10.safetensors

Save to:
/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/revcow.safetensors

everything else left as default.  here is the output:

python3 "networks/extract_lora_from_models.py" --save_precision float --save_to "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/revcow.safetensors" --model_org "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/PerfectLevel10.safetensors" --model_tuned "/content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/RevcowPerfLev10_step_35000.ckpt" --dim 128 --device cuda --conv_dim 128
2023-07-31 17:15:28.478035: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-31 17:15:30.487057: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-07-31 17:15:34.330257: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-07-31 17:15:34.330786: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-07-31 17:15:34.330923: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/PerfectLevel10.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/RevcowPerfLev10_step_35000.ckpt
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
Killed

any ideas?  help much appreciated!
