### ISSUE TITLE
Extracting LyCORIS LoCON problem

### ISSUE THREAD

**Issue by kazekoiiii** [bmaltais/kohya_ss#1182]
![00OXREO()3PZLDF9 C8@)0T](https://github.com/bmaltais/kohya_ss/assets/139376407/79d9deb1-1970-4ffb-9d47-d649d49cf0c3)

I'm trying to extract a Loconfrom a finetuned model but failed, Traceback (most recent call last):
  File "/root/kohya_ss/tools/lycoris_locon_extract.py", line 89, in <module>
    from lycoris.kohya_model_utils import load_models_from_stable_diffusion_checkpoint
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

**Comment by bmaltais** [comment]
I will test it out... Maybe there is an issue with the latest LyCORIS python module not having bits where they are supposed to be...

**Comment by Boldor83** [comment]
Got the same Problem, its also not working with the same error outside gui with kohakuBlueLeaf LyCORIS script command.

**Comment by le-khang** [comment]
I got the same error No module named 'lycoris.kohya_model_utils' too

**Comment by astro9ine** [comment]
same issue!  any way to fix?
