### ISSUE TITLE
After updating installation I get "the model may not be trained by `sd-scripts`." for Lora model in Automatic1111

### ISSUE THREAD

**Issue by zadokov** [bmaltais/kohya_ss#1183]
### Discussed in https://github.com/bmaltais/kohya_ss/discussions/1150

<div type='discussions-op-text'>

<sup>Originally posted by **zadokov** July 10, 2023</sup>
This is not working either when placing in standard Lora model folder or in additional-networks.
The trained Lora cannot be used.</div>

**Comment by hinablue** [comment]
Same problem here, https://github.com/bmaltais/kohya_ss/issues/1163

Dropdown the version to 21.7.16.
