### ISSUE TITLE
Modules installed outside the virtual environment were found.  No module named 'fastapi'

### ISSUE THREAD

**Issue by endlessmeiya** [bmaltais/kohya_ss#1197]
<img width="876" alt="e4ddf7fcbeba50a49de837b55dd6b20" src="https://github.com/bmaltais/kohya_ss/assets/139549030/2a3c0735-304b-4fa3-9fa2-2c7f1f278f06">
Those prompts appear after selecting 5.Start Kohya_ss GUI in browser in Kohya_ss GUI setup menu,  and  and the GUI page fails to open.
How can I fix it?  Or how to uninstall completed and retry?

**Comment by bmaltais** [comment]
Try deleting the venv folder and re-run setup. Hope it resolves the issue. If not then follow the instructions to uninstall all local modules, delete the venv and re-run setup
