### ISSUE TITLE
We cant specify custom model

### ISSUE THREAD

**Issue by axel578** [bmaltais/kohya_ss#1199]
We cant specify a custom safetensor model from the gui ( in master branch), 
the UI rework makes every tutorial obsolete.

**Comment by axel578** [comment]
I think you released broken version on master, the custom should trigger the appearance of the custom model etc.. but its not the case here

**Comment by zethfoxster** [comment]
![Screenshot 2023-07-14 202827](https://github.com/bmaltais/kohya_ss/assets/5951657/595f71c8-a0d4-4556-a95f-b4c0e04dcfe6)

maybe reinstall, I git pulled and it appears fine myself....

**Comment by bmaltais** [comment]
Strange... I will check this... And yes... The current master can be a bit buggy. I have released the sdxl code as part of it but kohya's sd-script is not yet fully tested and debugged... You may want to revert the the release prior to the sdxl introduction to regain stability.

**Comment by steelskysoftware** [comment]
> Strange... I will check this... And yes... The current master can be a bit buggy. I have released the sdxl code as part of it but kohya's sd-script is not yet fully tested and debugged... You may want to revert the the release prior to the sdxl introduction to regain stability.

Seems there are three `False and not headless` additions in this file, possibly for debug reasons and left in?

https://github.com/bmaltais/kohya_ss/blob/397bf51a8cd36104e52055358e4ffd066c5858df/library/class_source_model.py#L59C38-L59C38
