### ISSUE TITLE
API instead of GUI

### ISSUE THREAD

**Issue by ChrGriffin** [bmaltais/kohya_ss#1201]
Ironically, this particular repo has much, much more robust features for installation, provisioning, etc. than the actual sdscripts repository.

Any chance that the RunPod setup could be altered to allow this to run as a JSON API rather than a GUI?

**Comment by bmaltais** [comment]
Not sure how hard it would be. If someone create a PR to add the functionality I will gladly merge it in.

**Comment by bmaltais** [comment]
Actually... it might already be there... run the GUI and got to: http://127.0.0.1:7860/?view=api

Instructions are provided on how to use the API interface.

**Comment by ChrGriffin** [comment]
Well, that's a great find! It seems to be newish, I last pulled maybe 2 months ago and had to do a fresh pull and setup to get that page to render. Awesome!
