### ISSUE TITLE
project-dir deprecated in Accelerate 0.15.0 (train.utils.py) 

### ISSUE THREAD

**Issue by markojak** [bmaltais/kohya_ss#1207]
REF: https://github.com/bmaltais/kohya_ss/issues/1053
And any issues with `TypeError: Accelerator.__init__() got an unexpected keyword argument 'project_dir'` in `train_util.py`

Issue appears to be related to Accelerate 0.15.0 as well as newer versions
It does not accept the argument for project_dir so just comment this out LN:3270 

Note that I'm on `sdxl` branch so might be bleeding edge

**Comment by bmaltais** [comment]
are you using torch 2? I am and I don't have any issue with it. I have not used torch 1 in a while.

**Comment by markojak** [comment]
I was using the `sdxl` branch and using the requirements_linux.txt installed there. It is using Torch2 yes. 
Let's close this issue as I'm switching over to master branch and will debug from there
