### ISSUE TITLE
Cannot use the Lyco extractor utility, please help

### ISSUE THREAD

**Issue by Giganoob23** [bmaltais/kohya_ss#1208]
Cannot use the lyco extractor utility (which is the entire reason why I got this repo :/ )

Getting the following error:

Traceback (most recent call last):
  File "C:\Downloads (SSD)\Kohya\kohya_ss\tools\lycoris_locon_extract.py", line 89, in <module>
    from lycoris.kohya_model_utils import load_models_from_stable_diffusion_checkpoint
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

I followed all installation instructions to the letter. Windows 10. Python 3.10.9. Not sure what went wrong. Lora extraction works fine.

Please help

EDIT: The lycoris_locon_extract.py file in Tools has a mistake. The line:
from lycoris.kohya_model_utils import load_models_from_stable_diffusion_checkpoint

should be edited to
from lycoris.kohya.kohya_model_utils import load_models_from_stable_diffusion_checkpoint

As by default when this entire repo is installed, kohya_model_utils sits under the kohya subpackage and NOT lycoris.

...However, unfortunately, even after applying this fix, I run into other errors:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Downloads (SSD)\Kohya\kohya_ss\tools\lycoris_locon_extract.py:129 in <module>                 │
│                                                                                                  │
│   126                                                                                            │
│   127                                                                                            │
│   128 if __name__ == '__main__':                                                                 │
│ ❱ 129 │   main()                                                                                 │
│   130                                                                                            │
│                                                                                                  │
│ C:\Downloads (SSD)\Kohya\kohya_ss\tools\lycoris_locon_extract.py:97 in main                      │
│                                                                                                  │
│    94                                                                                            │
│    95 def main():                                                                                │
│    96 │   args = ARGS                                                                            │
│ ❱  97 │   base = load_models_from_stable_diffusion_checkpoint(args.is_v2, args.base_model)       │
│    98 │   db = load_models_from_stable_diffusion_checkpoint(args.is_v2, args.db_model)           │
│    99 │                                                                                          │
│   100 │   linear_mode_param = {                                                                  │
│                                                                                                  │
│ C:\Downloads (SSD)\Kohya\kohya_ss\venv\lib\site-packages\lycoris\kohya\kohya_model_utils.py:865  │
│ in load_models_from_stable_diffusion_checkpoint                                                  │
│                                                                                                  │
│    862 │   converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)         │
│    863 │                                                                                         │
│    864 │   vae = AutoencoderKL(**vae_config).to(device)                                          │
│ ❱  865 │   info = vae.load_state_dict(converted_vae_checkpoint)                                  │
│    866 │   print("loading vae:", info)                                                           │
│    867 │                                                                                         │
│    868 │   # convert text_model                                                                  │
│                                                                                                  │
│ C:\Downloads (SSD)\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:2041 in      │
│ load_state_dict                                                                                  │
│                                                                                                  │
│   2038 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   2039 │   │                                                                                     │
│   2040 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 2041 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   2042 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   2043 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   2044                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight",
"encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight",
"encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight",
"encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight",
"encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight",
"decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight",
"decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight",
"decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight",
"decoder.mid_block.attentions.0.to_out.0.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias",
"encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias",
"encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias",
"encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias",
"encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias",
"decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias",
"decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias",
"decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias",
"decoder.mid_block.attentions.0.value.weight".

**Comment by bmaltais** [comment]
I suggest you revert back to a release version before the sdxl code release. I think this is an issue introduced with the latest LyCORIS network update that reworked things internally.

**Comment by Giganoob23** [comment]
@bmaltais Thank you, will try that and update accordingly

**Comment by Giganoob23** [comment]
Yeah nvm man, after trying 3 different verified June commits before SDXL changes where literally none of the GUI buttons worked/did anything I give up.

**Comment by le-khang** [comment]
I got the same error and was about to make a new issue. Any update please?

**Comment by bmaltais** [comment]
I suggest to open an issue directly with the author of LyCORIS on his repo. I can't fix this issue... I can only update the module once he release a fix: https://github.com/KohakuBlueleaf/LyCORIS/issues

**Comment by zengjie617789** [comment]
I meet the exact error after i update the repository which i must upgrade pytorch to 2.0 to install xformers,
but when i using the old env which pytorch version is 1.13 and without installing xformers, it runs successfully.
As not installing xformers, it cost too much time to install without pytoch 2.0.

**Comment by astro9ine** [comment]
> I suggest to open an issue directly with the author of LyCORIS on his repo. I can't fix this issue... I can only update the module once he release a fix: https://github.com/KohakuBlueleaf/LyCORIS/issues

![v8fC6w4joog1](https://github.com/bmaltais/kohya_ss/assets/133167655/1c630e6c-5043-4f46-8352-50f46dc81d6c)

**Comment by astro9ine** [comment]
> I suggest to open an issue directly with the author of LyCORIS on his repo. I can't fix this issue... I can only update the module once he release a fix: https://github.com/KohakuBlueleaf/LyCORIS/issues

![#1](https://github.com/bmaltais/kohya_ss/assets/133167655/9e2e0da1-d278-4923-b89a-a2e10d40b0a7)

**Comment by bmaltais** [comment]
Darn, I am away on vacation with just a laptop. I can try to update the requirements to the latest version and push a quick update maybe

**Comment by bmaltais** [comment]
OK, fixed in the latest release
