### ISSUE TITLE
how to use sdxl lora in comfy ui and automatic?

### ISSUE THREAD

**Issue by nikolaiusa** [bmaltais/kohya_ss#1211]
Can someone send me a picture for an example?

**Comment by bmaltais** [comment]
Give this a try. Does a bit more but can be used as a starting point:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/4d766038-9f19-4641-a220-7a384090e235)

**Comment by nikolaiusa** [comment]
> Give this a try. Does a bit more but can be used as a starting point:
> 
> ![image](https://user-images.githubusercontent.com/7474674/253819292-4d766038-9f19-4641-a220-7a384090e235.png)

thx, but Png parameters None..(

**Comment by bmaltais** [comment]
Darn... github must be replacing them... Try this:

[workflow (1).zip](https://github.com/bmaltais/kohya_ss/files/12064741/workflow.1.zip)

**Comment by nikolaiusa** [comment]
> Darn... github must be replacing them... Try this:
> 
> [workflow (1).zip](https://github.com/bmaltais/kohya_ss/files/12064741/workflow.1.zip)

thx so much, 
i used this preset - locon-dadaptation-sdxl
I connect Lora but I do not see its effect. I used 26 images and there were 2600 steps in total. ( 5 saved checkpoints )
64 -64 dim alpha
may need to use other settings

**Comment by nikolaiusa** [comment]
what strength_model for lora are you using? -+
