### ISSUE TITLE
Is there a way to provide multiple configuration files and create a queue that will train one after another without manual intervention?

### ISSUE THREAD

**Issue by srbustdown** [bmaltais/kohya_ss#1212]
Is there a way to provide multiple configuration files and create a queue that will train one after another without manual intervention?

I see there are two issues related to queueing training marked as closed. But there are no instructions or UI tabs that have this feature.

https://github.com/bmaltais/kohya_ss/issues/443
https://github.com/bmaltais/kohya_ss/issues/174

**Comment by bmaltais** [comment]
Not at the moment... But it would be nice to be able to do that... I need to think of a way implement this without making it too complex for basic use.

At the moment you can you the Print command button to obtain the command that would be executed and accumulate them in a script file... Then run that...

**Comment by BelovedTomboyishGirl** [comment]
> Not at the moment... But it would be nice to be able to do that... I need to think of a way implement this without making it too complex for basic use.
> 
> At the moment you can you the Print command button to obtain the command that would be executed and accumulate them in a script file... Then run that...

A good way may be to store commands to an array when you click train button and processing them after each one finish it's about the same as doing it manually to a batch file i think.
