### ISSUE TITLE
Pause or cancel

### ISSUE THREAD

**Issue by Lazer-AGF** [bmaltais/kohya_ss#1216]
Possibly a rediculous request and not sure if anyone else would find the feature useful in any way, but having a pause/cancel training option within the GUI would be useful. I utilize the sample feature most of the time and when I see that a train is going 'wrong' due to captioning or settings I will stop the training and change whatever I need to change then restart training. Problem is, the only way I know how to stop training while it is in progress is to shut everything down and restart it.

**Comment by abetteridea** [comment]
This has been answered a few times. There is no option to pause the training in kohya scripts, sadly.

You can stop the training by pressing Ctrl-C in the terminal window. I'm interested to know softer ways to do that too!

**Comment by Lazer-AGF** [comment]
Thanks for answering that. I looked but just had not seen it posted. sorry fo rthe re-ask. Im kind-of new to the forums and the github community.

**Comment by bmaltais** [comment]
Kohya has said he was interested in adding the ctrl-c option. Maybe once he publish the official sdxl I might try to add it myself and create a PR on his repo... that way it might be possible to implement the option...

**Comment by abetteridea** [comment]
Ctrl-C works now too! It just stops the process abruptly:

![image](https://github.com/bmaltais/kohya_ss/assets/67851516/81645a09-66f8-47cf-a003-07b2e82f452d)

I assume kohya is working on a more graceful solution?

**Comment by f0yhMkKB** [comment]
This might not work for everyone, but you can suspend and resume the python process used for training itself (e.g. using Process Explorer on Windows), which effectively pauses training. Memory usage might still be an issue though.
