### ISSUE TITLE
Extra Redundant Training Process Launching

### ISSUE THREAD

**Issue by RicketySplit1** [bmaltais/kohya_ss#1218]
Sometimes when I start training a model, a duplicate training process starts running in parallel.  It's not consistent, but it seems like there's an extra "start training" operation that sometimes gets queued up if I try to run with misconfigured settings or something and then it begins once I try to run again.  I don't know if this is a GUI or browser issue but I only seem to run into it when running on my runpod and not locally despite both using the latest version.  (I'm sure it's not my mouse as it doesn't register single clicks as double in any other circumstance.)   Has anyone else encountered something like this?  It doesn't seem to be critical but it does cause my trainings to take longer and eat up twice as much VRAM, and I can't cancel without Ctrl+Cing out or crudely running another short process that takes just enough memory to kill one subprocess but not the other.

**Comment by bmaltais** [comment]
Interesting... I wonder if I could trap this in the code to detect a running training process and just report to that fact when one is discovered and just not start if it is the case... Let me explore how I could do that...

**Comment by bmaltais** [comment]
Hummm... on my local system I can't actually execute it twice... the `Train` button won't run a 2nd time until the function exit... not sure what is going on in runpod.
