### ISSUE TITLE
Can Windows install instructions be better? (more comprehensive?)

### ISSUE THREAD

**Issue by cleverestx** [bmaltais/kohya_ss#1225]
The instructions on the page for installation leave out a few steps, such as local machine installation choices, multi-GPU/CPU install options and do you want Torch Dynamo installed, etc...had no idea with my 4090 it I should choose Dynamo or not... Can't these extra steps/descriptions be added to make it easier to follow along until the point of launching into the GUI?

Thanks.

**Comment by bmaltais** [comment]
If people share their specific systems/card settings I could build something around it... but you pretty much use the defaults all around unless you have a reason not to.

**Comment by cleverestx** [comment]
Thanks. Perhaps mention that in the install guide (accept all defaults) and create a small separate header/notice section for users with a 24-bit video card (3090/4090 users) about what else is recommended? The issue is I don't know the reason to do so, but I may be missing something cool (faster/better) by not knowing what these things are for and if my system can utilize them...just a brief description line per options would go a long way...

I use a 4090 and had no idea about some of these, so I said yes to Dynamo and took the default choice for the next option; no idea if that was correct, but the UI did open... (not sure if it works yet, haven't generated anything yet with it...)

**Comment by goodglitch** [comment]
I agree with OP, install instructions can tell what options mean and then have few lines like: If you have 24Gb cards choose this, if you have 12Gb cards choose that, and if you have 8Gb cards do that, if you have less VRAM use defaults. Alternatively you may incorporate additional info in installer. Like choose this if you have... etc.

**Comment by bmaltais** [comment]
I will add a little something to the README... but essentially those are just defaults values that will be overriden by the parameters in the GUI... so just accepting the defaults is pretty much fine... unless you have more than 1 GPU and you need to specify which GPU to use for training because one of them is not compatible (like you have an AMD and an NVidia... you only want to use the NVidia for training.

**Comment by cleverestx** [comment]
> I will add a little something to the README... but essentially those are just defaults values that will be overriden by the parameters in the GUI... so just accepting the defaults is pretty much fine... unless you have more than 1 GPU and you need to specify which GPU to use for training because one of them is not compatible (like you have an AMD and an NVidia... you only want to use the NVidia for training.

Okay, thanks. So there is nothing beyond defaults I should be choosing to _optimize_ the installation if I have a system with a single 4090? I'll assume choosing to enable Dynamo and the next default choice that came up did not harm my install...

**Comment by bmaltais** [comment]
I have never used Dynamo so I am not sure what that will do. I suggest you try with the default, look at a training result, the re-run the accelerate config and set Dynamo and see what that does to the speed/results.
