### ISSUE TITLE
LoRa/Training Presets - explanation?

### ISSUE THREAD

**Issue by nailz420** [bmaltais/kohya_ss#1227]
Could we have an explanation of the various presets available in the Lora Training tab, their pro/cons and their relationship to the other parameters, hardware specifications (VRAM size for example)?

**Comment by bmaltais** [comment]
Interesting idea... but I would need time to study and document... and this would be highly dependant on the dataset... maybe one day

**Comment by nailz420** [comment]
I don't understand. You included presets but you don't know what they do or how they should be used? Why is no one else complaining about this? Is everyone who uses this tool a such expert so they doesn't care for presets? Am I the only schmuck who just now starting to train and would like to load a preset that's optimal for my specs and requirements so that I don't have to mess with all those arcane parameters?

**Comment by SeekerOfTheThicc** [comment]
Honestly I would like the preset to say what amount of vram to expect to use with those settings.  I think that's reasonable.

@nailz420 The AI training/finetuning technology advances at such a pace that the time invested into very thorough documentation is an investment that doesn't pay off.  bmaltais's gui for kohya_ss is a lot more user friendly than kohya_ss is by default- it's all command line, and I'm sure that if the technology slowed down enough that it would become much more worth the investment of time for people to make detailed and nuanced guides.  As it is right now you have to google and ask and be patient as you try things out yourself.  As someone who uses this tool I'm just happy it's easier to use than kohya_ss and that it works most of the time.

**Comment by eadnams22** [comment]
I think just a comment in the existing preset files (or the github change note) that says what it is, like, what's the difference between the 1.5 EDG LoHa and just 1.5 LoHa presets?

Could even pull it in to the empty space beside the presets dropdown, I suppose.

**Comment by ykk648** [comment]
same question, a little confusion.

I know truly about the challenging of doc mantaince for a opensource project  btw.

**Comment by christopherquenneville** [comment]
> Why is no one else complaining about this? 

Easy with the choice of words, tiger

**Comment by christopherquenneville** [comment]
> I am sorry if I don't provide everything in a perfect and free app but it is what it is at the moment.

You are doing just fine man

**Comment by dolphin-electric** [comment]
annoying af

**Comment by nabcht** [comment]
I made an assistant in [HuggingChat](https://huggingface.co/chat/)
type the name of the Json file from .\kohya_ss\presets 
and the contenant of the file and ask the assistant.

https://hf.co/chat/assistant/67a120446e4a057a9b91f7d1
