### ISSUE TITLE
Problem in Merge LyCORIS - No module named 'lycoris.kohya_model_utils'

### ISSUE THREAD

**Issue by neoraoz** [bmaltais/kohya_ss#1231]
I got a problem in Merge LyCORIS.
It was working fine, as far as I remember, but all of sudden, it's not working like this.

Error message is:
File "C:\kohya_ss\tools\merge_lycoris.py", line 41, in <module>
    from lycoris.kohya_model_utils import (
ModuleNotFoundError: No module named 'lycoris.kohya_model_utils'

the portion of the merge_lycoris.py is:
from lycoris_utils import merge
from lycoris.kohya_model_utils import (
    load_models_from_stable_diffusion_checkpoint,
    save_stable_diffusion_checkpoint,
    load_file

I've tried to sort this out by re-installing the KOHY_SS from the scratch, but it's not working with same error message, though.

Anyone who has same problem, or remedy, would you be so kind to let me know the way to solve this problem?
Many thanks in advance.

**Comment by bmaltais** [comment]
There is probably a solution by downgrading to a previous release of LyCORIS by editing the requirements.txt file... This would being back the release that had the file the utility is looking for

**Comment by neoraoz** [comment]
Thx for your comment.
I've downgraded lycoris_lora from 1.8.0.dev9 to 1.7.2, now I have different error message.
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
 Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight",  blah blah.
 
Any recommendation for the version of lycoris_lora which is working for this merging process?

**Comment by Boldor83** [comment]
downgrading the whole gui to 21.7.16 works so not sure why
lycoris_lora==0.1.6 doesn't . I haven't tried changing just that myself.

**Comment by neoraoz** [comment]
I've downloaded kohya_ss-21.7.16.zip and installed it. After installation procedure, the GUI could turned up, but all the command from action in GUI doesn't make any response, such as open file dialogue>
Please let me know how I can 'downgrading the whole gui to 21.7.16'

**Comment by neoraoz** [comment]
Many thx to your kindness

**Comment by nikolaiusa** [comment]
can you write how to downgrade? - what commands need to be executed?

**Comment by Boldor83** [comment]
git checkout df1a9ac

gradio needs fix then:
.\venv\Scripts\activate
pip uninstall fastapi
pip uninstall pydantic
pip install fastapi==0.99.1
pip install pydantic==1.10.11
https://github.com/bmaltais/kohya_ss/issues/1129#issuecomment-1626372311

**Comment by astro9ine** [comment]
any resolve ? still have this issue

**Comment by islanq** [comment]
The reply from @Boldor83 worked for me.

**Comment by DoguCatto** [comment]
I still have the error after going back as far as [v21.7.13)
re-installing doesn't help
Traceback (most recent call last):
  File "C:\kohya\kohya_ss\kohya_ss\networks\resize_lora.py", line 9, in <module>
    from library import train_util, model_util
ModuleNotFoundError: No module named 'library'
02:08:12-166806 INFO     Done resizing...


similar issues for merging and other utils
