### ISSUE TITLE
Error while running BLIP captioning in Kohya_ss version kohya_ss-21.8.3

### ISSUE THREAD

**Issue by jondoe231** [bmaltais/kohya_ss#1236]
I get the following error when trying to run BLIP captioning in Kohya_ss version kohya_ss-21.8.3. Please help.

00:47:54-819080 INFO     Version: v21.8.3
00:47:54-828177 INFO     nVidia toolkit detected
00:47:56-805450 INFO     Torch 2.0.1+cu118
00:47:56-881315 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
00:47:56-883852 INFO     Torch detected GPU: NVIDIA GeForce GTX 1660 Ti VRAM 6144 Arch (7, 5) Cores 24
00:47:56-884855 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
00:47:56-891393 INFO     Verifying modules instalation status from requirements.txt...
00:48:00-668941 INFO     headless: False
00:48:00-668941 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
00:48:39-635297 INFO     Captioning files in D:/Data/kj/KJLora/img/25_mykajal woman...
00:48:39-637337 INFO     ./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="12"
                         --top_p="0.9" --max_length="75" --min_length="25" --beam_search --caption_extension=".txt"
                         "D:/Data/kj/KJLora/img/25_mykajal woman"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/mode
                         l_large_caption.pth"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Current Working Directory is:  D:\Data\kohya\kohya_ss-21.8.3
load images from D:\Data\kj\KJLora\img\25_mykajal woman
found 58 images.
loading BLIP caption: https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth
BLIP loaded
  0%|                                                                                           | 0/58 [00:07<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\make_captions.py:200 in <module>                          │
│                                                                                                  │
│   197 │   if args.caption_extention is not None:                                                 │
│   198 │   │   args.caption_extension = args.caption_extention                                    │
│   199 │                                                                                          │
│ ❱ 200 │   main(args)                                                                             │
│   201                                                                                            │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\make_captions.py:144 in main                              │
│                                                                                                  │
│   141 │   │   │                                                                                  │
│   142 │   │   │   b_imgs.append((image_path, img_tensor))                                        │
│   143 │   │   │   if len(b_imgs) >= args.batch_size:                                             │
│ ❱ 144 │   │   │   │   run_batch(b_imgs)                                                          │
│   145 │   │   │   │   b_imgs.clear()                                                             │
│   146 │   if len(b_imgs) > 0:                                                                    │
│   147 │   │   run_batch(b_imgs)                                                                  │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\make_captions.py:97 in run_batch                          │
│                                                                                                  │
│    94 │   │                                                                                      │
│    95 │   │   with torch.no_grad():                                                              │
│    96 │   │   │   if args.beam_search:                                                           │
│ ❱  97 │   │   │   │   captions = model.generate(                                                 │
│    98 │   │   │   │   │   imgs, sample=False, num_beams=args.num_beams, max_length=args.max_le   │
│    99 │   │   │   │   )                                                                          │
│   100 │   │   │   else:                                                                          │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\blip.py:158 in generate                              │
│                                                                                                  │
│   155 │   │   │   │   │   │   │   │   │   │   │   │     **model_kwargs)                          │
│   156 │   │   else:                                                                              │
│   157 │   │   │   #beam search                                                                   │
│ ❱ 158 │   │   │   outputs = self.text_decoder.generate(input_ids=input_ids,                      │
│   159 │   │   │   │   │   │   │   │   │   │   │   │     max_length=max_length,                   │
│   160 │   │   │   │   │   │   │   │   │   │   │   │     min_length=min_length,                   │
│   161 │   │   │   │   │   │   │   │   │   │   │   │     num_beams=num_beams,                     │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\utils\_contextlib.py:115 in           │
│ decorate_context                                                                                 │
│                                                                                                  │
│   112 │   @functools.wraps(func)                                                                 │
│   113 │   def decorate_context(*args, **kwargs):                                                 │
│   114 │   │   with ctx_factory():                                                                │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                   │
│   116 │                                                                                          │
│   117 │   return decorate_context                                                                │
│   118                                                                                            │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\transformers\generation\utils.py:1611 in    │
│ generate                                                                                         │
│                                                                                                  │
│   1608 │   │   │   │   **model_kwargs,                                                           │
│   1609 │   │   │   )                                                                             │
│   1610 │   │   │   # 13. run beam search                                                         │
│ ❱ 1611 │   │   │   return self.beam_search(                                                      │
│   1612 │   │   │   │   input_ids,                                                                │
│   1613 │   │   │   │   beam_scorer,                                                              │
│   1614 │   │   │   │   logits_processor=logits_processor,                                        │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\transformers\generation\utils.py:2909 in    │
│ beam_search                                                                                      │
│                                                                                                  │
│   2906 │   │   │                                                                                 │
│   2907 │   │   │   model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)  │
│   2908 │   │   │                                                                                 │
│ ❱ 2909 │   │   │   outputs = self(                                                               │
│   2910 │   │   │   │   **model_inputs,                                                           │
│   2911 │   │   │   │   return_dict=True,                                                         │
│   2912 │   │   │   │   output_attentions=output_attentions,                                      │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:886 in forward                                │
│                                                                                                  │
│   883 │   │   if labels is not None:                                                             │
│   884 │   │   │   use_cache = False                                                              │
│   885 │   │                                                                                      │
│ ❱ 886 │   │   outputs = self.bert(                                                               │
│   887 │   │   │   input_ids,                                                                     │
│   888 │   │   │   attention_mask=attention_mask,                                                 │
│   889 │   │   │   position_ids=position_ids,                                                     │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:781 in forward                                │
│                                                                                                  │
│   778 │   │   else:                                                                              │
│   779 │   │   │   embedding_output = encoder_embeds                                              │
│   780 │   │                                                                                      │
│ ❱ 781 │   │   encoder_outputs = self.encoder(                                                    │
│   782 │   │   │   embedding_output,                                                              │
│   783 │   │   │   attention_mask=extended_attention_mask,                                        │
│   784 │   │   │   head_mask=head_mask,                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:445 in forward                                │
│                                                                                                  │
│   442 │   │   │   │   │   mode=mode,                                                             │
│   443 │   │   │   │   )                                                                          │
│   444 │   │   │   else:                                                                          │
│ ❱ 445 │   │   │   │   layer_outputs = layer_module(                                              │
│   446 │   │   │   │   │   hidden_states,                                                         │
│   447 │   │   │   │   │   attention_mask,                                                        │
│   448 │   │   │   │   │   layer_head_mask,                                                       │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:361 in forward                                │
│                                                                                                  │
│   358 │   │   if mode=='multimodal':                                                             │
│   359 │   │   │   assert encoder_hidden_states is not None, "encoder_hidden_states must be giv   │
│   360 │   │   │                                                                                  │
│ ❱ 361 │   │   │   cross_attention_outputs = self.crossattention(                                 │
│   362 │   │   │   │   attention_output,                                                          │
│   363 │   │   │   │   attention_mask,                                                            │
│   364 │   │   │   │   head_mask,                                                                 │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:277 in forward                                │
│                                                                                                  │
│   274 │   │   past_key_value=None,                                                               │
│   275 │   │   output_attentions=False,                                                           │
│   276 │   ):                                                                                     │
│ ❱ 277 │   │   self_outputs = self.self(                                                          │
│   278 │   │   │   hidden_states,                                                                 │
│   279 │   │   │   attention_mask,                                                                │
│   280 │   │   │   head_mask,                                                                     │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\venv\lib\site-packages\torch\nn\modules\module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ D:\Data\kohya\kohya_ss-21.8.3\finetune\blip\med.py:178 in forward                                │
│                                                                                                  │
│   175 │   │   past_key_value = (key_layer, value_layer)                                          │
│   176 │   │                                                                                      │
│   177 │   │   # Take the dot product between "query" and "key" to get the raw attention scores   │
│ ❱ 178 │   │   attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))          │
│   179 │   │                                                                                      │
│   180 │   │   if self.position_embedding_type == "relative_key" or self.position_embedding_typ   │
│   181 │   │   │   seq_length = hidden_states.size()[1]                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (12) must match the size of tensor b (144) at non-singleton dimension 0
00:49:08-456631 INFO     ...captioning done

**Comment by Signorlimone** [comment]
same here

**Comment by jondoe231** [comment]
Even version kohya_ss-21.8.2 is broken. So far tried the below versions and none of them worked. In older versions, the GUI buttons don't work. If anybody knows a known working version, please share.

versions tried without sucess
kohya_ss-21.5.10.tar.gz
kohya_ss-21.5.14.tar.gz
kohya_ss-21.7.10.tar.gz
kohya_ss-21.7.14.tar.gz
kohya_ss-21.7.6.tar.gz
kohya_ss-21.8.2.tar.gz
kohya_ss-21.8.3.tar.gz

**Comment by linhuaiyi** [comment]
if you don't need beam search things, you can set the number of beams to 1. it works ok.but if you need beam search things it may something wrong about that. @jondoe231

**Comment by mbednarski** [comment]
It is very likely to be related to: https://github.com/salesforce/BLIP/issues/165. I'll try to see If I can find a workaround.

**Comment by MTNZLVSK** [comment]
same issue happened to me yesterday.
Setting number of beams to 1 can temporarily solve the problem, but resulted in very simple captions.

Not very sure how to solve this problem.

**Comment by mbednarski** [comment]
The problem can be workarounded by downgrading transfomers and making a slight code change (so, that requires another instance of kohya_ss purely for beam search caption generation). I'll try to write a guide how to do it shortly.

**Comment by leothaes** [comment]
> The problem can be workarounded by downgrading transfomers and making a slight code change (so, that requires another instance of kohya_ss purely for beam search caption generation). I'll try to write a guide how to do it shortly.

I'm having the same issue. Looking forward to your reply.

In the meantime, Can someone tell me where we might find the samples generated during training as I don't seem to have a 'Models' folder in my installation.

**Comment by iqddd** [comment]
Yes. Any value above 1 doesn't work. At value 1 it generates very simple captions. If you increase the minimum length of the caption, it starts generating captions with numerous repetitions of words and phrases, or completely nonsense.

**Comment by Trojaner** [comment]
In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

**Comment by MTNZLVSK** [comment]
> In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

Thank you for the tip to downgrade transformer! Instead of run 'pip install -r requirements.txt' after editing the file 'requirement.txt', I have re-run the setup.bat from kohya_ss GUI's folder and it works perfectly fine with number of beam >1.

**Comment by zxsumd** [comment]
22:55:35-297654 INFO     Version: v21.8.5

22:55:35-302653 INFO     nVidia toolkit detected
22:55:36-411406 INFO     Torch 2.0.1+cu118
22:55:38-273582 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
22:55:38-275583 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU VRAM 16384 Arch (8, 6) Cores 58
22:55:38-276582 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
22:55:38-278586 INFO     Verifying modules instalation status from requirements.txt...
22:55:40-027806 INFO     headless: False
22:55:40-029806 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
22:56:04-949630 INFO     Captioning files in C:/Users/zxsumd/Desktop/qinlan/image/10_qinlan...
22:56:04-952627 INFO     ./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1"
                         --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt"
                         "C:/Users/zxsumd/Desktop/qinlan/image/10_qinlan"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/mode
                         l_large_caption.pth"
Traceback (most recent call last):
  File "E:\sd\kohya_ss\finetune\make_captions.py", line 10, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
22:56:05-013561 INFO     ...captioning done


What should I do！What should I do！What should I do！

**Comment by One-With-The-Freaks** [comment]
> In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

Can confirm that downgrading the transformer solves this issue! I tried for days to fix this exact problem. Finally you gave me the solution. Thank you very much!

**Comment by ArielBenichou** [comment]
> In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

Yes, both using beams=1 or downgrading the version worked for me.
Thanks

**Comment by simonk852** [comment]
> > In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.
> 
> Thank you for the tip to downgrade transformer! Instead of run 'pip install -r requirements.txt' after editing the file 'requirement.txt', I have re-run the setup.bat from kohya_ss GUI's folder and it works perfectly fine with number of beam >1.

Followed what you did and that worked perfectly!

**Comment by coderCK2** [comment]
> In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

Thank you for this! This issue is still happening, and your solution worked.

**Comment by iqddd** [comment]
Downgrade is by definition a so-so solution.

**Comment by danielaixer** [comment]
> In requirements.txt, change `transformers==x.x.x` to `transformers==4.25.1`. You may have to run `pip install -r requirements.txt` as well. This will fix the issue by downgrading transformers to a working version.

I confirm too that this works.

Also, it needs a tokenizers version below 14, such as tokenizers==0.13.3

> Downgrade is by definition a so-so solution.

At least we have a workaround...

**Comment by maxfahl** [comment]
For me the error was `PYTHON = 'python3' if os.name == 'posix' else './venv/Scripts/python.exe'` inside of `"\library\git_caption_gui.py"`. I don't have a `./venv/Scripts/python.exe` file, so when I changed this row to be `PYTHON = 'python3' if os.name == 'posix' else 'python.exe'`. Note that I'm on windows, this may differ if you're on MacOS or Linux.

**Comment by Baltzar-dev** [comment]
OS: Win11
Environment Manager: Miniconda

When reinstalling: transformers==4.41.2 
isn't working for BLIP captioning of kohyass 
because of uv project management (aka https://github.com/astral-sh/uv)
which forces different transformers version on run of gui-uv.bat.

Next method does not mind of version of transformers.

Make changes to file blip.py (\kohyass\kohya_ss\sd-scripts\finetune\blip\blip.py)
as below:

Under section of:
"from transformers import BertTokenizer"

# --- UV fix starts---
try:
    from transformers.generation import GenerationMixin
   	# Forcing BertLMHeadModel to inherit GenerationMixin dynamically
	# so all .generate() and it's methods (like _prepare_generation_config) are available to use.
    if GenerationMixin not in BertLMHeadModel.__bases__:
        BertLMHeadModel.__bases__ = (GenerationMixin,) + BertLMHeadModel.__bases__
except Exception as e:
    print(f"Error in dynamic fixing: {e}")
# --- UF fix ends ---

AFTER fix You can safely run gui-uv.bat and use BLIP captioning in KOHYASS again.
