### ISSUE TITLE
I am having many errors while training

### ISSUE THREAD

**Issue by Tahreezz** [bmaltais/kohya_ss#124]
![image](https://user-images.githubusercontent.com/91004859/217212900-65da7fcf-aaed-4508-9a2d-8b5d3bb71736.png)

**Comment by Pico52** [comment]
I am having this exact same error.  Are you using a 1080ti as well by any chance?  ChatGPT told me this means the software is not properly accessing the use of the GPU, which I have no idea why that would be.
