### ISSUE TITLE
[question]What exactly did REPEAT do during training?

### ISSUE THREAD

**Issue by pzzmyc** [bmaltais/kohya_ss#1242]
I'd like to know what repeat did during training，when I set repeat 40, in the training process,**Did it train the same image 40 times before moving on to the next image?**.
 or If I copy an image 40 times,Is the effect the same as setting the repeat40？（Maybe it's just an increase in the number of latents?） can someone help me, thank you!

**Comment by Loadus** [comment]
In short: You can get more details with more repeats but over repeats will probably make the model spit out images that are too close to the training images.
