### ISSUE TITLE
[Feature Request]: Steps rather than Epoch training option

### ISSUE THREAD

**Issue by Maki9009** [bmaltais/kohya_ss#1244]
could we have a option in the GUI for training dreambooth or lora... using max steps rather than amount of epochs, the calculation can sometimes be confusing. could we have an option to choose if i want to train based on max steps rather than max epochs?

**Comment by etha302** [comment]
you actually can, just ignore epochs. and just use repeats. Dreambooth/Lora, then go to tools, you set your dataset repeats.
Repeats x num of images = total steps, that is if you are not using reg images. Then under parameters, set "epoch" and "save every n epochs" to 1.
Then in advanced config, there is an option. Save every n steps, this is how often your models is saved during generation.
Then under sample images config: "sample every n steps" this means, when you want to generate sample images.

**Comment by rickberto** [comment]
> Repeats x num of images = total steps, that is if you are not using reg images. Then under parameters, set "epoch" and "save every n epochs" to 1.

Do I understand correctly that Repeats are Steps should be written at the beginning of the image folder name? there's no point in naming the folder "10_name" anymore?

**Comment by etha302** [comment]
> > Repeats x num of images = total steps, that is if you are not using reg images. Then under parameters, set "epoch" and "save every n epochs" to 1.
> 
> Do I understand correctly that Repeats are Steps should be written at the beginning of the image folder name? there's no point in naming the folder "10_name" anymore?

you are correct, but when you click "prepare training data" it does all this for you, so lets say you set it to 100 repeats, it will create folder 100_instance prompt_class (whatever that is in your case), you dont have to do it manually. but sure you can change it manually if you want to.

**Comment by rickberto** [comment]
> after this you just click "copy info to folders tab"

Really thank you!
