### ISSUE TITLE
can i use two 3090 cards when learning sdxl?

### ISSUE THREAD

**Issue by nikolaiusa** [bmaltais/kohya_ss#1245]
I constantly lack a little gpu memory for learning.
does it work? 24gb+24gb?

**Comment by nikolaiusa** [comment]
I saw a button in your video - Gradient checkpointing

**Comment by nikolaiusa** [comment]
How do you think it affects the quality of training?

**Comment by nikolaiusa** [comment]
because without it I can only train Network Rank <=128

**Comment by Loadus** [comment]
As I've understood it, only physical memory is visible and can not be combined with another card - I could be wrong though. But you could run two trainings at the same time if you use two cards ..
