### ISSUE TITLE
Kohya finetuning error

### ISSUE THREAD

**Issue by etha302** [bmaltais/kohya_ss#1246]
Hello,

i am getting this error when using "finetuning" method in kohya_ss: fine_tune.py: error: unrecognized arguments: --no_half_vae. It worked for me in the past just fine, but after the update i simply cannot figure out why i am getting this error, this only applies for "finetune". Dreambooth and loras are working just fine.Hope someone can help me out.
i cannot figure out where --no_half_vae, args are in fine_tune.py and if removing it would even help.
edit: also i have no extra arguments specified in the gui itself

**Comment by etha302** [comment]
i havent been able to find a solution so far, so if anyone has a clue please help me out here. this for finetuning 1.5 but exactly the same happens for sdxl.

**Comment by bmaltais** [comment]
Hummm... did I broke something in the GUI with the recent SDXL update? You are training SD1.5, right? I will add it to the list of things to check when I am back from vacation.

**Comment by etha302** [comment]
> Hummm... did I broke something in the GUI with the recent SDXL update? You are training SD1.5, right? I will add it to the list of things to check when I am back from vacation.

hi, thanks for your reply. OR im doing something really wrong, but i dont know. i would really appreciate if you take a look when you are back from vacation, here are some screenshots. ignore parameters, but it doesnt even matter what i set them to, same error always.
![2023-07-26_002803](https://github.com/bmaltais/kohya_ss/assets/139644787/a2db7447-5229-41db-bbeb-d4712a329aa2)
![2023-07-26_003947](https://github.com/bmaltais/kohya_ss/assets/139644787/60a1480d-2ecb-4b9e-be19-f014f72e8e07)

**Comment by maifree123** [comment]
open SDXL model，--no_half_vae in Parameters

**Comment by dneilsterino** [comment]
modify your config .json with:

`"sdxl_no_half_vae": false`

then open the config and train. You might also have to use:

`"bucket_no_upscale": false`

**Comment by asgeorges** [comment]
Just to add on to @maifree123 ....

You'll want to open up SDXL model option, even though you might not be using it, uncheck the half vae option, then unselect the SDXL option if you are using 1.5, etc... 

Thanks @maifree123 !

**Comment by farizy4n** [comment]
> modify your config .json with:
> 
> `"sdxl_no_half_vae": false`
> 
> then open the config and train. You might also have to use:
> 
> `"bucket_no_upscale": false`

where i can edit the script?
