### ISSUE TITLE
finetuning metadata generation bug

### ISSUE THREAD

**Issue by betterftr** [bmaltais/kohya_ss#1247]
latest dev2 or sdxl-dev
Win11

21:08:29-130069 INFO     Start Finetuning...
21:08:29-131068 INFO     ./venv/Scripts/python.exe finetune/merge_captions_to_metadata.py

'.' is not recognized as an internal or external command,
operable program or batch file.

running the script manually in venv does the job

**Comment by KAPBICH** [comment]
Same problem

**Comment by chenxluo** [comment]
I had the same issue after updating, and everything worked fine before
