### ISSUE TITLE
fastapi error: 'FieldInfo' object has no attribute 'in_'

### ISSUE THREAD

**Issue by NetyashaRoozi** [bmaltais/kohya_ss#1253]
I was having issues with installing Kohya GUI for a while, most due to user error like using python 3.10.11 which breaks bitsandbytes but now I have python 3.10.9 and am having a completely different error. I'm really not sure how I can fix this because this happens for every clean install, even when removing the pip cache

13:24:58-878761 INFO     Version: v21.8.3
13:24:58-888284 INFO     nVidia toolkit detected
13:25:01-133928 INFO     Torch 2.0.1+cu118
13:25:01-217737 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:25:01-219739 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 6144 Arch (7, 5) Cores 30
13:25:01-221887 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
13:25:01-224889 INFO     Verifying modules instalation status from requirements.txt...
13:25:05-975714 INFO     headless: False
13:25:05-985038 INFO     Load CSS...
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\DeepLearning\kohya_ss\kohya_gui.py:133 in <module>                                                                │
│                                                                                                                      │
│   132                                                                                                                │
│ ❱ 133     UI(                                                                                                        │
│   134         username=args.username,                                                                                │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\kohya_gui.py:41 in UI                                                                       │
│                                                                                                                      │
│    40                                                                                                                │
│ ❱  41     with interface:                                                                                            │
│    42         with gr.Tab('Dreambooth'):                                                                             │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\gradio\blocks.py:1473 in __exit__                                    │
│                                                                                                                      │
│   1472         self.config = self.get_config_file()                                                                  │
│ ❱ 1473         self.app = routes.App.create_app(self)                                                                │
│   1474         self.progress_tracking = any(block_fn.tracks_progress for block_fn in self.fns)                       │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\gradio\routes.py:219 in create_app                                   │
│                                                                                                                      │
│   218         @app.post("/login/")                                                                                   │
│ ❱ 219         def login(form_data: OAuth2PasswordRequestForm = Depends()):                                           │
│   220             username, password = form_data.username, form_data.password                                        │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\routing.py:706 in decorator                                  │
│                                                                                                                      │
│    705         def decorator(func: DecoratedCallable) -> DecoratedCallable:                                          │
│ ❱  706             self.add_api_route(                                                                               │
│    707                 path,                                                                                         │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\routing.py:645 in add_api_route                              │
│                                                                                                                      │
│    644         )                                                                                                     │
│ ❱  645         route = route_class(                                                                                  │
│    646             self.prefix + path,                                                                               │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\routing.py:491 in __init__                                   │
│                                                                                                                      │
│    490         assert callable(endpoint), "An endpoint must be a callable"                                           │
│ ❱  491         self.dependant = get_dependant(path=self.path_format, call=self.endpoint)                             │
│    492         for depends in self.dependencies[::-1]:                                                               │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:268 in get_dependant                   │
│                                                                                                                      │
│   267         if depends is not None:                                                                                │
│ ❱ 268             sub_dependant = get_param_sub_dependant(                                                           │
│   269                 param_name=param_name,                                                                         │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:111 in get_param_sub_dependant         │
│                                                                                                                      │
│   110     assert depends.dependency                                                                                  │
│ ❱ 111     return get_sub_dependant(                                                                                  │
│   112         depends=depends,                                                                                       │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:147 in get_sub_dependant               │
│                                                                                                                      │
│   146         )                                                                                                      │
│ ❱ 147     sub_dependant = get_dependant(                                                                             │
│   148         path=path,                                                                                             │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:289 in get_dependant                   │
│                                                                                                                      │
│   288         else:                                                                                                  │
│ ❱ 289             add_param_to_fields(field=param_field, dependant=dependant)                                        │
│   290     return dependant                                                                                           │
│                                                                                                                      │
│ D:\DeepLearning\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:462 in add_param_to_fields             │
│                                                                                                                      │
│   461     field_info = cast(params.Param, field.field_info)                                                          │
│ ❱ 462     if field_info.in_ == params.ParamTypes.path:                                                               │
│   463         dependant.path_params.append(field)                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'FieldInfo' object has no attribute 'in_'

**Comment by mbednarski** [comment]
I have the same error on linux. For me downgrading fastapi to the previous version seems to fix the problem (although I have not performed comprehensive testing)

`pip install --force-reinstall -v "fastapi==0.991"`

**Comment by NetyashaRoozi** [comment]
That does seem to fix the issue of the gui starting up! I'll try training and bring up any errors that show up

For those on windows, use 0.99.1

**Comment by Veghist** [comment]
I'm having the same problem:
│ D:\AI\kohya_ss\venv\lib\site-packages\fastapi\dependencies\utils.py:462 in add_param_to_fields                       │
│                                                                                                                      │
│   461     field_info = cast(params.Param, field.field_info)                                                          │
│ ❱ 462     if field_info.in_ == params.ParamTypes.path:                                                               │
│   463         dependant.path_params.append(field)                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'FieldInfo' object has no attribute 'in_'

**Comment by vielleicht-nicht** [comment]
> I have the same error on linux. For me downgrading fastapi to the previous version seems to fix the problem (although I have not performed comprehensive testing - but it runs).
> 
> `pip install --force-reinstall -v "fastapi==0.99.1"`
> 
> EDIT: Fixed version. It is `0.99.1` instead of `0.991` as I posted originally.

Worked on runpod as well. Needed to activate the venv, and then run the command. Thank you!

**Comment by mbednarski** [comment]
I think the root cause is that gradio that has a fixed version in `kohya_ss` https://github.com/bmaltais/kohya_ss/blob/397bf51a8cd36104e52055358e4ffd066c5858df/requirements.txt#L10

Depends on FastAPI, but they don't lock the version - https://github.com/gradio-app/gradio/blob/1c9ebdea5b288bd7358ba6e0d72d8069c021e44a/requirements.txt#L4

And FastAPI recently had a major release that seems to be not fully backward-compatible - https://github.com/tiangolo/fastapi/releases/tag/0.100.0

**Comment by Veghist** [comment]
I must be doing something wrong, but it doesn't work for me. FastAPI rollback seems successful though.

**Comment by agabekian** [comment]
Thanks so much man! Waste some time today on this..

**Comment by Veghist** [comment]
Allow me the noobest question ever: how do you exactly activate the environment?

**Comment by mbednarski** [comment]
@Veghist On my Windows machine; I use PowerShell. So the command is:

```
cd D:\AI\kohya_ss
.\venv\Scripts\Activate.ps1
# make sure it points to the python inside proper venv
Get-Command python 
pip install --force-reinstall -v "fastapi==0.99.1"
```

If it does not work, you can try running pip through Python (in case of a broken pip path)
`python -m pip install --force-reinstall -v "fastapi==0.99.1"`

**Comment by vielleicht-nicht** [comment]
> Allow me the noobest question ever: how do you exactly activate the environment? EDIT: It is just (venv) D:\AI\kohya_ss\venv\Scripts>activate right? After this I run pip install --force-reinstall -v "fastapi==0.99.1" in GIT Bash seems to run fine But no luck, no gui What am I doing wrong? EDIT: FastAPI in venv/lib/site-packages seems to remain the same fastapi-0.100.0, all files in fastapi are from original install date, so I conclude that 0.99.1 did not install

And if this is on Linux/ runpod, the instructions would be:
cd <top folder from where you activate Kohya - typically kohya_ss>
source venv/bin/activate
# It should now show '(venv)' before the folder name
pip install --force-reinstall -v "fastapi==0.99.1"

**Comment by ahmadbass3l** [comment]
I guess we need a proper solution for this. I am upgrading to pydantic v2 and getting the same error. Rolling back to previous fastapi version (0.99.1) that doesn't support pydantic v2 is not an option

**Comment by sandeza-admin** [comment]
> I guess we need a proper solution for this. I am upgrading to pydantic v2 and getting the same error. Rolling back to previous fastapi version (0.99.1) that doesn't support pydantic v2 is not an option.
> 
> EDIT: fastapi 0.100.0 is also producing the same error and the error i am encountering is not related to gradio EDIT: was solved by changing the type hints to the new pydantic Annotated convention

Could you please tell me exact procedure to solve this?
