### ISSUE TITLE
TypeError: memory_efficient_attention() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by AIrtistry** [bmaltais/kohya_ss#1261]
Hi guy's,

I get this error when I start a Lora Training, I just updated kohya_ss.
Im sorry by advance with my 2 screenshots, Im not a very techy person and dont really know what show exactly

Thanks

<img width="943" alt="Untitled" src="https://github.com/bmaltais/kohya_ss/assets/139043392/70f8e253-7026-4ea2-8932-8247edcb3284">

<img width="875" alt="Unctitled" src="https://github.com/bmaltais/kohya_ss/assets/139043392/2b58a4a6-c60f-4b7a-987a-5b4731ce3454">

**Comment by NeoLoger** [comment]
I'm having the same issue

**Comment by AIrtistry** [comment]
> TypeError: memory_efficient_attention() got an unexpected keyword argument 'scale'

no idea :(

**Comment by AIrtistry** [comment]
did a fresh install, its working now

**Comment by AIrtistry** [comment]
done
