### ISSUE TITLE
Is SDXL textual inversion already implemented?

### ISSUE THREAD

**Issue by LK2511** [bmaltais/kohya_ss#1264]
I tried training an Textual Inversion with the new SDXL 1.0 model and get following issue:

![8469f1636b81b4d0ed6dabaed0a367ea](https://github.com/bmaltais/kohya_ss/assets/26706343/ae5230e3-2263-4361-a3b5-2066d8668142)

Here are the command args used:

![9077ef607fbf68ba14043853c36ef9bb](https://github.com/bmaltais/kohya_ss/assets/26706343/3b852ace-2114-4231-b4b6-649c6ab0377b)

Tried disabling some like caching latents etc. but still get the same issue. Would appreciate help. Thanks in advance!

**Comment by wangdong2023** [comment]
same question here, I tried to train one, then ComfyUI just quits quietly after I apply the new embedding, I guess the length of embedding is different
