### ISSUE TITLE
Kohya Won't Do Anything After I Updated

### ISSUE THREAD

**Issue by BrianStark** [bmaltais/kohya_ss#1270]
hi there, I just updated Kohya but he won't do anything anymore.
I only get error messages.
I don't know how I can get out of this mess, can someone tell me more about this or better if he has a solution?
kohya is installed on an SSD.

i'm running it on a:

Windows 11 computer
CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor
RAM: 128GB
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

14:14:42-500631 INFO     Version: v21.8.3
14:14:42-510633 INFO     nVidia toolkit detected
14:14:45-428275 INFO     Torch 2.0.1+cu118
14:14:45-462285 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:14:45-465292 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
14:14:45-467282 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
14:14:45-471294 INFO     Verifying modules instalation status from requirements.txt...
14:14:49-842730 INFO     headless: False
14:14:49-847738 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
14:15:10-712020 INFO     Loading config...
14:15:13-782290 INFO     Loading config...
14:15:15-129802 INFO     Start training Dreambooth...
14:15:15-132802 INFO     Valid image folder names found in:
                         C:\Users\bstark\Desktop\Model-brianstark\brianstark
14:15:15-135801 INFO     Folder 25_brianstark : steps 1050
14:15:15-136801 INFO     max_train_steps = 8400
14:15:15-137803 INFO     stop_text_encoder_training = 0
14:15:15-138794 INFO     lr_warmup_steps = 0
14:15:15-140802 INFO     Saving training config to
                         C:\Users\bstark\Desktop\Model-brianstark\models\brianstark_20230727-141515.jso
                         n...
14:15:15-142802 INFO     accelerate launch --num_cpu_threads_per_process=2 "train_db.py"
                         --pretrained_model_name_or_path="D:/AI/stable-diffusion-webui/stable-diffusio
                         n-webui/models/Stable-diffusion/analogMadness_analogMadnessV11.safetensors"
                         --train_data_dir="C:\Users\bstark\Desktop\Model-brianstark\brianstark"
                         --resolution="768,768"
                         --output_dir="C:\Users\bstark\Desktop\Model-brianstark\models"
                         --save_model_as=safetensors --output_name="brianstark"
                         --max_data_loader_n_workers="1" --learning_rate="0.0001"
                         --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="8400"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16"
                         --seed="1234" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2
                         --bucket_reso_steps=64 --xformers --bucket_no_upscale
[14:15:25] WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.   redirects.py:27
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
prepare images.
found directory C:\Users\bstark\Desktop\Model-brianstark\brianstark\25_brianstark contains 42 image files
1050 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (768, 768)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\bstark\Desktop\Model-brianstark\brianstark\25_brianstark"
    image_count: 42
    num_repeats: 25
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: brianstark
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████| 42/42 [00:00<00:00, 1948.68it/s]
prepare dataset
prepare accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\AI\kohya_ss\kohya_ss\train_db.py:474 in <module>                                              │
│                                                                                                  │
│   471 │   args = parser.parse_args()                                                             │
│   472 │   args = train_util.read_config_from_file(args, parser)                                  │
│   473 │                                                                                          │
│ ❱ 474 │   train(args)                                                                            │
│   475                                                                                            │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\train_db.py:99 in train                                                  │
│                                                                                                  │
│    96 │   │   │   f"gradient_accumulation_stepsが{args.gradient_accumulation_steps}に設定され    │
│    97 │   │   )                                                                                  │
│    98 │                                                                                          │
│ ❱  99 │   accelerator = train_util.prepare_accelerator(args)                                     │
│   100 │                                                                                          │
│   101 │   # mixed precisionに対応した型を用意しておき適宜castする                                │
│   102 │   weight_dtype, save_dtype = train_util.prepare_dtype(args)                              │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\library\train_util.py:3513 in prepare_accelerator                        │
│                                                                                                  │
│   3510 │   │   │   if args.wandb_api_key is not None:                                            │
│   3511 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3512 │                                                                                         │
│ ❱ 3513 │   accelerator = Accelerator(                                                            │
│   3514 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3515 │   │   mixed_precision=args.mixed_precision,                                             │
│   3516 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361 in __init__         │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in __init__               │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in __init__               │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py:907 in      │
│ init_process_group                                                                               │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py:1013 in     │
│ _new_process_group_helper                                                                        │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
[14:15:41] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 15724) of binary:              api.py:672
                    D:\AI\kohya_ss\kohya_ss\venv\Scripts\python.exe
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\bstark\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\bstark\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:909 in              │
│ launch_command                                                                                   │
│                                                                                                  │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   907 │   │   multi_gpu_launcher(args)                                                           │
│   908 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                                           │
│   910 │   elif args.tpu and not args.cpu:                                                        │
│   911 │   │   if args.tpu_use_cluster:                                                           │
│   912 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:604 in              │
│ multi_gpu_launcher                                                                               │
│                                                                                                  │
│   601 │   )                                                                                      │
│   602 │   with patch_environment(**current_env):                                                 │
│   603 │   │   try:                                                                               │
│ ❱ 604 │   │   │   distrib_run.run(args)                                                          │
│   605 │   │   except Exception:                                                                  │
│   606 │   │   │   if is_rich_available() and debug:                                              │
│   607 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\run.py:785 in run               │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:134 in __call__ │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:250 in          │
│ launch_agent                                                                                     │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError:
============================================================
train_db.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-27_14:15:41
  host      : Brian-PC.home
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 15724)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by BrianStark** [comment]
I also just downloaded the update v21.8.5 but it still doesn't work and doesn't give this error.
what could be causing this and how do I fix it?


00:03:15-579288 INFO     Version: v21.8.5

00:03:15-590288 INFO     nVidia toolkit detected
00:03:18-448330 INFO     Torch 2.0.1+cu118
00:03:18-481341 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
00:03:18-483341 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
00:03:18-485341 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
00:03:18-489331 INFO     Verifying modules instalation status from requirements.txt...
00:03:22-976951 INFO     headless: False
00:03:22-982951 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
00:03:38-069459 INFO     Loading config...
00:03:39-252015 INFO     Start training LoRA Standard ...
00:03:39-254016 INFO     Checking for duplicate image filenames in training data directory...
00:03:39-258015 INFO     Valid image folder names found in:
                         C:\Users\bstark\Desktop\Model-brianstark\brianstark
00:03:39-262012 INFO     Folder 25_brianstark: 42 images found
00:03:39-263016 INFO     Folder 25_brianstark: 1050 steps
00:03:39-265015 INFO     Total steps: 1050
00:03:39-266016 INFO     Train batch size: 1
00:03:39-268016 INFO     Gradient accumulation steps: 1.0
00:03:39-269016 INFO     Epoch: 8
00:03:39-270013 INFO     Regulatization factor: 1
00:03:39-272013 INFO     max_train_steps (1050 / 1 / 1.0 * 8 * 1) = 8400
00:03:39-273016 INFO     stop_text_encoder_training = 0
00:03:39-275017 INFO     lr_warmup_steps = 0
00:03:39-276015 INFO     Saving training config to
                         C:\Users\bstark\Desktop\Model-brianstark\models\brianstark_20230728-000339.jso
                         n...
00:03:39-279014 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py"
                         --pretrained_model_name_or_path="D:/AI/stable-diffusion-webui/stable-diffusio
                         n-webui/models/Stable-diffusion/analogMadness_analogMadnessV11.safetensors"
                         --train_data_dir="C:\Users\bstark\Desktop\Model-brianstark\brianstark"
                         --resolution="768,768"
                         --output_dir="C:\Users\bstark\Desktop\Model-brianstark\models"
                         --network_alpha="1" --save_model_as=safetensors
                         --network_module=networks.lora --network_dim=8 --output_name="brianstark"
                         --lr_scheduler_num_cycles="8" --no_half_vae --learning_rate="0.0001"
                         --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="8400"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16"
                         --seed="1234" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW" --max_data_loader_n_workers="1" --clip_skip=2
                         --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0
[00:03:49] WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.   redirects.py:27
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\bstark\Desktop\Model-brianstark\brianstark\25_brianstark contains 42 image files
1050 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (768, 768)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\bstark\Desktop\Model-brianstark\brianstark\25_brianstark"
    image_count: 42
    num_repeats: 25
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: brianstark
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████| 42/42 [00:00<00:00, 1679.13it/s]
prepare dataset
preparing accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [Brian-PC]:29500 (system error: 10049 - The requested address is not valid in its context.).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\AI\kohya_ss\kohya_ss\train_network.py:990 in <module>                                         │
│                                                                                                  │
│   987 │   args = train_util.read_config_from_file(args, parser)                                  │
│   988 │                                                                                          │
│   989 │   trainer = NetworkTrainer()                                                             │
│ ❱ 990 │   trainer.train(args)                                                                    │
│   991                                                                                            │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\train_network.py:206 in train                                            │
│                                                                                                  │
│   203 │   │                                                                                      │
│   204 │   │   # acceleratorを準備する                                                            │
│   205 │   │   print("preparing accelerator")                                                     │
│ ❱ 206 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   207 │   │   is_main_process = accelerator.is_main_process                                      │
│   208 │   │                                                                                      │
│   209 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\library\train_util.py:3556 in prepare_accelerator                        │
│                                                                                                  │
│   3553 │   │   │   if args.wandb_api_key is not None:                                            │
│   3554 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3555 │                                                                                         │
│ ❱ 3556 │   accelerator = Accelerator(                                                            │
│   3557 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3558 │   │   mixed_precision=args.mixed_precision,                                             │
│   3559 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361 in __init__         │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in __init__               │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in __init__               │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py:907 in      │
│ init_process_group                                                                               │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py:1013 in     │
│ _new_process_group_helper                                                                        │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
[00:04:05] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 20840) of binary:              api.py:672
                    D:\AI\kohya_ss\kohya_ss\venv\Scripts\python.exe
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\bstark\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\bstark\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:909 in              │
│ launch_command                                                                                   │
│                                                                                                  │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   907 │   │   multi_gpu_launcher(args)                                                           │
│   908 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                                           │
│   910 │   elif args.tpu and not args.cpu:                                                        │
│   911 │   │   if args.tpu_use_cluster:                                                           │
│   912 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:604 in              │
│ multi_gpu_launcher                                                                               │
│                                                                                                  │
│   601 │   )                                                                                      │
│   602 │   with patch_environment(**current_env):                                                 │
│   603 │   │   try:                                                                               │
│ ❱ 604 │   │   │   distrib_run.run(args)                                                          │
│   605 │   │   except Exception:                                                                  │
│   606 │   │   │   if is_rich_available() and debug:                                              │
│   607 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\run.py:785 in run               │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:134 in __call__ │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ D:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api.py:250 in          │
│ launch_agent                                                                                     │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError:
============================================================
./train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-28_00:04:05
  host      : Brian-PC.home
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 20840)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by wuyue0509** [comment]
same problem

**Comment by zilvergrafix** [comment]
I have the same errors, what is the cause? I updated using git pull on root folder as suggested on documentation, do I need to delete venv folder for update all?

![Screenshot 2023-07-28 144716](https://github.com/bmaltais/kohya_ss/assets/126435153/627673a7-1037-4411-9557-803c06897afe)
![Screenshot 2023-07-28 144623](https://github.com/bmaltais/kohya_ss/assets/126435153/756b66b3-1563-4ac3-a5db-b6cd12dac145)
![Screenshot 2023-07-28 144648](https://github.com/bmaltais/kohya_ss/assets/126435153/38da3ea9-f24a-428e-851b-46db73b6d9fd)

**Comment by ViliNeto** [comment]
Same here. 
I'll go back to older versions, IDK how to fix it yet
