### ISSUE TITLE
[21.8.4 lycoris_lora 1.8.1 Issue] TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by vidiotgameboss** [bmaltais/kohya_ss#1273]
Unable to start training.

![Capture](https://github.com/bmaltais/kohya_ss/assets/63921540/f068f524-4a81-4691-8383-144b84091553)

**Comment by bmaltais** [comment]
Dang... I updated the requirements file to 1.8.1 cause it was supposed to fix an issue with LoCon extraction... Look like it now broke training... Man...  can't ever win. I will update the requirements file in master to revert to 1.8.0. I am traveling so I can't test anything at the moment.

**Comment by bmaltais** [comment]
V21.8.5 should fix the issue.

**Comment by vidiotgameboss** [comment]
> V21.8.5 should fix the issue.

Yes all good now.
