### ISSUE TITLE
No module named 'triton'

### ISSUE THREAD

**Issue by Trobyss** [bmaltais/kohya_ss#1274]
Hey ! It's seems like they is an error with triton

<img width="1098" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/43353685/a3964104-6127-4539-8492-ae3cce819abd">

Any tips ?

**Comment by vidiotgameboss** [comment]
Not related to triton but rather bitsandbytes I think, try adding bitsandbytes==0.35.0 to requirements.txt or use setup.bat option 3.
