### ISSUE TITLE
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings

### ISSUE THREAD

**Issue by WalidAliAlfaid** [bmaltais/kohya_ss#1275]
i have downloaded python from the link you provided but i got this error in setup step

Warning: Python version 3.10.9 is recommended.
Creating venv...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The system cannot find the path specified.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The system cannot find the path specified.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by bmaltais** [comment]
Have you rebooted your computer after installing Python?

**Comment by hiyour** [comment]
For Windows users - check and remove the app execution aliases for python: https://stackoverflow.com/questions/58754860/cmd-opens-windows-store-when-i-type-python
