### ISSUE TITLE
v21.8.5 is tagged as V21.8.5 (with capital) and still displays as v21.8.4 in gradio

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#1276]
For consistency, it would be nice for all releases to be tagged with a lowercase `v` rather than a capital `V` as was done with the `V21.8.5` release.

The 21.8.5 release is also displaying as `v21.8.4` within gradio instead of `v21.8.5`.

**Comment by bmaltais** [comment]
Thanks... I will update the version.
