### ISSUE TITLE
Why is it running wrong？

### ISSUE THREAD

**Issue by wuyue0509** [bmaltais/kohya_ss#1279]
14:25:24-305563 INFO     Start training LoRA Standard ...
14:25:29-617564 INFO     Checking for duplicate image filenames in training data directory...
14:25:29-620564 INFO     Valid image folder names found in: G:\Training\lora_yuanyuan\images
14:25:29-621564 INFO     Folder 30_yuanyuan: 50 images found
14:25:29-621564 INFO     Folder 30_yuanyuan: 1500 steps
14:25:29-622564 INFO     Total steps: 1500
14:25:29-623563 INFO     Train batch size: 2
14:25:29-624563 INFO     Gradient accumulation steps: 1.0
14:25:29-624563 INFO     Epoch: 5
14:25:29-625564 INFO     Regulatization factor: 1
14:25:29-626564 INFO     max_train_steps (1500 / 2 / 1.0 * 5 * 1) = 3750
14:25:29-627563 INFO     stop_text_encoder_training = 0
14:25:29-628564 INFO     lr_warmup_steps = 375
14:25:29-629564 INFO     Saving training config to G:\Training\lora_yuanyuan\model\yuanzi_20230728-142529.json...
14:25:29-631563 INFO     accelerate launch --num_cpu_threads_per_process=24 "./train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="G:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors" --train_data_dir="G:\Training\lora_yuanyuan\images" --resolution="768,768"
                         --output_dir="G:\Training\lora_yuanyuan\model" --logging_dir="G:\Training\lora_yuanyuan\log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=128 --output_name="yuanzi" --lr_scheduler_num_cycles="5" --no_half_vae --learning_rate="0.0001" --lr_scheduler="cosine_with_restarts" --lr_warmup_steps="375" --train_batch_size="2"
                         --max_train_steps="3750" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --clip_skip=2 --bucket_reso_steps=64
                         --bucket_no_upscale --noise_offset=0.0
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.0.1+cpu)
    Python  3.10.11 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\detection\anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device("cpu"),
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory G:\Training\lora_yuanyuan\images\30_yuanyuan contains 50 image files
No caption file found for 50 images. Training will continue without captions for these images. If class token exists, it will be used. / 50枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
G:\Training\lora_yuanyuan\images\30_yuanyuan\00000-0-00.png
G:\Training\lora_yuanyuan\images\30_yuanyuan\00001-0-01.png
G:\Training\lora_yuanyuan\images\30_yuanyuan\00002-0-02.png
G:\Training\lora_yuanyuan\images\30_yuanyuan\00003-0-03.png
G:\Training\lora_yuanyuan\images\30_yuanyuan\00004-0-04.png
G:\Training\lora_yuanyuan\images\30_yuanyuan\00005-0-05.png... and 45 more
1500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (768, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "G:\Training\lora_yuanyuan\images\30_yuanyuan"
    image_count: 50
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: yuanyuan
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 6249.71it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 1024), count: 30
bucket 1: resolution (576, 896), count: 90
bucket 2: resolution (640, 832), count: 60
bucket 3: resolution (640, 896), count: 330
bucket 4: resolution (704, 704), count: 180
bucket 5: resolution (768, 704), count: 30
bucket 6: resolution (768, 768), count: 30
bucket 7: resolution (896, 576), count: 30
bucket 8: resolution (896, 640), count: 210
bucket 9: resolution (960, 512), count: 30
bucket 10: resolution (960, 576), count: 120
bucket 11: resolution (1024, 512), count: 150
bucket 12: resolution (1024, 576), count: 180
bucket 13: resolution (1088, 512), count: 30
mean ar error (without repeats): 0.021488429967155446
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: G:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
import network module: networks.lora
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\kohya_ss\train_network.py:990 in <module>                                                     │
│                                                                                                  │
│   987 │   args = train_util.read_config_from_file(args, parser)                                  │
│   988 │                                                                                          │
│   989 │   trainer = NetworkTrainer()                                                             │
│ ❱ 990 │   trainer.train(args)                                                                    │
│   991                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\train_network.py:325 in train                                                        │
│                                                                                                  │
│   322 │   │   │   )                                                                              │
│   323 │   │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, ar   │
│   324 │   │                                                                                      │
│ ❱ 325 │   │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, train   │
│   326 │   │                                                                                      │
│   327 │   │   # dataloaderを準備する                                                             │
│   328 │   │   # DataLoaderのプロセス数：0はメインプロセスになる                                  │
│                                                                                                  │
│ G:\kohya_ss\library\train_util.py:3187 in get_optimizer                                          │
│                                                                                                  │
│   3184 │                                                                                         │
│   3185 │   if optimizer_type == "AdamW8bit".lower():                                             │
│   3186 │   │   try:                                                                              │
│ ❱ 3187 │   │   │   import bitsandbytes as bnb                                                    │
│   3188 │   │   except ImportError:                                                               │
│   3189 │   │   │   raise ImportError("No bitsand bytes / bitsandbytesがインストールされていない  │
│   3190 │   │   print(f"use 8-bit AdamW optimizer | {optimizer_kwargs}")                          │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__ini │
│ t__.py:6 in <module>                                                                             │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\autog │
│ functions.py:5 in <module>                                                                       │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\funct │
│ onal.py:13 in <module>                                                                           │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cexte │
│ sion.py:41 in <module>                                                                           │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cexte │
│ sion.py:37 in get_instance                                                                       │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cexte │
│ sion.py:31 in initialize                                                                         │
│                                                                                                  │
│   28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   29 │   │   else:                                                                               │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")                           │
│ ❱ 31 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   32 │                                                                                           │
│   33 │   @classmethod                                                                            │
│   34 │   def get_instance(cls):                                                                  │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:452 in        │
│ LoadLibrary                                                                                      │
│                                                                                                  │
│   449 │   │   return getattr(self, name)                                                         │
│   450 │                                                                                          │
│   451 │   def LoadLibrary(self, name):                                                           │
│ ❱ 452 │   │   return self._dlltype(name)                                                         │
│   453 │                                                                                          │
│   454 │   __class_getitem__ = classmethod(_types.GenericAlias)                                   │
│   455                                                                                            │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:364 in        │
│ __init__                                                                                         │
│                                                                                                  │
│   361 │   │   │   else:                                                                          │
│   362 │   │   │   │   import nt                                                                  │
│   363 │   │   │   │   mode = nt._LOAD_LIBRARY_SEARCH_DEFAULT_DIRS                                │
│ ❱ 364 │   │   │   │   if '/' in name or '\\' in name:                                            │
│   365 │   │   │   │   │   self._name = nt._getfullpathname(self._name)                           │
│   366 │   │   │   │   │   mode |= nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR                           │
│   367                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'WindowsPath' is not iterable
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in                  │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code         │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\command │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\command │
│ aunch.py:918 in launch_command                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\五月的小窝\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\command │
│ aunch.py:580 in simple_launcher                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\五月的小窝\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=G:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors', '--train_data_dir=G:\\Training\\lora_yuanyuan\\images', '--resolution=768,768',
'--output_dir=G:\\Training\\lora_yuanyuan\\model', '--logging_dir=G:\\Training\\lora_yuanyuan\\log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001',
'--network_dim=128', '--output_name=yuanzi', '--lr_scheduler_num_cycles=5', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=375', '--train_batch_size=2', '--max_train_steps=3750',
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--bucket_no_upscale', '--noise_offset=0.0']'
returned non-zero exit status 1.

**Comment by WilliamChen-luckbob** [comment]
看样子你的CUDA toolkit没有正确安装，安好以后会有一个软连接从/usr/local/cuda指向你的/usr/local/cuda-X.Y，其中XY为你的实际版本号。然后再去~/.bashrc中添加一个`export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH`完后`sorce ~/.bashrc`应该就可以了，我这边显卡能支持的GPU版本高，好像将CUDA 120以上的配置到环境变量总是会报错，我只安装好CUDA并添加`export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH`后他能识别到CUDA 115，目前正常运行
