### ISSUE TITLE
"TI training is not compatible with an SDXL model" when i was trying to DreamBooth training a SDXL model

### ISSUE THREAD

**Issue by sd2530615** [bmaltais/kohya_ss#1280]
i did switch to DreamBooth Tab and fill up all neccessary params,

But when i clicking start training,a warning window is pop out and shows this.

is it something wrong cuz i am trying to dreambooth something but it gives me a Ti warning?

**Comment by sd2530615** [comment]
![1222aaa](https://github.com/bmaltais/kohya_ss/assets/52244346/87629053-dba2-4c96-941f-bf5dc016160a)

**Comment by alessandro893** [comment]
Try to run from terminal, here is my command as example:

accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" \
 --pretrained_model_name_or_path="/sd_xl_base_1.0.safetensors" \
 --train_data_dir="/output/img" \
 --reg_data_dir="/output/reg" \
 --logging_dir="/output/log" \
 --output_dir="/output/model" \
 --output_name="MeXL" \
 --save_model_as=safetensors \
 --train_batch_size=1 \
 --learning_rate="1e-5" \
 --max_train_steps=18400 \
 --save_every_n_epochs=1 \
 --optimizer_type="Adafactor" \
 --xformers \
 --cache_latents \
 --cache_text_encoder_outputs \
 --optimizer_args scale_parameter=False relative_step=False warmup_init=False \
 --lr_scheduler="constant" \
 --resolution="1024,1024" \
 --mixed_precision="no" \
 --save_precision="float"

**Comment by bmaltais** [comment]
Humm... That error came while trying to do a SD1.5 dreambooth? Or was it trying to do an SSXL TI? I am traveling so my ability to help is limited at the moment.

**Comment by E2GO** [comment]
Same issue when trying to train SDXL.

**Comment by sd2530615** [comment]
> Humm... That error came while trying to do a SD1.5 dreambooth? Or was it trying to do an SSXL TI? I am traveling so my ability to help is limited at the moment.

it happens when i trying to Traning SDXL dreambooth (not TI)

**Comment by bmaltais** [comment]
Dreambooth is not supported yet by kohya_ss sd-scripts for SDXL models. Only LoRA, Finetune and TI.

**Comment by buzzz3d** [comment]
> Dreambooth is not supported yet by kohya_ss sd-scripts for SDXL models. Only LoRA, Finetune and TI.

Hi Bernard, do you have an example of settings that work for training an SDXL TI?
All the info I can find is about training LORA and I'm more interested in training embedding with it.

**Comment by jndietz** [comment]
Try using `finetune_gui.py` instead of Dreambooth.
