### ISSUE TITLE
Neither Lora nor Lycoris extractons work.

### ISSUE THREAD

**Issue by Spaceisprettybig** [bmaltais/kohya_ss#1283]
I'm unable to extract Loras any more.

I verified that there were no issues with the Finetuned model nor the base model so far as I am able to tell.

This is the process in full:

loading SD model : E:/Ai/Automatic1111/stable-diffusion-webui/models/Stable-diffusion/Base v1-5-pruned.safetensors
loading u-net: <All keys matched successfully>
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\Ai\Kohya\kohya_ss\networks\extract_lora_from_models.py:189 in <module>                        │
│                                                                                                  │
│   186   parser = setup_parser()                                                                  │
│   187                                                                                            │
│   188   args = parser.parse_args()                                                               │
│ ❱ 189   svd(args)                                                                                │
│   190                                                                                            │
│                                                                                                  │
│ E:\Ai\Kohya\kohya_ss\networks\extract_lora_from_models.py:43 in svd                              │
│                                                                                                  │
│    40   save_dtype = str_to_dtype(args.save_precision)                                           │
│    41                                                                                            │
│    42   print(f"loading SD model : {args.model_org}")                                            │
│ ❱  43   text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(ar   │
│    44   print(f"loading SD model : {args.model_tuned}")                                          │
│    45   text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffusion_checkpoint(ar   │
│    46                                                                                            │
│                                                                                                  │
│ E:\Ai\Kohya\kohya_ss\venv\lib\site-packages\library\model_util.py:871 in                         │
│ load_models_from_stable_diffusion_checkpoint                                                     │
│                                                                                                  │
│    868 │   converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)         │
│    869 │                                                                                         │
│    870 │   vae = AutoencoderKL(**vae_config).to(device)                                          │
│ ❱  871 │   info = vae.load_state_dict(converted_vae_checkpoint)                                  │
│    872 │   print("loading vae:", info)                                                           │
│    873 │                                                                                         │
│    874 │   # convert text_model                                                                  │
│                                                                                                  │
│ E:\Ai\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1604 in load_state_dict   │
│                                                                                                  │
│   1601 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   1602 │   │                                                                                     │
│   1603 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 1604 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   1605 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   1606 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   1607                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight",
"encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight",
"encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight",
"encoder.mid_block.attentions.0.to_v.bias", "encoder.mid_block.attentions.0.to_out.0.weight",
"encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_q.weight",
"decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight",
"decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight",
"decoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_out.0.weight",
"decoder.mid_block.attentions.0.to_out.0.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.key.bias",
"encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.proj_attn.bias",
"encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.query.bias",
"encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.value.bias",
"encoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.key.bias",
"decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.proj_attn.bias",
"decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.query.bias",
"decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.value.bias",
"decoder.mid_block.attentions.0.value.weight".

**Comment by astro9ine** [comment]
same

**Comment by Darkenlord1** [comment]
Getting the same error

**Comment by nayan-dhabarde** [comment]
same error
