### ISSUE TITLE
Training ultra-slow on SDXL - RTX 3060 12GB VRAM OC

### ISSUE THREAD

**Issue by Undi95** [bmaltais/kohya_ss#1285]
Hi, so let me add some context.

Setting from the training was taken from this video : https://www.youtube.com/watch?v=AY6DMBCIZ3A
The resolution I choose was 768, 768.

So, I always used collab to train my LoRA habitually, infortunatelly it seems Collab don't want me to train on SD XL (bf16 don't work and fp16 seems to make it crash).
I then tried on my local machine, I have a 16GB RAM and a new RTX 3060 12GB VRAM that I put to the test, I trained the LoRA with 63 images, 8 visualisation on each and 8 epoch for a total of 4032 step.

The problem is that it's so slow, it took 15 hours to train the LoRA completely, I tried after that to tweak the setting to use less power, but my it/s don't go lower.
I don't know what to do else, I tried some fix people have posted in the past to make the train faster, but nothing work, sadly.
I'm a little frustrated tho because I don't have the money to buy a better GC and I was thinking than 12GB VRAM will be enough to train on SD XL.

I tried pytorch1 but it's even slower...

About the LoRA, it's working fine, so that's always good to take.
So is it normal, do I really lack power to do this or there's really a problem ?
Thank you for future answer!
!
[Picture of the it/s here](https://github.com/bmaltais/kohya_ss/assets/35925808/0ae62f9c-f6de-46d0-80c8-b58a086f6965)

**Comment by Undi95** [comment]
Someone posted help on reddit post I made, the configuration work for me!
https://www.reddit.com/r/StableDiffusion/comments/15ccwpp/comment/jtvpjdi/?utm_source=share&utm_medium=web2x&context=3

Maybe try those if you have the same problem, not perfect, but way better!
Waiting for result.

**Comment by Undi95** [comment]
I tried the training setting posted but the LoRA ending up to be unusable, sadly...
If anyone have a fix or a better configuration training, I'm open to test all.

**Comment by bmaltais** [comment]
You have to train at 1024,1024 otherwise results are usually terrible and diformed. There is no easy solution to train SDXL LoRA and SDXL finetune.

**Comment by Undi95** [comment]
> You have to train at 1024,1024 otherwise results are usually terrible and diformed. There is no easy solution to train SDXL LoRA and SDXL finetune.

Just for adding more context : I got a working LoRA trained on 768,768 !
But the time to train it was unbelievebly long soooo... I will wait for better optimisation I think haha, thank you for the precision, I will try to stay at 1024,1024 and try to find setting that work.

**Comment by FurkanGozukara** [comment]
hopefully will release a tutorial for 12gb cards : will be published on SECourses : https://www.youtube.com/SECourses

doing the training atm

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/a2fda17a-d556-4f0e-aa49-fd44928087b8)

**Comment by j2l** [comment]
I know, I'm late, but I can't find your specific 3060 video after August 1 @FurkanGozukara 
Would you please write the link?

**Comment by j2l** [comment]
Thank you @FurkanGozukara ! I was searching for 3060 in the titles of your videos.
