### ISSUE TITLE
SDXL LoRA Extraction does that Work? 

### ISSUE THREAD

**Issue by Maki9009** [bmaltais/kohya_ss#1286]
Does LoRA extraction work for DB SDXL Models?

**Comment by bmaltais** [comment]
What is the error message? I have not tried extracting with the new SDXL 1.0 model... maybe something got broken with it?

**Comment by bmaltais** [comment]
I have pushed an update that will enable SDXL LoRA extraction from checkpoints. I tis in the dev2 branch:

```
git checkout dev2
git pull
.\setup.bat
.\gui.bat
```

**Comment by Maki9009** [comment]
Thank you sir, i shall test it out now

**Comment by bmaltais** [comment]
There is a new SDXL checkbox when you extract the LoRA form a model, make sure to tick it for SDXL models.

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/6ca6c7e8-d7f0-49e3-956b-66b28f02e1c6)

**Comment by Maki9009** [comment]
Thank you it works, also by the way when is DB training going to work for SDXL on the GUI? it keeps giving the TI error

**Comment by bmaltais** [comment]
Yeah... kohya_ss need to add support for it to the dreambooth trainer... not sure if he will... but if he does I will add it to the GUI.

**Comment by Maki9009** [comment]
dreambooth training does work though... iv been training DB with ur Repo.. but it only works through the command line, because the GUI error

**Comment by bmaltais** [comment]
DB Training on SDXL model work? Really? THis would be great. If you can confirm I will remove the error message in the gui and let it rip.

**Comment by Maki9009** [comment]
it does... iv literally trained like 3 models using ur repo. im currently training a DB model now

**Comment by Maki9009** [comment]
Go to the venu folder, then Scripts, then cmd "activate", then cd.. back into koyha_ss. then run 

accelerate launch --num_cpu_threads_per_process=2 "sdxl_train.py" --pretrained_model_name_or_path="E:/ComfyUI_windows_portable/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors" --train_data_dir="E:/Training/DreamBooth/rubber\img" --reg_data_dir="E:/Training/DreamBooth/artstyle\reg" --output_dir="E:/Training/DreamBooth/rubber\model" --logging_dir="E:/Training/DreamBooth/Rubber\log"  --output_name="ohwx_artstyle" --save_model_as=safetensors --train_text_encoder  --train_batch_size=1 --learning_rate="1e-5" --max_train_steps=3000 --save_every_n_steps="1500" --optimizer_type="Adafactor" --xformers --cache_latents  --optimizer_args scale_parameter=False relative_step=False warmup_init=False --lr_scheduler="constant" --resolution="1024,1024" --mixed_precision="bf16" --gradient_checkpointing

its literally been working since it was added, just through the command prompt tho

**Comment by bmaltais** [comment]
OK, give the dev2 branch a try...

```
git checkout dev2
git pull
.\setup.bat
.\gui.bat
```

Let me know how it goes.

**Comment by bmaltais** [comment]
I am asking because the dev2 branch now use bitsandbytes 0.40.1 and I am not sure how well it will work for users... and that branch will also allow DB training... but I am worried about bitsandbytes effect... The update is required to allow PagedAdamW8bit optimizer use...

**Comment by Maki9009** [comment]
can't atm training a model currently... currently asking someone from the Stable Dreambooth Discord if anyone could test it out. https://discord.gg/Yj2XxSTa 
In the tech-discussion channel

**Comment by moon47usaco** [comment]
09:59:12-502336 INFO     ./venv/Scripts/python.exe "networks\extract_lora_from_models.py" --save_precision bf16
                         --save_to "S:/Drop/Drive/SD-Data/models/Lora/sdxl/sd_xl_meg8e6-lora_1.0.safetensors"
                         --model_org "S:/Drop/Drive/SD-Data/models/Stable-diffusion/sdxl/sd_xl_base_1.0.safetensors"
                         --model_tuned
                         "S:/Drop/Drive/SD-Data/models/Stable-diffusion/sdxl/megamech/04-test25kstep/models/Full_25ks_8e
                         6_1e_100r-v2.safetensors" --dim 256 --device cpu --conv_dim 256 --clamp_quantile 1.0 --min_diff
                         0.01
Traceback (most recent call last):
  File "S:\Ai\Repos\kohya_ss\networks\extract_lora_from_models.py", line 12, in <module>
    from library import sai_model_spec, model_util, sdxl_model_util
ImportError: cannot import name 'sai_model_spec' from 'library' (S:\Ai\Repos\kohya_ss\venv\lib\site-packages\library\__init__.py)

Used the sdxl check box
