### ISSUE TITLE
Has anyone got DeepSpeed to work with SDXL training?

### ISSUE THREAD

**Issue by 2kpr** [bmaltais/kohya_ss#1289]
I'm wondering if anyone got DeepSpeed to work with SDXL training?

Be that general fine-tuning, dreambooth, or LoRA?

If so, could you show your config or explain how you got it working?

Thanks!

**Comment by Dhanamerdeka** [comment]
i also looking for this info... i hope i can get an update for this

**Comment by 2kpr** [comment]
Ok, I had to move to a machine with 128GB of system RAM, but I 'just' got 'something' working now without it crashing, I still need to test this heavily, testing various parameters/settings like ZERO, etc, but at least it seems to be working. I will post more as I test more.

For now I can say that on training loading the system RAM spikes to about 71.8GB, and during training it sits at 62.8GB of system RAM usage and 10661/12288MB of VRAM usage.

**Comment by Dhanamerdeka** [comment]
wat the......
"For now I can say that on initial loading of the training the system RAM spikes to about 71.8GB and 10661/12288MB of VRAM usage on my 3080 Ti 12GB"


that's so heavy bro

**Comment by 2kpr** [comment]
> wat the...... "For now I can say that on initial loading of the training the system RAM spikes to about 71.8GB and 10661/12288MB of VRAM usage on my 3080 Ti 12GB"
> 
> that's so heavy bro

Yea, I knewe it would be a lot, but I thought I could get away with 64GB, which I might still be able to do adjusting these params...

If you look here as a reference: https://www.reddit.com/r/StableDiffusion/comments/xwdj79/dreambooth_training_in_under_8_gb_vram_and/
You can see that even with the old sd v1.5 models the system RAM spiked up to 20-25GB with deepspeed...

**Comment by Dhanamerdeka** [comment]
> > wat the...... "For now I can say that on initial loading of the training the system RAM spikes to about 71.8GB and 10661/12288MB of VRAM usage on my 3080 Ti 12GB"
> > that's so heavy bro
> 
> Yea, I knew it would be a lot, but I thought I could get away with 64GB, which I might still be able to do adjusting these params...
> 
> If you look here as a reference: https://www.reddit.com/r/StableDiffusion/comments/xwdj79/dreambooth_training_in_under_8_gb_vram_and/ You can see that even with the old sd v1.5 models the system RAM spiked up to 20-25GB with DeepSpeed with dreambooth training...
> 
> Now, I have not used DeepSpeed with LoRA training yet, so that should require much less RAM, I was mainly/initially focused on general 'full model' SDXL fine-tuning / DreamBooth first...
> 
> Here is a quote I found elsewhere related to the DeepSpeed RAM usage:
> 
> > since you are offloading both parameters and optimizer state to CPU you would need roughly 18 bytes per model parameter. That means for 7B model you would need ~126GB of CPU memory. Please see page 3 of https://arxiv.org/pdf/1910.02054.pdf for a discussion of the memory breakdown.
> 
> Considering SDXL is roughly 3.6 billion parameters, that is roughly 64.8GB by that above calc, but I'm still going to try various settings with DeepSpeed to see what I can do and if I can run it on a machine with 64GB of RAM.
> 
> EDIT: Not that anyone wants to thrash HDs, but you can offload the DeepSpeed training to NVME and 'normal' HDs too instead of system RAM.

maybe it's time to upgrade
i just had 8 ram and 6gb vram
and it seems not able to run SDXL
