### ISSUE TITLE
Convert SDXL diffuser model into checkpoint

### ISSUE THREAD

**Issue by zyddnys** [bmaltais/kohya_ss#1294]
Is there a way to convert SDXL diffuser model into a single safetensors model?

**Comment by alessandro893** [comment]
I have same question. Want to convert sdxl-1.0 to float32 safetensors.
<img width="176" alt="Снимок экрана 2023-08-03 в 17 57 24" src="https://github.com/bmaltais/kohya_ss/assets/4077478/a58e77ce-825b-4d38-ad78-68fa1fb78ea4">

**Comment by alessandro893** [comment]
[https://github.com/huggingface/diffusers/pull/4596](url)
