### ISSUE TITLE
please anyone can  share the  training setting that work for  LoRa SDXL v1.0 in google colab please ?

### ISSUE THREAD

**Issue by organicmind-pixel** [bmaltais/kohya_ss#1298]
please share the  training setting that work for  LoRa SDXL in google colab please ?

**Comment by Undi95** [comment]
I tried to make one but Collab force me to use PyTorch 1, so bf16 isn't possible, and fp16 make it crash when I train on SD XL.
If someone succeed, I'm interested too.
