### ISSUE TITLE
Feature Request: Allow merging more than 4 lora models at a time

### ISSUE THREAD

**Issue by Hellisotherpeople** [bmaltais/kohya_ss#1300]
Currently, you can only merge up to 4 lora models at a time. I don't see why there's any particular reason why this couldn't be an arbitrarily large number of loras.

**Comment by bmaltais** [comment]
It is a GUI challenge. I can add more lines to add more loras but this end up cluttering the GUI. If someone know of a better way to add support for "n" number of loras please submit a PR for the GUI. Otherwise you can manually run the command with more models to merge.
