### ISSUE TITLE
Trying to train a SDXL Lora and I get a  'project_dir' error. can somebody help me here?

### ISSUE THREAD

**Issue by navalguijo** [bmaltais/kohya_ss#1301]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Programas\0-AI\kohya_ss-sdxl\sdxl_train_network.py:167 in <module>                            │
│                                                                                                  │
│   164 │   args = train_util.read_config_from_file(args, parser)                                  │
│   165 │                                                                                          │
│   166 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 167 │   trainer.train(args)                                                                    │
│   168                                                                                            │
│                                                                                                  │
│ C:\Programas\0-AI\kohya_ss-sdxl\train_network.py:205 in train                                    │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ C:\Programas\0-AI\kohya_ss-sdxl\library\train_util.py:3266 in prepare_accelerator                │
│                                                                                                  │
│   3263 │   │   │   if args.wandb_api_key is not None:                                            │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3265 │                                                                                         │
│ ❱ 3266 │   accelerator = Accelerator(                                                            │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3268 │   │   mixed_precision=args.mixed_precision,                                             │
│   3269 │   │   log_with=log_with,                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 'project_dir'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\navalNew03\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in                  │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\navalNew03\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code         │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Programas\0-AI\kohya_ss-sdxl\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45  │
│ in main                                                                                          │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Programas\0-AI\kohya_ss-sdxl\venv\lib\site-packages\accelerate\commands\launch.py:1104 in     │
│ launch_command                                                                                   │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ C:\Programas\0-AI\kohya_ss-sdxl\venv\lib\site-packages\accelerate\commands\launch.py:567 in      │
│ simple_launcher                                                                                  │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Programas\\0-AI\\kohya_ss-sdxl\\venv\\Scripts\\python.exe',
'./sdxl_train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=Y:/Automatic1111_130/stable-diffusion-webui/models/Stable-diffusion/SDXL/sdxlFixedvaeF
p16Remove_fixedvaeFp16.safetensors', '--train_data_dir=K:/Proyectos/AI/Skeksis/Destination\\img',
'--resolution=1024,1024', '--output_dir=K:/Proyectos/AI/Skeksis/Destination\\model',
'--logging_dir=K:/Proyectos/AI/Skeksis/Destination\\log', '--network_alpha=8', '--save_model_as=safetensors',
'--network_module=lycoris.kohya', '--network_args', 'conv_dim=4', 'conv_alpha=4', 'use_cp=False', 'algo=loha',
'--network_dropout=0', '--unet_lr=0.002', '--network_train_unet_only', '--network_dim=8',
'--output_name=SkeksisCreature', '--lr_scheduler_num_cycles=1', '--cache_text_encoder_outputs', '--no_half_vae',
'--learning_rate=0.002', '--lr_scheduler=cosine', '--train_batch_size=4', '--max_train_steps=2450',
'--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=17415',
'--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=AdamW8bit',
'--optimizer_args', 'weight_decay=0.05', 'betas=0.9,0.98', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64',
'--min_snr_gamma=5', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0357',
'--min_bucket_reso=512', '--max_bucket_reso=2048', '--log_prefix=xl-loha']' returned non-zero exit status 1.

**Comment by SileNTViP** [comment]
Try update Accelerate: "pip install -U accelerate"
