### ISSUE TITLE
All of my own trained loras just output black

### ISSUE THREAD

**Issue by Accy587** [bmaltais/kohya_ss#1303]
I am using https://github.com/bmaltais/kohya_ss to train my loras with these settings https://www.mediafire.com/file/p7hc4q8n7wuu31z/CharacterLoraSettings.json/file

I am using https://github.com/vladmandic/automatic as my stable diffusion because https://github.com/AUTOMATIC1111/stable-diffusion-webui kept giving me error issues and a reddit thread said to switch to this fork and it would fix my error issues and it did. Any other lora works just fine just not the ones that i train. My training images are all 512 x 512 like i have in the settings. I have used both stable-diffusion-v1-5 and stable-diffusion-2-1-base as my basses with the same outcome. I am running it on a new 3060 12gb so i know that it is not a gpu related issue. The sample images that it gives me are fine just not the output in stable diffusion they are all black. Any help would be greatly appreciated

**Comment by CJohnDesign** [comment]
I'm in the middle of a training right now and also getting black images in the sample images. I'm using RunPod on an A100

**Comment by Thkaal** [comment]
Um, how is this completed if it's still happening?
