### ISSUE TITLE
PermissionError: [Errno 13] Permission denied & ValueError: no metadata G:/kohya_ss/Training XL/meta_lat.json

### ISSUE THREAD

**Issue by SilverRider76** [bmaltais/kohya_ss#1314]
'Morning!
I'm going crazy, it's 2 days that I've try everything, but FT won't work.
I'm using:
Win 11 
32gb of ram
12gb RTX asus
SSD 
Python 3.10.6 ( I can't install 3.10.9 because it go in conflish with A1111)

`16:30:57-899938 INFO     Version: v21.8.5

16:30:57-907937 INFO     nVidia toolkit detected
16:31:00-012204 INFO     Torch 2.0.1+cu118
16:31:00-044203 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
16:31:00-044203 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 12288 Arch (7, 5) Cores 34
16:31:00-044203 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
16:31:00-052201 INFO     Verifying modules instalation status from requirements.txt...
16:31:03-732008 INFO     headless: False
16:31:03-732008 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7861`

This is the first problem:
`To create a public link, set `share=True` in `launch()`.
16:35:24-915495 INFO     Save as...
16:35:33-636795 INFO     G:/kohya_ss/Training XL/Aniverse XL.json
16:35:39-905714 INFO     Start Finetuning...
16:35:39-907711 INFO     ./venv/Scripts/python.exe finetune/merge_captions_to_metadata.py --caption_extension=.txt
                         "H:/A1111/Training/Imagine/images/300_Animesh" "G:/kohya_ss/Training XL/meta_cap.json"
                         --full_path
16:35:39-915703 INFO     ./venv/Scripts/python.exe finetune/prepare_buckets_latents.py
                         "H:/A1111/Training/Imagine/images/300_Animesh" "G:/kohya_ss/Training XL/meta_cap.json"
                         "G:/kohya_ss/Training XL/meta_lat.json" "G:/CKPT/sdXL_v10VAEFix.safetensors" --batch_size=1
                         --max_resolution=1024,1024 --min_bucket_reso=256 --max_bucket_reso=1024 --mixed_precision=fp16
                         --full_path
"." non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
16:35:39-926690 INFO     image_num = 2261
16:35:39-928688 INFO     repeats = 90440
16:35:39-930689 INFO     max_train_steps = 271320
16:35:39-931686 INFO     lr_warmup_steps = 0
16:35:39-933683 WARNING  Here is the trainer command as a reference. It will not be executed:

accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" --pretrained_model_name_or_path="G:/CKPT/sdXL_v10VAEFix.safetensors" --in_json="G:/kohya_ss/Training XL/meta_lat.json" --train_data_dir="H:/A1111/Training/Imagine/images/300_Animesh" --output_dir="G:/kohya_ss/Training XL/model" --logging_dir="G:/kohya_ss/Training XL/log" --dataset_repeats=40 --learning_rate=4e-07 --enable_bucket --resolution="1024,1024" --min_bucket_reso=256 --max_bucket_reso=1024 --save_model_as=safetensors --output_name="Aniverse XL V1.0" --cache_text_encoder_outputs --no_half_vae --learning_rate="4e-07" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="271320" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --caption_extension=".txt" --cache_latents --optimizer_type="Adafactor" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --save_every_n_steps="20000" --save_state --mem_eff_attn --gradient_checkpointing --full_fp16 --xformers --bucket_no_upscale --noise_offset=0.0
16:35:45-031549 INFO     Start Finetuning...
16:35:45-034548 INFO     ./venv/Scripts/python.exe finetune/merge_captions_to_metadata.py --caption_extension=.txt
                         "H:/A1111/Training/Imagine/images/300_Animesh" "G:/kohya_ss/Training XL/meta_cap.json"
                         --full_path
16:35:45-039541 INFO     ./venv/Scripts/python.exe finetune/prepare_buckets_latents.py
                         "H:/A1111/Training/Imagine/images/300_Animesh" "G:/kohya_ss/Training XL/meta_cap.json"
                         "G:/kohya_ss/Training XL/meta_lat.json" "G:/CKPT/sdXL_v10VAEFix.safetensors" --batch_size=1
                         --max_resolution=1024,1024 --min_bucket_reso=256 --max_bucket_reso=1024 --mixed_precision=fp16
                         --full_path
16:35:45-043540 INFO     The command is already running. Please wait for it to finish.
"." non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
16:35:45-052528 INFO     image_num = 2261
16:35:45-056523 INFO     repeats = 90440
16:35:45-058522 INFO     max_train_steps = 271320
16:35:45-060519 INFO     lr_warmup_steps = 0
16:35:45-062517 INFO     Saving training config to G:/kohya_ss/Training XL/model\Aniverse XL
                         V1.0_20230801-163545.json...
16:35:45-065513 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py"
                         --pretrained_model_name_or_path="G:/CKPT/sdXL_v10VAEFix.safetensors"
                         --in_json="G:/kohya_ss/Training XL/meta_lat.json"
                         --train_data_dir="H:/A1111/Training/Imagine/images/300_Animesh"
                         --output_dir="G:/kohya_ss/Training XL/model" --logging_dir="G:/kohya_ss/Training XL/log"
                         --dataset_repeats=40 --learning_rate=4e-07 --enable_bucket --resolution="1024,1024"
                         --min_bucket_reso=256 --max_bucket_reso=1024 --save_model_as=safetensors
                         --output_name="Aniverse XL V1.0" --cache_text_encoder_outputs --no_half_vae
                         --learning_rate="4e-07" --lr_scheduler="constant" --train_batch_size="1"
                         --max_train_steps="271320" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --caption_extension=".txt" --cache_latents --optimizer_type="Adafactor"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --save_every_n_steps="20000"
                         --save_state --mem_eff_attn --gradient_checkpointing --full_fp16 --xformers --bucket_no_upscale
                         --noise_offset=0.0
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Warning: SDXL has been trained with noise_offset=0.0357 / SDXLはnoise_offset=0.0357で学習されています
noise_offset is set to 0.0 / noise_offsetが0.0に設定されました
prepare tokenizers
Training with captions.`

The first Error is: 

```

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\kohya_ss\sdxl_train.py:648 in <module>                                                        │
│                                                                                                  │
│   645 │   args = parser.parse_args()                                                             │
│   646 │   args = train_util.read_config_from_file(args, parser)                                  │
│   647 │                                                                                          │
│ ❱ 648 │   train(args)                                                                            │
│   649                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\sdxl_train.py:93 in train                                                            │
│                                                                                                  │
│    90 │   │   │   │   }                                                                          │
│    91 │   │                                                                                      │
│    92 │   │   blueprint = blueprint_generator.generate(user_config, args, tokenizer=[tokenizer   │
│ ❱  93 │   │   train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.   │
│    94 │   else:                                                                                  │
│    95 │   │   train_dataset_group = train_util.load_arbitrary_dataset(args, [tokenizer1, token   │
│    96                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\library\config_util.py:426 in generate_dataset_group_by_blueprint                    │
│                                                                                                  │
│   423 │     dataset_klass = FineTuningDataset                                                    │
│   424 │                                                                                          │
│   425 │   subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in d   │
│ ❱ 426 │   dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))           │
│   427 │   datasets.append(dataset)                                                               │
│   428                                                                                            │
│   429   # print info                                                                             │
│                                                                                                  │
│ G:\kohya_ss\library\train_util.py:1479 in __init__                                               │
│                                                                                                  │
│   1476 │   │   │   │   with open(subset.metadata_file, "rt", encoding="utf-8") as f:             │
│   1477 │   │   │   │   │   metadata = json.load(f)                                               │
│   1478 │   │   │   else:                                                                         │
│ ❱ 1479 │   │   │   │   raise ValueError(f"no metadata / メタデータファイルがありません: {subset  │
│   1480 │   │   │                                                                                 │
│   1481 │   │   │   if len(metadata) < 1:                                                         │
│   1482 │   │   │   │   print(f"ignore subset with '{subset.metadata_file}': no image entries fo  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: no metadata / メタデータファイルがありません: G:/kohya_ss/Training XL/meta_lat.json
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Python311\lib\runpy.py:196 in _run_module_as_main                                             │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Python311\lib\runpy.py:86 in _run_code                                                        │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['G:\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train.py',
'--pretrained_model_name_or_path=G:/CKPT/sdXL_v10VAEFix.safetensors', '--in_json=G:/kohya_ss/Training XL/meta_lat.json',
'--train_data_dir=H:/A1111/Training/Imagine/images/300_Animesh', '--output_dir=G:/kohya_ss/Training XL/model',
'--logging_dir=G:/kohya_ss/Training XL/log', '--dataset_repeats=40', '--learning_rate=4e-07', '--enable_bucket',
'--resolution=1024,1024', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--save_model_as=safetensors',
'--output_name=Aniverse XL V1.0', '--cache_text_encoder_outputs', '--no_half_vae', '--learning_rate=4e-07',
'--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=271320', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents',
'--optimizer_type=Adafactor', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--save_every_n_steps=20000',
'--save_state', '--mem_eff_attn', '--gradient_checkpointing', '--full_fp16', '--xformers', '--bucket_no_upscale',
'--noise_offset=0.0']' returned non-zero exit status 1.
```

So I've deleted in the config the file: meta_lat.json

And now I got this error: 
```

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ G:\kohya_ss\sdxl_train.py:648 in <module>                                                        │
│                                                                                                  │
│   645 │   args = parser.parse_args()                                                             │
│   646 │   args = train_util.read_config_from_file(args, parser)                                  │
│   647 │                                                                                          │
│ ❱ 648 │   train(args)                                                                            │
│   649                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\sdxl_train.py:93 in train                                                            │
│                                                                                                  │
│    90 │   │   │   │   }                                                                          │
│    91 │   │                                                                                      │
│    92 │   │   blueprint = blueprint_generator.generate(user_config, args, tokenizer=[tokenizer   │
│ ❱  93 │   │   train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.   │
│    94 │   else:                                                                                  │
│    95 │   │   train_dataset_group = train_util.load_arbitrary_dataset(args, [tokenizer1, token   │
│    96                                                                                            │
│                                                                                                  │
│ G:\kohya_ss\library\config_util.py:426 in generate_dataset_group_by_blueprint                    │
│                                                                                                  │
│   423 │     dataset_klass = FineTuningDataset                                                    │
│   424 │                                                                                          │
│   425 │   subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in d   │
│ ❱ 426 │   dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))           │
│   427 │   datasets.append(dataset)                                                               │
│   428                                                                                            │
│   429   # print info                                                                             │
│                                                                                                  │
│ G:\kohya_ss\library\train_util.py:1476 in __init__                                               │
│                                                                                                  │
│   1473 │   │   │   # メタデータを読み込む                                                        │
│   1474 │   │   │   if os.path.exists(subset.metadata_file):                                      │
│   1475 │   │   │   │   print(f"loading existing metadata: {subset.metadata_file}")               │
│ ❱ 1476 │   │   │   │   with open(subset.metadata_file, "rt", encoding="utf-8") as f:             │
│   1477 │   │   │   │   │   metadata = json.load(f)                                               │
│   1478 │   │   │   else:                                                                         │
│   1479 │   │   │   │   raise ValueError(f"no metadata / メタデータファイルがありません: {subset  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 13] Permission denied: 'G:/kohya_ss/Training XL/'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Python311\lib\runpy.py:196 in _run_module_as_main                                             │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Python311\lib\runpy.py:86 in _run_code                                                        │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ G:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['G:\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train.py',
'--pretrained_model_name_or_path=G:/CKPT/sdXL_v10VAEFix.safetensors', '--in_json=G:/kohya_ss/Training XL/',
'--train_data_dir=H:/A1111/Training/Imagine/images/300_Animesh', '--output_dir=G:/kohya_ss/Training XL/model',
'--logging_dir=G:/kohya_ss/Training XL/log', '--dataset_repeats=40', '--learning_rate=4e-07', '--enable_bucket',
'--resolution=1024,1024', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--save_model_as=safetensors',
'--output_name=Aniverse XL V1.0', '--cache_text_encoder_outputs', '--no_half_vae', '--learning_rate=4e-07',
'--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=271320', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents',
'--optimizer_type=Adafactor', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--save_every_n_steps=20000',
'--save_state', '--mem_eff_attn', '--gradient_checkpointing', '--full_fp16', '--xformers', '--bucket_no_upscale',
'--noise_offset=0.0']' returned non-zero exit status 1.
```
I've already try:
1) Start Kohya as administrator
2) Changed the permission folder
3) try another folder
4) Total reinstall Kohya_ss (for 4 times)

Any help it will be really really appreciated! REALLY <3

**Comment by KAPBICH** [comment]
Same problem

**Comment by SilverRider76** [comment]
> Same problem

Today I've fresh installed the master branch and also the sdxl dev branch.

Same problems!

I'm really going crazy

(also I must modify the setup.bat and gui.bat because they don't start. 
The line problems is relative the cmd /k command calling the file. I've comment the lines and now they works with double click)

**Comment by KAPBICH** [comment]
> > Same problem
> 
> Today I've fresh installed the master branch and also the sdxl dev branch.
> 
> Same problems!
> 
> I'm really going crazy
> 
> (also I must modify the setup.bat and gui.bat because they don't start. The line problems is relative the cmd /k command calling the file. I've comment the lines and now they works with double click and the command: _**findstr**_ not recognised)
> 
> EDIT: Add the link at the two working files:
> 
> Gui.bat: [gui.bat](https://drive.google.com/file/d/1d49Jngu_fCwYKLcwe6KBaXa_irpXXYGp/view?usp=drivesdk)
> 
> Setup.bat [setup.bat](https://drive.google.com/file/d/1d0d515jMGuCu3vk5oI5tyi4GAkMe2Tk9/view?usp=drivesdk)

Thank you for these files! But is the error "ValueError: no metadata / メタデータファイルがありません: G:/kohya_ss/Training XL/meta_lat.json" solved? This is the main problem that makes me unable to start training.

**Comment by SilverRider76** [comment]
> > > Same problem
> > 
> > Today I've fresh installed the master branch and also the sdxl dev branch.
> > 
> > Same problems!
> > 
> > I'm really going crazy
> > 
> > (also I must modify the setup.bat and gui.bat because they don't start. The line problems is relative the cmd /k command calling the file. I've comment the lines and now they works with double click and the command: _**findstr**_ not recognised)
> > 
> > EDIT: Add the link at the two working files:
> > 
> > Gui.bat: [gui.bat](https://drive.google.com/file/d/1d49Jngu_fCwYKLcwe6KBaXa_irpXXYGp/view?usp=drivesdk)
> > 
> > Setup.bat [setup.bat](https://drive.google.com/file/d/1d0d515jMGuCu3vk5oI5tyi4GAkMe2Tk9/view?usp=drivesdk)
> 
> Thank you for these files! But is the error "ValueError: no metadata / メタデータファイルがありません: G:/kohya_ss/Training XL/meta_lat.json" solved? This is the main problem that makes me unable to start training.

Nope, the main problem is always here!
I've try everything in the setting, but nothing seems work.

**Comment by SilverRider76** [comment]
I don't know if someone can understand that, but I found another thread with the same problem and the solution.

But I don't know if is can help to fix our problem

https://github.com/Linaqruf/kohya-trainer/issues/194

and this is the script for fixing it


https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/merge_all_to_metadata.py

**Comment by KAPBICH** [comment]
> I don't know if someone can understand that, but I found another thread with the same problem and the solution.
> 
> But I don't know if is can help to fix our problem
> 
> [Linaqruf/kohya-trainer#194](https://github.com/Linaqruf/kohya-trainer/issues/194)
> 
> and this is the script for fixing it
> 
> https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/merge_all_to_metadata.py

This did not solve the problem with "ValueError: no metadata". Have you had any success in fixing the problem?

**Comment by SilverRider76** [comment]
> > I don't know if someone can understand that, but I found another thread with the same problem and the solution.
> > 
> > But I don't know if is can help to fix our problem
> > 
> > [Linaqruf/kohya-trainer#194](https://github.com/Linaqruf/kohya-trainer/issues/194)
> > 
> > and this is the script for fixing it
> > 
> > https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/merge_all_to_metadata.py
> 
> This did not solve the problem with "ValueError: no metadata". Have you had any success in fixing the problem?

I know that this is not a fix for this problem.
and no, I've no success.

I'm waiting for a new version of kohya...

**Comment by SG161222** [comment]
> > I don't know if someone can understand that, but I found another thread with the same problem and the solution.
> > But I don't know if is can help to fix our problem
> > [Linaqruf/kohya-trainer#194](https://github.com/Linaqruf/kohya-trainer/issues/194)
> > and this is the script for fixing it
> > https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/merge_all_to_metadata.py
> 
> This did not solve the problem with "ValueError: no metadata". Have you had any success in fixing the problem?



> > > I don't know if someone can understand that, but I found another thread with the same problem and the solution.
> > > But I don't know if is can help to fix our problem
> > > [Linaqruf/kohya-trainer#194](https://github.com/Linaqruf/kohya-trainer/issues/194)
> > > and this is the script for fixing it
> > > https://github.com/Linaqruf/kohya-trainer/blob/main/finetune/merge_all_to_metadata.py
> > 
> > 
> > This did not solve the problem with "ValueError: no metadata". Have you had any success in fixing the problem?
> 
> I know that this is not a fix for this problem. and no, I've no success.
> 
> I'm waiting for a new version of kohya...

I solved the problem with ValueError: no metadata
This requires some manual work, I'm in the process of writing a solution, please hold on

**Comment by SG161222** [comment]
1. Move the training data to the location C:\kohya_ss\finetune\train_data
2. Captions can be converted to .caption format using Total Commander
3. Next, activate venv in the location C:\kohya_ss\venv\Scripts with the command **activate.bat** using cmd
4. Move to the location C:\kohya_ss\finetune with the command **cd C:\kohya_ss\finetune**
5. Execute the command **python merge_captions_to_metadata.py train_data meta_cap.json**
6. Execute the command:
**python prepare_buckets_latents.py train_data meta_cap.json meta_lat.json "C:\Training\Models\sd_xl_base_1.0.safetensors" --batch_size 1 --max_resolution 768,1024 --mixed_precision fp16**

7. Move **meta_cap.json** and **meta_lat.json** to the config folder and the training data back.
8. Start training.

**Comment by SilverRider76** [comment]
> 1. Move the training data to the location C:\kohya_ss\finetune\train_data
> 2. Captions can be converted to .caption format using Total Commander
> 3. Next, activate venv in the location C:\kohya_ss\venv\Scripts with the command **activate.bat** using cmd
> 4. Move to the location C:\kohya_ss\finetune with the command **cd C:\kohya_ss\finetune**
> 5. Execute the command **python merge_captions_to_metadata.py train_data meta_cap.json**
> 6. Execute the command:
>    **python prepare_buckets_latents.py train_data meta_cap.json meta_lat.json "C:\Training\Models\sd_xl_base_1.0.safetensors" --batch_size 1 --max_resolution 768,1024 --mixed_precision fp16**
> 7. Move **meta_cap.json** and **meta_lat.json** to the config folder and the training data back
> 8. Start training

Thank you so much! I'm trying.
Can you explain better what you mean in point 1) about "train data"
Exactly what files or folders I must inside the folder train_data

**Comment by SG161222** [comment]
> > 1. Move the training data to the location C:\kohya_ss\finetune\train_data
> > 2. Captions can be converted to .caption format using Total Commander
> > 3. Next, activate venv in the location C:\kohya_ss\venv\Scripts with the command **activate.bat** using cmd
> > 4. Move to the location C:\kohya_ss\finetune with the command **cd C:\kohya_ss\finetune**
> > 5. Execute the command **python merge_captions_to_metadata.py train_data meta_cap.json**
> > 6. Execute the command:
> >    **python prepare_buckets_latents.py train_data meta_cap.json meta_lat.json "C:\Training\Models\sd_xl_base_1.0.safetensors" --batch_size 1 --max_resolution 768,1024 --mixed_precision fp16**
> > 7. Move **meta_cap.json** and **meta_lat.json** to the config folder and the training data back
> > 8. Start training
> 
> Thank you so much! I'm trying. Can you explain better what you mean in point 1) about "train data" Exactly what files or folders I must inside the folder train_data

Your images for training. Also disable "Don't upscale bucket resolution" in the GUI in the advanced parameters, it may cause an error and make sure there are no .npz files in the folder with your images. I haven't tested the training fully yet, but I'll be interested to hear about your results :)

**Comment by SilverRider76** [comment]
it seems going better, but now I got this error: RuntimeError: NaN detected in latents

the file: meta_cap.json now is correctted populated
the file meta_lat.json is empty (inside there is only {} )

any idea? have I wrong something?

**Comment by SG161222** [comment]
> it seems going better, but now I got this error: RuntimeError: NaN detected in latents
> 
> the file: meta_cap.json now is correctted populated the file meta_lat.json is empty (inside there is only {} )
> 
> any idea? have I wrong something?

Perform step 6, but replace --mixed_precision fp16 with --mixed_precision no
