### ISSUE TITLE
How to train SDXL basemodel with kohya_ss?

### ISSUE THREAD

**Issue by linkedlist771** [bmaltais/kohya_ss#1317]
Hi, I found there is the introduction of the training of the `SDXL` lora model. But I do not find the training script of the SDXL basedmodel, like the train_db.py.

**Comment by jndietz** [comment]
Are you trying to finetune, create an embedding, or create a LoRA?

**Comment by linkedlist771** [comment]
I am trying to finetune the SDXL model. I have finetuned this model with the `SDXL1.0 base`, but the output image of the pretrained model can not form a shape.

![img_v2_d3535afa-b548-4fcc-841a-911dcac82c2g](https://github.com/bmaltais/kohya_ss/assets/72634327/e6f84066-d702-4c95-ad93-3b97ca1d365f)

The parameter config of the finetune is the same as the `READMD.md`, I have no idea about this.
