### ISSUE TITLE
error when starting standard lora train with SDXL 

### ISSUE THREAD

**Issue by Jaulustus** [bmaltais/kohya_ss#1318]
C:\Kohya_SS\kohya_ss>gui.bat --listen 127.0.0.1 --server_port 7862
=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

deactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
=============================================================

08:44:36-850445 INFO     Version: v21.8.5

08:44:36-854950 INFO     nVidia toolkit detected
08:44:38-164809 INFO     Torch 2.0.1+cu118
08:44:38-179816 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
08:44:38-181325 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
08:44:38-182324 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
08:44:38-183826 INFO     Verifying modules instalation status from requirements.txt...
08:44:39-977234 INFO     headless: False
08:44:39-979236 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
08:44:51-116397 INFO     Loading config...
08:45:17-064219 INFO     Save...
08:45:27-742844 INFO     Start training LoRA Standard ...
08:45:27-743343 INFO     Checking for duplicate image filenames in training data directory...
08:45:27-744344 INFO     Valid image folder names found in: C:/Kohya_SS/train/yen/img
08:45:27-745843 INFO     Folder 100_yen_net: 24 images found
08:45:27-746343 INFO     Folder 100_yen_net: 2400 steps
08:45:27-746844 INFO     Total steps: 2400
08:45:27-747344 INFO     Train batch size: 2
08:45:27-748344 INFO     Gradient accumulation steps: 1.0
08:45:27-748843 INFO     Epoch: 10
08:45:27-748843 INFO     Regulatization factor: 1
08:45:27-749344 INFO     max_train_steps (2400 / 2 / 1.0 * 10 * 1) = 12000
08:45:27-750343 INFO     stop_text_encoder_training = 0
08:45:27-750843 INFO     lr_warmup_steps = 0
08:45:27-750843 INFO     Saving training config to C:/Kohya_SS/train/yen/mod\Yen_v1_XL_20230802-084527.json...
08:45:27-752853 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket
                         --min_bucket_reso=128 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="A:/stable-diffusion-webui/models/Stable-diffusion/New-SDXL/sd_
                         xl_base_1.0.safetensors" --train_data_dir="C:/Kohya_SS/train/yen/img" --resolution="1024,1024"
                         --output_dir="C:/Kohya_SS/train/yen/mod" --logging_dir="C:/Kohya_SS/train/yen/log"
                         --network_alpha="16" --save_model_as=safetensors --network_module=networks.lora
                         --text_encoder_lr=1.0 --unet_lr=1.0 --network_dim=32 --output_name="Yen_v1_XL"
                         --lr_scheduler_num_cycles="10" --scale_weight_norms="1" --learning_rate="1.0"
                         --lr_scheduler="cosine" --train_batch_size="2" --max_train_steps="12000"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="12345"
                         --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="Lion"
                         --optimizer_args decouple=True weight_decay=0.5 betas=0.9,0.99 use_bias_correction=False
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --gradient_checkpointing --xformers
                         --bucket_no_upscale --noise_offset=0.0357 --max_grad_norm=0 --sample_sampler=euler_a
                         --sample_prompts="C:/Kohya_SS/train/yen/mod\sample\prompt.txt" --sample_every_n_epochs="1"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory C:\Kohya_SS\train\yen\img\100_yen_net contains 24 image files
2400 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 128
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Kohya_SS\train\yen\img\100_yen_net"
    image_count: 24
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: yen_net
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 1262.62it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (448, 192), count: 100
bucket 1: resolution (448, 256), count: 100
bucket 2: resolution (448, 512), count: 100
bucket 3: resolution (512, 1024), count: 200
bucket 4: resolution (704, 1280), count: 100
bucket 5: resolution (768, 1344), count: 300
bucket 6: resolution (896, 1088), count: 100
bucket 7: resolution (960, 960), count: 100
bucket 8: resolution (1024, 832), count: 100
bucket 9: resolution (1024, 896), count: 100
bucket 10: resolution (1024, 960), count: 100
bucket 11: resolution (1024, 1024), count: 100
bucket 12: resolution (1216, 704), count: 100
bucket 13: resolution (1216, 832), count: 400
bucket 14: resolution (1344, 768), count: 400
mean ar error (without repeats): 0.042987672851102214
noise_offset is set to 0.0357 / noise_offsetが0.0357に設定されました
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: A:/stable-diffusion-webui/models/Stable-diffusion/New-SDXL/sd_xl_base_1.0.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|███████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 48072.25it/s]
caching latents...
  0%|                                                                                           | 0/24 [00:04<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Kohya_SS\kohya_ss\sdxl_train_network.py:174 in <module>                                       │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\train_network.py:252 in train                                               │
│                                                                                                  │
│   249 │   │   │   vae.requires_grad_(False)                                                      │
│   250 │   │   │   vae.eval()                                                                     │
│   251 │   │   │   with torch.no_grad():                                                          │
│ ❱ 252 │   │   │   │   train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_l   │
│   253 │   │   │   vae.to("cpu")                                                                  │
│   254 │   │   │   if torch.cuda.is_available():                                                  │
│   255 │   │   │   │   torch.cuda.empty_cache()                                                   │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\library\train_util.py:1824 in cache_latents                                 │
│                                                                                                  │
│   1821 │   def cache_latents(self, vae, vae_batch_size=1, cache_to_disk=False, is_main_process=  │
│   1822 │   │   for i, dataset in enumerate(self.datasets):                                       │
│   1823 │   │   │   print(f"[Dataset {i}]")                                                       │
│ ❱ 1824 │   │   │   dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)    │
│   1825 │                                                                                         │
│   1826 │   def cache_text_encoder_outputs(                                                       │
│   1827 │   │   self, tokenizers, text_encoders, device, weight_dtype, cache_to_disk=False, is_m  │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\library\train_util.py:873 in cache_latents                                  │
│                                                                                                  │
│    870 │   │   # iterate batches: batch doesn't have image, image will be loaded in cache_batch  │
│    871 │   │   print("caching latents...")                                                       │
│    872 │   │   for batch in tqdm(batches, smoothing=1, total=len(batches)):                      │
│ ❱  873 │   │   │   cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.rando  │
│    874 │                                                                                         │
│    875 │   # weight_dtypeを指定するとText Encoderそのもの、およひ出力がweight_dtypeになる        │
│    876 │   # SDXLでのみ有効だが、datasetのメソッドとする必要があるので、sdxl_train_util.pyでは   │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\library\train_util.py:2160 in cache_batch_latents                           │
│                                                                                                  │
│   2157 │   for info, latent, flipped_latent in zip(image_infos, latents, flipped_latents):       │
│   2158 │   │   # check NaN                                                                       │
│   2159 │   │   if torch.isnan(latents).any() or (flipped_latent is not None and torch.isnan(fli  │
│ ❱ 2160 │   │   │   raise RuntimeError(f"NaN detected in latents: {info.absolute_path}")          │
│   2161 │   │                                                                                     │
│   2162 │   │   if cache_to_disk:                                                                 │
│   2163 │   │   │   save_latents_to_disk(info.latents_npz, latent, info.latents_original_size, i  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: NaN detected in latents: C:\Kohya_SS\train\yen\img\100_yen_net\020.jpg
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in           │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Jaulustus-Desktop\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code  │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main     │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command  │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Kohya_SS\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Kohya_SS\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py',
'--enable_bucket', '--min_bucket_reso=128', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=A:/stable-diffusion-webui/models/Stable-diffusion/New-SDXL/sd_xl_base_1.0.safetensors',
'--train_data_dir=C:/Kohya_SS/train/yen/img', '--resolution=1024,1024', '--output_dir=C:/Kohya_SS/train/yen/mod',
'--logging_dir=C:/Kohya_SS/train/yen/log', '--network_alpha=16', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=1.0', '--unet_lr=1.0', '--network_dim=32',
'--output_name=Yen_v1_XL', '--lr_scheduler_num_cycles=10', '--scale_weight_norms=1', '--learning_rate=1.0',
'--lr_scheduler=cosine', '--train_batch_size=2', '--max_train_steps=12000', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--seed=12345', '--caption_extension=.txt', '--cache_latents',
'--cache_latents_to_disk', '--optimizer_type=Lion', '--optimizer_args', 'decouple=True', 'weight_decay=0.5',
'betas=0.9,0.99', 'use_bias_correction=False', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64',
'--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0357', '--max_grad_norm=0',
'--sample_sampler=euler_a', '--sample_prompts=C:/Kohya_SS/train/yen/mod\\sample\\prompt.txt',
'--sample_every_n_epochs=1']' returned non-zero exit status 1.

**Comment by VijayaMelavarige** [comment]
Seems like this issue is similar to [this](https://github.com/bmaltais/kohya_ss/issues/1103#issuecomment-1628805115).
Enable --no_half_vae.
