### ISSUE TITLE
Error while trying to train a LoRA

### ISSUE THREAD

**Issue by MrRubRub** [bmaltais/kohya_ss#1323]
I am trying to train a LoRA. After doing all the setup (folders, configuration...), when i run the training program, it gives me an error.
Here is what the gui.bat shows while executing the program:

18:01:20-853466 INFO     Loading config...
18:01:31-847827 INFO     Loading config...
18:02:17-519343 INFO     Start training LoRA Standard ...
18:02:17-520341 INFO     Checking for duplicate image filenames in training data directory...
18:02:17-522336 INFO     Valid image folder names found in: C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos
                         Stable Diffusion/LORA-Test/image
18:02:17-523333 INFO     Folder 100_Test: 20 images found
18:02:17-524331 INFO     Folder 100_Test: 2000 steps
18:02:17-525328 INFO     Total steps: 2000
18:02:17-526333 INFO     Train batch size: 1
18:02:17-528320 INFO     Gradient accumulation steps: 1.0
18:02:17-529317 INFO     Epoch: 1
18:02:17-531312 INFO     Regulatization factor: 1
18:02:17-532309 INFO     max_train_steps (2000 / 1 / 1.0 * 1 * 1) = 2000
18:02:17-533306 INFO     stop_text_encoder_training = 0
18:02:17-534304 INFO     lr_warmup_steps = 0
18:02:17-535301 INFO     Saving training config to C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
                         Diffusion/LORA-Test/model\Test_20230803-180217.json...
18:02:17-538303 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py"
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
                         Diffusion/LORA-Test/image" --resolution="512,512"
                         --output_dir="C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
                         Diffusion/LORA-Test/model"
                         --logging_dir="C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
                         Diffusion/LORA-Test/model/sample" --network_alpha="128" --save_model_as=safetensors
                         --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=128
                         --output_name="Test" --lr_scheduler_num_cycles="1" --no_half_vae --learning_rate="0.0001"
                         --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="2000"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234"
                         --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit"
                         --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn
                         --gradient_checkpointing --xformers --bucket_no_upscale --noise_offset=0.0
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\vicll\Desktop\Diseño\DIBUJAR_CON_IA\Proyectos Stable Diffusion\LORA-Test\image\100_Test contains 20 image files
2000 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\vicll\Desktop\Diseño\DIBUJAR_CON_IA\Proyectos Stable Diffusion\LORA-Test\image\100_Test"
    image_count: 20
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Test
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 319.92it/s]
prepare dataset
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
vae\diffusion_pytorch_model.safetensors not found
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable memory efficient attention for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.92it/s]
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
CrossAttnDownBlock2D False -> True
CrossAttnDownBlock2D False -> True
CrossAttnDownBlock2D False -> True
DownBlock2D False -> True
UNetMidBlock2DCrossAttn False -> True
UpBlock2D False -> True
CrossAttnUpBlock2D False -> True
CrossAttnUpBlock2D False -> True
CrossAttnUpBlock2D False -> True
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 2000
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 2000
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 2000
steps:   0%|                                                                                  | 0/2000 [00:00<?, ?it/s]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\vicll\Desktop\Diseño\DIBUJAR_CON_IA\kohya_ss\train_network.py:990 in <module>           │
│                                                                                                  │
│   987 │   args = train_util.read_config_from_file(args, parser)                                  │
│   988 │                                                                                          │
│   989 │   trainer = NetworkTrainer()                                                             │
│ ❱ 990 │   trainer.train(args)                                                                    │
│   991                                                                                            │
│                                                                                                  │
│ C:\Users\vicll\Desktop\Diseño\DIBUJAR_CON_IA\kohya_ss\train_network.py:691 in train              │
│                                                                                                  │
│   688 │   │   │   init_kwargs = {}                                                               │
│   689 │   │   │   if args.log_tracker_config is not None:                                        │
│   690 │   │   │   │   init_kwargs = toml.load(args.log_tracker_config)                           │
│ ❱ 691 │   │   │   accelerator.init_trackers("network_train" if args.log_tracker_name is None e   │
│   692 │   │                                                                                      │
│   693 │   │   loss_list = []                                                                     │
│   694 │   │   loss_total = 0.0                                                                   │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator. │
│ py:564 in _inner                                                                                 │
│                                                                                                  │
│    561 │   │   │   │   )                                                                         │
│    562 │   │                                                                                     │
│    563 │   │   def _inner(*args, **kwargs):                                                      │
│ ❱  564 │   │   │   return PartialState().on_main_process(function)(*args, **kwargs)              │
│    565 │   │                                                                                     │
│    566 │   │   return _inner                                                                     │
│    567                                                                                           │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator. │
│ py:2093 in init_trackers                                                                         │
│                                                                                                  │
│   2090 │   │   │   │   if getattr(tracker_init, "requires_logging_directory"):                   │
│   2091 │   │   │   │   │   # We can skip this check since it was done in `__init__`              │
│   2092 │   │   │   │   │   self.trackers.append(                                                 │
│ ❱ 2093 │   │   │   │   │   │   tracker_init(project_name, self.logging_dir, **init_kwargs.get(s  │
│   2094 │   │   │   │   │   )                                                                     │
│   2095 │   │   │   │   else:                                                                     │
│   2096 │   │   │   │   │   self.trackers.append(tracker_init(project_name, **init_kwargs.get(st  │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\tracking.py: │
│ 83 in execute_on_main_process                                                                    │
│                                                                                                  │
│    80 │   @wraps(function)                                                                       │
│    81 │   def execute_on_main_process(self, *args, **kwargs):                                    │
│    82 │   │   if getattr(self, "main_process_only", False):                                      │
│ ❱  83 │   │   │   return PartialState().on_main_process(function)(self, *args, **kwargs)         │
│    84 │   │   else:                                                                              │
│    85 │   │   │   return function(self, *args, **kwargs)                                         │
│    86                                                                                            │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\tracking.py: │
│ 190 in __init__                                                                                  │
│                                                                                                  │
│   187 │   │   super().__init__()                                                                 │
│   188 │   │   self.run_name = run_name                                                           │
│   189 │   │   self.logging_dir = os.path.join(logging_dir, run_name)                             │
│ ❱ 190 │   │   self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)                │
│   191 │   │   logger.debug(f"Initialized TensorBoard project {self.run_name} logging to {self.   │
│   192 │   │   logger.debug(                                                                      │
│   193 │   │   │   "Make sure to log any initial configurations with `self.store_init_configura   │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard │
│ \writer.py:247 in __init__                                                                       │
│                                                                                                  │
│    244 │   │   # Initialize the file writers, but they can be cleared out on close               │
│    245 │   │   # and recreated later as needed.                                                  │
│    246 │   │   self.file_writer = self.all_writers = None                                        │
│ ❱  247 │   │   self._get_file_writer()                                                           │
│    248 │   │                                                                                     │
│    249 │   │   # Create default bins for histograms, see generate_testdata.py in tensorflow/ten  │
│    250 │   │   v = 1e-12                                                                         │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard │
│ \writer.py:277 in _get_file_writer                                                               │
│                                                                                                  │
│    274 │   def _get_file_writer(self):                                                           │
│    275 │   │   """Returns the default FileWriter instance. Recreates it if closed."""            │
│    276 │   │   if self.all_writers is None or self.file_writer is None:                          │
│ ❱  277 │   │   │   self.file_writer = FileWriter(                                                │
│    278 │   │   │   │   self.log_dir, self.max_queue, self.flush_secs, self.filename_suffix       │
│    279 │   │   │   )                                                                             │
│    280 │   │   │   self.all_writers = {self.file_writer.get_logdir(): self.file_writer}          │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\tensorboard │
│ \writer.py:76 in __init__                                                                        │
│                                                                                                  │
│     73 │   │   # TODO: See if we can remove this in the future if we are                         │
│     74 │   │   # actually the ones passing in a PosixPath                                        │
│     75 │   │   log_dir = str(log_dir)                                                            │
│ ❱   76 │   │   self.event_writer = EventFileWriter(                                              │
│     77 │   │   │   log_dir, max_queue, flush_secs, filename_suffix                               │
│     78 │   │   )                                                                                 │
│     79                                                                                           │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorboard\summary\wri │
│ ter\event_file_writer.py:72 in __init__                                                          │
│                                                                                                  │
│    69 │   │   │   pending events and summaries to disk.                                          │
│    70 │   │   """                                                                                │
│    71 │   │   self._logdir = logdir                                                              │
│ ❱  72 │   │   tf.io.gfile.makedirs(logdir)                                                       │
│    73 │   │   self._file_name = (                                                                │
│    74 │   │   │   os.path.join(                                                                  │
│    75 │   │   │   │   logdir,                                                                    │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\lib\i │
│ o\file_io.py:513 in recursive_create_dir_v2                                                      │
│                                                                                                  │
│    510   Raises:                                                                                 │
│    511 │   errors.OpError: If the operation fails.                                               │
│    512   """                                                                                     │
│ ❱  513   _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))                        │
│    514                                                                                           │
│    515                                                                                           │
│    516 @tf_export("io.gfile.copy")                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FailedPreconditionError: C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable Diffusion/LORA-Test/model/sample
is not a directory
steps:   0%|                                                                                  | 0/2000 [00:00<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:918 in launch_command                                                                     │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\vicll\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:580 in simple_launcher                                                                    │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\vicll\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
'./train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5',
'--train_data_dir=C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable Diffusion/LORA-Test/image',
'--resolution=512,512', '--output_dir=C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
Diffusion/LORA-Test/model', '--logging_dir=C:/Users/vicll/Desktop/Diseño/DIBUJAR_CON_IA/Proyectos Stable
Diffusion/LORA-Test/model/sample', '--network_alpha=128', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128',
'--output_name=Test', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001',
'--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=2000', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents',
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64',
'--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned
non-zero exit status 1.

**Comment by Sinay-Show** [comment]
did u find any solution ?

**Comment by MrRubRub** [comment]
Yes, i think it was all caused by the fact that kohya was installed inside of a folder that had a "ñ" character, which seemed to be the cause of the error (i refer to this:  C:\Users\vicll\Desktop\ **Diseño** \DIBUJAR_CON_IA\kohya_ss).  After changing Diseño's name folder to something without "ñ"  and reinstalling kohya, it worked perfectly.
If it helps you, i had another issue which was also caused by this character problem. Here is the link, i hope it helps.
https://github.com/bmaltais/kohya_ss/issues/1322
