### ISSUE TITLE
Cannot extract LORA from DreamBooth checkpoints any more

### ISSUE THREAD

**Issue by shadowlocked** [bmaltais/kohya_ss#1328]
As of last week, kohya_ss throws an error when converting a DreamBooth checkpoint created by the [ShivamShirao Colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb). 

`╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\[USER]\Desktop\KOHYA2\kohya_ss\networks\extract_lora_from_models.py:189 in <module>     │
│                                                                                                  │
│   186   parser = setup_parser()                                                                  │
│   187                                                                                            │
│   188   args = parser.parse_args()                                                               │
│ ❱ 189   svd(args)                                                                                │
│   190                                                                                            │
│                                                                                                  │
│ C:\Users\[USER]\Desktop\KOHYA2\kohya_ss\networks\extract_lora_from_models.py:45 in svd           │
│                                                                                                  │
│    42   print(f"loading SD model : {args.model_org}")                                            │
│    43   text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(ar   │
│    44   print(f"loading SD model : {args.model_tuned}")                                          │
│ ❱  45   text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffusion_checkpoint(ar   │
│    46                                                                                            │
│    47   # create LoRA network to extract weights: Use dim (rank) as alpha                        │
│    48   if args.conv_dim is None:                                                                │
│                                                                                                  │
│ C:\Users\[USER]\Desktop\KOHYA2\kohya_ss\library\model_util.py:1059 in                            │
│ load_models_from_stable_diffusion_checkpoint                                                     │
│                                                                                                  │
│   1056 │   │   │   torch_dtype="float32",                                                        │
│   1057 │   │   )                                                                                 │
│   1058 │   │   text_model = CLIPTextModel._from_config(cfg)                                      │
│ ❱ 1059 │   │   info = text_model.load_state_dict(converted_text_encoder_checkpoint)              │
│   1060 │   print("loading text encoder:", info)                                                  │
│   1061 │                                                                                         │
│   1062 │   return text_model, vae, unet                                                          │
│                                                                                                  │
│ C:\Users\[USER]\Desktop\KOHYA2\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1604   │
│ in load_state_dict                                                                               │
│                                                                                                  │
│   1601 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   1602 │   │                                                                                     │
│   1603 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 1604 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   1605 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   1606 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   1607                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯`

_(if you paste the error code above into a text editor, it becomes well-ordered, but the Github code styling doesn't work for this one)_

Prior to this, the Kohya install had successfully converted many historical checkpoints I made over the winter.

In fact, it can still convert any checkpoint I made up until about a month ago. But if I try and extract a LORA from a brand new Shivam DreamBooth checkpoint, I get the error above every time.

I just talked to Shivam on Discord. He says (which you can see from the versioning at the Colab): 'The colab has been exact same for months. Some dependencies or format of either kohya or some other package changed'

If anyone has any ideas about this, would appreciate it.

**Comment by bmaltais** [comment]
I published a new release that I hope will address this issue. It has the latest LoRA extraction utility that should fix the issue. If not then I suggest to open an issue directly on kohya_ss sd-scripts repo as this would need to be addressed by kohya.

**Comment by shadowlocked** [comment]
> 

Thanks for this. Unfortunately, though the _LoRA > Tools > Extract LoRA_ process can now successfully extract a LoRA from a Shivam Shirao Dreambooth checkpoint, it loses the trigger words in the process, which means you end up with random 1girls, landscapes and pictures of buildings in the extracted LoRA.

This applies not only to newly created DreamBooths, but to historical ones that the framework was able to successfully extract into LoRAs prior to this latest update.

Shivam suspects that changes in Diffusers may be behind this. - https://huggingface.co/runwayml/stable-diffusion-v1-5/commits/main

Therefore I have tried to create a DreamBooth with the Shivam Colab that uses the [May 5th Diffusers commit](https://huggingface.co/runwayml/stable-diffusion-v1-5/commit/aa9ba505e1973ae5cd05f5aedd345178f52f8e6a), which produced a working and extractable DreamBooth file at the time.

I did this by changing this code in the [Shivam Colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb):

`--revision="fp16"`

Into

`--revision="aa9ba505e1973ae5cd05f5aedd345178f52f8e6a"`

This has not worked. I extracted a LoRA from the checkpoint, and it still gives random output.

However, this is a clue - the nature of the error and the recent commit history of Diffusers suggests that CLIP information has been renamed and moved, so maybe this could help in fixing the problem.

As it stands, the current version cannot extract any Shiva, Colab-created DreamBooth (and, perhaps, not any DreamBooth checkpoint at all).

I can confirm that merging, converting to safetensors, etc. makes no difference. Right now Kohya_ss simply cannot find the keys.

**Comment by bmaltais** [comment]
You should raise this issue directly on kohya's sd-script repo as this is something only he can fix in the code

**Comment by shadowlocked** [comment]
I don't think I can bear to re-document the entire thing again in a new thread. I've [linked to it at that repo](https://github.com/kohya-ss/sd-scripts/issues/723), but at this point I'm assuming very limited interest in fixing it, and I'll figure that it's time to learn how to train LoRA directly.

**Comment by bmaltais** [comment]
I only make the gui, the underlying script that does all the work is from kohya. Sorry if that is not more clear. But hopefully kohya will be able to help. Others might have that same exact issue.
