### ISSUE TITLE
Lora training speed on Windows 11 is slower than on Windows 10

### ISSUE THREAD

**Issue by bananasss00** [bmaltais/kohya_ss#1337]
This week I decided to upgrade from Windows 10 -> 11 and noticed that training speed is noticeably slower. 

**Video card:** RTX 4080
**Lora params:** dimension=128, optimizer=AdamW8bit, scheduler=Const

For experiment I specifically installed windows 10 and windows 11 from scratch, ran lora training on both.

**Windows 10 = ~4it/sec
Windows 11 = ~2.7-3it/sec**

Tried disabling / enabling xformers, updating cudnn for torch, changing precision in accelerate config: 'no', 'fp16', 'bf16'. Nothing helped to raise the speed above 3it/sec on Windows 11.

**What could be the problem?**

PS: I have triton installed from here https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl, it increases the training speed a bit on Windows 10 and 11

**Comment by juanigsrz** [comment]
it/s is meaningless on its own

**Comment by bmaltais** [comment]
Interesting... I have not tested on windows 10. THank you for sharing the info.

**Comment by neoraoz** [comment]
thx for triton info. Plz let me know the installation command.
Many thanks in advance.

**Comment by bananasss00** [comment]
> thx for triton info. Plz let me know the installation command. Many thanks in advance.

```
venv/scripts/activate
pip install --use-pep517 https://huggingface.co/r4ziel/xformers_pre_built/resolve/main/triton-2.0.0-cp310-cp310-win_amd64.whl```

**Comment by bananasss00** [comment]
> 



> Interesting... I have not tested on windows 10. THank you for sharing the info.

** Windows 11 **
![изображение](https://github.com/bmaltais/kohya_ss/assets/30229634/882bd0f4-81c7-4cb2-8013-f88da1f8b264)

** Windows 11 - WSL2 ArchLinux **
![win11-main-wsl2arch-train](https://github.com/bmaltais/kohya_ss/assets/30229634/65ba7279-957b-4770-8f2c-e0029691270b)

** Windows 10 **
![win10-main-train](https://github.com/bmaltais/kohya_ss/assets/30229634/13921ccc-2d4f-4365-b57d-41e1cb511481)

PS: Windows 10/11 used a similar build from the permanent path
ArchWSL has a clean installation without any modifications

**Comment by bananasss00** [comment]
**I found a solution for windows 11:**
https://forums.developer.nvidia.com/t/performance-decreases-after-upgrading-from-windows-10-to-windows-11/255036/2

**Need to disable this!!!:**
![Hardware-Accelerated-GPU-Scheduling](https://github.com/bmaltais/kohya_ss/assets/30229634/d6d15a40-4097-43ce-a4a2-12cb47d0101a)

**and now I get the same speed as in windows 10**
