### ISSUE TITLE
Tensorboard on runpod

### ISSUE THREAD

**Issue by moon47usaco** [bmaltais/kohya_ss#1339]
How can I add share support for the tensor board?

When trying to launch on run pod it wants to open on localhost. Is there a way to rout it to the current gradio interface I am using for the GUI.

IE running the KohyaGUI with "bash gui.sh --share" works, but how to tell tensor board to use that or another interface not localhost?

**Comment by moon47usaco** [comment]
Solved my own problem:

See the Post by [Andrew Schreiber] currently third from the bottom.
Essentially install ngrok

PS Don't forget to run this before "ngrok http 6006":
ngrok config add-authtoken <your ngrok token from signing up online>

**Comment by kostia-official** [comment]
You can use link:

https://<pod id>-6006.proxy.runpod.net
