### ISSUE TITLE
Textual Inversion not working

### ISSUE THREAD

**Issue by leonary** [bmaltais/kohya_ss#1344]
![image](https://github.com/bmaltais/kohya_ss/assets/83766753/a0f2d063-83ee-462e-bca8-579ca41fe944)
When you select the template as Caption on the TI interface(and set the Caption Extension correctly), the TI model cannot learn anything. The TI model works fine when you select the template as object.
You can try with this simple dataset:
https://files.catbox.moe/7tcvcg.zip

**Comment by bmaltais** [comment]
This is probably something with the training script and kohya will probably need to look into it. I suggest opening an issue on his sd-script repo. Once he publish a fix I will import the fix into my repo.

**Comment by coljacarls** [comment]
sorry, [found it](https://github.com/kohya-ss/sd-scripts/issues/728) and also found that I made the same mistake with the token string 😄
