### ISSUE TITLE
ERROR: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by oliverban** [bmaltais/kohya_ss#1347]
05:20:47-523308 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket
                         --min_bucket_reso=64 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="C:/Users/Oliver/Documents/Github/stable-diffusion-webui/models
                         /Stable-diffusion/dynavisionDuchaiten.safetensors"
                         --train_data_dir="C:/Users/Oliver/Pictures/LoRA Outputs/TR33D33/img" --resolution="1024,1024"
                         --output_dir="C:/Users/Oliver/Pictures/LoRA Outputs/TR33D33/model"
                         --logging_dir="C:/Users/Oliver/Pictures/LoRA Outputs/TR33D33/log" --network_alpha="128"
                         --training_comment="XKSTDO style" --save_model_as=safetensors --network_module=networks.lora
                         --text_encoder_lr=1.0 --unet_lr=1.0 --network_dim=128 --output_name="XKSTDO"
                         --lr_scheduler_num_cycles="1" --scale_weight_norms="1" --no_half_vae --learning_rate="1.0"
                         --lr_scheduler="adafactor" --train_batch_size="4" --max_train_steps="6675"
                         --save_every_n_epochs="5" --mixed_precision="bf16" --save_precision="bf16"
                         --caption_extension=".txt2" --cache_latents --cache_latents_to_disk
                         --optimizer_type="Adafactor" --max_train_epochs=30 --max_data_loader_n_workers="0"
                         --keep_tokens="1" --bucket_reso_steps=32 --gradient_checkpointing --xformers
                         --noise_offset=0.0357 --adaptive_noise_scale=0.00357 --log_prefix=xl-loha
[05:20:53] WARNING  The following values were not passed to `accelerate launch` and had defaults used      launch.py:890
                    instead:
                            `--num_processes` was set to a value of `2`
                                    More than one GPU was found, enabling multi-GPU training.
                                    If this was unintended please pass in `--num_processes=1`.
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.
[05:20:54] WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.                     redirects.py:27
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizersprepare tokenizers

Using DreamBooth method.
Using DreamBooth method.
prepare images.
found directory C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style contains 89 image files
No caption file found for 89 images. Training will continue without captions for these images. If class token exists, it will be used. / 89枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_001.png
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_002.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_003.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_004.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_005.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_006.jpg... and 84 more
890 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 64
  max_bucket_reso: 2048
  bucket_reso_steps: 32
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style"
    image_count: 89
    num_repeats: 10
    shuffle_caption: False
    keep_tokens: 1
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: XKSTDO style
    caption_extension: .txt2

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 3144.13it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 1344), count: 20
bucket 1: resolution (800, 1280), count: 40
bucket 2: resolution (832, 1216), count: 10
bucket 3: resolution (832, 1248), count: 40
bucket 4: resolution (864, 1184), count: 10
bucket 5: resolution (896, 1152), count: 80
bucket 6: resolution (960, 1088), count: 10
bucket 7: resolution (992, 1056), count: 20
bucket 8: resolution (1024, 1024), count: 250
bucket 9: resolution (1056, 992), count: 50
bucket 10: resolution (1184, 864), count: 20
bucket 11: resolution (1280, 800), count: 10
bucket 12: resolution (1344, 768), count: 330
mean ar error (without repeats): 0.014880481433337627
noise_offset is set to 0.0357 / noise_offsetが0.0357に設定されました
preparing accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
prepare images.
found directory C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style contains 89 image files
No caption file found for 89 images. Training will continue without captions for these images. If class token exists, it will be used. / 89枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を 続行します。class tokenが存在する場合はそれを使います。
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_001.png
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_002.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_003.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_004.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_005.jpg
C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style\XKSTD_006.jpg... and 84 more
890 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 4
  resolution: (1024, 1024)
  enable_bucket: True
  min_bucket_reso: 64
  max_bucket_reso: 2048
  bucket_reso_steps: 32
  bucket_no_upscale: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Oliver\Pictures\LoRA Outputs\TR33D33\img\10_XKSTDO style"
    image_count: 89
    num_repeats: 10
    shuffle_caption: False
    keep_tokens: 1
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: XKSTDO style
    caption_extension: .txt2

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 89/89 [00:00<00:00, 2892.56it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (768, 1344), count: 20
bucket 1: resolution (800, 1280), count: 40
bucket 2: resolution (832, 1216), count: 10
bucket 3: resolution (832, 1248), count: 40
bucket 4: resolution (864, 1184), count: 10
bucket 5: resolution (896, 1152), count: 80
bucket 6: resolution (960, 1088), count: 10
bucket 7: resolution (992, 1056), count: 20
bucket 8: resolution (1024, 1024), count: 250
bucket 9: resolution (1056, 992), count: 50
bucket 10: resolution (1184, 864), count: 20
bucket 11: resolution (1280, 800), count: 10
bucket 12: resolution (1344, 768), count: 330
mean ar error (without repeats): 0.014880481433337627
noise_offset is set to 0.0357 / noise_offsetが0.0357に設定されました
preparing accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-H1GCOEJ]:29500 (system error: 10049 - The requested address is not valid in its context.).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Oliver\Documents\Github\kohya_ss\sdxl_train_network.py:174 in <module>                  │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:205 in train                          │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\library\train_util.py:3569 in prepare_accelerator      │
│                                                                                                  │
│   3566 │   │   │   if args.wandb_api_key is not None:                                            │
│   3567 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3568 │                                                                                         │
│ ❱ 3569 │   accelerator = Accelerator(                                                            │
│   3570 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3571 │   │   mixed_precision=args.mixed_precision,                                             │
│   3572 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361   │
│ in __init__                                                                                      │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:907 in init_process_group                                                                 │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:1013 in _new_process_group_helper                                                         │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Oliver\Documents\Github\kohya_ss\sdxl_train_network.py:174 in <module>                  │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\train_network.py:205 in train                          │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\library\train_util.py:3569 in prepare_accelerator      │
│                                                                                                  │
│   3566 │   │   │   if args.wandb_api_key is not None:                                            │
│   3567 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3568 │                                                                                         │
│ ❱ 3569 │   accelerator = Accelerator(                                                            │
│   3570 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3571 │   │   mixed_precision=args.mixed_precision,                                             │
│   3572 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:361   │
│ in __init__                                                                                      │
│                                                                                                  │
│    358 │   │   │   │   │   │   self.fp8_recipe_handler = handler                                 │
│    359 │   │                                                                                     │
│    360 │   │   kwargs = self.init_handler.to_kwargs() if self.init_handler is not None else {}   │
│ ❱  361 │   │   self.state = AcceleratorState(                                                    │
│    362 │   │   │   mixed_precision=mixed_precision,                                              │
│    363 │   │   │   cpu=cpu,                                                                      │
│    364 │   │   │   dynamo_plugin=dynamo_plugin,                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:549 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   546 │   │   if parse_flag_from_env("ACCELERATE_USE_CPU"):                                      │
│   547 │   │   │   cpu = True                                                                     │
│   548 │   │   if PartialState._shared_state == {}:                                               │
│ ❱ 549 │   │   │   PartialState(cpu, **kwargs)                                                    │
│   550 │   │   self.__dict__.update(PartialState._shared_state)                                   │
│   551 │   │   self._check_initialized(mixed_precision, cpu)                                      │
│   552 │   │   if not self.initialized:                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\state.py:143 in      │
│ __init__                                                                                         │
│                                                                                                  │
│   140 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   141 │   │   │   │   │   if self.backend is None:                                               │
│   142 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 143 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   144 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   145 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   146 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:907 in init_process_group                                                                 │
│                                                                                                  │
│    904 │   │   │   # different systems (e.g. RPC) in case the store is multi-tenant.             │
│    905 │   │   │   store = PrefixStore("default_pg", store)                                      │
│    906 │   │                                                                                     │
│ ❱  907 │   │   default_pg = _new_process_group_helper(                                           │
│    908 │   │   │   world_size,                                                                   │
│    909 │   │   │   rank,                                                                         │
│    910 │   │   │   [],                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c │
│ 10d.py:1013 in _new_process_group_helper                                                         │
│                                                                                                  │
│   1010 │   │   │   backend_type = ProcessGroup.BackendType.GLOO                                  │
│   1011 │   │   elif backend_str == Backend.NCCL:                                                 │
│   1012 │   │   │   if not is_nccl_available():                                                   │
│ ❱ 1013 │   │   │   │   raise RuntimeError("Distributed package doesn't have NCCL " "built in")   │
│   1014 │   │   │   if pg_options is not None:                                                    │
│   1015 │   │   │   │   assert isinstance(                                                        │
│   1016 │   │   │   │   │   pg_options, ProcessGroupNCCL.Options                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Distributed package doesn't have NCCL built in
[05:21:05] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 13852) of binary:                                api.py:672
                    C:\Users\Oliver\Documents\Github\kohya_ss\venv\Scripts\python.exe
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ c:\python\lib\runpy.py:196 in _run_module_as_main                                                │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ c:\python\lib\runpy.py:86 in _run_code                                                           │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_ │
│ cli.py:45 in main                                                                                │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:9 │
│ 09 in launch_command                                                                             │
│                                                                                                  │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   907 │   │   multi_gpu_launcher(args)                                                           │
│   908 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                                           │
│   910 │   elif args.tpu and not args.cpu:                                                        │
│   911 │   │   if args.tpu_use_cluster:                                                           │
│   912 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:6 │
│ 04 in multi_gpu_launcher                                                                         │
│                                                                                                  │
│   601 │   )                                                                                      │
│   602 │   with patch_environment(**current_env):                                                 │
│   603 │   │   try:                                                                               │
│ ❱ 604 │   │   │   distrib_run.run(args)                                                          │
│   605 │   │   except Exception:                                                                  │
│   606 │   │   │   if is_rich_available() and debug:                                              │
│   607 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\run.py:785 in │
│ run                                                                                              │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api. │
│ py:134 in __call__                                                                               │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ C:\Users\Oliver\Documents\Github\kohya_ss\venv\lib\site-packages\torch\distributed\launcher\api. │
│ py:250 in launch_agent                                                                           │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError:
============================================================
./sdxl_train_network.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-08_05:21:05
  host      : DESKTOP-H1GCOEJ.lan
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 13316)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-08_05:21:05
  host      : DESKTOP-H1GCOEJ.lan
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13852)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by vrgz2022** [comment]
same error,can some one help?

**Comment by oliverban** [comment]
> same error,can some one help?

After a recent update this went away. I was getting the error when changing too many parameters and when I went back to default, only changing the optimizer, it worked fine. Also make sure your paths to the folders is correct!

**Comment by Echostorm44** [comment]
Following this guy: https://www.youtube.com/watch?v=AY6DMBCIZ3A
Most recent version pulled down this morning, still getting error.  Do you see anything wrong here?

 accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="E:/AI/sd_xl_base_1.0.safetensors"
                         --train_data_dir="E:\LoraTrainer\TrainingResults\img"
                         --reg_data_dir="E:\LoraTrainer\TrainingResults\reg" --resolution="1024,1024"
                         --output_dir="E:\LoraTrainer\TrainingResults\model"
                         --logging_dir="E:\LoraTrainer\TrainingResults\log" --save_model_as=safetensors
                         --output_name="TestingLora" --lr_scheduler_num_cycles="10" --max_data_loader_n_workers="0"
                         --learning_rate="0.0004" --lr_scheduler="constant" --train_batch_size="1"
                         --max_train_steps="5200" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --cache_latents --cache_latents_to_disk --optimizer_type="Adafactor"
                         --optimizer_args scale_parameter=False relative_step=False warmup_init=False
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --gradient_checkpointing --xformers
                         --bucket_no_upscale --noise_offset=0.0

**Comment by oliverban** [comment]
> I fixed this by running accelerate config For some reason it thought I wanted to run distributed GPUs and that was the source of the error.

Well, I do have 2 gpus in the system, maybe that was why? I'd love to train on both at the same time if that is a thing? :D

**Comment by Stareshine** [comment]
First , launch the setup.bat, select 5 to enter Accelerate config,
Following "https://www.youtube.com/watch?v=adVhm9aI9Gc"
Launch UI
Make sure u have selected the correct pretrained model. As to me, I selected the checkpoint model from stablediffusion
Make sure u have name the folder and image files correct.
