### ISSUE TITLE
Cannot merge lora(s)  into a checkpoint in v21.8.6

### ISSUE THREAD

**Issue by michaeltran33** [bmaltais/kohya_ss#1348]
Cannot merge lora(s)  into a checkpoint in v21.8.6
Console.
15:27:05-153681 INFO     Version: v21.8.6

15:27:05-160681 INFO     nVidia toolkit detected
15:27:05-905680 INFO     Torch 2.0.1+cu118
15:27:05-928705 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:27:05-932705 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
15:27:05-933706 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
15:27:05-935706 INFO     Verifying modules instalation status from requirements.txt...
15:27:07-517731 INFO     headless: False
15:27:07-520732 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
15:27:30-683045 INFO     Merge model...
15:27:30-684045 INFO     ./venv/Scripts/python.exe "networks\sdxl_merge_lora.py" --sd_model
                         "D:/stable-diffusion-webui/models/Stable-diffusion/AModel/lofi2.safetensors" --save_precision
                         fp16 --precision float --save_to
                         "D:/stable-diffusion-webui/models/Stable-diffusion/AModel/lofi3.safetensors" --models
                         "D:/stable-diffusion-webui/models/Lora/Specials/NijiV3Fantasy.safetensors"
                         "D:/stable-diffusion-webui/models/Lora/Specials/ocIllustration_v10.safetensors" --ratios 0.4
                         0.4
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
loading SD model: D:/stable-diffusion-webui/models/Stable-diffusion/AModel/lofi2.safetensors
building U-Net
loading U-Net from checkpoint
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\networks\sdxl_merge_lora.py:257 in <module>                                          │
│                                                                                                  │
│   254 │   parser = setup_parser()                                                                │
│   255 │                                                                                          │
│   256 │   args = parser.parse_args()                                                             │
│ ❱ 257 │   merge(args)                                                                            │
│   258                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\networks\sdxl_merge_lora.py:205 in merge                                             │
│                                                                                                  │
│   202 │   │   │   unet,                                                                          │
│   203 │   │   │   logit_scale,                                                                   │
│   204 │   │   │   ckpt_info,                                                                     │
│ ❱ 205 │   │   ) = sdxl_model_util.load_models_from_sdxl_checkpoint(sdxl_model_util.MODEL_VERSI   │
│   206 │   │                                                                                      │
│   207 │   │   merge_to_sd_model(text_model1, text_model2, unet, args.models, args.ratios, merg   │
│   208                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:196 in load_models_from_sdxl_checkpoint                   │
│                                                                                                  │
│   193 │   for k in list(state_dict.keys()):                                                      │
│   194 │   │   if k.startswith("model.diffusion_model."):                                         │
│   195 │   │   │   unet_sd[k.replace("model.diffusion_model.", "")] = state_dict.pop(k)           │
│ ❱ 196 │   info = _load_state_dict_on_device(unet, unet_sd, device=map_location)                  │
│   197 │   print("U-Net: ", info)                                                                 │
│   198 │                                                                                          │
│   199 │   # Text Encoders                                                                        │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:158 in _load_state_dict_on_device                         │
│                                                                                                  │
│   155 │   if unexpected_keys:                                                                    │
│   156 │   │   error_msgs.insert(0, "Unexpected key(s) in state_dict: {}. ".format(", ".join('"   │
│   157 │                                                                                          │
│ ❱ 158 │   raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__cla   │
│   159                                                                                            │
│   160                                                                                            │
│   161 def load_models_from_sdxl_checkpoint(model_version, ckpt_path, map_location, dtype=None)   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for SdxlUNet2DConditionModel:
        Unexpected key(s) in state_dict: "output_blocks.11.1.transformer_blocks.0.attn1.to_q.weight",
"output_blocks.11.1.transformer_blocks.0.attn2.to_v.weight", "output_blocks.9.0.out_layers.3.weight",
"output_blocks.8.2.conv.weight", "input_blocks.2.1.transformer_blocks.0.attn2.to_k.weight",
"output_blocks.11.1.proj_out.bias", "output_blocks.10.1.norm.weight",
"output_blocks.11.1.transformer_blocks.0.norm3.weight", "output_blocks.9.0.out_layers.3.bias",
"output_blocks.9.0.in_layers.0.weight", "output_blocks.11.1.transformer_blocks.0.norm1.bias",
"input_blocks.2.1.transformer_blocks.0.attn1.to_out.0.bias",
"input_blocks.1.1.transformer_blocks.0.attn1.to_out.0.weight",
"output_blocks.11.1.transformer_blocks.0.attn2.to_out.0.weight",
"output_blocks.8.1.transformer_blocks.0.attn2.to_v.weight", "input_blocks.10.0.out_layers.0.weight",
"input_blocks.2.1.proj_out.weight", "input_blocks.11.0.out_layers.3.bias", "output_blocks.11.0.in_layers.0.bias",
"output_blocks.10.0.out_layers.3.bias", "output_blocks.7.1.transformer_blocks.0.norm2.bias",
"output_blocks.7.1.transformer_blocks.0.attn2.to_k.weight", "input_blocks.11.0.emb_layers.1.weight",
"output_blocks.10.1.transformer_blocks.0.norm2.bias", "output_blocks.8.1.transformer_blocks.0.attn1.to_q.weight",
"output_blocks.9.1.proj_out.weight", "output_blocks.7.1.transformer_blocks.0.attn2.to_v.weight",
"output_blocks.6.1.transformer_blocks.0.norm1.bias", "output_blocks.11.0.out_layers.3.bias",
"output_blocks.10.0.out_layers.0.bias", "output_blocks.7.1.transformer_blocks.0.ff.net.2.bias",
"output_blocks.11.0.out_layers.3.weight", "output_blocks.10.1.transformer_blocks.0.attn1.to_k.weight",
"output_blocks.8.1.proj_in.bias", "output_blocks.9.1.transformer_blocks.0.attn2.to_k.weight",
"input_blocks.2.1.proj_in.weight", "output_blocks.9.1.transformer_blocks.0.attn2.to_out.0.bias",
"output_blocks.8.1.transformer_blocks.0.attn2.to_out.0.weight", "input_blocks.11.0.in_layers.0.weight",
...
"output_blocks.10.0.emb_layers.1.bias", "input_blocks.1.1.proj_in.bias",
"output_blocks.7.1.transformer_blocks.0.ff.net.0.proj.bias", "output_blocks.6.1.norm.bias",
"output_blocks.11.1.transformer_blocks.0.attn1.to_out.0.weight", "output_blocks.9.1.transformer_blocks.0.norm3.weight".
        Missing key(s) in state_dict: "middle_block.1.transformer_blocks.9.attn2.to_out.0.bias",
"input_blocks.8.1.transformer_blocks.9.ff.net.0.proj.weight",
"output_blocks.2.1.transformer_blocks.0.ff.net.0.proj.bias",
"output_blocks.0.1.transformer_blocks.7.attn2.to_out.0.weight",
"output_blocks.0.1.transformer_blocks.3.ff.net.2.weight", "input_blocks.7.1.transformer_blocks.2.norm3.bias",
"output_blocks.5.1.transformer_blocks.1.norm1.bias", "output_blocks.0.1.transformer_blocks.3.attn2.to_k.weight",
"output_blocks.0.1.transformer_blocks.8.attn1.to_q.weight", "input_blocks.8.1.transformer_blocks.1.ff.net.2.bias",
"output_blocks.0.1.transformer_blocks.8.norm2.weight", "input_blocks.8.1.transformer_blocks.4.attn1.to_q.weight",
"output_blocks.1.1.transformer_blocks.7.ff.net.0.proj.weight", "input_blocks.7.1.transformer_blocks.3.norm1.bias",
"middle_block.1.transformer_blocks.6.attn2.to_out.0.bias", "output_blocks.0.1.transformer_blocks.3.norm2.bias",
"input_blocks.7.1.transformer_blocks.7.attn1.to_out.0.bias", "output_blocks.2.1.transformer_blocks.1.attn2.to_q.weight",
"middle_block.1.transformer_blocks.4.attn1.to_v.weight", "input_blocks.8.1.transformer_blocks.7.norm2.weight",
"input_blocks.7.1.transformer_blocks.4.attn1.to_out.0.bias",
"output_blocks.2.1.transformer_blocks.0.attn1.to_out.0.weight", "middle_block.1.transformer_blocks.4.norm2.weight",
"input_blocks.7.1.transformer_blocks.9.attn1.to_v.weight", "input_blocks.8.1.transformer_blocks.3.ff.net.2.bias",
"input_blocks.7.1.transformer_blocks.2.attn1.to_out.0.bias", "output_blocks.0.1.transformer_blocks.2.norm2.bias",
"output_blocks.0.1.transformer_blocks.6.attn2.to_out.0.weight", "output_blocks.1.1.transformer_blocks.1.norm2.bias",
"middle_block.1.transformer_blocks.7.attn2.to_k.weight", "output_blocks.0.1.transformer_blocks.1.norm3.weight",
"output_blocks.2.1.transformer_blocks.6.norm1.weight", "input_blocks.8.1.transformer_blocks.8.attn1.to_out.0.weight",
"middle_block.1.transformer_blocks.2.norm1.weight", "output_blocks.2.1.transformer_blocks.1.norm1.bias",
"middle_block.1.transformer_blocks.1.attn1.to_v.weight", "output_blocks.2.1.transformer_blocks.8.norm2.bias",
"output_blocks.0.1.transformer_blocks.8.attn1.to_out.0.weight",
"output_blocks.2.1.transformer_blocks.6.attn2.to_out.0.bias",
"middle_block.1.transformer_blocks.2.attn1.to_out.0.weight", "input_blocks.8.1.transformer_blocks.7.norm3.bias",
"output_blocks.2.1.transformer_blocks.6.attn2.to_q.weight", "output_blocks.0.1.transformer_blocks.4.attn2.to_v.weight",
"output_blocks.4.1.transformer_blocks.1.attn2.to_k.weight", "output_blocks.1.1.transformer_blocks.6.norm3.weight",
"output_blocks.1.1.transformer_blocks.8.attn2.to_v.weight", "input_blocks.8.1.transformer_blocks.4.norm3.bias",
"input_blocks.7.1.transformer_blocks.9.norm2.bias", "input_blocks.7.1.transformer_blocks.7.attn1.to_q.weight",
"output_blocks.1.1.transformer_blocks.2.attn1.to_q.weight", "input_blocks.8.1.transformer_blocks.9.attn2.to_k.weight",
"input_blocks.7.1.transformer_blocks.1.norm2.weight", "output_blocks.2.1.transformer_blocks.1.attn1.to_q.weight",
"input_blocks.8.1.transformer_blocks.6.attn1.to_out.0.weight",
"output_blocks.1.1.transformer_blocks.0.attn1.to_out.0.bias", "middle_block.1.transformer_blocks.5.attn1.to_k.weight",
"output_blocks.1.1.transformer_blocks.8.attn1.to_k.weight", "input_blocks.8.1.transformer_blocks.4.norm1.bias",
"middle_block.1.transformer_blocks.9.ff.net.0.proj.bias", "output_blocks.2.1.transformer_blocks.1.ff.net.2.bias",
"middle_block.1.transformer_blocks.4.attn2.to_out.0.bias", "output_blocks.1.1.transformer_blocks.8.attn2.to_q.weight",
"output_blocks.2.1.transformer_blocks.5.attn1.to_k.weight", "output_blocks.3.1.transformer_blocks.1.attn1.to_v.weight",
"input_blocks.7.1.transformer_blocks.6.attn1.to_k.weight", "input_blocks.7.1.transformer_blocks.6.attn2.to_k.weight",
"output_blocks.1.1.transformer_blocks.2.attn2.to_out.0.weight", "input_blocks.4.1.transformer_blocks.1.ff.net.2.weight",
"output_blocks.1.1.transformer_blocks.5.attn1.to_out.0.bias",
"output_blocks.2.1.transformer_blocks.4.attn1.to_out.0.weight", "input_blocks.8.1.transformer_blocks.7.norm3.weight",
"middle_block.1.transformer_blocks.3.attn2.to_out.0.weight", "middle_block.1.transformer_blocks.6.norm2.bias",
"input_blocks.8.1.transformer_blocks.8.attn1.to_out.0.bias", "output_blocks.3.1.transformer_blocks.1.norm3.bias",
"input_blocks.8.1.transformer_blocks.2.ff.net.2.bias", "input_blocks.8.1.transformer_blocks.4.attn1.to_out.0.bias",
"input_blocks.8.1.transformer_blocks.1.ff.net.0.proj.weight", "input_blocks.7.1.transformer_blocks.4.norm3.weight",
"output_blocks.1.1.transformer_blocks.1.attn2.to_k.weight".
15:27:34-315137 INFO     Done merging...

**Comment by bmaltais** [comment]
Look like an issue with the merge tool. Not something I can fix. You should open an issue directly with kohya in his sd-scripts repo regarding this.

**Comment by michaeltran33** [comment]
already did as suggested. Wd b grateful for a way to roll back to the version that doesnt use sdxl_merge_lora.py. Did try v21.7.8 #1003 but it still use networks/sdxl_merge_lora.py. Any suggestions will be great. Thanks.

**Comment by bmaltais** [comment]
Grab the dev2 branch code. I have pushed a fix:

```
git checkout dev2
git pull
```

**Comment by michaeltran33** [comment]
I did try to merge sd15 lora into a sd15 checkpoint. there is nothing todo with xdxl. Somehow the system call sdxl_merge_lora.py to do the job, and failed. 
I did check and uncheck the XL checkbox, it seems have no different result. both failed.
tried checkout dev2
below is the result
-------
←[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

←[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
←[1;33m=============================================================←[0m

22:49:34-174005 INFO     Version: v21.8.7

22:49:34-186005 INFO     nVidia toolkit detected
22:49:34-560005 INFO     Torch 1.12.1+cu116
22:49:34-576005 INFO     Torch backend: nVidia CUDA 11.6 cuDNN 8302
22:49:34-577005 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
22:49:34-579005 INFO     Verifying modules instalation status from requirements_windows_torch1.txt...
22:49:34-590039 INFO     Verifying modules instalation status from requirements.txt...
22:49:36-122635 INFO     headless: False
22:49:36-124635 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
22:50:18-308521 INFO     Merge model...
22:50:18-309521 INFO     ./venv/Scripts/python.exe "networks\merge_lora.py" --sd_model
                         "D:/stable-diffusion-webui/models/Stable-diffusion/johan.safetensors" --save_precision fp16
                         --precision float --save_to
                         "D:/stable-diffusion-webui/models/Stable-diffusion/johan2.safetensors" --models
                         "D:/stable-diffusion-webui/models/Stable-diffusion/johanLora.safetensors" --ratios 0.46
loading SD model: D:/stable-diffusion-webui/models/Stable-diffusion/johan.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\networks\merge_lora.py:328 in <module>                                               │
│                                                                                                  │
│   325 │   parser = setup_parser()                                                                │
│   326 │                                                                                          │
│   327 │   args = parser.parse_args()                                                             │
│ ❱ 328 │   merge(args)                                                                            │
│   329                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\networks\merge_lora.py:227 in merge                                                  │
│                                                                                                  │
│   224 │   if args.sd_model is not None:                                                          │
│   225 │   │   print(f"loading SD model: {args.sd_model}")                                        │
│   226 │   │                                                                                      │
│ ❱ 227 │   │   text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoin   │
│   228 │   │                                                                                      │
│   229 │   │   merge_to_sd_model(text_encoder, unet, args.models, args.ratios, merge_dtype)       │
│   230                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\library\model_util.py:1008 in load_models_from_stable_diffusion_checkpoint           │
│                                                                                                  │
│   1005 │   converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)         │
│   1006 │                                                                                         │
│   1007 │   vae = AutoencoderKL(**vae_config).to(device)                                          │
│ ❱ 1008 │   info = vae.load_state_dict(converted_vae_checkpoint)                                  │
│   1009 │   print("loading vae:", info)                                                           │
│   1010 │                                                                                         │
│   1011 │   # convert text_model                                                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1604 in load_state_dict            │
│                                                                                                  │
│   1601 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   1602 │   │                                                                                     │
│   1603 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 1604 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   1605 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   1606 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   1607                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight",
"encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight",
"encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight",
"encoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_q.weight",
"decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight",
"decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight",
"decoder.mid_block.attentions.0.to_v.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_to_k.bias",
"encoder.mid_block.attentions.0.to_to_k.weight", "encoder.mid_block.attentions.0.to_to_q.bias",
"encoder.mid_block.attentions.0.to_to_q.weight", "encoder.mid_block.attentions.0.to_to_v.bias",
"encoder.mid_block.attentions.0.to_to_v.weight", "decoder.mid_block.attentions.0.to_to_k.bias",
"decoder.mid_block.attentions.0.to_to_k.weight", "decoder.mid_block.attentions.0.to_to_q.bias",
"decoder.mid_block.attentions.0.to_to_q.weight", "decoder.mid_block.attentions.0.to_to_v.bias",
"decoder.mid_block.attentions.0.to_to_v.weight".
22:50:24-095642 INFO     Done merging...

**Comment by bmaltais** [comment]
Now, this is something for kohya ;-) Look like there is an issue with the vae in the model you try to merge into. Try merging into base sd1.5 and see if that work as a test... if it does then your model is not supported by kohya's code.

**Comment by michaeltran33** [comment]
tried with sd15 pruned n a few different loras for experiment. they all failed. 
tried with previous checkpoints n loras that worked before. They all failed with same errors.
XL checkbox is unchecked.
-----------
./venv/Scripts/python.exe "networks\sdxl_merge_lora.py" --sd_model
                         "D:/temp/Models/v1-5-pruned.safetensors" --save_precision fp16 --precision float --save_to
                         "D:/stable-diffusion-webui/models/Stable-diffusion/Anime/camel3.safetensors" --models
                         "D:/stable-diffusion-webui/models/Lora/ComicArt/lineart-modified.safetensors" --ratios 1
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
loading SD model: D:/temp/Models/v1-5-pruned.safetensors
building U-Net
loading U-Net from checkpoint
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\networks\sdxl_merge_lora.py:257 in <module>                                          │
│                                                                                                  │
│   254 │   parser = setup_parser()                                                                │
│   255 │                                                                                          │
│   256 │   args = parser.parse_args()                                                             │
│ ❱ 257 │   merge(args)                                                                            │
│   258                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\networks\sdxl_merge_lora.py:205 in merge                                             │
│                                                                                                  │
│   202 │   │   │   unet,                                                                          │
│   203 │   │   │   logit_scale,                                                                   │
│   204 │   │   │   ckpt_info,                                                                     │
│ ❱ 205 │   │   ) = sdxl_model_util.load_models_from_sdxl_checkpoint(sdxl_model_util.MODEL_VERSI   │
│   206 │   │                                                                                      │
│   207 │   │   merge_to_sd_model(text_model1, text_model2, unet, args.models, args.ratios, merg   │
│   208                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:196 in load_models_from_sdxl_checkpoint                   │
│                                                                                                  │
│   193 │   for k in list(state_dict.keys()):                                                      │
│   194 │   │   if k.startswith("model.diffusion_model."):                                         │
│   195 │   │   │   unet_sd[k.replace("model.diffusion_model.", "")] = state_dict.pop(k)           │
│ ❱ 196 │   info = _load_state_dict_on_device(unet, unet_sd, device=map_location)                  │
│   197 │   print("U-Net: ", info)                                                                 │
│   198 │                                                                                          │
│   199 │   # Text Encoders                                                                        │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:158 in _load_state_dict_on_device                         │
│                                                                                                  │
│   155 │   if unexpected_keys:                                                                    │
│   156 │   │   error_msgs.insert(0, "Unexpected key(s) in state_dict: {}. ".format(", ".join('"   │
│   157 │                                                                                          │
│ ❱ 158 │   raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__cla   │
│   159                                                                                            │
│   160                                                                                            │
│   161 def load_models_from_sdxl_checkpoint(model_version, ckpt_path, map_location, dtype=None)   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for SdxlUNet2DConditionModel:
        Unexpected key(s) in state_dict: "output_blocks.10.0.skip_connection.weight", "output_blocks.2.1.conv.bias",
"output_blocks.6.1.transformer_blocks.0.norm2.bias", "output_blocks.8.1.transformer_blocks.0.ff.net.2.weight",
"input_blocks.1.1.transformer_blocks.0.norm3.weight", "output_blocks.11.1.proj_in.weight",
"output_blocks.10.1.transformer_blocks.0.ff.net.0.proj.bias",
"output_blocks.6.1.transformer_blocks.0.attn2.to_out.0.weight",
"output_blocks.7.1.transformer_blocks.0.attn2.to_out.0.bias",
"input_blocks.2.1.transformer_blocks.0.attn2.to_out.0.weight", "output_blocks.7.1.transformer_blocks.0.norm2.bias",
"output_blocks.9.1.proj_out.weight", "input_blocks.1.1.proj_in.bias", "output_blocks.8.2.conv.bias",
"input_blocks.1.1.transformer_blocks.0.attn2.to_v.weight", ...

**Comment by michaeltran33** [comment]
"Please verify the model is SDXL based. If the model is SD1/2 based, please use merge_lora.py instead." The reply from sd_scripts is that somehow the GUI generate the wrong code. instead of using merge_lora.py, it does sdxl_merge_lora.py.
Please help to look into it. Thanksssssss.

**Comment by michaeltran33** [comment]
I tried .\venv\Scripts\python.exe "networks\merge_lora.py" --sd_model "D:/stable-diffusion-webui/models/Stable-diffusion/AModel/lofi2.safetensors" --save_precision fp16 --precision float --save_to "D:/stable-diffusion-webui/models/Stable-diffusion/AModel/lofi3.safetensors" --models "D:/stable-diffusion-webui/models/Lora/Specials/NijiV3Fantasy.safetensors" "D:/stable-diffusion-webui/models/Lora/Specials/ocIllustration_v10.safetensors" --ratios 0.4 0.4
it works. so the GUI somehow generates the cmd with sdxl_merge_lora.py while it should use merge_lora.py instead in case of no sdxl.

**Comment by michaeltran33** [comment]
I changed file library/merge_lora_gui.py line 71 
from "if not sd_model: to  if sd_model:" and the gui gens cmd correct. Dont know if it works in SDXL, bc I have no intention to move to that direction. Thanks for the guide and help. Pls lemme know when I should do a git pull for new version. Thanks.

**Comment by michaeltran33** [comment]
Sorry. Should not close this until you reviewed. My bad.

**Comment by bmaltais** [comment]
I implemented a fix in the dev2 branch. Will publish it in the next release. Use dev2 for now for the fix.
