### ISSUE TITLE
SDXLv1.0 text encoder loading error

### ISSUE THREAD

**Issue by attashe** [bmaltais/kohya_ss#1355]
I tried LoRA training using FurkanGozukara(SECourses) guide with next setup :
```
RTX3090, Windows 10
pytorch==2.0.1+cu117
open_clip_torch==2.20.0
transformers==4.32.0.dev0
accelerate==0.22.0.dev0
diffusers==0.19.2
others packages version from requirements.txt
Last version of kohya_ss repo
```

And got an error:

```
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
Traceback (most recent call last):
  File "K:\GitHub\kohya_ss\sdxl_train_network.py", line 174, in <module>
    trainer.train(args)
  File "K:\GitHub\kohya_ss\train_network.py", line 213, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "K:\GitHub\kohya_ss\sdxl_train_network.py", line 34, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V0_9, weight_dtype)
  File "K:\GitHub\kohya_ss\library\sdxl_train_util.py", line 33, in load_target_model
    ) = _load_target_model(
  File "K:\GitHub\kohya_ss\library\sdxl_train_util.py", line 70, in _load_target_model
    ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_version, name_or_path, device, weight_dtype)
  File "K:\GitHub\kohya_ss\library\sdxl_model_util.py", line 260, in load_models_from_sdxl_checkpoint
    info1 = text_model1.load_state_dict(te1_sd)
  File "C:\Users\yamih\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids".
...
```

As I understood, problem was with incorrect keys, and I found a fix in this line:

https://github.com/huggingface/diffusers/blob/e7e3749498921121d6e710cb7524f48617cec233/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L803

I've fix this modifying `sdxl_model_util.py : load_models_from_sdxl_checkpoint` code

```python
    # Fix for text_model1
    state_dict.pop("conditioner.embedders.0.transformer.text_model.embeddings.position_ids", None)
    
    for k in list(state_dict.keys()):
        if k.startswith("conditioner.embedders.0.transformer."):
            te1_sd[k.replace("conditioner.embedders.0.transformer.", "")] = state_dict.pop(k)
        elif k.startswith("conditioner.embedders.1.model."):
            te2_sd[k] = state_dict.pop(k)

    info1 = text_model1.load_state_dict(te1_sd)
    print("text encoder 1:", info1)

    converted_sd, logit_scale = convert_sdxl_text_encoder_2_checkpoint(te2_sd, max_length=77)
    converted_sd.pop("text_model.embeddings.position_ids", None)  # Fix for text_model2
    
    info2 = text_model2.load_state_dict(converted_sd)
    print("text encoder 2:", info2)
```

It works for me `text encoder 1: <All keys matched successfully>  text encoder 2: <All keys matched successfully>`

**Comment by Norod** [comment]
> I've fix this modifying sdxl_model_util.py : load_models_from_sdxl_checkpoint code
> ...
> It works for me `text encoder 1: <All keys matched successfully> text encoder 2: <All keys matched successfully>`

I tried it and it worked like charm, thank you very much for this information @attashe

**Comment by AIMads** [comment]
This doesn't fix the error for me. I still get following error log:
loading text encoders from checkpoint
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/humaid/Desktop/kohya_ss/./sdxl_train_network.py:176 in <module>        │
│                                                                              │
│   173 │   args = train_util.read_config_from_file(args, parser)              │
│   174 │                                                                      │
│   175 │   trainer = SdxlNetworkTrainer()                                     │
│ ❱ 176 │   trainer.train(args)                                                │
│   177                                                                        │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/train_network.py:214 in train                  │
│                                                                              │
│   211 │   │   vae_dtype = torch.float32 if args.no_half_vae else weight_dtyp │
│   212 │   │                                                                  │
│   213 │   │   # モデルを読み込む                                             │
│ ❱ 214 │   │   model_version, text_encoder, vae, unet = self.load_target_mode │
│   215 │   │                                                                  │
│   216 │   │   # text_encoder is List[CLIPTextModel] or CLIPTextModel         │
│   217 │   │   text_encoders = text_encoder if isinstance(text_encoder, list) │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/./sdxl_train_network.py:37 in                  │
│ load_target_model                                                            │
│                                                                              │
│    34 │   │   │   unet,                                                      │
│    35 │   │   │   logit_scale,                                               │
│    36 │   │   │   ckpt_info,                                                 │
│ ❱  37 │   │   ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_ │
│    38 │   │                                                                  │
│    39 │   │   self.load_stable_diffusion_format = load_stable_diffusion_form │
│    40 │   │   self.logit_scale = logit_scale                                 │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/library/sdxl_train_util.py:34 in               │
│ load_target_model                                                            │
│                                                                              │
│    31 │   │   │   │   unet,                                                  │
│    32 │   │   │   │   logit_scale,                                           │
│    33 │   │   │   │   ckpt_info,                                             │
│ ❱  34 │   │   │   ) = _load_target_model(                                    │
│    35 │   │   │   │   args.pretrained_model_name_or_path,                    │
│    36 │   │   │   │   args.vae,                                              │
│    37 │   │   │   │   model_version,                                         │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/library/sdxl_train_util.py:75 in               │
│ _load_target_model                                                           │
│                                                                              │
│    72 │   │   │   unet,                                                      │
│    73 │   │   │   logit_scale,                                               │
│    74 │   │   │   ckpt_info,                                                 │
│ ❱  75 │   │   ) = sdxl_model_util.load_models_from_sdxl_checkpoint(model_ver │
│    76 │   else:                                                              │
│    77 │   │   # Diffusers model is loaded to CPU                             │
│    78 │   │   from diffusers import StableDiffusionXLPipeline                │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/library/sdxl_model_util.py:264 in              │
│ load_models_from_sdxl_checkpoint                                             │
│                                                                              │
│   261 │   │   elif k.startswith("conditioner.embedders.1.model."):           │
│   262 │   │   │   te2_sd[k] = state_dict.pop(k)                              │
│   263 │                                                                      │
│ ❱ 264 │   info1 = text_model1.load_state_dict(te1_sd)                        │
│   265 │   print("text encoder 1:", info1)                                    │
│   266 │                                                                      │
│   267 │   converted_sd, logit_scale = convert_sdxl_text_encoder_2_checkpoint │
│                                                                              │
│ /home/humaid/Desktop/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/mod │
│ ules/module.py:2041 in load_state_dict                                       │
│                                                                              │
│   2038 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_k │
│   2039 │   │                                                                 │
│   2040 │   │   if len(error_msgs) > 0:                                       │
│ ❱ 2041 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {} │
│   2042 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(e │
│   2043 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)       │
│   2044                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".
