### ISSUE TITLE
AttributeError: module 'os' has no attribute 'statvfs' on Windows 10

### ISSUE THREAD

**Issue by murphysez** [bmaltais/kohya_ss#1358]
Attempting to run kohya_ss for the first time on a Windows 10 19045.3208. Web search seems to show lots of results indicating this isn't supported on Windows, but the results are all very old.

Installed kohya per the directions with Torch 2, and attempting to launch the GUI batch file results in the following error:

08:04:58-123990 INFO     Version: v21.8.7

08:04:58-132969 INFO     nVidia toolkit detected
08:04:59-652837 INFO     Torch 2.0.1+cu118
08:04:59-670788 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
08:04:59-672810 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 VRAM 8192 Arch (7, 5) Cores 46
08:04:59-675775 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
08:04:59-677794 INFO     Verifying modules instalation status from requirements.txt...
Traceback (most recent call last):
  File "D:\Git\kohya_ss\kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\components\base.py", line 29, in <module>
    from gradio.blocks import Block, BlockContext
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 26, in <module>
    from gradio import (
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\networking.py", line 18, in <module>
    from gradio.routes import App
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 44, in <module>
    import gradio.ranged_response as ranged_response
  File "D:\Git\kohya_ss\venv\lib\site-packages\gradio\ranged_response.py", line 12, in <module>
    from aiofiles.os import stat as aio_stat
  File "D:\Git\kohya_ss\venv\lib\site-packages\aiofiles\os.py", line 32, in <module>
    statvfs = wrap(os.statvfs)
AttributeError: module 'os' has no attribute 'statvfs'

**Comment by pynguin** [comment]
I am also getting the same error while trying to install and run

**Comment by tridasha** [comment]
Same issue. new install tried - pip install aiofiles==23.1.0, which someone said would fix it, but had no effect.

**Comment by tridasha** [comment]
Okay worked it out. the advise to run - pip install aiofiles==23.1.0 is correct. However, it is lacking a bunch of key information. You have to run this with the venv active. So:
1. run cmd and go into the kohya_ss\venv\Scripts  directory.
2. run the activate.bat
3. run pip install aiofiles==23.1.0
4. close the cmd, and start another one, then try kohya_ss\gui.bat

**Comment by DarkAlchy** [comment]
WHAT the you know what.  run pip install aiofiles==23.1.0 is the previous version (23.2.0 was uninstalled) and it worked.

**Comment by liuyinzhong** [comment]
> 

good

**Comment by murphysez** [comment]
> Okay worked it out. The advise to run - pip install aiofiles==23.1.0 is correct. However, it is lacking key information. You have to run this with the venv active. So:
> 
>     1. run cmd and go into the kohya_ss\venv\Scripts  directory.
> 
>     2. run the activate.bat
> 
>     3. run pip install aiofiles==23.1.0
> 
>     4. close the cmd, and start another one, then in the kohya_ss directory run gui.bat
> 
> 
> This would suggest the install script for kohya is not setting up the venv with the correct version of aiofiles module that includes the statvfs method that works for windows.

This did the trick! Thank you.
