### ISSUE TITLE
Please update to Python 3.11

### ISSUE THREAD

**Issue by CHJ85** [bmaltais/kohya_ss#1361]
Hi. The installation script only supports Python versions up to version 3.10.
**20:01:15-133757 ERROR    Incompatible Python version: 3.11.3 required 3.[9, 10]**
Please fix this. Thanks.

**Comment by bmaltais** [comment]
It will not work on 3.11... you absolutly need to use 3.10.6+

**Comment by CHJ85** [comment]
That's why I'm asking if you can update to Python 3.11.
3.11 is the new default.
That is one thing I really dislike about Python. As a developer, you have to constantly make sure it all works with each and every release.

**Comment by Fiendstar77** [comment]
how can i run kohya_ss with python 3.10.6 and keep python 3.11. for my sd next ?
