### ISSUE TITLE
Whatever I do, all I get is noise

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [bmaltais/kohya_ss#137]
I'm training on a simple 3D model to test KohyaSS and whatever I do, LORA, TI, SD1.5, SD2.1, all I get is noise. However how I caption the files or however I don't. Everyone is successful but I stay behind because IDK, there's something wrong with the installation maybe. I really don't know what's going on.

**Comment by bmaltais** [comment]
Change the default leraning rate for the UNet to "0.0001". The current one is too strong (0.001). I will update the default value in the next release.

**Comment by crackfoo** [comment]
I can confirm, this fixed my same issue. ty

**Comment by ARandomUserFromGithub** [comment]
Cool, tho reinstalling it fresh fixed it for me, now it works well!
