### ISSUE TITLE
Sample every n steps doesn't work.

### ISSUE THREAD

**Issue by FullStack0verfl0w** [bmaltais/kohya_ss#1375]
I have `Sample every n steps` set to 100 for LoRA, but it doesn't sample anything after every 100 steps. `Sample every n epochs` and `Save every n steps` work just fine

**Comment by marshalleq** [comment]
Yep, I noticed this too.

**Comment by pheobus63** [comment]
issue still exists :-(

**Comment by bmaltais** [comment]
Is the parameter showing in the command executed? If it does then this is probably an sd-scripts issue and not related to the GUI. You should open an issue with Koby’s on his repo so he can look into it.
