### ISSUE TITLE
Can't run captioning

### ISSUE THREAD

**Issue by placeboyue** [bmaltais/kohya_ss#1381]
It's probably not a bug but some error on my end, some conflict between some previous install of some other thing and this. 
But i cannot find a way to run captioning successfully (and therefore i haven't trained yet so that might be broken too)

i'll proceed to copy the console log

`20:57:13-633390 INFO     Captioning files in C:/Users/w/AI/Training/LORA training/Carey
                         Mulligan/lora/img/63_Carey_Mulligan woman...
20:57:13-633390 INFO     accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size=8
                         --general_threshold=0.35 --character_threshold=0.35 --caption_extension=".txt"
                         --model="SmilingWolf/wd-v1-4-convnextv2-tagger-v2" --max_data_loader_n_workers="2" --debug
                         --remove_underscore --frequency_tags "C:/Users/w/AI/Training/LORA training/Carey
                         Mulligan/lora/img/63_Carey_Mulligan woman"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
using existing wd14 tagger model
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\w\AI\Kohya_ss\kohya_ss\finetune\tag_images_by_wd14_tagger.py:303 in <module>            │
│                                                                                                  │
│   300 │   if args.character_threshold is None:                                                   │
│   301 │   │   args.character_threshold = args.thresh                                             │
│   302 │                                                                                          │
│ ❱ 303 │   main(args)                                                                             │
│   304                                                                                            │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\finetune\tag_images_by_wd14_tagger.py:99 in main                 │
│                                                                                                  │
│    96 │   │   print("using existing wd14 tagger model")                                          │
│    97 │                                                                                          │
│    98 │   # 画像を読み込む                                                                       │
│ ❱  99 │   model = load_model(args.model_dir)                                                     │
│   100 │                                                                                          │
│   101 │   # label_names = pd.read_csv("2022_0000_0899_6549/selected_tags.csv")                   │
│   102 │   # 依存ライブラリを増やしたくないので自力で読むよ                                       │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\keras\saving\saving_api.py:212 in         │
│ load_model                                                                                       │
│                                                                                                  │
│   209 │   │   )                                                                                  │
│   210 │                                                                                          │
│   211 │   # Legacy case.                                                                         │
│ ❱ 212 │   return legacy_sm_saving_lib.load_model(                                                │
│   213 │   │   filepath, custom_objects=custom_objects, compile=compile, **kwargs                 │
│   214 │   )                                                                                      │
│   215                                                                                            │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\keras\utils\traceback_utils.py:70 in      │
│ error_handler                                                                                    │
│                                                                                                  │
│    67 │   │   │   filtered_tb = _process_traceback_frames(e.__traceback__)                       │
│    68 │   │   │   # To get the full stack trace, call:                                           │
│    69 │   │   │   # `tf.debugging.disable_traceback_filtering()`                                 │
│ ❱  70 │   │   │   raise e.with_traceback(filtered_tb) from None                                  │
│    71 │   │   finally:                                                                           │
│    72 │   │   │   del filtered_tb                                                                │
│    73                                                                                            │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\tensorflow\python\saved_model\load.py:969 │
│ in load_partial                                                                                  │
│                                                                                                  │
│   966 │   │   loader = Loader(object_graph_proto, saved_model_proto, export_dir,                 │
│   967 │   │   │   │   │   │   ckpt_options, options, filters)                                    │
│   968 │     except errors.NotFoundError as err:                                                  │
│ ❱ 969 │   │   raise FileNotFoundError(                                                           │
│   970 │   │   │   str(err) + "\n You may be trying to load on a different device "               │
│   971 │   │   │   "from the computational device. Consider setting the "                         │
│   972 │   │   │   "`experimental_io_device` option in `tf.saved_model.LoadOptions` "             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
SmilingWolf/wd-v1-4-convnextv2-tagger-v2\variables\variables
 You may be trying to load on a different device from the computational device. Consider setting the
`experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\w\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main       │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\w\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code                  │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45  │
│ in main                                                                                          │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in      │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Users\w\AI\Kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in      │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\w\\AI\\Kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe',
'./finetune/tag_images_by_wd14_tagger.py', '--batch_size=8', '--general_threshold=0.35', '--character_threshold=0.35',
'--caption_extension=.txt', '--model=SmilingWolf/wd-v1-4-convnextv2-tagger-v2', '--max_data_loader_n_workers=2',
'--debug', '--remove_underscore', '--frequency_tags', 'C:/Users/w/AI/Training/LORA training/Carey
Mulligan/lora/img/63_Carey_Mulligan woman']' returned non-zero exit status 1.
20:57:46-321387 INFO     ...captioning done`

please help i tried everything i found online and anything i could think of

**Comment by kieranxsomer** [comment]
FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for SmilingWolf/wd-v1-4-convnextv2-tagger-v2\variables\variables You may be trying to load on a different device from the computational device. Consider setting theexperimental_io_deviceoption intf.saved_model.LoadOptions to the io_device such as '/job:localhost'.

That's what's killed it, dunno what you did for it, i'm not cranking at you -- just saying that's largley the thing that blew up--
I just upgraded my local copy (i'm on a potato mac) and got 1200 images tagged, maybe you clicked something wrong?

**Comment by placeboyue** [comment]
i dont think i clicked something wrong tbh, i uninstalled and tried different things. The BLIP tagger works, it's the only one. Maybe that's some clue?
I did see the error message but i wouldn't know what to do to fix it. Perhaps someone who understands anything about python and all that can point me in the right direction? i wouldn't even know what to google :( i didn't find any "intf.saved_model.loadOptions" file, and even if i did i think i would break more stuff

**Comment by placeboyue** [comment]
i tried to install triton and successfully did but kohya says "external modules blahblah can cause issues" and captioning with W14 still fails. I honestly ran out of ideas on what to do here. Perhaps trying some external W14 caption thingy and only train the lora with this...

**Comment by CJohnDesign** [comment]
I'm also getting this error on RunPod

**Comment by placeboyue** [comment]
I gave up on this, i managed to run "W14 captioning" on automatic1111 stable diffusion with an extension, it took me like 10 minutes to install and run. The LoRA training and such works just fine tho, i did test it.

**Comment by demib72** [comment]
Check the /SmilingWolf/wd-v1-4-convnextv2-tagger-v2 directory. The large files within the huggingface repository it is pulling from might not have downloaded fully. Was my issue when I was getting this.
