### ISSUE TITLE
no module named tqdm

### ISSUE THREAD

**Issue by zxsumd** [bmaltais/kohya_ss#1384]
13:17:27-823649 INFO     Version: v21.8.5

13:17:27-829653 INFO     nVidia toolkit detected
13:17:31-840648 INFO     Torch 2.0.1+cu118
13:17:31-852384 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:17:31-854384 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU VRAM 16384 Arch (8, 6) Cores 58
13:17:31-856685 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
13:17:31-861724 INFO     Verifying modules instalation status from requirements.txt...
13:17:35-234402 INFO     headless: False
13:17:35-240556 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
14:02:13-957901 INFO     Captioning files in C:/Users/zxsumd/Desktop/qinlan/image/10_qinlan...
14:02:13-958901 INFO     ./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1"
                         --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt"
                         "C:/Users/zxsumd/Desktop/qinlan/image/10_qinlan"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/mode
                         l_large_caption.pth"
Traceback (most recent call last):
  File "E:\sd\kohya_ss\finetune\make_captions.py", line 10, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
14:02:14-100273 INFO     ...captioning done

**Comment by FirminSun** [comment]
Try:
` pip install tqdm`

https://stackoverflow.com/questions/47529792/no-module-named-tqdm

**Comment by zxsumd** [comment]
The installation has been displayed, but it has not been resolved yet.
