### ISSUE TITLE
Kohya, the model training is extremely slow, what could be the reason?

### ISSUE THREAD

**Issue by wenwenwennnnn** [bmaltais/kohya_ss#1385]
23:24:47-916312 INFO     Version: v21.8.6

23:24:47-929891 INFO     nVidia toolkit detected
23:25:14-250176 INFO     Torch 2.0.1+cu118
23:25:14-334057 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:25:14-336691 INFO     Torch detected GPU: NVIDIA RTX A6000 VRAM 49140 Arch (8, 6) Cores 84
23:25:14-338790 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
23:25:14-341383 INFO     Verifying modules instalation status from requirements.txt...
23:25:30-033918 INFO     headless: False
23:25:30-038708 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.

Display headless: False, then training is very slow, 1500 steps can take up to 51 hours, please provide a solution

**Comment by FirminSun** [comment]
Maybe you can try:
1. Try cache the latent
2. Size the image

![image](https://github.com/bmaltais/kohya_ss/assets/16684985/716c6c25-702c-4796-af41-4b5297efdab7)

**Comment by ladydarkness** [comment]
> Maybe you can try:
> 
> 1. Try cache the latent
> 2. Size the image
> 
> ![image](https://user-images.githubusercontent.com/16684985/260742367-716c6c25-702c-4796-af41-4b5297efdab7.png)

Doesn't work, for some reason it's very slow, even in 512,512, even if have 5 images, even check these two caches, even if disable it. Do you have or anyone have some another idea of what's going on? It wasn't like this before.

I tried reinstalling from zero, the one thing different I saw was that message:
![image](https://github.com/bmaltais/kohya_ss/assets/18520008/59c23111-1d3b-41b8-97cc-c3be47fd9170)

Thank you for your attention in advance.
