### ISSUE TITLE
How  to set --network_train_unet_only in Ui of kohya-ss-gui when training SDXL Lora?

### ISSUE THREAD

**Issue by FirminSun** [bmaltais/kohya_ss#1395]
As the title say:How  to set --network_train_unet_only in Ui of kohya-ss-gui when training SDXL Lora?
Can you help me?

**Comment by LaikaSa** [comment]
This is a late response but in case you still need it, in the parameters' advance tab, there is a text box called Additional parameters, just put "--network_train_unet_only" without "" in there
