### ISSUE TITLE
Add --inbrowser and --server_port to utilities.py

### ISSUE THREAD

**Issue by mykeehu** [bmaltais/kohya_ss#140]
My request is simple: the utilities.py should be started in the same way as kohya_gui.py, i.e. with --inbrowser and --server_port arguments.

**Comment by bmaltais** [comment]
I will add the same argument setup to them in a nest update

**Comment by bmaltais** [comment]
Look in the dev branch, I have added support for them. Let me know if you run into issues.

**Comment by mykeehu** [comment]
Could something be wrong? I switched to dev branch, but utilities.py does not see the new commands

![image](https://user-images.githubusercontent.com/6390413/218173264-7926800d-64f2-4d59-b03c-6558b7731e1d.png)

**Comment by mykeehu** [comment]
Working after change to dev branch. Thank you for fast and great developing!
