### ISSUE TITLE
LoRA Training Error on Initialisation (RTX 3090 24GB)

### ISSUE THREAD

**Issue by gabrielconroy** [bmaltais/kohya_ss#1406]
I've followed all the set-up process in this [video](https://www.youtube.com/watch?v=AY6DMBCIZ3A). When I try to run the training I get this error and can't find anything online about it besides general Python stuff.

I have Python 3.10 installed, could that be the reason? Get this error even when only attempting 10 repetitions.

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\kohya_ss\sdxl_train_network.py:174 in <module>                                                │
│                                                                                                  │
│   171 │   args = train_util.read_config_from_file(args, parser)                                  │
│   172 │                                                                                          │
│   173 │   trainer = SdxlNetworkTrainer()                                                         │
│ ❱ 174 │   trainer.train(args)                                                                    │
│   175                                                                                            │
│                                                                                                  │
│ C:\kohya_ss\train_network.py:325 in train                                                        │
│                                                                                                  │
│   322 │   │   │   )                                                                              │
│   323 │   │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, ar   │
│   324 │   │                                                                                      │
│ ❱ 325 │   │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, train   │
│   326 │   │                                                                                      │
│   327 │   │   # dataloaderを準備する                                                             │
│   328 │   │   # DataLoaderのプロセス数：0はメインプロセスになる                                  │
│                                                                                                  │
│ C:\kohya_ss\library\train_util.py:3305 in get_optimizer                                          │
│                                                                                                  │
│   3302 │   if args.optimizer_args is not None and len(args.optimizer_args) > 0:                  │
│   3303 │   │   for arg in args.optimizer_args:                                                   │
│   3304 │   │   │   key, value = arg.split("=")                                                   │
│ ❱ 3305 │   │   │   value = ast.literal_eval(value)                                               │
│   3306 │   │   │                                                                                 │
│   3307 │   │   │   # value = value.split(",")                                                    │
│   3308 │   │   │   # for i in range(len(value)):                                                 │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py │
│ :110 in literal_eval                                                                             │
│                                                                                                  │
│    107 │   │   │   │   else:                                                                     │
│    108 │   │   │   │   │   return left - right                                                   │
│    109 │   │   return _convert_signed_num(node)                                                  │
│ ❱  110 │   return _convert(node_or_string)                                                       │
│    111                                                                                           │
│    112                                                                                           │
│    113 def dump(node, annotate_fields=True, include_attributes=False, *, indent=None):           │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py │
│ :109 in _convert                                                                                 │
│                                                                                                  │
│    106 │   │   │   │   │   return left + right                                                   │
│    107 │   │   │   │   else:                                                                     │
│    108 │   │   │   │   │   return left - right                                                   │
│ ❱  109 │   │   return _convert_signed_num(node)                                                  │
│    110 │   return _convert(node_or_string)                                                       │
│    111                                                                                           │
│    112                                                                                           │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py │
│ :83 in _convert_signed_num                                                                       │
│                                                                                                  │
│     80 │   │   │   │   return + operand                                                          │
│     81 │   │   │   else:                                                                         │
│     82 │   │   │   │   return - operand                                                          │
│ ❱   83 │   │   return _convert_num(node)                                                         │
│     84 │   def _convert(node):                                                                   │
│     85 │   │   if isinstance(node, Constant):                                                    │
│     86 │   │   │   return node.value                                                             │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py │
│ :74 in _convert_num                                                                              │
│                                                                                                  │
│     71 │   │   raise ValueError(msg + f': {node!r}')                                             │
│     72 │   def _convert_num(node):                                                               │
│     73 │   │   if not isinstance(node, Constant) or type(node.value) not in (int, float, comple  │
│ ❱   74 │   │   │   _raise_malformed_node(node)                                                   │
│     75 │   │   return node.value                                                                 │
│     76 │   def _convert_signed_num(node):                                                        │
│     77 │   │   if isinstance(node, UnaryOp) and isinstance(node.op, (UAdd, USub)):               │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ast.py │
│ :71 in _raise_malformed_node                                                                     │
│                                                                                                  │
│     68 │   │   msg = "malformed node or string"                                                  │
│     69 │   │   if lno := getattr(node, 'lineno', None):                                          │
│     70 │   │   │   msg += f' on line {lno}'                                                      │
│ ❱   71 │   │   raise ValueError(msg + f': {node!r}')                                             │
│     72 │   def _convert_num(node):                                                               │
│     73 │   │   if not isinstance(node, Constant) or type(node.value) not in (int, float, comple  │
│     74 │   │   │   _raise_malformed_node(node)                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: malformed node or string on line 1: <ast.Name object at 0x000001C8C1027EE0>
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:196 in _run_module_as_main                                                                    │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Program                                                                                       │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy. │
│ py:86 in _run_code                                                                               │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket',
'--min_bucket_reso=256', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=C:/ComfyUI_windows_portable/ComfyUI/models/checkpoints/sd_xl_base_1.0_0.9vae.safetensor
s', '--train_data_dir=C:/Users/benrn/Desktop\\img', '--resolution=1024,1024',
'--output_dir=C:/Users/benrn/Desktop\\model', '--logging_dir=C:/Users/benrn/Desktop\\log', '--network_alpha=1',
'--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.0004', '--unet_lr=0.0004',
'--network_dim=128', '--output_name=last', '--lr_scheduler_num_cycles=8', '--no_half_vae', '--learning_rate=0.0004',
'--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1520', '--save_every_n_epochs=1',
'--mixed_precision=bf16', '--save_precision=bf16', '--cache_latents', '--cache_latents_to_disk',
'--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=false', 'relative_step=false', 'warmup_init=false',
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']'
returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Something appear to be wrong with optimizer args. Try deleting them for a test and see if training start.

**Comment by gabrielconroy** [comment]
That worked. Thanks!
