### ISSUE TITLE
Training memory error for RTX 3090 24g

### ISSUE THREAD

**Issue by DuroCuri** [bmaltais/kohya_ss#1407]
Training error for RTX 3090 24g. When I start training, the vram will use 23.7g.
![Snipaste_2023-08-18_15-10-15](https://github.com/bmaltais/kohya_ss/assets/118010803/565a038f-c233-490a-9e3c-5509fb650c83)
Everything is ok before saving checkpoint, it always come up with this problem. I think this is because saving checkpoint will occupy vram. Obviously 0.3g vrams is not enough. As I observed, RTX 4090 will use 23.3g when training the same dataset, it will not come out this error when saving checkpoint.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Novelai\kohya_ss\sdxl_train.py:649 in <module>                                                │
│                                                                                                  │
│   646 │   args = parser.parse_args()                                                             │
│   647 │   args = train_util.read_config_from_file(args, parser)                                  │
│   648 │                                                                                          │
│ ❱ 649 │   train(args)                                                                            │
│   650                                                                                            │
│                                                                                                  │
│ D:\Novelai\kohya_ss\sdxl_train.py:556 in train                                                   │
│                                                                                                  │
│   553 │   │   if args.save_every_n_epochs is not None:                                           │
│   554 │   │   │   if accelerator.is_main_process:                                                │
│   555 │   │   │   │   src_path = src_stable_diffusion_ckpt if save_stable_diffusion_format els   │
│ ❱ 556 │   │   │   │   sdxl_train_util.save_sd_model_on_epoch_end_or_stepwise(                    │
│   557 │   │   │   │   │   args,                                                                  │
│   558 │   │   │   │   │   True,                                                                  │
│   559 │   │   │   │   │   accelerator,                                                           │
│                                                                                                  │
│ D:\Novelai\kohya_ss\library\sdxl_train_util.py:282 in save_sd_model_on_epoch_end_or_stepwise     │
│                                                                                                  │
│   279 │   │   │   save_dtype=save_dtype,                                                         │
│   280 │   │   )                                                                                  │
│   281 │                                                                                          │
│ ❱ 282 │   train_util.save_sd_model_on_epoch_end_or_stepwise_common(                              │
│   283 │   │   args,                                                                              │
│   284 │   │   on_epoch_end,                                                                      │
│   285 │   │   accelerator,                                                                       │
│                                                                                                  │
│ D:\Novelai\kohya_ss\library\train_util.py:4089 in save_sd_model_on_epoch_end_or_stepwise_common  │
│                                                                                                  │
│   4086 │   │                                                                                     │
│   4087 │   │   ckpt_file = os.path.join(args.output_dir, ckpt_name)                              │
│   4088 │   │   print(f"\nsaving checkpoint: {ckpt_file}")                                        │
│ ❱ 4089 │   │   sd_saver(ckpt_file, epoch_no, global_step)                                        │
│   4090 │   │                                                                                     │
│   4091 │   │   if args.huggingface_repo_id is not None:                                          │
│   4092 │   │   │   huggingface_util.upload(args, ckpt_file, "/" + ckpt_name)                     │
│                                                                                                  │
│ D:\Novelai\kohya_ss\library\sdxl_train_util.py:256 in sd_saver                                   │
│                                                                                                  │
│   253 ):                                                                                         │
│   254 │   def sd_saver(ckpt_file, epoch_no, global_step):                                        │
│   255 │   │   sai_metadata = train_util.get_sai_model_spec(None, args, True, False, False, is_   │
│ ❱ 256 │   │   sdxl_model_util.save_stable_diffusion_checkpoint(                                  │
│   257 │   │   │   ckpt_file,                                                                     │
│   258 │   │   │   text_encoder1,                                                                 │
│   259 │   │   │   text_encoder2,                                                                 │
│                                                                                                  │
│ D:\Novelai\kohya_ss\library\sdxl_model_util.py:509 in save_stable_diffusion_checkpoint           │
│                                                                                                  │
│   506 │   new_ckpt["global_step"] = steps                                                        │
│   507 │                                                                                          │
│   508 │   if model_util.is_safetensors(output_file):                                             │
│ ❱ 509 │   │   save_file(state_dict, output_file, metadata)                                       │
│   510 │   else:                                                                                  │
│   511 │   │   torch.save(new_ckpt, output_file)                                                  │
│   512                                                                                            │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\safetensors\torch.py:232 in save_file                 │
│                                                                                                  │
│   229 │   save_file(tensors, "model.safetensors")                                                │
│   230 │   ```                                                                                    │
│   231 │   """                                                                                    │
│ ❱ 232 │   serialize_file(_flatten(tensors), filename, metadata=metadata)                         │
│   233                                                                                            │
│   234                                                                                            │
│   235 def load_file(filename: Union[str, os.PathLike], device="cpu") -> Dict[str, torch.Tensor   │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\safetensors\torch.py:402 in _flatten                  │
│                                                                                                  │
│   399 │   │   │   """                                                                            │
│   400 │   │   )                                                                                  │
│   401 │                                                                                          │
│ ❱ 402 │   return {                                                                               │
│   403 │   │   k: {                                                                               │
│   404 │   │   │   "dtype": str(v.dtype).split(".")[-1],                                          │
│   405 │   │   │   "shape": v.shape,                                                              │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\safetensors\torch.py:406 in <dictcomp>                │
│                                                                                                  │
│   403 │   │   k: {                                                                               │
│   404 │   │   │   "dtype": str(v.dtype).split(".")[-1],                                          │
│   405 │   │   │   "shape": v.shape,                                                              │
│ ❱ 406 │   │   │   "data": _tobytes(v, k),                                                        │
│   407 │   │   }                                                                                  │
│   408 │   │   for k, v in tensors.items()                                                        │
│   409 │   }                                                                                      │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\safetensors\torch.py:372 in _tobytes                  │
│                                                                                                  │
│   369 │   newptr = ctypes.cast(ptr, ctypes.POINTER(ctypes.c_ubyte))                              │
│   370 │   data = np.ctypeslib.as_array(newptr, (total_bytes,))  # no internal copy               │
│   371 │                                                                                          │
│ ❱ 372 │   return data.tobytes()                                                                  │
│   373                                                                                            │
│   374                                                                                            │
│   375 def _flatten(tensors: Dict[str, torch.Tensor]) -> Dict[str, Dict[str, Any]]:               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
MemoryError
steps:  20%|██████████▍                                         | 1840/9200 [26:27:48<105:51:14, 51.78s/it, loss=0.122]╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\anaconda3\lib\runpy.py:196 in _run_module_as_main                                             │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ D:\anaconda3\lib\runpy.py:86 in _run_code                                                        │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main      │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\Novelai\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\Novelai\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train.py', '--enable_bucket','--min_bucket_reso=256', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=D:/Novelai/stable-diffusion-webui/models/Stable-diffusion/realistic/sdxl10ArienmixxlAsian_v10.safetensors', '--train_data_dir=D:\\photo\\processing\\zhoushuyi\\train',
'--reg_data_dir=D:\\photo\\processing\\zhoushuyi\\reg', '--resolution=1024,1408',
'--output_dir=D:/Novelai/stable-diffusion-webui/models/Stable-diffusion/zhoushuyi',
'--logging_dir=D:\\photo\\processing\\zhoushuyi\\log', '--save_model_as=safetensors', '--output_name=zhoushuyi',
'--lr_scheduler_num_cycles=10', '--max_token_length=150', '--max_data_loader_n_workers=0', '--learning_rate=2.24e-06',
'--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=460', '--train_batch_size=2', '--max_train_steps=9200',
'--save_every_n_epochs=2', '--mixed_precision=bf16', '--save_precision=bf16', '--caption_extension=.txt',
'--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--max_token_length=150',
'--keep_tokens=2', '--bucket_reso_steps=64', '--shuffle_caption', '--gradient_checkpointing', '--xformers',
'--bucket_no_upscale', '--noise_offset=0.0375', '--adaptive_noise_scale=0.0375']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Set your resolution to 1024,1024... your resolution is too high,

**Comment by DuroCuri** [comment]
> 
Thank you. If I want to finetune sdxl model, the base model used 1024x1024 to train. If I used resolution lower than it, is it a demage to model. Because these picture is blurry. Worse than the base data?

**Comment by bmaltais** [comment]
I have never tried for finetuning. I suspect it should be OK but might produce results that won't be as sharp. Worth testing.

**Comment by DuroCuri** [comment]
> 

Thank you!
