### ISSUE TITLE
How to run setup if python is not on path?

### ISSUE THREAD

**Issue by TeKett** [bmaltais/kohya_ss#1412]
I tried to add python to the path, does not work. Been a problem for years, my path is completely empty, yet everything works just fine. This too would not be an issue if i can just somehow specify to kohya where python is, like i do with a1111, since its in the place where it should be per default, and it has, as per default, an exe in the windows folder, and i can run 'py' in cmd just fine.

**Comment by bmaltais** [comment]
The gui is built aroung the installation of python 3.10.9. Did you select to add python to the windows path when you ran the installation? Might be why. You might have to re-install python and make sure to select the option to allow it to add to the path variables.
