### ISSUE TITLE
error, can't start train

### ISSUE THREAD

**Issue by 2575044704** [bmaltais/kohya_ss#1414]
**VAE: <All keys matched successfully>
[01:21:55] ERROR    failed (exitcode: -7) local_rank: 0 (pid:      api.py:672
                    2255697) of binary:                                      
                    /root/miniconda3/envs/sd-webui/bin/python                
╭──────────────────── Traceback (most recent call last) ────────────────────╮
│ /root/miniconda3/envs/sd-webui/bin/accelerate:8 in <module>               │
│                                                                           │
│   5 from accelerate.commands.accelerate_cli import main                   │
│   6 if __name__ == '__main__':                                            │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])  │
│ ❱ 8 │   sys.exit(main())                                                  │
│   9                                                                       │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/accelerate/co │
│ mmands/accelerate_cli.py:45 in main                                       │
│                                                                           │
│   42 │   │   exit(1)                                                      │
│   43 │                                                                    │
│   44 │   # Run                                                            │
│ ❱ 45 │   args.func(args)                                                  │
│   46                                                                      │
│   47                                                                      │
│   48 if __name__ == "__main__":                                           │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/accelerate/co │
│ mmands/launch.py:909 in launch_command                                    │
│                                                                           │
│   906 │   elif args.use_megatron_lm and not args.cpu:                     │
│   907 │   │   multi_gpu_launcher(args)                                    │
│   908 │   elif args.multi_gpu and not args.cpu:                           │
│ ❱ 909 │   │   multi_gpu_launcher(args)                                    │
│   910 │   elif args.tpu and not args.cpu:                                 │
│   911 │   │   if args.tpu_use_cluster:                                    │
│   912 │   │   │   tpu_pod_launcher(args)                                  │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/accelerate/co │
│ mmands/launch.py:604 in multi_gpu_launcher                                │
│                                                                           │
│   601 │   )                                                               │
│   602 │   with patch_environment(**current_env):                          │
│   603 │   │   try:                                                        │
│ ❱ 604 │   │   │   distrib_run.run(args)                                   │
│   605 │   │   except Exception:                                           │
│   606 │   │   │   if is_rich_available() and debug:                       │
│   607 │   │   │   │   console = get_console()                             │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/torch/distrib │
│ uted/run.py:785 in run                                                    │
│                                                                           │
│   782 │   │   )                                                           │
│   783 │                                                                   │
│   784 │   config, cmd, cmd_args = config_from_args(args)                  │
│ ❱ 785 │   elastic_launch(                                                 │
│   786 │   │   config=config,                                              │
│   787 │   │   entrypoint=cmd,                                             │
│   788 │   )(*cmd_args)                                                    │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/torch/distrib │
│ uted/launcher/api.py:134 in __call__                                      │
│                                                                           │
│   131 │   │   self._entrypoint = entrypoint                               │
│   132 │                                                                   │
│   133 │   def __call__(self, *args):                                      │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(ar │
│   135                                                                     │
│   136                                                                     │
│   137 def _get_entrypoint_name(                                           │
│                                                                           │
│ /root/miniconda3/envs/sd-webui/lib/python3.10/site-packages/torch/distrib │
│ uted/launcher/api.py:250 in launch_agent                                  │
│                                                                           │
│   247 │   │   │   # if the error files for the failed children exist      │
│   248 │   │   │   # @record will copy the first error (root cause)        │
│   249 │   │   │   # to the error file of the launcher process.            │
│ ❱ 250 │   │   │   raise ChildFailedError(                                 │
│   251 │   │   │   │   name=entrypoint_name,                               │
│   252 │   │   │   │   failures=result.failures,                           │
│   253 │   │   │   )                                                       │
╰───────────────────────────────────────────────────────────────────────────╯
ChildFailedError: 
=======================================================
./sdxl_train_network.py FAILED
-------------------------------------------------------
Failures:
[1]:
  time      : 2023-08-21_01:21:55
  host      : 8060b82bf090
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 2255698)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2255698
[2]:
  time      : 2023-08-21_01:21:55
  host      : 8060b82bf090
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 2255699)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2255699
[3]:
  time      : 2023-08-21_01:21:55
  host      : 8060b82bf090
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 2255700)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2255700
-------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-21_01:21:55
  host      : 8060b82bf090
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 2255697)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2255697
=======================================================
**

**Comment by chunish** [comment]
I catched the same error, how did you resolve it?
