### ISSUE TITLE
Is it possible to merge the LyCORIS model into SDXL?

### ISSUE THREAD

**Issue by zbulrush** [bmaltais/kohya_ss#1418]
LyCORIS has its own unique advantages. Can it support the merging function?

**Comment by bmaltais** [comment]
Technically you can do it via ComfyUI... but I don't think the native LyCORIS tool has been updated to merge into SDXL:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/16d8bc7b-937a-4b36-b77c-0a087503ec84)

**Comment by magicwang1111** [comment]
> Technically you can do it via ComfyUI... but I don't think the native LyCORIS tool has been updated to merge into SDXL:从技术上讲，您可以通过 ComfyUI 来完成此操作...但我认为本机 LyCORIS 工具尚未更新以合并到 SDXL 中：
> 
> ![image](https://user-images.githubusercontent.com/7474674/262091324-16d8bc7b-937a-4b36-b77c-0a087503ec84.png)

how to use comfui to merge  LyCORIS into sdxl? i have tested that merge lora into sdxl can work.or when will you update this feature?
