### ISSUE TITLE
--listen compatibilities 

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [bmaltais/kohya_ss#142]
Is there a way to run this with --listen to allow other devices on the same network to access the interface while all the back end is done of the host system, and can we change the port that is used if so how many I do this.

**Comment by difelice** [comment]
You can pass `--listen 0.0.0.0` as per documentation: https://github.com/bmaltais/kohya_ss#launching-the-gui-using-guibat-or-guips1
