### ISSUE TITLE
ModuleNotFoundError: No module named 'library'

### ISSUE THREAD

**Issue by JanHmmr** [bmaltais/kohya_ss#1421]
Hey,
After installing everything it still says ModuleNotFoundError: No module named 'library'
Checking the VENV it is installed: 

"(venv) C:\Users\xxx\Pictures\kohya_ss-master\kohya_ss-master>pip list
Package                      Version
---------------------------- ---------
absl-py                      1.4.0
accelerate                   0.19.0
aiofiles                     23.2.1
aiohttp                      3.8.5
aiosignal                    1.3.1
altair                       4.2.2
annotated-types              0.5.0
anyio                        3.7.1
appdirs                      1.4.4
astunparse                   1.6.3
async-timeout                4.0.3
attrs                        23.1.0
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.2.0
click                        8.1.7
colorama                     0.4.6
contourpy                    1.1.0
cycler                       0.11.0
dadaptation                  3.1
diffusers                    0.18.2
distlib                      0.3.7
docker-pycreds               0.4.0
easygui                      0.98.3
einops                       0.6.0
entrypoints                  0.4
exceptiongroup               1.1.3
fairscale                    0.4.13
fastapi                      0.101.1
ffmpy                        0.3.1
filelock                     3.12.2
flatbuffers                  23.5.26
fonttools                    4.42.1
frozenlist                   1.4.0
fsspec                       2023.6.0
ftfy                         6.1.1
gast                         0.4.0
gitdb                        4.0.10
GitPython                    3.1.32
google-auth                  2.22.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
gradio                       3.36.1
gradio_client                0.4.0
grpcio                       1.57.0
h11                          0.14.0
h5py                         3.9.0
httpcore                     0.17.3
httpx                        0.24.1
huggingface-hub              0.15.1
idna                         3.4
importlib-metadata           6.8.0
invisible-watermark          0.2.0
jax                          0.4.14
Jinja2                       3.1.2
jsonschema                   4.19.0
jsonschema-specifications    2023.7.1
keras                        2.12.0
kiwisolver                   1.4.4
libclang                     16.0.6
Library                      0.0.0
lightning-utilities          0.9.0
linkify-it-py                2.0.2
lion-pytorch                 0.0.6
lycoris-lora                 1.8.3
Markdown                     3.4.4
markdown-it-py               2.2.0
MarkupSafe                   2.1.3
matplotlib                   3.7.2
mdit-py-plugins              0.3.3
mdurl                        0.1.2
ml-dtypes                    0.2.0
mpmath                       1.3.0
multidict                    6.0.4
mypy-extensions              1.0.0
networkx                     3.1
numpy                        1.23.5
oauthlib                     3.2.2
open-clip-torch              2.20.0
opencv-python                4.7.0.68
opt-einsum                   3.3.0
orjson                       3.9.5
packaging                    23.1
pandas                       2.0.3
pathtools                    0.1.2
Pillow                       10.0.0
pip                          22.2.1
platformdirs                 3.10.0
prodigyopt                   1.0
protobuf                     3.20.3
psutil                       5.9.5
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pydantic                     2.2.1
pydantic_core                2.6.1
pydub                        0.25.1
Pygments                     2.16.1
pyparsing                    3.0.9
pyre-extensions              0.0.29
python-dateutil              2.8.2
python-multipart             0.0.6
pytorch-lightning            1.9.0
pytz                         2023.3
PyWavelets                   1.4.1
PyYAML                       6.0.1
referencing                  0.30.2
regex                        2023.8.8
requests                     2.31.0
requests-oauthlib            1.3.1
rich                         13.4.1
rpds-py                      0.9.2
rsa                          4.9
safetensors                  0.3.1
scipy                        1.11.2
semantic-version             2.10.0
sentencepiece                0.1.99
sentry-sdk                   1.29.2
setproctitle                 1.3.2
setuptools                   63.2.0
six                          1.16.0
smmap                        5.0.0
sniffio                      1.3.0
starlette                    0.27.0
sympy                        1.12
tensorboard                  2.12.3
tensorboard-data-server      0.7.1
tensorflow                   2.12.0
tensorflow-estimator         2.12.0
tensorflow-intel             2.12.0
tensorflow-io-gcs-filesystem 0.31.0
termcolor                    2.3.0
timm                         0.6.12
tk                           0.1.0
tokenizers                   0.13.3
toml                         0.10.2
toolz                        0.12.0
torch                        2.0.1
torchmetrics                 1.0.3
torchvision                  0.15.2
tqdm                         4.66.1
transformers                 4.30.2
typing_extensions            4.7.1
typing-inspect               0.9.0
tzdata                       2023.3
uc-micro-py                  1.0.2
urllib3                      1.26.16
uvicorn                      0.23.2
virtualenv                   20.24.3
voluptuous                   0.13.1
wandb                        0.15.0
wcwidth                      0.2.6
websockets                   11.0.3
Werkzeug                     2.3.7
wheel                        0.41.1
wrapt                        1.14.1
xformers                     0.0.20
yarl                         1.9.2
zipp                         3.16.2
"

What could be the reason? 

I also added the Projects Main Path to my PATH

Does anyone know why the Error still occurs?

**Comment by AsaTyr2018** [comment]
got the same problem. 
correct me if i´m wrong. but could it be that "Library" is broken?

![grafik](https://github.com/bmaltais/kohya_ss/assets/43162495/163fa8a1-ba02-44e7-a401-628059589051)

Version 0.0.0?

**Comment by marvin0815** [comment]
Add

```
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

```

somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py

**Comment by AsaTyr2018** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

Thats the stuff kings are made of =D

Thanks a lot! This finally works. Had other similar "workarounds" but this one finally works.

**Comment by Sudgary003** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

Solved my issue!

**Comment by oojar** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

marvin0815 you star! That actually worked !

**Comment by AcTePuKc** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

Thank you for your help! I was struggling all night and couldn't seem to find a solution.
After editing tag_images_by_wd14_tagger.py it looks like something like this

```
import argparse
import csv
import glob
import os
import sys

from PIL import Image
import cv2
from tqdm import tqdm
import numpy as np
from tensorflow.keras.models import load_model
from huggingface_hub import hf_hub_download
import torch
from pathlib import Path

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import library.train_util as train_util ```

I still got this Warning but at least it proceeded with the process

``` NOTE: Redirects are currently not supported in Windows or MacOs.                     redirects.py:27
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-SPCCJVG]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-SPCCJVG]:29500 (system error: 10049 - The requested address is not valid in its context.).
downloading wd14 tagger model from hf_hub. id: SmilingWolf/wd-v1-4-convnext-tagger-v2
F:\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py:1104: FutureWarning: The `force_filename` parameter is deprecated as a new caching system, which keeps the filenames as they are on the Hub, is now in place.
  warnings.warn( ```

**Comment by cmd-d** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

Thanks man! this actually worked

**Comment by will9829** [comment]
> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

jesus you are such a god

**Comment by RAHoebe** [comment]
Yes it works!

**Comment by Taikakim** [comment]
I tried in the Colab version, and it got past that error message about 'library', but got a ton of other warnings and errors instead:
```
22:19:02-721159 INFO     Captioning files in /content/drive/MyDrive/ai-train-data/wendelin...       
22:19:02-722430 INFO     accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size=12
                         --general_threshold=0.35 --character_threshold=0.35                        
                         --caption_extension=".txt" --model="SmilingWolf/wd-v1-4-vit-tagger-v2"     
                         --max_data_loader_n_workers="2" --debug --remove_underscore                
                         --frequency_tags "/content/drive/MyDrive/ai-train-data/wendelin"           
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
2023-12-18 22:19:06.541574: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-18 22:19:06.541621: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-18 22:19:06.543503: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-18 22:19:07.543735: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
downloading wd14 tagger model from hf_hub. id: SmilingWolf/wd-v1-4-convnext-tagger-v2
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1155: FutureWarning: The `force_filename` parameter is deprecated as a new caching system, which keeps the filenames as they are on the Hub, is now in place.
  warnings.warn(
keras_metadata.pb: 100% 654k/654k [00:00<00:00, 80.2MB/s]
saved_model.pb: 100% 5.71M/5.71M [00:00<00:00, 88.9MB/s]
selected_tags.csv: 100% 254k/254k [00:00<00:00, 1.07MB/s]
variables.data-00000-of-00001: 100% 388M/388M [00:00<00:00, 435MB/s]
variables.index: 100% 22.6k/22.6k [00:00<00:00, 57.5MB/s]
2023-12-18 22:19:18.444885: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
found 22 images.
  0% 0/2 [00:00<?, ?it/s]2023-12-18 22:19:33.301019: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:447] Loaded runtime CuDNN library: 8.5.0 but source was compiled with: 8.9.4.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-12-18 22:19:33.302055: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at conv_ops_impl.h:1199 : UNIMPLEMENTED: DNN library is not found.
  0% 0/2 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/content/kohya_ss/./finetune/tag_images_by_wd14_tagger.py", line 308, in <module>
    main(args)
  File "/content/kohya_ss/./finetune/tag_images_by_wd14_tagger.py", line 216, in main
    run_batch(b_imgs)
  File "/content/kohya_ss/./finetune/tag_images_by_wd14_tagger.py", line 132, in run_batch
    probs = model(imgs, training=False)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 5883, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnimplementedError: Exception encountered when calling layer 'root_conv2d' (type Conv2D).

{{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. [Op:Conv2D] name: 

Call arguments received by layer 'root_conv2d' (type Conv2D):
  • inputs=tf.Tensor(shape=(12, 448, 448, 3), dtype=float32)
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', './finetune/tag_images_by_wd14_tagger.py', '--batch_size=12', '--general_threshold=0.35', '--character_threshold=0.35', '--caption_extension=.txt', '--model=SmilingWolf/wd-v1-4-vit-tagger-v2', '--max_data_loader_n_workers=2', '--debug', '--remove_underscore', '--frequency_tags', '/content/drive/MyDrive/ai-train-data/wendelin']' returned non-zero exit status 1.
22:19:37-195467 INFO     ...captioning done 
```

**Comment by skyfrostz** [comment]
thx bro

> Add
> 
> ```
> import os
> import sys
> 
> sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
> ```
> 
> somewhere before `import library.train_util` in finetune/tag_images_by_wd14_tagger.py or whatever you're trying to run

**Comment by Alexadar** [comment]
solved with install of kohya-ss as local package. run "pip install -e ." in kohya-ss folder
