### ISSUE TITLE
How can I extract a lora from two sdxl models?

### ISSUE THREAD

**Issue by FrostyForest** [bmaltais/kohya_ss#1422]
It seems that the extract_lora_from_models.py doesn't work correctly on sdxl models?

**Comment by bmaltais** [comment]
Use this utility:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/30a12179-9bae-46c4-b7f8-4fcc53873d6f)

and make sure to select the SDXL option when extracting the LoRA.

**Comment by FrostyForest** [comment]
> Use this utility:
> 
> ![image](https://user-images.githubusercontent.com/7474674/262331555-30a12179-9bae-46c4-b7f8-4fcc53873d6f.png)
> 
> and make sure to select the SDXL option when extracting the LoRA.

ok,thank you.
