### ISSUE TITLE
dreambooth trainning seems to have some problem with 4090

### ISSUE THREAD

**Issue by dalcefo** [bmaltais/kohya_ss#1430]
hello.
i have 2 PC.
one of them has 4090 and the other one has 3090.

In the case of model training on the main PC using the 4090, it took almost 50 hours with around 100 images on SDXL.
Somehow, it was strange, so I ran it on a PC with the 3090 installed with the same settings. It took less than 10 hours.
Even this sub PC is only the GPU is usable and other parts such as the CPU are using older models.

I've tried plenty of different optimizers and settings, and tried them with the settings recommended by the coder, but I can't help but think that this application has some issues with the 4090.

Is it just me? Has anyone else had lingering symptoms on the 4090?

**Comment by pphu** [comment]
See https://github.com/bmaltais/kohya_ss/issues/1288
