### ISSUE TITLE
lora bug.. help

### ISSUE THREAD

**Issue by pakachu4** [bmaltais/kohya_ss#1436]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮

│ C:\ko\kohya_ss\train_db.py:481 in <module>                                                       │

│                                                                                                  │

│   478 │   args = parser.parse_args()                                                             │

│   479 │   args = train_util.read_config_from_file(args, parser)                                  │

│   480 │                                                                                          │

│ ❱ 481 │   train(args)                                                                            │

│   482                                                                                            │

│                                                                                                  │

│ C:\ko\kohya_ss\train_db.py:164 in train                                                          │

│                                                                                                  │

│   161 │   else:                                                                                  │

│   162 │   │   trainable_params = unet.parameters()                                               │

│   163 │                                                                                          │

│ ❱ 164 │   _, _, optimizer = train_util.get_optimizer(args, trainable_params)                     │

│   165 │                                                                                          │

│   166 │   # dataloaderを準備する                                                                 │

│   167 │   # DataLoaderのプロセス数：0はメインプロセスになる                                      │

│                                                                                                  │

│ C:\ko\kohya_ss\library\train_util.py:3329 in get_optimizer                                       │

│                                                                                                  │

│   3326 │   optimizer_kwargs = {}                                                                 │

│   3327 │   if args.optimizer_args is not None and len(args.optimizer_args) > 0:                  │

│   3328 │   │   for arg in args.optimizer_args:                                                   │

│ ❱ 3329 │   │   │   key, value = arg.split("=")                                                   │

│   3330 │   │   │   value = ast.literal_eval(value)                                               │

│   3331 │   │   │                                                                                 │

│   3332 │   │   │   # value = value.split(",")                                                    │

╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

ValueError: not enough values to unpack (expected 2, got 1)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮

│ C:\Program Files\Python310\lib\runpy.py:196 in _run_module_as_main                               │

│                                                                                                  │

│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │

│   194 │   if alter_argv:                                                                         │

│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │

│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │

│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │

│   198                                                                                            │

│   199 def run_module(mod_name, init_globals=None,                                                │

│                                                                                                  │

│ C:\Program Files\Python310\lib\runpy.py:86 in _run_code                                          │

│                                                                                                  │

│    83 │   │   │   │   │      __loader__ = loader,                                                │

│    84 │   │   │   │   │      __package__ = pkg_name,                                             │

│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │

│ ❱  86 │   exec(code, run_globals)                                                                │

│    87 │   return run_globals                                                                     │

│    88                                                                                            │

│    89 def _run_module_code(code, init_globals=None,                                              │

│                                                                                                  │

│ in <module>:7                                                                                    │

│                                                                                                  │

│   4 from accelerate.commands.accelerate_cli import main                                          │

│   5 if __name__ == '__main__':                                                                   │

│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │

│ ❱ 7 │   sys.exit(main())                                                                         │

│   8                                                                                              │

│                                                                                                  │

│ C:\ko\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main           │

│                                                                                                  │

│   42 │   │   exit(1)                                                                             │

│   43 │                                                                                           │

│   44 │   # Run                                                                                   │

│ ❱ 45 │   args.func(args)                                                                         │

│   46                                                                                             │

│   47                                                                                             │

│   48 if __name__ == "__main__":                                                                  │

│                                                                                                  │

│ C:\ko\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command        │

│                                                                                                  │

│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │

│   916 │   │   sagemaker_launcher(defaults, args)                                                 │

│   917 │   else:                                                                                  │

│ ❱ 918 │   │   simple_launcher(args)                                                              │

│   919                                                                                            │

│   920                                                                                            │

│   921 def main():                                                                                │

│                                                                                                  │

│ C:\ko\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher       │

│                                                                                                  │

│   577 │   process.wait()                                                                         │

│   578 │   if process.returncode != 0:                                                            │

│   579 │   │   if not args.quiet:                                                                 │

│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │

│   581 │   │   else:                                                                              │

│   582 │   │   │   sys.exit(1)                                                                    │

│   583                                                                                            │

╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

CalledProcessError: Command '['C:\\ko\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--v2', '--enable_bucket',

'--min_bucket_reso=256', '--max_bucket_reso=2048',

'--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-base', '--train_data_dir=C:/test/image',

'--resolution=512,512', '--output_dir=C:/test/output', '--logging_dir=C:/test/log', '--output_name=last',

'--lr_scheduler_num_cycles=5', '--max_token_length=150', '--max_data_loader_n_workers=2', '--learning_rate=0.0001',

'--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=88', '--train_batch_size=6', '--max_train_steps=1750',

'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt',

'--optimizer_type=AdamW8bit', '--optimizer_args', '1e-4', '--lr_scheduler_args', '1e-4',

'--max_data_loader_n_workers=2', '--max_token_length=150', '--bucket_reso_steps=64', '--mem_eff_attn',

'--shuffle_caption', '--gradient_checkpointing', '--xformers', '--persistent_data_loader_workers',

'--bucket_no_upscale', '--random_crop', '--noise_offset=0.0']' returned non-zero exit status 1.

I haven't solved this problem for three hours help..

**Comment by FurkanGozukara** [comment]
i think this is related to training images

**Comment by marshalleq** [comment]
What does this mean 'related to training images'.  Do you mean _**'the'**_ training images?  So the training images need to be something specific?
