### ISSUE TITLE
SDXL lora training is crashing for last 2-3 days

### ISSUE THREAD

**Issue by utsav1232002** [bmaltais/kohya_ss#1437]
for last 2-3 days all of my sdxl lora trainings are crashing after 3-4 epoch. i use rtx 3090.
![Screenshot 2023-08-24 195208](https://github.com/bmaltais/kohya_ss/assets/122025114/728f1158-7db2-43ef-84ea-7e7e1a464860)
![Screenshot 2023-08-24 195257](https://github.com/bmaltais/kohya_ss/assets/122025114/1e928f4c-0489-42a3-8e8f-df467265708e)

**Comment by AURORA-HA** [comment]
I am having the same issue and it's not only the last 3 days it's been happening since the first day I downloaded it, I have tried many different ways and still getting same error, if you find a solution could you please update?

**Comment by joneschunghk** [comment]
I've had the same problem before. When I use the same character training settings to train the cityscape dataset. It caused oom error after running few steps. I think it's because the image content is more complex. My solution is to lower Network Rank and Network Alpha (from 64,32 to 32,16).

**Comment by bmaltais** [comment]
This is caused by an update of the NVidia drivers on windows. Revert to the July version of the drivers. Problem solved. NVidia introduced a bug in the latest version.
