### ISSUE TITLE
lose pillow

### ISSUE THREAD

**Issue by cqqzyx** [bmaltais/kohya_ss#1439]
My kohya_ SS started everything normally, but when I tried to train, it told me that the Pillow module was missing. How to handle this issue.

The environment I run in is Docker. Everything was normal during the installation process.

I tried adding Pillow=10.0.0 in requirements. txt, but it didn't work.

My operating system is Debian11

The exceptions are as follows:

CLIPImageProcessor requires the PIL library but it was not found in your
environment. You can install it with pip:
`pip install pillow`. Please note that you may need to restart your runtime
after installation.

**Comment by rpfile** [comment]
what if you activate the environment (source venv/bin/activate) and then issue that command (pip install pillow)?

**Comment by cqqzyx** [comment]
I have resolved the issue and executed the pip install pipeline in the Docker container

**Comment by yu840732962** [comment]
May I ask how it was resolved
