### ISSUE TITLE
Can't train SDXL models for some reason

### ISSUE THREAD

**Issue by link-1227** [bmaltais/kohya_ss#1442]
I get error cuDNN error: CUDNN_STATUS_NOT_INITIALIZED when I try to train on any sdxl model. Any other model works perfectly fine, I've updated kohya to no avail.

Any ideas?

Error below

> Modules installed outside the virtual environment were found.
> This can cause issues. Please review the installed modules.
> 
> You can uninstall all local modules with:
> 
> deactivate
> pip freeze > uninstall.txt
> pip uninstall -y -r uninstall.txt
> =============================================================
> 
> 15:17:31-658865 INFO     Version: v21.8.8
> 
> 15:17:31-663035 INFO     nVidia toolkit detected
> 15:17:32-456385 INFO     Torch 2.0.1+cu118
> 15:17:32-466366 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
> 15:17:32-467363 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
> 15:17:32-468864 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
> 15:17:32-469863 INFO     Verifying modules instalation status from requirements.txt...
> 15:17:33-854983 INFO     headless: False
> 15:17:33-856977 INFO     Load CSS...
> Running on local URL:  http://127.0.0.1:7860
> 
> ─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ A:\AI image\kohya_ss\sdxl_train_network.py:176 in <module>                                       │
> │                                                                                                  │
> │   173 │   args = train_util.read_config_from_file(args, parser)                                  │
> │   174 │                                                                                          │
> │   175 │   trainer = SdxlNetworkTrainer()                                                         │
> │ ❱ 176 │   trainer.train(args)                                                                    │
> │   177                                                                                            │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\train_network.py:798 in train                                               │
> │                                                                                                  │
> │   795 │   │   │   │   │                                                                          │
> │   796 │   │   │   │   │   loss = loss.mean()  # 平均なのでbatch_sizeで割る必要なし               │
> │   797 │   │   │   │   │                                                                          │
> │ ❱ 798 │   │   │   │   │   accelerator.backward(loss)                                             │
> │   799 │   │   │   │   │   if accelerator.sync_gradients and args.max_grad_norm != 0.0:           │
> │   800 │   │   │   │   │   │   params_to_clip = network.get_trainable_params()                    │
> │   801 │   │   │   │   │   │   accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)    │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1743 in backward           │
> │                                                                                                  │
> │   1740 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
> │   1741 │   │   │   return                                                                        │
> │   1742 │   │   elif self.scaler is not None:                                                     │
> │ ❱ 1743 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
> │   1744 │   │   else:                                                                             │
> │   1745 │   │   │   loss.backward(**kwargs)                                                       │
> │   1746                                                                                           │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\torch\_tensor.py:487 in backward                     │
> │                                                                                                  │
> │    484 │   │   │   │   create_graph=create_graph,                                                │
> │    485 │   │   │   │   inputs=inputs,                                                            │
> │    486 │   │   │   )                                                                             │
> │ ❱  487 │   │   torch.autograd.backward(                                                          │
> │    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
> │    489 │   │   )                                                                                 │
> │    490                                                                                           │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py:200 in backward           │
> │                                                                                                  │
> │   197 │   # The reason we repeat same the comment below is that                                  │
> │   198 │   # some Python versions print out the first line of a multi-line function               │
> │   199 │   # calls in the traceback and some print out the last line                              │
> │ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
> │   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
> │   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
> │   203                                                                                            │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
> steps:   0%|                                                                                  | 0/1300 [00:05<?, ?it/s]
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ C:\Python310\lib\runpy.py:196 in _run_module_as_main                                             │
> │                                                                                                  │
> │   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
> │   194 │   if alter_argv:                                                                         │
> │   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
> │ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
> │   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
> │   198                                                                                            │
> │   199 def run_module(mod_name, init_globals=None,                                                │
> │                                                                                                  │
> │ C:\Python310\lib\runpy.py:86 in _run_code                                                        │
> │                                                                                                  │
> │    83 │   │   │   │   │      __loader__ = loader,                                                │
> │    84 │   │   │   │   │      __package__ = pkg_name,                                             │
> │    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
> │ ❱  86 │   exec(code, run_globals)                                                                │
> │    87 │   return run_globals                                                                     │
> │    88                                                                                            │
> │    89 def _run_module_code(code, init_globals=None,                                              │
> │                                                                                                  │
> │ in <module>:7                                                                                    │
> │                                                                                                  │
> │   4 from accelerate.commands.accelerate_cli import main                                          │
> │   5 if __name__ == '__main__':                                                                   │
> │   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
> │ ❱ 7 │   sys.exit(main())                                                                         │
> │   8                                                                                              │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main     │
> │                                                                                                  │
> │   42 │   │   exit(1)                                                                             │
> │   43 │                                                                                           │
> │   44 │   # Run                                                                                   │
> │ ❱ 45 │   args.func(args)                                                                         │
> │   46                                                                                             │
> │   47                                                                                             │
> │   48 if __name__ == "__main__":                                                                  │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command  │
> │                                                                                                  │
> │   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
> │   916 │   │   sagemaker_launcher(defaults, args)                                                 │
> │   917 │   else:                                                                                  │
> │ ❱ 918 │   │   simple_launcher(args)                                                              │
> │   919                                                                                            │
> │   920                                                                                            │
> │   921 def main():                                                                                │
> │                                                                                                  │
> │ A:\AI image\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher │
> │                                                                                                  │
> │   577 │   process.wait()                                                                         │
> │   578 │   if process.returncode != 0:                                                            │
> │   579 │   │   if not args.quiet:                                                                 │
> │ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
> │   581 │   │   else:                                                                              │
> │   582 │   │   │   sys.exit(1)                                                                    │
> │   583                                                                                            │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> CalledProcessError: Command '['A:\\AI image\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py',
> '--pretrained_model_name_or_path=A:/AI image/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors',
> '--train_data_dir=A:/images/Amanda', '--resolution=1024,1024', '--output_dir=A:/AI
> Image/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora',
> '--logging_dir=C:/git/Data/Dreambooth\\log', '--network_alpha=64', '--save_model_as=safetensors',
> '--network_module=networks.lora', '--network_dim=128', '--output_name=Amandaxx1-sdxl-500',
> '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=1e-05', '--lr_scheduler=cosine',
> '--train_batch_size=1', '--max_train_steps=1300', '--save_every_n_epochs=1', '--mixed_precision=fp16',
> '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Adafactor',
> '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--gradient_checkpointing', '--xformers',
> '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
> 
>

**Comment by Sinay-Show** [comment]
Same problem

**Comment by link-1227** [comment]
> Same problem

Which driver are you on?

**Comment by Fade07w** [comment]
Same problem ever find solution?

**Comment by link-1227** [comment]
> Same problem ever find solution?

It just magically started working.

I did a git pull in the kohya folder and updated my video card driver, then went back to the 531 driver to avoid that memory leak issue. No idea if that's what did it, but give it a try

**Comment by huitang96** [comment]
some problem:
  File "D:\projects\AI\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\projects\AI\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
