### ISSUE TITLE
Are there any way to reduce system RAM usage? I am trying to make a tutorial for free colab SDXL LoRA training

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1443]
Hello. I am trying to make a tutorial for free colab

It has good GPU but the problem is system ram is only 13 GB

We need some options or way to reduce RAM usage

**Comment by FurkanGozukara** [comment]
well i made it work with free Kaggle

hopefully a tutorial coming soon

**Comment by adolfocesar1** [comment]
i trained a lora sdxl in colab today (5.19it/s removing --mem_eff_attn): !accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=1024 --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --train_data_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/img" --resolution="1024,1024" --output_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/model" --logging_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0005 --unet_lr=0.0005 --network_dim=64 --output_name="caronte-sdxl" --lr_scheduler_num_cycles="5" --no_half_vae --learning_rate="0.0005" --lr_scheduler="cosine" --lr_warmup_steps="0" --train_batch_size="4" --max_train_steps="638" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="Adafactor" --max_data_loader_n_workers="0" --keep_tokens="1" --bucket_reso_steps=64 --min_snr_gamma=5 --mem_eff_attn  --gradient_checkpointing --full_fp16 --xformers --bucket_no_upscale --noise_offset=0.0375 --lowram --network_train_unet_only --cache_text_encoder_outputs --sample_sampler=euler_a --sample_prompts="/content/drive/MyDrive/LoRA/characters/death-skull-caronte/model/sample/prompt.txt" --sample_every_n_steps="200" 

i still had memory left and the lora was amazing.
i love your videos.

(off-topic question: did you invest in ads for your udemy course? it was a great success. i'm finishing editing one on 'creating webtoons with a.i' and i keep wondering if the platform is capable of showing my course to other people or if i need to be 100% in charge of the marketing)....

(sorry for the bad English, Deepl)

**Comment by FurkanGozukara** [comment]
> i trained a lora sdxl in colab today (5.19it/s removing --mem_eff_attn): !accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket --min_bucket_reso=256 --max_bucket_reso=1024 --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --train_data_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/img" --resolution="1024,1024" --output_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/model" --logging_dir="/content/drive/MyDrive/LoRA/characters-webtoon/caronte-sdxl/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=0.0005 --unet_lr=0.0005 --network_dim=64 --output_name="caronte-sdxl" --lr_scheduler_num_cycles="5" --no_half_vae --learning_rate="0.0005" --lr_scheduler="cosine" --lr_warmup_steps="0" --train_batch_size="4" --max_train_steps="638" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --caption_extension=".txt" --cache_latents --cache_latents_to_disk --optimizer_type="Adafactor" --max_data_loader_n_workers="0" --keep_tokens="1" --bucket_reso_steps=64 --min_snr_gamma=5 --mem_eff_attn --gradient_checkpointing --full_fp16 --xformers --bucket_no_upscale --noise_offset=0.0375 --lowram --network_train_unet_only --cache_text_encoder_outputs --sample_sampler=euler_a --sample_prompts="/content/drive/MyDrive/LoRA/characters/death-skull-caronte/model/sample/prompt.txt" --sample_every_n_steps="200"
> 
> i still had memory left and the lora was amazing. i love your videos.
> 
> (off-topic question: did you invest in ads for your udemy course? it was a great success. i'm finishing editing one on 'creating webtoons with a.i' and i keep wondering if the platform is capable of showing my course to other people or if i need to be 100% in charge of the marketing)....
> 
> (sorry for the bad English, Deepl)

thank you so much

i spent 0$ on udemy ads. it is all organic. but the revenue is very low. like 3$ per student :)

**Comment by loboere** [comment]
Can you give me the links to train Lora in SDXL with Colab Free or Kaggle, please?

**Comment by FurkanGozukara** [comment]
> Can you give me the links to train Lora in SDXL with Colab Free or Kaggle, please?

i have up to date tutorial and kaggle notebook

[**How To Do Stable Diffusion XL (SDXL) DreamBooth Training For Free - Utilizing Kaggle - Easy Tutorial**](https://youtu.be/16-b1AjvyBE)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/JU3U2Kk6IdVxx1-hfNkrA.png)](https://youtu.be/16-b1AjvyBE)

**Comment by loboere** [comment]
Why can't colab do the same if it has the same gpu as kaggle, is it because of the ram or something else?

**Comment by FurkanGozukara** [comment]
> Why can't colab do the same if it has the same gpu as kaggle, is it because of the ram or something else?

Kaggle gives 29 GB RAM right now. google colab didnt do it

**Comment by loboere** [comment]
ok, kaggle is a bit uncomfortable, they should improve their interface like colab's

**Comment by FurkanGozukara** [comment]
> ok, kaggle is a bit uncomfortable, they should improve their interface like colab's

true but i am providing full instructions and tutorials to my supporters and help
