### ISSUE TITLE
Ubuntu 22.04 and bitsandbytes.

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1445]
systemwide I do not have this error but activate your venv and suddenly I get this error (iow, I can't train at all).

RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
        
doing the python -m bitsandbytes while in the venv brings

python -m bitsandbytes
False

===================================BUG REPORT===================================
/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/cuda-12.2/lib64: did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/1277,unix/ga-101'), PosixPath('local/ga-101')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/71bf328c_4ec3_491d_a201_5e480be82701')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/mnt/WIN_D/kohya_ss2-dev2_linux/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
        
If I run that command outside of your venv (system wide iow) no issues.

Here is the report globally (system wide):

python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.2/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/ga/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/ga/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/ga/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/ga/.local/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++++++++ /usr/local/cuda-12.2/lib64 CUDA PATHS +++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.9']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

**Comment by DarkAlchy** [comment]
Got it, and it was because the versions you are installing are so old now.

--pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
xformers==0.0.21 bitsandbytes==0.41.1
tensorboard==2.14.0 tensorflow==2.13.0
#torch==2.0.1+cu118 torchvision==0.15.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 # no_verify leave this to specify not checking this a verification stage
#xformers==0.0.20 bitsandbytes==0.41.1
#tensorboard==2.12.3 tensorflow==2.12.0
-r requirements.txt

**Comment by Dannypeja** [comment]
The included requirements are for cuda18. 
If you use cuda 12.2 set requirements to this:

requirements_linux.txt
```
torch torchvision # no_verify leave this to specify not checking this a verification stage
scipy
xformers==0.0.21 bitsandbytes==0.41.1
tensorboard==2.14.1 tensorflow==2.14.0
-r requirements.txt

```

**Comment by RudraPS97** [comment]
I have cuda 12.3
I used the settings you mentioned but now I get this error,
```
`decoderF` is not supported because:
xFormers wasn't build with CUDA support
attn_bias type is <class 'NoneType'>
operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
xFormers wasn't build with CUDA support
dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
xFormers wasn't build with CUDA support
dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
operator wasn't built - see `python -m xformers.info` for more info
triton is not available
Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
xFormers wasn't build with CUDA support
operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
max(query.shape[-1] != value.shape[-1]) > 32
xFormers wasn't build with CUDA support
operator wasn't built - see `python -m xformers.info` for more info
unsupported embed per head: 40
```

Is there any specific requirement for cuda 12.3 that I can use?
