### ISSUE TITLE
【Help me】dreambooth Lora tab does not exist

### ISSUE THREAD

**Issue by silquey** [bmaltais/kohya_ss#1447]
![Help me](https://github.com/bmaltais/kohya_ss/assets/143247762/ebcc4ec7-7da0-4a27-8a0b-b8793bbf6d64)

I installed kohya_ss GUI following the instructions.
Why is it not labeled dreambooth Lora?

**Comment by silquey** [comment]
Python 3.10.9
Windows 11 Home 64bit
Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz   2.90 GHz
RAM 16GB
RTX2070 super

**Comment by bmaltais** [comment]
Correct. It is called LoRA now as Dreambooth LoRA was incorrect...

**Comment by silquey** [comment]
To bmaltais san
> Correct. It is called LoRA now as Dreambooth LoRA was incorrect...

So you are saying that my information was out of date?
Arigato for letting me know. I will try it.
