### ISSUE TITLE
Where are the buttons at to create the dataset for FT?

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1448]
![image](https://github.com/bmaltais/kohya_ss/assets/10561690/29925cce-717d-441e-8500-221df1628f47)

**Comment by DarkAlchy** [comment]
Guess this native FT method I am confused about since I can't even find any really good documentation to set everything up right.  DB/LoRA, but FT is still not many doing it enough to make enough guides a Google search will bring one up.

**Comment by MZalfred** [comment]
I'm sorry are you trying to create a dataset for FT (FastText) typically involves preparing your data in a specific format and then using the FastText command-line tool  IF YES hit me
OR review the official FastText documentation. Even if it doesn't cover your specific integration with DB/LoRA, it will provide valuable insights into how FastText works and its command-line options
