### ISSUE TITLE
Issue with extracting lora

### ISSUE THREAD

**Issue by ShaheerAhmedAwan** [bmaltais/kohya_ss#1450]
Hi everyone
I've generated a checkpoint using Dreambooth in 'automatic1111,' and now, while attempting to extract lora with Khoya SS, I'm encountering this error.

Kindly help me out with this
Image
or any alternativ way to extract lora from checkpoint

![Screenshot 2023-08-27 230252](https://github.com/bmaltais/kohya_ss/assets/46984472/739dca83-b209-4f99-b644-dd4407a896cf)

**Comment by zengjie617789** [comment]
rename the key in weights manually.
