### ISSUE TITLE
Tags getting ignored while training

### ISSUE THREAD

**Issue by DerHamm3r** [bmaltais/kohya_ss#1467]
Hey, I have started to encounter a problem since yesterday. When trying to train a LoRA (1.5) it appears that the tags prepared in the .txt files are no longer getting trained in. I am still running on an older version and have not updated in a while, and made no changes to my presets, but when I train something it appears that it has not worked properly, and if I use a1111 additional networks to look into the training data it does not show any tags, it only shows whatever I called the folders. I am not sure why but my only assumption is that some other library or program it relies on in the background got updated and that changed? Maybe someone else encountered a similar issue. There are no exceptions or errors during training and everything appears to be working normally.

**Comment by ZikViM** [comment]
same trouble with tags,lora didnt get any captured tags, how did u solve this ussue
