### ISSUE TITLE
MacOS Warning: LD_LIBRARY_PATH environment variable is not set.

### ISSUE THREAD

**Issue by LIKE2000-ART** [bmaltais/kohya_ss#1471]
I am using Mac Studio 2022 (M1 MAX 32GB RAM) with system version 13.5.1 and SIP disabled. I created a Python 3.10 environment in Conda.Here is my configuration file

```
command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false
```

When I granted permission and ran setup.sh, I received the following report:

```
./setup.sh -v
Installing Python 3.10 if not found.
Python 3.10 found!
Installing Python-TK 3.10 if not found.
Python Tkinter 3.10 found!
Skipping git operations.
Switching to virtual Python environment.
10:14:30-986295 INFO     Installing python dependencies. This could take a few  
                         minutes as it downloads files.                         
10:14:30-988026 INFO     If this operation ever runs too long, you can rerun    
                         this script in verbose mode to check.                  
10:14:30-988530 INFO     Version: v21.8.8                                       
                                                                                
10:14:30-988945 INFO     Python 3.10.12 on Darwin                               
10:14:30-989582 INFO     Installing modules from requirements_macos_arm64.txt...
10:14:30-990311 INFO     Installing package: torch==2.0.0 torchvision==0.15.1 -f
                         https://download.pytorch.org/whl/cpu/torch_stable.html 
10:14:35-312804 INFO     Installing modules from requirements.txt...            
10:14:35-316451 INFO     Installing package: -e .                               
10:14:38-364662 INFO     Configuring accelerate...                              
10:14:38-365606 WARNING  Could not automatically configure accelerate. Please   
                         manually configure accelerate with the option in the   
                         menu or with: accelerate config.                       
Exiting Python virtual environment.
Source accelerate config location: /Users/yuanyi/kohya_ss//config_files/accelerate/default_config.yaml
Target accelerate config location: /Users/yuanyi/accelerate/default_config.yaml
Copying accelerate config file to: /Users/yuanyi/.cache/huggingface/accelerate/default_config.yaml
Setup finished! Run ./gui.sh to start.
```

When I grant permission and run gui.sh, I receive a warning:

```
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.
 
If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/

```

This warning does not seem to affect the operation of webUI, and I have not yet tested any specific impact on training.
I would like to know what impact this has on me and how to eliminate this warning. Thank

**Comment by kasha776** [comment]
I have the same issue.

**Comment by MZalfred** [comment]
To eliminate warning, you have already set the LD_LIBRARY_PATH environment variable using command:export LD_LIBRARY_PATH=/usr/lib/wsl/lib/
The warning about the LD_LIBRARY_PATH environment variable not being set might not always have an immediate noticeable impact on the operation of the web UI or other software. However, it's a good practice to address it because it can potentially lead to issues in the future, especially when running certain programs or software that depend on specific shared libraries

**Comment by rpfile** [comment]
well, WSL is a windows thing, so setting it to /usr/lib/wsl/lib does not make sense on the mac. it's not clear what LD_LIBRARY_PATH should be pointing to in the kohya_ss environment.

**Comment by harumeow88** [comment]
I have the same issue. T T

**Comment by rpfile** [comment]
i don't think this has any effect, have been running kohya_ss for a week with no apparent problems. python probably does not need to load any dylibs outside of the virtual environment...

**Comment by MZalfred** [comment]
> well, WSL is a windows thing, so setting it to /usr/lib/wsl/lib does not make sense on the mac. it's not clear what LD_LIBRARY_PATH should be pointing to in the kohya_ss environment.
 You are correct,   In the context of your macOS environment and the `kohya_ss` setup,  no need to set `LD_LIBRARY_PATH` manually unless explicitly instructed by maintainers. Setting it incorrectly can cause issues.
Remove the incorrect LD_LIBRARY_PATH and
unset LD_LIBRARY_PATH
