### ISSUE TITLE
the training becomes be slow

### ISSUE THREAD

**Issue by g558800** [bmaltais/kohya_ss#1477]
Why is the new version of kohya__ss training so slow, it used to be fast.

![image](https://github.com/bmaltais/kohya_ss/assets/119348639/0fe7c197-f5c3-4bf8-bddc-42a8e76b30e9)

**Comment by g558800** [comment]
> I just updated my version and it has indeed become insanely slow, I'm at 65s/it now, usually I have around 1it/s. It was working fine before I upstaed

I wonder what version started the slowdown?

**Comment by zadokov** [comment]
For me it starts at around 1.8 s/it and as the training continues it grows by ~2 seconds per iteration every ~1000 steps.
All this started with the latest v21.8.9.

**Comment by Asaghon** [comment]
Just an update, I reinstalled a bunch of stuff and my speed is the same as before now, going up to 1.4 it/s. Not exactly sure what the issue was

**Comment by bosbrand** [comment]
@zadokov I have the same, it gradually slows down, starts at 4.2s/it avg, now in the third epoch I'm down to 12s/it avg.

**Comment by zuGROB** [comment]
Same problems, i would recommed uncheck memory efficient attention and turn off hardware acceleration in Windows graphic parameters

**Comment by 2blackbar** [comment]
What was the last date of this reposotory working good with sdxl training ? This repo is getting broken 80% of the time but sometimes there is one good working version from one particular day, which one is it ?

**Comment by zadokov** [comment]
> What was the last date of this reposotory working good with sdxl training ? This repo is getting broken 80% of the time but sometimes there is one good working version from one particular day, which one is it ? LAtely dev branch was merged which probably messed everything up, im getting this one now which is the first merge of sdxl trianing code into this repo: https://github.com/bmaltais/kohya_ss/tree/4449374507102bd459c4f2e0d75d115abb5b0305

Previous version released was good.

**Comment by 2blackbar** [comment]
What do you mean by that ? i want sdxl version and this is the first one that has it so i dont need previous one without sdxl cause i already had it.

**Comment by zadokov** [comment]
> What do you mean by that ? i want sdxl version and this is the first one that has it so i dont need previous one without sdxl cause i already had it.

Previous release was v21.8.7.

https://github.com/bmaltais/kohya_ss/releases/tag/v21.8.7
