### ISSUE TITLE
Scheduler for finetuning SDXL

### ISSUE THREAD

**Issue by fiona-lxd** [bmaltais/kohya_ss#1490]
In sdxl_train.py it writes "noise_scheduler = DDPMScheduler(
        beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", num_train_timesteps=1000, clip_sample=False
    )" . However, the scheduler for the official SDXL is EulerDiscreteScheduler not DDPM. Can someone provide any thoughts on this? Will this matter for training a good SDXL?

**Comment by mio-nyan** [comment]
The original script is from https://github.com/kohya-ss/sd-scripts repo and since I have the same question, I just opened an issue there.
