### ISSUE TITLE
3060 / 12 gb epically slow LoRA training

### ISSUE THREAD

**Issue by elphamale** [bmaltais/kohya_ss#1504]
Hello,
I have 3060 with 12 gb Vram and 64 gbs RAM and I'm trying to train a lora out of 20 images sized 1megapixel. 
The process loads VRAM to close to 100% and RAM close to 70%. GPU utilization is close to max and CPU is idling. 
Aaaaand I get this per iteration time:
![image](https://github.com/bmaltais/kohya_ss/assets/120310966/a04a7a0c-1962-4c5a-a3c2-c6ca61e5aaa9)
I must be doing something SERIOUSLY wrong or what the hell?

I tried reducing the number of images but the lowest I got was still around 6 mins per iteration.

Here's the screencap of the settings:
![image](https://github.com/bmaltais/kohya_ss/assets/120310966/36164712-cc83-4c20-98d1-4ae592c64279)

I am willing to provide any info needed. Please advise.

**Comment by scrumpyman** [comment]
1024 resolution and batch size 10 requires an insane amount of vram, and that's not accounting sdxl, which probably requires more too. 12gb vram can barely handle 768px batch size 2 on sd 1.5. Try batch size 1, but even then it might not work.

**Comment by cerarslan** [comment]
> Hello, I have 3060 with 12 gb Vram and 64 gbs RAM and I'm trying to train a lora out of 20 images sized 1megapixel. The process loads VRAM to close to 100% and RAM close to 70%. GPU utilization is close to max and CPU is idling. Aaaaand I get this per iteration time: ![image](https://user-images.githubusercontent.com/120310966/266769396-a04a7a0c-1962-4c5a-a3c2-c6ca61e5aaa9.png) I must be doing something SERIOUSLY wrong or what the hell?
> 
> I tried reducing the number of images but the lowest I got was still around 6 mins per iteration.
> 
> Here's the screencap of the settings: ![image](https://user-images.githubusercontent.com/120310966/266769619-36164712-cc83-4c20-98d1-4ae592c64279.png)
> 
> I am willing to provide any info needed. Please advise.

Same for me. 3000 steps took 19hours and ∼21s/it. It wasn't like this before.

**Comment by elphamale** [comment]
I applied a preset (can't say which one right now because I'm not at home)
from the selection in webui, selected LoCON instead of Standard and
specified batch of one.
That got me to around 5.5 s/it, which is far less scary than 6 or 40 mins
per iteration.

I can provide the training command I got later if needed.

**Comment by cerarslan** [comment]
I just figure out to solve my problem. I only use standart lora. When I clicked bf16 experimental and it solved my issue.
