### ISSUE TITLE
SDXL LORA Training with Errors 'load tokenizers models'

### ISSUE THREAD

**Issue by DanielXu123** [bmaltais/kohya_ss#1509]
Solution:
1.Download all those files from [https://huggingface.co/laion/CLIP-ViT-bigG-14-laion2B-39B-b160k/tree/main](url) and put them 
into a specific folder 
2. Modify the TOKENIZER2_PATH to the full path of the specific folder

**Comment by DanielXu123** [comment]
Would anyone share the  folders directories under **~/.cache/huggingface/hub/models--laion--CLIP-ViT-bigG-14-laion2B-39B-b160k/**

And May I ask what files should I download and which specific folder should I put those files in

**Comment by kenny-sparkle** [comment]
Excuse me, how to Modify the TOKENIZER2_PATH?
I use docker compose command to run the gui and I can't find a way to set TOKENIZER2_PATH.
