### ISSUE TITLE
Network Rank, Network Alpha - Please explain in simple words if anyone knows

### ISSUE THREAD

**Issue by nikolaiusa** [bmaltais/kohya_ss#1511]
Can anyone explain to me in simple words with a simple example what these parameters mean when training lora?

**Comment by nikolaiusa** [comment]
I did 1000 experiments and 1000 LORA but I don’t fully understand...

**Comment by iqddd** [comment]
I don't pretend that the information is accurate. The way I understand it: if Network Rank = Network Alpha, there may be a case where the network weights get "zeroed out". "Zeroed weights" can no longer participate in training and, in fact, hang "dead" weight. Consequently, Lora becomes "weaker" and contains less information. To prevent this, set Network Alpha = Network Rank / N (N > 1). The larger N is, the less probability of weights zeroing.

**Comment by Davikar** [comment]
This section explains it pretty well,
https://rentry.org/59xed3#network-alpha
