### ISSUE TITLE
Did bmaltais pass away?

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1513]
I haven't seen him in here for a while and wondering if something happened to him, or what is going on?

Concerned.

**Comment by Davikar** [comment]
Last update was 4 days ago in the dev2 branch. Which might seem like an eternity in AI time, but in real world time not so much.

**Comment by DarkAlchy** [comment]
At least he is alive with all the Ukraine and Russia nonsense happening, just shirking his duty to clear all these tickets out and address them properly.

**Comment by 2blackbar** [comment]
Mayobe someone would branch out from this but i think this repo is already too messed up to fix, or maybe it just needs proper presets

**Comment by DarkAlchy** [comment]
Well, he was far too much of a beta passive male and allowed this to happen.  Most of the tickets he has no control over and people are too stupid to realize it is simply a gui front end and Kohya is the backend.  I bet if you got rid of those alone, the ticket count would dwindle to almost nothing.

This place should be for real gui tickets as the one I posted where it doesn't save the vae I use in the lora tab but does if I use the Dreambooth tab.  Now that is a gui related issue that is an easy fix for sure.

**Comment by bmaltais** [comment]
Don't worry. I have just been super busy with the paid job and it is taking 100% of my attention at the moment.

I will push a small update today but nothing significant given kohya has not updated his code recently... Talking of that... let me check if this is still the case... yup, no update in the last 3 weeks.

Hope I can find more time to work with SD... but at the moment super busy at work.

**Comment by DarkAlchy** [comment]
With all the crazy stuff happening in the world one never knows.  Glad you are alright.

**Comment by bmaltais** [comment]
Watched a Netflix series I had not seen yet and it was pretty good. I think I might try to create a series of LoRA from it. Ragnarock.

**Comment by DarkAlchy** [comment]
I have heard of that one but never watched it though it looks good.  When you say a LoRA you mean a character LoRA, right?

**Comment by bmaltais** [comment]
> I have heard of that one but never watched it though it looks good. When you say a LoRA you mean a character LoRA, right?

Yes. I am not super pleased with the lora... but I stumbled on a new "no LoRA" solution called IPAdapter. I tested it last night and combining the not perfect LoRA + IPAdapter produce amazing results.

**Comment by DarkAlchy** [comment]
Yes, and it sort of saddens me as I am seeing a trend of no longer needing to train.
