### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by ghainey** [bmaltais/kohya_ss#1515]
As usual, I've trained the models in SD 2.1 Dreambooth on Windows 11 RTX 4070 12Gb. After installing the CUDA Toolkit, the training became very slow. Even after uninstalling Toolkit, Kohya somehow finds it (nVidia toolkit detected). I've tried various combinations of enabling and disabling: Triton, cudann, bitsandbytes-windows, deletion of CUDA's environment variables. I even reinstalled different versions all of nVidia programs and GPU drivers but nothing helps.
![image](https://github.com/bmaltais/kohya_ss/assets/145015999/b8168f94-9df8-4c68-9304-69a0f6ed829b)
![image](https://github.com/bmaltais/kohya_ss/assets/145015999/4c957eff-f646-4edb-9de1-4a14733c2a3a)

**Comment by zuGROB** [comment]
Same problem. I was using release from about half a year ago and now it's like 50% slower on my 3060 w/12gigs

**Comment by zuGROB** [comment]
> Same problem. I was using release from about half a year ago and now it's like 50% slower on my 3060 w/12gigs

Update: if you check "Memory efficient attention" it hella slows your trauning, like, A LOT. So, that can be a problem too. Also, in Windows graphics settings you may disable GPU hardware acceleration, it can help too, especially, as someone saind, on Win11

**Comment by ghainey** [comment]
> > Same problem. I was using release from about half a year ago and now it's like 50% slower on my 3060 w/12gigs
> 
> Update: if you check "Memory efficient attention" it hella slows your trauning, like, A LOT. So, that can be a problem too. Also, in Windows graphics settings you may disable GPU hardware acceleration, it can help too, especially, as someone saind, on Win11

Thank you for your reply! Unfortunately it doesn't solve my problem as I already unchecked "Memory efficient attention" and Win11 acceleration.

Perhaps this screenshot can clarify the situation.
![image](https://github.com/bmaltais/kohya_ss/assets/145015999/68f8e20f-34ed-4edc-84b0-a323354d6316)

**Comment by iqddd** [comment]
Had a similar situation on free Google Colab ( before they started blocking for running a training on the free version).
The speed drop was almost exactly 2 times. It resolved itself. :)
I'd check the versions of the python libraries. The newest doesn't mean the best. Try rolling back libraries to the versions specified in requirements files.

**Comment by 2blackbar** [comment]
I have this issue locally, someone really, i mean REALLY dropped the ball lately with this repo, now my training takes 24 hours suddenly when it took 24 minutes, what the hell ?

**Comment by etha302** [comment]
> Its not the same we have here 60!!!! times slower training , I have this issue locally, someone really, i mean REALLY dropped the ball lately with this repo, now my training takes 24 hours on 3090 suddenly when it took 24 minutes, what the hell ? This repository is like this since at least half year, most versions dont work and you can find one version per 2 months that works properly and you can use only this one but which one is it now ? Ok no luck with first version taht introduced SDXL, is dev of thsi repo going to address it ? | 4/5200 [01:32<33:27:40, 23.18s/it, loss=0.164]
> 
> This is laughable on 3090 Do we have to find some secret specific settings to UnLoCk normal training dev ? Seriously ? Already wasted 5 hours on this... still no change , its like a bad prank

3090 is however still faster than 4090, and no answers whether is nvidia or is it the script i don’t know anymore. It makes it so hard to train sdxl at this point, it is pointless owning 4090 for this. Or basically any 40 series cards

**Comment by 2blackbar** [comment]
this repo is off, i dont see any complaints on official kohya scripts repo where people have slow speeds for sdxl but i want gui so maybe i should just write one with bing ai cause i already did that for a lot of pyuthon code without guis

**Comment by ghainey** [comment]
Also the Device Manager and GeForce Experience are both trying to install the same version of the video driver. For these programs only their own installment matters.

**Comment by yamasoo** [comment]
4070 regresses driver from latest 537.34 to 531.79 in May and train speeds  back to full speed .... What the hell?

**Comment by quantumbalance** [comment]
Im having the same issue but im an idiot. can someone please hurry and fix this?

**Comment by JAssertz** [comment]
go to [https://www.nvidia.com/en-us/geforce/drivers](https://www.nvidia.com/en-us/geforce/drivers) select your gpu and downgrade to version 531 and that will fix your issue I had a new ver b4 and had like 6-12 s/it now its down to like ~1.2-.09s/it

**Comment by ghainey** [comment]
> go to https://www.nvidia.com/en-us/geforce/drivers select your gpu and downgrade to version 531 and that will fix your issue I had a new ver b4 and had like 6-12 s/it now its down to like ~1.2-.09s/it

This version makes this error:
│ kohya_ss\venv\lib\site-packages\transformers\optimization.py:697 in step                         │
│                                                                                                  │
│   694 │   │   │   │   lr = self._get_lr(group, state)                                            │
│   695 │   │   │   │                                                                              │
│   696 │   │   │   │   beta2t = 1.0 - math.pow(state["step"], group["decay_rate"])                │
│ ❱ 697 │   │   │   │   update = (grad**2) + group["eps"][0]                                       │
│   698 │   │   │   │   if factored:                                                               │
│   699 │   │   │   │   │   exp_avg_sq_row = state["exp_avg_sq_row"]                               │
│   700 │   │   │   │   │   exp_avg_sq_col = state["exp_avg_sq_col"]

OutOfMemoryError: CUDA out of memory. Tried to allocate 194.00 MiB (GPU 0; 11.99 GiB total capacity; 10.97 GiB already
allocated; 0 bytes free; 11.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ghainey** [comment]
GeForce Game Ready 545.92 solved the problem

**Comment by etha302** [comment]
Actually this driver did nothing but slow down training for me. 1.8s/it is not fast for me, as i got 1.35s/it with previous driver on 4090
