### ISSUE TITLE
"The following values were not passed to", but it was

### ISSUE THREAD

**Issue by DevArqSangoi** [bmaltais/kohya_ss#1518]
But the value was passed, why this error?

![ué](https://github.com/bmaltais/kohya_ss/assets/125471877/cf520288-b021-45a2-acba-f831f132f08f)

**Comment by iqddd** [comment]
Try manually set FP16. Run 'accelerate config'.
Also try BF16.

**Comment by DevArqSangoi** [comment]
Done, thanks!
