### ISSUE TITLE
Linux Ubuntu: Can't find libcudart.so "...directories listed in your path were found to be non-existent: ...lib64"

### ISSUE THREAD

**Issue by michaelbob23** [bmaltais/kohya_ss#1520]
Linux Ubuntu RTX 2090. This is happening when I try to Lora anything.

-     I have tried installing the Nvidia developer thingy several times w/o the drivers as advised
-     I am running a clean latest Ubuntu install
-     I have tried copying and pasting the libcudart files into every folder that is called lib64
-     I have spent weeks looking through Google results with no luck
-     How is it that I seem to be the only one with this problem?
-     Thank you for any help!

![Screenshot from 2023-09-15 17-05-22](https://github.com/bmaltais/kohya_ss/assets/145167569/7740b091-ac8b-430e-bfa3-6e2509c015e9)

![Screenshot from 2023-09-15 17-58-29](https://github.com/bmaltais/kohya_ss/assets/145167569/a8946d77-fa74-4a9f-8b04-c90f1c7850c4)

**Comment by iqddd** [comment]
1. Uninstall the NVidia drivers. `sudo apt-get purge nvidia*`
2. Install the kernel header files. `sudo apt-get install linux-headers-$(uname -r)`
3. Download the installation package from the NVidia website. Install the driver. When asked about DKMS, select yes.
4. Install the CUDA toolkit following this guide: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#network-repo-installation-for-ubuntu
5. Check this one out, too. https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#faq3

**Comment by michaelbob23** [comment]
Hi, thanks for helping me out!

> 4. Install the CUDA toolkit following this guide: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#network-repo-installation-for-ubuntu

I can't get passed this step: sudo dpkg -i cuda-repo-<distro>_<version>_<architecture>.deb

How am I supposed to enter it?

Like this...

sudo dpkg -i-repo-<Ubuntu>_<22.04>_<x86_64>.deb    ???

or...

sudo dpkg -i-repo-Ubuntu_22.04_x86_64.deb    ???

or...

sudo dpkg -i-repo-Ubuntu_2204_x86_64.deb    ???

I have tried like ten different ways and keep getting an error about a directory.

**Comment by iqddd** [comment]
Skip "3.10.2. Local Repo Installation for Ubuntu"
Do "3.10.3. Network Repo Installation for Ubuntu"

**Comment by michaelbob23** [comment]
> Skip "3.10.2. Local Repo Installation for Ubuntu" Do "3.10.3. Network Repo Installation for Ubuntu"

I don't understand the very first line..

sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/$distro/$arch/cuda-$distro.repo

where $distro/$arch should be replaced by one of the following:

    rhel7/x86_64
    rhel7/ppc64le

Is it supposed to be this? ...

sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhe17.repo

or...

sudo yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/$distro.repo

??? Neither worked. I get Sudo: yum-config-manager: command not found

**Comment by michaelbob23** [comment]
> Skip "3.10.2. Local Repo Installation for Ubuntu" Do "3.10.3. Network Repo Installation for Ubuntu"

First step fails...

wget https://developer.download.nvidia.com/compute/cuda/repos/$distro/$arch/cuda-keyring_1.1-1_all.deb

Got...

404 Not Found
2023-09-16 17:35:52 ERROR 404: Not Found

**Comment by iqddd** [comment]
> where $distro/$arch should be replaced by one of the following:
For example, if you have Ubuntu 22.04 x64, command would look like:
https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb

**Comment by michaelbob23** [comment]
> > where $distro/$arch should be replaced by one of the following:
> 
> For example, if you have Ubuntu 22.04 x64, command would look like: `wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb`

Thank you. I ju**st finished that and tried to Lora and got the exact same error.** I went through the first few steps of the "Post Installation Actions" ? I am trying to work on those now. Very confusing. I think I am up to Persistence Daemon?

**Comment by iqddd** [comment]
```
sudo apt-get update
sudo apt-get install cuda
sudo reboot
```
Did you follow these commands? Did it install without errors?

`export PATH=/usr/local/cuda-x.x/bin${PATH:+:${PATH}}`
cuda-x.x replace to your version.

```
export LD_LIBRARY_PATH=/usr/local/cuda-x.x/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions
This link has everything in detail.

**Comment by michaelbob23** [comment]
Thank you for everything. Yes I followed those commands. No errors. Did the PATH thing with my Cuda version (12.1). Just tried to Lora and got the exact same error.

**Comment by iqddd** [comment]
¯\_(ツ)_/¯
