### ISSUE TITLE
Which checkbox should i check when trying to train a lora with unet only?

### ISSUE THREAD

**Issue by msqiqi10** [bmaltais/kohya_ss#1528]
I'm trying to train a lora with sdxl model and my GPU is 2080ti 11gb.
I have to use the cmd
`./sdxl_train_network.py --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048 --pretrained_model_name_or_path=/home/sd-all/stable-diffusion-webui/models/Stable-diffusion/leosamsHelloworldSDXLModel_helloworldSDXL10.safetensors --train_data_dir=/home/lora --resolution=640,640 --output_dir=/home/lora/ --network_alpha=8 --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=8 --output_name=last --lr_scheduler_num_cycles=10 --cache_text_encoder_outputs --no_half_vae --learning_rate=0.0001 --lr_scheduler=cosine --lr_warmup_steps=140 --train_batch_size=2 --max_train_steps=1400 --save_every_n_epochs=1 --mixed_precision=fp16 --save_precision=fp16 --cache_latents --cache_latents_to_disk --optimizer_type=AdamW8bit --max_data_loader_n_workers=0 --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0 --network_train_unet_only`
to train lora because I couldn't find corresponding checkbox of --network_train_unet_only in the lora training GUI. 
So which checkbox should i check when trying to train a lora with unet only?

**Comment by zadokov** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/98109474/42c21574-30c4-42d0-8fdc-1c5eaf64dce8)
