### ISSUE TITLE
setup.bat instantly closes after running

### ISSUE THREAD

**Issue by Hugs288** [bmaltais/kohya_ss#1535]
it used to be fine, but this issue started happening after i installed cuda11.8 framework and installed new drivers
a1111 runs fine.
if i run it as administrator, i get:
Warning: Python version 3.10.9 is recommended.
Creating venv...
python: can't open file 'C:\\Windows\\System32\\setup\\check_local_modules.py': [Errno 2] No such file or directory
C:\Users\Hugs\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Windows\\System32\\setup\\setup_windows.py': [Errno 2] No such file or directory

its checking for the files in system32 for some reason??

i think might be wrong with my python install but im not sure, and ive already tried reinstalling it.

i managed to get around this stupid error by just running the setup.bat commands in a cmd of the correct directory, but its still very weird.

**Comment by zsfwz** [comment]
same question, the first step can be carried out, but suddenly it quickly turns into a black screen.

**Comment by bmaltais** [comment]
Try running it from a cmd windows instead of running the .bat file by clicking on it. It should state what the issue is in that windows as it will not close upon error.

**Comment by Hugs288** [comment]
i fixed my issue with a windows repair install, still not sure what caused it though
