### ISSUE TITLE
"Stop text encoder training not supported"

### ISSUE THREAD

**Issue by fanasthesia** [bmaltais/kohya_ss#1537]
Setting the stop text encoder training to anything higher than 0 ignores the output and turns it off. I am using the dev2 branch but it did the same on master branch. 
![image](https://github.com/bmaltais/kohya_ss/assets/141881072/9d35c983-6af8-426c-8e16-90fd5c722082)

**Comment by bmaltais** [comment]
kohya need to add support for it in his code before I can support. SOmeone already created a PR for this and hopefully will bring it to kohya so he can merge and then I can support it in the GUI.

**Comment by zethfoxster** [comment]
if someone manually adds the pull request he made in the koyha git...it still wouldnt work in your webui?

**Comment by zengjie617789** [comment]
still not supported in April 8

**Comment by bmaltais** [comment]
When John’s add support in his sd-scripts I will be able to provide a UI for it.

**Comment by DarkAlchy** [comment]
Seems it doesn't even work in dreambooth, and I swear I thought it did in it before.  Not your gui stopping it it is the scripts

![image](https://github.com/bmaltais/kohya_ss/assets/10561690/da462809-cf9c-4d89-866d-b69650ed9333)
