### ISSUE TITLE
During training, the graphics card is sometimes fully loaded and sometimes only half full. Is this a normal phenomenon? RTX 2080 TI 22G is used

### ISSUE THREAD

**Issue by AlexanderDash** [bmaltais/kohya_ss#1538]

**Comment by AlexanderDash** [comment]
Trained for XL Lora

**Comment by bmaltais** [comment]
This can depend on other programs using the card. Depending on the training config more or less VRAM will be consumed also... Training rarelly fully utilise the full VRAM.

**Comment by sammcj** [comment]
It really depends on what settings you've configured, for example

- What is your network rank set to? (e.g. 256, 384 etc...)
- Have you ticked 'Memory efficient attention' (uses less memory at the cost of quality I believe)?

etc...

On my 3090 I'm able to train SDXL with as little as 12GB, or use all 24GB~ of the cards vRAM depending on what settings I choose.
