### ISSUE TITLE
Error while trying to create directories for LoRA Training.

### ISSUE THREAD

**Issue by mrmeseeks23** [bmaltais/kohya_ss#1541]
OS: Linux/Ubuntu 22.04 on RunPod
GPU: NVIDIA A100 80 GB
Kohya Version: Latest git pull as of 9/23/2023 at 2000
Training runs if I manually create the directories.

this is a new error I have never run into before. Seems like it might be a simple fix.

it seems to add ‘\n’’ onto the end.

` ` `
00:13:30-542736 INFO     Copy /workspace/kohya_ss/dataset/forky_ukj_v1
                          to /workspace/kohya_ss/dataset/forky_ukj_v1/img/60_ukj character...
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/workspace/kohya_ss/library/dreambooth_folder_creation_gui.py", line 74, in dreambooth_folder_preparation
    shutil.copytree(util_training_images_dir_input, training_dir)
  File "/usr/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/workspace/kohya_ss/dataset/forky_ukj_v1\n'
` ` `

**Comment by CoraAI** [comment]
looks like I've been through the same problem ,sort of. And this is also new to me  


20:05:45-236597 INFO     Version: v22.3.0

20:05:45-239588 INFO     nVidia toolkit detected
20:06:09-986519 INFO     Torch 2.0.1+cu118
20:06:09-998938 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:06:09-999931 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
20:06:10-000924 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
20:06:10-002911 INFO     Verifying modules installation status from requirements.txt...
20:06:10-005891 WARNING  Package wrong version: huggingface-hub 0.19.4 required 0.15.1
20:06:10-006387 INFO     Installing package: huggingface-hub==0.15.1
20:06:41-170329 INFO     headless: False
20:06:41-180449 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
20:09:34-232106 INFO     Copy E:\Ai_program\00_training_data\1212\tagged\characters to
                         E:\Ai_program\00_training_data\1212\output\img/120_shadopupyct a piying style of ...
Traceback (most recent call last):
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Ai_program\kohya_ss\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "E:\Ai_program\kohya_ss\kohya_ss\library\dreambooth_folder_creation_gui.py", line 74, in dreambooth_folder_preparation
    shutil.copytree(util_training_images_dir_input, training_dir)
  File "C:\Ai_program\Python\Python310\lib\shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "C:\Ai_program\Python\Python310\lib\shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\2.jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\2.jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\2.jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\2.txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\2.txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\2.txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\200704_py_ynj_dntg.jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\200704_py_ynj_dntg.jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\200704_py_ynj_dntg.jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\200704_py_ynj_dntg.txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\200704_py_ynj_dntg.txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\200704_py_ynj_dntg.txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (1).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (1).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (1).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (1).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (1).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (1).txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (2).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (2).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (2).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (2).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (2).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (2).txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (3).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (3).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (3).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (3).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (3).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (3).txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (4).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (4).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (4).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (4).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (4).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (4).txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (5).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (5).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (5).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (5).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (5).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (5).txt'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (6).jpg', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (6).jpg', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (6).jpg'"), ('E:\\Ai_program\\00_training_data\\1212\\tagged\\characters\\heads (6).txt', 'E:\\Ai_program\\00_training_data\\1212\\output\\img/120_shadopupyct a piying style of \\heads (6).txt', "[Errno 2] No such file or directory: 'E:\\\\Ai_program\\\\00_training_data\\\\1212\\\\output\\\\img/120_shadopupyct a piying style of \\\\heads (6).txt'")]
