### ISSUE TITLE
Torch 2 Not Installing Due to Torch 1 Existing in Venv; Venv 1 deleted, Issue Remains Unresolved

### ISSUE THREAD

**Issue by CakeEaterLink** [bmaltais/kohya_ss#1545]
Hello, upon running the set-up menu for Khoya I select option #1 to install the gui, and then option #2 to install Torch 2. I then get the following message:

"Torch 1 is already installed in the venv. To install Torch 2 delete the venv and re-run setup.bat

Hit any key to acknowledge."

I've deleted the venv, as well as deleted khoya and then reinstalled it and I am still getting the same message, does anyone know how to fix this? Thankyou in advance for your help.

**Comment by bmaltais** [comment]
This is odd... I am pulling all support for torch 1 from the code for the next release... the current code in the dev2 branch should fix this issue... if you care to try it you can do:

```
git checkout dev2
git pull
```

Then run setup. To return to the main code branch do:

```
git checkoit master
git pull
```
