### ISSUE TITLE
RuntimeError : Error(s) in loading state_dict for AutoencoderKL: - When trying to extract lora from a base SD 1.5 Pruned

### ISSUE THREAD

**Issue by dugemkakek** [bmaltais/kohya_ss#1546]
**F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\Kohya\kohya_ss\networks\extract_lora_f │
│ rom_models.py:277 in <module>                                                                    │
│                                                                                                  │
│   274 │   parser = setup_parser()                                                                │
│   275 │                                                                                          │
│   276 │   args = parser.parse_args()                                                             │
│ ❱ 277 │   svd(args)                                                                              │
│   278                                                                                            │
│                                                                                                  │
│ F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\Kohya\kohya_ss\networks\extract_lora_f │
│ rom_models.py:54 in svd                                                                          │
│                                                                                                  │
│    51 │   │   text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpo   │
│    52 │   │   text_encoders_o = [text_encoder_o]                                                 │
│    53 │   │   print(f"loading tuned SD model : {args.model_tuned}")                              │
│ ❱  54 │   │   text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffusion_checkpo   │
│    55 │   │   text_encoders_t = [text_encoder_t]                                                 │
│    56 │   │   model_version = model_util.get_model_version_str_for_sd1_sd2(args.v2, args.v_par   │
│    57 │   else:                                                                                  │
│                                                                                                  │
│ F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\Kohya\kohya_ss\library\model_util.py:1 │
│ 008 in load_models_from_stable_diffusion_checkpoint                                              │
│                                                                                                  │
│   1005 │   converted_vae_checkpoint = convert_ldm_vae_checkpoint(state_dict, vae_config)         │
│   1006 │                                                                                         │
│   1007 │   vae = AutoencoderKL(**vae_config).to(device)                                          │
│ ❱ 1008 │   info = vae.load_state_dict(converted_vae_checkpoint)                                  │
│   1009 │   print("loading vae:", info)                                                           │
│   1010 │                                                                                         │
│   1011 │   # convert text_model                                                                  │
│                                                                                                  │
│ F:\Programs\Stable-Diffuser\stable-diffusion-webui-master\Kohya\kohya_ss\venv\lib\site-packages\ │
│ torch\nn\modules\module.py:2041 in load_state_dict                                               │
│                                                                                                  │
│   2038 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   2039 │   │                                                                                     │
│   2040 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 2041 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   2042 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   2043 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   2044                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight", "encoder.mid_block.attentions.0.to_q.bias",
"encoder.mid_block.attentions.0.to_k.weight", "encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight",
"encoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_q.weight", "decoder.mid_block.attentions.0.to_q.bias",
"decoder.mid_block.attentions.0.to_k.weight", "decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight",
"decoder.mid_block.attentions.0.to_v.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_to_k.bias", "encoder.mid_block.attentions.0.to_to_k.weight",
"encoder.mid_block.attentions.0.to_to_q.bias", "encoder.mid_block.attentions.0.to_to_q.weight", "encoder.mid_block.attentions.0.to_to_v.bias",
"encoder.mid_block.attentions.0.to_to_v.weight", "decoder.mid_block.attentions.0.to_to_k.bias", "decoder.mid_block.attentions.0.to_to_k.weight",
"decoder.mid_block.attentions.0.to_to_q.bias", "decoder.mid_block.attentions.0.to_to_q.weight", "decoder.mid_block.attentions.0.to_to_v.bias",
"decoder.mid_block.attentions.0.to_to_v.weight".`**

Hi i get this error when trying to extract a finetuned model tha was trained based on the same SD Model (SD V1.5 Pruned), this Error also comes in Dreambooth in Automatic1111 when trying to extract the lora. This Model was trained using Dreambooth in Automatic1111 since training in kohya is so slow (1+ S/it and dreambooth in Automatic1111 give me like 2,5it/s)

Things that ive tried =

- Installing A fresh Kohya.ss
- Deleting Venv and rebuilding
- Making a yaml for model
- googling

anyone have the same problem ?

**Comment by nayan-dhabarde** [comment]
I am facing the same problem, i have fine tuned realistic 4.0 using diffusers converted it to .ckpt

**Comment by G4RLK** [comment]
Having a similar problem no fix yet

**Comment by nayan-dhabarde** [comment]
@G4RLK I have observed the following:
realistic vision -> fine tuned model --  fails
base sd 1.5 -> fine tuned model -- works

**Comment by captainipxe** [comment]
i have the same problem

**Comment by papuSpartan** [comment]
Not entirely sure yet the downsides of doing this, but a solution for me was to run my model through https://github.com/arenasys/stable-diffusion-webui-model-toolkit. This gave a leaner (and much smaller) version which kohya didn't complain about parsing.

**Comment by LgnGithub** [comment]
> Not entirely sure yet the downsides of doing this, but a solution for me was to run my model through https://github.com/arenasys/stable-diffusion-webui-model-toolkit. This gave a leaner (and much smaller) version which kohya didn't complain about parsing.

It doesn't work. There is no "advaned" tab. Bugged extension

**Comment by ghub29** [comment]
It looks like at some point a duplicate "to_" is added to checkpoint keys.

Example fix/workaround:

In model_util.py, added correct_checkpoint_to_keys() function and added a call in conv_attn_to_linear()

`
def correct_checkpoint_to_keys(checkpoint):
    keys = list(checkpoint.keys())
    for key in keys:
        if ".to_to_" in key:
            newkey = key.replace(".to_to_", ".to_")
            checkpoint[newkey] = checkpoint[key]
            del checkpoint[key]
            logger.info("Replaced checkpoint key: " + key + " -> " + newkey)


def conv_attn_to_linear(checkpoint):
    correct_checkpoint_to_keys(checkpoint)
    keys = list(checkpoint.keys())
    attn_keys = ["query.weight", "key.weight", "value.weight"]
    for key in keys:
        if ".".join(key.split(".")[-2:]) in attn_keys:
            if checkpoint[key].ndim > 2:
                checkpoint[key] = checkpoint[key][:, :, 0, 0]
        elif "proj_attn.weight" in key:
            if checkpoint[key].ndim > 2:
                checkpoint[key] = checkpoint[key][:, :, 0]
`

**Comment by Miyamoto-Musashi-0315** [comment]
running khoya on colab and i have the same error
