### ISSUE TITLE
Resuming Lora training on a saved training state outputs the original state

### ISSUE THREAD

**Issue by Hirmuolio** [bmaltais/kohya_ss#1552]
Reproduction steps:

1. Train standard Lora. Enable saving of training state.
2. Use the saved training state to resume training.
3. The resumed training will output file identical to the training output in step 1.

I trained a lora for 50 epochs. The training state was saved. I resumed training from that training state.
The output on every epoch from the training that was resumed was identical to the 50 epoch output. I compared the file contents by hand and they seemed to be 100% identical (except for the metadata at the top which appeared to be in different order).
I used the gui https://github.com/bmaltais/kohya_ss

Settings used in training: [settings.txt](https://github.com/bmaltais/kohya_ss/files/12748222/settings.txt)

**Comment by yuxu915** [comment]
hi, @Hirmuolio , meet the same question, have you finally solve it? Would you like to share your solution? Thanks!
