### ISSUE TITLE
AssertionError: resolution is required / resolution（解像度）指定は必須です

### ISSUE THREAD

**Issue by abozahran** [bmaltais/kohya_ss#1558]
I git this error message althought same setting used successufuly to train sdxl dreambooth a week ago
all photos reolution is 1024*1024
and Max resolution in kohya is 1024*1024

prepare tokenizers
Using DreamBooth method.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\kohya_ss-21.8.9\sdxl_train.py:746 in <module>                                                 │
│                                                                                                  │
│   743 │   args = parser.parse_args()                                                             │
│   744 │   args = train_util.read_config_from_file(args, parser)                                  │
│   745 │                                                                                          │
│ ❱ 746 │   train(args)                                                                            │
│   747                                                                                            │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\sdxl_train.py:162 in train                                                    │
│                                                                                                  │
│   159 │   │   │   │   }                                                                          │
│   160 │   │                                                                                      │
│   161 │   │   blueprint = blueprint_generator.generate(user_config, args, tokenizer=[tokenizer   │
│ ❱ 162 │   │   train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.   │
│   163 │   else:                                                                                  │
│   164 │   │   train_dataset_group = train_util.load_arbitrary_dataset(args, [tokenizer1, token   │
│   165                                                                                            │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\library\config_util.py:430 in generate_dataset_group_by_blueprint             │
│                                                                                                  │
│   427 │     dataset_klass = FineTuningDataset                                                    │
│   428 │                                                                                          │
│   429 │   subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in d   │
│ ❱ 430 │   dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))           │
│   431 │   datasets.append(dataset)                                                               │
│   432                                                                                            │
│   433   # print info                                                                             │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\library\train_util.py:1314 in __init__                                        │
│                                                                                                  │
│   1311 │   ) -> None:                                                                            │
│   1312 │   │   super().__init__(tokenizer, max_token_length, resolution, debug_dataset)          │
│   1313 │   │                                                                                     │
│ ❱ 1314 │   │   assert resolution is not None, f"resolution is required / resolution（解像度）指  │
│   1315 │   │                                                                                     │
│   1316 │   │   self.batch_size = batch_size                                                      │
│   1317 │   │   self.size = min(self.width, self.height)  # 短いほう                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: resolution is required / resolution（解像度）指定は必須です
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\zahran\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main  │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\zahran\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code             │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main       │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command    │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ E:\kohya_ss-21.8.9\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher   │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['E:\\kohya_ss-21.8.9\\venv\\Scripts\\python.exe', './sdxl_train.py',

![image](https://github.com/bmaltais/kohya_ss/assets/107565623/81bb0bd8-5818-4ce0-a780-f4a707c360e7)

**Comment by abozahran** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/107565623/9668eff2-a856-402c-86bb-ae17d297b199)

**Comment by dayo6** [comment]
Hey I fixed this error by putting forwards slashes instead of backslashes.

**Comment by abozahran** [comment]
> Hey I fixed this error by putting forwards slashes instead of backslashes.

I`m sorry can you help me furthe to understand what should i do

![image](https://github.com/bmaltais/kohya_ss/assets/107565623/7f82d93c-9b6e-4ec8-a5fe-6c1b772cf609)

**Comment by dayo6** [comment]
In your folder parameters, put forward slashes "/" instead of "\".  Like "F:/DB/SDXL/SALOMAV1/IMG/" instead of "F:\DB\SDXL\SALOMAV1\IMG\", I hope it helps.

**Comment by abozahran** [comment]
> In your folder parameters, put forward slashes / instead of \.  Like "F:/DB/SDXL/SALOMAV1/IMG/" instead of "F:\DB\SDXL\SALOMAV1\IMG\", I hope it helps.
> 

Gonna try it tomorrow
Thanks for your time

**Comment by abozahran** [comment]
> In your folder parameters, put forward slashes / instead of . Like "F:/DB/SDXL/SALOMAV1/IMG/" instead of "F:\DB\SDXL\SALOMAV1\IMG", I hope it helps.

it did fixed resolution problem so thank you so much for the solution
but i gave me another error (TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'debug')
![image](https://github.com/bmaltais/kohya_ss/assets/107565623/f009788e-a26c-4b2f-b661-7a604d54c2a4)

**Comment by Shenrui-Ma** [comment]
Sorry guys, I used forwards slashes,but still "resolution is required / resolution（解像度）指定は必須です".

https://github.com/kohya-ss/sd-scripts/issues/1449#issue-2459558005
