### ISSUE TITLE
Destination directory \torch\lib does not exist

### ISSUE THREAD

**Issue by marmosetjones** [bmaltais/kohya_ss#1561]
![image](https://github.com/bmaltais/kohya_ss/assets/116389415/b9c93471-981d-46af-a848-3e7e41567380)

I've tried manually adding it, but it locks the installer up. I have the cudann files in the root directory as well. I'm using 3.10.10 python because I can't get 3.10.9 installed without uninstalling 3.10.10. Using windows 11.

**Comment by cat0318** [comment]
I had the same problem, how did you fix it? Can you help me?

**Comment by cat0318** [comment]
> ![image](https://user-images.githubusercontent.com/116389415/271911204-b9c93471-981d-46af-a848-3e7e41567380.png)
> 
> I've tried manually adding it, but it locks the installer up. I have the cudann files in the root directory as well. I'm using 3.10.10 python because I can't get 3.10.9 installed without uninstalling 3.10.10. Using windows 11.

I had the same problem, have you fixed it? Hopefully it will help me out a bit. I am using 3.10.9 python.Using windows 11.

**Comment by marmosetjones** [comment]
You have to install the gui and then install cudann files.
