### ISSUE TITLE
Problem on Setup.bat Cannot be run correctly

### ISSUE THREAD

**Issue by zsfwz** [bmaltais/kohya_ss#1569]
I`m Windows users with no experience of programming Python, i study it by myself a little,So please forgive me if I'm wrong.
Here is my situation:
I download code with zip and unzip it on my G:. When running Setup.bat, it suddenly disappear.
So I run the bat as administrator , it remind me that i have no such file or directory.
While open it with notepad, i find that it can not locate setup_windows.py correctly. Then i change it with my path on G:\
Then i can run to Kohya_ss GUI setup menu. But when i installing entrypoints, it reminds me no module pip._internal
After research, i reinstall pip, then i finally install Kohya_ss.
So the problem might appear with pip or wrong path located. 
Based on no experience about writing py, hope my method will help.

**Comment by zsfwz** [comment]
New discovery, I also created a new one in C disk, but the same situation also appeared, can not be installed correctly

**Comment by zsfwz** [comment]
Now I repeat type : gui.bat --listen 127.0.0.1 --server_port 7860 --inbrowser --share on cmd, and install the missing module, but in the entrypoint package, I have been repeatedly installed but doesnt work. I really want to use train my own lora, please solve this problem. ToT

**Comment by yushan777** [comment]
I made this guide a while ago for Windows. Even if you don't use dreambooth or sdxl, it at least covers the set up part.  
https://medium.com/@yushantripleseven/dreambooth-training-sdxl-using-kohya-ss-windows-7d2491460608
