### ISSUE TITLE
Odd warning and botched training

### ISSUE THREAD

**Issue by DiggyDre** [bmaltais/kohya_ss#1573]
I haven't been able to get a proper training ever since I upgraded from a 3070 to a 4070ti. I have no clue why. I am giving it another go, but I also keep seeing this warning when I am training an SD 1.5 LorA, and I wondered what it means:

}
 is outdated. `steps_offset` should be set to 1 instead of 0. Please make sure to update the config accordingly as leaving `steps_offset` might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hugging Face Hub, it would be very nice if you could open a Pull request for the `scheduler/scheduler_config.json` file

**Comment by Nthompson096** [comment]
I keep getting this warning too, though I think my training goes well; still would like to know how to correct this unless if this is something I can ignore.
