### ISSUE TITLE
Constantly fails to install tensorboard / tensorflow.

### ISSUE THREAD

**Issue by mkultra333** [bmaltais/kohya_ss#1576]
Always fails to install tensorboard tensorflow.  I used pip to install them independently but that doesn't help, I guess because of a venv or something.

Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files (avoid unless you really need it)
3. (Optional) Install specific bitsandbytes versions
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 1

1. Torch 1 (legacy, no longer supported. Will be removed in v21.9.x)
2. Torch 2 (recommended)
3. Cancel

Enter your choice: 2

15:58:45-342672 INFO     Version: v22.0.1

15:58:45-347672 INFO     Python 3.10.6 on Windows
15:58:45-360670 INFO     nVidia toolkit detected
15:58:46-786298 INFO     Torch 2.0.1+cu118
15:58:46-812299 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:58:46-815298 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8191 Arch (8, 6) Cores 46
15:58:46-817297 INFO     Installing modules from requirements_windows_torch2.txt...
15:58:46-819299 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
15:58:52-577155 INFO     Installing package: bitsandbytes==0.35.0
15:58:54-419469 INFO     Installing package: tensorboard==2.12.3 tensorflow==2.12.0
15:59:10-200002 ERROR    Error running pip: install --upgrade tensorboard==2.12.3 tensorflow==2.12.0
15:59:10-203003 INFO     Installing modules from requirements.txt...
15:59:10-211002 INFO     Installing package: -e .
15:59:16-276195 INFO     Copying bitsandbytes files...
15:59:16-279195 INFO     Configuring accelerate...

**Comment by MysticDaedra** [comment]
Having the same problem.

**Comment by bmaltais** [comment]
Torch 1 is no longer supported. Try with Torch 2. Torch 1 support will be removed in the next update.

**Comment by mkultra333** [comment]
I was selecting option 2 to use Torch 2.
