### ISSUE TITLE
Runpod ports

### ISSUE THREAD

**Issue by Ai-Artsca** [bmaltais/kohya_ss#1582]
![Screenshot 2023-10-06 094132](https://github.com/bmaltais/kohya_ss/assets/89314745/ea3b525a-fd10-4cd6-8780-8258a4cc3c25)

Ports are not opening

**Comment by ashleykleynhans** [comment]
This is the wrong repo for this.
You need to wait for the applications to sync to `/workspace`.
Check your container logs, the container is only ready when the logs say `Container is READY!`.
Then you can access the ports.
