### ISSUE TITLE
Broken setup script

### ISSUE THREAD

**Issue by ahernandezmiro** [bmaltais/kohya_ss#1584]
Setup script appears to be broken on Windows at least:

C:\Users\user\dev\kohya_ss>setup.bat
←[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

←[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
←[1;33m=============================================================←[0m

Traceback (most recent call last):
  File ".\setup\setup_windows.py", line 238, in <module>
    setup_common.setup_logging()
  File "C:\Users\user\dev\kohya_ss\setup\setup_common.py", line 54, in setup_logging
    logging.basicConfig(
  File "C:\Users\user\miniconda3\lib\logging\__init__.py", line 1997, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**Comment by bmaltais** [comment]
Are you using python 3.10.6 or 3.11.x? I am not getting this error under 3.10.x.

**Comment by bandinopla** [comment]
i get the same error: **Unrecognised argument(s): encoding, force**
Using **python 3.10.9**

**Comment by bmaltais** [comment]
Hummm, this is a new one. I will try to re-run a full setup at my end to see if I can reproduce the issue. You are on Windows, right?

**Comment by bandinopla** [comment]
> Hummm, this is a new one. I will try to re-run a full setup at my end to see if I can reproduce the issue. You are on Windows, right?

i just noticed on the console... python 3.7 is being used... is this my error? did i forgot to set some other variable?

```
I:\LoRA--Trainer\kohya_ss>.\setup.bat
[1;33m=============================================================
Modules installed outside the virtual environment were found.
This can cause issues. Please review the installed modules.

You can uninstall all local modules with:

[1;34mdeactivate
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
[1;33m=============================================================[0m

Traceback (most recent call last):
  File ".\setup\setup_windows.py", line 209, in <module>
    setup_common.setup_logging()
  File "I:\LoRA--Trainer\kohya_ss\setup\setup_common.py", line 60, in setup_logging
    force=True,
  File "C:\Program Files\Python37\lib\logging\__init__.py", line 1870, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding, force
```

**Comment by bmaltais** [comment]
Indeed, the code only work with v3.9.6+

**Comment by bandinopla** [comment]
> Unrecognised argument(s): encoding

do you have any idea why, even tho i have 310 on my PATH, the code for kohya is being executed by my 37 version of python?
