### ISSUE TITLE
[Enhancement]: Support for Torch 2.1.0

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#1588]
Torch 2.1.0 was released 5 days ago, it would be awesome to upgrade from Torch 2.0.1 to 2.1.0.

**Comment by bmaltais** [comment]
I am trying to keep aligned with kohya's requirements file as much as I can to maximize compatibility with his code. Does torch 2.1.0 bring significant speed improvements that would be worth integrating before kohya adopt that release?

**Comment by ashleykleynhans** [comment]
I am not sure about that, but xformers is currently blocking it anyway:

https://github.com/facebookresearch/xformers/issues/870

We will need xformers to add support for Torch 2.1.0 before changing anything.

I can run some performance comparisons in RunPod once xformers is updated.
