### ISSUE TITLE
[Enhancement] Early stopping when training models

### ISSUE THREAD

**Issue by segalinc** [bmaltais/kohya_ss#1593]
Hi 
I was curious to learn if there is any plan to add some sort of early stopping method when training SD models instead of training until they overfit and have to manually inspect all the checkpoints, maybe using some of the metrics like FIS or IS

**Comment by bmaltais** [comment]
This would need to be added by kohya himself. I only wrap his great code in a gradio GUI. I suggest you create an issue directly on his sd-scripts repo.
