### ISSUE TITLE
HEIC File Format

### ISSUE THREAD

**Issue by vararth** [bmaltais/kohya_ss#1600]
Just a question - will the LoRA training for SD1.5 or SDXL work if I use HEIC images instead of JPEG or PNG files?

**Comment by bmaltais** [comment]
It is not supported as an image encoding format, sorry.

**Comment by vararth** [comment]
No issues - I actually just discovered an open source and free to use tool for image conversion that helped me get png files from my heic files - it is called converseen linked below
https://converseen.fasterland.net/
No clue if integrating it as another utility would be useful or helpful but thought I should share it here in case anyone else has files of different formats that they would like to train :)
