### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by PowerToTheNerd** [bmaltais/kohya_ss#1603]
![Screenshot 2023-10-12 082305](https://github.com/bmaltais/kohya_ss/assets/72634179/6eca10ad-6c21-4e71-81eb-60776bf485b8)

When running ./setup I get this error.

**Comment by bmaltais** [comment]
I am not sure why this is... I have no such issue on my system in either powershell terminal of Command. If someone know why that is I would be interested to learn about it.

**Comment by PowerToTheNerd** [comment]
Added "C:\Windows\System32\" into my environment variables and made some progress. Although instead of an error nothing is happening.

![image](https://github.com/bmaltais/kohya_ss/assets/72634179/22278d8d-184f-4590-8a10-6aa43466f511)
