### ISSUE TITLE
GLoRA training?

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#1606]
sd-scripts has it, and automatic1111 now allows it but the gui I can't train it even if I do  --network_module=networks.glora.  In sd-scripts do --algo=glora and it will train it.

**Comment by v0xie** [comment]
GLora training works if you do `--network_module=networks.lycoris --network_args "algo=glora" <other args here>`. 

You'll probably have to run the training command in a separate terminal because I don't think you can specify network_args in kohya_ss.

**Comment by DarkAlchy** [comment]
Anything on the extras line gets passed directly to the scripts so it should work, but I didn't type all of that I just saw what the gui was sending for dylora and changed it to glora.  I didn't think we needed more.  Seems this gui is falling VERY far behind as of late.

**Comment by DarkAlchy** [comment]
Got it to work by selecting dylora and using --network_args "algo=glora" only.

Disable conv layer for GLoRA
Using rank adaptation algo: glora
