### ISSUE TITLE
Problem when training LoRA

### ISSUE THREAD

**Issue by jonasr87** [bmaltais/kohya_ss#1609]
I've trained plenty of persons using lora (SDXL) some weeks ago without a problem. When I tried to do another training yesterday with the same settings and a good dataset it does not work at all, the models turns out really bad, the person is not looking anything like the dataset when trying to use in a prompt. I dont get any error messages. Also tried to reinstall Kohya but that didnt help. The only thing ive done during the last weeks Is to move kohya to another drive, but that should not be the problem I guess. Any suggestions?

**Comment by Vicullum** [comment]
I'm having the same problem, since updating to the latest version the SDXL Loras I train on a person end up a deep purplish color. I'm using the exact same images and parameters I used in an earlier version and I had no problems then.
