### ISSUE TITLE
Bug ile "H:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess returned non-zero exit status 1. -

### ISSUE THREAD

**Issue by TkonstAL** [bmaltais/kohya_ss#161]
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Folder 100_photo: 418300 steps
max_train_steps = 418300
stop_text_encoder_training = 0
lr_warmup_steps = 41830
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --enable_bucket --pretrained_model_name_or_path="H:/kohya_ss/train/Config.json" --train_data_dir="H:/kohya_ss/train/image" --resolution=512,512 --output_dir="H:/kohya_ss/train/model" --logging_dir="H:/kohya_ss/train/log" --save_model_as=safetensors --output_name="last" --learning_rate="1e-5" --lr_scheduler="cosine" --lr_warmup_steps="41830" --train_batch_size="1" --max_train_steps="418300" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --cache_latents --bucket_reso_steps=64 --xformers --use_8bit_adam --bucket_no_upscale
prepare tokenizer
prepare train images.
found directory 100_photo contains 4183 image files
418300 train images with repeating.
loading image sizes.
100%|?????????????????????????????????????????????????????????????????????????????| 4183/4183 [00:25<00:00, 162.84it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscale??????????bucket??????????????????????min_bucket_reso?max_bucket_reso???????
number of images (including repeats) / ?bucket????????????????
bucket 0: resolution (640, 384), count: 418300
mean ar error (without repeats): 0.1111971737455838
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "H:\kohya_ss\train_db.py", line 346, in <module>
    train(args)
  File "H:\kohya_ss\train_db.py", line 68, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype)
  File "H:\kohya_ss\library\train_util.py", line 1584, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "H:\kohya_ss\library\model_util.py", line 869, in load_models_from_stable_diffusion_checkpoint
    _, state_dict = load_checkpoint_with_text_encoder_conversion(ckpt_path)
  File "H:\kohya_ss\library\model_util.py", line 846, in load_checkpoint_with_text_encoder_conversion
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "H:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "H:\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '{'.
Traceback (most recent call last):
  File "C:\Users\tavol\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\tavol\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "H:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=H:/kohya_ss/train/Config.json', '--train_data_dir=H:/kohya_ss/train/image', '--resolution=512,512', '--output_dir=H:/kohya_ss/train/model', '--logging_dir=H:/kohya_ss/train/log', '--save_model_as=safetensors', '--output_name=last', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=41830', '--train_batch_size=1', '--max_train_steps=418300', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1. -

**Comment by TkonstAL** [comment]
![тнеогве7](https://user-images.githubusercontent.com/91704308/218520106-c81d5bcf-0847-4aad-99da-cd6644ea3347.png)
![5еуг76цу5г8цу](https://user-images.githubusercontent.com/91704308/218520120-07f2085b-b114-4e44-9766-81ebdd9f5835.png)

**Comment by Thund3rPat** [comment]
In your first error message, you accidentally set the wrong model path:
`pretrained_model_name_or_path=H:/kohya_ss/train/Config.json` 

And in the screenshot, it seems like you ran out of memory:
`Cuda out of memory`

Can you try to enable the “Memory efficient attention” option in the advanced tab or reduce the batch size?

**Comment by GonSpeedy** [comment]
I have the same issue like in the first message, even with correct pretrained model name. I am not sure what happened. I am not able to get it working. What is the root cause for that issue?

**Comment by qaisarehman** [comment]
> I have the same issue like in the first message, even with correct pretrained model name. I am not sure what happened. I am not able to get it working. What is the root cause for that issue?

As @Thund3rPat said, your pretrained model URL is wrong, I had the same issue, my models are in automatic1111>stable diffusion folder, so i copied the SD1.5 link in pretrained model.

and I also checked Memory efficient attention, as my GPU is  6GB, 

doing this started the training. :)
