### ISSUE TITLE
Accelerate Config

### ISSUE THREAD

**Issue by PowerToTheNerd** [bmaltais/kohya_ss#1613]
![image](https://github.com/bmaltais/kohya_ss/assets/72634179/6d4df6c3-ec82-44c6-bf28-bbe2d0135920)

How can I figure out the best values for my system running it on a GTX 4090 and AMD Ryzen 7 7800X3D 8-Core Processor 4201 Mhz?

![image](https://github.com/bmaltais/kohya_ss/assets/72634179/8f0c8efe-f95c-43cd-92cc-4fcf76f80943)

**Comment by josemerinom** [comment]
Hi

Accelerate==0.23.0 (mixprecision fp16):

compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

windows folder = C:\Users\<your user>\.cache\huggingface\accelerate\default_config.yaml
