### ISSUE TITLE
What this could be? :(

### ISSUE THREAD

**Issue by 4lt3r3go** [bmaltais/kohya_ss#1619]
![image](https://github.com/bmaltais/kohya_ss/assets/44883288/d0767168-0a22-44e0-a072-4cd0b281aba7)

**Comment by G4RLK** [comment]
> ![image](https://user-images.githubusercontent.com/44883288/276204607-d0767168-0a22-44e0-a072-4cd0b281aba7.png)

In my case, i reinstalled Python and it started working again, idk if it's gonna work on you but u can try it :)

**Comment by TheMoye** [comment]
Hello, I'm not sure but maybe the passed parameter '**scale_parameter**' is not compatible with the optimizer '**AdamW8bit**'. I encountered the same error message and removing the parameters '**scale_parameter=False relative_step=False warmup_init=False**' provided for the optimizer '**Adafactor**' resolved this issue.

However, I am still getting errors "**AttributeError: module 'tensorflow' has no attribute 'io'**" and "**raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)**" which is preventing any training via kohya_ss.
