### ISSUE TITLE
Cuda12.1 has achieved significant performance improvement and hopes to be adaptable

### ISSUE THREAD

**Issue by wzgrx** [bmaltais/kohya_ss#1624]
Cuda12.1 has achieved significant performance improvement and hopes to be adaptable

**Comment by suede299** [comment]
The current version does not have any compatibility issues with cuda12.1, at least with sdxl_train_network.py. You will only get a user warning that has no effect. you can even enable xformers, and the just released version 0.0.22.post7 I used without any problems.
Modify the version of the dependencies yourself, the whole process will only encounter errors in the accelerate configuration, you need to update the accelerate.
![image](https://github.com/bmaltais/kohya_ss/assets/85022330/b3103d68-e36e-4b27-a8d8-f44f8b746c41)

**Comment by sammcj** [comment]
Yeah 12.1 or 12.2 would be nice, I was doing my own custom docker image builds with them and they worked great.

**Comment by sammcj** [comment]
Just tested the project with Cuda 12.1 again which worked great, my fork is here if anyone else wants to do similar - https://github.com/sammcj/kohya_ss/tree/cudafix
