### ISSUE TITLE
Parameter settings of UI seems random, if not can someone please explain how the parameters are set especially the # epoch

### ISSUE THREAD

**Issue by andrewtvuong** [bmaltais/kohya_ss#1636]
![395577580_1251501482183311_6058618631504669907_n](https://github.com/bmaltais/kohya_ss/assets/15879426/0e431e98-9f10-4e61-9f6a-dd3a0ea8c06d)

Everything has been retried and values changed to ensure not a one off case.

For example, on the UI I set for 5 epoch, but somehow I end up with 350 epoch, not sure how this value is determined.

I have 150 images and its .txt caption placed in a folder that's named 5_apple. This should mean 5 repeated steps for 150 images for 5 epoch for a total of 3750 total steps, but somehow I have 261875 total steps.

My GPU is a 3070ti with 8gb vram, Driver 545.84, CUDA 12.3, with CUDNN optimization.

With a smaller image dataset of 15 files and 20 repeated steps the epoch parameter on the UI seems to respond correctly.
I just don't understand where the number 350 epoch is coming from, not divisible into any parameters I actually inputted.

Thanks! I saw a similar issue here https://github.com/bmaltais/kohya_ss/issues/1618.

**Comment by suede299** [comment]
Is it possible that it's a problem with the versions of the various dependencies? I'm using pytorch 2.1+cu121 and today also set 64epoch and ended up running 56epoch. but mine only has this one parameter different from the setup.

**Comment by 954114865** [comment]
Hey I solved this issue by windows repair install. This did no important changes to my system but fix this, you can try it out.
