### ISSUE TITLE
one machine multiple gpu problem

### ISSUE THREAD

**Issue by upseem** [bmaltais/kohya_ss#1639]
Training with 2 GPUs on a single machine. The total number of training steps I want is 100 steps, each training step is 50 steps, and finally a 100-step model is saved. Now I am training with accelerate, the total number of steps is 100 steps, and two GPUs are trained at the same time. 100 steps, save two models。 
accelerate config:
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by bishalsahooviga** [comment]
I am facing same issue. What is the solution that worked?

**Comment by thecodebloodedguy** [comment]
I am facing the same issue. What solution worked for you?
