### ISSUE TITLE
1st time sdxl lora training

### ISSUE THREAD

**Issue by marks202309** [bmaltais/kohya_ss#1641]
Below is the config.toml. But I have got 10 safetensors files, every file is 6.9GB. What is the wrong here?
[additional_network_arguments]
no_metadata = false
unet_lr = 0.0001
text_encoder_lr = 5e-5
network_module = "locon.locon_kohya"
network_dim = 64
network_alpha = 32
network_args = [ "conv_dim=64", "conv_alpha=32",]
network_train_unet_only = false
network_train_text_encoder_only = false

[optimizer_arguments]
optimizer_type = "AdamW8bit"
learning_rate = 0.0001
max_grad_norm = 1.0
optimizer_args = [ "weight_decay=0.6",]
lr_scheduler = "constant"
lr_warmup_steps = 0

[dataset_arguments]
cache_latents = true
debug_dataset = false

[training_arguments]
output_dir = "/media/marks/OS_Share/sdxl_lora_output"
output_name = "zoe2023"
save_precision = "fp16"
save_every_n_epochs = 1
train_batch_size = 6
max_token_length = 225
mem_eff_attn = false
xformers = true
max_train_epochs = 10
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
gradient_checkpointing = true
gradient_accumulation_steps = 1
mixed_precision = "fp16"
clip_skip = 2
logging_dir = "/media/marks/OS_Share/SD_Sample_Set/logs"
log_prefix = "zoe2023"
noise_offset = 0.1
lowram = true

[sample_prompt_arguments]
sample_every_n_epochs = 1
sample_sampler = "ddim"

[dreambooth_arguments]
prior_loss_weight = 1.0

[saving_arguments]
save_model_as = "safetensors"

**Comment by paboum** [comment]
`network_dim` is basically controlling the model size. Change it to 32 or even 16 if you want smaller files, or increase `save_every_n_epochs` to 2 if want only half the files, 3 if only one third etc.
