### ISSUE TITLE
Unable to run in docker on Manjaro

### ISSUE THREAD

**Issue by wereretot** [bmaltais/kohya_ss#1647]
sudo docker compose run --service-ports kohya-ss-gui
[sudo] password for rexommendation: 
ERRO[0000] error waiting for container:                 
Error response from daemon: could not select device driver "nvidia" with capabilities: [[]]

**Comment by kabrio** [comment]
might have to install the nvidia container toolkit to enable your gpu in docker! 

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
