### ISSUE TITLE
Loading external VAE does not work in LoRA training

### ISSUE THREAD

**Issue by gordigo** [bmaltais/kohya_ss#1655]
Hi there, as described in the title trying to load a external VAE will do nothing in the LoRA tab (might happen too in Dreambooth?)
![imagen](https://github.com/bmaltais/kohya_ss/assets/23042093/727ecd6d-9e1f-430d-9bc3-6bbfeac8f8cd)

Printing the command does not show any references to the VAE, and starting training does not show it being loaded
![imagen](https://github.com/bmaltais/kohya_ss/assets/23042093/81b17150-8f94-414a-984f-4540698d0899)

Passing --vae "F:/stable-diff/stable-diffusion-webui/models/VAE/counterfeitV25VAE_v25.pt" as Additional Parameter works as expected.

![imagen](https://github.com/bmaltais/kohya_ss/assets/23042093/c8defe7d-d81e-49dc-a3d9-d7c5c31babde)

**Comment by rockerBOO** [comment]
I think I put together the code to link the VAE box to the cmd code in #1656 if you want to give it a shot

**Comment by rockerBOO** [comment]
This has been merged and should be fixed.

**Comment by bmaltais** [comment]
@rockerBOO Do you have a recommendation for a VAE that could be used to improve training? I would like to give it a try,

**Comment by rockerBOO** [comment]
@bmaltais 

<https://huggingface.co/stabilityai/sd-vae-ft-mse> or <https://huggingface.co/stabilityai/sd-vae-ft-ema> for SD 1.5.

Can see the comparisons on the model card. Says ft-ema has a slightly lower FID. ft-mse says smoother outputs from ft-ema version. Many people go with ft-mse version.

<https://huggingface.co/stabilityai/sdxl-vae> for SDXL.

Kohya supports putting in the path like `--vae="stabilityai/sdxl-vae"` which will download the VAE model.
