### ISSUE TITLE
kohya not detecting the other gpus despite configuring accelerate

### ISSUE THREAD

**Issue by HG2407** [bmaltais/kohya_ss#1657]
`-------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
-------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
multi-GPU
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Should distributed operations be checked while running for errors? This can avoid timeout issues but will be slower. [yes/NO]: yes
Do you wish to optimize your script with torch dynamo?[yes/NO]:no
Do you want to use DeepSpeed? [yes/NO]: no
Do you want to use FullyShardedDataParallel? [yes/NO]: no
Do you want to use Megatron-LM ? [yes/NO]: no
How many GPU(s) should be used for distributed training? [1]:4
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:0,1,2,3
-------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
fp16`

these were my configurations but on running ./gui.sh --share I get
INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700

why is it not detecting the other gpus ?

I have also done "export CUDA_VISIBLE_DEVICES="0,1,2,3" " in  gui.sh file

**Comment by zengjie617789** [comment]
accelerate config --> distribute training ---> multi gpus
