### ISSUE TITLE
SyntaxWarning: invalid escape sequence '\c'

### ISSUE THREAD

**Issue by Fire1982Photo** [bmaltais/kohya_ss#1660]
Hi, I follow the instruction for installing, but I have this error for the last point?

`D:\Kohya\kohya_ss>.\setup.bat
Warning: Python version 3.10.9 is recommended.
Creating venv...
D:\Kohya\kohya_ss\setup\setup_windows.py:19: SyntaxWarning: invalid escape sequence '\c'
  os.path.dirname(os.path.realpath(__file__)), '..\cudnn_windows'
D:\Kohya\kohya_ss\setup\setup_windows.py:229: SyntaxWarning: invalid escape sequence '\g'
  subprocess.Popen('start cmd /k .\gui.bat --inbrowser', shell=True) # /k keep the terminal open on quit. /c would close the terminal instead
Traceback (most recent call last):
  File "D:\Kohya\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "D:\Kohya\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
D:\Kohya\kohya_ss>/c
'/c' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.`

Can u help me?

Thanks

**Comment by luismartinezs** [comment]
@Fire1982Photo I have the same problem. If you close this is it because you found a solution? If yes, what is it?

**Comment by KmBase** [comment]
modifiy comment will be work
