### ISSUE TITLE
When can we expect sd-scripts-dev to be merged?

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1670]
I have done over 20 SDXL DreamBooth trainings with text encoder

working nice

when can you merge? 

Thank you so much

**Comment by bmaltais** [comment]
It is currently in the dev2 branch. You can give it a try with:

```
git checkout dev2
git pull
```

to return back to master do:

```
git checkout master
git pull
```

I am planning to release the new code to master later today or tomorrow.

**Comment by FurkanGozukara** [comment]
awesome will test ty
