### ISSUE TITLE
unsolvable puzzle

### ISSUE THREAD

**Issue by ponylin19780630** [bmaltais/kohya_ss#1672]
[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 509/509 [00:00<00:00, 1392.43it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (480, 736), count: 30
bucket 1: resolution (512, 704), count: 60
bucket 2: resolution (512, 736), count: 60
bucket 3: resolution (512, 768), count: 1140
bucket 4: resolution (544, 576), count: 30
bucket 5: resolution (544, 640), count: 30
bucket 6: resolution (544, 672), count: 300
bucket 7: resolution (544, 704), count: 60
bucket 8: resolution (576, 544), count: 30
bucket 9: resolution (576, 608), count: 30
bucket 10: resolution (576, 640), count: 30
bucket 11: resolution (576, 672), count: 90
bucket 12: resolution (608, 576), count: 30
bucket 13: resolution (608, 608), count: 120
bucket 14: resolution (608, 640), count: 30
bucket 15: resolution (640, 416), count: 30
bucket 16: resolution (640, 576), count: 60
bucket 17: resolution (672, 576), count: 30
bucket 18: resolution (736, 480), count: 30
mean ar error (without repeats): 0.0008985845715163716
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
unet\diffusion_pytorch_model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.18it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable memory efficient attention for U-Net
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████████████████████████████████████████████████| 509/509 [00:08<00:00, 58.39it/s]
caching latents...
0it [00:00, ?it/s]
create LoRA network. base dim (rank): 128, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use Adafactor optimizer | {'relative_step': True, 'weight_decay': 0.02}
relative_step is true / relative_stepがtrueです
learning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されます
unet_lr and text_encoder_lr are ignored / unet_lrとtext_encoder_lrは無視されます
use adafactor_scheduler / スケジューラにadafactor_schedulerを使用します
Traceback (most recent call last):
  File "C:\Users\user\Desktop\kohya_ss\train_network.py", line 1009, in <module>
    trainer.train(args)
  File "C:\Users\user\Desktop\kohya_ss\train_network.py", line 344, in train
    train_dataloader = torch.utils.data.DataLoader(
  File "C:\Users\user\Desktop\kohya_ss\venv\lib\site-packages\torch\utils\data\dataloader.py", line 253, in __init__
    raise ValueError('persistent_workers option needs num_workers > 0')
ValueError: persistent_workers option needs num_workers > 0
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Desktop\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\user\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\Users\user\Desktop\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\Desktop\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:\\Users\\user\\Desktop\\SDtrain_data\\AVGIRLriver\\img', '--reg_data_dir=C:\\Users\\user\\Desktop\\SDtrain_data\\AVGIRLriver\\reg', '--resolution=512,768', '--output_dir=C:\\Users\\user\\Desktop\\SDtrain_data\\AVGIRLriver\\model', '--logging_dir=C:\\Users\\user\\Desktop\\SDtrain_data\\AVGIRLriver\\log', '--network_alpha=1', '--training_comment=avriver1111', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=0.5', '--unet_lr=1.0', '--network_dim=128', '--output_name=avriver1111', '--lr_scheduler_num_cycles=6', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=13320', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'relative_step=True', 'weight_decay=0.02', '--lr_scheduler_args', '0.0001', '--max_data_loader_n_workers=0', '--bucket_reso_steps=32', '--min_snr_gamma=5', '--mem_eff_attn', '--shuffle_caption', '--full_fp16', '--xformers', '--persistent_data_loader_workers', '--bucket_no_upscale', '--noise_offset=0.1']' returned non-zero exit status 1.

**Comment by a-l-e-x-d-s-9** [comment]
You need num_workers to be 1 or more, which is defined by max_data_loader_n_workers argument.
