### ISSUE TITLE
changing the location of .cache to D drive

### ISSUE THREAD

**Issue by Tempaccnt** [bmaltais/kohya_ss#169]
Hi

I would like to train lora models. but after setting everything up, kohya_ss start downloading models in the C drive (I managed to clear up 12GB but even that was not enough) .

is it possible to change the location/path of those models to D drive instead?

**Comment by linbiaotongzhiyongyuanjiankang** [comment]
Hey dude, I tried setting up a new path for cache.

It's 'The Disk':\kohya_ss\venv\Lib\site-packages\torch\hub.py

You may change the path at the 74th line: DEFAULT_CACHE_DIR = './.cache'

You may change the path at the 74th line: DEFAULT_CACHE_DIR = './.cache'

**Comment by maxryan02** [comment]
Can you step by step bro. i'm not good with this stuff.
I already edit line 74th. 
line 78 i don't know how .
and change env variables i can't find on google.
