### ISSUE TITLE
Kohya_ss - Tcl wasn't installed properly

### ISSUE THREAD

**Issue by joli-coeur50** [bmaltais/kohya_ss#1693]
I have had this problem on kohya for a few days,
when I click on a folder to select my checkpoint or my images, I have this message that appears. 

Can't find a usable init;tcl in the following directories : (...)
This probably means that Tcl wasn't installed properly

I'm on Linux Ubuntu, I've already tried on Linux Mint and Cinnamon, I have exactly the same problem...
I tried installing Tcl via the pip command, installing old versions of kohya, and many other things but nothing changes... it was working fine a few days ago, I don't know why. ..

Thanks for your help !

**Comment by ashleykleynhans** [comment]
```
apt install python3-tk
```

**Comment by joli-coeur50** [comment]
> ```
> apt install python3-tk
> ```

thank you for your answer, but nothing happens...
he installs the package correctly (with sudo) but kohya tells me exactly the same thing...
Maybe I should install the package elsewhere?
or is the problem coming from elsewhere? I really do not understand...
