### ISSUE TITLE
Setting LRs for TE in dreambooth training will not enable TE training

### ISSUE THREAD

**Issue by mebe1012** [bmaltais/kohya_ss#1696]
In the latest version of kohya ss (v22.2.1), if you enter values at the boxes at the GUI for the learning rates of the text encoders during dreambooth training, it will still not train with these values. 

Logs show:

`--learning_rate_te1="5e-06" --learning_rate_te2="5e-06"
                         --learning_rate="1e-05"` in training cmd, but

`train unet: True, text_encoder1: False, text_encoder2: False`

is shown before starting the training.

I assume that entering values in the boxes in the GUI is not enabling the `--train_text_encoder` flag, as this was not set in the training cmd. Setting the `--train_text_encoder` manually at the training cmd will fix the issue.

**Comment by bolli20000** [comment]
I have the same issue, is there a solution with it now ?

**Comment by Syscore64** [comment]
same problem at 22.5.0
