### ISSUE TITLE
I really can't figure out what he wants from me, I'm not a programmer.

### ISSUE THREAD

**Issue by WagnerFighter** [bmaltais/kohya_ss#1700]
I can't start training on my 4060ti 16gb in any way. Can you please explain in detail what is needed to fix it.

02:14:41-212323 INFO     ./venv/Scripts/python.exe finetune/prepare_buckets_latents.py "E:\Training_dir\10_Retush"
                         "E:\Training_dir/meta_cap.json" "E:\Training_dir/meta_lat.json"
                         "runwayml/stable-diffusion-v1-5" --batch_size=2 --max_resolution=768,1024 --min_bucket_reso=256                         --max_bucket_reso=1024 --mixed_precision=fp16 --full_path
found 88 images.
no metadata / メタデータファイルがありません: E:\Training_dir/meta_cap.json
02:14:44-358026 INFO     image_num = 88
02:14:44-359026 INFO     repeats = 880
02:14:44-360026 INFO     max_train_steps = 88000
02:14:44-361027 INFO     lr_warmup_steps = 4400
02:14:44-361027 INFO     Saving training config to E:\Training_dir\last1_20231120-021444.json...
02:14:44-362027 INFO     accelerate launch --num_cpu_threads_per_process=14 "./fine_tune.py" --train_text_encoder
                         --learning_rate_te="1e-07" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --in_json="E:\Training_dir/meta_lat.json" --train_data_dir="E:\Training_dir\10_Retush"
                         --output_dir="E:\Training_dir" --dataset_repeats=10 --enable_bucket --resolution="768,1024"
                         --min_bucket_reso=256 --max_bucket_reso=1024 --save_model_as=safetensors --output_name="last1"
                         --learning_rate="1e-07" --lr_scheduler="adafactor" --lr_warmup_steps="4400"
                         --train_batch_size="2" --max_train_steps="88000" --save_every_n_epochs="1"
                         --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="Adafactor"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --noise_offset=0.0
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
prepare tokenizer
Traceback (most recent call last):
  File "E:\kohya_ss\fine_tune.py", line 499, in <module>
    train(args)
  File "E:\kohya_ss\fine_tune.py", line 81, in train
    train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.dataset_group)
  File "E:\kohya_ss\library\config_util.py", line 430, in generate_dataset_group_by_blueprint
    dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))
  File "E:\kohya_ss\library\train_util.py", line 1528, in __init__
    raise ValueError(f"no metadata / メタデータファイルがありません: {subset.metadata_file}")
ValueError: no metadata / メタデータファイルがありません: E:\Training_dir/meta_lat.json
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', './fine_tune.py', '--train_text_encoder', '--learning_rate_te=1e-07', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--in_json=E:\\Training_dir/meta_lat.json', '--train_data_dir=E:\\Training_dir\\10_Retush', '--output_dir=E:\\Training_dir', '--dataset_repeats=10', '--enable_bucket', '--resolution=768,1024', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--save_model_as=safetensors', '--output_name=last1', '--learning_rate=1e-07', '--lr_scheduler=adafactor', '--lr_warmup_steps=4400', '--train_batch_size=2', '--max_train_steps=88000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=Adafactor', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--noise_offset=0.0']' returned non-zero exit status 1.

![Screenshot_1](https://github.com/bmaltais/kohya_ss/assets/121365756/eb625544-db16-401b-8ade-1c2c26194222)

**Comment by BansheeStudio** [comment]
same issue here

**Comment by mebe1012** [comment]
It is complaining about the meta_lat.json file that you're passing in. Maybe it is just the problem that you passed the file path to the meta_lat.json with a backslash instead of a slash (you got a mix of backslash and slash in your file path).

**Comment by WagnerFighter** [comment]
> Он жалуется на файл мета_lat.json, который вы передаете. Возможно, проблема просто в том, что вы передали путь к файлу в мета_lat.json с обратной косой чертой вместо косой черты (у вас есть смесь обратной косой черты и косой черты в ваш путь к файлу).

he creates this file himself, I don't touch it at all, all these slashes appear by themselves. I dug around and sort of fixed it by unscrewing "LR warmup (%steps)" to the value "0" and "Use latent files" - no.

**Comment by kuyacai** [comment]
`--train_data_dir=E:\Training_dir\10_Retush`
Is the image folder configured wrong?
If the location of  image is  `E:\Training_dir\10_Retush\1.png`, then the image folder should be `E:\Training_dir`

**Comment by WagnerFighter** [comment]
> `--train_data_dir=E:\Training_dir\10_Retush` Папка с изображениями настроена неправильно? Если расположение изображения `E:\Training_dir\10_Retush\1.png`, то папка изображения должна быть`E:\Training_dir`
You're wrong.
Only a direct link to the folder with pictures works (E:\Training_dir\images\1_retush)
![Screenshot_881](https://github.com/bmaltais/kohya_ss/assets/121365756/d9a5a13b-d6ad-4d29-8efe-16f404e6f306)

**Comment by WagnerFighter** [comment]
> `--train_data_dir=E:\Training_dir\10_Retush` Папка с изображениями настроена неправильно? Если расположение изображения `E:\Training_dir\10_Retush\1.png`, то папка изображения должна быть`E:\Training_dir`

That's what I'm doing. does not work
![Screenshot_1](https://github.com/bmaltais/kohya_ss/assets/121365756/c8441c98-70d5-4ea3-abc3-00a9d7b6c43f)
![Screenshot_2](https://github.com/bmaltais/kohya_ss/assets/121365756/4045e7bd-a152-4ba1-9e98-f65516efc369)
![Screenshot_881](https://github.com/bmaltais/kohya_ss/assets/121365756/f1914f5c-62f3-497d-8246-3bce6de2e46e)
