### ISSUE TITLE
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

### ISSUE THREAD

**Issue by venomsoft1** [bmaltais/kohya_ss#1704]
![image](https://github.com/bmaltais/kohya_ss/assets/151836533/7cc40f86-25e6-4fda-821d-043391251f46)

**Comment by venomsoft1** [comment]
go to .\venv\scripts using cmd
write "activate", then "pip install bitsandbytes-windows"

**Comment by kyesniper** [comment]
> go to .\venv\scripts using cmd write "activate", then "pip install bitsandbytes-windows"

Oh my god thank you, this finally solved my problem.

**Comment by Casey-bit** [comment]
thank u so much!!!!!!!
really helps me  a lot

**Comment by Lucfifael** [comment]
> go to .\venv\scripts using cmd write "activate", then "pip install bitsandbytes-windows"

You are the best, so quick and simple!

**Comment by MOGRAINEREPORTS** [comment]
> go to .\venv\scripts using cmd write "activate", then "pip install bitsandbytes-windows"

For anyone still having this problem in the future, it definitely works.
Hopefully its fixed in setup soon ;P

**Comment by nikolatesla20** [comment]
ran into this problem today. Going to try the fix soon

**Comment by wallypop** [comment]
mine randomly broke today on windows, had to uninstall bitsandbytes-windows and then reinstall it, but I'm up and running again. For those not sure how to do that, open a command prompt in the kohya_ss directory, then:

cd ./venv/scripts/
./activate
pip uninstall bitsandbytes-windows
pip install bitsandbytes-windows
pip check

You should show clean, and should be able to run kohya_ss again.

**Comment by github-gil** [comment]
I see following errors when I try to execute "activate" or activate.bat
"Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\Kohya-ss\kohya_ss\venv\Scripts> activate
activate : **The term 'activate' is not recognized as the name of a cmdlet, function, script file, or operable program. C
heck the spelling of the name, or if a path was included, verify that the path is correct and try again.**
At line:1 char:1                                                                                                        + activate                                                                                                              + ~~~~~~~~                                                                                                                  + CategoryInfo          : ObjectNotFound: (activate:String) [], CommandNotFoundException                                + FullyQualifiedErrorId : CommandNotFoundException                                                                                                                                                                                                                                                                                                                  Suggestion [3,General]: **The command activate was not found, but does exist in the current location.** Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: **".\activate**". See "get-help about_Command_Precedence" for more details.                                                                    PS D:\Kohya-ss\kohya_ss\venv\Scripts> activate.bat                                                                      activate.bat : The term 'activate.bat' is not recognized as the name of a cmdlet, function, script file, or operable pr ogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.        At line:1 char:1                                                                                                        + activate.bat                                                                                                          + ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (activate.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException"


if I run this as an administrator I see:
D:\Kohya-ss\kohya_ss\venv>**.\activate**
**'.\activate' is not recognized as an internal or external command,
operable program or batch file.**
or
D:\Kohya-ss\kohya_ss\venv>**activate**
'activate' is not recognized as an internal or external command,
operable program or batch file.
or
D:\Kohya-ss\kohya_ss\venv>**activate.bat**
'activate.bat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by wallypop** [comment]
> I see following errors when I try to execute "activate" or activate.bat "Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows
> 
> PS D:\Kohya-ss\kohya_ss\venv\Scripts> activate activate : **The term 'activate' is not recognized as the name of a cmdlet, function, script file, or operable program. C heck the spelling of the name, or if a path was included, verify that the path is correct and try again.** At line:1 char:1 + activate + ~~~~~~~~ + CategoryInfo : ObjectNotFound: (activate:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException Suggestion [3,General]: **The command activate was not found, but does exist in the current location.** Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: **".\activate**". See "get-help about_Command_Precedence" for more details. PS D:\Kohya-ss\kohya_ss\venv\Scripts> activate.bat activate.bat : The term 'activate.bat' is not recognized as the name of a cmdlet, function, script file, or operable pr ogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1 + activate.bat + ~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (activate.bat:String) [], CommandNotFoundException + FullyQualifiedErrorId : CommandNotFoundException"
> 
> if I run this as an administrator in standard command line, I see: D:\Kohya-ss\kohya_ss\venv>**.\activate** **'.\activate' is not recognized as an internal or external command, operable program or batch file.** or D:\Kohya-ss\kohya_ss\venv>**activate** 'activate' is not recognized as an internal or external command, operable program or batch file. or D:\Kohya-ss\kohya_ss\venv>**activate.bat** 'activate.bat' is not recognized as an internal or external command, operable program or batch file.

In a powershell window it needs to be ./activate from the webui\venv\Scripts\ directory. It looks like in your powershell window you didn't use the ./ and in the standard command line you weren't in the Scripts directory.

**Comment by mAlazwari** [comment]
> go to .\venv\scripts using cmd write "activate", then "pip install bitsandbytes-windows"

You're a legend

**Comment by github-gil** [comment]
> In a powershell window it needs to be ./activate from the webui\venv\Scripts\ directory. It looks like in your powershell window you didn't use the ./ and in the standard command line you weren't in the Scripts directory.

I don't have "webui" directory in my Kohya directory. The path to "scripts" directory is D:\Kohya-ss\kohya_ss\venv\scripts
I launched CMD there and typed "activate" but it ended with 0 messages in CMD as you can see on printscreen. is it expected?
![image](https://github.com/bmaltais/kohya_ss/assets/111198267/4091f1c6-e7a2-41fb-9e4c-b73f739a2f3e)

**Comment by wallypop** [comment]
> > In a powershell window it needs to be ./activate from the webui\venv\Scripts\ directory. It looks like in your powershell window you didn't use the ./ and in the standard command line you weren't in the Scripts directory.
> 
> I don't have "webui" directory in my Kohya directory. The path to "scripts" directory is D:\Kohya-ss\kohya_ss\venv\scripts I launched CMD there and typed "activate" but it ended with 0 messages in CMD as you can see on printscreen. is it expected? ![image](https://private-user-images.githubusercontent.com/111198267/309339480-4091f1c6-e7a2-41fb-9e4c-b73f739a2f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTc3OTAsIm5iZiI6MTcwOTMxNzQ5MCwicGF0aCI6Ii8xMTExOTgyNjcvMzA5MzM5NDgwLTQwOTFmMWM2LWU3YTItNDFmYi05ZTRjLWI3M2Y3MzlhMmYzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQxODI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTgyMmUzMDliMDNhMDA5YjNlODIyMTgwMGQzMThhMTZhMTJjY2E3NGIwYmVkYTgwNmI0MjBlOWJlYTlmYzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aDmGzy1UGmrnz8AAgqMExWPOK6QuUKRv3vHMDVmdbgo)

Got my wires crossed with automatic1111. See the (venv) to the left of the prompt? That tells me you've activated the virtual environment already, so just skip to the "pip install bitsandbytes-windows"
