### ISSUE TITLE
Installation bug : 'accelerate' is not recognized

### ISSUE THREAD

**Issue by patmol25** [bmaltais/kohya_ss#1705]
When i try to install Kohya, I have this issue :

Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files (avoid unless you really need it)
3. (Optional) Install specific bitsandbytes versions
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 1

11:18:29-532617 INFO     Version: v22.2.1

11:18:29-539610 INFO     Python 3.10.6 on Windows
11:18:29-543609 INFO     Installing modules from requirements_windows_torch2.txt...
11:18:29-546610 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
11:18:32-556362 INFO     Installing package: bitsandbytes==0.41.1
11:18:34-338893 INFO     Installing modules from requirements.txt...
11:18:34-347893 INFO     Installing package: -e .
11:18:41-016542 INFO     Copying bitsandbytes files...
11:18:41-018461 INFO     Configuring accelerate...
accelerate' is not recognized as an internal or external command
or external command, an executable program or a command file.

Someone know how to solve it ?
Thanks

**Comment by paseri3739** [comment]
maybe manually activate venv and run:
accelerate config
will fix it

**Comment by Grsz** [comment]
Same issue, @paseri3739 's suggestion didn't solve it

**Comment by nayyaung** [comment]
During the setup, kohya_ss is not only installing but also executing accelerator. So, you need to have it during the installation time which means whatever python env you are running the setup, it could be the host or another virtual env for the installation step, must have accelerate installed. 

Basically, run this before running setup

` pip install accelerate`

**Comment by sidx1024** [comment]
`pip install accelerate` did not work.

I had an existing setup which broke. I had Python 3.10.0 installed and when I run setup it says "The python version needs to be greater or equal to 3.10.9 and less than 3.11.0". Earlier it was working fine with 3.10.

I managed to fix it by installing 3.10.11 version from here: https://www.python.org/downloads/release/python-31011/
