### ISSUE TITLE
not generating samples

### ISSUE THREAD

**Issue by orenong** [bmaltais/kohya_ss#1708]
![סמפלס](https://github.com/bmaltais/kohya_ss/assets/52457663/1ce79ac7-14d9-40cf-ab87-25c2c2ab0714)

after 1,000 steps there were no samples, no attempt to generate them, no error, is it a bug? 

an epoch is 5,0000 steps and I didn't reach it yet

I'm trainning UNET only, I used to be able to generate samples with my other config

I have 6 prompts, same prompts as I had before when it waroked. 

techinally it's a bug even if it's not a bug because if it's not a bug then it should clearify why it's not generating the samples in the intended interval.

**Comment by orenong** [comment]
update: it does genrate the samples every epoch, it just ingores the "samples every n steps" option

**Comment by Deathawaits4** [comment]
yes, i have the same issue. You currently cant set both. If you want to sample every n steps, you need to disable epoch sampling. It would be great if this gets fixed because when using cosine with restarts, the epoch sample looks a lot different to the actual step samples.
