### ISSUE TITLE
 No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Sjbullis23** [bmaltais/kohya_ss#1722]
I have uninstalled all of the requirements and even tried older or newer versions and nothing fixes this 
![Screenshot_1034](https://github.com/bmaltais/kohya_ss/assets/69125870/18cad3a7-9c10-4be8-96d6-db13d53c5b08)
![Screenshot_1033](https://github.com/bmaltais/kohya_ss/assets/69125870/73ae6e7c-74d9-4200-b5d8-1cdd54528c80)

**Comment by Sjbullis23** [comment]
where are you seeing line 229 I only see up to 211 btw I'm using notepad++ if that changes anything

**Comment by l-trochelmann** [comment]
I ran into the same error.
After following the steps outlined above (note: the lines may be wrong, but the code is the same), I had to additionally run `pip install torch` in the venv. 
After that I could proceed with setup and encountered no further issues.
