### ISSUE TITLE
all new LORA produce "modules.devices.NansException: A tensor with all NaNs was produced in Unet" in StableDiffusion

### ISSUE THREAD

**Issue by mechamuffin2000** [bmaltais/kohya_ss#1729]
I don't know what I did, but I uninstalled and reinstalled Python for Kohya and now none of the LORA I'm making are generating in StableDiffusion. It keeps giving the NanException error. What did I do 😭

I first was having problems with bitsandbytes after reinstalling Python, it was saying there was no module for it and wouldn't train, so I installed one of them with Kohya's installer.

Now every model I'm training keeps giving this NanException area and I don't know why. FP16 Or BF16, it still does it. I already had Half-VAE on in StableDiffusion's UI. I'm genuinely not sure what's causing it, but it is specific to the new LORA I'm training. What am I doing wrong? What could be causing this??? It was working fine before.

**Comment by blu3maxi** [comment]
Yeah getting the same around Kohya v22.2.1, have done a complete fresh install on Windows 11. I'll try 22.1.1

nVidia driver version is 531.79 because the newest versions cause training to slow down.

**Comment by mechamuffin2000** [comment]
I managed to get a small LORA working again with about 240 steps. So, I honestly don't know anymore. Maybe it's running out of VRAM so the end result is the error in stablediffusion??? I don't understand why it keeps going then though in training.

 From what I understand, my 4080 should be able to handle training a LORA... So, maybe it's just something I'm doing wrong in settings. I really don't understand this.

**Comment by blu3maxi** [comment]
You should be able to get way more steps than that, I went all the way back to v21.8.10 and the NaN errors stopped and I was able to train again with the settings that worked for me.

I didn't try 22.0.0, 22.1.0 but 22.1.1 had NaN errors on my loras.

**Comment by bmaltais** [comment]
I think part of the issue might be the different version of bitsandbytes or xformers used in more recent updates by Kohya...

**Comment by humanistical** [comment]
Deleting the bitsandbytes install in venv\Lib\site-packages\bitsandbytes and the versioned folders and then reinstalling with 0.41.1 fixed it for me. Took it from cuda116 to cuda118 like the torch version in use.

**Comment by mAlazwari** [comment]
did all the stuff mentioned above, still getting the error for every LORA I train. I even went back to Khoya v21.8.10 and tried this version of bitsandbytes==0.35.0.  

My SD works fine with any other SDXL Loras and my VRAM is 24Gs so idk where the issue is exactly
