### ISSUE TITLE
error on train: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by tcflying** [bmaltais/kohya_ss#173]
(venv) PS F:\kohya_ss> .\gui.ps1
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Folder 25_allinone: 6575 steps
max_train_steps = 3288
stop_text_encoder_training = 0
lr_warmup_steps = 0
Traceback (most recent call last):
  File "F:\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "F:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\kohya_ss\lora_gui.py", line 462, in train_model
    run_cmd += run_cmd_advanced_training(
  File "F:\kohya_ss\library\common_gui.py", line 638, in run_cmd_advanced_training
    if int(kwargs.get('caption_dropout_every_n_epochs', 0)) > 0
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by ashesashes** [comment]
ran into this issue as well. how did you fix it @bmaltais  @tcflying ?

**Comment by Jackmekiss** [comment]
Same issue here

**Comment by bmaltais** [comment]
Will to check what is going on.

**Comment by bmaltais** [comment]
I can't reproduce the issue on my system ;-( All is working fine for me. What version are you using?

```txt
(venv) PS D:\kohya_ss> .\gui.ps1
18:59:49-253286 INFO     Kohya_ss GUI version: v24.1.5
18:59:49-866663 INFO     Submodule initialized and updated.
18:59:49-866663 INFO     nVidia toolkit detected
18:59:51-695771 INFO     Torch 2.1.2+cu118
18:59:51-727956 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
18:59:51-730576 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
18:59:51-733378 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
18:59:51-733378 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
18:59:51-733378 INFO     Verifying modules installation status from requirements_windows.txt...
18:59:51-741391 INFO     Verifying modules installation status from requirements.txt...
18:59:51-742343 WARNING  Package wrong version: gradio 4.26.0 required 4.36.0
18:59:51-742343 INFO     Installing package: gradio==4.36.0
18:59:56-559244 WARNING  Package wrong version: onnx 1.15.0 required 1.16.1
18:59:56-559244 INFO     Installing package: onnx==1.16.1
19:00:14-991188 INFO     headless: False
19:00:15-211189 INFO     Using shell=True when running external commands...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by b-fission** [comment]
@bmaltais 
You can cause the error if the "Dropout caption every n epochs" is blank in the gui.

**Comment by bmaltais** [comment]
Ah, that I can fix. Thanks!

**Comment by bmaltais** [comment]
Should be fixed in most recent release.
