### ISSUE TITLE
rtx 3080 sdxl lora training, extremely slow

### ISSUE THREAD

**Issue by ARRed98** [bmaltais/kohya_ss#1730]
Hi, I have a problem. Despite having a high-performance PC with an RTX 3080, 64GB DDR5, and Ryzen 7950X, I'm experiencing slow training times, specifically 140 seconds per iteration when using SDXL. This implies that completing the training would take hundreds of hours. I followed the guide from SECourses.

**Comment by wolfgangmeyers** [comment]
running pretty slow on rtx 3090 as well. Trying to figure out why

**Comment by wolfgangmeyers** [comment]
Dropped my dimensions from 32 to 8 and everything now fits into vram, and runs much, much quicker. Went from 200+s / it to 1.2s/it

**Comment by Roshag** [comment]
SDXL requires more ram. 11GB can handle SD1.5 512x512 with batch size 4 and dim 64, but SDXL with batch size 1 takes all VRAM and around 15-20GB of RAM - and training on RAM os much slower.
