### ISSUE TITLE
Outdated colab reference, no module `library` in finetune/make_captions.py

### ISSUE THREAD

**Issue by 0xlws** [bmaltais/kohya_ss#1734]
Hey i just wanted to give a headsup that the camenduru colab link is cloning a outdated fork which gives this error.
initially i solved it by 
from:
`sys.path.append(os.path.dirname(__file__))`
to:
`sys.path.append(os.path.dirname(os.path.dirname(__file__)))`
correctly append the parent but then i saw the main repo already fixed this

**Comment by GuillaumeCleme** [comment]
Duplicates #1007, solved in https://github.com/bmaltais/kohya_ss/commit/e084bc55395ba85b6aca4fdd897a7c474f3632ae
