### ISSUE TITLE
The following values were not passed to `accelerate launch` and had defaults used instead:

### ISSUE THREAD

**Issue by CRCODE22** [bmaltais/kohya_ss#1735]
Since the latest update at time of writing I am getting the following errors "The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`."

I have a 3060 RTX 12GB which is very capable of mixed_precision as I have used it often before with training in mixed precision and all the other settings above used to work.

**Comment by CRCODE22** [comment]
The problem seems to occur when you change the optimizer AdamW to Adafactor.

**Comment by tjip1234** [comment]
What is the exact problem? this seems to just be a warning to configure accelerate
