### ISSUE TITLE
Kohya_ss gives out errors whilst initializing Lora training

### ISSUE THREAD

**Issue by Totoro51212** [bmaltais/kohya_ss#1740]
I probably messed up somewhere whilst following this youtube tutorial https://youtu.be/k5imq01uvUY?si=DnesUIpkh2j0I3At. I thought it was due to missing modules, so reinstalled and did setup a couple times. During setup it redownloads a few modules, including bitsandbytes. Every time I try to train the model it ends up with some error and ends the process. Below is the powershell log whilst it crashes. I apologize if this was a waste of your time.

`loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 1833.73it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 100
bucket 1: resolution (384, 576), count: 200
bucket 2: resolution (448, 384), count: 100
bucket 3: resolution (448, 448), count: 200
bucket 4: resolution (448, 512), count: 200
bucket 5: resolution (512, 384), count: 100
bucket 6: resolution (512, 448), count: 100
bucket 7: resolution (512, 512), count: 100
bucket 8: resolution (576, 320), count: 200
bucket 9: resolution (576, 384), count: 400
bucket 10: resolution (640, 384), count: 600
mean ar error (without repeats): 0.060760629696905356
prepare accelerator
loading model for process 0/1
load Diffusers pretrained models: stabilityai/stable-diffusion-2-base
text_encoder\model.safetensors not found
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.21it/s]
UNet2DConditionModel: 64, [5, 10, 20, 20], 1024, True, False
U-Net converted to original U-Net
Enable xformers for U-Net
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:10<00:00,  2.14it/s]
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "D:\kohya_ss\library\train_util.py", line 3433, in get_optimizer
    import bitsandbytes as bnb
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "D:\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\kohya_ss\train_db.py", line 495, in <module>
    train(args)
  File "D:\kohya_ss\train_db.py", line 181, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\kohya_ss\library\train_util.py", line 3435, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\evani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\evani\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--v2', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-base', '--train_data_dir=D:\\Lora files\\Glass\\img', '--resolution=512,512', '--output_dir=D:\\Ai art\\Models\\Lora', '--logging_dir=D:\\Lora files\\Glass\\logs', '--save_model_as=safetensors', '--output_name=Glassv1.0', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=1', '--learning_rate_te=1e-05', '--learning_rate=0.001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1150', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.'

**Comment by Toiletduck34** [comment]
try this:

 to go the folder venv/scripts/ and in a cmd do: "activate" to activate the venv
And then type in: pip install bitsandbytes-windows

If that doesnt work, in the set up choose option 3 for installying bitsandbytes, choose version .35

**Comment by XiaoXiaoJiangYun** [comment]
> try this:
> 
> to go the folder venv/scripts/ and in a cmd do: "activate" to activate the venv And then type in: pip install bitsandbytes-windows
> 
> If that doesnt work, in the set up choose option 3 for installying bitsandbytes, choose version .35

Very good answer! 
In the set up choose option 3 for installying bitsandbytes, choose version .35 ---- it solve my problem!

**Comment by bstuart999** [comment]
> try this:
> 
> to go the folder venv/scripts/ and in a cmd do: "activate" to activate the venv And then type in: pip install bitsandbytes-windows
> 
> If that doesnt work, in the set up choose option 3 for installying bitsandbytes, choose version .35

This works. What a nightmare to try and figure out.

**Comment by Totoro51212** [comment]
Fixed my problem, but now the training is going ridiculously slow and my generated LoRa was 2GB for some reason. It also did not seem to do anything whatsoever. I will be attaching my config file for anyone that can double check my settings, I did 2500 total steps with 25 images. I am considering using the portable version or Onetrainer.
[Config1.json](https://github.com/bmaltais/kohya_ss/files/13624239/Config1.json)

**Comment by aidenli** [comment]
> try this:
> 
> to go the folder venv/scripts/ and in a cmd do: "activate" to activate the venv And then type in: pip install bitsandbytes-windows
> 
> If that doesnt work, in the set up choose option 3 for installying bitsandbytes, choose version .35

It works！Thank you!
