### ISSUE TITLE
Kohya's WD14 Captioning is Not Outputting .txt Files

### ISSUE THREAD

**Issue by WhiteHorns** [bmaltais/kohya_ss#1742]
Below is a screenshot. I've tried several solutions that have worked for other but I've had no luck. I guess it's best to start at square 1 again.

![Screenshot 2023-12-06 074558](https://github.com/bmaltais/kohya_ss/assets/153089368/1383c7e4-f1a9-4a26-b8fc-0cb3fce5b6b2)

**Comment by WhiteHorns** [comment]
UPDATE: I went into my kohya_ss folder, and started the setup.bat file. I chose option 3 (Install specific bitsandbytes versions). Then I chose the first option (Force installation of bitsandbytes 0.35.0). I then returned to my open Kohya instance, went to the WD14 Captioning, selected my folder containing the images, ran it, and I now have .txt files in that folder. However, the captions are not as specific as I've seen in other videos but I now have .txt files. I'm trying the other versions of bitsandbytes.
![image](https://github.com/bmaltais/kohya_ss/assets/153089368/27a0c55e-6061-4322-aaca-a53f353b3788)

**Comment by WhiteHorns** [comment]
Nevermind, it's not working anymore after re-installing Kohya...

**Comment by bmaltais** [comment]
I just tried it on my system with BNB 0.41.0 and it worked fine. Not sure why you are getting an error. I wish things we easy to troubleshoot but with python there are so many things that can go wrong.

**Comment by WhiteHorns** [comment]
I finally got it working. I deleted the venv folder, re-ran setup.bat and installed Kohya_ss gui.

![image](https://github.com/bmaltais/kohya_ss/assets/153089368/831bb608-202a-4522-b47d-92148afc6069)

![image](https://github.com/bmaltais/kohya_ss/assets/153089368/e2115e36-e801-438c-a16b-f904af9d768e)

Then I went into Kohya, and clicked "caption images" to which I got the following back...

![image](https://github.com/bmaltais/kohya_ss/assets/153089368/f9a6d789-e390-4885-88de-a58dff685a2a)

![image](https://github.com/bmaltais/kohya_ss/assets/153089368/5b32a6e4-4e90-4fbb-857b-7c2a84c0a97d)

**Comment by bmaltais** [comment]
Success. Yeah, sometimes the vent modules get messed up and deleting it and reinstalling everything is the only solution.

**Comment by adrianfiedler** [comment]
I have the same problem, no captions created. I deleted venv and reinstalled mutliple times. Still not working

**Comment by Eugeniusz-Gienek** [comment]
Unfortunately didn't help me as well...
