### ISSUE TITLE
Diag-OFT performance issue

### ISSUE THREAD

**Issue by iqddd** [bmaltais/kohya_ss#1747]
LoRA Diag-OFT is trained 2-2.5 times slower (s/it) than conventional LoRA/LoCon. Moreover, intermediate preview samples are also generated 2-2.5 times slower when Diag-OFT is trained.
I just want to know if anyone has encountered the same problem, or if I'm the one messed up somewhere.

**Comment by bmaltais** [comment]
I tried training it when I implemented the code and it was also slower for me… but since I could not make use of it in ComfyUI I moved on and I have not spent much time training with it to really compare.

**Comment by Simwake** [comment]
I also find that using Diag-OFT is three times slower than using regular LoRa in a1111 webui
