### ISSUE TITLE
Everytime I run upgrade.psl it redownloads xformers though it has the right version

### ISSUE THREAD

**Issue by riade3788** [bmaltais/kohya_ss#175]

**Comment by bmaltais** [comment]
Yes, I know, it is also annoying me. I will need to investigate. If someone know why and has a suggestion to fix it please let me know.

**Comment by riade3788** [comment]
now the xformers in stable diffusion doesn't work and I have to reinstall it
also, the installation leaves a huge cache in pip folder in app data folder

**Comment by riade3788** [comment]
> 

can you link blip also so I don't have to redownload it
