### ISSUE TITLE
What models exist for captions and where can I find them and how to add them?

### ISSUE THREAD

**Issue by WagnerFighter** [bmaltais/kohya_ss#1756]
What models exist for captions and where can I find them and how to add them?

For a large pack of portrait photos of different people, standard captions recognize photos with severe errors and incompleteness. need a model for a 16gb video card
![Screenshot_1](https://github.com/bmaltais/kohya_ss/assets/121365756/27b374c1-7f62-4a65-8702-60bc78b158aa)

**Comment by DKnight54** [comment]
Try this tool by Talmendo
https://github.com/Talmendo/blip2-for-sd
Be warn, willingness to mess around in Linux or WSL may be required to get it running.

I had to use WSL to get it to run on my 10gb VRAM card
