### ISSUE TITLE
LCM converter script

### ISSUE THREAD

**Issue by KarelAI** [bmaltais/kohya_ss#1760]
Please add a section in utilities for the lcm-convert.py script.

https://github.com/vladmandic/automatic/blob/master/cli/lcm-convert.py

**Comment by bmaltais** [comment]
A custom conversion script and the GUI for it is now in the dev2 branch for testing.

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/abc43b0b-9be9-408e-929a-625bcd152f4e)

Give it a try.
