### ISSUE TITLE
Dataset preparation script copies recursively until disk full if source and target folder are identical

### ISSUE THREAD

**Issue by DudeWhoNeedsAGit** [bmaltais/kohya_ss#1761]
Just installed fresh this week. On Windows 11.

1. Start UI
2. Go to either Tab Dreambooth/LoRa 
3. Select subTab Dataset preparation
4. Fill in instance prompt / class prompt
5. Image source folder is kohya_input/img
6. Reg Image source folder is kohya_input/reg
7. Target folder destination is kohya_input

Click "Prepare Training Data"

This will do two things, copy the contents of the img folder recursively into itself appending the path "<repeats>_instance_prompt/img<repeats>_instance_prompt/img"

with the images as well, for me it stopped around 90GB with only 200MB image files. Even more annoying is that it re-writes it even when deleted. Deleted the folder 5-6 times it kept reappearing. I shutdown the server but it seemed the command kept running.

WinDirStar didnt even show the disk usage just "Unknown" even as admin.

Could only find it with TreeSizeFree. But even there deleting did not work, had to remove it manually using powershell.

**Comment by bmaltais** [comment]
Yeah... that code is finnyky. If someone care to rewrite I will gladly take a PR for it. Any taker?
