### ISSUE TITLE
LR scheduler extra arguments

### ISSUE THREAD

**Issue by MortalSage** [bmaltais/kohya_ss#1762]
I have multiple issues with how the lr_scheduler_args work currently.
I'm unable to pass args by simply writing them in.
The only way to pass args is to pass an extra --lr_scheduler_args="milestones=[10,80]" in the args field (see attached image).

Also I can pass only one arg, any more and I get this:
Traceback (most recent call last):
  File "A:\kohya_ss\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "A:\kohya_ss\train_network.py", line 370, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "A:\kohya_ss\library\train_util.py", line 3659, in get_scheduler_fix
    key, value = arg.split("=")
ValueError: too many values to unpack (expected 2)

I can see that it has issues seperating the args with the arg.split("=") command, I guess it's because I'm giving it multiple "=" when I pass more than 1 arg.

So for short, these are the issues I noticed:
1: The lr_scheduler_args field is not working, it just dumps the text, and has no way to pass args itself.
2: It cannot pass more than 1 arg.
3. I'm also missing schedulers, I was able to get the MultiStepLR to work, but I had to pass it through the argument field (see attached image).

![Screenshot 2023-12-12 005940](https://github.com/bmaltais/kohya_ss/assets/147339248/a1aa7bad-d943-45b3-92ea-5e163d25aed8)
This is literally the only way that actually started to train.

**Comment by MortalSage** [comment]
Maybe this also helps, this is how it parses the field:
![Screenshot 2023-12-12 010830](https://github.com/bmaltais/kohya_ss/assets/147339248/315b546d-2c21-4885-b8ce-fed0c8cb9f53)
If I do not add another --lr_scheduler_args, the original one stays separate, and milestones is thrown in on it's own.

**Comment by MortalSage** [comment]
I tried almost all combinations and I think it's impossible to pass more than one value inside an argument using the current code. 
I see that --lr_scheduler_args is designed to carry more than one string, but if I use the correct syntax for that:
`--lr_scheduler_args=["milestones=[1,10,30,50]", "gamma=0.1"]`
It correctly writes into the console:
`accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --v2 --v_parameterization --enable_bucket ... --lr_scheduler_args=["milestones=[1,10,30,50]", "gamma=0.1"] ...`
But I get an error: 
`train_network.py: error: unrecognized arguments: gamma=0.1]`
And:
`subprocess.CalledProcessError: Command '['A:\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--v2', '--v_parameterization', '--enable_bucket', ..., '--lr_scheduler_args=[milestones=[1,10,30,50],', 'gamma=0.1]', ...]' returned non-zero exit status 2.`
Which obviously means that it did not get that I want to pass two arguments at all. It just cuts gamma into a separate arg.
So no, I do not know what syntax needs to be output, as I have not found a working one. 

Currently the only solution I could think of is to pass all scheduler args in one string (which actually works) and split it manually into substrings inside of `get_scheduler_fix()` in `train_util.py` before feeding it into the key/value split loop. This would circumvent the need to pass multiple args using argparse, which I cannot get to work.

**Comment by bmaltais** [comment]
So this is something kohl’s would need to fix in his code before I can merge his update in mine. I think you should raise this issue directly in his repo so he can fix it properly.

**Comment by MortalSage** [comment]
I have no idea which other repo you mean. The accelerate repo, but thats owned by jxysoft?

**Comment by bmaltais** [comment]
Oh, sorry, this one: https://github.com/kohya-ss/sd-scripts

**Comment by bmaltais** [comment]
I think it would be possible to use the GUI as it to enter the parameters… I will have to test it…

**Comment by bmaltais** [comment]
OK, Confirmed, the GUI work as is... 1st, enter the custom scheduler choice like this:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/b635835d-8169-41b0-92f8-8962047d7e79)

then provide the supported scheduler parameters like this:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/9e1188c5-8802-45b3-a48c-c4930ab28fad)

**Comment by rafstahelin** [comment]
Hi @bmaltais 
I am on dev branch. I tried this LR scheduler extra arguments 
"milestones=[1,5,10]" "gamma=0,1" with constant scheduler but didnt work
Is there an issue with sd-scripts.? This was a few months ago. 
Cosine Annealing does work. Thanks

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/917c2a48-aee0-4120-970d-25b3b2189ef2)

**Comment by rafstahelin** [comment]
maybe this broke because now you have LR scheduler type, which only gives "cosine annealing" as dropdown option? @bmaltais

**Comment by DarkAlchy** [comment]
File "F:\kohya_ss-24.2.0\sd-scripts\library\train_util.py", line 4330, in get_scheduler_fix
    initial_lr = float(name.split(":")[1])
ValueError: could not convert string to float: 'None'

I am on the dev branch as well and nothing I do fixes this error.
