### ISSUE TITLE
AdamW8bit no longer works after bitsandbytes  0.41.1

### ISSUE THREAD

**Issue by brianiup** [bmaltais/kohya_ss#1766]
If you install the newer bitsandbytes  0.41.1 AdamW8bit scheduler will no longer work, reverting back to 0.40.1 it will work. If you try to train a 1.5 Model LoRA with AdamW8bit scheduler set it will produce an error that specifies it can not find the scheduler specified in the location library\train_util.py", line 3444, in get_optimizer

**Comment by kyeno** [comment]
I can confirm.
More than that: Neither `AdamW` nor `AdamW8bit` work. I had to use `Adafactor`.

**Comment by kyeno** [comment]
`Lion8bit` is broken as well.

**Comment by YuPr0** [comment]
Yup, not working with AdamW / AdamW8bit or Adafactor for me. Had to end up using Lion

**Comment by TheZaind** [comment]
if youre on windows and want to use the adam8bit, change in the "requirements_windows_torch2.tx"t the "bitsandbytes==0.41.1 # no_verify" to "bitsandbytes-windows". Worked for me! it can be that you need to delete the bitsandbytes folder from the venv.
