### ISSUE TITLE
UnboundLocalError: local variable 'release' referenced before assignment

### ISSUE THREAD

**Issue by seanbetts** [bmaltais/kohya_ss#1774]
When trying to run .gui.sh for the first time I get the following Traceback:

```
/Users/xxx/Documents/AI/Kohya/kohya_gui.py:136 in <module>
135
❱ 136     UI(
137         username=args.username,

/Users/xxx/Documents/AI/Kohya/kohya_gui.py:40 in UI
39     interface = gr.Blocks(
❱ 40         css=css, title=f"Kohya_ss GUI {release}", theme=gr.themes.Default()
41     )
```

I'm trying to run the on an M1 Max Mac Studio with macOS Sonoma 14.2

**Comment by bqxiao123** [comment]
the same problem to me

**Comment by mattpaulhus** [comment]
I was able to get this to work by replacing the semi-file path one or two lines above with the full file path.  
The if os.path.exists(partial_path) --> if os.path.exists(full_path).  
There's about 6-7 more of these updates I had to do as it's not the only issue.  But I was able to finish with replacing partial with full file paths to get through the whole way and run and view the Kohya GUI.

**Comment by seanbetts** [comment]
> I was able to get this to work by replacing the semi-file path one or two lines above with the full file path. The if os.path.exists(partial_path) --> if os.path.exists(full_path). There's about 6-7 more of these updates I had to do as it's not the only issue. But I was able to finish with replacing partial with full file paths to get through the whole way and run and view the Kohya GUI.

I found it easier just to add the following to the start of the UI function:

```
release = ""
README = ""
```

**Comment by mattpaulhus** [comment]
> > I was able to get this to work by replacing the semi-file path one or two lines above with the full file path. The if os.path.exists(partial_path) --> if os.path.exists(full_path). There's about 6-7 more of these updates I had to do as it's not the only issue. But I was able to finish with replacing partial with full file paths to get through the whole way and run and view the Kohya GUI.
> 
> I found it easier just to add the following to the start of the UI function:
> 
> ```
> release = ""
> README = ""
> ```

Thanks.  I was very close to going that option too but found that adjusting the file path worked for me, so I went ahead with that route.

**Comment by mraiser** [comment]
> I found it easier just to add the following to the start of the UI function:

I found it easier to create a file named '.release' at the root of the project. Makes updating from git easier, too.
