### ISSUE TITLE
Windows users error: ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

### ISSUE THREAD

**Issue by luotinen** [bmaltais/kohya_ss#1775]
Error description: https://www.reddit.com/r/StableDiffusion/comments/17va89v/error_when_using_kohya_with_modulenotfounderror/

Error message:
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

Fix by FeistyReindeer (source: :
"
I found the fix. Go to your venv/scripts/ and in a cmd do: "activate" to activate the venv
And then you need this: pip install bitsandbytes-windows
"

**Comment by dpappa** [comment]
It may just be better to choose a different optimizer instead of installing bitsandbytes-windows if you are using a gaming GPU.

Per this [comment](https://www.reddit.com/r/StableDiffusion/comments/17va89v/comment/k99c2ef/), and [reference](https://aituts.com/stable-diffusion-lora#training:~:text=On%2010XX%20GPUs,this%20to%20AdamW).

**Comment by luotinen** [comment]
Steps to reproduce
1. On a Windows machine, complete the installation instructions here: https://github.com/bmaltais/kohya_ss

Suggested fix:
1. On the "Troubleshooting" section of https://github.com/bmaltais/kohya_ss add:
Title: ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'
Text: Go to your venv/scripts/ and run activate: "cmd", "cd venv/scripts", "activate" . Then install bitsandbytes for windows: "pip install bitsandbytes-windows"

**Comment by adisloom** [comment]
v22.3.1 following all the installation steps. When I try to train a LoRA, I see this error in console.

**Comment by TheZaind** [comment]
You need to change your optimizer! The bitsnbytes version for kohya_ss dont support AddamW8Bit rieght now... For me now AdamW works, other say they can only use Adafactor! :)
