### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Sjbullis23** [bmaltais/kohya_ss#1776]
![Screenshot_1054](https://github.com/bmaltais/kohya_ss/assets/69125870/41d43295-0ffa-4c92-9dab-63472f5fdc0f)

**Comment by Sjbullis23** [comment]
![Screenshot_1055](https://github.com/bmaltais/kohya_ss/assets/69125870/c26dbdce-1010-4e3e-a7aa-1884861522eb)

**Comment by Firedan1176** [comment]
Try `pip install --upgrade --force-reinstall setuptools`
