### ISSUE TITLE
Collaboration?

### ISSUE THREAD

**Issue by d8ahazard** [bmaltais/kohya_ss#178]
Hey there...it's me again.

I'm just going around, reaching out to some of the other developers who've made awesome contributions to the Dreambooth training scene, inviting them to pop over to my discord to have a chat about the possibility of collaborating on one combined Dreambooth project, versus continuing to basically make the same thing with slightly different variations forever. ;)

If you're interested, I've got a discord over here where I'll be inviting some of the other devs to come and chat. It'd be awesome to talk with you and discuss how we can work together. ;)

https://discord.gg/q8dtpfRD5w

**Comment by bmaltais** [comment]
I believe I am already connected on the discord. The idea is interesting but we use different "engine" which make it a hard decision... Switch to another codebase vs stick with what you leverage... Well, in my case at least as I don't write the actual trainer code.

**Comment by d8ahazard** [comment]
> I believe I am already connected on the discord. The idea is interesting but we use different "engine" which make it a hard decision... Switch to another codebase vs stick with what you leverage... Well, in my case at least as I don't write the actual trainer code.

Well, that's the fun part.

My trainer code is *largely* based on Koyha's implementation, with some added stuff here and there. Or, it's like a hybrid of OG and yours. But I'm sure there have been added improvements on your side since then, and I'm sure I've done some things you could benefit from as well.

Even better - I'm presently working to completely ditch Auto1111 for my backend, and more or less write my own from scratch using just FastAPI and some bootstrap. This completely eliminates gradio, which I have grown to hate with a passion, as well as a lot of the things Auto1111 does that I have no use for.

In addition, my new master backend is designed from the ground-up to have a lot of features that could make it quite powerful in the future as new toys come into existence.

For example, the new UI is 100% modular. Each "module" you create has a python class that inherits from the base module and handles all of the stuff between the frontend and python. You can register webhook callbacks, create API endpoints, and design the corresponding js/css/html elements for the UI at the same time. 

Even better - I've got a base for an extension system started that works mostly like modules, but at the same time restricts the extension's abilities to mess with the underlying code of the application. 

I've also got working stand-ins for the neat gradio slider with number bar, a gallery that's a lot simpler than the gradio gallery/preview setup, and even an in-browser file explorer that only lets the user traverse a specified data directory, not the whole filesystem.

It's still very much a work-in-progress as I've only been writing it for like...three days now, but in that span of time, I've stood up a backend that's capable of running my dreambooth extension (albeit via API calls), and more or less all the pieces in place to make the rest of the UI modules.

Here's a screenshot of the very basic UI I've put together so far:

Gallery:

![image](https://user-images.githubusercontent.com/1633844/219225662-8ce5d151-3d97-42e2-923f-02786933c390.png)


Sample form with gradio ripoff sliders and a "modelSelect" element, which can be configured to auto-populate with any model type, as well as append listeners for changes, etc.

![image](https://user-images.githubusercontent.com/1633844/219225796-a3194c15-2b3e-4a66-a9fa-57715dff17f8.png)

In-browser file selector with options to select starting dir, show directories only, filter by file type, auto expand/hide...callbacks...

![image](https://user-images.githubusercontent.com/1633844/219225948-675b0a59-f211-4310-ada1-c08a387568ca.png)




So, the TL/DR version is - I'm starting something new, and it would be a great time to get other like-minded individuals onboard. ;)

**Comment by bmaltais** [comment]
Wow, look like you have done a lot of great work. It certainly sound like a much improved UI and user experience 

It would be interesting to see how easy it will be to port the current gradio based code to run under your framework.

I can say that gradio has been limiting and using a better solution is a positive thing 

Do you intend to do more than the training aspect or will this be focussed on providing tools to fine-tune models?

I will keep checking your discord to see when the code will be ready to work on integrating training features.

**Comment by d8ahazard** [comment]
> Wow, look like you have done a lot of great work. It certainly sound like a much improved UI and user experience
> 
> It would be interesting to see how easy it will be to port the current gradio based code to run under your framework.
> 
> I can say that gradio has been limiting and using a better solution is a positive thing
> 
> Do you intend to do more than the training aspect or will this be focussed on providing tools to fine-tune models?
> 
> I will keep checking your discord to see when the code will be ready to work on integrating training features.

The intention is to completely replace Auto1111...provide an entire modular ecosystem for training, inference, browsing images...whatever. 

As of a few days ago, the base framework can already load and run my Auto1111 extension via API. 

As of today, I think I've built the majority of the new framework required to build the UI to run training more or less the same as in gradio...at least in terms of functionality...and done so in a way where it's re-useable UI elements and calls, versus requiring a TON of js to make it work. Click a button, build some JSON that corresponds to my config (or user args for a script), send it to the websocket...track status...repeat.

We've started talks with a few other developers to work towards the same goal - if you feel like it, maybe pop into the discord tomorrow and message myself or arrow or ethan_ryu, they can add you to the private chat we've set up.

As we're building a new SD platform more or less from the ground up, it'd be awesome to discuss progress with anybody else involved as we're building it, versus trying to change or add something after the fact. I think I've got some pretty good ideas so far, but as I've already discovered, sometimes I just need a few suggestions to really make something kickass. So, the more the merrier.

Here's a ss of the latest UI stuff I've done - The progbar and status texts are one JS element you can just pipe data into via JSON and customize however you want (one bar, two bars, no bars).

The model select box is actually tied directly to the model handler, and has options to specify model type (including diffusion models), load model on change, add other change handlers, and filter by filetype if that's not enough.

Oh, and the entries in the sliding menu on the left are auto-populated by adding new directories to /modules or /extensions and editing a bit of code.

![image](https://user-images.githubusercontent.com/1633844/219532105-5335350f-10c4-48ca-9947-f4776bddfe44.png)
