### ISSUE TITLE
Issue running setup.bat

### ISSUE THREAD

**Issue by rafed1973** [bmaltais/kohya_ss#1786]
when running setup.bat I get the error
  **File "D:\Kohya\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "D:\Kohya\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'**

Can you help?
I am running the right version of python

**Comment by leito711** [comment]
bump

**Comment by mckaycheatham** [comment]
Having had the same issue myself, if you have a newer version of python installed, even if you have the right one installed too, setup fails at that point. In my case, I had python 3.12 as well (thanks Windows) and that was automatically selected for some reason even though I had a fresh install of 3.10.9. If you're certain that you only have python 3.10.9 installed, in the venv terminal right after the error, type `pip install setuptools` and hit enter and that fixes the immediate error.
