### ISSUE TITLE
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

### ISSUE THREAD

**Issue by marc-1212** [bmaltais/kohya_ss#179]
when I try to train Dreambooth LORA the trainning is not running and I've got this error:

**Comment by irigyano** [comment]
I had this issue when I tried importing config from other json file,
I think the issue is pathing from different PC,
Manually set the config might solve the problem.

**Comment by Tempaccnt** [comment]
someone already posted about this. jist disable 8bit adam and it should work

**Comment by bmaltais** [comment]
It is because your card does not support 8nit adam. As @Tempaccnt said you have to disable the option.

**Comment by ArmadstheDoom** [comment]
How exactly do you disable it? The only options are to use it, and there's no explanation as to what you're supposed to use if NOT 8bitadam which is the standard. Just any of the other ones? 

It's not a flag you can check/uncheck in the gui, you have to select one of 7 or so to use.

**Comment by bmaltais** [comment]
That is correct. The only optimizer that is 8bit Adam is the AdamW8bit. All other will not try to use 8bitadam.

**Comment by dpkirchner** [comment]
Anyone following up on this figure out how to disable 8bit adam?
