### ISSUE TITLE
Which file should I edit to log each step trained training images and regularization images names into a txt file?

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1791]
Hello. I want to personally log to a txt file in each step which training files and regularization images files are trained

Which file should I edit how for this purpose?

**Comment by aycaecemgul** [comment]
did you find a solution?

**Comment by FurkanGozukara** [comment]
> did you find a solution?

no but i used --debug to verify my thought. it is randomly training images instead of like training every image once in and repeating. so some images are trained more than others sadly

**Comment by aycaecemgul** [comment]
thanks, it sounds like it may cause overfitting with less reg image amounts.
