### ISSUE TITLE
SDXL dreambooth training samples stuck at 512x512 size

### ISSUE THREAD

**Issue by brentjohnston** [bmaltais/kohya_ss#1794]
I cannot find a way to change the SDXL dreambooth training samples to 1024x1024 size, they default to 512x512 and look nothing like the actual models when loading into automatic1111 and doing 1024x1024.

I'm not using buckets, so need exactly 1024x1024 samples. Does anyone know how I can edit this somewhere?

**Comment by pixelass** [comment]
As mentioned in the description:

![image](https://github.com/bmaltais/kohya_ss/assets/1148334/d4016866-39bd-4026-a593-ae61a84b0c1d)


You have to specify the size per sample

Here's and example:

```
A red apple on a wooden table --n worst quality --h 1024 --w 1024
```

- Prompt: A red apple on a wooden table
- Negative Prompt: worst quality
- Height: 1024
- Width: 1024


Here's and example with multiple sample images with different dimensions:

```
A red apple on a wooden table --n worst quality --h 1024 --w 1024

A cardinal sitting on a branch --n worst quality --h 1216 --w 832
```

**Comment by brentjohnston** [comment]
Thanks a lot! Apparantly I can't read.
