### ISSUE TITLE
Sample image generation while training is broken

### ISSUE THREAD

**Issue by randaller** [bmaltais/kohya_ss#1799]
generating sample images at step / サンプル画像生成 ステップ: 200
Traceback (most recent call last):
  File "D:\Dev\NN\github\pytorch\kohya_ss\train_db.py", line 495, in <module>
    train(args)
  File "D:\Dev\NN\github\pytorch\kohya_ss\train_db.py", line 370, in train
    train_util.sample_images(
  File "D:\Dev\NN\github\pytorch\kohya_ss\library\train_util.py", line 4452, in sample_images
    return sample_images_common(StableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "D:\Dev\NN\github\pytorch\kohya_ss\library\train_util.py", line 4551, in sample_images_common
    pipeline = pipe_class(
  File "D:\Dev\NN\github\pytorch\kohya_ss\library\lpw_stable_diffusion.py", line 526, in __init__
    super().__init__(
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'image_encoder'

**Comment by bmaltais** [comment]
Hummm... this is unfortunate... You might want to go back to the previous release and see if things are working there. It is possible one of the update is causing this behaviour...

**Comment by randaller** [comment]
It worked well in a release about week-two ago, sadly I'm accidentally typed "git pull" as used to be and got samples broken :)

**Comment by randaller** [comment]
A little addition, images generating well while training SDXL, but still fails for SD 1.5

**Comment by danielaixer** [comment]
I found a workaround the other day, but I think I forgot to post it, because I wrote a comment but I don't see it here...

Edit `kohya_ss/library/lpw_stable_diffusion.py`

Around line 512, comment both lines that mention `image_encoder`

```
    def __init__(
        self,
        vae: AutoencoderKL,
        text_encoder: CLIPTextModel,
        tokenizer: CLIPTokenizer,
        unet: UNet2DConditionModel,
        scheduler: SchedulerMixin,
        safety_checker: StableDiffusionSafetyChecker,
        feature_extractor: CLIPFeatureExtractor,
        #image_encoder: CLIPVisionModelWithProjection = None,  # Incluindo o image_encoder
        requires_safety_checker: bool = True,
        clip_skip: int = 1,
    ):
        self._clip_skip_internal = clip_skip
        super().__init__(
            vae=vae,
            text_encoder=text_encoder,
            tokenizer=tokenizer,
            unet=unet,
            scheduler=scheduler,
            safety_checker=safety_checker,
            feature_extractor=feature_extractor,
            #image_encoder=image_encoder,
            requires_safety_checker=requires_safety_checker,
        )
        self.__init__additional__()
```
