### ISSUE TITLE
Feature Request - flash-attention support

### ISSUE THREAD

**Issue by mediocreatmybest** [bmaltais/kohya_ss#18]
Hi!

Would be great to see some support for flash-attention (flash-attn in pip) as you already support xformers. 
My understanding is from using it on some other projects it can lower the vRAM requirements a little lower than xformers. 

https://github.com/HazyResearch/flash-attention

Thanks!

**Comment by bmaltais** [comment]
This would require modifications of the code maintained by kohya in his repo. You should ask him to implement them and once he does I will be able to wrap them with a GUI... Here is where he maintain the actual python code: https://github.com/kohya-ss/sd-scripts

**Comment by mediocreatmybest** [comment]
> This would require modifications of the code maintained by kohya in his repo. You should ask him to implement them and once he does I will be able to wrap them with a GUI... Here is where he maintain the actual python code: https://github.com/kohya-ss/sd-scripts

Awesome, will do :) 
Thanks.
