### ISSUE TITLE
"setup.bat" is not working and  install it manually doesn't not works

### ISSUE THREAD

**Issue by livie993** [bmaltais/kohya_ss#1813]
I've been trying to install Kohya_ss, but when I run .\setup.bat, it only shows 'findstr' is not recognized as an internal or external command operable program or batch file."

So I decided to try downloading it manually, following the instructions on https://github.com/bmaltais/kohya_ss/issues/589. However, when I open the GUI, it shows that it requires a new version of xformers and displays an error when installing the new version. After that, every time I try to open the GUI, it just keeps crashing. Is there any way to solve this issue? I've been uninstalling and reinstalling for three hours.

**Comment by LeF0URBE** [comment]
open with notepad the setup.bat file and delete the 4 first lines (after @echo off) that  serve to verify your Python version.
with that out of the way you should be able to run the setup.
i had the " "findstr" not recognized" before due to this trivial non necessary verification today.

**Comment by FurkanGozukara** [comment]
uninstall all python and install as shown exactly here

[**Essential AI Tools and Libraries: A Guide to Python, Git, C++ Compile Tools, FFmpeg, CUDA, PyTorch**](https://youtu.be/-NjNy7afOQ0)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/uSxPD2Yav4JlLEAHQE5Dr.png)](https://youtu.be/-NjNy7afOQ0)
