### ISSUE TITLE
Model fails to train and execute

### ISSUE THREAD

**Issue by labelhigh** [bmaltais/kohya_ss#182]
![2023-02-16 17 07 35](https://user-images.githubusercontent.com/1137748/219319535-d4841c26-02df-4d9a-9ce9-31e5e4be4ce8.jpg)
I am not sure if I am making a mistake somewhere in the installation.  The tool does not seem to be able to proceed.
Has anyone encountered this problem?

**Comment by lashombpLQCD** [comment]
I'm experiencing the same problem.

**Comment by labelhigh** [comment]
I later solved this problem. When installation to the end, there will be a few questions to answer. At this time, pay special attention to the answer, otherwise the installation will not be successful.

**This machine  		        -->Enter
**No distributed training  	-->Enter
**No			                -->Enter
**No			                -->Enter
**No			                -->Enter
**all			                        -->Enter
**fp16			                -->Enter

It depends on your computer's device to determine the option

**Comment by lashombpLQCD** [comment]
That's what I was missing. Thanks! Appreciate it.
