### ISSUE TITLE
no support for dynamic naming for wandb run sessions

### ISSUE THREAD

**Issue by nirweingarten** [bmaltais/kohya_ss#1823]
In run time users can only control the name of the wandb project, but cannot control the name of the session (without editing the log_tracker_config file).
Users need to give runs specific names with timestamps and hyper parameters.

**Comment by hopl1t** [comment]
I've written a small fix for this and would love to contribute and open a PR, but I can't push the new branch. Could I get permissions please? Thanks :)

`ubuntu@ip-172-31-29-35:~/kohya_ss$ git diff origin
diff --git a/library/train_util.py b/library/train_util.py
index 3c85001..fd6537a 100644
--- a/library/train_util.py
+++ b/library/train_util.py
@@ -2941,6 +2941,12 @@ def add_training_arguments(parser: argparse.ArgumentParser, support_dreambooth:
         default=None,
         help="path to tracker config file to use for logging / ログ出力に使用するtrackerの設定ファイルのパス",
     )
+    parser.add_argument(
+        "--wandb_run_name",
+        type=str,
+        default=None,
+        help="The name of the specific run to be shown in wandb log / wandb ログに表示される特定の実行の名前",
+    )
     parser.add_argument(
         "--wandb_api_key",
         type=str,
diff --git a/train_network.py b/train_network.py
index 9cba78d..5e022e2 100644
--- a/train_network.py
+++ b/train_network.py
@@ -686,6 +686,8 @@ class NetworkTrainer:
             init_kwargs = {}
             if args.log_tracker_config is not None:
                 init_kwargs = toml.load(args.log_tracker_config)
+            if args.wandb_run_name:
+                init_kwargs['wandb'] = {'name': args.wandb_run_name}
             accelerator.init_trackers(
                 "network_train" if args.log_tracker_name is None else args.log_tracker_name, init_kwargs=init_kwargs
             )`
