### ISSUE TITLE
Pause and resume training?

### ISSUE THREAD

**Issue by rendomnet** [bmaltais/kohya_ss#1824]
Is there any way to pause and resume lora training?

**Comment by FiveSaix** [comment]
You can use the advanced option, and click save training state, then you can resume from there. 

Then use Resume from saved training state. load the latest file, and start training again.

**Comment by OriginLive** [comment]
it would be nice to have a pause button, and resume, much easier

**Comment by ataylorm** [comment]
> > You can use the advanced option, and click save training state, then you can resume from there.
> > Then use Resume from saved training state. load the latest file, and start training again.
> 
> Could you please elaborate on this; I got the "Save training state" checked, but where is it saved? "Resume from saved training state" asks for a file path, what do I need to select here?
> 
> I tried selecting the latest folder which is created under "log" folder, did not work. I tried adding the file at the end which is something like "events.out.tfevents.1729066174.DESKTOP-8KBN6C.15052.0" but did not work. What folder should I select?
> 
> Also, does this option allow to continue exactly where it left? Like for example, If I had stopped training and quit Kohya on the 2nd epoch's 300th step, will it continue from there or start the steps from start?

Did you ever get an answer to this?

**Comment by Wernervanrun** [comment]
The log folder is used for Tensorboard, it is the location where the loss data is stored. The training state folders are stored inside the folder you choose for "Output directory for trained model".
