### ISSUE TITLE
not able to install, Windows 11

### ISSUE THREAD

**Issue by Shadeling3D** [bmaltais/kohya_ss#1833]
Hello and happy new year! I'm having a lot of trouble installing Kohya ss and was wondering if you can point me in the right direction. I've tried multiple times with the git method and installer by Aitrepreneur. everytime I get the same error every time during setup: See image attached

I have Python v3.10.9 properly installed with no problems running comfy, SDXL, and diffexDesktopUIFor_v143.    any suggestions?

Razor Blade 15 base, maxed out ram, 2TB SSD

![setup](https://github.com/bmaltais/kohya_ss/assets/32183085/59fdd07c-1c38-4603-a7a3-f3dfd0a16b50)

**Comment by FurkanGozukara** [comment]
uninstall all python and install exactly as shown here

[**Essential AI Tools and Libraries: A Guide to Python, Git, C++ Compile Tools, FFmpeg, CUDA, PyTorch**](https://youtu.be/-NjNy7afOQ0)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/uSxPD2Yav4JlLEAHQE5Dr.png)](https://youtu.be/-NjNy7afOQ0)

**Comment by Shadeling3D** [comment]
Thank you so much, that did the trick :)
![Screenshot 2024-01-07 163852](https://github.com/bmaltais/kohya_ss/assets/32183085/7b1b4090-3fe3-44f3-a8e8-16bbdf27073c)
