### ISSUE TITLE
I don't find the lora safetensors file after training, I only find the json file

### ISSUE THREAD

**Issue by aigoar** [bmaltais/kohya_ss#1845]
22:49:40-280267 INFO     Loading config...
22:50:50-535059 INFO     Start training LoRA Standard ...
22:50:50-536055 INFO     Checking for duplicate image filenames in training data directory...
22:50:50-538054 INFO     Valid image folder names found in: C:/Users/Ghost/Downloads/goku/lora goku/image
22:50:50-540055 INFO     Folder 100_goku: 20 images found
22:50:50-541054 INFO     Folder 100_goku: 2000 steps
22:50:50-541054 INFO     Total steps: 2000
22:50:50-542055 INFO     Train batch size: 2
22:50:50-543054 INFO     Gradient accumulation steps: 1
22:50:50-544054 INFO     Epoch: 1
22:50:50-545055 INFO     Regulatization factor: 1
22:50:50-546055 INFO     max_train_steps (2000 / 2 / 1 * 1 * 1) = 1000
22:50:50-547054 INFO     stop_text_encoder_training = 0
22:50:50-548003 INFO     lr_warmup_steps = 0
22:50:50-548763 INFO     Saving training config to C:/Users/Ghost/Downloads/goku/lora
                         goku/model\goku_20240105-225050.json...
22:50:50-550763 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py"
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="C:/Users/Ghost/Downloads/goku/lora goku/image" --resolution="512,512"
                         --output_dir="C:/Users/Ghost/Downloads/goku/lora goku/model"
                         --logging_dir="C:/Users/Ghost/Downloads/goku/lora goku/log" --network_alpha="128"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=128 --output_name="goku" --lr_scheduler_num_cycles="1"
                         --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2"
                         --max_train_steps="1000" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="1" --clip_skip=2
                         --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\Ghost\Downloads\goku\lora goku\image\100_goku contains 20 image files
2000 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Ghost\Downloads\goku\lora goku\image\100_goku"
    image_count: 20
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: goku
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 3631.12it/s]
prepare dataset
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 15.73it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable xformers for U-Net
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  5.86it/s]
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "D:\sd\مجلد جديد\kohya\kohya_ss\library\train_util.py", line 3480, in get_optimizer
    import bitsandbytes as bnb
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\sd\مجلد جديد\kohya\kohya_ss\train_network.py", line 996, in <module>
    trainer.train(args)
  File "D:\sd\مجلد جديد\kohya\kohya_ss\train_network.py", line 348, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\sd\مجلد جديد\kohya\kohya_ss\library\train_util.py", line 3482, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Ghost\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ghost\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\sd\مجلد جديد\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd\\مجلد جديد\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/Ghost/Downloads/goku/lora goku/image', '--resolution=512,512', '--output_dir=C:/Users/Ghost/Downloads/goku/lora goku/model', '--logging_dir=C:/Users/Ghost/Downloads/goku/lora goku/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=goku', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by aigoar** [comment]
![التقاط](https://github.com/bmaltais/kohya_ss/assets/122462312/15d1ee6c-6f7c-4ee7-8fcd-ae7c12a0cbb9)

**Comment by DKnight54** [comment]
The reason is because training failed and didn't run. In order to the AdamW8bit optimizer, you need to install bitsandbytes but in order to do it on a windows machine, you need to install a specific built/version.

Try using Adafactor instead

**Comment by aigoar** [comment]
> The reason is because training failed and didn't run. In order to the AdamW8bit optimizer, you need to install bitsandbytes but in order to do it on a windows machine, you need to install a specific built/version.
> 
> Try using Adafactor instead

How do I using adafactor?

**Comment by DKnight54** [comment]
Change this field to adafactor
![image](https://github.com/bmaltais/kohya_ss/assets/126916963/56e214bb-77f9-4cf9-a829-01425a8f8236)

**Comment by aigoar** [comment]
> Change this field to adafactor ![image](https://private-user-images.githubusercontent.com/126916963/294691273-56e214bb-77f9-4cf9-a829-01425a8f8236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NDk4OTMsIm5iZiI6MTcwNDU0OTU5MywicGF0aCI6Ii8xMjY5MTY5NjMvMjk0NjkxMjczLTU2ZTIxNGJiLTc3ZjktNGNmOS1hODI5LTAxNDI1YThmODIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNlQxMzU5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTNkYWRkNDJhODkwMDZjMjlhNjRiOGEwMDcyM2Y0ODMzMzYyMDYxNTEyZjJkZDA5NTJlNWMwZTlhNDBhMTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XruykMJlX8vMoZwka8FVGwOLnMhu56mCnArCkXjGixA)

It worked thanks

**Comment by KASUMIYUREN** [comment]
#

> 将此字段更改为 adafactor ![image](https://github.com/bmaltais/kohya_ss/assets/126916963/56e214bb-77f9-4cf9-a829-01425a8f8236)

bro，I followed your instructions to make changes, but I still don't have the safetensors file. Do you have any other solutions?

<img width="474" alt="Image" src="https://github.com/user-attachments/assets/e5e89d1b-ee80-46ed-bee6-074551056083" />
