### ISSUE TITLE
Configuration file doesnt load correctly on first try

### ISSUE THREAD

**Issue by stettler** [bmaltais/kohya_ss#1846]
When loading a LyCORIS/LoCon configuration file, some values are set incorrectly (for example "Network Rank" and "Network Alpha"). If loading again the same configuration file a 2nd time, then the values are set correctly. So we have to load 2 times the same configuration file to be sure that all values are set correctly.

This wasn't happening before.

**Comment by bmaltais** [comment]
Hi, yes, this is annoying. I need to track down why it does that... must be the logic that set the defaults that is causing the issue... frustrating.

**Comment by stettler** [comment]
The first time, when you load the configuration file, there is a message in the console saying that the "LoRA type changed".
The 2nd time, there is no such message.

Also, after you load the config for the first time, the parameters layout in the GUI is not the same as when you load the config a 2nd time.

Maybe it try to set the parameters before changing the type of LoRA first? So the parameters/fields don't match. Then it change the LoRA type so when you reload the configuration it's already the correct one and the parameters/fields match. That's just a wild
guess. I haven't checked what really happen :)

**Comment by bmaltais** [comment]
I will look I to it today, hopefully it will be easy enough to fix.

**Comment by bmaltais** [comment]
I think I found the issue, give the dev branch release a spin to confirm if it fixed the issue for you.

**Comment by stettler** [comment]
Yes, that seems ok, thanks!
