### ISSUE TITLE
Most recent version turned SD 1.5 lora trainings awfully slow

### ISSUE THREAD

**Issue by Charmandrigo** [bmaltais/kohya_ss#1847]
I post this because I had to revert to commit 9eb5da2 (22.1.1) after version 22.4.1 turned my trainings slow, my logs showed an extremely high it/s and a estimated time of 50 hours upon loading my usual .json parameters, my average trainings take only 1hr at least. This is on the Prodigy optimizer and a standard lora. 
I leave my last json sample which tested on the most recent version turned the trainings slow but on past versions were perfectly fast.
And I setup accelerate properly when updating so it wasn't any setting I did wrong.
[20231122-201122.json.zip](https://github.com/bmaltais/kohya_ss/files/13851486/20231122-201122.json.zip)

**Comment by bmaltais** [comment]
Strange… have you tried the latest dev branch version that include many updates from kohya?

git checkout dev
git pull

to return to the master branch:

git checkout master
git pull

**Comment by bmaltais** [comment]
I just tried your config and I get around 1.7it/s on my 3090... so really fast... what it/s (or s/it) do you get? I used the latest dev branch code for testing.

[koopa troopa.zip](https://github.com/bmaltais/kohya_ss/files/13853906/koopa.troopa.zip)

I have attached my testing dataset and config if you want to test with it.

**Comment by bmaltais** [comment]
I modified the training script to use lokr instead of standard and the results are much better:

![ComfyUI_04201_](https://github.com/bmaltais/kohya_ss/assets/7474674/96974de5-31b9-4331-9310-2c3c0e8a1849)
![ComfyUI_04202_](https://github.com/bmaltais/kohya_ss/assets/7474674/0130af66-a636-4a65-9a6c-6dc52a27116f)

**Comment by Charmandrigo** [comment]
I made a new test and it seem to have been fixed after removing the venv folder and installing it again. could have been a wrong package running but I am not sure.
Originally the training slowed down showed it was running at around 30it/s for some reason. I use a RTX 3070

**Comment by hanggun** [comment]
> I modified the training script to use lokr instead of standard and the results are much better:
> 
> ![ComfyUI_04201_](https://private-user-images.githubusercontent.com/7474674/294769598-96974de5-31b9-4331-9310-2c3c0e8a1849.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDc4MzUsIm5iZiI6MTcwNjUwNzUzNSwicGF0aCI6Ii83NDc0Njc0LzI5NDc2OTU5OC05Njk3NGRlNS0zMWI5LTQzMzEtOTMxMC0yYzNjMGU4YTE4NDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDU1MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I4OTk2MWMyMzA2OTNjMWVkMTQ4Zjg2OWFkM2VlMWU3MDI4ZDYyZmU1MDA5MTI4MjRiZDM0ZjQwN2I2ZWRmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lPrXSqkCHQflEUKbFwRYEvQR7jWs6lL_oJBgv9n8kn0) ![ComfyUI_04202_](https://private-user-images.githubusercontent.com/7474674/294769599-0130af66-a636-4a65-9a6c-6dc52a27116f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MDc4MzUsIm5iZiI6MTcwNjUwNzUzNSwicGF0aCI6Ii83NDc0Njc0LzI5NDc2OTU5OS0wMTMwYWY2Ni1hNjM2LTRhNjUtOWE2Yy02ZGM1MmEyNzExNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDU1MjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE3ZGE4NGY4MTFjM2RlMTNkMDcxZjUwODhhMDU1NjJlYmRhNTk5ODYyYjhjNzliZjNjYmEyYzY4Y2UxODhkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.M1SM9RSdpIEhXcq8CRwF2xocm69utAnRkKud3dSVoxk)

what is the lokr config?
