### ISSUE TITLE
Correct way of doing regularization and naming regularization images with this GUI

### ISSUE THREAD

**Issue by xuzihe2010** [bmaltais/kohya_ss#1849]
Thanks for sharing the tool and it is super useful for training SD models, LoRA and embeddings!

I have some questions regarding improving the quality of LoRA with regularization images. I have gone through some existing issues about regularization like this: https://github.com/kohya-ss/sd-scripts/issues/449, however, I still want to clarify some details.

I have seen some bloggers sharing their experience on using regularization to improve their LoRA, and some of them suggest to match the regularization image names with training images. For example, when training a LoRA of a certain person, if the training images are: some_body_1.png, some_body_1.txt (tags), some_body_2.png, some_body_2.txt (tags), ..., some_body_n.png, some_body_n.txt (tags), then define the regularization images like: some_body_1.png, some_body_2.png, ..., some_body_n.png (in the regularization folder) as well. The purpose of this is to tell the mapping between training images and reg image, e.g. which reg image to use for a given training image.

However, after quickly looking through the docs some high-level code, I'm not sure if the names of regularization images really matter. It seems to me that after enabling regularization, it doubles the training steps of each training image, and the choice of regularization image for a given training image is random (could be anyone from the pool of regularization images). Could you please clarify the logic of regularization and correct my understanding if it is wrong? I really appreciate it if you could shed some light on this.

Again, thank you very much for sharing this great tool with the community!

**Comment by anae-git** [comment]
As far as I know the filenames of the reg images don't matter at all. There are always a lot of myths floating around out there, and this seems to be another one.

**Comment by xuzihe2010** [comment]
Yeah, I didn't see any evidence that the reg image file names really matter, or there is any connection/mapping between individual training images and reg images in the implementation. Just try to confirm that. Thanks for the response!

**Comment by gesen2egee** [comment]
you can use --debug_dataset to find out mapping (it's just random)
