### ISSUE TITLE
Trying to convert an SD1.5 model to SD1.5 LCM and keep getting an error every time

### ISSUE THREAD

**Issue by AndreyRGW** [bmaltais/kohya_ss#1852]
```
17:40:34-546865 INFO     ./venv/Scripts/python.exe "tools\lcm_convert.py" --name
                         "C:/sdmodel/aZovyaRPGArtistTools_v4_LCM.safetensors" --model
                         "F:/WBC/automatic1111_dev/models/Stable-diffusion/aZovyaRPGArtistTools_v4.safetensors"
                         --lora-scale 1
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
F:\WBC\kohya_ss\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
The config attributes {'skip_prk_steps': True} were passed to LCMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
F:\WBC\kohya_ss\venv\lib\site-packages\diffusers\loaders\lora.py:952: FutureWarning: `fuse_text_encoder_lora` is deprecated and will be removed in version 0.25. You are using an old version of LoRA backend. This will be deprecated in the next releases in favor of PEFT make sure to install the latest PEFT and transformers packages in the future.
  deprecate("fuse_text_encoder_lora", "0.25", LORA_DEPRECATION_MESSAGE)
17:41:06-667706 INFO     Saving file...
17:41:06-672816 ERROR    An error occurred: 'StableDiffusionPipeline' object has no attribute 'text_encoder_2'
17:41:08-238326 INFO     Done extracting...

```

**Comment by AndreyRGW** [comment]
Strange that the script tries to find text_encoder_2 in StableDiffusionPipeline, even though it is only in StableDiffusionXLPipeline

**Comment by bmaltais** [comment]
Only work for SDXL models...

**Comment by AndreyRGW** [comment]
> Only work for SDXL models...

I wonder how [this model](https://civitai.com/models/253141/photographer-alpha7lcm?modelVersionId=285337) was converted then

**Comment by AndreyRGW** [comment]
> Only work for SDXL models...

@bmaltais 
Anyway, I figured out how to convert models to LCM. Take [this script](https://github.com/vladmandic/automatic/blob/master/cli/lcm-convert.py) it converts a regular SD1.5 (and not only 1.5) to LCM Diffusers, and then just use your script "tools/convert_diffusers20_original_sd.py" --v1 --fp16 to convert from Diffusers to Safetensors. Profit!

**Comment by kuzman123** [comment]
@bmaltais you should spend some time to learn what your forked repo can do

**Comment by larinius** [comment]
There's no need to "convert" anything. This script simply loads the default LCM LoRA and saves the checkpoint to a new file. You can directly use the LCM LoRA with a weight of 1.0 along with the LCM scheduler to get the exact same results, with the model performing well on low CFG and fewer steps. Generation time remains the same, with only a slight delay for loading the LoRA.

However, the final image quality of these "converted" models seems to be lower than models actually trained with LCM settings.

Example: 15 steps, CFG 1, Deliberate 2, 36 sec on CPU.

![image](https://github.com/user-attachments/assets/05089505-05ca-40ba-be3f-8f661ebc9844)
