### ISSUE TITLE
Mean ar error (without repeats)

### ISSUE THREAD

**Issue by crapthings** [bmaltais/kohya_ss#1856]
<img width="703" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/1147704/175694b2-2245-483c-b129-fd91bcacbdd0">

mean ar error (without repeats): 0.00029235223036407505

well this error impact train result?

**Comment by sleepyMMp** [comment]
check Mixed precision or save precision.  In my case, my gpu doesn't support bf16, select fp16.
