### ISSUE TITLE
Overtrains on regularization images

### ISSUE THREAD

**Issue by okageblade** [bmaltais/kohya_ss#186]
As the title says, the GUI heavily overtrains on regularization images even at the ratio of 100 repeats of 1200 images of the concept to train compared to 1 repeat of 350 regularization images to train. The output of a person concept far more resembles the reg images than the person it was supposed to be trained on.

![image](https://user-images.githubusercontent.com/115046565/219603095-6410068f-697f-4135-b410-3e4561a0cf22.png)

**Comment by mykeehu** [comment]
In this case, the Prior loss weight should be reduced to around 0.2-0.3. The lower the value, the more it will stick to the original images.
