### ISSUE TITLE
Every time same error during training: any idea?

### ISSUE THREAD

**Issue by marcotrani** [bmaltais/kohya_ss#1867]
14:19:58-177395 INFO     Version: v22.3.1

14:19:58-181683 INFO     nVidia toolkit detected
14:20:00-299575 INFO     Torch 2.0.1+cu118
14:20:00-320150 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:20:00-321151 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
14:20:00-322150 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
14:20:00-327150 INFO     Verifying modules installation status from requirements.txt...
14:20:02-600299 INFO     headless: False
14:20:02-605484 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
14:26:24-616939 INFO     Copy C:/ai/Kohya_Gui/images/prepared/150_sladjana to
                         C:/ai/Kohya_Gui/images/test1\img/40_sladjana woman...
14:26:24-672939 INFO     Regularization images directory is missing... not copying regularisation images...
14:26:24-673939 INFO     Done creating kohya_ss training folder structure at C:/ai/Kohya_Gui/images/test1...
14:29:10-973203 INFO     Start training LoRA Standard ...
14:29:10-974203 INFO     Checking for duplicate image filenames in training data directory...
14:29:10-976203 INFO     Valid image folder names found in: C:\ai\Kohya_Gui\images\img
14:29:10-977203 INFO     Folder 150_sladjana: 10 images found
14:29:10-978203 INFO     Folder 150_sladjana: 1500 steps
14:29:10-978203 INFO     Total steps: 1500
14:29:10-979203 INFO     Train batch size: 1
14:29:10-980203 INFO     Gradient accumulation steps: 1
14:29:10-981203 INFO     Epoch: 1
14:29:10-981203 INFO     Regulatization factor: 1
14:29:10-982203 INFO     max_train_steps (1500 / 1 / 1 * 1 * 1) = 1500
14:29:10-983203 INFO     stop_text_encoder_training = 0
14:29:10-984203 INFO     lr_warmup_steps = 150
14:29:10-985203 INFO     Saving training config to C:\ai\Kohya_Gui\images\mod\last_20240112-142910.json...
14:29:10-986203 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="C:\ai\Kohya_Gui\images\img" --resolution="512,512"
                         --output_dir="C:\ai\Kohya_Gui\images\mod" --logging_dir="C:\ai\Kohya_Gui\images\log"
                         --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora
                         --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=256 --output_name="last"
                         --lr_scheduler_num_cycles="1" --no_half_vae --learning_rate="0.0001" --lr_scheduler="cosine"
                         --lr_warmup_steps="150" --train_batch_size="1" --max_train_steps="1500"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="0"
                         --bucket_reso_steps=64 --bucket_no_upscale --noise_offset=0.0
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\ai\Kohya_Gui\images\img\150_sladjana contains 10 image files
No caption file found for 10 images. Training will continue without captions for these images. If class token exists, it will be used. / 10枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_1.png
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_10.png
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_2.png
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_3.png
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_4.png
C:\ai\Kohya_Gui\images\img\150_sladjana\Screenshot_5.png... and 5 more
1500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\ai\Kohya_Gui\images\img\150_sladjana"
    image_count: 10
    num_repeats: 150
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: sladjana
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 1666.59it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1500
mean ar error (without repeats): 0.0
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 15.86it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 10.47it/s]
create LoRA network. base dim (rank): 256, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder:
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\ai\Kohya_Gui\kohya_ss\library\train_util.py", line 3444, in get_optimizer
    import bitsandbytes as bnb
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ai\Kohya_Gui\kohya_ss\train_network.py", line 1012, in <module>
    trainer.train(args)
  File "C:\ai\Kohya_Gui\kohya_ss\train_network.py", line 342, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\ai\Kohya_Gui\kohya_ss\library\train_util.py", line 3446, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\Kohya_Gui\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "C:\ai\Kohya_Gui\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ai\\Kohya_Gui\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:\\ai\\Kohya_Gui\\images\\img', '--resolution=512,512', '--output_dir=C:\\ai\\Kohya_Gui\\images\\mod', '--logging_dir=C:\\ai\\Kohya_Gui\\images\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=256', '--output_name=last', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=150', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by DKnight54** [comment]
Try installing bitsandbytes (needed for 8 bit optimizers) first. Go to your sd-scripts folder and run the following from the command prompt:

```
.\venv\Scripts\activate
pip install bitsandbytes==0.35.0

cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bitsandbytes\cextension.py
cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py
```

Personally, I use the adafactor optimizer instead
