### ISSUE TITLE
No success with Controlnet Lllite

### ISSUE THREAD

**Issue by celticsha** [bmaltais/kohya_ss#1872]
I've tried sdxl_train_control_net_lllite.py several times with various different sets of images ranging from 2500-5000 pairs. The training always appears to be working, but whenever I try my model in the webui, it seems to have no effect on the final image that resembles what it's been trained to do.

I realise it's experimental, and was wondering if somebody with more experience than me could give me a few pointers please?

**Comment by kagevazquez** [comment]
I'm still trying to figure out the file structure myself.
