### ISSUE TITLE
Doing a Dreambooth with sdxl_train.py distributing memory across two GPUs to avoid out of memory errors

### ISSUE THREAD

**Issue by topological-modular-forms** [bmaltais/kohya_ss#1875]
I'm trying to train a Dreambooth using the following command on Kaggle:
```
!accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train.py" \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --train_data_dir="dataset/img" \
  --reg_data_dir="dataset/reg" \
  --output_dir="output" \
  --output_name="SDXLDreambooth" \
  --save_model_as="safetensors" \
  --train_batch_size=1 \
  --max_train_steps=3000 \
  --save_every_n_steps=1501 \
  --optimizer_type="adafactor" \
  --optimizer_args scale_parameter=False relative_step=False warmup_init=False \
  --xformers \
  --lr_scheduler="constant_with_warmup" \
  --lr_warmup_steps=100 \
  --learning_rate=5e-6 \
  --max_grad_norm=0.0 \
  --resolution="1024,1024" \
  --save_precision="fp16" \
  --save_n_epoch_ratio=1 \
  --max_data_loader_n_workers=1 \
  --persistent_data_loader_workers \
  --mixed_precision="fp16" \
  --full_fp16 \
  --logging_dir="logs" \
  --log_prefix="last" \
  --gradient_checkpointing \
  --caption_extension=".txt" \
  --no_half_vae \
  --cache_latents
```
and adding `--train_text_encoder` gives an out of memory error on a P100 GPU with 16 GB VRAM, even with all optimisations on. However, Kaggle provides the option of using two T4 GPUs with 16 GB VRAM each.

Is it possible to configure things (the script, DeepSpeed, accelerate, etc.) to make use of the 2 GPUs in a way that the memory the script needs is shared across the two T4s, instead of the default behaviour set by Kaggle where the 2 GPUs just process the training in parallel, running out of memory regardless?

**Comment by vhly** [comment]
1. I think if you training with 16GB, you should use SDXL LoRA method. with 8bit adapter for memory size.
2. I had training a SDXL LoRA Model with reg classes, it will use more than 23GB in One GPU.
3. I think the accelerate may be train model with the same script and share the settings, so If you have 2 GPU, 16GB + 8GB I think the 8GB can't run (it will load the same base model xlbase1.0 or vae or the same you images), If you have 2GPU 16GB + 40GB It the 16GB is bad.
4. the "--train_text_encoder" will increase memory usage, it will load text encoders(SDXL has 2 encoders), so each GPUs memory must more than 16GB

**Comment by Filarh** [comment]
Hi, could you please share your Kaggle notebook?

**Comment by topological-modular-forms** [comment]
Hi!

Here are some links to a sample notebook and some runs:

- [The notebook](https://www.kaggle.com/code/emilyyui/dreambooth-sdxl-example?scriptVersionId=161817873);
- [An OOM'd run with two 15 GB T4 GPUs](https://www.kaggle.com/code/emilyyui/dreambooth-sdxl-example/notebook);
- [A successful run with one 16 GB P100 GPU](https://www.kaggle.com/code/emilyyui/dreambooth-sdxl-example/notebook?scriptVersionId=161820873).

Neither of these have `--train-text-encoder` enabled, as it leads to an OOM error. Here's the memory utilization for the T4 GPUs:

![gpus](https://github.com/bmaltais/kohya_ss/assets/95149992/ee5ca047-c98b-4b0b-bea5-a68f319c5737)
