### ISSUE TITLE
Accidentally erased a lot of work because of one click

### ISSUE THREAD

**Issue by Xenodimensional** [bmaltais/kohya_ss#1883]
I accidentally clicked the prepare folder data button (when I had already done so) and the captions I'd spent an hour on were erased form the univewrse.

Do you think it might be possible to add a deletion prompt or just move files to the recycle bin to stop this from happening to someone else? 

It honestly seems baffling that this would be the default behaviour for any application.

**Comment by bmaltais** [comment]
I am really sorry. I need to look at this code and rewrite it. It was provided by a contributor a long time ago and I don’t quite like how it work. I might spend some time next weekend rewriting the thing so it is less dangerous.
