### ISSUE TITLE
Some error about CUDA in sdxl lora training

### ISSUE THREAD

**Issue by dabaonidetou** [bmaltais/kohya_ss#1886]
/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
steps:   0%|                                                                                                        | 2/4500 [00:02<1:42:24,  1.37s/it, avr_loss=0.0911]../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.

Traceback (most recent call last):
  File "/kohya_ss/sdxl_train_network.py", line 189, in <module>
    trainer.train(args)
  File "/kohya_ss/train_network.py", line 777, in train
    noise, noisy_latents, timesteps = train_util.get_noise_noisy_latents_and_timesteps(
  File "/kohya_ss/library/train_util.py", line 4482, in get_noise_noisy_latents_and_timesteps
    noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm.py", line 509, in add_noise
    sqrt_alpha_prod = alphas_cumprod[timesteps] ** 0.5
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

steps:   0%|                                                                                                        | 2/4500 [00:02<1:50:16,  1.47s/it, avr_loss=0.0911]

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sdxl_train_network.py', '--dataset_config=./config/dataset_config.toml', '--config_file=./config/config_file.toml']' returned non-zero exit status 1.

NVIDIA GeForce RTX 4090
CUDA Version: 12.2

**Comment by ea0hw33** [comment]
how did you solve it?

**Comment by ea0hw33** [comment]
> /usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants. warnings.warn( steps: 0%| | 2/4500 [00:02<1:42:24, 1.37s/it, avr_loss=0.0911]../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [0,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> 
> Traceback (most recent call last): File "/kohya_ss/sdxl_train_network.py", line 189, in trainer.train(args) File "/kohya_ss/train_network.py", line 777, in train noise, noisy_latents, timesteps = train_util.get_noise_noisy_latents_and_timesteps( File "/kohya_ss/library/train_util.py", line 4482, in get_noise_noisy_latents_and_timesteps noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps) File "/usr/local/lib/python3.10/dist-packages/diffusers/schedulers/scheduling_ddpm.py", line 509, in add_noise sqrt_alpha_prod = alphas_cumprod[timesteps] ** 0.5 RuntimeError: CUDA error: device-side assert triggered Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> steps: 0%| | 2/4500 [00:02<1:50:16, 1.47s/it, avr_loss=0.0911]
> 
> Traceback (most recent call last): File "/usr/local/bin/accelerate", line 8, in sys.exit(main()) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main args.func(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command simple_launcher(args) File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', 'sdxl_train_network.py', '--dataset_config=./config/dataset_config.toml', '--config_file=./config/config_file.toml']' returned non-zero exit status 1.
> 
> NVIDIA GeForce RTX 4090 CUDA Version: 12.2

how did you solve it?

**Comment by ea0hw33** [comment]
how did you solve it?
