### ISSUE TITLE
Error:(Optional) Install cudann file

### ISSUE THREAD

**Issue by sonisoniaaa** [bmaltais/kohya_ss#1893]
I got error when installing cudann file

1. Install kohya_ss gui
2. (Optional) Install cudann files (avoid unless you really need it)
3. (Optional) Install specific bitsandbytes versions
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

I choiced 2 and got error as followings

----------------------------------------
Enter your choice: 2

13:01:12-229900 INFO     Checking for CUDNN files in G:\sd\kohyabf241020\kohya_ss\venv\Lib\site-packages\torch\lib...
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ G:\sd\kohyabf241020\kohya_ss\setup\setup_windows.py:210 in <module>                                                  ││                                                                                                                      ││   209     setup_common.setup_logging()                                                                               ││ ❱ 210     main_menu()                                                                                                ││   211                                                                                                                ││                                                                                                                      ││ G:\sd\kohyabf241020\kohya_ss\setup\setup_windows.py:159 in main_menu                                                 ││                                                                                                                      ││   158         elif choice == "2":                                                                                    ││ ❱ 159             cudann_install()                                                                                   ││   160         elif choice == "3":                                                                                    ││                                                                                                                      ││ G:\sd\kohyabf241020\kohya_ss\setup\setup_windows.py:36 in cudann_install                                             ││                                                                                                                      ││    35                 else:                                                                                          ││ ❱  36                     shutil.copy2(src_file, cudnn_dest)                                                         ││    37             log.info("Copied CUDNN 8.6 files to destination")                                                  ││                                                                                                                      ││ C:\Users\■■■\AppData\Local\Programs\Python\Python310\lib\shutil.py:434 in copy2                                    ││                                                                                                                      ││    433         dst = os.path.join(dst, os.path.basename(src))                                                        ││ ❱  434     copyfile(src, dst, follow_symlinks=follow_symlinks)                                                       ││    435     copystat(src, dst, follow_symlinks=follow_symlinks)                                                       ││                                                                                                                      ││ C:\Users\■■■\AppData\Local\Programs\Python\Python310\lib\shutil.py:254 in copyfile                                 ││                                                                                                                      ││    253     else:                                                                                                     ││ ❱  254         with open(src, 'rb') as fsrc:                                                                         ││    255             try:                                                                                              │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯PermissionError: [Errno 13] Permission denied:
'G:\\sd\\kohyabf241020\\kohya_ss\\setup\\..\\cudnn_windows\\cudnn_windows'
----------------------------------------
(※■■■ is username)

I installed cuda_11.8.0 from NVIDIA.
Maybe I need to unistall it?

**Comment by kamichen1213** [comment]
the same problem
