### ISSUE TITLE
stuck on setup.bat help me, I even reinstalled Windows

### ISSUE THREAD

**Issue by dreamuddin** [bmaltais/kohya_ss#1899]
Kohya_ss GUI setup menu:

1. Install kohya_ss gui
2. (Optional) Install cudann files (avoid unless you really need it)
3. (Optional) Install specific bitsandbytes versions
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

Enter your choice: 1

02:10:17-262165 INFO     Version: v22.5.0

02:10:17-276175 INFO     Python 3.10.9 on Windows
02:10:17-276175 INFO     Installing modules from requirements_windows_torch2.txt...
02:10:17-276175 INFO     Installing package: torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
                         
                         
My cmd display is stuck there

**Comment by dreamuddin** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/131955492/08992462-44dc-495a-9821-b468fec537c4)

**Comment by daffatahtaa** [comment]
have you tried install the packages manually? So it'll be like this

before running setup.py run this 
>py -m venv venv

wait till finish, then write this on the same cmd
> venv\scripts\activate

make sure it look like this:
![image](https://github.com/bmaltais/kohya_ss/assets/43267539/1134cb72-6521-41b5-9692-09e8c9efed5f)

then you can install the package manually in your case it'll be
> pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 --index-url https://download.pytorch.org/whl/cu118
