### ISSUE TITLE
Lora Extract Error: RuntimeError: Error(s) in loading state_dict for CLIPTextModel

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#1901]
I extract Lora using SDXL base checkpoint using finetuned turbo fp16 model. 

I am getting the below error

<img width="878" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/64715158/ea146325-67d3-424c-976a-0e15ccb798ad">

`RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".`

Anybody know this errr

12:19:59-717133 INFO     ./venv/Scripts/python.exe "networks\extract_lora_from_models.py" --save_precision fp16
                         --save_to
                         "E:\ComfyUI_windows_portable\ComfyUI\ComfyUI\models\loras\SDXL_turbo_dim256_lora_fp16.safetenso
                         rs" --model_org
                         "E:\ComfyUI_windows_portable\ComfyUI\ComfyUI\models\checkpoints\SDXL_base.safetensors"
                         --model_tuned
                         "E:\ComfyUI_windows_portable\ComfyUI\ComfyUI\models\checkpoints\SDXL_turbo\SDXL_turbo_1.0_fp16.
                         safetensors" --dim 256 --device cuda --conv_dim 256 --sdxl --clamp_quantile 1.0 --min_diff 0.01
loading original SDXL model : E:\ComfyUI_windows_portable\ComfyUI\ComfyUI\models\checkpoints\SDXL_base.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
loading original SDXL model : E:\ComfyUI_windows_portable\ComfyUI\ComfyUI\models\checkpoints\SDXL_turbo\SDXL_turbo_1.0_fp16.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\networks\extract_lora_from_models.py:277 in <module>                                 │
│                                                                                                  │
│   274 │   parser = setup_parser()                                                                │
│   275 │                                                                                          │
│   276 │   args = parser.parse_args()                                                             │
│ ❱ 277 │   svd(args)                                                                              │
│   278                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\networks\extract_lora_from_models.py:64 in svd                                       │
│                                                                                                  │
│    61 │   │   )                                                                                  │
│    62 │   │   text_encoders_o = [text_encoder_o1, text_encoder_o2]                               │
│    63 │   │   print(f"loading original SDXL model : {args.model_tuned}")                         │
│ ❱  64 │   │   text_encoder_t1, text_encoder_t2, _, unet_t, _, _ = sdxl_model_util.load_models_   │
│    65 │   │   │   sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, args.model_tuned, "cpu"          │
│    66 │   │   )                                                                                  │
│    67 │   │   text_encoders_t = [text_encoder_t1, text_encoder_t2]                               │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:262 in load_models_from_sdxl_checkpoint                   │
│                                                                                                  │
│   259 │   │   elif k.startswith("conditioner.embedders.1.model."):                               │
│   260 │   │   │   te2_sd[k] = state_dict.pop(k)                                                  │
│   261 │                                                                                          │
│ ❱ 262 │   info1 = _load_state_dict_on_device(text_model1, te1_sd, device=map_location)  # rema   │
│   263 │   print("text encoder 1:", info1)                                                        │
│   264 │                                                                                          │
│   265 │   converted_sd, logit_scale = convert_sdxl_text_encoder_2_checkpoint(te2_sd, max_lengt   │
│                                                                                                  │
│ D:\kohya_ss\library\sdxl_model_util.py:158 in _load_state_dict_on_device                         │
│                                                                                                  │
│   155 │   if unexpected_keys:                                                                    │
│   156 │   │   error_msgs.insert(0, "Unexpected key(s) in state_dict: {}. ".format(", ".join('"   │
│   157 │                                                                                          │
│ ❱ 158 │   raise RuntimeError("Error(s) in loading state_dict for {}:\n\t{}".format(model.__cla   │
│   159                                                                                            │
│   160                                                                                            │
│   161 def load_models_from_sdxl_checkpoint(model_version, ckpt_path, map_location, dtype=None)   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".

**Comment by WarAnakin** [comment]
Yes, same error. This wasnt happening with the previous version of kohya_ss . I think something got screwed up, please revert the change or fix it. Until then i advise using the previous version of the software.
