### ISSUE TITLE
AttributeError: 'LokrModule' object has no attribute 'lokr_w1'. Did you mean: 'lokr_w1_a'?

### ISSUE THREAD

**Issue by hanggun** [bmaltais/kohya_ss#1909]
When I trained from standard to lokr, it cause this error, how to deal with it
![image](https://github.com/bmaltais/kohya_ss/assets/39485441/997f68b8-0006-4636-890e-10f1fa8dbfac)

**Comment by Goldenkoron** [comment]
Setting convolution rank and alpha to 0 I think fixed this for me.
