### ISSUE TITLE
Cant find another GPU

### ISSUE THREAD

**Issue by AdrianY0809** [bmaltais/kohya_ss#1912]
I have two graphics cards, one is a 4090 and the other is an A100. However, no matter which GPU ID I choose during the setup process, whether it's 0 or 1, the final result is always that the training runs on the 4090. Meanwhile, my A100 works fine in the web UI

![822938e7b95e451199f60b9f3d8b7daf](https://github.com/bmaltais/kohya_ss/assets/158061732/2875360f-e3dc-4c62-98a9-63e5b502007e)

**Comment by littleyeson** [comment]
I have same problem.Cannt change another Graphics card. how to fixed it?
