### ISSUE TITLE
How to use multiple GPUs for Kohya Dreambooth Training?

### ISSUE THREAD

**Issue by KarMa-31** [bmaltais/kohya_ss#1915]
I am using 2x gpus for training using Kohya(Dreambooth). But it is not utilizing both the gpus and instead only 1 gpu is being utilized.

I have tried following solutions:

1. added "export CUDA_VISIBLE_DEVICES=0,1" to gui.sh file of kohya_ss

2. added the parameters(hardcoded): "aceelerate launch --num_processes=2 --num_machines=1 --multi_gpus --gpu_ids=0,1 args..." in the run_cmd of dreambooth_gui.py. But on starting the training, it is mysteriously skipping the newly added parameters and in log file, shows the command used to run as "accelerate launch args...".

3. modified the config_files/accelerate where I set num_processes = 2 in default_config.yaml and runpod.yaml

Still somehow when I restart the training, only 1 gpu is being utilized. How can I solve this to use multiple gpu for training?

**Comment by AdrianY0809** [comment]
I have a similiar question , that i have 2 gpu but no matter which GPU ID I choose during the setup process, whether it's 0 or 1, the final result is always that the training runs on the first one .

**Comment by bmaltais** [comment]
The GUI does not support configuring multiple GPU. You will need to configure it by passing an extra parameter via the GUI to get it to work... I don't have multiple GPUs on my system so I have never used not tried to make it work. Hopefully someone with many GPU can answer.

**Comment by KarMa-31** [comment]
Yes, since GUI is not supporting multiple GPU, as I mentioned solution 2 above, I made changes to the "dreambooth_gui.py" code file. This must have some effect when I start training right?

As seen in this image, I added the required parameters on line 543 in "dreambooth_gui.py" file:
<img width="1342" alt="Screenshot 2024-01-31 at 12 29 52 PM" src="https://github.com/bmaltais/kohya_ss/assets/77107688/3ebddaf2-1262-4c86-bf10-1a879d4a1b36">


While running, in the image below, it still does not take those parameters in the "accelerate launch command" and executes as default:
<img width="531" alt="Screenshot 2024-01-31 at 12 29 05 PM" src="https://github.com/bmaltais/kohya_ss/assets/77107688/4d388031-f36d-40c9-a22a-e93227256011">

I checked other files as well and didn't find this command that is run while executing the training in any of other files.

I am not understanding what am I missing? Is this the wrong file that I am modifying or something else?

Would appreciate your help on this! :)

**Comment by bmaltais** [comment]
Try adding them here in the GUI instead:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/6b65aaf5-3cbf-423d-b7b4-54de514d2109)

**Comment by KarMa-31** [comment]
Yes, I did that too.

The additional parameters are added at the end of command used to start training:
<img width="854" alt="Screenshot 2024-01-31 at 12 39 27 PM" src="https://github.com/bmaltais/kohya_ss/assets/77107688/addcf741-212e-4b97-a304-eb4390994215">

But got this error:
<img width="885" alt="Screenshot 2024-01-31 at 8 33 34 PM" src="https://github.com/bmaltais/kohya_ss/assets/77107688/660957e0-d08c-4bff-8763-b5a91f149578">

The solution I found is that it must be added in the command before the _"./sdxl_train.py ..."_ (see the command image 2 of my previous comment). Because those parameters are not included in sdxl_train.py file, they are not recognized and hence the error.

That's the reason I am trying to add these right after _"accelerate launch"_ and before the file name in the command.

**Comment by bmaltais** [comment]
Hummm… I could try to add multigpu parameters to the GUI over the weekend… that way they would be put in the right place and would be stored in the config file…

**Comment by bmaltais** [comment]
I have implemented support for multi-gpu. Look under the `Parameters > Advanced` tab near the bottom:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/e3d24fc3-250f-45f1-a0f5-4aea841aa4a6)

You will need to use the dev branch to test it. You cn use it but doing:

`git checkout dev`

**Comment by alloc7260** [comment]
hey @bmaltais,

I also have tried training with multiple gpus in runpod with 2 x A100.

<img width="676" alt="nvidia" src="https://github.com/bmaltais/kohya_ss/assets/101977910/12a8d323-e92c-4763-af63-25ae03e740de">

But I got an error while starting kohya_ss webui
Here is the error :

<img width="886" alt="runpod issue" src="https://github.com/bmaltais/kohya_ss/assets/101977910/807872c5-d0bd-44c8-b1f5-dfde1911c52e">

While debugging I found that it is running after I checked out to just previous commit 40598ba.

I think the error is generated by your last commit 2dec489 that you pushed a few hours ago.

Please have a look at it.

Thank You

**Comment by bmaltais** [comment]
I think I know what the issue is with my last dev commit. I will fix it
later tonight

**Comment by ai-marat** [comment]
Did you manage to solve the problem? All my hopes are on multi-GPU

**Comment by ai-marat** [comment]
@alloc7260 Wow, that's great! I need to test it with 2xT4 on Kaggle. Thanks for responding!

**Comment by rmknyc** [comment]
If I am using 8 GPUs, do I select # of processes as 8? or leave it to 1? 

Do I need to identify the GPUs I'm using as well? With 0,1,2,3,4,5,6,7 ?

<img width="1528" alt="Screenshot 2024-03-11 at 6 29 26 PM" src="https://github.com/bmaltais/kohya_ss/assets/162852389/9242813f-7100-48a8-885b-60165298383b">

**Comment by littleyeson** [comment]
> I have a similiar question , that i have 2 gpu but no matter which GPU ID I choose during the setup process, whether it's 0 or 1, the final result is always that the training runs on the first one .

I have same problem.Do you fix it?

**Comment by xnorcode** [comment]
> identify the GP

same question here. How we decide the number for "Number of processes"?

**Comment by martindellavecchia** [comment]
Any luck?

**Comment by blandpebbles** [comment]
Hi, has anyone managed to get this working? I have dual A5000s and when trying to run with multi-gpu box ticked I get NCL errors and saying it can't find the AI machine.

**Comment by blacklig** [comment]
first of all, from my experience, if you are using 3090 or 4090 or so, two GPUs will perform worse than only one as accelerate cannot handle it properly.. they just dont have fast enough sync between them.. you need those special nvlinks or so to get this working properly.. but if you have A100 or so on AWS etc , then it should work via accelerate no problem

**Comment by mbac** [comment]
Hi,

Using a dual 4090 on vast.ai, I tried setting the Number of Processes to 2 and didn't change anything else related.

Got this warning that I haven't seen in this issue before:

```
The following values were not passed to `accelerate launch` and had defaults used instead:
More than one GPU was found, enabling multi-GPU training.
If this was unintended please pass in `--num_processes=1`.
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
```
using https://github.com/ai-dock/kohya_ss

**Comment by ataylorm** [comment]
Any chance of getting this added to the Flux branch?

**Comment by bmaltais** [comment]
This really need to be answered by kohya himself. I only wrapnhis sd-scrip Rd a in a GUI. I don't add the training code...

**Comment by WXT-NO1** [comment]
I have two GPUs, but I want to train by using one. But it got a error"ValueError: Less than two GPU ids were configured (gpu_ids='0') while multi_gpu=True. Please ensure at least two are specified for `--gpu_ids`, or use `--gpu_ids='all'`.". I found that even if I set multi_gpu to false, the code will automatically detect multiple GPUs and change multi_gpu to true. Therefore, we need to modify the part of the code that automatically detects hardware and sets multi_gpu. The code is located in venv\Lib\site-packages\accelerate\commands\launch.py. Hope to help.
