### ISSUE TITLE
Сan't train LORA on Proteus v0.2 model

### ISSUE THREAD

**Issue by alexv0iceh** [bmaltais/kohya_ss#1925]
I got the error when trying to start lora train with Playground V2 model
How to fix it? Looks like an error due to Proteus' TE training, but I'm not sure.

https://civitai.com/models/267242/proteus
Works for inference in a1, comfy, fooocus without changing anything.

ERROR:
RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Missing key(s) in state_dict: "text_model.embeddings.position_ids".

**Comment by ssuperGeorge** [comment]
you will need to update your transfomers dependency version. look at the updated requirement.py file
