### ISSUE TITLE
Unknown Issue when starting the bat file

### ISSUE THREAD

**Issue by PierrunoYT** [bmaltais/kohya_ss#1929]
![grafik](https://github.com/bmaltais/kohya_ss/assets/95778421/4dcdd717-82a6-4698-819d-99248ea6c04d)

**Comment by bmaltais** [comment]
Look like you have not properly installed python 3.10.9 on your computer?

```
Install [Python 3.10](https://www.python.org/ftp/python/3.10.9/python-3.10.9-amd64.exe).

During the installation process, ensure that you select the option to add Python to the 'PATH' environment variable.
```

**Comment by PierrunoYT** [comment]
I installed 3.12 clean and it worked but I'm using Pinokio for it now

**Comment by AvenueSupplies** [comment]
I have exactly same error, python 3.10.9 download and installed produces version 3.12, cannot get past this point. Any clues ?

```
Warning: Python version 3.10.9 is recommended.
The system cannot find the path specified.
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\Users\Superuser\Downloads\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\Superuser\Downloads\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'


```

Windows environment path points to C:\Users\Superuser\AppData\Local\Programs\Python\Python310

It appears that the package appears here:

```

    Directory: C:\Users\Superuser\AppData\Local\Programs\Python\Python310\Lib\site-packages


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2/12/2024   5:34 AM                pip
d-----         2/12/2024   5:34 AM                pip-24.0.dist-info
d-----         2/12/2024   6:44 AM                pkg_resources
d-----         2/12/2024   6:44 AM                setuptools
d-----         2/12/2024   6:44 AM                setuptools-69.1.0.dist-info
d-----         2/12/2024   6:08 AM                wheel
d-----         2/12/2024   6:08 AM                wheel-0.42.0.dist-info
d-----         2/12/2024   6:44 AM                _distutils_hack
-a----         2/12/2024   6:44 AM            151 distutils-precedence.pth
-a----         12/6/2022   8:25 PM            121 README.txt

```

**Comment by bmaltais** [comment]
1st, you can’t use 3.12 with Libya’s as-scripts code base. So 1st thing is to go back to 3.10.9

**Comment by FBEZ** [comment]
I solved the issue (in Windows) by forcing the `setup.bat` to use the 3.10 version, replacing 
`python -m venv venv` with `py -3.10 -m venv venv`.
Since the virtual environment is created inside the bat file, you need to be sure it's created with the right version of python.

**Comment by bmaltais** [comment]
Interesting… I will test and add the parameter to my setup if it work. This might solve some issues for many.

**Comment by arces** [comment]
> I solved the issue (in Windows) by forcing the `setup.bat` to use the 3.10 version, replacing `python -m venv venv` with `py -3.10 -m venv venv`. Since the virtual environment is created inside the bat file, you need to be sure it's created with the right version of python.

Thank you! I had python 3.12 installed, removed it from my path and installed 3.10 added that to my path, refreshed my terminal and still no luck. Did python --version and it was 3.10.9. Did FBEZ's suggestion and setup.bat worked! @bmaltais

**Comment by bmaltais** [comment]
I tried the py -3.10 and it does not work on my system so it is not a common command on windows with the python.org installed version… so I will not be able to use it as part of setup.

**Comment by joedulin** [comment]
@bmaltais I had the same issue but then remembered that setup.bat creates a venv. Deleting that folder (so that now running 3.10 it could recreate it properly) fixed issues for me.
