### ISSUE TITLE
train_network.py: error: unrecognized arguments: --no_token_padding

### ISSUE THREAD

**Issue by TeKett** [bmaltais/kohya_ss#1930]
How do i use it? I assume its supposed to work, considering its there as an option to pick. But its missing from the "usage" list of arguments that show up on the error message.

**Comment by bmaltais** [comment]
I probably potgot to remove it from the GUI for that particulat training script. Arou you training a dreambooth, finetuning, LoRA or Textual Inversion?

**Comment by bmaltais** [comment]
I have removed the parameter for LoRA... Is not supported by the script. Will be published in the next release. For now you can use it in the dev branch.
