### ISSUE TITLE
Can you add new options to the GUI or make them default for LoRA extraction?

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1933]
So 1 model can be loaded onto CPU and 1 model can be loaded onto GPU

Jan 23, 2024 / 2024/1/23: v0.8.2 : https://github.com/kohya-ss/sd-scripts?tab=readme-ov-file#jan-23-2024--2024123-v082

Some options are added to networks/extract_lora_from_models.py to reduce the memory usage.

--load_precision option can be used to specify the precision when loading the model. If the model is saved in fp16, you can reduce the memory usage by specifying --load_precision fp16 without losing precision.
--load_original_model_to option can be used to specify the device to load the original model. --load_tuned_model_to option can be used to specify the device to load the derived model. The default is cpu for both options, but you can specify cuda etc. You can reduce the memory usage by loading one of them to GPU. This option is available only for SDXL.

**Comment by bmaltais** [comment]
Git it a try in the dev branch. Let me know if it work.

```
git checkout dev
git pull
```

**Comment by FurkanGozukara** [comment]
> Git it a try in the dev branch. Let me know if it work.
> 
> ```
> git checkout dev
> git pull
> ```

thank you i tested but still missing these options

--load_original_model_to cpu
--load_tuned_model_to cuda

**Comment by bmaltais** [comment]
Did you selected sdxl? They only show for SDXL models…

**Comment by FurkanGozukara** [comment]
> Did you selected sdxl? They only show for SDXL models…

haha i tested on SD 1.5 :d will test ty

**Comment by FurkanGozukara** [comment]
I just tested with this config. Worked as supposed to be nice thank you

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/d4750dff-0262-419e-9a1a-ed16762db1b1)

**Comment by FurkanGozukara** [comment]
this screen not appears on latest version

22.6.1

```
Traceback (most recent call last):
  File "F:\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "F:\kohya_ss\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "F:\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\kohya_ss\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "F:\kohya_ss\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "F:\kohya_ss\venv\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "F:\kohya_ss\library\extract_lora_gui.py", line 98, in change_sdxl
    return gr(visible=sdxl), gr(visible=sdxl)
TypeError: 'module' object is not callable
```

**Comment by bmaltais** [comment]
Probably a side effect of the code refactoring… I will investigate

**Comment by bmaltais** [comment]
Problem fixed in the latest commit to the dev branch

**Comment by FurkanGozukara** [comment]
> Problem fixed in the latest commit to the dev branch

Could you push that to main? I prepared a tutorial article that shows LoRA extract and need it working :/

**Comment by bmaltais** [comment]
I merged it to master. Should be good to go.

**Comment by FurkanGozukara** [comment]
> I merged it to master. Should be good to go.

yep appeared thanks a lot
