### ISSUE TITLE
Kohya_ss stopped training by itself

### ISSUE THREAD

**Issue by chclkkkk** [bmaltais/kohya_ss#1935]
Everytime that I have tried to train, it stopped training by itself. 
![f](https://github.com/bmaltais/kohya_ss/assets/154470298/2c85a80f-09db-4024-919e-ff0e1de69b70)

**Comment by bmaltais** [comment]
At that point this is really an issue for kohya-ss as the GUI successfully started the training and the issue is with the training script...

https://github.com/kohya-ss/sd-scripts/issues
