### ISSUE TITLE
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation'

### ISSUE THREAD

**Issue by lemoneder** [bmaltais/kohya_ss#1938]
09:41:58-796123 INFO Version: v22.6.0

09:41:58-799113 INFO nVidia toolkit detected
09:41:59-694567 INFO Torch 2.1.2+cu118
09:41:59-706490 INFO Torch backend: nVidia CUDA 11.8 cuDNN 8700
09:41:59-707487 INFO Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
09:41:59-708484 INFO Verifying modules installation status from requirements_windows_torch2.txt...
09:41:59-709481 INFO Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
--index-url https://download.pytorch.org/whl/cu118
09:42:04-102950 INFO Installing package: xformers==0.0.23.post1+cu118 --index-url
https://download.pytorch.org/whl/cu118
09:42:06-055032 INFO Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
File "C:\kohyass\kohya_ss\kohya_gui.py", line 1, in
import gradio as gr
File "C:\kohyass\kohya_ss\venv\lib\site-packages\gradio_init_.py", line 3, in
import gradio.components as components
File "C:\kohyass\kohya_ss\venv\lib\site-packages\gradio\components_init_.py", line 1, in
from gradio.components.annotated_image import AnnotatedImage
File "C:\kohyass\kohya_ss\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in
from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (C:\kohyass\kohya_ss\venv\lib\site-packages\gradio_client\documentation.py)

**Comment by nr1a** [comment]
This problem is occurring because the Gradio version is too low.
You can temporarily work around this by changing the Gradio version specified in "requirements.txt" to **"3.44.0"**. (It is not guaranteed to work perfectly.)

**Comment by nathankrueger** [comment]
It seems like requirements.txt doesn't require a specific version of 'gradio_client' package.  I downgraded to 0.8.1 and the problem went away.

pip install gradio_client==0.8.1

**Comment by Zueuk** [comment]
> pip install gradio_client==0.8.1

Did that, now it's
```
Z:\kohya_ss>gui
17:44:22-357887 INFO     Version: v22.6.0

17:44:22-396914 INFO     nVidia toolkit detected
17:44:24-496774 INFO     Torch 2.1.2+cu118
17:44:24-525047 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:44:24-528052 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82
17:44:24-530051 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
17:44:24-533565 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         --index-url https://download.pytorch.org/whl/cu118
17:44:28-534008 INFO     Installing package: xformers==0.0.23.post1+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
17:44:31-287448 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "Z:\kohya_ss\kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "Z:\kohya_ss\dreambooth_gui.py", line 14, in <module>
    from library.common_gui import (
  File "Z:\kohya_ss\library\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by NeoLoger** [comment]
I'm having similar problem.
I tired to run `pip install gradio_client==0.8.1` it installed but I'm still getting this error.

Is there a problem with the path?


```
NeoLoger@ubuntu:~/ai/kohya/kohya_ss$ ./gui.sh
22:52:33-095607 INFO     Version: v22.6.0

22:52:33-113398 INFO     nVidia toolkit detected
22:52:33-989410 INFO     Torch 2.0.1+cu118
22:52:33-994365 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
22:52:34-006818 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 7971 Arch (8, 6) Cores 38
22:52:34-007866 INFO     Verifying modules installation status from /home/NeoLoger/ai/kohya/kohya_ss/requirements_linux.txt...
22:52:34-009738 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "/home/NeoLoger/ai/kohya/kohya_ss/kohya_gui.py", line 1, in <module>
    import gradio as gr
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/gradio_client/documentation.py)
```


Any suggestions?

**Comment by waifuista** [comment]
For me it's the same problem, I don't know what could be happening, I've tried about 10 times and the same problem always occurs :c

**Comment by NeoLoger** [comment]
Try changing the in the requirements.txt the Gradio version to 3.44.0
From - https://github.com/bmaltais/kohya_ss/discussions/1940

This fixed this issue for me.

**Comment by waifuista** [comment]
god bless you bro <3

**Comment by bmaltais** [comment]
I have updated the gradio version in the dev branch to the latest release available under the 3.x releases (3.50.2).

I had to update a bunch of gradio code to support the removal of `.update`.

Give it a try and let me know it it help:

```
git checkout dev
git pull
```
