### ISSUE TITLE
installation inport eerror gardio_client documentation

### ISSUE THREAD

**Issue by VIncewww** [bmaltais/kohya_ss#1942]
<img width="846" alt="螢幕擷取畫面 2024-02-07 183858" src="https://github.com/bmaltais/kohya_ss/assets/139464115/d30769e3-cb81-4945-a2d3-f15613e5bf58">

**Comment by FurkanGozukara** [comment]
gradio_client update broken it @bmaltais 
we need urgent update
it broken automatic1111 too

gradio_client==0.8.1 working right now

**Comment by FurkanGozukara** [comment]
opened issue on gradio as well

https://github.com/gradio-app/gradio/issues/7339

**Comment by Zueuk** [comment]
> gradio_client==0.8.1 working right now

Tried installing this version, now I'm getting
```
Traceback (most recent call last):
  File "Z:\kohya_ss\kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "Z:\kohya_ss\dreambooth_gui.py", line 14, in <module>
    from library.common_gui import (
  File "Z:\kohya_ss\library\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by VIncewww** [comment]
thank you guys, i guess i just download the file until next update. appreciate yall help

**Comment by hrustbb2** [comment]
Это гавно никогда не заработает нормально

**Comment by adek** [comment]
I'm having same error (macos). Tried to update to gradio_client==0.8.1 but it's not helping.

**Comment by NeoLoger** [comment]
I think its the same issue as on https://github.com/bmaltais/kohya_ss/issues/1938

**Comment by FurkanGozukara** [comment]
> I think its the same issue as on #1938

yes same

**Comment by ButCheR-PRO** [comment]
У меня точно такая же проблема. Причем и с версией Kohya_ss-GUI-LoRA-Portable-main и любой другой официальной версией kohya_ss-master. Пытаюсь установить kohya_ss на свой Windows 10 x64, перед этим установил python-3.10.9-amd64, и Git-2.43.0-64-bit. Так же поставил Visual Studio 2022. Всё работает. Но как только установил kohya_ss и пытаюсь запустить в нём файл gui.bat, выдаёт ошибку импорта в консоли: import gradio as gr
Я уже пробовал полностью удалить Python, Git, kohya_ss, чистил остатки в реестре, чистил омтатки программ через ccleaner, удалял через pip uninstall  все компоненты,:
pip freeze > uninstall.txt
pip uninstall -r uninstall.txt -y
  pip uninstall gradio
  pip uninstall gradio_client
 потом по новой всё ставил и на диск С ставил, и на диск F и на диск D, все также ошибка, gradio не видит, я уже вручную ставлю gradio через pip install gradio, он ставится, а при запуске gui.bat также ошибка при проверке версии gradio... Запускал даже  venv\Scripts\activate.bat
После этого запускаю gui.bat и лог консоли с той же ошибкой. Кстати когда я запустил firstrun.bat, оно скачало и установило все компоненты, и в конце просто закрылось окно, в бразузере ничего не запустилось и сервер не стартанул. Запускаю вручную  webui.bat, и он заново пытается скачать, удалить и установить компоненты, а в конце просто закрывается.
![image](https://github.com/bmaltais/kohya_ss/assets/23020594/609299eb-bb13-4bd3-943f-02a3fa6870c0)
![image](https://github.com/bmaltais/kohya_ss/assets/23020594/82acb46a-0739-44d0-ad76-2e08ce180d6d)

**Comment by ButCheR-PRO** [comment]
> У меня точно такая же проблема. Причем и с версией Kohya_ss-GUI-LoRA-Portable-main и любой другой официальной версией kohya_ss-master. Пытаюсь установить kohya_ss на свой Windows 10 x64, перед этим установил python-3.10.9-amd64, и Git-2.43.0-64-bit. Так же поставил Visual Studio 2022. Всё работает. Но как только установил kohya_ss и пытаюсь запустить в нём файл gui.bat, выдаёт ошибку импорта в консоли: import gradio as gr Я уже пробовал полностью удалить Python, Git, kohya_ss, чистил остатки в реестре, чистил омтатки программ через ccleaner, удалял через pip uninstall все компоненты,: pip freeze > uninstall.txt pip uninstall -r uninstall.txt -y pip uninstall gradio pip uninstall gradio_client потом по новой всё ставил и на диск С ставил, и на диск F и на диск D, все также ошибка, gradio не видит, я уже вручную ставлю gradio через pip install gradio, он ставится, а при запуске gui.bat также ошибка при проверке версии gradio... Запускал даже venv\Scripts\activate.bat После этого запускаю gui.bat и лог консоли с той же ошибкой. Кстати когда я запустил firstrun.bat, оно скачало и установило все компоненты, и в конце просто закрылось окно, в бразузере ничего не запустилось и сервер не стартанул. Запускаю вручную webui.bat, и он заново пытается скачать, удалить и установить компоненты, а в конце просто закрывается. ![image](https://private-user-images.githubusercontent.com/23020594/303154638-609299eb-bb13-4bd3-943f-02a3fa6870c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDQ5MjcsIm5iZiI6MTcwNzM0NDYyNywicGF0aCI6Ii8yMzAyMDU5NC8zMDMxNTQ2MzgtNjA5Mjk5ZWItYmIxMy00YmQzLTk0M2YtMDJhM2ZhNjg3MGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIyMjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YTVjZTVhOGMxZGY4NGYxODhiZDMzMzZiOWUwNDA0MjhlN2RhNGYwN2U5ZmUwNzRhMTMyNjFmOWI3NGQ2OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dcyAUNOf3fmJZMTFIPEvUrekrSONmCfQPyVmqIsSNbQ) ![image](https://private-user-images.githubusercontent.com/23020594/303154710-82acb46a-0739-44d0-ad76-2e08ce180d6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczNDQ5MjcsIm5iZiI6MTcwNzM0NDYyNywicGF0aCI6Ii8yMzAyMDU5NC8zMDMxNTQ3MTAtODJhY2I0NmEtMDczOS00NGQwLWFkNzYtMmUwOGNlMTgwZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIyMjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOTQ3MzljMzFkZjdkODE0OWM3YmM3ZWVjNTBhNzE5YWQyZTNiMzhkZTkxY2ViMTgwODNjMzA3YTYzNzM4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xOd7_UneobtOTRezb0bCpFrmH7k_EOOubXe50x81UzY)
Проблема решается интересным способом:
Сначала запускаем консоль cmd и пишем:  
python.exe -m pip install gradio_client==0.8.1
потом в requirements.txt меняем значение версии gradio, вместо gradio==3.36.1 пишем gradio==0.8.1 после чего, запускаем webui.cmd (gui.bat) ждём, в конце выдаст ошибку gradio, что-то связанное с атрибутом checkbox. 
После этого в консоли cmd пишем: 
python.exe -m pip install gradio_client
И в requirements.txt вместо gradio==0.8.1 пишем gradio==3.44.0
Теперь запускаем webui.cmd (gui.bat), он скачает этот gradio и запустит в браузере Kohya_ss GUI!
Profit!

**Comment by Rojinski** [comment]
I've softly modified the file "requirement.txt" and changed the gradio version from 3.36.1 to 3.41.2 (the same version used by A 1111). And the then Kohya SS started as usual... Not sure if it's all fine because I've another problem and i can't train not a lora nor a TI because the error "Non Zero Exit" that I get before the gradio pb...

**Comment by NeoLoger** [comment]
I changed the Gradio version to 3.44.0 and kohya_ss starts now.
However I'm now getting a `torch.cuda.OutOfMemoryError`

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 7.78 GiB total capacity; 7.41 GiB already allocated; 9.06 MiB free; 7.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|     
```


This is the traceback output with the command I use to train a model.
```
Traceback (most recent call last):
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/home/NeoLoger/ai/kohya/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/NeoLoger/ai/kohya/kohya_ss/venv/bin/python', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--pretrained_model_name_or_path=/home/NeoLoger/ai/models/sd_xl_base_1.0.safetensors', '--train_data_dir=/home/NeoLoger/ai/ImagesForSDTrining/Lora training/person/Train/images', '--resolution=768,768', '--output_dir=/home/NeoLoger/ai/ImagesForSDTrining/Lora training/person/Train/model', '--logging_dir=/home/NeoLoger/ai/ImagesForSDTrining/Lora training/person/Train/logs', '--network_alpha=12', '--training_comment=Extremely person, some times referred also as Wasp Waist ', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=64', '--output_name=Narrow_Waist_v0.1_SDXL', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--train_batch_size=1', '--max_train_steps=2776', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', 'warmup_init=False', '--max_grad_norm=1', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--flip_aug', '--shuffle_caption', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.
```

I have formatted the PC from Windows11 to Ubuntu 22.04 to see if I can get a little boos in performance but the same configs and data sets that worked fine on windows now get out of memory, and I have no idea if its related...

Anyone have any suggestions?

**Comment by ButCheR-PRO** [comment]
> I've softly modified the file "requirement.txt" and changed the gradio version from 3.36.1 to 3.41.2 (the same version used by A 1111). And the then Kohya SS started as usual... Not sure if it's all fine because I've another problem and i can't train not a lora nor a TI because the error "Non Zero Exit" that I get before the gradio pb...

The problem is solved in an interesting way:
First, launch the cmd console and write:
python.exe -m pip install gradio_client==0.8.1
then in requirements.txt we change the value of the gradio version, instead of gradio==3.36.1 we write gradio==0.8.1 after which we run webui.cmd (gui.bat) and wait, at the end it will give a gradio error, something related to the attribute checkbox.
After that, in the cmd console we write:
python.exe -m pip install gradio_client
And in requirements.txt instead of gradio==0.8.1 we write gradio==3.44.0
Now we launch webui.cmd (gui.bat), it will download this gradio and launch Kohya_ss GUI in the browser!
After this, it is better to launch Kohya_ss GUI via gui.bat
Profit!

**Comment by FOMbastic** [comment]
> > I've softly modified the file "requirement.txt" and changed the gradio version from 3.36.1 to 3.41.2 (the same version used by A 1111). And the then Kohya SS started as usual... Not sure if it's all fine because I've another problem and i can't train not a lora nor a TI because the error "Non Zero Exit" that I get before the gradio pb...
> 
> The problem is solved in an interesting way: First, launch the cmd console and write: python.exe -m pip install gradio_client==0.8.1 then in requirements.txt we change the value of the gradio version, instead of gradio==3.36.1 we write gradio==0.8.1 after which we run webui.cmd (gui.bat) and wait, at the end it will give a gradio error, something related to the attribute checkbox. After that, in the cmd console we write: python.exe -m pip install gradio_client And in requirements.txt instead of gradio==0.8.1 we write gradio==3.44.0 Now we launch webui.cmd (gui.bat), it will download this gradio and launch Kohya_ss GUI in the browser! After this, it is better to launch Kohya_ss GUI via gui.bat Profit!

I solved the Gradio problem in the way you mentioned, but after making certain preparations, when I clicked 'Start Training', it gave this error;

![4444Alıntısı](https://github.com/bmaltais/kohya_ss/assets/159487448/ea339874-fdb3-4352-b567-5bf7f3be8cef)




Just letting you know.

**Comment by Rojinski** [comment]
> > > I've softly modified the file "requirement.txt" and changed the gradio version from 3.36.1 to 3.41.2 (the same version used by A 1111). And the then Kohya SS started as usual... Not sure if it's all fine because I've another problem and i can't train not a lora nor a TI because the error "Non Zero Exit" that I get before the gradio pb...
> > 
> > 
> > The problem is solved in an interesting way: First, launch the cmd console and write: python.exe -m pip install gradio_client==0.8.1 then in requirements.txt we change the value of the gradio version, instead of gradio==3.36.1 we write gradio==0.8.1 after which we run webui.cmd (gui.bat) and wait, at the end it will give a gradio error, something related to the attribute checkbox. After that, in the cmd console we write: python.exe -m pip install gradio_client And in requirements.txt instead of gradio==0.8.1 we write gradio==3.44.0 Now we launch webui.cmd (gui.bat), it will download this gradio and launch Kohya_ss GUI in the browser! After this, it is better to launch Kohya_ss GUI via gui.bat Profit!
> 
> I solved the Gradio problem in the way you mentioned, but after making certain preparations, when I clicked 'Start Training', it gave this error;
> 
> ![4444Alıntısı](https://private-user-images.githubusercontent.com/159487448/303485335-ea339874-fdb3-4352-b567-5bf7f3be8cef.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjgwNjEsIm5iZiI6MTcwNzQyNzc2MSwicGF0aCI6Ii8xNTk0ODc0NDgvMzAzNDg1MzM1LWVhMzM5ODc0LWZkYjMtNDM1Mi1iNTY3LTViZjdmM2JlOGNlZi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQyMTI5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2EwNmExMDdmYmMyNmMzN2I1OWRiOTdjMzBhYmFiM2IyNjY5ZTZmYmJhYjEyN2JhNjQwZjNjYWY5ZTk5MmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0UBm_EGf4lhK7w8VtApAdZReZeWS9VZCvVQD_S3fElY)
> 
> Just letting you know.

You're right and it explains certainly that I get the same error at the end. Thanks a lot for your comment!!!

**Comment by Zueuk** [comment]
> I solved the Gradio problem in the way you mentioned, but after making certain preparations, when I clicked 'Start Training', it gave this error;

sounds like #1704
have you tried `pip install bitsandbytes-windows`?

**Comment by Rojinski** [comment]
> > I solved the Gradio problem in the way you mentioned, but after making certain preparations, when I clicked 'Start Training', it gave this error;
> 
> sounds like #1704 have you tried `pip install bitsandbytes-windows`?

I did... But it didn't work. So I've deleted everything and, in a minute, I will make a clean (re)install and will try that again.
Thanks for your help !!!

**Comment by FOMbastic** [comment]
> > I solved the Gradio problem in the way you mentioned, but after making certain preparations, when I clicked 'Start Training', it gave this error;
> 
> sounds like #1704 have you tried `pip install bitsandbytes-windows`?

not work for me too... It seemed like it was trained (because it much much faster than I did before), but I couldn't generate an image with the file. It was giving this error on the SD interface, 

`"NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check."`

and no visual was created.
