### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half' when trying to run Khoya

### ISSUE THREAD

**Issue by GypsyButterfly** [bmaltais/kohya_ss#1943]
I keep getting the same error... it seem to occur after the same point each time. If anyone can suggest anything i might try, I would greatly appreciated it.

I know from my searches on this site that it may help to post what happened just before it breaks, so here that is...

    File "C:\Users\username\AI_Productions\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\username\\AI_Productions\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/username/AI_Productions/mandy lora/image', '--resolution=512,512', '--output_dir=C:/Users/username/AI_Productions/mandy lora/model', '--logging_dir=C:/Users/username/AI_Productions/mandy lora/log', '--save_model_as=safetensors', '--output_name=mandymodel', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=0', '--learning_rate_te=1e-05', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=240', '--train_batch_size=1', '--max_train_steps=2400', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by ssokolow** [comment]
You didn't go far enough up to find "what happened just before it breaks".

Here's how you read those errors:

1. Look at the bottom. It says "subprocess.CalledProcessError: Command [very long line] returned non-zero exit status 1.
2. Since it's a CalledProcessError, scroll up to before the "Traceback (most recent call last):" line to find the actual error message.

("CalledProcessError" means "When I ran this other program, it errored out", the Traceback tells the programmer how it got to that point, and the stuff above the traceback is what the program that actually failed said before it exited.)

**Comment by GypsyButterfly** [comment]
Thank you so much for responding. The line i am seeing write before the traceback is this:

  File "C:\Users\<username>\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by r4881t** [comment]
I am trying to train a model and getting this same error.

I am on Google Colab using T4 instance.

my cuda info as below

<img width="576" alt="Screenshot 2024-03-07 at 12 48 57 AM" src="https://github.com/bmaltais/kohya_ss/assets/81687400/6ab19775-f1d0-4dad-b0b5-e25e61b99445">
<img width="948" alt="Screenshot 2024-03-07 at 12 48 50 AM" src="https://github.com/bmaltais/kohya_ss/assets/81687400/eb04a0da-4180-4062-b22f-3e14f137f6df">

<img width="954" alt="Screenshot 2024-03-07 at 12 50 41 AM" src="https://github.com/bmaltais/kohya_ss/assets/81687400/91b1f61f-ca93-4991-a460-10f7cec3bd5c">
