### ISSUE TITLE
Suppress Triton warning

### ISSUE THREAD

**Issue by magitekerINC** [bmaltais/kohya_ss#1949]
Is there a way to suppress the warning message;

```
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
```

After the latest update this gets spammed several times between epochs.

**Comment by Jay123210599** [comment]
I have the same problem, too. How do I fix it?

![Screenshot (366)](https://github.com/bmaltais/kohya_ss/assets/141977822/54fa68a4-cdbf-45ff-a115-7847c0c53367)

**Comment by bmaltais** [comment]
It is an issue under Windows and I can't fix it... just ignore it.
