### ISSUE TITLE
increase batch size limit for finetuning?

### ISSUE THREAD

**Issue by Nazzaroth2** [bmaltais/kohya_ss#195]
For people that have cards with high vram (24gb and above) the batch size limit of 32 is pretty low.

I already use the ui-inspection trick to increase slider limits above and can work with batch sizes of 50+, but it is rather annoying to redo that change every time i reload the trainer or the page :P

**Comment by bmaltais** [comment]
Hummm... Let me update this... would 64 be a better limit?

**Comment by Nazzaroth2** [comment]
yeah that would probably be plenty.
