### ISSUE TITLE
I cant run setup.bat's first step

### ISSUE THREAD

**Issue by kayserimantisi** [bmaltais/kohya_ss#1952]
When I write ''1''  in the Kohya GUI setup menu, this text comes up

19:39:06-640341 INFO     Version: v22.6.0

19:39:06-648342 INFO     Python 3.10.6 on Windows
19:39:06-654343 INFO     Installing modules from requirements_windows_torch2.txt...
19:39:06-658075 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         --index-url https://download.pytorch.org/whl/cu118

I wait for a hour and nothing happens, and I tried reinstalling Python but nothing happened

**Comment by kferterb** [comment]
> When I write ''1'' in the Kohya GUI setup menu, this text comes up
> 
> 19:39:06-640341 INFO Version: v22.6.0
> 
> 19:39:06-648342 INFO Python 3.10.6 on Windows 19:39:06-654343 INFO Installing modules from requirements_windows_torch2.txt... 19:39:06-658075 INFO Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118 --index-url https://download.pytorch.org/whl/cu118
> 
> I wait for a hour and nothing happens, and I tried reinstalling Python but nothing happened

Try -> https://github.com/serpotapov/Kohya_ss-GUI-LoRA-Portable

**Comment by danilasenko** [comment]
Same thing

**Comment by NotSpecific** [comment]
Yeah same issue here :/

**Comment by gohan2091** [comment]
I think you have to run webui.cmd file to get it to load up.
