### ISSUE TITLE
Unable to load `SD v2.1 768 ema pruned` and `SD v2.1 512 ema pruned` model

### ISSUE THREAD

**Issue by sean1832** [bmaltais/kohya_ss#1959]
## Issue
Cannot load both `SD v2.1 768 ema pruned` and `SD v2.1 512 ema pruned`. 

Looks like the following path is cannot be download:
- `stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-ema-pruned`
- `stabilityai/stable-diffusion-2-1/blob/main/v2-1_512-ema-pruned`

## Error
```
ValueError: The provided pretrained_model_name_or_path "stabilityai/stable-diffusion-2-1/blob/main/v2-1_768-ema-pruned" is neither a valid local path nor a valid repo id. Please check the parameter.
```

**Comment by bmaltais** [comment]
Try manually downloading the .safetensors files instead... and use those instead
