### ISSUE TITLE
training support for cascade

### ISSUE THREAD

**Issue by DataCTE** [bmaltais/kohya_ss#1964]
https://huggingface.co/stabilityai/stable-cascade
![image](https://github.com/bmaltais/kohya_ss/assets/105170707/300eb8af-b828-4964-ac6f-d97bf3531931)

**Comment by bmaltais** [comment]
If kohya ever add it to his sd-scripts repo I should be able to add support for it in the GUI.

**Comment by GamingDaveUk** [comment]
> If kohya ever add it to his sd-scripts repo I should be able to add support for it in the GUI.

Ah i was actually searching for how to use Kohya to do some training for LORA in cascade when I stumbled on this one... didnt realise it needed a whole new system. 

crossing my fingers support happens.

**Comment by MushroomFleet** [comment]
> If kohya ever add it to his sd-scripts repo I should be able to add support for it in the GUI.

https://github.com/kohya-ss/sd-scripts/tree/stable-cascade

things move so fast !

**Comment by bmaltais** [comment]
I have pinned an issue where we dis uss the gui development aspects.
