### ISSUE TITLE
Error extracting LyCORIS

### ISSUE THREAD

**Issue by physeo** [bmaltais/kohya_ss#1968]
Been getting this error for the last month or so when attempting to extract a LyCORIS:

`UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
Traceback (most recent call last):
  File "H:\StableDiffusion\kohya_ss\tools\lycoris_locon_extract.py", line 190, in <module>
    main()
  File "H:\StableDiffusion\kohya_ss\tools\lycoris_locon_extract.py", line 169, in main
    state_dict = extract_diff(
  File "H:\StableDiffusion\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 376, in extract_diff
    for idx, te1, te2 in enumerate(zip(base_tes, db_tes)):
ValueError: not enough values to unpack (expected 3, got 2)
23:52:28-452085 INFO     Done extracting...`

**Comment by bmaltais** [comment]
Wait... it just failed near the end... I think it is a bug with the Lycoris script:

```
16:37:42-259867 INFO     ./venv/Scripts/python.exe "tools\lycoris_locon_extract.py" --is_sdxl --device cuda --mode quantile --safetensors --linear_quantile 0.75 --conv_quantile 0.75                 
                         --sparsity 0.98 "E:/models/sdxl/base/sd_xl_base_1.0_0.9vae.safetensors" "E:/models/sdxl/RealVisXL_V3.0.safetensors"
                         "E:/lora/sdxl/RealVisXL_V3.0.safetensors"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
text encoder 2: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
text encoder 2: _IncompatibleKeys(missing_keys=[], unexpected_keys=['text_model.embeddings.position_ids'])
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Traceback (most recent call last):
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 190, in <module>
    main()
  File "D:\kohya_ss\tools\lycoris_locon_extract.py", line 169, in main
    state_dict = extract_diff(
  File "D:\kohya_ss\venv\lib\site-packages\lycoris\utils\__init__.py", line 376, in extract_diff
    for idx, te1, te2 in enumerate(zip(base_tes, db_tes)):
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by bmaltais** [comment]
Yeah... it is a bug with his code... open an issue at: https://github.com/KohakuBlueleaf/LyCORIS/tree/main

**Comment by blormp** [comment]
I had this same issue. Rolling back to v22.2.2 fixed it for me
