### ISSUE TITLE
Merge LoRAs outputs a non existant 'corrupt safetensor Lora merger file'

### ISSUE THREAD

**Issue by Ehtz** [bmaltais/kohya_ss#1970]
Hello, 

When merging 2 LoRAs i cannot find the output file, I can see it within my 'Recent directory' but won't let me copy it or find the location of the output file 'Could not find this item'.

merging...
Traceback (most recent call last):
  File "C:\Users\OneDrive\Bureau\kohya_ss\networks\merge_lora.py", line 276, in merge
    state_dict, metadata, v2 = merge_lora_models(args.models, args.ratios, merge_dtype, args.concat, args.shuffle)
  File "C:\Users\OneDrive\Bureau\kohya_ss\networks\merge_lora.py", line 178, in merge_lora_models
    merged_sd[key].size() == lora_sd[key].size() or concat_dim is not None
**AssertionError:** weights shape mismatch merging v1 and v2, different dims? / 重みのサイズが合いません。v1とv2、または次元数の異なるモデルはマージできません
14:04:34-883925 INFO     Done merging...

Thanks.

**Comment by Ehtz** [comment]
I am merging 1 Lora 768 with a 512 Lora and getting an AssertionError. Now i have tested the merge of the 512 with a different 768 lora and it works... This is very peculiar... So 512x768 do work but this particular 768 Lora doesn't is not compatible merging with 512.

**Comment by Ehtz** [comment]
Network rank was modified from 128 -> 8 in my log file during training. I set it to 128 before training. The output log file was marked at 8.

**Comment by bmaltais** [comment]
Is it consistently switching from 128 to 8?

**Comment by Ehtz** [comment]
> Is it consistently switching from 128 to 8?
Trained another Lora, DIM stayed consistant to input.
