### ISSUE TITLE
 --lora_network_weights  not being recognized as a valid argument

### ISSUE THREAD

**Issue by futureflix87** [bmaltais/kohya_ss#1972]
It seems that --lora_network_weights is not being recognized as a valid argument

usage: sdxl_train_network.py [-h] [--v2] [--v_parameterization]
                             [--pretrained_model_name_or_path PRETRAINED_MODEL_NAME_OR_PATH]
                             [--tokenizer_cache_dir TOKENIZER_CACHE_DIR] [--train_data_dir TRAIN_DATA_DIR]
                             [--shuffle_caption] [--caption_separator CAPTION_SEPARATOR]
                             [--caption_extension CAPTION_EXTENSION] [--caption_extention CAPTION_EXTENTION]
                             [--keep_tokens KEEP_TOKENS] [--keep_tokens_separator KEEP_TOKENS_SEPARATOR]
                             [--caption_prefix CAPTION_PREFIX] [--caption_suffix CAPTION_SUFFIX] [--color_aug]
                             [--flip_aug] [--face_crop_aug_range FACE_CROP_AUG_RANGE] [--random_crop]
                             [--debug_dataset] [--resolution RESOLUTION] [--cache_latents]
                             [--vae_batch_size VAE_BATCH_SIZE] [--cache_latents_to_disk] [--enable_bucket]
                             [--min_bucket_reso MIN_BUCKET_RESO] [--max_bucket_reso MAX_BUCKET_RESO]
                             [--bucket_reso_steps BUCKET_RESO_STEPS] [--bucket_no_upscale]
                             [--token_warmup_min TOKEN_WARMUP_MIN] [--token_warmup_step TOKEN_WARMUP_STEP]
                             [--dataset_class DATASET_CLASS] [--caption_dropout_rate CAPTION_DROPOUT_RATE]
                             [--caption_dropout_every_n_epochs CAPTION_DROPOUT_EVERY_N_EPOCHS]
                             [--caption_tag_dropout_rate CAPTION_TAG_DROPOUT_RATE] [--reg_data_dir REG_DATA_DIR]
                             [--in_json IN_JSON] [--dataset_repeats DATASET_REPEATS] [--output_dir OUTPUT_DIR]
                             [--output_name OUTPUT_NAME] [--huggingface_repo_id HUGGINGFACE_REPO_ID]
                             [--huggingface_repo_type HUGGINGFACE_REPO_TYPE]
                             [--huggingface_path_in_repo HUGGINGFACE_PATH_IN_REPO]
                             [--huggingface_token HUGGINGFACE_TOKEN]
                             [--huggingface_repo_visibility HUGGINGFACE_REPO_VISIBILITY] [--save_state_to_huggingface]
                             [--resume_from_huggingface] [--async_upload] [--save_precision {None,float,fp16,bf16}]
                             [--save_every_n_epochs SAVE_EVERY_N_EPOCHS] [--save_every_n_steps SAVE_EVERY_N_STEPS]
                             [--save_n_epoch_ratio SAVE_N_EPOCH_RATIO] [--save_last_n_epochs SAVE_LAST_N_EPOCHS]
                             [--save_last_n_epochs_state SAVE_LAST_N_EPOCHS_STATE]
                             [--save_last_n_steps SAVE_LAST_N_STEPS]
                             [--save_last_n_steps_state SAVE_LAST_N_STEPS_STATE] [--save_state] [--resume RESUME]
                             [--train_batch_size TRAIN_BATCH_SIZE] [--max_token_length {None,150,225}]
                             [--mem_eff_attn] [--torch_compile]
                             [--dynamo_backend {eager,aot_eager,inductor,aot_ts_nvfuser,nvprims_nvfuser,cudagraphs,ofi,fx2trt,onnxrt}]
                             [--xformers] [--sdpa] [--vae VAE] [--max_train_steps MAX_TRAIN_STEPS]
                             [--max_train_epochs MAX_TRAIN_EPOCHS]
                             [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
                             [--persistent_data_loader_workers] [--seed SEED] [--gradient_checkpointing]
                             [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                             [--mixed_precision {no,fp16,bf16}] [--full_fp16] [--full_bf16] [--fp8_base]
                             [--ddp_timeout DDP_TIMEOUT] [--ddp_gradient_as_bucket_view] [--ddp_static_graph]
                             [--clip_skip CLIP_SKIP] [--logging_dir LOGGING_DIR] [--log_with {tensorboard,wandb,all}]
                             [--log_prefix LOG_PREFIX] [--log_tracker_name LOG_TRACKER_NAME]
                             [--wandb_run_name WANDB_RUN_NAME] [--log_tracker_config LOG_TRACKER_CONFIG]
                             [--wandb_api_key WANDB_API_KEY] [--noise_offset NOISE_OFFSET]
                             [--multires_noise_iterations MULTIRES_NOISE_ITERATIONS] [--ip_noise_gamma IP_NOISE_GAMMA]
                             [--multires_noise_discount MULTIRES_NOISE_DISCOUNT]
                             [--adaptive_noise_scale ADAPTIVE_NOISE_SCALE] [--zero_terminal_snr]
                             [--min_timestep MIN_TIMESTEP] [--max_timestep MAX_TIMESTEP] [--lowram]
                             [--sample_every_n_steps SAMPLE_EVERY_N_STEPS] [--sample_at_first]
                             [--sample_every_n_epochs SAMPLE_EVERY_N_EPOCHS] [--sample_prompts SAMPLE_PROMPTS]
                             [--sample_sampler {ddim,pndm,lms,euler,euler_a,heun,dpm_2,dpm_2_a,dpmsolver,dpmsolver++,dpmsingle,k_lms,k_euler,k_euler_a,k_dpm_2,k_dpm_2_a}]
                             [--config_file CONFIG_FILE] [--output_config] [--metadata_title METADATA_TITLE]
                             [--metadata_author METADATA_AUTHOR] [--metadata_description METADATA_DESCRIPTION]
                             [--metadata_license METADATA_LICENSE] [--metadata_tags METADATA_TAGS]
                             [--prior_loss_weight PRIOR_LOSS_WEIGHT] [--optimizer_type OPTIMIZER_TYPE]
                             [--use_8bit_adam] [--use_lion_optimizer] [--learning_rate LEARNING_RATE]
                             [--max_grad_norm MAX_GRAD_NORM] [--optimizer_args [OPTIMIZER_ARGS ...]]
                             [--lr_scheduler_type LR_SCHEDULER_TYPE] [--lr_scheduler_args [LR_SCHEDULER_ARGS ...]]
                             [--lr_scheduler LR_SCHEDULER] [--lr_warmup_steps LR_WARMUP_STEPS]
                             [--lr_scheduler_num_cycles LR_SCHEDULER_NUM_CYCLES]
                             [--lr_scheduler_power LR_SCHEDULER_POWER] [--dataset_config DATASET_CONFIG]
                             [--min_snr_gamma MIN_SNR_GAMMA] [--scale_v_pred_loss_like_noise_pred]
                             [--v_pred_like_loss V_PRED_LIKE_LOSS] [--debiased_estimation_loss] [--weighted_captions]
                             [--no_metadata] [--save_model_as {None,ckpt,pt,safetensors}] [--unet_lr UNET_LR]
                             [--text_encoder_lr TEXT_ENCODER_LR] [--network_weights NETWORK_WEIGHTS]
                             [--network_module NETWORK_MODULE] [--network_dim NETWORK_DIM]
                             [--network_alpha NETWORK_ALPHA] [--network_dropout NETWORK_DROPOUT]
                             [--network_args [NETWORK_ARGS ...]] [--network_train_unet_only]
                             [--network_train_text_encoder_only] [--training_comment TRAINING_COMMENT]
                             [--dim_from_weights] [--scale_weight_norms SCALE_WEIGHT_NORMS]
                             [--base_weights [BASE_WEIGHTS ...]]
                             [--base_weights_multiplier [BASE_WEIGHTS_MULTIPLIER ...]] [--no_half_vae]
                             [--cache_text_encoder_outputs] [--cache_text_encoder_outputs_to_disk]
sdxl_train_network.py: error: unrecognized arguments: --lora_network_weights=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/model/TwoSidesXL_K-000013.safetensors
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "...\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "...\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "...\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "...\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['...kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--network_train_unet_only', '--cache_text_encoder_outputs', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--cache_text_encoder_outputs', '--caption_extension=.txt', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--full_bf16', '--gradient_checkpointing', '--keep_tokens=1', '--learning_rate=5e-05', '--logging_dir=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/log', '--lora_network_weights=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/model/TwoSidesXL_K-000013.safetensors', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=40', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_token_length=150', '--max_train_steps=20000', '--mixed_precision=bf16', '--network_alpha=1', '--network_dim=32', '--network_module=networks.lora', '--no_half_vae', '--multires_noise_iterations=6', '--multires_noise_discount=0.1', '--optimizer_args', 'scale_parameter=False', 'relative_step=False', '--optimizer_type=Adafactor', '--output_dir=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/model', '--output_name=TwoSidesXL_K', '--pretrained_model_name_or_path=.../stable-diffusion-webui-1.6.0/stable-diffusion-webui-1.6.0/models/Stable-diffusion/sd_xl_base_1.0_0.9vae.safetensors', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=bf16', '--text_encoder_lr=5e-05', '--train_batch_size=3', '--train_data_dir=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/img', '--unet_lr=5e-05', '--xformers', '--sample_sampler=euler_a', '--sample_prompts=E:/Training/LoRAs Models/SDXL/TwoSidesXL2/model\\sample\\prompt.txt', '--sample_every_n_steps=100']' returned non-zero exit status 2.

**Comment by Zhincore** [comment]
Same goes for `train_network.py` when training 1.5

**Comment by vmetternich** [comment]
same error here

**Comment by bmaltais** [comment]
Might be a side affect of my code refactoring... Rvert to the previous release until I can implement a fix.

**Comment by bmaltais** [comment]
OK, Try the updated code in the dev branch... I have pushed a fix:

```
git pull
git checkout dev
```

**Comment by Zhincore** [comment]
dev branch works!

**Comment by Ahoo-Mun** [comment]
> dev branch works!

I'm having the same issue, using the dev branch seems to have fixed it.

**Comment by jhainzlschmid** [comment]
I think the fix is already released (current version: [v22.6.2](https://github.com/bmaltais/kohya_ss/releases/tag/v22.6.2)) and the issue can be closed
