### ISSUE TITLE
kohya Lora trainer can't find base XL model

### ISSUE THREAD

**Issue by wywhynot** [bmaltais/kohya_ss#1974]
i've tried using the huggingface link and a local downloaded file path and neither work. it can find my 1.5 model to train with though, and it is in the exact same folder as the XL. please, what's going on and how can i get Kohya to find XL?

**Comment by bmaltais** [comment]
I just tried on my system and it does work fine:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/274b3c39-027e-48a9-86c5-e6800af070b7)

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/3d7ed00c-471d-40aa-95d1-5f8f83581048)

**Comment by wywhynot** [comment]
well, a friend pointed it out to me: my folder path looked like this> C:\stable diffusion\models\sdxl_vae.safetensors

they said their can't be spaces in the file path. i changed that and it SEEMS to be working but so far it keeps running out of memory. i have enough Vram, i just have to get the settings right, this is only my 1st time using kohya for an XL model. any tips? i have a dataset of about 215 images

> I just tried on my system and it does work fine:
> 
> ![image](https://private-user-images.githubusercontent.com/7474674/305678951-274b3c39-027e-48a9-86c5-e6800af070b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk1MS0yNzRiM2MzOS0wMjdlLTQ4YTktODZjNS1lNjgwMGFmMDcwYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE2YjE1MGVmNGFjZGNjMGVmMzA4Mzk3ZGFlZGMzNTA2MDE5MTFiODc2NzI5YzQyNDVkZDFlMzNkODNjNWFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vywpl2gx-07yX3f4UBq80PweCYUWjAbRF6tLWG-sd3c)
> 
> ![image](https://private-user-images.githubusercontent.com/7474674/305678964-3d7ed00c-471d-40aa-95d1-5f8f83581048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk2NC0zZDdlZDAwYy00NzFkLTQwYWEtOTVkMS01ZjhmODM1ODEwNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMyN2ZhZjAzODBmOTRhNzIwNjYxMjU2YTMzNjhjZDkwYTEyMDBkN2JmZDhmNGEyNDJlMTJjM2JiNDI1ZWIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CFwuBer6fJmDnS-ZtY1P7o6DTtx5WM82qdtWVewCL34)

**Comment by bmaltais** [comment]
This is odd... the code should wrap the path in double quotes to avoid this... I will check my code... perhaps my refactoring has dropped the double quotes around the model path...

**Comment by DKnight54** [comment]
> well, a friend pointed it out to me: my folder path looked like this> C:\stable diffusion\models\sdxl_vae.safetensors
> 
> they said their can't be spaces in the file path. i changed that and it SEEMS to be working but so far it keeps running out of memory. i have enough Vram, i just have to get the settings right, this is only my 1st time using kohya for an XL model. any tips? i have a dataset of about 215 images. i have 16GB of vram and was told it should be workable
> 
> > I just tried on my system and it does work fine:
> > ![image](https://private-user-images.githubusercontent.com/7474674/305678951-274b3c39-027e-48a9-86c5-e6800af070b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk1MS0yNzRiM2MzOS0wMjdlLTQ4YTktODZjNS1lNjgwMGFmMDcwYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE2YjE1MGVmNGFjZGNjMGVmMzA4Mzk3ZGFlZGMzNTA2MDE5MTFiODc2NzI5YzQyNDVkZDFlMzNkODNjNWFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vywpl2gx-07yX3f4UBq80PweCYUWjAbRF6tLWG-sd3c)
> > ![image](https://private-user-images.githubusercontent.com/7474674/305678964-3d7ed00c-471d-40aa-95d1-5f8f83581048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk2NC0zZDdlZDAwYy00NzFkLTQwYWEtOTVkMS01ZjhmODM1ODEwNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMyN2ZhZjAzODBmOTRhNzIwNjYxMjU2YTMzNjhjZDkwYTEyMDBkN2JmZDhmNGEyNDJlMTJjM2JiNDI1ZWIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CFwuBer6fJmDnS-ZtY1P7o6DTtx5WM82qdtWVewCL34)

16 GB of VRAM will run out of memory if loading the safetensor version of the file. You should try to get the diffusers version of the model which is easiest done by providing the model in the huggingface format of "stabilityai/stable-diffusion-xl-base-1.0". This should get the script to download the diffusers model on the first run, and future runs should load from the cached model

**Comment by wywhynot** [comment]
> > well, a friend pointed it out to me: my folder path looked like this> C:\stable diffusion\models\sdxl_vae.safetensors
> > they said their can't be spaces in the file path. i changed that and it SEEMS to be working but so far it keeps running out of memory. i have enough Vram, i just have to get the settings right, this is only my 1st time using kohya for an XL model. any tips? i have a dataset of about 215 images. i have 16GB of vram and was told it should be workable
> > > I just tried on my system and it does work fine:
> > > ![image](https://private-user-images.githubusercontent.com/7474674/305678951-274b3c39-027e-48a9-86c5-e6800af070b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk1MS0yNzRiM2MzOS0wMjdlLTQ4YTktODZjNS1lNjgwMGFmMDcwYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmE2YjE1MGVmNGFjZGNjMGVmMzA4Mzk3ZGFlZGMzNTA2MDE5MTFiODc2NzI5YzQyNDVkZDFlMzNkODNjNWFmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Vywpl2gx-07yX3f4UBq80PweCYUWjAbRF6tLWG-sd3c)
> > > ![image](https://private-user-images.githubusercontent.com/7474674/305678964-3d7ed00c-471d-40aa-95d1-5f8f83581048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjk0NTMsIm5iZiI6MTcwODIyOTE1MywicGF0aCI6Ii83NDc0Njc0LzMwNTY3ODk2NC0zZDdlZDAwYy00NzFkLTQwYWEtOTVkMS01ZjhmODM1ODEwNDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMThUMDQwNTUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmMyN2ZhZjAzODBmOTRhNzIwNjYxMjU2YTMzNjhjZDkwYTEyMDBkN2JmZDhmNGEyNDJlMTJjM2JiNDI1ZWIyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CFwuBer6fJmDnS-ZtY1P7o6DTtx5WM82qdtWVewCL34)
> 
> 16 GB of VRAM will run out of memory if loading the safetensor version of the file. You should try to get the diffusers version of the model which is easiest done by providing the model in the huggingface format of "stabilityai/stable-diffusion-xl-base-1.0". This should get the script to download the diffusers model on the first run, and future runs should load from the cached model

alrght, anything besides that i should remember for properly setting XL training parameters? this would be my first time and not all youtube tutorials are easy for me to follow

**Comment by DKnight54** [comment]
Hmm... I'm gonna say that the specific error is going to have to wait until bmaltais fixes the double quote issue. Although if you are daring, I suppose you can try running the script from the command line. 

Just a note, from the parameters? I think you are running it from the dreambooth tab for training the full model, and not the lora training tab. I would expect to see './sdxl_train_network.py' instead of './sdxl_train.py'

**Comment by wywhynot** [comment]
> Hmm... I'm gonna say that the specific error is going to have to wait until bmaltais fixes the double quote issue. Although if you are daring, I suppose you can try running the script from the command line.
> 
> Just a note, from the parameters? I think you are running it from the dreambooth tab for training the full model, and not the lora training tab. I would expect to see './sdxl_train_network.py' instead of './sdxl_train.py'

nope, not daring. i barely know how to use command line codes all. just trying to stay patient, i really REALLY want this to work. and thanks, i'll double check next time
