### ISSUE TITLE
[Feature request] Create json file for training from Lora-Metadata?

### ISSUE THREAD

**Issue by neojam** [bmaltais/kohya_ss#1977]
Hallo,

I would like to ask, if its possible to create a json file for training based on existing Lora-Metadata?

Often you come around a good trained lora and just want to try these settings.
Would be great, if you could just load the lora and have all settings ready for the baking, without much fuss.

**Comment by bmaltais** [comment]
I think this is a great idea... if someone what to tackle this and submit a PR I will gladly merge it... but at the moment I don't have the time to dive in it.
