### ISSUE TITLE
After the update today doesn't work

### ISSUE THREAD

**Issue by TomiTom1234** [bmaltais/kohya_ss#198]
I have a card with low VRAMs (RTX 3070 Ti 8 gb) , I trained my pictures using LORA successfully 2 weeks ago..
Today I wanted to train another pictures, I updated the app, then tried to train, it starts checking, after that it stops with the message "returned non-zero exit status 1"..

Any solution? Or can I downgrade to previous version maybe?

Here is the message after the error report:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\AI\Koya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
enable full fp16 training.
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1000
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1000
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1000
Traceback (most recent call last):
  File "C:\AI\Koya\kohya_ss\train_network.py", line 573, in <module>
    train(args)
  File "C:\AI\Koya\kohya_ss\train_network.py", line 356, in train
    "ss_noise_offset": args.noise_offset,
AttributeError: 'Namespace' object has no attribute 'noise_offset'
Traceback (most recent call last):
  File "C:\Users\abu-m\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abu-m\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\Koya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\AI\\Koya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/AI/SUPERSD2.0Dependencies/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV13_v13.safetensors', '--train_data_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/image', '--resolution=512,512', '--output_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/model', '--logging_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=AbuMuawia2', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=100', '--train_batch_size=1', '--max_train_steps=1000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--full_fp16', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by kofboy2000** [comment]
https://github.com/bmaltais/kohya_ss/issues/192
https://github.com/TimDettmers/bitsandbytes/issues/148 

I think you can refer above issues. 
I had a same issue and can resolve by updating library/train_util.py with kohya's new version
https://github.com/kohya-ss/sd-scripts/blob/main/library/train_util.py
suggested by @martianunlimited at https://github.com/bmaltais/kohya_ss/issues/192

**Comment by TomiTom1234** [comment]
> #192 [TimDettmers/bitsandbytes#148](https://github.com/TimDettmers/bitsandbytes/issues/148)
> 
> I think you can refer above issues. I had a same issue and can resolve by updating library/train_util.py with kohya's new version https://github.com/kohya-ss/sd-scripts/blob/main/library/train_util.py suggested by @martianunlimited at #192

Thank you for your reply..
I saw this thread earlier, and I downloaded that file from the link, replaced the old one with it, then started the "Dreambooth Lora" all over again.. But I got error immediately.. This is the message I received 👍 

Traceback (most recent call last):
  File "C:\AI\Koya\kohya_ss\train_network.py", line 21, in <module>
    import library.train_util as train_util
  File "C:\AI\Koya\kohya_ss\library\train_util.py", line 69
    <title>sd-scripts/train_util.py at main · kohya-ss/sd-scripts</title>
                                            ^
SyntaxError: invalid character '·' (U+00B7)
Traceback (most recent call last):
  File "C:\Users\abu-m\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\abu-m\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\AI\Koya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\AI\Koya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\AI\\Koya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=C:/AI/SUPERSD2.0Dependencies/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV13_v13.safetensors', '--train_data_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/img', '--resolution=512,512', '--output_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/model', '--logging_dir=C:/Users/abu-m/Documents/Lora Training Data/AbuMuawia2/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=AbuMuawia2', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by ReturnnTure** [comment]
> > #192 [TimDettmers/bitsandbytes#148](https://github.com/TimDettmers/bitsandbytes/issues/148)
> > I think you can refer above issues. I had a same issue and can resolve by updating library/train_util.py with kohya's new version https://github.com/kohya-ss/sd-scripts/blob/main/library/train_util.py suggested by @martianunlimited at #192
> 
> Thank you for your reply.. I saw this thread earlier, and I downloaded that file from the link, replaced the old one with it, then started the "Dreambooth Lora" all over again.. But I got error immediately, I don't know if I did the right steps or do I have to do something else beside replacing the file? This is the message I received :
> 
> ==EDIT== No I was doing it wrong, I thought I had to download the file and replace the old one with it, but I figured out to copy the text then paste it on the old one, and that method worked.. Thank you!!

is ther a difference between copy the text and replace the entire fpy file? I tried both, none of it works ,still getting the same error.

**Comment by Inkfield** [comment]
> > #192 [TimDettmers/bitsandbytes#148](https://github.com/TimDettmers/bitsandbytes/issues/148)
> > I think you can refer above issues. I had a same issue and can resolve by updating library/train_util.py with kohya's new version https://github.com/kohya-ss/sd-scripts/blob/main/library/train_util.py suggested by @martianunlimited at #192
> 
> Thank you for your reply.. I saw this thread earlier, and I downloaded that file from the link, replaced the old one with it, then started the "Dreambooth Lora" all over again.. But I got error immediately, I don't know if I did the right steps or do I have to do something else beside replacing the file? This is the message I received :
> 
> ==EDIT== No I was doing it wrong, I thought I had to download the file and replace the old one with it, but I figured out to copy the text then paste it on the old one, and that method worked.. Thank you!!

Hello. I have the same problem as you. After using the new file, I immediately get the error: SyntaxError: invalid character '-'

When you say "copy the text then paste it on the old one", do you mean to overwrite the content of the old file with the content of the new one, or paste everything right after the text content of the old one?
