### ISSUE TITLE
batch["images"] == None after caching latents, but I want to use it.

### ISSUE THREAD

**Issue by caiweihan** [bmaltais/kohya_ss#1985]
I cannot acccess to `batch["images"]` of the dataset train_dataset_group after this line of code:
`train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)` in `train_network.py`:
```
        # 学習を準備する
        if cache_latents:
            vae.to(accelerator.device, dtype=vae_dtype)
            vae.requires_grad_(False)
            vae.eval()
            with torch.no_grad():
                train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
            vae.to("cpu")
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()

            accelerator.wait_for_everyone()
```

This is the output that proves cache_latents will calculate `batch["latents"]` and set `batch["images"]` to None:
```
Key: images, Type: <class 'torch.Tensor'>, Shape: torch.Size([1, 3, 384, 640])
Key: latents, Type: <class 'NoneType'>

[Dataset 0]
caching latents.
checking cache validity...
100%|█████████████████████████████████████| 131/131 [00:00<00:00, 403713.32it/s]
caching latents...
100%|█████████████████████████████████████████| 131/131 [00:10<00:00, 12.32it/s]

Key: images, Type: <class 'NoneType'>
Key: latents, Type: <class 'torch.Tensor'>, Shape: torch.Size([1, 4, 48, 80])
```
But I want to use this attribute later. How can I remain ` batch["images"]`? I didn't find any code in `cache_latents` or `cache_batch_latents` that clear ` batch["images"]`.

**Comment by DKnight54** [comment]
I'm just going to add, that the batch["images"] that you are trying to access is a temporary variable that only existed in the `for step, batch in enumerate(train_dataloader):` loop that only exists if you decided not to cache your images as latents.

Assuming you are trying to access that inside the for loop, I'm pretty sure the only way you'll get anything but noneType for is if you don't use cached latents and let the latents be generated on the fly.

For better understanding, which I have not fully comprehended myself yet, you can try checking out the dataset implementation in **[Kohya's code here](https://github.com/kohya-ss/sd-scripts/blob/cd19df49cd512e13ac90db115c424d19c0e8868a/library/train_util.py#L2119C1-L2119C35)**.
