### ISSUE TITLE
Is it possible to update the lycoris related files under Tools?

### ISSUE THREAD

**Issue by suede299** [bmaltais/kohya_ss#1988]
There is already a bug-fixed version of lycoris on pypi, but using the GUI's extraction tool results in an error, and now requires a manual modification of the .py to run.

**Comment by bmaltais** [comment]
What tool need to be updated?

**Comment by suede299** [comment]
> What tool need to be updated?

lycoris_utils.py

**Comment by bmaltais** [comment]
I think Lycoris retired that one… if you have a link to the new version please share. I will update it. When I checked yesterday I could not find it. Maybe I should remove it from the GUI if it no longer work.

**Comment by suede299** [comment]
> I think Lycoris retired that one… if you have a link to the new version please share. I will update it. When I checked yesterday I could not find it. Maybe I should remove it from the GUI if it no longer work.

https://pypi.org/project/lycoris-lora/2.1.0.post3/#files

**Comment by bmaltais** [comment]
Is updated in the next release.
