### ISSUE TITLE
ValueError when changing Model Quick Pick from SD V1.5 to SD XL 1.0 in LoRA training

### ISSUE THREAD

**Issue by Taigunata** [bmaltais/kohya_ss#1990]
I trained a few working LoRA models for SD V1.5 without any issues. Now i want to train LoRAs for SD XL but ran into a ValueError. How do i fix that? 

06:52:09-030944 INFO     SDXL model selected. Setting sdxl parameters
06:52:10-226519 INFO     Start training LoRA Standard ...
06:52:10-653673 INFO     Checking for duplicate image filenames in training data directory...
06:52:10-658694 INFO     Valid image folder names found in: D:/LoRA_Modelmaker-Data/Model6/image
06:52:10-696147 INFO     Folder 100_fcb: 104 images found
06:52:10-698142 INFO     Folder 100_fcb: 10400 steps
06:52:10-729425 INFO     Total steps: 10400
06:52:10-732417 INFO     Train batch size: 2
06:52:10-734413 INFO     Gradient accumulation steps: 1
06:52:10-736408 INFO     Epoch: 1
06:52:10-738402 INFO     Regulatization factor: 1
06:52:10-740396 INFO     max_train_steps (10400 / 2 / 1 * 1 * 1) = 5200
06:52:10-743388 INFO     stop_text_encoder_training = 0
06:52:10-745382 INFO     lr_warmup_steps = 0
06:52:10-749371 INFO     Saving training config to
                         D:/LoRA_Modelmaker-Data/Model6/model\My_LoRA_fcb_sdxl_20240221-065210.json...
06:52:10-824704 INFO     accelerate launch --num_cpu_threads_per_process=2 "./sdxl_train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-refiner-1.0"
                         --train_data_dir="D:/LoRA_Modelmaker-Data/Model6/image" --resolution="512,512"
                         --output_dir="D:/LoRA_Modelmaker-Data/Model6/model"
                         --logging_dir="D:/LoRA_Modelmaker-Data/Model6/log" --network_alpha="128"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=128 --output_name="My_LoRA_fcb_sdxl"
                         --lr_scheduler_num_cycles="1" --no_half_vae --learning_rate="0.0001" --lr_scheduler="constant"
                         --train_batch_size="2" --max_train_steps="5200" --save_every_n_epochs="1"
                         --mixed_precision="fp16" --save_precision="fp16" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW" --max_data_loader_n_workers="1" --keep_tokens="1"
                         --bucket_reso_steps=64 --shuffle_caption --xformers --bucket_no_upscale --noise_offset=0.0
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory D:\LoRA_Modelmaker-Data\Model6\image\100_fcb contains 104 image files
10400 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\LoRA_Modelmaker-Data\Model6\image\100_fcb"
    image_count: 104
    num_repeats: 100
    shuffle_caption: True
    keep_tokens: 1
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: fcb
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 104/104 [00:02<00:00, 37.45it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (320, 576), count: 200
bucket 1: resolution (384, 512), count: 2600
bucket 2: resolution (384, 576), count: 5600
bucket 3: resolution (448, 448), count: 300
bucket 4: resolution (448, 512), count: 300
bucket 5: resolution (448, 576), count: 100
bucket 6: resolution (512, 320), count: 400
bucket 7: resolution (512, 384), count: 200
bucket 8: resolution (576, 384), count: 700
mean ar error (without repeats): 0.010620214153660847
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: stabilityai/stable-diffusion-xl-refiner-1.0, variant=fp16
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:42<00:00,  8.42s/it]
Traceback (most recent call last):
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\sdxl_train_network.py", line 185, in <module>
    trainer.train(args)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\train_network.py", line 228, in train
    model_version, text_encoder, vae, unet = self.load_target_model(args, weight_dtype, accelerator)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\sdxl_train_network.py", line 44, in load_target_model
    ) = sdxl_train_util.load_target_model(args, accelerator, sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, weight_dtype)  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\library\sdxl_train_util.py", line 34, in load_target_model
    ) = _load_target_model(
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\library\sdxl_train_util.py", line 84, in _load_target_model
    pipe = StableDiffusionXLPipeline.from_pretrained(
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1191, in from_pretrained
    raise ValueError(
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion_xl.pipeline_stable_diffusion_xl.StableDiffusionXLPipeline'> expected {'scheduler', 'tokenizer_2', 'text_encoder', 'text_encoder_2', 'tokenizer', 'vae', 'unet'}, but only {'scheduler', 'tokenizer_2', 'text_encoder_2', 'tokenizer', 'vae', 'unet'} were passed.
Traceback (most recent call last):
  File "C:\Users\Acer Aspire 7 Thies\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Acer Aspire 7 Thies\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\launch.py", line 986, in launch_command
    simple_launcher(args)
  File "D:\dowloads\kohya_ss-22.3.0\kohya_ss-22.3.0\venv\lib\site-packages\accelerate\commands\launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\dowloads\\kohya_ss-22.3.0\\kohya_ss-22.3.0\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-refiner-1.0', '--train_data_dir=D:/LoRA_Modelmaker-Data/Model6/image', '--resolution=512,512', '--output_dir=D:/LoRA_Modelmaker-Data/Model6/model', '--logging_dir=D:/LoRA_Modelmaker-Data/Model6/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128', '--output_name=My_LoRA_fcb_sdxl', '--lr_scheduler_num_cycles=1', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=5200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--keep_tokens=1', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by Lecho303** [comment]
have u try to pick up v2、v_parameterization、SDXL Model?if u changing model,u need to pick up this 3 options
![v2-a4d1ad6b3b1693fee8145dd83f4eb9ba_r](https://github.com/bmaltais/kohya_ss/assets/153365532/63a9de5a-b016-46e8-9ca9-4f928818687a)
