### ISSUE TITLE
I get a crash when I try to trian SD 1.5 lora what are some things I should try ? 

### ISSUE THREAD

**Issue by Infinitusvoid** [bmaltais/kohya_ss#1997]
![image](https://github.com/bmaltais/kohya_ss/assets/84730862/5c1b9ec2-046a-42b7-aed1-aefd3d7c79f4)

**Comment by Infinitusvoid** [comment]
Than I used the 

`go to .\venv\scripts using cmd
write "activate", then "pip install bitsandbytes-windows"`

as here and it solved the issue 

[https://github.com/bmaltais/kohya_ss/issues/1704](url)

**Comment by waynespa** [comment]
@Infinitusvoid , you may want to use the `Reference` icon in the panel or a `#` to link an issue, the link you posted is not working.

#1704
