### ISSUE TITLE
ModuleNotFoundError: No module named 'xformers'

### ISSUE THREAD

**Issue by toyxyz** [bmaltais/kohya_ss#2]
If --use_8bit_adam and --xformers are used, ModuleNotFoundError is raised. Activate venv and do pip list, xformers 0.0.14.dev0 and bitsandbytes 0.35.0 are in the list. am i missing something? The python version is 3.10.6. The rest works just fine.

```
ModuleNotFoundError: No module named 'xformers'

ModuleNotFoundError: No module named 'bitsandbytes'
```

**Comment by toyxyz** [comment]
Deleting the repo completely and git clone again solved the problem.

**Comment by Tays-s** [comment]
still have this problem
