### ISSUE TITLE
[Feature request] FP8 training for finetuning

### ISSUE THREAD

**Issue by Goldenkoron** [bmaltais/kohya_ss#2009]
FP8 seems to work very well with lora training, is there any reason it couldn't be added for full finetuning? FP8 was giving me better training quality than full BF16.

EDIT: I see lycoris does have a native finetuning option which I guess works as a substitute for this maybe.

**Comment by bmaltais** [comment]
If kohya ever add support for it I should be able to add the switch to the GUI
