### ISSUE TITLE
Please implement all ui in gradio and remove tkinter dialogs,

### ISSUE THREAD

**Issue by Mikhael-Danilov** [bmaltais/kohya_ss#2016]
As for now some dialogs (file selectors, some messages) implemented in tkinter which renders then unaccessible when running gui on headless server.

**Comment by bmaltais** [comment]
There may be uncouth calls in headless mode. Please create a PR to fix those that.are causing the issue. The use of teinter is quite useful under windows and I don’t want to remove it… but headless should be functional enough to provide console messages instead of teinter…
