### ISSUE TITLE
Last step of installation - issue

### ISSUE THREAD

**Issue by Polukeev** [bmaltais/kohya_ss#202]
Hello!
When i try to use arrow buttons and choose fp16 option i have an error which ends with with line:
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: invalid character

How can i fix that?

**Comment by Polukeev** [comment]
For everyone who has the same issue i found out how to solve it:
![Screenshot_1](https://user-images.githubusercontent.com/45034807/219946202-a1b4911d-82d8-4007-ae7d-39eb775e5a2d.png)

First you need to go to your language setting of OS
And enable uft-8 option
Then try to accelerate your config again.
Arrows won't work still but you can use numbers 0,1,2 to select the option you need
Thank you

**Comment by vivexx** [comment]
> How can i fix that?

If your keyboard have numpad block on, you can turn off NumLock and just use "8" and "2" buttons for navigate without errors

**Comment by BothBosu** [comment]
Thanks! I have been figuring out this error and this helps me a lot.
