### ISSUE TITLE
Playground V2.5 support

### ISSUE THREAD

**Issue by DenRakEiw** [bmaltais/kohya_ss#2027]
Hello, is it possible to add Playground v2.5 to Kohya? It appears there is already a possibility to train through Diffusers. Here's the link https://github.com/huggingface/diffusers/blob/playground-dreambooth-lora/examples/dreambooth/train_dreambooth_lora_sdxl.py

**Comment by Benji-Montgomery** [comment]
I just wasted a day trying to get 2.5 to train with diffusers. I think we will probably have to wait for the next public release of diffusers to get it implemented into kohya_ss.

**Comment by rdcoder33** [comment]
> "PlaygroundAI released a new v2.5 model (playgroundai/playground-v2.5-1024px-aesthetic), which particularly excels at aesthetics. The model closely follows the architecture of Stable Diffusion XL, except for a few tweaks. This release comes with support for this model"
> 
> https://github.com/huggingface/diffusers/releases/tag/v0.27.0

Diffusers team also released a training script but it doesn't work well. Can we get a kohya implementation for it?
