### ISSUE TITLE
Kohya_ss GUI PURE edition

### ISSUE THREAD

**Issue by bmaltais** [bmaltais/kohya_ss#2029]
Starting a discussion about work being done to strip all sd-scripts code from this repo and use a "cloned" version of kohya_ss sd-scripts as the true source of python code to execute the training.

Since this is a major refactor of most of the code I think it is worth discussion issues you might encounter with it. The current refactored code is in the `dev-pure` branch.

Pleade give it a try by checking out that branch with:

```
git pull
git checkout dev-pure
```

Then start the gui as usual... hope everything will fall in place properly... this is the goal... but you will notice a much lighter file structure in the repo as now everything is referenced from the sd-scripts folder that get cloned at setup / run time.

**Comment by bmaltais** [comment]
I did run a test under WLS2 on the PURE codebse and all look good. Both Windows and Linux (Ubuntu) appear pretty solid.

**Comment by brentjohnston** [comment]
Sounds pretty great idea to me, what do you think the benefits of doing this potentially be? (I have no idea) I will help test this.

**Comment by bmaltais** [comment]
From a user point view it is fairly invisible, but this open the door for easier maintenance of the GUI.

**Comment by bmaltais** [comment]
@jim60105 OK, let's discuss the git submodule vs .gitignore local clone approach. I am really unsure of which is the least risky and least trouble to do upgrade and move to other branch for users. With the local clone method I know I could easilly tell a user to:

```
git pull
git checkout <branch name>
.\gui.bat or ./gui.sh
```

And the sd-scripts folder will be transparently updated... But I am unsure what the actual impact will be if I use submodule. My past experience make me think it will be much more troublesome for users to do something similar...

For you Dockerfile you could technically use the git submodule road as part of your build... especially if I specify a commit hash instead of a tag in the .sd-scripts-release file...

What do you think?

**Comment by jim60105** [comment]
```sh
git pull
git checkout <branch name>
git submodule update --init --recursive
.\gui.bat or ./gui.sh
```

Notice that the `git submodule` command only need to execute once, after that submodules will be checkout when executing `git checkout` in the main repository.

In terms of Dockerfile I implemented, all the project files should be obtained before docker building.
That is, if the user do `git clone --recursive`, the Dockerfile will work as usual.

Generally speaking, I do not perform `git clone` in Dockerfile.
I rarely do this, except in some CI/CD scenarios where I need to automate the building of specific versions of projects. Often doing this is where the Dockerfile becomes more and more complicated.

**Comment by jim60105** [comment]
In addition, I personally prefer to use `git fetch` instead of `git pull`, because `git pull` implies `merge`, which may create unexpected commits.

**Comment by bmaltais** [comment]
I have updated the dev-pure to use submodule. It is as much trouble to maintain as git clone but if it is more standard and easier then why not ;-) Look at the last commit and let me know if you find an issue with it

**Comment by jim60105** [comment]
git submodule is fixed on commit, not branch or tags
Unless you have such a need, just do `git checkout` in the parent folder and then `git submodule update --init --recursive` all the submodules will update. There is no need to go into the submodule folder for git operations.

**Comment by jim60105** [comment]
Other than that, I haven't tried docker build yet (it takes a little time to build such a large image), but I think it looks good

**Comment by bmaltais** [comment]
Is it possible to change the submodule commit without going in the sub module folder? Or is it possible to specify it in the .gitmodules file?

**Comment by bmaltais** [comment]
Ohhhh... if I git checkout <tag> in the sd-scripts it will actually get commited to the repo and this lock that version so that when a `git submodule update --init --recursive` is done that specific version will be used... brilliant ;-)

**Comment by jim60105** [comment]
`git checkout --recurse-submodules` should also do the trick during checkout.
I'm not sure if it does --init though, need to check the documentation.

**Comment by bmaltais** [comment]
Commited updated code. Much simpled this way. I have not used submodules much so learning as I go ;-)

```python
def update_submodule():
    """
    Ensure the submodule is initialized and updated.
    
    Parameters:
    - submodule_path: The relative path within the repository to the submodule.
    - branch_or_tag: The specific commit, tag, or branch to checkout in the submodule.
    """
    try:
        # Initialize and update the submodule
        subprocess.run(["git", "submodule", "update", "--init", "--recursive", "--quiet"], check=True)
        log.info("Submodule initialized and updated.")
        
    except subprocess.CalledProcessError as e:
        log.error(f"Error during Git operation: {e}")
    except FileNotFoundError as e:
        log.error(e)
```

**Comment by jim60105** [comment]
I have submit a PR for this changes #2032

**Comment by bmaltais** [comment]
Excellent, merged into dev-pure. This is looking pretty solid.

**Comment by bmaltais** [comment]
@wkpark If you have a functional a1111 extension I could add something about it in the README. Le me know and let's add something if it is the case.

**Comment by bmaltais** [comment]
I am updating the setup for windows to make things better. The old bitsandbytes files that were copied are causing more issues than good. I have disabled that from the setup code. Instead, installing the latest `https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.2.post2-py3-none-win_amd64.whl` work just as well.

I have also discovered a python module for cudnn that can install the required updated cudnn files without having to download them manually on windows. I have updated the instructions to suggest installing those for users with 39x0 and 40x0 cards.

This will turn out to be some major release. @wkpark has started work to make the GUI more streamlined (interestingly going back to the old accordions style rather than tabs to keep everything on the same page)... and a bunch of other things. Keep an eye in the Pull Request section if you want to discuss/contribute.

**Comment by bmaltais** [comment]
@wkpark Regarding the list offered to the users, I added an empty choice at the begining of each list to make sure it was not causing confusion to the users and issues with the feilds that are optional. You may have a better solution but for now this was a quick and dirty fix.
