### ISSUE TITLE
CUDNN 9.0 

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2030]
https://docs.nvidia.com/deeplearning/cudnn/release-notes.html#cudnn-9-0-0

Is it possible to add Cudnn 9.0 

The cuDNN backend API uses less memory for many execution plans which should be beneficial for users who cache execution plans.

FP16 and BF16 fused flash attention engine performance has been significantly improved for NVIDIA GPUs:

Speed-up of up to 50% over cuDNN 8.9.7 on Hopper GPUs.

Speed-up of up to 100% over cuDNN 8.9.7 on Ampere GPUs.

**Comment by bmaltais** [comment]
Hello @DarkViewAI ,

It might work but this is really something that need to be discussed with kohya_ss in his sd-script repo. Can you open an issue directly with him (or even better, if you test cudnn-9.0.0 and it work you could submir a PR)?

I only leverage his code and don't want to stray too far from what he support as this will only lead to trouble for users of the GUI...

Bernard
