### ISSUE TITLE
Wandb funtional request.

### ISSUE THREAD

**Issue by KwangryeolPark** [bmaltais/kohya_ss#2034]
I want to add tag to wandb like below:
```python
wandb.init(
...
tags=[args.class_label, args.instance_label]
```

I hope it is automatically done.

**Comment by bmaltais** [comment]
Hi, this is probably a request for kohya_ss under his sd-scripts repo. This repo only maintain the code to wrap kohya's sd-scripts with a GUI. Any new functionality not already provided by his scripts need to be requested to kohya. Once he add support for it it is then possible to implement the support for it in the GUI.
