### ISSUE TITLE
When installing kohya i get the error system cannot find path

### ISSUE THREAD

**Issue by MoriDBagon** [bmaltais/kohya_ss#2037]
E:\SD\kohya_ss>.\setup.bat
Warning: Python version 3.10.9 is recommended.
Creating venv...
Python System cannot find the path
System cannot find the path
Python System cannot find the path

**Comment by bmaltais** [comment]
Have you properly installed python 3.10.9 following the pre requirements instructions: https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#windows-pre-requirements

**Comment by princehonour** [comment]
same problem, how to fix it?
