### ISSUE TITLE
There is not enough 8Gb of VRAM after the upgrade.

### ISSUE THREAD

**Issue by sashaok123** [bmaltais/kohya_ss#204]
After the update, VRAM stopped being enough.
I have 8Gb of VRAM and everything worked fine before.
Now it is impossible to create LoRA on SD2.1 even in 512x512, there is a memory shortage error, then 20mb, then 2mb.
Tried different batch, even 1
Tried turning on and off "Enable buckets"
I tried different sizes of the dataset from 512x512 to 1024x1024
I set the "Memory efficient attention" setting, it doesn't help either.
I also tried different SD2.1 models, the original diffuse and pruned version.
<img width="851" alt="image" src="https://user-images.githubusercontent.com/27728380/219951180-9a3f5cfc-48ef-4780-bbae-c083c42af56e.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/27728380/219951202-42afb89c-9364-4877-8399-b1552c017a1f.png">

**Comment by runner22k** [comment]
Oh! I was happy that "DAdaptation" was added and I was looking forward to train a model, few hours a day and finish 4hrs. But now 8GB is not enough! its bad.
