### ISSUE TITLE
bitsandbytes 0.43.0 released with official windows support!

### ISSUE THREAD

**Issue by wkpark** [bmaltais/kohya_ss#2041]
https://pypi.org/project/bitsandbytes/
https://github.com/TimDettmers/bitsandbytes/releases/tag/0.43.0

- windows support with cuda 11.7, 11.8, 12.0, 12.1, 12.2, 12.3 dll (all dlls are included in the wheels)

**Comment by bmaltais** [comment]
That is great. I will test it and add it to the requirements if it does. Thank you for pointing it out.
