### ISSUE TITLE
The 'six' package is required

### ISSUE THREAD

**Issue by Phill526** [bmaltais/kohya_ss#2049]
Hello guys! Help me solve next problem:
Warning: Python version 3.10.9 is recommended.
Traceback (most recent call last):
  File ".\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\HYPERPC\Documents\cohya\kohya_ss\setup\setup_common.py", line 11, in <module>
    import pkg_resources
  File "C:\Users\HYPERPC\Documents\cohya\kohya_ss\venv\lib\site-packages\pkg_resources\__init__.py", line 57, in <module>
    from pkg_resources.extern import six
  File "C:\Users\HYPERPC\Documents\cohya\kohya_ss\venv\lib\site-packages\pkg_resources\extern\__init__.py", line 54, in load_module
    "distribution.".format(**locals())
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

**Comment by bmaltais** [comment]
It appear as if you are not using the required python version as required by as-scripts. Make sure to install python 3.10.9 as per the instructions in the README.

**Comment by Phill526** [comment]
It installed 
![image](https://github.com/bmaltais/kohya_ss/assets/162844134/db410bce-e327-4160-ba79-47b02958ce0f)

**Comment by Phill526** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/162844134/1fbe13a6-2dfe-4cdf-a425-a488a9559afb)

**Comment by bmaltais** [comment]
Make sure python 3.10.9 is the default version such that when kohua_gui run it is the version running. The warning shown in the log is showing it is not and this is why you are running into this issue.

**Comment by Phill526** [comment]
Okay, 

> Make sure python 3.10.9 is the default version such that when kohua_gui run it is the version running. The warning shown in the log is showing it is not and this is why you are running into this issue.

Okey, i ll try. But i dont know how check and make python 3.10.9 is the default version? Could u help? Describe)

**Comment by Phill526** [comment]
GPT Chat helped 
(venv) C:\Users\HYPERPC\Documents\cohya\kohya_ss>python --version
Python 3.7.9
So, how to make 3.10.9 the default version?

**Comment by bmaltais** [comment]
Good question... you could try uninstalling the old python version so windows will use 3.10.9 as the default?

**Comment by sugarkwork** [comment]
The same problem occurred on my PC, but after rewriting setup.bat as follows, this error disappeared.

IF NOT EXIST venv (
    echo Creating venv...
    python -m venv venv
)

↓

IF NOT EXIST venv (
    echo Creating venv...
    **python3.10** -m venv venv
)
