### ISSUE TITLE
No data found within folder of 15 images.

### ISSUE THREAD

**Issue by captainweasly** [bmaltais/kohya_ss#205]
Just started my first Dreambooth Lora training and got the  "No data found" error, path is correct with tranining data.

![image](https://user-images.githubusercontent.com/115602603/219954399-f12e836f-3618-49e1-a5cc-13fd3bd92afd.png)

**Comment by elv56** [comment]
Hello, did you find a solution ? Im having the same error message
Also tried the FileNotFoundError fix but still no results
