### ISSUE TITLE
Training Process Dies Without Details

### ISSUE THREAD

**Issue by Kagenokami** [bmaltais/kohya_ss#2051]
When attempting to run training on the latest update of khoya_ss (fresh install, accelerate config ran) the program runs the training commands - failing to find accelerate as a program - before quietly closing the process without any additional information. When attempting to 'stop' what one would assume is a hung training, it alerts that there is no running process. 

**PLEASE NOTE: This is for the latest 23.0.1 version**

Details below:

23:25:00-065004 INFO     Start training LoRA Standard ...                      
23:25:00-065004 INFO     Checking for duplicate image filenames in training    
                         data directory...                                     
23:25:00-066000 INFO     Valid image folder names found in:                    
                         C:/Artifice/StabilityMatrix/DataSet/Nox/images        
23:25:00-066000 INFO     Folder 40_Tm94 Nox: 20 images found                   
23:25:00-067501 INFO     Folder 40_Tm94 Nox: 800 steps                         
23:25:00-068503 INFO     Total steps: 800                                      
23:25:00-068503 INFO     Train batch size: 1                                   
23:25:00-069505 INFO     Gradient accumulation steps: 1                        
23:25:00-070505 INFO     Epoch: 1                                              
23:25:00-070505 INFO     Regulatization factor: 1                              
23:25:00-071505 INFO     max_train_steps (800 / 1 / 1 * 1 * 1) = 800           
23:25:00-071505 INFO     stop_text_encoder_training = 0                        
23:25:00-072505 INFO     lr_warmup_steps = 0                                   
23:25:00-073505 INFO     Saving training config to                             
                         C:/Artifice/StabilityMatrix/DataSet/Nox/model\NoxV4_20
                         240309-232500.json...                                 
23:25:00-074505 INFO     accelerate launch --multi_gpu                         
                         --num_cpu_threads_per_process=24                      
                         "C:\Artifice\StabilityMatrix\Packages\kohya_ss/sd-scri
                         pts/train_network.py"  --bucket_no_upscale            
                         --bucket_reso_steps=64 --cache_latents                
                         --caption_extension=".txt" --enable_bucket            
                         --min_bucket_reso=256 --max_bucket_reso=2048          
                         --keep_tokens="1" --learning_rate="0.0001"            
                         --logging_dir="C:/Artifice/StabilityMatrix/DataSet/Nox
                         /log" --lr_scheduler="cosine"                         
                         --lr_scheduler_num_cycles="1"                         
                         --max_data_loader_n_workers="8" --max_grad_norm="1"   
                         --resolution="512,512" --max_train_steps="800"        
                         --mixed_precision="fp16" --network_alpha="1"          
                         --network_dim=8 --network_module=networks.lora        
                         --optimizer_type="AdamW8bit"                          
                         --output_dir="C:/Artifice/StabilityMatrix/DataSet/Nox/
                         model" --output_name="NoxV4"                          
                         --pretrained_model_name_or_path="C:/Artifice/Stability
                         Matrix/Models/StableDiffusion/yiffymix_v41.safetensors
                         " --save_every_n_epochs="1"                           
                         --save_model_as=safetensors --save_precision="fp16"   
                         --shuffle_caption --train_batch_size="1"              
                         --train_data_dir="C:/Artifice/StabilityMatrix/DataSet/
                         Nox/images" --xformers                                
'accelerate' is not recognized as an internal or external command,
operable program or batch file.
23:25:56-123437 INFO     There is no running process to kill.

**Comment by Kagenokami** [comment]
I did manage to get further. Some details on 23.0.1 fixes.

To get the application to launch successfully one must first:
move wd14_caption_gui.py from **..\kohya_ss\kohya_gui** to **..\kohya_ss\library** this folder needs created.

Next, I had to make the following change to **..\kohya_ss\kohya_gui\lora_gui.py**:
**run_cmd = "accelerate launch"** to **run_cmd = fr' "{scriptdir}/venv/Scripts/accelerate-launch.exe"'**

Finally, I needed to manually download the contents of **..\kohya_ss\sd-scripts** from this repository to my local installation.

At this point I received new errors appearing to indicate a missing NCCL package, as well as some client socket failures. I will not proceed further with this for the time being but will save the error log in case it proves useful. Hope some of this may help!

**Comment by Kagenokami** [comment]
Alright. Correction. Going back to 22.6.2, that final error I got is the same error I receive when attempting to run the training... Details below:

**Comment by storuky** [comment]
Windows doesn't support NCCL as a backend. Try to set `PL_TORCH_DISTRIBUTED_BACKEND = "gloo"` env.

**Comment by Kagenokami** [comment]
> PL_TORCH_DISTRIBUTED_BACKEND = "gloo"

Where exactly should I place this?

**Comment by bmaltais** [comment]
One suggestion, hit the "Print" button to see what parameters the GUI is setting... Also, try using the previous version that does not crash and do the same.

Then provide both in this discussion. Perhaps the new GUI is not setting everything as it shold (quite possibly) and is causing the crash.

**Comment by Kagenokami** [comment]
> run_cmd = fr' "{scriptdir}/venv/Scripts/accelerate-launch.exe"'

https://pastebin.com/M6cLiR0Q

**Comment by Kagenokami** [comment]
This new error arrises as a result of running v23.0.1 after repeating accelerate-config turn manually turn off multiple GPU, sidestepping the need for NCCL or gloo.

https://pastebin.com/fgKYHPH0

**Comment by bmaltais** [comment]
This appear to be the issue:

`ValueError: torch.cuda.is_available() should be True but is False. xformers' memory efficient attention is only available for GPU`

**Comment by Kagenokami** [comment]
I do not have memory efficient attention turned on however. And as far as I can tell, I do have the appropriate software installed. Thoughts on a fix?

**Comment by bmaltais** [comment]
> I do not have memory efficient attention turned on however. And as far as I can tell, I do have the appropriate software installed. Thoughts on a fix?

Are you seeing --xformers listed in the command the GUI generate? Maybe it is a bug with the GUI not properly handling the xformers gui selection...

**Comment by Kagenokami** [comment]
Hmmm. I see the section that says xformers within the gui. I thought I have/had xformers installed though. But I will do a run with that dropdown changed and update this comment with the results in one moment.

**Comment by bmaltais** [comment]
Are you running python 3.10.9? Something appear to be seriously wrong with your setup for causing all those errors.

**Comment by bmaltais** [comment]
This error in the log is weird

RuntimeError: "slow_conv2d_cpu" not implemented for 'Half

Are you training in fp16? Does it work with v226.9?

**Comment by Kagenokami** [comment]
I thought the same. It appears that it is 3.10.11 that is installed. I make use of Stability Matrix to install the requirements in their own venv specifically for kohya so that I don't run into versioning conflicts with my other AI applications. The recent items are for the unstable v23.0.1 which sees sd-scripts failing to install with the rest of the package. So there is very likely a fair bit of mess. However, I was receiving the same initial errors on the final 22 version.

**Comment by bmaltais** [comment]
Can you not simply run ./setup.sh to vreate the venv and install everything? Why manually install the requirements?

**Comment by Kagenokami** [comment]
> Can you not simply run ./setup.sh to create the venv and install all the python requirements for linux? Why manually install the requirements?

That is how it's being installed. I don't manually install things. I just brought it up since I know some folks don't like the use of venv's. Also...this is a Windows installation, not a Linux installation

**Comment by bmaltais** [comment]
Interesting... so I really don't know why it won't work properly... Maybe it is the fact that it is python v3.10.11? But I don't think so...

Can you try training one of the test config files under the test/config folder? Try training a Standard LoRA. THis always work for me.

**Comment by Kagenokami** [comment]
> Interesting... so I really don't know why it won't work properly... Maybe it is the fact that it is python v3.10.11? But I don't think so...
> 
> Can you try training one of the test config files under the test/config folder? Try training a Standard LoRA. THis always work for me.

I'll give it a try. One moment. I'll update this with my findings in...2 minutes?

**Comment by bmaltais** [comment]
Is CUDA installed on your Windows PC?

**Comment by Kagenokami** [comment]
18:35:25-508791 INFO     Version: v23.0.1

18:35:25-512928 INFO     nVidia toolkit detected
18:35:27-061622 INFO     Torch 2.1.2+cu118
18:35:27-111820 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
18:35:27-116946 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 Laptop GPU VRAM 16376 Arch (8, 9) Cores 76
18:35:27-119946 ERROR    [WinError 2] The system cannot find the file specified
18:35:27-120946 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
18:35:27-123452 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         xformers==0.0.23.post1+cu118 --index-url https://download.pytorch.org/whl/cu118
18:35:30-395601 INFO     Verifying modules installation status from requirements.txt...
18:35:34-204757 INFO     headless: False
18:35:34-207756 INFO     Load CSS...

**Comment by bmaltais** [comment]
This error is supposed to report the python version you are using but it fail... Perhaps your issue is how python was installed?

`18:35:27-119946 ERROR [WinError 2] The system cannot find the file specified`

Can you uninstall the current version of Python you have and re-install it following those instructions:

https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#windows-pre-requirements

**Comment by Kagenokami** [comment]
Okay. So...couple things.

I snagged the new version and attempted to run setup.bat. However, without the venv existing in the file it could not run python, and with my existing venv it would get mad about 3.10.11. I surmounted that by creating a new venv using the embeddable package for python 3.10.9. However, the new error it throws, after I got it to recognize that there was, in fact, a venv with python for it to use, is the following:

(venv) PS C:\Artifice\StabilityMatrix\Packages\kohya_ss> .\setup.bat
Traceback (most recent call last):
  File "C:\Artifice\StabilityMatrix\Packages\kohya_ss\setup\setup_windows.py", line 7, in <module>
    import setup_common
ModuleNotFoundError: No module named 'setup_common'

**Comment by bmaltais** [comment]
I think this all stem from the fact that the version of python is not installed to the liking of the GUI... Let me try to upgrade my version of python to 3.10.11 and see why it does not like that version... maybe it is causing a bug in the code...

**Comment by bmaltais** [comment]
OK, I upgraded my system to python 3.10.11 and all is working fine. Training work as expected.

So, I think all the issues are from the fact that you are not using the python.org 3.10.11 package but rather something from StabilityMatrix. Their Python install is probably missing a few things and will not work with Kohya_ss GUI. Hope you can figure how to make it work... I only support native python.org version of Python at the moment.

**Comment by Kagenokami** [comment]
> OK, I upgraded my system to python 3.10.11 and all is working fine. Training work as expected.
> 
> So, I think all the issues are from the fact that you are not using the python.org 3.10.11 package but rather something from StabilityMatrix. Their Python install is probably missing a few things and will not work with Kohya_ss GUI. Hope you can figure how to make it work... I only support native python.org version of Python at the moment.

At the moment I am using an embedded 3.10.9 installation of python directly from their website as opposed to what was installed by Stability Matrix. If it would be helpful, I can send you my virtual environment folder. Or coordinate to discuss over telegram or the like. I'm fine living with 22.6.0 if all else fails but wanted to try and help when I noticed some of the errors.

**Comment by bmaltais** [comment]
I have updated the readme to point to the release of python 3.10.11 that worked for me. I ha to uninstall my previous python version, install the new one and then reboot so it would be properly visible.

Also, make sure to install the CUDA Toolkit 11.8 on your windows machine... I added that step to the README also and a link to get that release.

After that I hope everything will install fine. Make sure to delete the venv and let setup.bat create it.

**Comment by Kagenokami** [comment]
I'm not sure that will work in my instance, simply due to the fact that I don't HAVE a global installation of Python. But I will give it a try at the very least. The way that I install python, it doesn't have a global path at all. I unpackage the embedded version and run that to create a valid venv. But it is never added to path or 'installed' in a typical manner. This worked prior, and it does recognize the installation when running scripts, so not sure what's wrong with the versions past 22.6.0

**Comment by bmaltais** [comment]
I am not sure why decoupling the sd-scripts from my repo into a submodule could cause that... but it is a "significant" change and I am not surprised it might cause all sort of headhake... Sorry about that. But having things seperate like it is now will make things much cleaner in the long run as I don't have to maintain kohya's code directly as file copy in my repo.

**Comment by bmaltais** [comment]
Installing the local version of python with the full system path might help you better understand why the StableMatrix matrix mewthod is not working and find the right fix for it...

**Comment by Kagenokami** [comment]
I try to avoid a direct install of python due to...past headaches with python versioning that almost resulted in a drive wipe when it comes to AI programs.  I will tinker a bit more. I don't imagine that you decoupling the scripts was a terribly huge deal. I do know that it caused StabilityMatrix to miss that installation, but that's on them to fix. I don't mind personally pulling those files to get things to run. Getting the environment to work manually is definitely a challenge though.

**Comment by Kagenokami** [comment]
(venv) PS C:\Artifice\StabilityMatrix\Packages\kohya_ss> .\gui.bat --headless
21:01:49-967819 INFO     Kohya_ss GUI version: v23.0.3
21:01:50-655234 INFO     Submodule initialized and updated.
21:01:50-658662 INFO     nVidia toolkit detected
21:01:51-855687 INFO     Torch 2.1.2+cu118
21:01:51-878227 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
21:01:51-880231 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 Laptop GPU VRAM 16376 Arch (8, 9) Cores 76
21:01:51-881231 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
21:01:51-882230 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
21:01:51-884228 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         xformers==0.0.23.post1+cu118 --index-url https://download.pytorch.org/whl/cu118
21:01:53-828867 INFO     Verifying modules installation status from requirements.txt...
Traceback (most recent call last):
  File "C:\Artifice\StabilityMatrix\Packages\kohya_ss\kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "C:\Artifice\StabilityMatrix\Packages\kohya_ss\dreambooth_gui.py", line 5, in <module>
    from kohya_gui.dreambooth_gui import dreambooth_tab
  File "C:\Artifice\StabilityMatrix\Packages\kohya_ss\kohya_gui\dreambooth_gui.py", line 8, in <module>
    from .common_gui import (
  File "C:\Artifice\StabilityMatrix\Packages\kohya_ss\kohya_gui\common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
(venv) PS C:\Artifice\StabilityMatrix\Packages\kohya_ss>

No such luck, sadly.

**Comment by bmaltais** [comment]
Darn... I could probably trap that so it does not traceback...

**Comment by bmaltais** [comment]
Do:

```
git pull
git checkout dev
```

then try running headless again

**Comment by Kagenokami** [comment]
One moment. I might have found a tkinter workaround to get it functioning.

**Comment by Kagenokami** [comment]
I went ahead and ran what you requested. Here is the result: https://pastebin.com/vLJbTtqp

That said, on the venv I tinkered with, I did manage to get tkinter working and the application launched after running .\setup.bat as usual. For some reason Windows won't let you install tkinter without going through the installer, so I installed locally without any path modifications and forced a new venv creation with tkinter included. That did the trick. Not pleased I had to install python but at least it wasn't global and never hit my PATH, so uninstalling it shouldn't be a huge headache like last time and it won't interfere with my other installs.

Going to test if it will run one of the sample trainings now.

**Comment by Kagenokami** [comment]
Result: https://pastebin.com/zHKAKrrs

**Comment by bmaltais** [comment]
Look like msgbox is also looking for tkinter... oh well... glad installing the standard python without the path worked.

**Comment by bmaltais** [comment]
Did you try to disable xformers?

**Comment by Kagenokami** [comment]
I forgot about that until I saw the error. Though I'd like to mention that I never used to have issues with xformers prior...

Having said that, I've reached the caching latents... step. It appears to be hanging, but it isn't spitting errors - yet.

**Comment by bmaltais** [comment]
YOu could also try sdpa instead of xformers... not sure why xformers is giving the ghost... did you try deleting the full venv then recreate it using setup.bat? xformers should be properly installed that way

**Comment by Kagenokami** [comment]
It ran through the process of installing xformers and didn't throw an issue. I can try a full reinstall again and see what happens. One moment.

**Comment by Kagenokami** [comment]
Didn't have much better luck with that. Unfortunately, at this point I've got to rest. Tomorrow I will try a more 'typical' installation after work. I feel like it's not just the virtual environment at this point...

**Comment by Kagenokami** [comment]
I did manage to get the latest version working it seems, including with xformers active. I cannot run with multi-gpu due to the NCCL/gloo issue, which is expected. The program spits triton warnings 10 times during the process of beginning training however. So maybe check into where it calls to print that warning?
