### ISSUE TITLE
Starting Lora SDXL training crashing vast.ai server with latest version.

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [bmaltais/kohya_ss#2052]
Using RTX 3090 on vast.ai server with latest version.
It crashed 2 separate hosts, with the same setting that used to work before the update.

**Comment by ashleykleynhans** [comment]
What do you mean by "crashing server"?
What do the logs say etc?
This issue isn't very useful without additional details.

**Comment by bmaltais** [comment]
Strange. Some of the requirements were updated but mostly for windows... so probably not that on a linux based OS.

When does it crash? At GUI load time? When you hit start?

What is shown in the logs when that happen?

**Comment by a-l-e-x-d-s-9** [comment]
@ashleykleynhans
I don't have any logs because the server crashed.
By "crashed" I mean that the server stopped working completely, any communication was lost with him, and his status changed to offline. And it happened to two different servers.
There were a lot of changes in the last few commits that caused it, I don't know which one exactly, and I don't have a way to debug it locally.
That's all the information I have.

**Comment by ashleykleynhans** [comment]
@bmaltais nothing wrong with the Linux requirements, many people use my template on RunPod which runs Ubuntu 22.04 LTS without any issues, so seems to be a vast.ai specific issue.

@a-l-e-x-d-s-9  what kind of GPU were you using?  The GPU probably ran out of VRAM.

**Comment by a-l-e-x-d-s-9** [comment]
@bmaltais 
When I ran the GUI it updated a few packages, I loaded a file with settings, and changed samples via GUI, after clicking on start training it started loading the images, and then the server died. I only have 150 images that were already used for training in the past, so they are fine. 
The server had RTX 3090 with 24GB Vram - even if there is an issue with OOM, it shouldn't have crashed the server.

**Comment by ashleykleynhans** [comment]
I have personally never heard of a server crashing.  Sounds like its a vast.ai issue, this kind of thing doesn't happen on RunPod.  On RunPod there is always an error in the log, whether its OOM or any other error for that matter.

**Comment by a-l-e-x-d-s-9** [comment]
I will try another server, and add whatever logs I will get.

**Comment by a-l-e-x-d-s-9** [comment]
I think that it was crashing due to an incompatible bitsandbytes version that I installed when I tried to fix another issue.
