### ISSUE TITLE
Unable to perform Dreambooth LoRA training

### ISSUE THREAD

**Issue by captainweasly** [bmaltais/kohya_ss#206]
Images were put inside the correct folder with correct path set, running my first training states I have no training date, but i reality I have 15 images.

**Update**: Turns out there is a specific folder structure needed and I have amended, files are able to be loaded.

**Comment by captainweasly** [comment]
Manage to get the folder structure correct but a new error.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\Captain-Weasly\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 400
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 200
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 200
Traceback (most recent call last):
  File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in <module>
    train(args)
  File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
    "ss_noise_offset": args.noise_offset,
AttributeError: 'Namespace' object has no attribute 'noise_offset'
Traceback (most recent call last):
  File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Captain-Weasly\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Captain-Weasly\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main    args.func(args)
  File "C:\Users\Captain-Weasly\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Captain-Weasly\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Captain-Weasly\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/Captain-Weasly/stable-diffusion-webui/models/Stable-diffusion/AOM3A3 F222 D0.3 Cafe 0.2 Kurenai 0.2.ckpt', '--train_data_dir=C:/Users/Captain-Weasly/LoRA_Training/image', '--resolution=768,768', '--output_dir=C:/Users/Captain-Weasly/LoRA_Training/model', '--logging_dir=C:/Users/Captain-Weasly/LoRA_Training/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=20', '--train_batch_size=2', '--max_train_steps=200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by nahojjjen** [comment]
I encountered the same error as your second comment. You should remove/ edit your initial post as it's not a valid issue. Your second comment however seems like it might be a real issue.

> Traceback (most recent call last):
> File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in
> train(args)
> File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
> "ss_noise_offset": args.noise_offset,
> AttributeError: 'Namespace' object has no attribute 'noise_offset'
> Traceback (most recent call last):
> File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> return _run_code(code, main_globals, None,
> File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
> exec(code, run_globals)

My current workaround is to revert to the v20.7.2 version which still works for me.

**Comment by Bellatrix8** [comment]
> I encountered the same error as your second comment. You should remove/ edit your initial post as it's not a valid issue. Your second comment however seems like it might be a real issue.
> 
> > Traceback (most recent call last):
> > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in
> > train(args)
> > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
> > "ss_noise_offset": args.noise_offset,
> > AttributeError: 'Namespace' object has no attribute 'noise_offset'
> > Traceback (most recent call last):
> > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> > return _run_code(code, main_globals, None,
> > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
> > exec(code, run_globals)
> 
> My current workaround is to revert to the v20.7.2 version which still works for me.

Hey, how did you revert to an older version?

**Comment by captainweasly** [comment]
> I encountered the same error as your second comment. You should remove/ edit your initial post as it's not a valid issue. Your second comment however seems like it might be a real issue.
> 
> > Traceback (most recent call last):
> > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in
> > train(args)
> > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
> > "ss_noise_offset": args.noise_offset,
> > AttributeError: 'Namespace' object has no attribute 'noise_offset'
> > Traceback (most recent call last):
> > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> > return _run_code(code, main_globals, None,
> > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
> > exec(code, run_globals)
> 
> My current workaround is to revert to the v20.7.2 version which still works for me.

> 

I'll give it a test in a couple of hours.

**Comment by fifth-dimensional** [comment]
> > I encountered the same error as your second comment. You should remove/ edit your initial post as it's not a valid issue. Your second comment however seems like it might be a real issue.
> > > Traceback (most recent call last):
> > > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in
> > > train(args)
> > > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
> > > "ss_noise_offset": args.noise_offset,
> > > AttributeError: 'Namespace' object has no attribute 'noise_offset'
> > > Traceback (most recent call last):
> > > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> > > return _run_code(code, main_globals, None,
> > > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
> > > exec(code, run_globals)
> > 
> > 
> > My current workaround is to revert to the v20.7.2 version which still works for me.
> 
> Hey, how did you revert to an older version?

I was getting the same error, but the suggestion to use the previous version worked for me. I cloned the prior version using...

`git clone https://github.com/bmaltais/kohya_ss.git --branch v20.7.2`

**Comment by Bellatrix8** [comment]
> > > I encountered the same error as your second comment. You should remove/ edit your initial post as it's not a valid issue. Your second comment however seems like it might be a real issue.
> > > > Traceback (most recent call last):
> > > > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 573, in
> > > > train(args)
> > > > File "C:\Users\Captain-Weasly\kohya_ss\train_network.py", line 356, in train
> > > > "ss_noise_offset": args.noise_offset,
> > > > AttributeError: 'Namespace' object has no attribute 'noise_offset'
> > > > Traceback (most recent call last):
> > > > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
> > > > return _run_code(code, main_globals, None,
> > > > File "C:\Users\Captain-Weasly\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in run_code
> > > > exec(code, run_globals)
> > > 
> > > 
> > > My current workaround is to revert to the v20.7.2 version which still works for me.
> > 
> > 
> > Hey, how did you revert to an older version?
> 
> I was getting the same error, but the suggestion to use the previous version worked for me. I cloned the prior version using...
> 
> `git clone https://github.com/bmaltais/kohya_ss.git --branch v20.7.2`

So to revert to the previous version I just need to type this command with cmd or use git bash?
