### ISSUE TITLE
New Installation Error (Runpod installer)

### ISSUE THREAD

**Issue by PsySpyGaming** [bmaltais/kohya_ss#2061]
Running setup_linux.py...
Traceback (most recent call last):
  File "/workspace/kohya_ss/setup/setup_linux.py", line 3, in <module>
    import setup_common
  File "/workspace/kohya_ss/setup/setup_common.py", line 13, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
WARNING: No matching packages

It worked yesterday morning, not working this morning, so must have been a change between then and now.

**Comment by bmaltais** [comment]
Ah... I added some validation to the python version being used and rely on this new package... It will need to be pip installed at the very begining of the setup... I can try to see how this can be weaved into the runpod installer...

**Comment by PsySpyGaming** [comment]
Thanks, at least it's getting past that step it got stuck on now. Appreciate your diligence!

**Comment by bmaltais** [comment]
What is it stuck on?

**Comment by PsySpyGaming** [comment]
Seems to install correctly though I haven't tested running it yet as I was in a meeting for work

**Comment by svitiashchuk** [comment]
I am on MacBook M1 and I'm experiencing the same issue with the mentioned error during execution of `setup.sh`:
`ModuleNotFoundError: No module named 'packaging'`

Installing manually `packaging` allows to setup via `./setup.sh`:

```shell
# manually create venv dir
python3.10 -m venv venv

# activate venv
source venv/bin/activate

# install "packaging" dependency
python -m pip install --upgrade packaging
```

Creating venv is manually is required to make sure you're consistent with your python version and installed packages.

**Comment by bmaltais** [comment]
Should be fixed in latest release.
