### ISSUE TITLE
Training brakes from "A matching Triton is not available, some optimizations will not be enabled. Error caught was: No module named 'triton" even when there are no triton dependent options enabled

### ISSUE THREAD

**Issue by MarineBirch723** [bmaltais/kohya_ss#2063]

**Comment by bmaltais** [comment]
THis is normal on windows. Triton report errors but does not cause any issues.

**Comment by MarineBirch723** [comment]
Except that it does for me. It keeps queuing the massage therefore it doesn't start training.

**Comment by bmaltais** [comment]
Humm, try training one of the test config under test/config

for example try the standard adamw8bit one

does it work?

**Comment by iamrohitanshu** [comment]
@MarineBirch723 It will give that error once at the start and then like 8 times consecutively before starting training.
Did you wait till then?

**Comment by user83922** [comment]
For me it repeats endlessly.

**Comment by user83922** [comment]
For me it repeats 24 times (the amount I've given for max data loader). Then it starts training. Correlation between those two is beyond my knowledge.

What's typical koyha_ss behaviour though: I have Triton installed and works flawlessly with other tests in the venv specific for koyha_ss.

**Comment by bmaltais** [comment]
I always set max data loader to avoid this annoying behaviour

**Comment by iamrohitanshu** [comment]
@user83922 Yes, I have data loader set as 8. So, that's the reason. Good to know, Thanks!
@bmaltais What do you set it to? 1? or 0? Or are you saying you set it in some other way?

**Comment by bmaltais** [comment]
@iamrohitanshu simply set it to 0

**Comment by iamrohitanshu** [comment]
@bmaltais Thanks you!

**Comment by bmaltais** [comment]
I have added built-in support to install Triton 2.1.0 for windows in the setup.bat menu. Look in the dev branch or wait for the next release.

**Comment by waifuista** [comment]
The same thing is happening to me, do you know how to solve it?
