### ISSUE TITLE
Paperspace (Runpod installer) - The current version of python is not appropriate to run Kohya_ss GUI 

### ISSUE THREAD

**Issue by MRX82** [bmaltais/kohya_ss#2070]
02:10:04-084671 INFO     Submodule initialized and updated.                                                                                                                                                                   
02:10:04-090913 INFO     Installing python dependencies. This could take a few minutes as it downloads files.                                                                                                                 
02:10:04-093946 INFO     If this operation ever runs too long, you can rerun this script in verbose mode to check.                                                                                                            
02:10:04-093946 INFO     Kohya_ss GUI version: v23.0.5                                                                                                                                                                        
02:10:04-094820 INFO     Python 3.9.16 on Linux                                                                                                                                                                               
02:10:04-096860 INFO     Installing modules from requirements_runpod.txt... 
.......
kohya_ss# ./gui.sh --share --headless
01:53:31-886869 INFO     Kohya_ss GUI version: v23.0.5                                                                                                                                                 
01:53:32-210476 INFO     Submodule initialized and updated.                                                                                                                                            
01:53:32-213025 INFO     nVidia toolkit detected                                                                                                                                                       
01:53:56-652037 INFO     Torch 2.1.2+cu118                                                                                                                                                             
01:53:57-890578 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                                                                                                    
01:53:57-920347 INFO     Torch detected GPU: Quadro P5000 VRAM 16273 Arch (6, 1) Cores 20                                                                                                              
01:53:57-922402 INFO     Python version is 3.9.16 (main, Dec  7 2022, 01:11:51)                                                                                                                        
                         [GCC 9.4.0]                                                                                                                                                                   
01:53:57-924505 ERROR    The current version of python is not appropriate to run Kohya_ss GUI                                                                                                          
01:53:57-925704 ERROR    The python version needs to be greater or equal to 3.10.9 and less than 3.11.0                                                                                                
Validation failed. Exiting...

**Comment by okingjo** [comment]
Just upgrade your python to 3.10.11 and you should be okay. I saw your current version is 3.9.16, that is too old. The new scripts needs it to be between 3.10.10 and 3.11
I just encounter the same issue my self, mine was 3.10.8

**Comment by bmaltais** [comment]
I could reduce the restriction… but since 3.10.9+ has been available for so long it should not be an issue to use something between >= 3.10.9 and < than 3.11.0

this make troubleshooting much easier.

**Comment by Kadah** [comment]
I'm suddenly getting this as well after updating from a few days ago. The thing is, I already updated to 3.10.13.

```
04:50:35-447293 INFO     Kohya_ss GUI version: v23.0.5                                                                                                   
04:50:35-487103 INFO     Submodule initialized and updated.                                                                                              
04:50:35-488378 INFO     nVidia toolkit detected                                                                                                         
04:50:36-284812 INFO     Torch 2.0.1+cu118                                                                                                               
04:50:36-312475 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700                                                                                      
04:50:36-371592 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24217 Arch (8, 9) Cores 128                                                    
04:50:36-373184 INFO     Python version is 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0]                                                             
04:50:36-374118 ERROR    The current version of python is not appropriate to run Kohya_ss GUI                                                            
04:50:36-374812 ERROR    The python version needs to be greater or equal to 3.10.9 and less than 3.11.0                                                  
Validation failed. Exiting...
kadah@FBB-3090:/ai/training/bmaltais_kohya_ss$ python --version
Python 3.10.13
```

**Comment by petepete333** [comment]
Reducing the restriction would be amazing since Paperspace (Gradient) uses 3.9.16 as default version of Python and changing it is difficult for someone who's not familiar with the coding. Thanks.

**Comment by Rockbdn** [comment]
Check this: [Engineer-of-Stuff/stable-diffusion-paperspace](https://github.com/Engineer-of-Stuff/stable-diffusion-paperspace), the section named "A note about Python 3.10".

Go to create a new **Paperspace notebook**, select **Start from scratch**, then **View advanced options** and there in the last section named "Container - Name" (in the text field right above "Registry username" and "registry password"), put the following:

`cyberes/gradient-base-py3.10:latest`

Then you'll only need to click start and you'll be on version 3.10
