### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by hexiaofeng1977** [bmaltais/kohya_ss#2072]
17:21:01-622125 INFO     Kohya_ss GUI version: v23.0.5
17:21:02-410497 INFO     Submodule initialized and updated.
17:21:02-410497 INFO     nVidia toolkit detected
17:21:03-277184 INFO     Torch 2.1.2+cu118
17:21:03-285792 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8905
17:21:03-295805 INFO     Torch detected GPU: NVIDIA GeForce RTX 4060 Laptop GPU VRAM 8188 Arch (8, 9) Cores 24
17:21:03-295805 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit
                         (AMD64)]
17:21:03-295805 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
17:21:03-295805 INFO     Verifying modules installation status from requirements.txt...
17:21:05-090147 INFO     headless: False
17:21:05-092147 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
17:21:10-952803 INFO     Start training Dreambooth...
17:21:10-952803 INFO     Validating model file or folder path D:/Model/huggingface/stable-diffusion-xl-base-1.0
                         existence...
17:21:10-952803 INFO     ...valid
17:21:10-952803 INFO     Validating training data folder path D:/Git/kohya_ss/LoraTraining/mynewmodel/images
                         existence...
17:21:10-952803 INFO     ...valid
17:21:10-952803 INFO     Checking for duplicate image filenames in training data directory
                         D:/Git/kohya_ss/LoraTraining/mynewmodel/images...
17:21:10-968440 INFO     ...valid
17:21:10-968440 INFO     Verifying image folder pattern of D:/Git/kohya_ss/LoraTraining/mynewmodel/images...
17:21:10-968440 INFO     ...valid
17:21:10-968440 INFO     Regularisation folder not specified, skipping validation
17:21:10-968440 INFO     Validating output folder path D:/Git/kohya_ss/LoraTraining/mynewmodel/model existence...
17:21:10-968440 INFO     ...valid
17:21:10-968440 INFO     Validating logging folder path D:/Git/kohya_ss/LoraTraining/mynewmodel/log existence...
17:21:10-968440 INFO     ...valid
17:21:10-968440 INFO     Model resume file not specified, skipping validation
17:21:10-984057 INFO     VAE file not specified, skipping validation
17:21:10-984057 INFO     Folder 2_face : steps 6
17:21:10-984057 INFO     max_train_steps (6 / 1 / 1 * 1 * 1) = 6
17:21:10-984057 INFO     stop_text_encoder_training = 0
17:21:10-984057 INFO     lr_warmup_steps = 1
17:21:11-000985 INFO     Saving training config to
                         D:/Git/kohya_ss/LoraTraining/mynewmodel/model\hexiaofeng_20240312-172111.json...
17:21:11-003999 INFO     accelerate launch --num_cpu_threads_per_process=2 "D:\Git\kohya_ss/sd-scripts/sdxl_train.py"
                         --bucket_no_upscale --bucket_reso_steps=64 --cache_latents --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048 --learning_rate="1e-05"
                         --learning_rate_te1="1e-05" --learning_rate_te2="1e-05"
                         --logging_dir="D:/Git/kohya_ss/LoraTraining/mynewmodel/log" --lr_scheduler="cosine"
                         --lr_scheduler_num_cycles="1" --lr_warmup_steps="1" --max_data_loader_n_workers="0"
                         --resolution="512,512" --max_train_steps="6" --mixed_precision="fp16"
                         --optimizer_type="AdamW8bit" --output_dir="D:/Git/kohya_ss/LoraTraining/mynewmodel/model"
                         --output_name="hexiaofeng"
                         --pretrained_model_name_or_path="D:/Model/huggingface/stable-diffusion-xl-base-1.0"
                         --save_every_n_epochs="1" --save_model_as=safetensors --save_precision="fp16"
                         --train_batch_size="1" --train_data_dir="D:/Git/kohya_ss/LoraTraining/mynewmodel/images"
                         --xformers
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
2024-03-12 17:21:18 INFO     prepare tokenizers                                                   sdxl_train_util.py:135
2024-03-12 17:22:40 INFO     Using DreamBooth method.                                                  sdxl_train.py:140
                    INFO     prepare images.                                                          train_util.py:1469
                    INFO     found directory D:\Git\kohya_ss\LoraTraining\mynewmodel\images\2_face    train_util.py:1432
                             contains 3 image files
                    WARNING  No caption file found for 3 images. Training will continue without       train_util.py:1459
                             captions for these images. If class token exists, it will be used. /
                             3枚の画像にキャプションファイルが見つかりませんでした。これらの画像につ
                             いてはキャプションなしで学習を続行します。class
                             tokenが存在する場合はそれを使います。
                    WARNING  D:\Git\kohya_ss\LoraTraining\mynewmodel\images\2_face\111.jpg            train_util.py:1466
                    WARNING  D:\Git\kohya_ss\LoraTraining\mynewmodel\images\2_face\222.jpg            train_util.py:1466
                    WARNING  D:\Git\kohya_ss\LoraTraining\mynewmodel\images\2_face\3333.jpg           train_util.py:1466
                    INFO     6 train images with repeating.                                           train_util.py:1508
                    INFO     0 reg images.                                                            train_util.py:1511
                    WARNING  no regularization images / 正則化画像が見つかりませんでした              train_util.py:1516
                    INFO     [Dataset 0]                                                              config_util.py:544
                               batch_size: 1
                               resolution: (512, 512)
                               enable_bucket: True
                               network_multiplier: 1.0
                               min_bucket_reso: 256
                               max_bucket_reso: 2048
                               bucket_reso_steps: 64
                               bucket_no_upscale: True

                               [Subset 0 of Dataset 0]
                                 image_dir: "D:\Git\kohya_ss\LoraTraining\mynewmodel\images\2_face"
                                 image_count: 3
                                 num_repeats: 2
                                 shuffle_caption: False
                                 keep_tokens: 0
                                 keep_tokens_separator:
                                 caption_dropout_rate: 0.0
                                 caption_dropout_every_n_epoches: 0
                                 caption_tag_dropout_rate: 0.0
                                 caption_prefix: None
                                 caption_suffix: None
                                 color_aug: False
                                 flip_aug: False
                                 face_crop_aug_range: None
                                 random_crop: False
                                 token_warmup_min: 1,
                                 token_warmup_step: 0,
                                 is_reg: False
                                 class_tokens: face
                                 caption_extension: .caption

                    INFO     [Dataset 0]                                                              config_util.py:550
                    INFO     loading image sizes.                                                      train_util.py:794
100%|███████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 302.05it/s]
                    INFO     make buckets                                                              train_util.py:800
                    WARNING  min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is   train_util.py:817
                             set, because bucket reso is defined by image size automatically /
                             bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計
                             算されるため、min_bucket_resoとmax_bucket_resoは無視されます
                    INFO     number of images (including repeats) /                                    train_util.py:846
                             各bucketの画像枚数（繰り返し回数を含む）
                    INFO     bucket 0: resolution (384, 512), count: 2                                 train_util.py:851
                    INFO     bucket 1: resolution (512, 384), count: 4                                 train_util.py:851
                    INFO     mean ar error (without repeats): 0.037949906842818404                     train_util.py:856
                    INFO     prepare accelerator                                                       sdxl_train.py:197
accelerator device: cpu
                    INFO     loading model for process 0/1                                         sdxl_train_util.py:31
2024-03-12 17:22:41 INFO     load Diffusers pretrained models:                                     sdxl_train_util.py:85
                             D:/Model/huggingface/stable-diffusion-xl-base-1.0, variant=fp16
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:27<00:00,  4.54s/it]
2024-03-12 17:23:08 INFO     U-Net converted to original U-Net                                    sdxl_train_util.py:121
Disable Diffusers' xformers
2024-03-12 17:23:09 INFO     Enable xformers for U-Net                                                train_util.py:2529
2024-03-12 17:23:10 INFO     [Dataset 0]                                                              train_util.py:1948
                    INFO     caching latents.                                                          train_util.py:915
                    INFO     checking cache validity...                                                train_util.py:925
100%|████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<?, ?it/s]
                    INFO     caching latents...                                                        train_util.py:962
  0%|                                                                                            | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\Git\kohya_ss\sd-scripts\sdxl_train.py", line 792, in <module>
    train(args)
  File "D:\Git\kohya_ss\sd-scripts\sdxl_train.py", line 262, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\Git\kohya_ss\sd-scripts\library\train_util.py", line 1949, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\Git\kohya_ss\sd-scripts\library\train_util.py", line 964, in cache_latents
    cache_batch_latents(vae, cache_to_disk, batch, subset.flip_aug, subset.random_crop)
  File "D:\Git\kohya_ss\sd-scripts\library\train_util.py", line 2285, in cache_batch_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "D:\Git\kohya_ss\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "D:\Git\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Git\kohya_ss\venv\lib\site-packages\diffusers\models\autoencoders\vae.py", line 143, in forward
    sample = self.conv_in(sample)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Git\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\SDK\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\SDK\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Git\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Git\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Git\\kohya_ss\\venv\\Scripts\\python.exe', 'D:\\Git\\kohya_ss/sd-scripts/sdxl_train.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=1e-05', '--learning_rate_te1=1e-05', '--learning_rate_te2=1e-05', '--logging_dir=D:/Git/kohya_ss/LoraTraining/mynewmodel/log', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--lr_warmup_steps=1', '--max_data_loader_n_workers=0', '--resolution=512,512', '--max_train_steps=6', '--mixed_precision=fp16', '--optimizer_type=AdamW8bit', '--output_dir=D:/Git/kohya_ss/LoraTraining/mynewmodel/model', '--output_name=hexiaofeng', '--pretrained_model_name_or_path=D:/Model/huggingface/stable-diffusion-xl-base-1.0', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--train_batch_size=1', '--train_data_dir=D:/Git/kohya_ss/LoraTraining/mynewmodel/images', '--xformers']' returned non-zero exit status 1.

How to fix it ？ Thanks

**Comment by bmaltais** [comment]
This appear to be some sort of incompatibility between sd-script, your GPU and the training options selected…

**Comment by bmaltais** [comment]
Have you installed CUDA 11.8 on your computer?
