### ISSUE TITLE
unable to use BLIP after reinstalling GUI

### ISSUE THREAD

**Issue by MTNZLVSK** [bmaltais/kohya_ss#2073]
17:46:52-512487 INFO     Kohya_ss GUI version: v23.0.5
17:46:53-138195 INFO     Submodule initialized and updated.
17:46:53-140012 INFO     nVidia toolkit detected
17:46:54-315545 INFO     Torch 2.1.2+cu118
17:46:54-327975 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:46:54-329971 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 22528 Arch (7, 5) Cores 68
17:46:54-330935 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
17:46:54-331936 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
17:46:54-333936 INFO     Verifying modules installation status from requirements.txt...
17:46:57-234482 INFO     headless: False
17:46:57-240485 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
D:\kohya-ss gui\kohya_ss\venv\lib\site-packages\gradio\components\dropdown.py:176: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Dropdown(...)` instead of `return gr.Dropdown.update(...)`.
  warnings.warn(
17:56:46-820761 INFO     Captioning files in D:/fauxart projects/fauxart Hiroshi Sato/training project/hiroshisato/img/20_hiroshisato fauxart...
17:56:46-821762 INFO     D:\kohya-ss gui\kohya_ss\venv\Scripts\python.exe "D:\kohya-ss gui\kohya_ss/sd-scripts/finetune/make_captions.py" --batch_size="1" --num_beams="8" --top_p="0.9" --max_length="75"
                         --min_length="20" --beam_search --caption_extension=".txt" "D:/fauxart projects/fauxart Hiroshi Sato/training project/hiroshisato/img/20_hiroshisato fauxart"
                         --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
'D:\kohya-ss' is not recognized as an internal or external command,
operable program or batch file.
17:56:46-910928 INFO     ...captioning done

Installation is completed without issue. But when using BLIP, terminal running gui.bat shows the above message without execution.

Wondering what's happening here. I have deleted the whole folder and git cloned the whole repo for several time and this is still happening...I must have missed something here without knowing.

**Comment by bmaltais** [comment]
I see there is a space in you D: folder name… I suspect it is a bug around handling those… for now try removing that space and see… it might help

**Comment by bmaltais** [comment]
I have pushed a fix to the dev branch, can you test it out?

```
git pull
git checkout dev
```

Test the latest fix in dev.

To revert back to master you simply do:

```
git checkout master
```
