### ISSUE TITLE
lycoris_locon_extract.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by elen07zz** [bmaltais/kohya_ss#2075]
06:18:17-453290 INFO     "D:\kohya_ss\venv\Scripts\python.exe" "D:\kohya_ss/sd-scripts/tools/lycoris_locon_extract.py"
                         --device cuda --mode fixed --safetensors --linear_dim 64 --conv_dim 64 --sparsity 0.98
                         "D:/stable-diffusion-webui/models/Stable-diffusion/Real/serenity_v21Safetensors.safetensors"
                         "D:/stable-diffusion-webui/models/Stable-diffusion/in.safetensors"
                         "D:/stable-diffusion-webui/models/Lora/Trained/out.safetensors"
C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'D:\\kohya_ss\\sd-scripts\\tools\\lycoris_locon_extract.py': [Errno 2] No such file or directory
06:18:17-497344 INFO     Done extracting...

lycoris extract no working.

**Comment by bmaltais** [comment]
Hummm. I will test it out

**Comment by bmaltais** [comment]
Should be fixed in the new release.
