### ISSUE TITLE
WD14_Caption path missing

### ISSUE THREAD

**Issue by crack2483** [bmaltais/kohya_ss#2077]
Hi

I use Stability Matrix as a package installer for all my Stable Diffusion needs. After updating Kohya to the latest version, I now get an error saying Could not find file (path...)\kohyass\library\wd14_caption_gui.py

I've tried uninstalling and re-installing. I've tried reverting back to older version as far back as 23.0

Any ideas? Or how do I re-install WD14 captioning?

Regards

**Comment by bmaltais** [comment]
You may have to stick with v22.6.2. I don’t use stability matrix so I can’t really help with it. The app expect python to be installed using the python.org installer. If someone figure out what will make stability matrix work I could take a Pull Request for code update to make it work as lo g as the change does not cause issues for the rest of the users.

**Comment by crack2483** [comment]
> You may have to stick with v22.6.2. I don’t use stability matrix so I can’t really help with it. The app expect python to be installed using the python.org installer. If someone figure out what will make stability matrix work I could take a Pull Request for code update to make it work as lo g as the change does not cause issues for the rest of the users.

Thanks. I'll try revert back to that version quick. It was working up until todays update though. Used it successfully yesterday even. And its always up to date.

**Comment by bmaltais** [comment]
Hummm... so something else must have caused the issue... I might give stabilitymatrix a try to see what it is and why it might cause issues with kohya_ss gui.

Is this it: https://github.com/LykosAI/StabilityMatrix

**Comment by crack2483** [comment]
> Hummm... so something else must have caused the issue... I might give stabilitymatrix a try to see what it is and why it might cause issues with kohya_ss gui.
> 
> Is this it: https://github.com/LykosAI/StabilityMatrix

Yes thats the one

**Comment by bmaltais** [comment]
Yeah... it does not install properly... when it try to install kohya_ss gui it fives a bunch of errors... I think stability matrix will need to adapt how they do the install as the new v23.0.x does not appear to be compatible with their installer.

**Comment by crack2483** [comment]
> Yeah... it does not install properly... when it try to install kohya_ss gui it fives a bunch of errors... I think stability matrix will need to adapt how they do the install as the new v23.0.x does not appear to be compatible with their installer.

Thanks for the replies. It looks like other guys are having separate issues regarding stability matrixs' latest update. I've voiced my issue in their thread as well.

Much appreciate the help, thanks again

**Comment by bmaltais** [comment]
OK... I was able to get kohya_ss gui work in stablematrix... but... it won't install properly on it's own.

Ifter asking stablematrix to install it I got an installation message error. I just opened a terminal in the install folder than manually ran ./setup.bat

The setup worked properly and then I was able to run the GUI and even caption with WD14...

Have you tried this avenue?

**Comment by crack2483** [comment]
No i haven't. I'll definitely try this tomorrow though. Thank you

**Comment by bmaltais** [comment]
OK. I have left them a message on Discord to see if there is something I can do to help them with the install issue... let see if they reply.
