### ISSUE TITLE
Output folder not created if not exist (v23.0.7)

### ISSUE THREAD

**Issue by zadokov** [bmaltais/kohya_ss#2078]
When changing the 'Trained Model output name' value and clicking on 'Print Training command' the folder is not created and the training command is not displayed.
This worked in past versions/

22:40:25-444149 INFO     Start training LoRA Standard ...
22:40:25-445148 INFO     Validating model file or folder path
                         C:/SD/stable-diffusion-webui/models/Stable-diffusion/juggernautXL_version5.safetensors
                         existence...
22:40:25-447149 INFO     ...valid
22:40:25-448148 INFO     Validating training data folder path F:/SD/workspace/images/training_images/img_IH - xlih -
                         set4 existence...
22:40:25-449148 INFO     ...valid
22:40:25-449148 INFO     Checking for duplicate image filenames in training data directory
                         F:/SD/workspace/images/training_images/img_IH - xlih - set4...
22:40:25-451148 INFO     ...valid
22:40:25-451148 INFO     Verifying image folder pattern of F:/SD/workspace/images/training_images/img_IH - xlih -
                         set4...
22:40:25-452148 INFO     ...valid
22:40:25-453148 INFO     Regularisation folder not specified, skipping validation
22:40:25-453148 INFO     Validating output folder path F:/SD/workspace/output/Lora/XLIH10/JNautIH10.71 existence...
22:40:25-454148 ERROR    ...output folder path is missing or invalid

**Comment by bmaltais** [comment]
You mean the creation of the output folder if it did not exist? I think when I standardised the validation code I might have removed this feature... If it used to be like that and you are leveraging this feature then I guess I could add it back... Same for the log folder I guess...

**Comment by zadokov** [comment]
@bmaltais Yes - I use it frequently and will appreciate adding it back :-)

**Comment by bmaltais** [comment]
OK... I was able to get kohya_ss gui work in stablematrix... but... it won't install properly on it's own.

Ifter asking stablematrix to install it I got an installation message error. I just opened a terminal in the install folder than manually ran ./setup.bat

The setup worked properly and then I was able to run the GUI and even caption with WD14...

Have you tried this avenue?
