### ISSUE TITLE
03:32:16-072235 ERROR    ...vae path is invalid  

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2081]
It can't see anymore this VAE path like before

`stabilityai/sdxl-vae`

Version : 23.0.8

**Comment by bmaltais** [comment]
That section of code has not been updated since 3 months... so that json file must be dating back way before as this section of parameters has not been shown for at least 3 months.

Can you point me to a version of kohya_ss gui that show it so I can analyse why it is?

**Comment by FurkanGozukara** [comment]
last version working nice thank you

**Comment by FurkanGozukara** [comment]
this issue returned back

latest version 23.0.14

![Uploading image.png…]()

**Comment by bmaltais** [comment]
Darn, Should be an easy fix… will look at it this afternoon

**Comment by bmaltais** [comment]
Should be fixed now

**Comment by FurkanGozukara** [comment]
thanks
