### ISSUE TITLE
merge lora svd not working

### ISSUE THREAD

**Issue by AmyWongCheese** [bmaltais/kohya_ss#2082]
The new model size doesn't seem to be correct.
![螢幕擷取畫面 2024-03-13 134018](https://github.com/bmaltais/kohya_ss/assets/13150286/2261160f-8c9a-45c5-90a0-40796c32a90d)
![螢幕擷取畫面 2024-03-13 134136](https://github.com/bmaltais/kohya_ss/assets/13150286/cef0b91d-5102-4f8a-b8fc-6c34e7c9f979)

**Comment by bmaltais** [comment]
This does not look like it is caused by the GUI but perhaps a bug with the merge python code

**Comment by AmyWongCheese** [comment]
Here are the relevant files that you can download to try it.
https://drive.google.com/drive/folders/1-RF2DoJumrDbdhitwkCUiOj8SdHVW___?usp=drive_link
