### ISSUE TITLE
Weights, Blocks, Conv tabs are missing in LyCORIS

### ISSUE THREAD

**Issue by iamrohitanshu** [bmaltais/kohya_ss#2084]
In the latest version v23.0.8, Weights, Blocks, Conv tabs under Advanced tab are missing. They were available in the previous versions, so as I loaded my old json config, they are also seen in the new json created, but the options are not visible in the main command printed at the start of the training.

This only happens in all LyCORIS types, so either

1. LyCORIS doesn't support these options. (but why were they available before)
2. They are being used but are not visible in the training command. (unlikely, I think) OR
3. They should be available and it's just a bug.

Sorry, I'm not sure what the actual issue is here. Someone help me out, please?

**Comment by bmaltais** [comment]
Will investigate

**Comment by iamrohitanshu** [comment]
@bmaltais I checked the metadata of my old Loras.
The standard Loras have the LR weights modified in them as I wanted, but the LyCORIS doesn't, even before the update.
So, it may be the case that LyCORIS doesn't support this functionality.
I don't know how to check that though. You might wanna start by looking into this. Thanks!

**Comment by bmaltais** [comment]
THis confirm my suspission. The way I save the config it will also save parameters that are not applicable for some of the types of LoRA and this may lead to the conclusion that it was supported... but in fact it never was.

Sorry for the the confusion the config file might bring ;-)

**Comment by iamrohitanshu** [comment]
No worries, you're already doing great work. :)

So, in conclusion, does LyCORIS not support modifying LR weights? or just that the original kohya scripts haven't implemented it?

**Comment by bmaltais** [comment]
I actually don’t know… you want to ask the author of LyCORIS and if he answer that he does the I could enable it in the GUI.

**Comment by iamrohitanshu** [comment]
@bmaltais alright, thanks!
