### ISSUE TITLE
Icons / Buttons are too small

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2088]
Please make icons / buttons bigger

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/2b669479-511b-48bc-914b-8a96bf884448)

**Comment by FurkanGozukara** [comment]
> Why is this an issue? If someone want to create a PR to make the button size a per user setting I would gladly take it in.

I wish i knew how to format Gradio. But this is a big issue. Buttons are so tiny, hard to click and could contain more info

For example load config is not apparent at all

**Comment by bmaltais** [comment]
Would be nice if gradio offered a native over function to provide text for the icons. Let see if I get more complain about the icon size. @wkpark created the GUI update and changed the button size... perhaps there might be a way to make it a parameter from a config file in the root that users could change to specify a bigger button size...

**Comment by wkpark** [comment]
you can add padding of buttons
~~~diff
diff --git a/style.css b/style.css
index 456433e..445fb3d 100644
--- a/style.css
+++ b/style.css
@@ -3,6 +3,7 @@
     flex-grow: 0;
     padding-left: 0.25em;
     padding-right: 0.25em;
+    padding: 1em;
 }

 #open_folder{
~~~
![image](https://github.com/bmaltais/kohya_ss/assets/232347/f37e6ad4-0ab8-4b98-96e7-ef1f97386edb)

or you can icrease the size of icons
~~~diff
diff --git a/style.css b/style.css
index 456433e..1e8394a 100644
--- a/style.css
+++ b/style.css
@@ -3,6 +3,8 @@
     flex-grow: 0;
     padding-left: 0.25em;
     padding-right: 0.25em;
+    /* padding: 1em; */
+    font-size:2em;
 }

 #open_folder{
~~~
![image](https://github.com/bmaltais/kohya_ss/assets/232347/4c82d63c-37ae-4f59-b64a-154b82554a19)

**Comment by bmaltais** [comment]
@wkpark was there a particular reason why you made the icons the size they are? Perhaps combining both the icon size increase and padding could provide the needed size increase…

**Comment by FurkanGozukara** [comment]
this looks much better
also when mouse hovered display what they are 

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/29f051ab-7c05-4c27-b949-eff89f54d4f2)

**Comment by bmaltais** [comment]
I have upgraded the size in the v23.0.11 release

**Comment by wkpark** [comment]
> @wkpark was there a particular reason why you made the icons the size they are? Perhaps combining both the icon size increase and padding could provide the needed size increase…

I did'nt touch icon size, as you can see, icon size (`font-size:`) was not designated before :)
