### ISSUE TITLE
New version new install problem

### ISSUE THREAD

**Issue by kisoft777** [bmaltais/kohya_ss#2093]
`C:\Users\ofuduldlutd\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\WINDOWS\\system32\\setup\\setup_windows.py': [Errno 2] No such file or directory`

Hello, first of all I thank you for the work accomplished.

I get this error as soon as I run the setup.bat file as administrator.
I reinstalled the vc++ and updated the python module, taking care to check the necessary boxes.

**Comment by bmaltais** [comment]
Strange that python think C:\\WINDOWS\\system32 is the folder where kohya_ss was clonned. When you run setup.bat, are you in the kohya_ss folder? Or are you running it from outside?

**Comment by kisoft777** [comment]
it is in the document>sd.webui>kohya_ss-master> folder

in the webui folder there is kohya/(system/webui for stable distribution)

**Comment by bmaltais** [comment]
No idea why it does this. Have you tried moving the folder to, say, the root of c: then delete the venv and run setup again?

**Comment by kisoft777** [comment]
he didn't create the venv folder.. on the other hand I moved it as you said and launched it without administrator mode and it started normally, that's not normal.

I followed a tutorial which said it was better to run it as administrator..

**Comment by kisoft777** [comment]
this code is correctly? 

    # Original path with "..\\venv"
    original_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..\\venv\\Lib\\site-packages\\nvidia\\cudnn\\bin")
    # Normalize the path to resolve "..\\venv"
    cudnn_src = os.path.abspath(original_path)
    cudnn_dest = os.path.join(sysconfig.get_paths()["purelib"], "torch", "lib")
    
    have a // ?
    
    I had problems with duplicates / in a previous installation.

I have this error: fatal: not a git repository (or any of the parent directories): .git
00:33:34-344334 ERROR Error during Git operation: Command '['git', 'submodule', 'update', '--init', '--recursive',
                          '--quiet']' returned non-zero exit status 128.

**Comment by bmaltais** [comment]
> he didn't create the venv folder.. on the other hand I moved it as you said and launched it without administrator mode and it started normally, that's not normal.
> 
> I followed a tutorial which said it was better to run it as administrator..

Hi,

You don't want to run this as administrator... Best is to use the `.\setup.bat` and not the .ps1 version. With the .bat you run it as a regular user... also, the git error appear to be related to some sort of git cloning issue... you might be better to delete the full kohya_ss folder, clone it fresh as a non administrator user and then run setup.bat as a non admin user... See if this work better.

**Comment by kisoft777** [comment]
je l'ai télécharger en .zip directement, je ne l'ai pas copier via cmd git.
je vais tester si il fonctionne quand même, si ce n'est pas le cas je le clonerais

**Comment by kisoft777** [comment]
![Capture](https://github.com/bmaltais/kohya_ss/assets/4012308/9c0957e2-7bfb-437a-80b9-434f744f9842)
i have a new issues, what is this problem?

**Comment by kisoft777** [comment]
despite this it works, thank you for your help <3

**Comment by bmaltais** [comment]
> ![Capture](https://private-user-images.githubusercontent.com/4012308/312849771-9c0957e2-7bfb-437a-80b9-434f744f9842.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDExNTQsIm5iZiI6MTcxMDQ0MDg1NCwicGF0aCI6Ii80MDEyMzA4LzMxMjg0OTc3MS05YzA5NTdlMi03YmZiLTQzN2EtODBiOS00MzRmNzQ0Zjk4NDIuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTgyNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjEwZmVmNDdmNmU3NDk4YzhmNjNmZmNmYTBlMjM3YzM5YmJiMGI1YTZlZTRkYTFkNGQ3MzIwMDcyNjBjN2JkYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NE23Edcphk76eaBHStTG3mdlfHpiBPFoKpD1bvQFYzo) i have a new issues, what is this problem?

This is a deprecation warning for Gradio. I need to cleanup the .update methods... No worries as this is just a warning.
