### ISSUE TITLE
Incredibly Slow LoRa Training

### ISSUE THREAD

**Issue by ArmyOfPun1776** [bmaltais/kohya_ss#2100]
Hello, 

For reference off the bat:  3050Ti Laptop GPU with 4GB Dedicated and 12GB Shard (16GB). Windows 11. 
![image](https://github.com/bmaltais/kohya_ss/assets/158170170/7e0bb53e-c179-488b-9233-20c907a24690)

I have been having a heck of a time with this... 
- I followed the install instructions to the 't'.  
- Ran through defaults on Accelerate. 
- Have tried selecting GPU 0, 1, and all.  
- Changed Bytesands version.... 
- Installed CUDA 
 
My training is always 150hrs Plus for a 30 Imgs, 20 repeats, 2 Batches, for a total of 3000 steps. 

![image](https://github.com/bmaltais/kohya_ss/assets/158170170/d31235d5-065a-4dd8-a800-fa3ef510dd58)
======================================================================================
![image](https://github.com/bmaltais/kohya_ss/assets/158170170/6e27c885-0ee7-4459-8b9c-ba831923ea91)

What am I doing wrong?

Memory Utilization is good.... I just don't understand.
![image](https://github.com/bmaltais/kohya_ss/assets/158170170/bf499c7c-8171-42d8-a0b4-916cd7912d8f)

Any help or guidance would be much appreciated.

**Comment by bmaltais** [comment]
The slow training is due to the fact that you have too little VRAM. Swapping to shared memory like you do it terribly slow. You will need a better CPU to train, sorry ;-( Based on the graph you would need a minimum of 8GB of VRAM for what you are attempting to train.

**Comment by bmaltais** [comment]
Thank you!
