### ISSUE TITLE
Change the default directory of regularization images and config directory.

### ISSUE THREAD

**Issue by jim60105** [bmaltais/kohya_ss#2103]
At present, both the regularization images directory and the training images directory share the same default directory `data`. In my opinion, it would be better to distinguish between them.

https://github.com/bmaltais/kohya_ss/blob/7081b22cbaed1487d18d84ffcc80e409b56f7f71/kohya_gui/class_folders.py#L12-L15

And the config directory is default to `None`. I suggest assign and init it just like other directories does.

https://github.com/bmaltais/kohya_ss/blob/61621939e3678cc297ffe930e9a02c598ba953d9/kohya_gui/class_configuration_file.py#L12

**Comment by jim60105** [comment]
Typo
`Regularisation` and `reqularization`
https://github.com/bmaltais/kohya_ss/blob/7081b22cbaed1487d18d84ffcc80e409b56f7f71/kohya_gui/class_folders.py#L60

**Comment by bmaltais** [comment]
Thanks, I will merge those to dev.

**Comment by bmaltais** [comment]
Was able to implement changes to class_folders but running into issues with clas_config_file
