### ISSUE TITLE
same hyperparameters and datasets, totally different result

### ISSUE THREAD

**Issue by syusukexrj** [bmaltais/kohya_ss#2104]
base model: anime model (sd1.5)
dataset 0:  realistic scenery images (ice castle) shot by mobile phone(count: 30, repeat : 40, resolution: rectangles)
dataset 1:  images of anime style (count: 150, repeat: 1, resolution: 768x768),  for regularized.  
Captions are generated by tagger and the prefix tag "ice castle" is added to the dataset 0.

Target: generate human and ice castle with anime style 

The lora is trained twice with same hyperparameters and datasets. The final losses are similar but the generation results are different. The first lora can generate ice castle very well but the result of second lora is very poor.

Why?

**Comment by bmaltais** [comment]
Closing since there was not updates in the last 30 days. Please re-open if needed.
