### ISSUE TITLE
LoRAs merging not working anymore

### ISSUE THREAD

**Issue by Bullseye110** [bmaltais/kohya_ss#2106]
Hello!
So I was trying to merge 2 models first, then 4, but they didn't work and nothing happened.
This is the only message appearing:
"INFO NumExpr defaulting to 2 threads."

Waited for a few minuted and nothing else appeared.
I'm sure I'm using the correct settings.

**Comment by bmaltais** [comment]
Hummm, what version of the GUI? 23.0.x? What exact tab are you using? I will try it at my end.

**Comment by Bullseye110** [comment]
The LoRA merging tab from the Utilities. It's the latest version of kohya.

**Comment by bmaltais** [comment]
I tried them last night and both started but I think the issue is with the actual merge utility as it ran but produced a bad merge. I don’t create those utilities so whoever created them need to fix that. I ce they do I will be able to bring the update in my project.

**Comment by Bullseye110** [comment]
> I tried them last night and both started but I think the issue is with the actual merge utility as it ran but produced a bad merge. I don’t create those utilities so whoever created them need to fix that. I ce they do I will be able to bring the update in my project.

I see, thanks!
