### ISSUE TITLE
The template for Runpod does not work

### ISSUE THREAD

**Issue by nvjob** [bmaltais/kohya_ss#2109]
The template for Runpod does not work
https://runpod.io/gsc?template=ya6013lj5a&ref=w18gds2n

**Comment by jim60105** [comment]
This issue should goes to https://github.com/ashleykleynhans/stable-diffusion-docker

**Comment by bmaltais** [comment]
Indeed. I did not create the template. Hope the creator can adapt it to the latest release.

**Comment by ashleykleynhans** [comment]
Template for RunPod DOES work and is already the latest release, so don't know what @nvjob is doing wrong.

**Comment by ashleykleynhans** [comment]
I assume @nvjob probably didn't first connect to port 8000 and stop A1111 before attempting to train Kohya_ss.
A1111 loads the model into VRAM on startup, which consumes about 30% of available VRAM on a 24GB GPU.
You first need to stop A1111 before training to train Kohya_ss, or alternatively use the [Kohya_ss standalone template](https://runpod.io/console/gpu-cloud?template=51q837fywe&ref=2xxro4sy).

**Comment by ashleykleynhans** [comment]
> This issue should goes to https://github.com/ashleykleynhans/stable-diffusion-docker

Shouldn't go here either, it works fine for everyone else.

**Comment by ashleykleynhans** [comment]
@nvjob also just saying "does not work" is not useful to anyone.  What does not work? What is the error etc?  Provide details otherwise you are just wasting everyones time.

**Comment by jim60105** [comment]
> > This issue should goes to https://github.com/ashleykleynhans/stable-diffusion-docker
> 
> Shouldn't go here either, it works fine for everyone else, plus its just a Docker image. Apparently bitsandbytes version uses more VRAM than the previous version but thats got nothing to do with my template, my template installs the requirements from this repo, so if there is an issue with the requirements here, then it needs to be fixed here.
> 
> Also I don't know why people use 8bit Adam optimizer to train SDXL when Adafactor is the recommended optimizer for SDXL.

He only titled it "The template for Runpod," so I think he got an issue with either the template or the Runpod. That's why I suggested sending the issue to your repo.

Of course, users come across issues does not means that there is something wrong with your code.
Most of the time, issues like this arise from users not understanding how to use it, while we here do not know Runpod too. You can then guide him back if it is indeed a bmaltais/kohya_ss issue.

**Comment by ashleykleynhans** [comment]
> > > This issue should goes to https://github.com/ashleykleynhans/stable-diffusion-docker
> > 
> > 
> > Shouldn't go here either, it works fine for everyone else, plus its just a Docker image. Apparently bitsandbytes version uses more VRAM than the previous version but thats got nothing to do with my template, my template installs the requirements from this repo, so if there is an issue with the requirements here, then it needs to be fixed here.
> > Also I don't know why people use 8bit Adam optimizer to train SDXL when Adafactor is the recommended optimizer for SDXL.
> 
> He only titled it "The template for Runpod," so I think he got an issue with either the template or the Runpod. That's why I suggested sending the issue to your repo.
> 
> Of course, users come across issues does not means that there is something wrong with your code. Most of the time, issues like this arise from users not understanding how to use it, while we here do not know Runpod too. You can then guide him back if it is indeed a bmaltais/kohya_ss issue.

Nope, if people have issues on RunPod, they should use the RunPod Discord to ask for help, it is not my job to help them, I am one person, RunPod Discord is a community of thousands of people who can help.  Basically this should have been posted on Discord in the first place instead of on Github and wasting everyones valuable time especially since there is not even any logs, error messages etc.

**Comment by jim60105** [comment]
> > > > This issue should goes to https://github.com/ashleykleynhans/stable-diffusion-docker
> > > 
> > > 
> > > Shouldn't go here either, it works fine for everyone else, plus its just a Docker image. Apparently bitsandbytes version uses more VRAM than the previous version but thats got nothing to do with my template, my template installs the requirements from this repo, so if there is an issue with the requirements here, then it needs to be fixed here.
> > > Also I don't know why people use 8bit Adam optimizer to train SDXL when Adafactor is the recommended optimizer for SDXL.
> > 
> > 
> > He only titled it "The template for Runpod," so I think he got an issue with either the template or the Runpod. That's why I suggested sending the issue to your repo.
> > Of course, users come across issues does not means that there is something wrong with your code. Most of the time, issues like this arise from users not understanding how to use it, while we here do not know Runpod too. You can then guide him back if it is indeed a bmaltais/kohya_ss issue.
> 
> Nope, if people have issues on RunPod, they should use the RunPod Discord to ask for help, it is not my job to help them, I am one person, RunPod Discord is a community of thousands of people who can help. Basically this should have been posted on Discord in the first place instead of on Github and wasting everyones valuable time especially since there is not even any logs, error messages etc.

In fact, I know that there is a "Runpod Discord" JUST NOW because I have never used Runpod.
This also proves that this issue does not belong here.😉

**Comment by nvjob** [comment]
The problem is that Kohya_ss and SD are not installed in Runpod. You have to run the installation manually. I waited a long time and looked at the logs, nothing happens. At the same time, sometimes everything installs and works, it does not depend on the GPU that I use. I wrote that the template does not work, there is no need to invent anything else.

**Comment by ashleykleynhans** [comment]
@nvjob Nonsense!  The template works perfectly fine.  Look at the container logs NOT the system logs, the system logs are completely useless.  The problem here is that you are too impatient and did not wait for the apps to complete syncing to workspace.  There is absolutely nothing wrong with the template.  The problem here is 100% YOU.

**Comment by ashleykleynhans** [comment]
Also if you click the link to connect to one of the ports, there are clear instructions on what to do, so you either just ignored them or else you need to go back to school so that you can learn how to read.

**Comment by nvjob** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/25087568/0300c2ab-f468-4f8e-9a9e-205736b18d5e)
Perhaps the problem is really on the server

**Comment by ashleykleynhans** [comment]
In summary, this ticket can be closed, there is nothing wrong with the template.  @nvjob should just go use some other platform because he doesn't  understand RunPod or know how to use it.

**Comment by nvjob** [comment]
@ashleykleynhans you don’t understand, you should be closed for your tactfulness.
You need to write in the logs that the process is in progress.

**Comment by jim60105** [comment]
Perhaps having rsync print the status would be a solution?
https://askubuntu.com/a/907717

The user is experiencing difficulty due to not being aware of the current state. Providing information about the status can help in preventing similar issues in the future, and saves your time.
