### ISSUE TITLE
Feature request: Update SmilingWolf captioning taggers to new v3 models

### ISSUE THREAD

**Issue by sammcj** [bmaltais/kohya_ss#2112]
SmilingWolf has released a new v3 taggers:

- https://huggingface.co/SmilingWolf/wd-swinv2-tagger-v3
- https://huggingface.co/SmilingWolf/wd-vit-tagger-v3
- https://huggingface.co/SmilingWolf/wd-convnext-tagger-v3

It would be great if Kohya_SS could have these added (currently has v1 and v2)

**Comment by bmaltais** [comment]
Hello, the current code by kohya_ss does not appear to support the new models. He will need to modify his wd14 tagger script for it. Once hw does that I will be able to add support in the GUI.

You can open an issue on his repo: https://github.com/kohya-ss/sd-scripts
