### ISSUE TITLE
For datasets using toml files

### ISSUE THREAD

**Issue by StupidGame** [bmaltais/kohya_ss#2114]
In the future, will there be support for creating configurations of datasets using toml files that are supported by sd-scripts?

**Comment by bmaltais** [comment]
I don't plan to create a GUI for creating the TOML file for dataset... but adding the option so specify a TOML can be done.

**Comment by StupidGame** [comment]
Thank you very much! Please!

**Comment by bmaltais** [comment]
@StupidGame Give the dev branch a try. I have implemented the feature for Dreambooth, LoRA and Finetuning. I will do the TI next but you can already test the feature for the other 3:

**Comment by StupidGame** [comment]
thanks!

**Comment by bmaltais** [comment]
Do you have a good document I could point users to about how to create the TOML?

**Comment by rafstahelin** [comment]
> In the future, will there be support for creating configurations of datasets using toml files that are supported by sd-scripts?

Where can I read about this?
