### ISSUE TITLE
Support for Smiling Wolf new V3 models

### ISSUE THREAD

**Issue by Verun11** [bmaltais/kohya_ss#2116]
Requesting support for these new models:
https://huggingface.co/SmilingWolf/wd-vit-tagger-v3
https://huggingface.co/SmilingWolf/wd-convnext-tagger-v3
https://huggingface.co/SmilingWolf/wd-swinv2-tagger-v3

**Comment by LaikaSa** [comment]
I searched for the same request on kohya_ss repo and found this https://github.com/kohya-ss/sd-scripts/issues/1180#issuecomment-1997410530 , it in Japanese but basically he said he reviewing a pull request for it and will merge as soon as he have time
