### ISSUE TITLE
[SDXL] Final model output only works with the specific checkpoint it was trained with

### ISSUE THREAD

**Issue by JVGA8837** [bmaltais/kohya_ss#2117]
There's this glaring issue with all Kohya trained models currently.

From testing with both Kohya and OneTrainer, Kohya has this issue, whereas OneTrainer does not. SD 1.5 and 2.0 models do not have this issue, and this is also what has caused CivitAI and other model hosters to add the "Pony" model section to their sites.

This seems like a very big issue, and I wanted to make sure you guys knew this is happening. If you'd like me to send my proof and evidence of this, I'd be happy to do so.

**Comment by karen-pal** [comment]
Thanks for the heads up! I only knew about kohya so I assumed that was the standard.

**Comment by bmaltais** [comment]
Have you opened an issue with @kohya-ss about this? Adding him to this thread so he can possible have a look into it...
