### ISSUE TITLE
value for --noise_offset can't be found or set on UI

### ISSUE THREAD

**Issue by tcflying** [bmaltais/kohya_ss#212]

**Comment by Rika-Mipa** [comment]
yeah ,i can't see noise_offset at all

**Comment by bmaltais** [comment]
What trainer are you using. I might have forgotten to make it global... LoRA? Finetune? I will add it to the file of things to fix.

It is under the adwanced section under training:

![image](https://user-images.githubusercontent.com/7474674/221182831-d984b4b0-5e88-44dd-aced-e8a4f9814cf1.png)
