### ISSUE TITLE
Support for QLyCORIS and DoRA

### ISSUE THREAD

**Issue by waomodder** [bmaltais/kohya_ss#2122]
Hello. Thank you for all your efforts in catching and upgrading the tool.

Now to the main topic, QLyCORIS and DoRA are supported in version 2.2.0 of Lycoris, but there is no entry for that at all in the "LoRA type" section of the GUI, so I would like you to add it.
The version used is v23.0.12.

Please work on correcting this.

https://github.com/KohakuBlueleaf/LyCORIS/blob/main/Change.md

![image](https://github.com/bmaltais/kohya_ss/assets/67697932/f68dba12-0bb7-4fb8-8e97-fa983a369b95)

**Comment by bmaltais** [comment]
I will need to get to it... if someone waht to tackle updating the GUI in the meantime I will gladly take a PR for it ;-)

**Comment by bmaltais** [comment]
Support for both can be found in the dev branch. Note that DoRA and QLyCORIS is not an actyal type byt rather a parameter for LoHA, LoKR and LoCon... So if you select either you will find two new options where you can select them... but selecting both will not work.

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8f7524cb-1a74-40ed-8ae8-6d01deddcf07)

**Comment by waomodder** [comment]
Thank you for your prompt response, I will try the Dev version.

**Comment by 8bit-boom** [comment]
Hello, is it possible to use QLyCORIS with BOFT and Diag-OFT?
