### ISSUE TITLE
no sample files generated, can't save lora file after update to newest version

### ISSUE THREAD

**Issue by kitamo1981** [bmaltais/kohya_ss#2123]
after updating to the latest version of kohyass, despite setting Sample every 100 steps, no samples are rendered. Are any additional changes necessary?

After last stem i got error and  it cant save lora file

epoch 1/1
steps: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 255/255 [02:21<00:00,  1.80it/s, avr_loss=0.148]Traceback (most recent call last):
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 1058, in <module>
    trainer.train(args)
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 926, in train
    self.sample_images(accelerator, args, epoch + 1, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "E:\kohyas\kohya_ss\sd-scripts\train_network.py", line 137, in sample_images
    train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "E:\kohyas\kohya_ss\sd-scripts\library\train_util.py", line 4705, in sample_images
    return sample_images_common(StableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "E:\kohyas\kohya_ss\sd-scripts\library\train_util.py", line 4789, in sample_images_common
    if epoch is None or epoch % args.sample_every_n_epochs != 0:
ZeroDivisionError: integer division or modulo by zero
steps: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 255/255 [02:21<00:00,  1.80it/s, avr_loss=0.148]
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohyas\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohyas\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohyas\\kohya_ss\\venv\\Scripts\\python.exe', 'E:\\kohyas\\kohya_ss/sd-scripts/train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--cache_latents_to_disk', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--full_bf16', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--lr_warmup_steps=26', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=512,512', '--max_train_steps=255', '--mixed_precision=bf16', '--network_alpha=8', '--network_dim=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--output_dir=E:/Lora/Jagoda Lora/model', '--output_name=last', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=bf16', '--text_encoder_lr=0.0001', '--train_batch_size=2', '--train_data_dir=E:/Lora/Jagoda Lora/image', '--unet_lr=0.0001', '--xformers', '--sample_sampler=euler_a', '--sample_prompts=E:/Lora/model\\sample\\prompt.txt', '--sample_every_n_epochs=0', '--sample_every_n_steps=0']' returned non-zero exit status 1.

**Comment by ashleykleynhans** [comment]
This is actually an issue with sd-scripts, this is just a GUI.

This issue is present on RunPod as well, one of the people who uses my template reported the same issue:
```
There seems to be a bug in the Kohya_ss, it throws the following error after the first epoch of Lora training: File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4789, in sample_images_common
    if epoch is None or epoch % args.sample_every_n_epochs != 0:
ZeroDivisionError: integer division or modulo by zero
Various epoch numbers and training sets tested, all throw the same :/
```

**Comment by ashleykleynhans** [comment]
I suggest logging here:
https://github.com/kohya-ss/sd-scripts

**Comment by bmaltais** [comment]
This is odd... I am trying to find when this was introduced as a bug... A work around for now is to set the Sample every n epochs to a high number.

I might have introduced a change in the code that is causing this... investigating

**Comment by tedited78** [comment]
> This is odd... I am trying to find when this was introduced as a bug... A work around for now is to set the Sample every n epochs to a high number.

I've tested with 0,1, save every # of epochs = total # of epochs and some random number between 1 and total # of epochs - all behave the same, also tried with max # of epochs. it seems like the gui is not reading/propagating the 'save every # of epochs' field properly...

**Comment by bmaltais** [comment]
I have pushed a new release that should fix the issue... It was a bug I introduced with a recent code update.

**Comment by kitamo1981** [comment]
it works like a dream, now I can easily set epochs = 0 and it renders samples without any problems, reacting to the number of steps set.

**Comment by Kh4rj1** [comment]
> I have pushed a new release that should fix the issue... It was a bug I introduced with a recent code update.

It's working now for me, thanks!
