### ISSUE TITLE
Lycoris slow training after update

### ISSUE THREAD

**Issue by killerciao** [bmaltais/kohya_ss#2129]
After updating to the latest release (git pull->setup.bat) 
Lycoris/LoCon (the only one i tested) is super slow. With my 4090 with the same setting loaded in the previous version was running at about 1it/s for SDXL training, now 10s/it.
Nothing has changed in the training data.
Standard LoRA training works fine.

**Comment by bmaltais** [comment]
The latest release is using the v2.2.0.post3 module of lycoris... Maybe there is a bug with it? You might want to open an issue directly with the author as I only provide the GUI... 

https://github.com/KohakuBlueleaf/LyCORIS

**Comment by killerciao** [comment]
I'll write @ lycoris repo when I have time. This must be something related to the update for sure because rolling back to previous version fixes the problem.
😅
