### ISSUE TITLE
error after download interrupted

### ISSUE THREAD

**Issue by wwwffbf** [bmaltais/kohya_ss#213]
I accidentally interrupted the download of pytorch_model.bin during the first run of the dreambooth lora train。（after loading vae..）Later, when I run train again, it will not resume the download, but will pop up these errors, is it because there is a cache not cleared?

Traceback (most recent call last):
  File "E:\SDiff\LoraTrain\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict    return torch.load(checkpoint_file, map_location="cpu")
  File "E:\SDiff\LoraTrain\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "E:\SDiff\LoraTrain\kohya_ss\venv\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by wwwffbf** [comment]
![qwe](https://user-images.githubusercontent.com/22142994/220269768-77d54337-251e-4922-8d24-7ed73f26ae99.png)

**Comment by callomerlose** [comment]
I have the same error. This happens after the download is interrupted

**Comment by callomerlose** [comment]
I solved this issue ,its ok now.
delete your c:\Users\yourname\.cache\huggingface folder and do it agian,good luck.

**Comment by wwwffbf** [comment]
> 

You're amazing, buddy! Problem solved

**Comment by wwwffbf** [comment]
> I solved this issue ,its ok now. delete your c:\Users\yourname.cache\huggingface folder and do it agian,good luck.

You're amazing, buddy! Problem solved
