### ISSUE TITLE
Finetuning Stable Diffusion XL base 1.0 - attention_head_dim missing one head

### ISSUE THREAD

**Issue by padmalcom** [bmaltais/kohya_ss#2133]
Hi, I tried to finetune the sdxl base 1.0 model on a custom dataset using the following command:

`accelerate launch --num_cpu_threads_per_process 8 fine_tune.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" --in_json "D:\Datasets\images\sdxlclean\meta_lat.json" --train_data_dir="D:\Datasets\images\sdxlclean" --output_dir=fine_tuned --shuffle_caption --train_batch_size=1 --learning_rate=5e-6 --max_train_steps=10000 --use_8bit_adam --xformers --gradient_checkpointing --mixed_precision=fp16 --save_every_n_epochs=4 --v2`

At the beginning of the training, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\admin\python\kohya_ss\sd-scripts\fine_tune.py", line 505, in <module>
    train(args)
  File "C:\Users\admin\python\kohya_ss\sd-scripts\fine_tune.py", line 113, in train
    text_encoder, vae, unet, load_stable_diffusion_format = train_util.load_target_model(args, weight_dtype, accelerator)
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\train_util.py", line 4113, in load_target_model
    text_encoder, vae, unet, load_stable_diffusion_format = _load_target_model(
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\train_util.py", line 4088, in _load_target_model
    original_unet = UNet2DConditionModel(
  File "C:\Users\admin\python\kohya_ss\sd-scripts\library\original_unet.py", line 1430, in __init__
    attn_num_head_channels=attention_head_dim[i],
IndexError: list index out of range
```

I found out that the attention head dim has a length of 3, but the DOWN_BLOCK_TYPES has a length of 4. This architectural difference between stable diffusion 2.1 and sdxl causes this crash - sd 2.1 has DOWN_BLOCK_TYPES of length 3.

Any fix for the finetuning script is apreciated.

Edit: This could be related to this issue: https://github.com/huggingface/diffusers/issues/2011

**Comment by bmaltais** [comment]
Hi, since my repo only use the sd-scripts from kohya I can't actually fix this. Please open a PR directly on kohya's repo to see if he can address this issue:

https://github.com/kohya-ss/sd-scripts

**Comment by padmalcom** [comment]
Thanks, I'll post it there.

**Comment by alecwattsgrab** [comment]
Did you find a solution to this error?
