### ISSUE TITLE
Docker file:///app/sd-scripts does not appear to be a Python project

### ISSUE THREAD

**Issue by mambari** [bmaltais/kohya_ss#2134]
Hi,
I try to build the docker image, but I have an issue.

`=> ERROR [build 5/6] RUN --mount=type=cache,id=pip-amd64,sharing=locked,target=/root/.cache/pi  0.8s 
------
 > [build 5/6] RUN --mount=type=cache,id=pip-amd64,sharing=locked,target=/root/.cache/pip     --mount=source=requirements_linux_docker.txt,target=requirements_linux_docker.txt     --mount=source=requirements.txt,target=requirements.txt     --mount=source=setup/docker_setup.py,target=setup.py     --mount=source=sd-scripts,target=sd-scripts,rw     pip install -r requirements_linux_docker.txt -r requirements.txt:
0.716 Obtaining file:///app/sd-scripts (from -r requirements.txt (line 46))
0.717 ERROR: file:///app/sd-scripts (from -r requirements.txt (line 46)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
------
Dockerfile:38
--------------------
  37 |     # Install requirements
  38 | >>> RUN --mount=type=cache,id=pip-$TARGETARCH$TARGETVARIANT,sharing=locked,target=/root/.cache/pip \
  39 | >>>     --mount=source=requirements_linux_docker.txt,target=requirements_linux_docker.txt \    
  40 | >>>     --mount=source=requirements.txt,target=requirements.txt \
  41 | >>>     --mount=source=setup/docker_setup.py,target=setup.py \
  42 | >>>     --mount=source=sd-scripts,target=sd-scripts,rw \
  43 | >>>     pip install -r requirements_linux_docker.txt -r requirements.txt
  44 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements_linux_docker.txt -r requirements.txt" did not complete successfully: exit code: 1`

Line 46 of requirement.txt
-e ./sd-scripts # no_verify leave this to specify not checking this a verification stage

**Comment by jim60105** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/16995691/a6ab8c20-6c2d-40ab-a1eb-2ba593548b5f)

Or, do a _**FRESH**_ `git clone --recursive https://github.com/bmaltais/kohya_ss.git` before docker build.
