### ISSUE TITLE
Another install issue thread...

### ISSUE THREAD

**Issue by MaestroFury** [bmaltais/kohya_ss#2136]
Hey Everyone, here's yet another can't install Kohya thread. I'm getting the same error so many others before me have gotten.

C:\Users\Administrator\Desktop\Kohya>setup.bat
Creating venv...
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Kohya\setup\setup_windows.py", line 7, in <module>
    import setup_common
  File "C:\Users\Administrator\Desktop\Kohya\setup\setup_common.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

I tried deleting the venv folder, I have the latest PHP installed.

I've tried pip install setuptools, and basically everything I've found online in other threads. I've gone into the windows setup file and changed line 19 and I believe it was 227 as detailed in this thread https://github.com/bmaltais/kohya_ss/issues/1673

I can just not get past this point... any advice?

**Comment by bmaltais** [comment]
Are you using python 3.10.11 installed from python.org as per the installation instructions?

**Comment by MaestroFury** [comment]
when I try to install Python 3.10.11 specifically, the installer rejects it because I have the latest version, and just reverts changes. 

Should I uninstall Python to reinstall 3.10.11 specifically? I think it might break SD Forge?

**Comment by bmaltais** [comment]
What is the version you have installed already? 3.10.11 or a newer version like 3.11.x or 3.12.x?

But uninstalling and re-installing should not hurt.

**Comment by MaestroFury** [comment]
- I uninstalled 3.12.2 completely
- I re-installed 3.10.11
- I restarted the PC
- Setup now works. 

So for future people who find this thread, do that first.

SD Forge seems to still work just fine :). Thank you bmaltais.

**Comment by bmaltais** [comment]
> I currently have 3.12.2. I'll try uninstalling if you think that's the break point.

It 110% is ;-) At the moment, interfaces like auto1111 webui and kohya_ss GUI are forced to use python 3.10.6+ due to Python dependancies.
