### ISSUE TITLE
Some errors during installation, GUI still opens, but training doesn't start and crashes

### ISSUE THREAD

**Issue by MaestroFury** [bmaltais/kohya_ss#2147]
Hello everyone!

I was able to get the install started after completely uninstalling PHP 3.12.x and reinstalling 3.10.11 as instructed. However, I got some errors during the install which didn't seem to stop the train, until I actually tried to train something. 

Here are the errors.

**When entering 1 (install kohya_ss GUI)**
fatal: not a git repository (or any of the parent directories): .git
15:18:26-559748 ERROR    Error during Git operation: Command '['git', 'submodule', 'update', '--init', '--recursive',
                         '--quiet']' returned non-zero exit status 128.

15:28:46-530738 INFO     Installing package: -e ./sd-scripts
15:28:46-932091 ERROR    Error running pip: install --upgrade -e ./sd-scripts

**When entering 2 (install cudnn files)**
15:50:47-566311 INFO     Installing nvidia-cudnn-cu11 8.9.5.29...
15:50:47-567310 INFO     Installing package: nvidia-cudnn-cu11==8.9.5.29
15:52:56-237977 INFO     Copying CUDNN files from C:\Users\Administrator\Desktop\Kohya\cudnn_windows to
                         C:\Users\Administrator\Desktop\Kohya\venv\Lib\site-packages\torch\lib...
15:52:56-239974 ERROR    Installation Failed: "C:\Users\Administrator\Desktop\Kohya\cudnn_windows" could not be found.

now, when I start up the GUI, I get these errors.
fatal: not a git repository (or any of the parent directories): .git
15:53:28-480198 ERROR    Error during Git operation: Command '['git', 'submodule', 'update', '--init', '--recursive',
                         '--quiet']' returned non-zero exit status 128.

C:\Users\Administrator\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'C:\\Users\\Administrator\\Desktop\\Kohya\\sd-scripts\\sdxl_train_network.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\Kohya\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\Desktop\Kohya\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\Administrator\Desktop\Kohya\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\Administrator\Desktop\Kohya\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher

Then it gives a bunch of parameters I entered into the GUI, but doesn't actually start... any ideas?

**Comment by bmaltais** [comment]
Did you use the fit clone command. You can use the zip file to install the project. Delete the complete folder and clone it using gut. It should fix the issues.

**Comment by MaestroFury** [comment]
you absolute legend, that fixed it. Lesson learned, use git clone in general instead of downloading a zip file.
