### ISSUE TITLE
someone knows hot to fix this problem? It keeps appearing to me every time I start training : ''returned non-zero exit status 1''

### ISSUE THREAD

**Issue by waifuista** [bmaltais/kohya_ss#2151]
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizers
Using DreamBooth method.
prepare images.
found directory C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\img\15_cyborggirl girl contains 21 image files
found directory C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl contains 40 image files
No caption file found for 40 images. Training will continue without captions for these images. If class token exists, it will be used. / 40枚の画像にキャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (1).png
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (10).png
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (11).png
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (12).png
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (13).png
C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl\img (14).png... and 35 more
315 train images with repeating.
40 reg images.
[Dataset 0]
  batch_size: 2
  resolution: (1024, 1024)
  enable_bucket: True
  network_multiplier: 1.0
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\img\15_cyborggirl girl"
    image_count: 21
    num_repeats: 15
    shuffle_caption: True
    keep_tokens: 1
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: cyborggirl girl
    caption_extension: .txt

  [Subset 1 of Dataset 0]
    image_dir: "C:\Users\kauan Pc\Pictures\LoRA Train\data_cyborg_concept\cyborgirl_data\dest-test1\dest\reg\1_girl"
    image_count: 40
    num_repeats: 1
    shuffle_caption: True
    keep_tokens: 1
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: girl
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 61/61 [00:00<00:00, 770.51it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視さ れます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (1024, 1024), count: 630
mean ar error (without repeats): 0.0
preparing accelerator
loading model for process 0/1
load StableDiffusion checkpoint: C:/Users/kauan Pc/Documents/MODELS/checkpoint/SDXL/animagineXLV31_v31.safetensors
building U-Net
loading U-Net from checkpoint
U-Net:  <All keys matched successfully>
building text encoders
loading text encoders from checkpoint
text encoder 1: <All keys matched successfully>
text encoder 2: <All keys matched successfully>
building VAE
loading VAE from checkpoint
VAE: <All keys matched successfully>
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|██████████████████████████████████████████████████████████████████████████████████████████| 61/61 [00:00<?, ?it/s]
caching latents...
100%|██████████████████████████████████████████████████████████████████████████████████| 61/61 [01:51<00:00,  1.82s/it]
create LoRA network. base dim (rank): 32, alpha: 1.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder 1:
create LoRA for Text Encoder 2:
create LoRA for Text Encoder: 264 modules.
create LoRA for U-Net: 722 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use Adafactor optimizer | {'relative_step': True, 'scale_parameter': True, 'warmup_init': True}
relative_step is true / relative_stepがtrueです
learning rate is used as initial_lr / 指定したlearning rateはinitial_lrとして使用されます
unet_lr and text_encoder_lr are ignored / unet_lrとtext_encoder_lrは無視されます
use adafactor_scheduler / スケジューラにadafactor_schedulerを使用します
Traceback (most recent call last):
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\train_network.py", line 413, in train
    unet = accelerator.prepare(unet)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1213, in prepare
    result = tuple(
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1214, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1094, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 1334, in prepare_model
    model = model.to(self.device)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes is free. Of the allocated memory 5.03 GiB is allocated by PyTorch, and 282.58 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Python3109\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3109\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\kauan Pc\Documents\No nome de Jesus\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\kauan Pc\\Documents\\No nome de Jesus\\kohya_ss\\venv\\Scripts\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/Users/kauan Pc/Documents/MODELS/checkpoint/SDXL/animagineXLV31_v31.safetensors', '--train_data_dir=C:/Users/kauan Pc/Pictures/LoRA Train/data_cyborg_concept/cyborgirl_data/dest-test1/dest\\img', '--reg_data_dir=C:/Users/kauan Pc/Pictures/LoRA Train/data_cyborg_concept/cyborgirl_data/dest-test1/dest\\reg', '--resolution=1024,1024', '--output_dir=C:/Users/kauan Pc/Pictures/LoRA Train/data_cyborg_concept/cyborgirl_data/dest-test1/dest\\model', '--logging_dir=C:/Users/kauan Pc/Pictures/LoRA Train/data_cyborg_concept/cyborgirl_data/dest-test1/dest\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=1e-05', '--unet_lr=0.0001', '--network_dim=32', '--output_name=15_cyborg_girl', '--lr_scheduler_num_cycles=6', '--no_half_vae', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1890', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--cache_latents_to_disk', '--optimizer_type=Adafactor', '--optimizer_args', '--optimizer_args', 'relative_step=True', 'scale_parameter=True', 'warmup_init=True', '--max_grad_norm=1', '--max_data_loader_n_workers=0', '--keep_tokens=1', '--bucket_reso_steps=64', '--shuffle_caption', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1

**Comment by b-fission** [comment]
It's crashing because your GPU doesn't have enough vram.

Yours seems to be 6gb which is not enough to do sdxl training. I think 10gb vram was the _bare_ minimum to get that started.

**Comment by waifuista** [comment]
I was trying to find a low RAM setting but I saw that it won't work, sad
