### ISSUE TITLE
How to trainning unet only in GUI?

### ISSUE THREAD

**Issue by littleyeson** [bmaltais/kohya_ss#2156]
How to trainning unet only in GUI?

**Comment by bmaltais** [comment]
Set the TE LR to 0 and it will spit out the argument to train unet only

**Comment by littleyeson** [comment]
> Set the TE LR to 0 and it will spit out the argument to train unet only

Thx. Setting TE LR to 0 will automatically train only the unet? No need to change network unet only=1 like in the script?

**Comment by bmaltais** [comment]
Correct. The GUI will specify that parameter automatically.

**Comment by littleyeson** [comment]
> Correct. The GUI will specify that parameter automatically.

thx
