### ISSUE TITLE
No error in v23.0.0 in v23.0.15 -> Error: Accelerate CLI tool: error: unrecognized arguments: --max_grad_norm=None

### ISSUE THREAD

**Issue by Ehtz** [bmaltais/kohya_ss#2157]
Hello everyone and bmaltais,

When starting Lora training SD.1.5 i get this error. In the Kohya_SS version v23.0.0 it used to work same params.

<img width="561" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/121399963/93f849c5-8c6e-4507-9b82-7287a3e852f7">

This is my params that worked in v23.0.0
<img width="646" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/121399963/b03f392b-3fc0-430c-9608-b15f797b1d68">

Thanks in advance for help on this issue.

**Comment by bmaltais** [comment]
Is this using the `dev` branch? I made a change last night... Hope I did not introduce a bug...

**Comment by Ehtz** [comment]
> Is this using the `dev` branch? I made a change last night... Hope I did not introduce a bug... yep... look like I did...
Yep, it was ```dev```, I am in main now did git pull then going to reinstall venv see what happens,

Thank!

**Comment by bmaltais** [comment]
No need to re-install... just do:

```
git checkout master
git pull
```

**Comment by bmaltais** [comment]
I have pushed the fix to dev

**Comment by Ehtz** [comment]
Thanks, now i am getting an error with the LR scheduler I never used to have this error before. Do you have some insight into what it is? 

<img width="1274" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/121399963/ae2ad4b3-3a41-4cdc-be97-88e41f8d93a9">

<img width="984" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/121399963/0de2fe12-7079-4580-a851-f978bffb15b3">

**Comment by Ehtz** [comment]
I tried all LR to 1 and LR TE1 then received a CUDA error, I am reverting to v23.0.0 before the major UI update

**Comment by bmaltais** [comment]
Are you setting the UNet LR to 0 or leaving it empty?

**Comment by Ehtz** [comment]
It has been solved, confusing myself with the new UI so Lora and Dreambooth confusion within the tabs. (maybe colour code it)
Thanks bmaltais for always giving it your all, I appreciate it.
