### ISSUE TITLE
(Optional) Install CuDNN files (to use the latest supported CuDNN version) - does not work and just hangs.

### ISSUE THREAD

**Issue by XTRMsavage** [bmaltais/kohya_ss#2158]
![image](https://github.com/bmaltais/kohya_ss/assets/90519573/442d7442-a37e-48a0-8bd4-fa264ea586da)
Hi, I am trying to install the CUDNN files but it will just show this message and won't install. I have downloaded CUDNN 9.0.0 (image below) and just want to know how to install it properly in the local environment without causing any issues to my other programs. Thanks
![image](https://github.com/bmaltais/kohya_ss/assets/90519573/8e5f350f-3ee9-43e3-84b5-db39b9f738dd)

**Comment by bmaltais** [comment]
Here is a link to how it is installed... you need to manually copy files in the venv as is done by the code:

https://github.com/bmaltais/kohya_ss/blob/5bbb4fcf781f870a5cd58557dab87b4e2ef13c6d/setup/setup_windows.py#L18

**Comment by XTRMsavage** [comment]
> Here is a link to how it is installed... you need to manually copy files in the venv as is done by the code:
> 
> https://github.com/bmaltais/kohya_ss/blob/5bbb4fcf781f870a5cd58557dab87b4e2ef13c6d/setup/setup_windows.py#L18

![image](https://github.com/bmaltais/kohya_ss/assets/90519573/e432eaba-3cf2-4887-ae9e-05c1decc6cf4)

Yes, It's not installed. How can I install the cudnn_9.0.0_windows into the root folder?

**Comment by bmaltais** [comment]
I re-tested the feature and it does install cudann fine on my system... but you have to be patient cause it take quite a while to install the python module... perhaps you are not waiting long enough? Expect between 5 and 10 minutes depending on your internet speed.

**Comment by XTRMsavage** [comment]
> I re-tested the feature and it does install cudann fine on my system... but you have to be patient cause it take quite a while to install the python module... perhaps you are not waiting long enough? Expect between 5 and 10 minutes depending on your internet speed.

Yes, You are correct. I did a second try and it got installed. Thanks
