### ISSUE TITLE
Whatever I do cant make this run on Vast.AI

### ISSUE THREAD

**Issue by cipherpodliq1** [bmaltais/kohya_ss#2160]
I am trying to train my own influencer LoRa, but i get this error. Changed precision , made the manual config step and everything that I could find on the internet. If someone has any suggestions for fixing this, please let me know

Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', '/workspace/kohya_ss/sd-scripts/train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=1', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=512,512', '--mixed_precision=bf16', '--network_alpha=1', '--network_dim=8', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--output_dir=/workspace/kohya_ss/outputs', '--output_name=Valentina_Moon', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--reg_data_dir=/workspace/kohya_ss/dataset', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=bf16', '--text_encoder_lr=0.0001', '--train_batch_size=1', '--train_data_dir=/workspace/kohya_ss/dataset', '--unet_lr=0.0001', '--xformers']' died with <Signals.SIGILL: 4>.

**Comment by bmaltais** [comment]
Is vast using CUDA 11.8? I never used it and mostly test on Windows (and WSL2 once in a while)...

**Comment by cipherpodliq1** [comment]
Yes they all support CUDA , it is stated under the instances tab (Max CUDA: 12.2)

![image](https://github.com/bmaltais/kohya_ss/assets/148264989/076849e1-00db-4b12-a5bd-847d3cf6c903)

**Comment by bmaltais** [comment]
But is it running CUDA 11.8 in the instance... kohya_ss is expecting CUDA 11.8... and wont work as is with CIDA 12.2... To work under 12.2 you need to update the requirements to install with pytorch modules made for 12.2 instead of 11.8...

**Comment by bmaltais** [comment]
What is the CUDA reported when you run the gui? 11.8 or 12.x?

**Comment by cipherpodliq1** [comment]
so it is a cuda error. I have not tought of this. Please let me try this and I will give an update

**Comment by cipherpodliq1** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/148264989/43499e4b-f581-45eb-b317-52126090416b)
This is what I get when I straight ssh into the system - so it is 11.8

**Comment by bmaltais** [comment]
OK. You can also check what the ./gui.sh report: 
![image](https://github.com/bmaltais/kohya_ss/assets/7474674/8430f3b4-a448-433f-938b-46196b8d0322)

If it report 11.8 then pytorch is not the issue

**Comment by cipherpodliq1** [comment]
Yes i just checked it is 11.8

**Comment by bmaltais** [comment]
No idea then as to why it doesn’t work

**Comment by Felixxxofficial** [comment]
I have the same problem, it doesn't work on vast.ai and their support is very unfriendly.

**Comment by ashleykleynhans** [comment]
Use [RunPod](https://runpod.io/console/gpu-cloud?template=51q837fywe&ref=2xxro4sy), works fine on RunPod and RunPod support is infinitely better than Vast.ai.
