### ISSUE TITLE
Training LORA can use  Tensor Cores ?

### ISSUE THREAD

**Issue by littleyeson** [bmaltais/kohya_ss#2162]
Kohya_ss training LORA can use Tensor Cores to quickly?

**Comment by bmaltais** [comment]
I am not sure. Have you asked kohya on his sd-scripts repo? https://github.com/kohya-ss/sd-scripts

**Comment by littleyeson** [comment]
> I am not sure. Have you asked kohya on his sd-scripts repo? https://github.com/kohya-ss/sd-scripts

thx
