### ISSUE TITLE
Folder browsing has become inconvenient

### ISSUE THREAD

**Issue by mykeehu** [bmaltais/kohya_ss#2168]
In the latest version, folder browsing does not open the last used directory, but always the directory kohya_ss. This makes the workflow inconvenient, because I have to constantly search for the training, log, model, images folders again. Can I request to use the last folder again for the folder browse button? Or maybe an option where this can be changed?

**Comment by bmaltais** [comment]
Hummm, this will not be possible. If you want to propose a solution via a Pull Request I would gladly accept it if it make the behaviour what you expect vs what it is now. At this point there is no easy going back, short of using the older releases.

**Comment by mykeehu** [comment]
Unfortunately I'm not a programmer, so I can't do PR for this. Saving the config file is fine, it works there, it opens the last used folder. However, in the other cases (model, log, img) it always opens the kohya_ss folder, slowing down the workflow compared to before.

**Comment by mykeehu** [comment]
I did not know that the default folder can be set, thanks for this tip!
I was thinking that when I specify the img folder, for example, this is the path when I load it:
D:\Loramodels\mystacy\img\
When I press the Browse button for the model save folder, this path came up earlier:
D:\Loramodels\mystacy\img\
Now it comes up C:\kohya_ss
Now, when I need to select the Log folder, C:\kohya_ss comes up again, so I have to keep looking for the D:\Loramodels\mystacy folder again.
It was fine before because it always opened the last folder (for example C:\Loramodels\mystacy\log\ or C:\Loramodels\mystacy\model\)
But I can probably work around this by setting the C:\Loramodels folder to permanent based on your tip.
