### ISSUE TITLE
Could not automatically configure accelerate.

### ISSUE THREAD

**Issue by Felixxxofficial** [bmaltais/kohya_ss#2169]
07:13:28-753950 WARNING  Could not automatically configure accelerate. Please manually configure accelerate with the option in the menu or with: accelerate config.                                                          
Copying accelerate config file to: /root/.cache/huggingface/accelerate/default_config.yaml
07:13:29-009535 INFO     Kohya_ss GUI version: v23.0.15                                                                                                                                                                      
07:13:29-042477 INFO     Submodule initialized and updated.                                                                                                                                                                  
07:13:29-045434 INFO     nVidia toolkit detected                                                                                                                                                                             
07:13:29-048294 ERROR    Could not load torch: No module named 'torch'  

Kohya_ss GUI version: v23.0.15  

How can I fix this please?

**Comment by bmaltais** [comment]
Run the "5. (Optional) Manually configure Accelerate" option in the setup.bat menu, that will do it.

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/2f17c9fe-4cb3-4b53-9e1c-a4121a3c573b)
