### ISSUE TITLE
Images with uppercase extension don't get processed

### ISSUE THREAD

**Issue by Phrosh** [bmaltais/kohya_ss#217]
While training LoRA and having images with .jpg and .JPEG, all images count to "num train images" and "patches per epoch" but the files with an uppercase extension are ignored in the LoRA steps. They are ignored for the important part.

**Comment by bmaltais** [comment]
Yeah... this is because the kohya_ss trainer code (and mine by extension) only check for lowercase extension... I could fix my code but kohya_ss will also need to fix his... I guess I could do my part ;-) Will add it to the list of things to do.

**Comment by bmaltais** [comment]
I will wait for kohya to fix the issue in his code before updating mine... to be consistent.

**Comment by JS3910** [comment]
Would it not be "better" to just have, for example the "prepare folders" preprocessing just rename these to an extension that will work?
