### ISSUE TITLE
Why kohya_ss inference speed faster than diffusers or Onetrainer?

### ISSUE THREAD

**Issue by zengjie617789** [bmaltais/kohya_ss#2172]
I trained a lora with kohya_ss and Onetrainer, I'm confused that why the lora with kohya_ss is much faster than using diffusers?
If the network is different from others, why diffusers state dict can convert into kohya_ss?

**Comment by bmaltais** [comment]
This is a good question to ask the author of the sd-scripts used by the GUI. You can ask him directly in his repo: https://github.com/kohya-ss/sd-scripts
