### ISSUE TITLE
SDXL trained LORAs not visible on Auto1111/Forge, visible on FOOOCUS, SDXL Lora missing Meta data?

### ISSUE THREAD

**Issue by MaestroFury** [bmaltais/kohya_ss#2173]
So I trained an SDXL LORA, and I'm loving this so much... but for the life of me, I could not get Auto1111/SD Forge to see the LORA. Only FOOOCUS can see it, and use it (to great effect).

I created a ticket on both Auto1111 and Forge, and they claim the reason they cannot see the lora, is because the lora is missing Meta information. There is hard resistance that this is a problem on their end. 

I am unsure how to check if my lora has meta data. 

The SD1.5 Lora I trained, has Meta data. But SDXL doesn't?

I will also add

When I started the SDXL training, I said 10 epochs. I didn't realize at the time, each epoch would want 8 hours of training. So I interrupted the training at 2 epochs.

Would this have any impact? Is Meta data added at the end of training? Why would the SD1.5 version, which completed training all the way have meta data, but not SDXL, other then the possibility I interrupted that training?

**Comment by Mosfett1975** [comment]
Try to choice sdxl base model in Automatic1111, after that you'll see you're LORA

**Comment by MaestroFury** [comment]
you are correct. I feel so silly. Thank you so much Mosfett. Having chosen an SDXL base model, I now see the lora in both Forge/Auto1111
