### ISSUE TITLE
Problem with captioning ! 

### ISSUE THREAD

**Issue by MIKETUFFIN66** [bmaltais/kohya_ss#2179]
Hello , 
after installing Kohya_ss , its working fine but .. captioning says captioning DONE! and nothing is captioned ... 
then i look into the sd-scripts folder and its Empty ! 
then i copied the sd-scripts folder from here to my folder and still captioning not working .. for example WD TAGGER ! 

what is the solution? or what have i done wrong here? ... thanks in advance .

**Comment by 5KilosOfCheese** [comment]
Can you post a screenshot of the caption settings you use on the GUI?
The captions go to the image folder you input to be captioned.

**Comment by MIKETUFFIN66** [comment]
> Can you post a screenshot of the caption settings you use on the GUI? The captions go to the image folder you input to be captioned.

Ofcourse ... for example if i choose basic captioning like in the attachment ,, it says its done but there is nothing only images with out captions ... 

![11](https://github.com/bmaltais/kohya_ss/assets/162156359/8b4226bd-d40f-42b5-8ffd-bbf375ce15ee)
![22](https://github.com/bmaltais/kohya_ss/assets/162156359/06e0b5b4-4645-4215-b139-b2ee7fe229d4)

then when i choose WD14 this time .. it gives a long error which i have no idea what it means ,,, 

![33](https://github.com/bmaltais/kohya_ss/assets/162156359/9e762f1f-aeab-44c0-9039-452f8c9f6eeb)
![44](https://github.com/bmaltais/kohya_ss/assets/162156359/904e57ff-718d-4508-916c-39020c7d03ba)
![55](https://github.com/bmaltais/kohya_ss/assets/162156359/07d824c6-2b86-45cd-b4ea-72a2460e507d)
![66](https://github.com/bmaltais/kohya_ss/assets/162156359/6b162a53-23da-4a3b-946c-e86fb548ed88)

**Comment by 5KilosOfCheese** [comment]
You didn't give anything for the basic caption to caption. It will not create a empty text file. It will say "captioning done" because there was nothing for it to do and thus it finished the task.

Add something to the fields and enable "overwrite captions", and see if this work.

For the waifu tagger, it can't find the model for some reason. See if the "force download" fixes it. I'm not familiar with the WD14 system. 

But lets see if the basic captioning works to begin with.

**Comment by MIKETUFFIN66** [comment]
> You didn't give anything for the basic caption to caption. It will not create a empty text file. It will say "captioning done" because there was nothing for it to do and thus it finished the task.
> 
> Add something to the fields and enable "overwrite captions", and see if this work.
> 
> For the waifu tagger, it can't find the model for some reason. See if the "force download" fixes it. I'm not familiar with the WD14 system.
> 
> But lets see if the basic captioning works to begin with.

Ok your right about the basic caption , overwrite capitions worked when i gave the captions...
about the WD14 : 
1- I forced download 
2- when its done i check ONNX and it worked :) 

Thanks
