### ISSUE TITLE
While training this Error appears what it means ? 

### ISSUE THREAD

**Issue by MIKETUFFIN66** [bmaltais/kohya_ss#2183]
. py: 182: FutureWarning:
eteScheduIer {
_class_name" :
" EulerAncestraIDiscreteScheduIer" ,
_ diffusers _ version " :
"0.25. 0"
" beta_end
0.012,
"beta _ schedule": "scaled_tinear"
"beta_start": O. 00085,
" num_train_timesteps
1000
"prediction _ type": "epsilon" ,
"rescale_betas_zero_snr": false,
"steps_offset": O
: "linspace"
"timestep _ spacing
"trained_betas " :
null
The configuration file of this scheduler:
EulerAncestraIDiscr
is outdated.
'steps_offset' should be set to 1 instead of O. Please make sure to update the config accordingly as leavi
ng 'steps_offset' might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hug
ging Face Hub, it would be very nice if you could open a Pull request for the 'scheduler/scheduler_config.json' file
deprecate( " steps_offset ! "
deprecation_message, standard_warn=FaIse)
![error Screenshot 2024-03-30 232759](https://github.com/bmaltais/kohya_ss/assets/162156359/319bc585-d010-4dc3-a3a0-ade78266c6c4)

**Comment by bmaltais** [comment]
You should open an issue on Kohya sd-scripts repo as this appear to be related to the config you provided for the image sampling during the training.

**Comment by MIKETUFFIN66** [comment]
> . py: 182: FutureWarning:
> eteScheduIer {
> _class_name" :
> " EulerAncestraIDiscreteScheduIer" ,
> _ diffusers _ version " :
> "0.25. 0"
> " beta_end
> 0.012,
> "beta _ schedule": "scaled_tinear"
> "beta_start": O. 00085,
> " num_train_timesteps
> 1000
> "prediction _ type": "epsilon" ,
> "rescale_betas_zero_snr": false,
> "steps_offset": O
> : "linspace"
> "timestep _ spacing
> "trained_betas " :
> null
> The configuration file of this scheduler:
> EulerAncestraIDiscr
> is outdated.
> 'steps_offset' should be set to 1 instead of O. Please make sure to update the config accordingly as leavi
> ng 'steps_offset' might led to incorrect results in future versions. If you have downloaded this checkpoint from the Hug
> ging Face Hub, it would be very nice if you could open a Pull request for the 'scheduler/scheduler_config.json' file
> deprecate( " steps_offset ! "
> deprecation_message, standard_warn=FaIse)

i opened an issue to see thanks
