### ISSUE TITLE
Error installing Kohya_ss

### ISSUE THREAD

**Issue by ellyoun13** [bmaltais/kohya_ss#2190]
![image](https://github.com/bmaltais/kohya_ss/assets/160593453/080b0c43-2bf1-4212-a01d-a306282eb17b)

Kohya_ss setup menu:

1. Install kohya_ss GUI
2. (Optional) Install CuDNN files (to use the latest supported CuDNN version)
3. (Optional) Install Triton 2.1.0 for Windows
4. (Optional) Install specific version of bitsandbytes
5. (Optional) Manually configure Accelerate
6. (Optional) Launch Kohya_ss GUI in browser
7. Exit Setup

Select an option: 1

17:08:53-451904 INFO     Kohya_ss GUI version: v23.0.15
17:08:53-459903 INFO     Python version is 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:20:04) [MSC v.1929 32 bit
                         (Intel)]
17:08:54-456706 INFO     Submodule initialized and updated.
17:08:54-458707 INFO     Installing modules from requirements_windows_torch2.txt...
17:08:54-460706 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         xformers==0.0.23.post1+cu118 --index-url https://download.pytorch.org/whl/cu118
17:08:56-335936 ERROR    Error running pip: install --upgrade torch==2.1.2+cu118 torchvision==0.16.2+cu118
                         torchaudio==2.1.2+cu118 xformers==0.0.23.post1+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
17:08:56-337936 INFO     Installing package: bitsandbytes==0.43.0
17:08:57-196449 ERROR    Error running pip: install --upgrade bitsandbytes==0.43.0
17:08:57-197449 INFO     Installing package: tensorboard==2.14.1 tensorflow==2.14.0
17:08:58-158923 ERROR    Error running pip: install --upgrade tensorboard==2.14.1 tensorflow==2.14.0
17:08:58-160923 INFO     Installing modules from requirements.txt...
17:08:58-161926 INFO     Installing package: accelerate==0.25.0
17:08:59-095888 ERROR    Error running pip: install --upgrade accelerate==0.25.0
17:08:59-097888 INFO     Installing package: altair==4.2.2
17:09:25-818847 ERROR    Error running pip: install --upgrade altair==4.2.2
17:09:25-820850 INFO     Installing package: diffusers[torch]==0.25.0
17:09:27-289038 ERROR    Error running pip: install --upgrade diffusers[torch]==0.25.0
17:09:27-291036 INFO     Installing package: fairscale==0.4.13
17:09:28-372699 ERROR    Error running pip: install --upgrade fairscale==0.4.13
17:09:28-375694 INFO     Installing package: gradio==3.50.2
17:10:25-831642 ERROR    Error running pip: install --upgrade gradio==3.50.2
17:10:25-833642 INFO     Installing package: invisible-watermark==0.2.0
17:10:27-121838 ERROR    Error running pip: install --upgrade invisible-watermark==0.2.0
17:10:27-123838 INFO     Installing package: lion-pytorch==0.0.6
17:10:28-070724 ERROR    Error running pip: install --upgrade lion-pytorch==0.0.6
17:10:28-072726 INFO     Installing package: lycoris_lora==2.2.0.post3
17:10:36-415649 ERROR    Error running pip: install --upgrade lycoris_lora==2.2.0.post3
17:10:36-418649 INFO     Installing package: onnxruntime-gpu==1.16.0
17:10:37-995255 ERROR    Error running pip: install --upgrade onnxruntime-gpu==1.16.0
17:10:37-997255 INFO     Installing package: open-clip-torch==2.20.0
17:10:38-947994 ERROR    Error running pip: install --upgrade open-clip-torch==2.20.0
17:10:38-949992 INFO     Installing package: pytorch-lightning==1.9.0
17:10:39-974161 ERROR    Error running pip: install --upgrade pytorch-lightning==1.9.0
17:10:39-976163 INFO     Installing package: timm==0.6.12
17:10:40-921288 ERROR    Error running pip: install --upgrade timm==0.6.12
17:10:40-924288 INFO     Installing package: scipy==1.11.4
17:11:28-318576 ERROR    Error running pip: install --upgrade scipy==1.11.4
17:11:28-320573 INFO     Installing package: -e ./sd-scripts
17:11:40-308823 INFO     Configuring accelerate...
------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
Please select a choice using the arrow or number keys, and selecting with enter
 * This machine
    AWS (Amazon SageMaker)

**Comment by ellyoun13** [comment]
I tried to install the elements of the requirements individually using the cmd, but this also failed

![image](https://github.com/bmaltais/kohya_ss/assets/160593453/d50e2455-bd58-4e60-932d-54bd7ca86d1b)

(venv) E:\kohya_ss\kohya_ss>pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118 xformers==0.0.23.post1+cu118 --index-url https://download.pytorch.org/whl/cu118
Looking in indexes: https://download.pytorch.org/whl/cu118
ERROR: Could not find a version that satisfies the requirement torch==2.1.2+cu118 (from versions: none)
ERROR: No matching distribution found for torch==2.1.2+cu118

(venv) E:\kohya_ss\kohya_ss>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

(venv) E:\kohya_ss\kohya_ss>python --version
Python 3.10.11

(venv) E:\kohya_ss\kohya_ss>pip show torch
WARNING: Package(s) not found: torch

(venv) E:\kohya_ss\kohya_ss>python -m pip install "torch-2.1.2+cu118-cp310-cp310-win_amd64.whl"
ERROR: torch-2.1.2+cu118-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

(venv) E:\kohya_ss\kohya_ss>python --version
Python 3.10.11

**Comment by ellyoun13** [comment]
Others cause the same problem
(problem with out-of-version)
So,,
I think I need to change the version of the requirements but I don't know which version will work well..
please help 


![image](https://github.com/bmaltais/kohya_ss/assets/160593453/f2994715-6efc-4f50-af50-f4be1db603b2)

**Comment by DarkViewAI** [comment]
Go into cmd and run pip cache purge, restart your pc, and try the setup again.
