### ISSUE TITLE
Dataset config creation / question

### ISSUE THREAD

**Issue by VelocityRa** [bmaltais/kohya_ss#2195]
Hello, is there a way to avoid having to set all "Dataset Preparation" options (like class prompt, file paths, etc) every time, when training multiple models/loras on the same dataset (to test different hyperparameters etc)?
Each test, I just want to modify hyperparams in my training json directly, load it in the UI, and start training.

I saw the recent `--dataset_config` feature that allows pointing to a `.toml` file with all these, but how to actually create one? Any docs?

Only example I see is [dataset.toml](https://github.com/bmaltais/kohya_ss/blob/master/test/config/dataset.toml). Are we supposed to write one like that? Can it be auto-generated from existing values selected instead? Every time we press "Prepare training data", for example.
Then it could just be specified in the training config json.

Thank you!

**Comment by bmaltais** [comment]
This should provide all the information you need ;-)

https://github.com/kohya-ss/sd-scripts/blob/dev/docs/config_README-en.md

**Comment by VelocityRa** [comment]
I see, thank you, and thanks for your work :)
