### ISSUE TITLE
--num_processes=1 is not passed

### ISSUE THREAD

**Issue by enznear** [bmaltais/kohya_ss#2196]
![image](https://github.com/bmaltais/kohya_ss/assets/20720041/e2e03f87-6a03-42f0-ade0-648f5a3ab0d5)
![image](https://github.com/bmaltais/kohya_ss/assets/20720041/83692a16-fb25-4373-9c3c-28a87ea39238)

I have multiple gpu machine and I want to only use 1 GPU, so I set Number of processes 1 on the web, but it keeps setting --num_processes to 10. Why can't I pass --num_processes 1 through webpage? Setting it to 2 works only 1 does not.

I'm working on Ubuntu 20.04...

**Comment by littleyeson** [comment]
Maybe can not use CUDA driver in Apple Silicon。

**Comment by bmaltais** [comment]
I can set it when it is equal to one. I will push an update to the dev branch later today to do that.

**Comment by bmaltais** [comment]
OK, the dev branch should now properly add the parameter for a value of 1

**Comment by enznear** [comment]
Thank you for swift reply. I'm using master branch and got hint from your answer and just modified here
![image](https://github.com/bmaltais/kohya_ss/assets/20720041/02a35661-acf9-4ac7-86ee-9025b139c1c5)

Would this dev update be reflected on master?

**Comment by bmaltais** [comment]
Once Koby’s update his master branch with his latest sd-scripts I will merge the dev branch to master as the dev branch is using Joshua’s latest code.

**Comment by enznear** [comment]
Great!
