### ISSUE TITLE
How to provide Config.json AND Dataset Preparation folders and configuration via CMD?

### ISSUE THREAD

**Issue by bjspi** [bmaltais/kohya_ss#2197]
Hi all,

I'm using Kohya on Runpod - and I do a lot of trainings to test different parameters like Epochs, Repeats etc.
I do the trainings in parallel, so I need multiple Runpods, which I close afterwards because of the server cost.

I want to simplify my Kohya Workflow and I am wondering, if it is possible to provide the 5 inputs for Dataset preparation (e.g. ohwx man + 3x Folder (Training pics, Reg pics, Training output)) as well as the Config.json directly via CMD when starting KOHYA?

I'd love to avoid having to enter the same inputs into the Training form everytime again (my folder structure is always the same!).

Any idea?
Thank you so much!

**Comment by bmaltais** [comment]
It is not supported at the moment. The closest you can do it to use the config.toml file to specify those folders as part of the config… I can add support for more of those in the future if useful

**Comment by bjspi** [comment]
Thanks for your reply - is it possible to fill the 5 fields within the "Dataset preparation" tab also via JSON config? If so, which dictionary keys to use? Thank you so much

**Comment by bmaltais** [comment]
Not at the moment but I should be able to add it easily enough.

**Comment by bmaltais** [comment]
OK... I think I have it working:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/4db1ea30-8e26-4503-ab30-0e6f61a8e156)

Will push it to the `dev` branch... simply uncomment the dataset_preparation section and set the values to the desired defaults.

**Comment by bmaltais** [comment]
OK, pushed, give it a try.

**Comment by bjspi** [comment]
Thank you so much - but this is only for the TOML Config, right? Or is it also accessible via JSON? Because as I wrote, I have everything configured JSON right now - I gotta see if I either convert it to TOML, or how I'll cope with it.

BTW: Passing a Config File (TOML or JSON) via CMD when starting KOHYA GUI is also not yet possible, right?

Thank you very much!

**Comment by bmaltais** [comment]
Correct. At the moment the toml file is always config.toml.

**Comment by bmaltais** [comment]
I pushed an update to the dev branch that will allow you to specify a `--config <file path>` option when starting the GUI. FOr example:

`.\gui.bat --config "./config example.toml"`

This will load the configuration from the example config file. You can point to any filename in any filepath.

**Comment by bmaltais** [comment]
I also started to expand the parameters you can set via the config.toml file... slowly making progress... The goal is that all values can be set using the config file

**Comment by bjspi** [comment]
Awesome to hear, thanks! 
Gotta switch to TOML soon :) (right now I have a Python script which modifies the config.json - hence I should rewrite it to support  TOML files as well). Because both your changes really simplify things again.

One more question: 
What do you think about supporting a "sequence of trainings" with some sort of scheduler? Actually Im looking for a way to change repeats, and basemodels and only start the process once - and let all the trainings run sequentially. Why would I wanna do it? Well, because I wanna let my PC / RunPod run on full speed without having to check the status and start the next training every few hours. That would be awesome

**Comment by bmaltais** [comment]
For the sequencing there is no plan to support that… you can use the print option to capture the training command and pot those in a script you can then run without the gui…

The toml is not re replacement for training json files. Rather, it is there to specify custom default values for the GUI elements… training g json are still needed to save the training configuration.

**Comment by bjspi** [comment]
I'm not talking about the training json files in the training output folder. 
I'm talking about my JSON config which defines all the Training parameters for the GUI!
The way I assumed it is: Either TOML or JSON can be used. I mean, obviously importing my config.json with predefined modelname, model checkpoint path, epoch, save_every etc works - so must be implemented as an alternative to TOML!?

**Comment by bmaltais** [comment]
TOML is a human friendly format an better suited for humans. I chose that for the GUI defaults for that reason. One could convert the json parameters to toml for use as an input but it is not really meant for that. But you could write a python script just to do that.

**Comment by dpons222** [comment]
> For the sequencing there is no plan to support that… you can use the print option to capture the training command and pot those in a script you can then run without the gui…
> 
hello! a beginner to all this. quick question to not take too much of your time.  after printing the training command, then what? I created a nat file, copy and pasted the training commands to it (3 different ones in this case), but I am not sure how to "activate" it? Can you explain, or point to a resource you may already have? Thank you! :)
