### ISSUE TITLE
A matching Triton is not available, some optimizations wilt not be enabled. Error caught was: No module named 'triton'

### ISSUE THREAD

**Issue by MIKETUFFIN66** [bmaltais/kohya_ss#2203]
A matching Triton is not available, some optimizations wilt not be enabled.
Error caught was: No module named 'triton'

the lora trainning keeps going ok just this part keeps pops up 

whats the fix ? 
thanks in advance .. 

![error](https://github.com/bmaltais/kohya_ss/assets/162156359/36a144c8-8b3f-4661-9487-aac6bee8be01)

**Comment by Niiickel** [comment]
Run setup.bat and select triton install

**Comment by bmaltais** [comment]
Or simply glance over those warnings. They are just warnings for Windows users... Triton is not implemented on Windows... there is a Windows compatible custom build out there but some users have reported more issues than benefits after installing it... so watchout.

**Comment by MIKETUFFIN66** [comment]
> Or simply glance over those warnings. They are just warnings for Windows users... Triton is not implemented on Windows... there is a Windows compatible custom build out there but some users have reported more issues than benefits after installing it... so watchout.

thanks i got the idea .. maybe better not to use it keep it this way
