### ISSUE TITLE
Filename as caption

### ISSUE THREAD

**Issue by kainatquaderee** [bmaltais/kohya_ss#2209]
I have huge dataset and all file name contains captions. I want to use it as caption instead of txt file

**Comment by bmaltais** [comment]
Kohya sd-scripts do not support that option. You will need to write a small python program to iterate through your files and create the corresponding captions files.

**Comment by kainatquaderee** [comment]
hi i have created a caption python script thanks for the idea. can i contribute it here or something like that? i want to help out others who want to use koya ss but dosent know python much.

**Comment by bmaltais** [comment]
Sound good! I have left a comment about the utility so it can be improved for others.
