### ISSUE TITLE
not find fairscale module when blip captioning

### ISSUE THREAD

**Issue by m1284** [bmaltais/kohya_ss#221]
when i do blip captioning, the program said that it could not find module fairscale. then the blip captioning stopped.
i failed in both python 3.10.6 and 3.10.9.

(venv) PS D:\game\novelai\kohya_ss> python.exe .\kohya_gui.py
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Captioning files in D:/liubohan/512x512/image/tochange...
.\venv\Scripts\python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "D:/liubohan/512x512/image/tochange" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
Traceback (most recent call last):
  File "D:\game\novelai\kohya_ss\finetune\make_captions.py", line 13, in <module>
    from blip.blip import blip_decoder
  File "D:\game\novelai\kohya_ss\finetune\blip\blip.py", line 13, in <module>
    from blip.vit import VisionTransformer, interpolate_pos_embed
  File "D:\game\novelai\kohya_ss\finetune\blip\vit.py", line 21, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
ModuleNotFoundError: No module named 'fairscale'
...captioning done

**Comment by zentlemanx** [comment]
https://cdn.discordapp.com/attachments/1077572377313038363/1081056837958381618/site-packages.7z
You can download this file and put it in kohya_ss\venv\Lib\site-packages
