### ISSUE TITLE
Textual Inversion's dlr0 diverges to inf

### ISSUE THREAD

**Issue by and1011** [bmaltais/kohya_ss#222]
I didn't test the algorithm before implementation of d-adaptation, but now, when I try to train a textual inversion, dlr0 starts low, which I suppose is correct anyway, but quickly starts increasing (exponentially) with each step until it reaches the float limit. 
Also, after the value diverges to inf the embedding becomes unusable.
If I understood correctly, what could be wrong, but in theory shouldn't the dlr converge to some value? 
Anyone else having this problem or who could help?

**Comment by bmaltais** [comment]
This is usually because the LR is too high... You could try to lower it a bit.

**Comment by and1011** [comment]
I saw here that you fixed it in this commit https://github.com/bmaltais/kohya_ss/commit/34ab8448fbb0ea44a47b1d7e5a5e4551d751f95f

Now that I've updated this bug has been fixed, I can now use AdamW normally.
Thank you.
