### ISSUE TITLE
How to Fully Update to 23.1.1 

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2225]
I think my sd-scripts module needs updating. This is clearly my lack of understanding of git. How do i clear this error? 

10:46:19-219095 INFO     Kohya_ss GUI version: v23.1.1
error: Your local changes to the following files would be overwritten by checkout:
        sdxl_train.py
        train_network.py
Please commit your changes or stash them before you switch branches.
Aborting
fatal: Unable to checkout 'bfb352bc433326a77aca3124248331eb60c49e8c' in submodule path 'sd-scripts'
10:46:19-739183 ERROR    Error during Git operation: Command '['git', 'submodule', 'update', '--init', '--recursive',
                         '--quiet']' returned non-zero exit status 1.
10:46:19-742186 INFO     nVidia toolkit detected
10:46:21-355670 INFO     Torch 2.1.2+cu118
10:46:21-369069 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
10:46:21-371069 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
10:46:21-376076 INFO     Python version is 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit
                         (AMD64)]
10:46:21-377588 INFO     Verifying modules installation status from requirements_pytorch_windows.txt...
10:46:21-379165 INFO     Verifying modules installation status from requirements_windows.txt...
10:46:21-381482 INFO     Verifying modules installation status from requirements.txt...
10:46:26-271501 INFO     headless: False
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by bmaltais** [comment]
Best way is to delete the venv folder and run setup.bat

**Comment by bmaltais** [comment]
For this error... you best bet might be to completely delete the kohya_gui folder and re-clone it using git... essentially starting from scratch:

https://github.com/bmaltais/kohya_ss?tab=readme-ov-file#setup-windows

**Comment by rafstahelin** [comment]
thanks will do
