### ISSUE TITLE
Trying to install Torch for CUDA on AMD hardware

### ISSUE THREAD

**Issue by morgan008** [bmaltais/kohya_ss#2228]
```
./gui.sh
Warning: LD_LIBRARY_PATH environment variable is not set.
Certain functionalities may not work correctly.
Please ensure that the required libraries are properly configured.

If you use WSL2 you may want to: export LD_LIBRARY_PATH=/usr/lib/wsl/lib/

INFO     Kohya_ss GUI version: v23.1.2
INFO     Submodule initialized and updated.
INFO     AMD toolkit detected
INFO     Torch 2.1.2+rocm5.6
INFO     Torch backend: AMD ROCm HIP 5.6.31061-8c743ae5d
INFO     Torch detected GPU: AMD Radeon RX 7800 XT VRAM 16368 Arch (11, 0) Cores 30
INFO     Python version is 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801]
INFO     Verifying modules installation status from .../kohya_ss/requirements_linux.txt...
WARNING  Package wrong version: torch 2.1.2+rocm5.6 required 2.1.2+cu118
INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 xformers==0.0.23.post1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
```
P.S. In general, should gui.sh intervene in the installation? For this, after all, there is setup.sh. And gui.sh should work on the principle of "take what's available", isn't it?

**Comment by bmaltais** [comment]
The project does not have support for AMD GPU... If someone come up with the proper requirements file to support it I can integrate support in the GUI based on it.

**Comment by morgan008** [comment]
@bmaltais then why detecting which toolkit are used? Never mind.

All we need is just
```torch==2.1.2+rocm5.6 torchvision==0.16.2+rocm5.6 --extra-index-url https://download.pytorch.org/whl/rocm5.6```

Or just remove these checks from gui.sh, because they duplicate setup.sh functionality and break the environment manually properly configured. And checking Python version too.

**Comment by bmaltais** [comment]
OK... I see there is a requirements_linux_rocm.txt file that specify some requirements... but I guess it does not work for your system? Would a new requirements file help with the installation for AMD cards that are not properly covered by the existing option?

I did not create those files as I don't own an AMD card and other contributors created PR to get them as part of the GUI...

If you can come up witht he required files to make the install work for you you might want to create a PR to submit the solution so others can benefit from it.

**Comment by Disty0** [comment]
Use `./setup.sh --use-rocm` then `./gui.sh --use-rocm`

https://github.com/bmaltais/kohya_ss/pull/2167

**Comment by morgan008** [comment]
@Disty0 First of all, it should have been added to the instructions. 
Secondly, it is inconvenient. Why not implement automatic detection? 
Thirdly, why did you specify Torch nightly builds and not the stable ones?

> gui.sh's entire purpose is setting up the environment and updating the environment.

Then why does setup.sh exist? The instructions clearly say that setup.sh is for setting up the environment, gui.sh is for running.

**Comment by Disty0** [comment]
> @Disty0 First of all, it should have been added to the instructions.  

I don't like writing documents in general, community PRs are welcome.

> Secondly, it is inconvenient. Why not implement automatic detection?  

This codebase implemented the requirements check in the setup.sh and gui.sh instead of python files and honestly, i didn't want to rewrite it to support autodetect.

> Thirdly, why did you specify Torch nightly builds and not the stable ones?  

MES Hangs and Memory Exceptions.  
Stable ones are not stable.  

> Then why does setup.sh exist? The instructions clearly say that setup.sh is for setting up the environment, gui.sh is for running.  

You can't run anything without activating the environment first.
