### ISSUE TITLE
A potential bug related to the WD14 Captioning GUI

### ISSUE THREAD

**Issue by howyoungchen** [bmaltais/kohya_ss#2230]
I have found a potential bug related to the WD14 Captioning GUI.

When the "Prefix to add to WD14 caption" option is set to a single word, it appears that the output command is missing the closing double quote.
![51b6a5d0fa88ec42459ac36c3b6b7fc](https://github.com/bmaltais/kohya_ss/assets/57206159/a40d91f1-fe1a-4018-8469-35fa78d989ea)
![6bfebef4c73b722a57c65d9b2972564](https://github.com/bmaltais/kohya_ss/assets/57206159/51e225ee-c33b-4b68-ba91-37a0d8af7136)

This will lead to "/bin/sh: 1: Syntax error: Unterminated quoted string".

**Comment by bmaltais** [comment]
Let me try to reproduced this issue...

**Comment by bmaltais** [comment]
OK, I have fixed the issue. Merged to master but won't create a release for it. Just `git pull` to get the updated code.
