### ISSUE TITLE
Dataset Preparation Copy Folder Info Button is Gone

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2237]
This is a huge issue. People can't use it anymore :/

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/db90bbdf-6f71-48ad-91b3-da384ccc896e)

**Comment by FurkanGozukara** [comment]
@bmaltais can you fix this issue urgently? thank you

**Comment by chinmoybasak** [comment]
This is surly causing problem..

**Comment by bmaltais** [comment]
THe new way the interface work it is very difficult to update the other fields like it used to... so I ditched it for now until I can figure out a solution... So until then you will have to manually fill in the fields.

**Comment by bmaltais** [comment]
Good news! I was able to quickly fix the feature. Only required a minor code change to how I was doing it before!
