### ISSUE TITLE
WD14 - Prefix to add to WD14 caption No longer working

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2243]
seems with the new update, its not longer working.

**Comment by bmaltais** [comment]
The new code leverage the built in prefix support but perhaps the implementation is not working right? I will test it and see if it work.

**Comment by bmaltais** [comment]
Indeed... the built-in prefix solution of the wd14 tagger does not appear to work... I will re-implement my original method and rely on that instead :-) I have pushed a fix to the dev branch

**Comment by DarkViewAI** [comment]
Much appreciated thank you for your hard work @bmaltais
