### ISSUE TITLE
Nan detected in latents : .../img.jpg

### ISSUE THREAD

**Issue by BenDes21** [bmaltais/kohya_ss#2244]
Hi there, trying to train my sdxl checkpoint with dreambooth SDXL. 

Getting this error 
<img width="1196" alt="Untitled" src="https://github.com/bmaltais/kohya_ss/assets/153294763/eb7a9289-923f-4844-9568-fa7868a28015">

This image is not corrupted, [from this page I find this ](https://github.com/bmaltais/kohya_ss/discussions/1947) : 

_Incorporating the torch.backends.cudnn.benchmark = True setting into the training script resolved the "NaN detected in latents" error on an NVIDIA GTX 1660 6GB card, facilitating successful training of LoRA models. This workaround might be helpful for others experiencing similar issues, and a permanent fix or documentation update could further improve user experience._

but after added the line, I get the same issue.

<img width="1032" alt="Untitled" src="https://github.com/bmaltais/kohya_ss/assets/153294763/fc4683f4-1912-4272-bf94-167b7a07cb2c">

Thanks a lot

**Comment by jjiikkkk** [comment]
i seem to come across the same errors

**Comment by jjiikkkk** [comment]
@BenDes21 have you solved this problem or error caused by the repo itself?

**Comment by BenDes21** [comment]
> @BenDes21 have you solved this problem or error caused by the repo itself?

No unfortunately T_T still trying to fix, let me know if you find a solution from your side

**Comment by bmaltais** [comment]
There is something the PIL library does not like with that file... What happen it you take it out?

**Comment by BenDes21** [comment]
> There is something the PIL library does not like with that file... What happen it you take it out?

I feel this error has been fixed by set into additional parameters " --no_half_vae " but now Im getting this new error : 

<img width="1041" alt="321147423-eb7a9289-923f-4844-9568-fa7868a28015" src="https://github.com/bmaltais/kohya_ss/assets/153294763/0ea3872d-3892-40e3-bafe-43f3586716a5">

**Comment by bmaltais** [comment]
Look like a write permission issue in docker containers. I can’t help with that.

**Comment by BenDes21** [comment]
> Look like a write permission issue in docker containers. I can’t help with that.

<img width="963" alt="321147423-eb7a9289-923f-4844-9568-fa7868a28015" src="https://github.com/bmaltais/kohya_ss/assets/153294763/77e3bb5c-c710-4459-866c-9a0b25912bd4">

issue has been fixed by unchecked cache latent to disk
