### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '\\meta_cap.json' while finetuning locally. lora works.

### ISSUE THREAD

**Issue by Tomtingelfield** [bmaltais/kohya_ss#2246]
Hi there,
I’m not able to start finetuning in kohya locally. On Runpod it works as well as my local lora training. Don’t know much about this technical stuff but as I understand it, meta_ cap.json can’t be written because it supposedly lacks authorization to write on my local drive. I'm logged in with administrator rights. Training a lora locally works well, without any permissons. 
 
![permission error](https://github.com/bmaltais/kohya_ss/assets/130799727/92d6f403-0d5c-4390-90ae-b048acd86338)

**Comment by bmaltais** [comment]
Humm, it is always better to run the GUI as a regular user. The Kohya_ss GUI does not require admin rights to run. If you installed it as an admin try deleting the kohya_ss gui and reinstalling as a regular user. Hope this will help.

**Comment by Tomtingelfield** [comment]
It din't help, unfortunatelly. I also reinstalled the Pre-requirements from my standard user account, when possible (python) without admin privileges...

**Comment by bmaltais** [comment]
I will try to train a new finetune today to try to reproduce the issue.

**Comment by bmaltais** [comment]
Everything is working fine o my side. There is a finetuning test file part of the repo that you can load to test that everything work fine. It work just fine on my system so it should also work for you: `/test/config/finetune-AdamW.json`

Open this config file in the GUI and try training with it. If it work then study the parameters and perhaps it will help find out what might be wrong with your config.

**Comment by Tomtingelfield** [comment]
ok, I will try it. Thanks for your reply!

**Comment by Tomtingelfield** [comment]
I found my mistake. I’m stupid, I’d forgotton to tell the gui where the Train config directory is! As it’s labeled optional i didn’t take it serious all the time. Thought something like If I don’t write some-thing here, kohya would shurely be using the default option… Thank you again! My problem is solved. But however, local sdxl finetuning doesn’t seem to be a good option for me, even with a 4090 it is unbelivable slow! 2:45 for just 4 Steps…

**Comment by bmaltais** [comment]
This is abnormally slow. You might be using parameters that exceed the 24GB of VRAM and cause swapping to ram… hence slow steps. SDXL take a lot of VRAM and 24 GB is not really enough to effectively train SDXL finetune

**Comment by Tomtingelfield** [comment]
yes, that's what I thought too. All I can do is wait and see if there is a model version with sd3 that works better with 24gb...
