### ISSUE TITLE
Vulnerability report contact person or email

### ISSUE THREAD

**Issue by sylwia-budzynska** [bmaltais/kohya_ss#2248]
Hello,

A month ago (on Feb 29) I sent a vulnerability report to the maintainer's email, but I haven't heard back. Please let me know if you'd like me to send the report to another email address or in another way, e.g. via private vulnerability reporting feature (see [docs](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository) on how to enable private vulnerability reporting). Thank you!

**Comment by bmaltais** [comment]
Please open PR to help fix the discovered issues. I will gladly take PR to improve the security issues.

**Comment by sylwia-budzynska** [comment]
Thank you, I finished adding the reports. You should be able to see them under: https://github.com/bmaltais/kohya_ss/security/advisories
