### ISSUE TITLE
How to disable share on Kaggle - it is bugged

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2252]
Unless I manually modify the source code as below it is always sharing on Kaggle

how can I prevent it? can you add an argument?

`interface.launch(**launch_kwargs, share=False)
`

**Comment by bmaltais** [comment]
By default it is not shared... I suspect whoever created the Kaggle solution must have turned sharing by default... I am not sure what the Kaggle solution is so it is hard to troubleshoot... but my repo does not share by default...

**Comment by FurkanGozukara** [comment]
> By default it is not shared... I suspect whoever created the Kaggle solution must have turned sharing by default... I am not sure what the Kaggle solution is so it is hard to troubleshoot... but my repo does not share by default...

@bmaltais 

I am the coder of the notebook

I am starting like this on kaggle and it auto activates gradio share

`!bash gui.sh --headless`

here screenshot sorry for the late reply kaggle starting took huge time

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/95f9955c-3e04-48bd-9777-296aeb1c690c)

**Comment by bmaltais** [comment]
This is strange... is Kaggle setting sharing to true on it's own?   It certainly look like it... this is not coming from my code... I do allow --share to be specified... but I never set things to share ...

**Comment by bmaltais** [comment]
Or maybe this is a Gradio feature when it detect Kaggle?

**Comment by FurkanGozukara** [comment]
> interface.launch(**launch_kwargs, share=False)

it could be

when i make like this it doesnt auto share

interface.launch(**launch_kwargs, share=False) 

perhaps you can add argument to make this happen?

**Comment by bmaltais** [comment]
I have pushed an update to the `dev` branch. You can specify --do_not_share and it will enforce share-False even if --share is specified...

`./gui.sh --do_not_share`

**Comment by FurkanGozukara** [comment]
> I have pushed an update to the `dev` branch. You can specify --do_not_share and it will enforce share=False even if --share is specified...
> 
> `./gui.sh --do_not_share`
> 
> Darn Kaggle auto sharing...

tried like this but still didnt work. i am gonna remove headless and try again now

![image](https://github.com/bmaltais/kohya_ss/assets/19240467/0df73b9c-243a-4ac1-95d6-3c315f2dd2e4)

**Comment by bmaltais** [comment]
Found the issue... SHould work now ;-)

**Comment by FurkanGozukara** [comment]
> Found the issue... Should work now ;-) `git pull`.

this one worked nice thank you
