### ISSUE TITLE
Log tracker config: how to

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2262]
I am trying to send my parameter config to wandb. 

I've added a diretory for Log tracker config, but I now get this error message which mentions a toml:
`running training / 学習開始
  num examples / サンプル数: 5
  num batches per epoch / 1epochのバッチ数: 5
  num epochs / epoch数: 2
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 10
steps:   0%|                                                                                       | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\kohya_ss\sd-scripts\sdxl_train.py", line 818, in <module>
    train(args)
  File "E:\kohya_ss\sd-scripts\sdxl_train.py", line 489, in train
    init_kwargs = toml.load(args.log_tracker_config)
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 133, in load
    with io.open(_getpath(f), encoding='utf-8') as ffile:
PermissionError: [Errno 13] Permission denied: 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\3training\\1_local_training_gr4ph1cw\\tracker'
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)`

What is this error?

Do i need to create a toml file in "Dataset config file"

I am Kohya 23.1.3, Windows
I am able to run training without the tracker config setting

**Comment by bmaltais** [comment]
I don’t use this feature. You will need to ask the question directly on the sd-scripts repo of kohya as he is the one supporting the scripts I wrap in a GUI.

**Comment by bmaltais** [comment]
Not sure why it is reporting a file permission denied on your system…

**Comment by rafstahelin** [comment]
Ok thanks @bmaltais

**Comment by rafstahelin** [comment]
> Not sure why it is reporting a file permission denied on your system…

I am not sure either. I am suspecting i need to use the toml as a security measure to avoid exposing the config data.

I've asked in sd-scripts

**Comment by bmaltais** [comment]
Oh… I remember reading something about that… Unfortunatly the GUI does not support as-scripts toml config files and I don’t k ow how this might be integrated…

**Comment by rafstahelin** [comment]
> Oh… I remember reading something about that… Unfortunatly the GUI does not support as-scripts toml config files and I don’t k ow how this might be integrated…

But do I understand correctly that the "log tracker config" works to send parameters to wandb? It has been used and tested? 

I'm just having access issue from the error message. 

So does that mean the optional config toml in the top of the Finetune module of the gui is not necessary?

**Comment by bmaltais** [comment]
Who’s I knew. I don’t use Wanda… I just provide the field in the gui to point to the config file… but what to put in and and how it work I have no idea :-)

**Comment by rafstahelin** [comment]
> Wish I knew. I don’t use wandb … I just provide the field in the gui to point to the config file… but what to put in and and how it work I have no idea :-)
> 
> 
> 
> The optional toml is just for dataset config… not for other config unfortunately… I think… I never tried to specify other parameters… so not 100% sure.

ok gotcha. no problem thx
