### ISSUE TITLE
Update the execution method of subprocess.Popen under windows .

### ISSUE THREAD

**Issue by ixdog** [bmaltais/kohya_ss#2265]
Hello, I am trying to install kohya_ss to my USB flash drive so that it can run on any WIN system. During the production process, I found that subprocess.Popen in tensorboard_gui.py cannot friendlyly change the default generation in python\Scripts. The built-in dependency path of exe. The default execution of programs in this directory will depend on the old Python installation path.

old code : 
    run_cmd = [
        #TENSORBOARD,
        "--logdir",
        logging_dir,
        "--host",
        "0.0.0.0",
        "--port",
        str(tensorboard_port),
    ]

Get error msg :  Fatal error in launcher: Unable to create process using xxxxxxx  👎 

my fix code:
    run_cmd = [
        sys.executable,
        "-m", 
        "tensorboard.main",
        #TENSORBOARD,
        "--logdir",
        logging_dir,
        "--host",
        "0.0.0.0",
        "--port",
        str(tensorboard_port),
    ]

When I use the fix code it works . 👍 
Could you please update all packages to run in subprocess.Popen([sys.executable, "-m", "module"]) mode?

**Comment by bmaltais** [comment]
I will check but I am not sure I understand the security implications of this change… especially since I had to rewrite how I run commands to fix a security vulnerability that was reported… so not really sure I want to do that…

**Comment by bmaltais** [comment]
Looking at the code it does appear to potentially make things safer actually... I will implement it for tensorboard and see how it goes...

When you say: Could you please update all packages to run in subprocess.Popen([sys.executable, "-m", "module"]) mode?

Do you mean all the call to "accelerate launch <parameters> "{scriptdir}/sd-scripts/train_db.py" <parameters> ?

How would this work? Like sys.executable, "-m", "accelerate.main", "the rest"?

**Comment by bmaltais** [comment]
Would this not also work:

```
    run_cmd = [
        # sys.executable,  # Refers to the Python executable itself
        # "-m",
        # "tensorboard.main",  # Runs Tensorboard as a module, not as a separate executable
        "tensorboard",
        "--logdir",
        logging_dir,
        "--host",
        "0.0.0.0",
        "--port",
        str(tensorboard_port),
    ]
```

I don't like the isea to depend on the module.main call... Like accelerate does not use a .main... so this does not appear to be applicable to everything...

**Comment by bmaltais** [comment]
`dev` branch should work.
