### ISSUE TITLE
22.1.5?

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#2267]
How did the releases go from 23.x.x to 22.1.5?

**Comment by ashleykleynhans** [comment]
Looks like the [.release](https://github.com/bmaltais/kohya_ss/blob/master/.release) file is correct, just a typo in the Github release.  I suggest deleting it and recreating it with the correct version number.

**Comment by bmaltais** [comment]
Thank you for pointing this out... Fixed ;-)
