### ISSUE TITLE
Where are the models Kohya downloads stored?

### ISSUE THREAD

**Issue by amarillosebas** [bmaltais/kohya_ss#2272]
Found this question already asked [here](https://github.com/bmaltais/kohya_ss/issues/253), but the answer as of now, April 2024 is not correct. I tried Blip2 captioning and saw around 15GB of models being downloaded. Since I just wanted to try that method, now I'd like to delete the models so that I can gain the 15 gigs back. I've used WinDirStat to try to locate those files, but I cannot find them.

**Comment by bmaltais** [comment]
In windows look in your home folder in a sub folder called .cache

Look in the hub folder:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/6f9c5eb3-0d06-4de0-accc-6c64b33a5ebb)

**Comment by amarillosebas** [comment]
Thank you! I may have missunderstood the response of the quoted post.
