### ISSUE TITLE
Gradio 4.19.2 does not work on RunPod

### ISSUE THREAD

**Issue by ashleykleynhans** [bmaltais/kohya_ss#2274]
Gradio 4.19.2 that was introduced in Kohya_ss v23.1.5 is not working on RunPod.
It just hangs on "Loading..." as shown in the screenshot.
<img width="722" alt="Screenshot 2024-04-13 at 10 13 26" src="https://github.com/bmaltais/kohya_ss/assets/886709/c668011b-1fe6-44cc-a8d1-7dc59f4c77f5">
It works fine if you upgrade gradio to the latest version 4.26.0.

**Comment by bmaltais** [comment]
Thanks. v4.26.0 now in `dev` branch
