### ISSUE TITLE
Log tracker config (wandb): "PermissionError: [Errno 13] Permission denied:"

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2276]
Finetune training with log tracker config assigned folder. Getting this error:

PermissionError: [Errno 13] Permission denied: 'E:\\studio Dropbox\\studio\\ai\\data\\styles\\style_lighting_graphicwhite\\3training\\1_local_training_gr4ph1cw\\tracker'

Everything else seems working. 

What could be wrong...? Here's my json

[local-fullfinetune-adamW8bit-v6-bf16.json](https://github.com/bmaltais/kohya_ss/files/14965796/local-fullfinetune-adamW8bit-v6-bf16.json)

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/991fa1b1-dfc8-4664-babc-40ad2b840a78)
(i've xxx'ed the api)

I presume this folder stores the parameters to be sent to WandB parameter columns.

**Comment by bmaltais** [comment]
This is now fixed in the `dev` branch. The GUI no longer pass arguments on the CLI and is no longer exposing them.
