### ISSUE TITLE
Lora size issue

### ISSUE THREAD

**Issue by specblades** [bmaltais/kohya_ss#228]
I've completed three trainings and am getting strange results.
Why are the file sizes different if I have hardly changed the settings? (only the batch size and noise offset)
![image](https://user-images.githubusercontent.com/113993746/221084491-8838a91e-6cf9-4c4a-bde9-ba03dc1a9987.png)

First Lora works well, but the others do nothing

**Comment by bmaltais** [comment]
Make sure to set the lora rank and alphja to 128 if you want to create 144.1 MB LoRA... the default is 8 for both on new projects.

**Comment by specblades** [comment]
> Make sure to set the lora rank and alphja to 128 if you want to create 144.1 MB LoRA... the default is 8 for both on new projects.

Acknowledged.
I figured it out. Sometimes when saving the config the network_dim line is reset to 8
