### ISSUE TITLE
Train problems 

### ISSUE THREAD

**Issue by Leshiy1** [bmaltais/kohya_ss#2280]
Hello, i was wanted train one model but it seems problem appears, first is new UI 
![изображение_2024-04-13_205908009](https://github.com/bmaltais/kohya_ss/assets/95132538/20a52af4-2862-4889-b135-13b3e10a309f)
The it's not complicated but still i prefere the old one. 
Second is the final output model it's not working at all i mean when i finish training i put Lora file in sd lora folder but problem appears when i start generate the image is brown mess. I use the same picture collection to train a model from my first i just add couple of new images use the same algorithm that work always but final generation result is just brown mess or it shows objects but image always brown original source images is not like that they has black or white background. 
![00001-3538732887](https://github.com/bmaltais/kohya_ss/assets/95132538/673c1d56-1ac1-46a4-83ad-12d4d55dd6a2)

My settings mostly i nothing change exept text encoder i put 5e-5 replace the numbers, rank dimenstion with alpha to 128 and Lr scheduler to constant 
![изображение_2024-04-13_210752958](https://github.com/bmaltais/kohya_ss/assets/95132538/d4108be0-3acf-4917-82b8-ba2f8650d6ca)
![изображение_2024-04-13_210829455](https://github.com/bmaltais/kohya_ss/assets/95132538/e438d383-3fa4-4aa2-ab4b-3eec87c86929)

I see other people has some problems after last updates and sdxl epansion supports. I just used good, old one SD 1.5 training method and this bad occasion appears. Wasn't sure how to fix that, all images has same standard resolution 512. Before i update the kohya_ss all works as it should guess last updates something broke. 
All warnings that i have when start training 
![изображение_2024-04-13_211957916](https://github.com/bmaltais/kohya_ss/assets/95132538/741c4ef5-84d3-4b5c-9792-f4ec2b32efb4)

**Comment by bmaltais** [comment]
The GUI has been significantly reworked. It will not please everyone but I think it reorganise things a little bit better... but might take some getting used to.

For the training I think it might be the result of some inderpinning module version updates. It might require changing the values of what used to work to something else to get things to work again... but I am not sure... there is always the off chance the gui is doing something different and causing the change in parameter... let me know if you can point to one such issue created by the updated GUI so I can fix it.
