### ISSUE TITLE
Why force LR warmup to be 0 with LR scheduler "constant"?

### ISSUE THREAD

**Issue by bjspi** [bmaltais/kohya_ss#2291]
Hi there,

I just noticed in the newest Dev branch that whenever one changes the LR scheduler to e.g. "constant", that Kohya not does an assert on the "LR warmup rate" parameter instead of simply ignoring it? So this config breaks because of the assert: 

![image](https://github.com/bmaltais/kohya_ss/assets/43368639/c68fc090-f0a4-4cfc-a65a-d907dce40e66)

```
Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 818, in <module>
    train(args)
  File "/workspace/kohya_ss/sd-scripts/sdxl_train.py", line 385, in train
    lr_scheduler = train_util.get_scheduler_fix(args, optimizer, accelerator.num_processes)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4163, in get_scheduler_fix
    return wrap_check_needless_num_warmup_steps(schedule_func(optimizer, **lr_scheduler_kwargs))
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4134, in wrap_check_needless_num_warmup_steps
    raise ValueError(f"{name} does not require `num_warmup_steps`. Set None or 0.")
ValueError: SchedulerType.CONSTANT does not require `num_warmup_steps`. Set None or 0.
```

My question is: Why? Is there any benefit?
A lot of users will not understand and/or read this message if they use "wrong" configs. 

Doesnt it make more sense to either show and/or validate it in the GUI (probably hard to do because you'd need to "connect" both input fields somehow) OR simply ignore the "LR warmup" when not required?

I don't think forcing a specific setting (warmup=0 in this case) has any benefit tbh and will simply confuse people. It doesnt do any harm when they set this variable - it's simply irrelevant with LR scheduler = constant.

Thanks for your consideration

**Comment by bmaltais** [comment]
This is a bug in the sd-scripts that the original GUI was hiding... In the latest GUI release I am passign the arguments specificd by the user as they are... and if they leave LR Scheduler to 10 with a Constant Scheduler it expose the incompatible settings to sd-scripts... and unfortunatly kohya's sd-script is tripping on this...

I can implement a change in the GUI that will set the LR warmup to 0 if constant is selected?

Try the new `dev`  branch code... should be providing proper feedback and fix to users.
