### ISSUE TITLE
Lora instead of being 16mb and above its only 1.26mb ..

### ISSUE THREAD

**Issue by MIKETUFFIN66** [bmaltais/kohya_ss#2293]
Hello, 

After the new update , every time i train a lora ... its only 1 mb !! 
IS THERE IS ANY ONE EXPERIANCE THE SAME THING !!

Thanks

**Comment by bmaltais** [comment]
Which version are you using? The one in the `master` branch or the `dev` branch?

Try the latest `dev` branch version as it has revceived many updates and might fix the issue... If it does not then the question will be why it is doing this... but 1st let's make sure the problem exist in dev.

**Comment by MIKETUFFIN66** [comment]
> Which version are you using? The one in the `master` branch or the `dev` branch?
> 
> Try the latest `dev` branch version as it has revceived many updates and might fix the issue... If it does not then the question will be why it is doing this... but 1st let's make sure the problem exist in dev.

thank you for your kind replay .. i will try & update about this issue ..

**Comment by MIKETUFFIN66** [comment]
yeah i checked its Kohya_ss GUI version: v23.1.5 ..

**Comment by MIKETUFFIN66** [comment]
> > Which version are you using? The one in the `master` branch or the `dev` branch?
> > Try the latest `dev` branch version as it has revceived many updates and might fix the issue... If it does not then the question will be why it is doing this... but 1st let's make sure the problem exist in dev.
> 
> thank you for your kind replay .. i will try & update about this issue ..

i deleted and reinstalled the default ver. now its working .. i think every update i was not suppose to use GIT PULL to update .. because it breaks the training .. every update we have to delete and reinstall a fresh installation ..based on my obeservation  thanks
