### ISSUE TITLE
Resume Training from the last saved checkpoints .safetensors

### ISSUE THREAD

**Issue by AdnaneAbou** [bmaltais/kohya_ss#2294]
I am wondering if there is a way of resuming the training after stopping the training ( session time , others ..) from the last saved checkpoints ! or it is one shot  ?
Thanks

**Comment by bmaltais** [comment]
You can if you select:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/ace8cfe1-421d-41d9-9c85-3fb461b6376f)
