### ISSUE TITLE
No option to provide a specific VAE checkpoint

### ISSUE THREAD

**Issue by CodeHatchling** [bmaltais/kohya_ss#2298]
I am trying to train an LoRA from a SDXL-based checkpoint, which comes with its own VAE.

- In the training GUI, there appears to be no option to provide this VAE as an argument.
- No list of command line arguments can be found online. Therefore, I cannot provide a custom VAE through the "Additional parameters" field, as it is not possible to determine what argument to enter.

Despite using recommended settings provided by others who have successfully trained SDXL LoRAs, and having a reasonable number of training images to work from, the resulting images look like JPEG glitch barf. I am therefore led to conclude that the cause is due to a lack of means to specify the VAE checkpoint.

Thanks for your help!

**Comment by bmaltais** [comment]
You can specify the VAE to use in this field:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/ddda6ab6-0842-4fec-b4f5-c59b49f5225c)
