### ISSUE TITLE
Can't switch language in Linux server

### ISSUE THREAD

**Issue by Diuyilu** [bmaltais/kohya_ss#2299]
I successfully deployed Kohya_ss into my remote  Linux server.
My system version is:Ubuntu 20.04.

I use this command to start GUI:`sudo ./gui.sh --listen 0.0.0.0 --server_port 7861 --language chinese`
But when I access the GUI page,I found that switching the language did not take effect.

I use DevTools(F12) to to search for the problem.
I found that both `script.js` and `localization.js` reported an error of 403, which means that the file is not allowed.

How can I solve this problem?

**Comment by bmaltais** [comment]
Gradio was upgraded to v4 and it might have broken how the localization was done... I did not implement the localization. I tried to poke at it but could not make it work... Maybe the original author @yxJoy can fix it?

**Comment by bmaltais** [comment]
I found the issue... I have pushed the fix to the `dev` branch
