### ISSUE TITLE
public 

### ISSUE THREAD

**Issue by fangbo6699** [bmaltais/kohya_ss#230]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
###############################################################
i want to Running on local URL:  http://0.0.0.0:7860，How to set it up

**Comment by bmaltais** [comment]
I have never tried this... but I could see if I could support the share=True option to make it shared? Will add it to the todo...

**Comment by bmaltais** [comment]
I have added the share option... it does not do quite what you want. I don't think there is actually to expose gradio to 0.0.0.0. If you can find some documentation on how to do that let me know. The --share option will be supported in the next release.

**Comment by neuralnermal** [comment]
> I have added the share option... it does not do quite what you want. I don't think there is actually to expose gradio to 0.0.0.0. If you can find some documentation on how to do that let me know. The --share option will be supported in the next release.

is sharing still not possible?

**Comment by OwenTruong** [comment]
`--share` just creates a public gradio url which is not ideal for privacy and also distributed training

**Comment by bmaltais** [comment]
How else should it be done? If you know of a better implementation using Gradio build in networking I could certainly accept either a PR if code sample showing an alternative.
