### ISSUE TITLE
Merge LoRA utility fails if the paths have a space

### ISSUE THREAD

**Issue by SecuoyaXR** [bmaltais/kohya_ss#231]
Merge LoRA utility fails if the paths have a space

It throws an unrecognized argument error. The paths aren't automatically put in quotes

**Comment by bmaltais** [comment]
Thanks for reporting... let me fix that.

**Comment by bmaltais** [comment]
Fixed with: https://github.com/bmaltais/kohya_ss/commit/3b93266aaec95315aa5bde24af3e154b5e33db2c
