### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by lawliet198t** [bmaltais/kohya_ss#2310]
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/bin/python: can't open file '/workspace/all_data/sd-scripts/sdxl_train_network.py': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/workspace/all_data/sd-scripts/sdxl_train_network.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--full_bf16', '--gradient_checkpointing', '--huber_c=0.1', '--huber_schedule=snr', '--learning_rate=0.0003', '--logging_dir=/workspace/all_data/logs', '--loss_type=l2', '--lr_scheduler=constant', '--lr_scheduler_num_cycles=5', '--max_data_loader_n_workers=0', '--max_grad_norm=1', '--resolution=1024,1024', '--max_train_steps=14500', '--min_timestep=0', '--mixed_precision=bf16', '--network_alpha=1', '--network_dim=384', '--network_dropout=0.2', '--network_module=networks.lora', '--no_half_vae', '--optimizer_type=AdamW', '--output_dir=/workspace/all_data/outputs', '--output_name=mariana last', '--pretrained_model_name_or_path=/workspace/all_data/models/sd_xl_base_1.0.safetensors', '--reg_data_dir=/workspace/all_data/regulization', '--save_every_n_epochs=5', '--save_model_as=safetensors', '--save_precision=bf16', '--text_encoder_lr=0.0003', '--train_batch_size=1', '--train_data_dir=/workspace/all_data/images', '--unet_lr=0.0003', '--xformers']' returned non-zero exit status 2.

**Comment by bmaltais** [comment]
Can you do a git pull to upgrade to the latest version of the code? You appear to use an older version.

**Comment by lawliet198t** [comment]
ok i am trying

**Comment by lawliet198t** [comment]
welp i am running it on runpod it sometimes just work magically or never works .

**Comment by lawliet198t** [comment]
lol it worked
