### ISSUE TITLE
Error trying to train a LORA

### ISSUE THREAD

**Issue by AlexLuqueGarcia** [bmaltais/kohya_ss#2312]
I'm new to Kohya and i Was trying to train a LORA, but i'm finding the following issue, I've tried doing a fresh install but still getting the error:

16:25:31-889966 INFO     Executing command: "D:\kohyaTraining\kohya_ss\venv\Scripts\accelerate.EXE" launch
                         --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 18
                         --num_machines 1 --num_cpu_threads_per_process 2
                         "D:/kohyaTraining/kohya_ss/sd-scripts/train_db.py" --config_file "./outputs/tmpfiledbooth.toml"
                         with shell=True
16:25:31-895965 INFO     Command executed.
2024-04-17 16:25:40 WARNING  A matching Triton is not available, some optimizations will not be enabled.  __init__.py:55
                             Error caught was: No module named 'triton'
                    INFO     Loading settings from ./outputs/tmpfiledbooth.toml...                    train_util.py:3744
Traceback (most recent call last):
  File "D:\kohyaTraining\kohya_ss\sd-scripts\train_db.py", line 527, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "D:\kohyaTraining\kohya_ss\sd-scripts\library\train_util.py", line 3746, in read_config_from_file
    config_dict = toml.load(f)
  File "D:\kohyaTraining\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\luis\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 830: invalid continuation byte**
Traceback (most recent call last):
  File "C:\Users\luis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\luis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohyaTraining\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohyaTraining\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\kohyaTraining\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\kohyaTraining\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohyaTraining\\kohya_ss\\venv\\Scripts\\python.exe', 'D:/kohyaTraining/kohya_ss/sd-scripts/train_db.py', '--config_file', './outputs/tmpfiledbooth.toml']' returned non-zero exit status 1.
16:25:42-091211 INFO     Training has ended.

**Comment by AlexLuqueGarcia** [comment]
Also tried to install kohya on another computer and I'm getting the same error :S

**Comment by bmaltais** [comment]
I wonder if perhaps the config file is not encoded in a format sd-scripts is expecting it? Do you use english on your computer? Maybe different language use different encoding and sd-scripts can't deal with it? Can you share the ./outputs/tmpfiledbooth.toml file?

**Comment by AlexLuqueGarcia** [comment]
> I wonder if perhaps the config file is not encoded in a format sd-scripts is expecting it? Do you use english on your computer? Maybe different language use different encoding and sd-scripts can't deal with it? Can you share the ./outputs/tmpfiledbooth.toml file?

sorry for the ignorance, but where can I find that file? I'm using Spanish on my computer

**Comment by AlexLuqueGarcia** [comment]
Here it is:

bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_dropout_every_n_epochs = 0
caption_dropout_rate = 0
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 2
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
keep_tokens = 0
learning_rate = 4e-7
learning_rate_te = 1e-5
logging_dir = "C:/Users/luis/Dropbox/TOKYO_LEGLESS/TRAILER 01/AI/inputImages/TokyoLeglessLora\\log"
loss_type = "l2"
lr_scheduler = "constant_with_warmup"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 462
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_token_length = 75
max_train_epochs = 1600
max_train_steps = 4620
mem_eff_attn = true
metadata_author = "Alex Luque García"
metadata_title = "Tokyo Legless V1"
min_bucket_reso = 256
mixed_precision = "bf16"
multires_noise_discount = 0
noise_offset_type = "Original"
optimizer_type = "AdamW"
output_dir = "C:/Users/luis/Dropbox/TOKYO_LEGLESS/TRAILER 01/AI/inputImages/TokyoLeglessLora\\model"
output_name = "last"
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = "C:/Users/luis/Dropbox/TOKYO_LEGLESS/TRAILER 01/AI/inputImages/TokyoLeglessLora\\model\\prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
train_batch_size = 2
train_data_dir = "C:/Users/luis/Dropbox/TOKYO_LEGLESS/TRAILER 01/AI/inputImages/TokyoLeglessLora\\img"
xformers = true

**Comment by AlexLuqueGarcia** [comment]
fuck, that was it hahaha, thx
