### ISSUE TITLE
Unable to set the Polynomial LR Power < 1.0

### ISSUE THREAD

**Issue by b-fission** [bmaltais/kohya_ss#2321]
A recent commit changed the LR Power setting to have a minimum value of 1.0, which prevents me from being able to save or start training for my existing configs which might use 0.6 for example.

I believe it would make sense to use a minimum of 0.0 instead.

https://github.com/bmaltais/kohya_ss/blob/05cf164279d7f8675cd498373e64c0148057472f/kohya_gui/class_basic_training.py#L324-L328

**Comment by bmaltais** [comment]
I will. Hange the minimum to 0. I made a global fix to align the input types and minimum values and must have changed it to the wrong value in the process…
