### ISSUE TITLE
For 24.0.3, the results from the print command cannot be used directly in sd-scripts

### ISSUE THREAD

**Issue by neoraoz** [bmaltais/kohya_ss#2328]
The results from 'Printing training command' had being used in sd-scripts for batch processs (ie. add many results to a single bat file) without any ammendment.
For 24.0.3, print comamnd is showing toml config file, but cannot be used directly.  I need to edit to add -- for every option, for instance, adding "--" on 'max_bucket_reso=2048' to make '--max_bucket_reso=2048' for single line command for sd-scripts

Plz. revert to previous  print command or add option to print command.
Altenatively, if there is a method to use toml config in sd-scripts, please let me know.

Many thanks in advance.

**Comment by bmaltais** [comment]
This is the result of the new security I had to implement to solve the potential hijack through gradio... so I won't be reversing this... what you can do is copy the command alongside the toml. You can actually name the toml what you like.. like lora_test_v1.toml and use that with the command like:

`"D:\kohya_ss\venv\Scripts\accelerate.EXE" launch --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1  --num_cpu_threads_per_process 2 "D:/kohya_ss/sd-scripts/train_network.py" --config_file "lora_test_v1.toml" --lr_scheduler_type CosineAnnealingLR --lr_scheduler_args T_max=1000 eta_min=0e-0`

You can also tweak the settings in the toml to your taste outside the GUI to train... quite useful.

**Comment by neoraoz** [comment]
That's very kind of you.
