### ISSUE TITLE
What are the default adaptive_noise_scale and noise_offset  for SD 1.5 and SDXL

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2336]
@bmaltais I don't know did you test but with newest version it is default 0 for adaptive_noise_scale  and then it gives error if we set noise_offset  = 0  

https://github.com/kohya-ss/sd-scripts/issues/1275

**Comment by bmaltais** [comment]
I just pushed a fix to the dev branch. Should work now.

**Comment by FurkanGozukara** [comment]
> I just pushed a fix to the dev branch. Should work now.

thanks. i wish you could push such app breaking stuff into main earlier. because my scripts and tutorials uses main branch and noobs having issues

so now when it is set as 0 it will work as before right?

**Comment by bmaltais** [comment]
I will push a release later tonight... I have found a MAJOR bug that was causing bad training... Should be fixed also ;-)
