### ISSUE TITLE
[Feature request] Hide "Start tensorboard" buttons with cli argument.

### ISSUE THREAD

**Issue by jim60105** [bmaltais/kohya_ss#2345]
I'm attempting to separate Tensorboard in PR #2344 for docker, which causes "Start tensorboard" button no longer needed.
It would be great if we could hide it selectively.

![image](https://github.com/bmaltais/kohya_ss/assets/16995691/641761c3-0a2d-42da-b2fd-25880e89ae04)

**Comment by bmaltais** [comment]
Interesting work for docker users. I like the idea of building it as part of a pipeline so users can trust it is coming from the right source.

hiding the tensotboard via a cli parameter should be doable… I will check how much work would be required.

**Comment by bmaltais** [comment]
Regarding the lack of tensorboard in the image... This might confuse some users that are used to have it... I don't know how I feel about feilding issues of users constantly reporting that the tensorboard support is broken... Would there not be a way to not package tensorboard in the image... but for users who want to use it to dynamically install the missing modules? Python should be able to install missing modules and maintain functionality? Or perhaps leave the button but log a warning when a user click it in the docker image stating that this image does not support tensorboard to stay lean?

**Comment by jim60105** [comment]
I believe Docker users will know that TensorBoard is already running when they see this.
![image](https://github.com/bmaltais/kohya_ss/assets/16995691/0a170280-b818-4edd-ac12-952fc0b578e1)

You can install tensorboard on the fly, but docker cannot dynamically establish port mapping. So this won't work.
Currently, when you do not have tensorboard installed and press the button, it will write an error in the console (rather than crashing), which is good enough.
I think there won't be any actual difference if we just add a warning in the console.
It would be clearer to just hide it.

Perhaps we can write about this situation in the README of docker section.
Let them know that this is "by design".

**Comment by bmaltais** [comment]
The latest dev branch code will no longer shor the tensorboard button if tensorflow is not installed.

**Comment by bmaltais** [comment]
Will push that to dev in the next commit.
