### ISSUE TITLE
Not Loading Existing Network Weights

### ISSUE THREAD

**Issue by ForceX34** [bmaltais/kohya_ss#2348]
The releases of the past two or three days including the dev 24.0.5 release, when training a LORA and selecting a safetensors file to load existing weights from in the parameters tab, it appears to not load the weights and starts training from a fresh state.

**Comment by bmaltais** [comment]
Can you share the json file? I will investigate why that is.

**Comment by ForceX34** [comment]
Yes, I’ll post when I get home from work

**Comment by jurgenprins** [comment]
i have the same issue, but was able to find a workaround that may help pinpoint the issue.

the config json has the lora_network_weights parameter,  but the accelerate is using tmpfilelora.toml, which seemingly expect network_weights parameter  (without lora_).

if I simply copy the lora_network_weights line to network_weights in tmpfilelora.toml just before the accelerate reads it, it works

actually there may be more parameters not going through properly, it seems there are a lot less lines in tmpfilelora.toml than in the original config json

**Comment by bmaltais** [comment]
I will check why the parameter is not mapped properly. The toml will not contain any of the non required or configured ones vs the json. This is normal.

**Comment by bmaltais** [comment]
OK... as you said... the toml expect network_weight... I have fixed the issue is the dev branch:

```
git fetch origin
git checkout dev
```
