### ISSUE TITLE
use_wandb

### ISSUE THREAD

**Issue by ccharest93** [bmaltais/kohya_ss#2351]
It seems that sd_scripts has been updated and the use_wandb option does not work anymore. Logger option in sd_scripts is now --log_with which has options ["all", "tensorboard", "wandb", None].

https://github.com/kohya-ss/sd-scripts/blob/71e2c91330a9d866ec05cdd10584bbb962896a99/library/train_util.py#L3139

I propose changing the WANDB Logging checkbox to a scroll down menu with the options specified above and a default of None, and which save to "log_with" argument instead of "use_wandb". This would not modify existing behaviour for users that do not use wandb, and would require a script modification for users that do (which is necessary anyway per the option use_wandb not doing anything in sd_scripts anymore).

I can write the PR if you agree with this change @bmaltais

**Comment by bmaltais** [comment]
Agree. Please create a PR to align with the updated as-scripts.
