### ISSUE TITLE
Getting Error when training, Error after prepare optimizer, data loader etc.

### ISSUE THREAD

**Issue by ai4uiux** [bmaltais/kohya_ss#236]
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.95it/s]
import network module: networks.lora
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
Traceback (most recent call last):
  File "C:\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\kohya_ss\train_network.py", line 150, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "C:\kohya_ss\library\train_util.py", line 1536, in get_optimizer
    assert optimizer_type is None or optimizer_type == "", "both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方のオプションが指定されています"
AssertionError: both option use_8bit_adam and optimizer_type are specified / use_8bit_adamとoptimizer_typeの両方のオプションが指定されています
Traceback (most recent call last):
  File "C:\Users\mohda\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mohda\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/SD/TRAINING/01.ANI/Emily_Simmons/img', '--resolution=768,768', '--output_dir=C:/SD/TRAINING/01.ANI/Emily_Simmons/model', '--logging_dir=C:/SD/TRAINING/01.ANI/Emily_Simmons/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Emily_Simmons1', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Lion', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by rockerBOO** [comment]
Remove `8bit adam` for the moment

**Comment by bmaltais** [comment]
Uncheck 8bit Adam for the moment. I think I will remove the checkbox in the GUI and make the AdamW8bit the new défaut... That way it will not error out anymore... This should have minimal effect on users with older config files prior to the optimiser addition.

**Comment by Woisek** [comment]
@bmaltais 
Sorry for getting off topic here, but could you explain, how we can use the TensorBoard, like you showed it in your video about the White Queen model? I can't get it to run and I'm not really sure on how to do it. :/

**Comment by bmaltais** [comment]
@Woisek There you go: https://www.youtube.com/watch?v=--AUw88UEVc

**Comment by Woisek** [comment]
@bmaltais 
Wow! That was quick and what a service. :D Many thanks for this short and on point video.
The only thing left to say is please concider the possibility to start the Tensorboard within the GUI, ideally plus an option with a selected log (i.e. a TB button besides the logging folder entry).
Many thanks again!

**Comment by bmaltais** [comment]
> 

Good idea... Will need to see how I can elegantly implement it.

**Comment by Woisek** [comment]
Perfect! Thanks. :D

**Comment by bmaltais** [comment]
I have implemented it in the dev branch. Will merge into master when there are a few more changes. For now you can test it by going:

`git checkout dev`

To get back to the master branch just do:

`git checkout master`

**Comment by Woisek** [comment]
OK, tested it a bit. So far looking good and is working. I want to suggest something, I open a new thread.
Thanks for now for this quick implementation!
