### ISSUE TITLE
Issue with epoch training parameters (1600 optimization steps) since the last update.

### ISSUE THREAD

**Issue by PeterLorre** [bmaltais/kohya_ss#2371]
I'm on a slowish machine with 8G Vram. When I train loras, I usually just train 1 epoch with a good data set. Usually this is fine for me. Since the last update, its automatically training multiple epochs even though I only have 1 selected. The optimization steps are at automatically set to 1600 forcing multiple epochs. I just want my batch size of 1 with a 20_X repeat folder and 1 epoch. What am I missing?

![image](https://github.com/bmaltais/kohya_ss/assets/9637697/1dae34af-8e49-49c8-85d0-b79ff84b37f4)
![image](https://github.com/bmaltais/kohya_ss/assets/9637697/89972022-ee22-454b-aa17-4489006a4fdb)

**Comment by bmaltais** [comment]
You need to set the max epoch value. By default sd-scripts will attribute a max steps = 1600 unless you specify something else... I aligned the GUI to  set the same default value... but older json files did not use that... so now youneed to watch out for that internal default of sd-scripts.
