### ISSUE TITLE
Problems with install, failing to get sd-scripts

### ISSUE THREAD

**Issue by TeKett** [bmaltais/kohya_ss#2380]
I recently re-installed kohya due to some issues that was solved. When i did that i had problems to get sd-scripts, folder is empty, and does not auto download. So while i was (but never submitted) writing up a issue for it, i re-installed kohya again using git clone, only for it to work as intended.

Now however, i accidentally deleted kohya, and re-installed it again, with the same issue of failing to get sd-scripts when i get it from the release page. Once again, if i instead get it using git clone it works.

win10

**Comment by jim60105** [comment]
git clone **--recursive** https://github.com/bmaltais/kohya_ss.git

**Comment by TeKett** [comment]
> git clone **--recursive** https://github.com/bmaltais/kohya_ss.git

So doing exactly what i did?

**Comment by jim60105** [comment]
> > git clone **--recursive** https://github.com/bmaltais/kohya_ss.git
> 
> So doing exactly what i did? I said it worked. The problem is the getting it from the release page.
> 
> Far as i can see it grabs it when you run the installer, so recursive should not be needed the way the gui is set up.

I'm sorry for misunderstanding your question. I thought you meant that git clone not working.

**Comment by bmaltais** [comment]
> I recently re-installed kohya due to some issues that was solved. When i did that i had problems to get sd-scripts, folder is empty, and does not auto download. So while i was (but never submitted) writing up a issue for it, i re-installed kohya again using git clone, only for it to work as intended.
> 
> Now however, i accidentally deleted kohya, and re-installed it again, with the same issue of failing to get sd-scripts when i get it from the release page. Once again, if i instead get it using git clone it works.
> 
> win10

When you say get it from the release page... you mean as a zip file? Yeah... that does not properly set the git subproject config and will not work... Always use git clone.
