### ISSUE TITLE
Default Max Train steps is 1600 and not zero - in v24.0,7

### ISSUE THREAD

**Issue by zadokov** [bmaltais/kohya_ss#2391]
![image](https://github.com/bmaltais/kohya_ss/assets/98109474/017f3ab4-0219-481c-a42e-61ed69e85855)
Since I assume the value is new, if you open old configuration and run it with this version, the training stops after 1600 steps.
@bmaltais - Value should be set to Zero.

**Comment by bmaltais** [comment]
The as-scripts internal default value is set to 1600, so I decided to set the GUI to the same to ensure users understand that this is the value the as/scripts use. I will see if I can change the config load code to sort of set the value to possibly 0 if it was not set.

**Comment by bmaltais** [comment]
The v24.0.8 will set it to 0 if there is no value specified in the old configs.

You can test it in the dev branch for now:

```
git fetch origin
git checkout dev
git pull
```
