### ISSUE TITLE
How can I train a lora without instance prompt and class token? 

### ISSUE THREAD

**Issue by younyokel** [bmaltais/kohya_ss#2401]
Hey, I keep setting up a runpod pod for kohya but different issues arise making it very hard to do. Is there a way to train using only with tags/caption files without setting the instance prompt and class token?

**Comment by bmaltais** [comment]
You can use caption files. If you make use of caption files the instance prompt and class tokens will not be used.

**Comment by younyokel** [comment]
@bmaltais Thanks, but how do I set up the dataset with caption format instead of instance/class? This is a bit confusing. When trying to prepare the dataset, it prints the fields are empty?
