### ISSUE TITLE
--always_first_tags is not passwed when using WD14 Captioning

### ISSUE THREAD

**Issue by Zoey2936** [bmaltais/kohya_ss#2402]
I tried using WD14 Captioning, but my "Prefix to add to WD14 caption" was not added to the txt files, so I looked at the command and there was not --always_first_tags argument added

**Comment by bmaltais** [comment]
It is not working. Instead I am addind the prefix tags using an alternate method... It should be added to the captions after the WD14 tagging is done.

```python
    subprocess.run(run_cmd, env=env)


    # Add prefix and postfix
    add_pre_postfix(
        folder=train_data_dir,
        caption_file_ext=caption_extension,
        prefix=always_first_tags,
    )

    log.info("...captioning done")
```

**Comment by Zoey2936** [comment]
no, I can't find the prefix in the txt files for some reason...

**Comment by bmaltais** [comment]
I will investigate what is going on... hopefully it is an easy fix.

**Comment by bmaltais** [comment]
I did test it and it work just fine for me... I put `test1, test2` in the `Prefix to add to WD14 caption` field and it was added to all the caption files as a prefix. I really don't understand why it does not work for you.

**Comment by Zoey2936** [comment]
I use the recursive option, could that be the readon?

**Comment by bmaltais** [comment]
> I use the recursive option, could that be the readon?

Right. OK, I have implemented the fix and pushed to master in the latest release.

**Comment by Zoey2936** [comment]
thanks!
