### ISSUE TITLE
[Feature Request] Print Command - Save TOML file as named file instead of temp file

### ISSUE THREAD

**Issue by keclee** [bmaltais/kohya_ss#2405]
For batching multiple training commands into a script file, it would be nice to not have to individually save every tmpfiledbooth.toml file, perhaps also save as a file with name based on timestamp. 

In previous versions the print training command would have all the necessary arguments to run with accelerate. Now the multi-line command from "print training command" requires carets^ per line in windows batch file and needing to separately save each toml file with a new filename and editing the filename in the command, which can easily be prone to errors when trying to batch multiple commands.

**Comment by bmaltais** [comment]
I agree... I will create the tmp files with a date time stamp so the can easilly be called in a batch file.

**Comment by bmaltais** [comment]
It is now merged in the `dev` branch.

**Comment by rafstahelin** [comment]
> For batching multiple training commands into a script file, it would be nice to not have to individually save every tmpfiledbooth.toml file, perhaps also save as a file with name based on timestamp.
> 
> In previous versions the print training command would have all the necessary arguments to run with accelerate. Now the multi-line command from "print training command" requires carets^ per line in windows batch file and needing to separately save each toml file with a new filename and editing the filename in the command, which can easily be prone to errors when trying to batch multiple commands.

@keclee I am interested in batching multiple training commands. What is your process now with calling in a batch file? I dont quite understand the process. 

I used to copy and paste accelerate cli commands straight into console.  thank you

**Comment by bmaltais** [comment]
Have a look at the dev branch. I made a change. Now each toml file has a unique name and you can simply copy the run command with the unique âme to a batch file to execute.

**Comment by rafstahelin** [comment]
> Have a look at the dev branch. I made a change. Now each toml file has a unique name and you can simply copy the run command with the unique name to a batch file to execute.

Hi Bernard, I like the new toml approach. However, I am renaming the toml to have a more meaningful training name, but I get an error. Is there a toml name rule to follow? 
```
(venv) E:\kohya_ss>E:\kohya_ss\venv\Scripts\accelerate.EXE launch --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 4 E:/kohya_ss/sd-scripts/sdxl_train.py --config_file ./outputs/config_finetune-test.toml
```
using "config_finetune-test.toml" as a config filename

and I get:

```
Traceback (most recent call last):
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 511, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 778, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 849, in load_value
    raise ValueError("Found tokens after a closed " +
ValueError: Found tokens after a closed string. Invalid TOML.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\kohya_ss\sd-scripts\sdxl_train.py", line 816, in <module>
    args = train_util.read_config_from_file(args, parser)
  File "E:\kohya_ss\sd-scripts\library\train_util.py", line 3746, in read_config_from_file
    config_dict = toml.load(f)
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 156, in load
    return loads(f.read(), _dict, decoder)
  File "E:\kohya_ss\venv\lib\site-packages\toml\decoder.py", line 514, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Found tokens after a closed string. Invalid TOML. (line 22 column 1 char 722)
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "E:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['E:\\kohya_ss\\venv\\Scripts\\python.exe', 'E:/kohya_ss/sd-scripts/sdxl_train.py', '--config_file', './outputs/config_finetune-test.toml']' returned non-zero exit status 1.
```

**Comment by rafstahelin** [comment]
> Have a look at the dev branch. I made a change. Now each toml file has a unique name and you can simply copy the run command with the unique name to a batch file to execute.

@bmaltais working very nicely for me thanks

**Comment by keclee** [comment]
> > For batching multiple training commands into a script file, it would be nice to not have to individually save every tmpfiledbooth.toml file, perhaps also save as a file with name based on timestamp.
> > In previous versions the print training command would have all the necessary arguments to run with accelerate. Now the multi-line command from "print training command" requires carets^ per line in windows batch file and needing to separately save each toml file with a new filename and editing the filename in the command, which can easily be prone to errors when trying to batch multiple commands.
> 
> @keclee I am interested in batching multiple training commands. What is your process now with calling in a batch file? I dont quite understand the process.
> 
> I used to copy and paste accelerate cli commands straight into console. thank you

Currently just paste the command(s) into a Windows .bat file and add carets^ at the end of each line for each command so batch file recognizes it as a single command. No caret at the final line of each command. Toml file is saved individually until dev branch is merged. You can run other commands in the batch file, like putting the computer to sleep afterward.

run batch file from kohya_ss folder

Example of the pasted command:
`"C:\Users\youruser\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE" launch^
                         --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1^
                         --num_machines 1 --num_cpu_threads_per_process 2^
                         "C:/ai/0_Kohya_SS/kohya_ss/sd-scripts/sdxl_train.py" --config_file^
                         "./outputs/tmpfiledbooth.toml"`

**Comment by rafstahelin** [comment]
> > > For batching multiple training commands into a script file, it would be nice to not have to individually save every tmpfiledbooth.toml file, perhaps also save as a file with name based on timestamp.
> > > In previous versions the print training command would have all the necessary arguments to run with accelerate. Now the multi-line command from "print training command" requires carets^ per line in windows batch file and needing to separately save each toml file with a new filename and editing the filename in the command, which can easily be prone to errors when trying to batch multiple commands.
> > 
> > 
> > @keclee I am interested in batching multiple training commands. What is your process now with calling in a batch file? I dont quite understand the process.
> > I used to copy and paste accelerate cli commands straight into console. thank you
> 
> Currently just paste the command(s) into a Windows .bat file and add carets^ at the end of each line for each command so batch file recognizes it as a single command. No caret at the final line of each command. Toml file is saved individually until dev branch is merged. You can run other commands in the batch file, like putting the computer to sleep afterward.
> 
> run batch file from kohya_ss folder
> 
> Example of the pasted command:
> 
> ```
> "C:\Users\youruser\AppData\Local\Programs\Python\Python310\Scripts\accelerate.EXE" launch^
>                          --dynamo_backend no --dynamo_mode default --mixed_precision bf16 --num_processes 1^
>                          --num_machines 1 --num_cpu_threads_per_process 2^
>                          "C:/ai/0_Kohya_SS/kohya_ss/sd-scripts/sdxl_train.py" --config_file^
>                          "./outputs/tmpfiledbooth.toml"
> ```

thanks. In Lixus I just run the above commands as a single line in terminal and I edit the toml name as a preset, using the dev branch. Instead of making a batch file, i just copy ech command in notepad, and when ready I paste all of them together in cli. I actually find the toml a very nice improvement over the Print only command readout from earlier Kohya version. Glad for it.
