### ISSUE TITLE
[Feature Request] Support for simultaneous loading of tag and caption files.

### ISSUE THREAD

**Issue by waomodder** [bmaltais/kohya_ss#2407]
Thanks for always maintaining the tool.
sd-script has a function that reads and learns captions and tags at the same time, but we would like you to create an item that reads not only tags but also captions in Lora learning, for example. At present, there is a method that creates metadata from tags and captions and reads it in, but we would like to read in caption files without having to create metadata.

**Comment by bmaltais** [comment]
Well, as I only wrap kohya's sd-scripts in a GUI I could add support for it if there is a way to provide the needed parameters to sd-scripts.

Is it possible to do this manually today via the sd-scripts trainers?

If not then I suggest to open an enhancement request directly on kohya's sd-scripts repo.

**Comment by waomodder** [comment]
Thanks for the answer. Yes, I will ask kohya directly.
