### ISSUE TITLE
Allow config file as input for lycoris preset

### ISSUE THREAD

**Issue by slashedstar** [bmaltais/kohya_ss#2419]
Currently you can only use the default presets
https://github.com/KohakuBlueleaf/LyCORIS/blob/main/docs/Preset.md

**Comment by bmaltais** [comment]
Interesting... I will check if this could be implemented easilly... perhaps by allowing custom preset as a file path to a config .toml file...

**Comment by bmaltais** [comment]
OK, Give it a try in the `dev` branch. You can now type the path to the toml config file in the preset dropdown to use that instead of one of the default presets.

**Comment by slashedstar** [comment]
Seems to be working as intended 👍 thanks
