### ISSUE TITLE
Browser GUI Load - ERROR Could not load torch: No module named 'torch'

### ISSUE THREAD

**Issue by HTVoidTH** [bmaltais/kohya_ss#2423]
I looked around for 2 hours and found nothing, reinstalling and updating various things did not work.

![image](https://github.com/bmaltais/kohya_ss/assets/168592541/accaa2db-4792-48ff-9623-c4977cc5f07c)

**Comment by bmaltais** [comment]
Did you install CUDA 11.8 (https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64) as per the README instructions?

**Comment by HTVoidTH** [comment]
> Did you install CUDA 11.8 (https://developer.nvidia.com/cuda-11-8-0-download-archive?target_os=Windows&target_arch=x86_64) as per the README instructions?

Yes, i sucessfully installed all listed requirements.

**Comment by bmaltais** [comment]
Not sure what it is... Must be something missing on your computer... but no idea what. Maybe go on the NVIDIA web site and update your video drivers?

**Comment by HTVoidTH** [comment]
Sorry for the bother. I have reinstalled Python and turned off its App execution aliases, which has seemed to fix it. It now starts properly.

Thank you for your time.
![image](https://github.com/bmaltais/kohya_ss/assets/168592541/821b42ec-5fbc-4138-a06b-06f535220e70)
