### ISSUE TITLE
Training has ended - Launch command

### ISSUE THREAD

**Issue by quiqueapolo** [bmaltais/kohya_ss#2424]
I'm trying to run the model but I'm getting this error and I'm not able to solve it:

23:09:09-998664 INFO     image_num = 5
23:09:10-006672 INFO     repeats = 50
23:09:10-006672 INFO     Max train steps: 1600
23:09:10-010671 INFO     lr_warmup_steps = 0
23:09:10-026221 INFO     Saving training config to C:/EnriqueModels/kohya_ss/strawberry/Log\last_20240430-230910.json...
23:09:10-034215 INFO     Executing command:  launch --dynamo_backend no --dynamo_mode default --mixed_precision bf16
                         --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2
                         C:/EnriqueModels/kohya_ss/sd-scripts/fine_tune.py --config_file
                         ./outputs/config_finetune-20240430-230910.toml with shell=True
23:09:10-054244 INFO     Command executed.
'launch' is not recognized as an internal or external command,
operable program or batch file.
23:09:10-379596 INFO     Training has ended.

**Comment by bmaltais** [comment]
What version are you using? Are you using v24.0.9?

**Comment by quiqueapolo** [comment]
It was solved!

**Comment by maxlee1917** [comment]
Can you please share how you solve it? i am facing the same problem too... Thanks

> It was solved!

**Comment by maxlee1917** [comment]
22:34:59-590192 INFO     max_train_steps (720 / 1 / 1 * 5 * 1) = 3600
22:34:59-591200 INFO     stop_text_encoder_training = 0
22:34:59-591200 INFO     lr_warmup_steps = 0
22:34:59-597200 INFO     Saving training config to D:\Lora Training
                         Data\Industrials\model\inds181_20240503-223459.json...
22:34:59-598191 INFO     Executing command: "" launch --dynamo_backend no --dynamo_mode default --mixed_precision fp16
                         --num_processes 1 --num_machines 1 --num_cpu_threads_per_process 2
                         "D:/kohya_ss/sd-scripts/train_network.py" --config_file
                         "./outputs/config_lora-20240503-223459.toml" with shell=True
22:34:59-601205 INFO     Command executed.
'""' is not recognized as an internal or external command,
operable program or batch file.
22:34:59-751730 INFO     Training has ended.

_I am not sure what is the "" means, looks like there are a lil different. I still can't solve it.._ 

> I set the train steps to 0
