### ISSUE TITLE
image_num is doubling 

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2446]
My Print Shows the correct image_num of 198 but running sdxl_train.py I get double, 334 training images

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/af712b0f-3c3b-4320-9cf7-27ca78bab183)

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/0690c2c7-22b9-4abf-b322-d0a7bf502c79)

**Comment by bmaltais** [comment]
Are you using regularisation images? This would be why.

**Comment by rafstahelin** [comment]
No I am not. I am sending args to wandb via sdxl_train.py my hats the only thing that changed
