### ISSUE TITLE
Toml config file in Model Output path rather than ./output

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2447]
Not sure why the toml is saved in kohya's output folder rather than same as model save path. I tend to download my safetensors with my training jsons, but since training through cli is saved to toml I have to manually download them separately. Would make sense for them to be in one place with safetensors and json's. 

Also, when training via cli with toml, the jsons are no longer accurate. Would be good not save a training json to avoid confusion 

Maybe there's a logic to how it is right now, but wish this would be addressed to avoid messy training records

**Comment by bmaltais** [comment]
I could swap the output for the model output folder... make sense. Regarding modified toml not lining up with json this is normal as the toml feed sd-scripts directly... where the json is used to create the toml... so if you modify the toml manually you essentially "form" the config and bypass the GUI entirely.

**Comment by bmaltais** [comment]
@rafstahelin I have implemented the output to model dir change in the dev branch. Give it a try.

**Comment by rafstahelin** [comment]
Thanks makes sense and would appreciate it the switch to model output path 

Cheers

**Comment by rafstahelin** [comment]
thanks
