### ISSUE TITLE
error validating vae

### ISSUE THREAD

**Issue by notjedi** [bmaltais/kohya_ss#2452]
i'm getting the following error when using `stabilityai/sdxl-vae` as the VAE:

`07:49:57-850003 ERROR    Validating stabilityai/sdxl-vae existence... FAILED: does not exist`.

### fix

https://github.com/bmaltais/kohya_ss/blob/95f888306ed32f7ed16b3af53f3d8fa349aad838/kohya_gui/dreambooth_gui.py#L544

the above line should be using `validate_model_path` instead of `validate_folder_path`

**Comment by bmaltais** [comment]
Dans, I will fix that today.

**Comment by notjedi** [comment]
i see that you have made a commit(#2454) to fix this issue but it's still not fixed. you've replaced `validate_folder_path` with `validate_file_path` instead of `validate_model_path`.

**Comment by bmaltais** [comment]
OK... I never use this option so maybe there is something I don't get... vae are usually indifidual files... so I check for the presence of the file at the path specified. Are you not passing a path to the VAE file?

**Comment by notjedi** [comment]
you can either give it a path to a file or a huggingface identifier like `stabilityai/sdxl-vae`

**Comment by bmaltais** [comment]
Crap... this is what I was afraid of...
