### ISSUE TITLE
Stop TE (% of total steps) Dreambooth function NOT in FinetTuning module

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2457]
Would love to experiment with this funtion that is present on Dreambooth.
Is there a reason why it is not in Finetuning? Is it not possible to use? Can we add?

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/58ea1b6f-979d-4a2c-8d0c-082b479311d9)

**Comment by bmaltais** [comment]
I need to remove that from the GUI, you are right.

**Comment by rafstahelin** [comment]
ok thanks

**Comment by bmaltais** [comment]
@rafstahelin You should raise this with koihya on his repo at sd-scripts... he would be the one that would need to implement the feature in the other trainers. There is probably a reason why he did not...

**Comment by rafstahelin** [comment]
Hi Bernard yes it figures. I will raise it. Thanks again
