### ISSUE TITLE
AMD GPU's do not work

### ISSUE THREAD

**Issue by silverace71** [bmaltais/kohya_ss#246]
Solution? yes. 
https://en.wikipedia.org/wiki/GPUOpen
https://github.com/ROCm-Developer-Tools/HIP
https://gpuopen.com/hiprt/
https://rocmdocs.amd.com/en/latest/
Those are a couple of useful links, you can compile Cuda into HIP whick runs on both AMD and NVIDIA.

**Comment by ClashSAN** [comment]
https://github.com/huggingface/diffusers/issues/684#issuecomment-1350188501
