### ISSUE TITLE
Logging when using sdxl_train_network.py

### ISSUE THREAD

**Issue by loremipsumyaya** [bmaltais/kohya_ss#2468]
How I could hook into the current status for logging purposes when using `sdxl_train_network.py`?

I am interested in running my own function for each training step or epoch.

 Thank you in advance!

**Comment by bmaltais** [comment]
This is a question for kohya in his sd-script repo. He might need to make provision into his code to properly do that. I don't maintain his code so he really is the persaon to ask to.

**Comment by loremipsumyaya** [comment]
Thank you for your reply @bmaltais ! I asked them as well. Here is a link for reference: https://github.com/kohya-ss/sd-scripts/issues/1326
