### ISSUE TITLE
v24.1.2 - Does not create output folder if not exist

### ISSUE THREAD

**Issue by zadokov** [bmaltais/kohya_ss#2470]
In this version (again :-) ) when specifying a non-existing folder for the model output, the folder is not created.
@bmaltais  - Can I ask to have this working as before (I use a separate folder per training)?
Now I get the below:

18:58:07-757534 INFO     Start training LoRA Standard ...
18:58:07-759399 INFO     Validating lr scheduler arguments...
18:58:07-760905 INFO     Validating optimizer arguments...
18:58:07-761905 INFO     Validating F:/SD/workspace/output/Lora/LogByRun/XLJC10 existence and writability... SUCCESS
18:58:07-762905 ERROR    Validating F:/SD/workspace/output/Lora/XLJC10/JNautJC10.29 existence and writability... FAILED:
                         does not exist

**Comment by bmaltais** [comment]
Darn... I keep improving the code but drop some featured ;-) I need to think of a way to properly create those folders in a structured manner...

**Comment by bmaltais** [comment]
Fixed in `dev` branch
