### ISSUE TITLE
ConnectionTimeoutError

### ISSUE THREAD

**Issue by cabasisijohnrey** [bmaltais/kohya_ss#249]
(venv) PS C:\Users\cabjo\OneDrive\Documents\Kohya\kohya_ss>
(venv) PS C:\Users\cabjo\OneDrive\Documents\Kohya\kohya_ss> pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000242086F6FB0>, 'Connection to download.pytorch.org timed out. (connect timeout=15)')': /whl/cu116/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000242086F7250>, 'Connection to download.pytorch.org timed out. (connect timeout=15)')': /whl/cu116/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000242086F73D0>, 'Connection to download.pytorch.org timed out. (connect timeout=15)')': /whl/cu116/torch/
ERROR: Operation cancelled by user

**Comment by bmaltais** [comment]
The provider of that module might have some networking issue... try again later

**Comment by cabasisijohnrey** [comment]
I have tried it again today but still have the same issue.
