### ISSUE TITLE
How exactly does masked training work?

### ISSUE THREAD

**Issue by massFlourine** [bmaltais/kohya_ss#2493]
I have tried to use a .toml dataset file, but every time there is some error where it does not understand what is being asked for. If anybody has figured out how to run LoRA masked loss training, I would be very grateful if they shared their .toml config file as well as a short description of their file structure.

My file structure is as follows:
training-data
 - img
    - 1_instancetag classtag
 - mask-img
    - 1_instancetag classtag
 - log
 - model
 - config.toml

Kind regards

**Comment by bmaltais** [comment]
There is a functional example under test/config/dreambooth-AdamW8bit-masked_loss-toml.json

Load it in Dreambooth and see if it will work for you. You can then use a similar structure for your own training.
