### ISSUE TITLE
Can stable_cascade branch be updated to match the master branch? GUI lora/custom model support?

### ISSUE THREAD

**Issue by b-7777777** [bmaltais/kohya_ss#2495]
As title says, would it be possible for the stable_cascade branch to receive updates to match (or be closer in version to) the master branch? Is lora/custom model support using the GUI still in progress? 

Thanks in advance!

**Comment by ermanitu** [comment]
Same here. I've tried OneTrainer and the models generated are incompatible with ComfyUI. Kohya_ss ever generate confiable models. People are switching to Stable Cascade but no good tool for train LoRAs.

**Comment by bmaltais** [comment]
Stable Cascade has not been updated by kohya in the lats 3 months... Unless he merge it in the dev or master branch I will have to wait to update the GUI... as it might never make it to main...

**Comment by b-7777777** [comment]
I made a new issue on kohya's repo about it: https://github.com/kohya-ss/sd-scripts/issues/1334
I know he's a busy guy but I really hope stable cascade can get some more love, I'm seeing some really nice results now that people are working on more finetunes

**Comment by 3blackbar** [comment]
cascade is much better than xl and 1.5 with some cartoon characters, peeople never gave it a chance cause of missing nudity... but its not a bad model, it exceeds xl with some stuff and its noise patterns are pleasing to the eye
