### ISSUE TITLE
sd-scripts folder is empty

### ISSUE THREAD

**Issue by samuelkurt** [bmaltais/kohya_ss#2497]
I don't know what to do. During the Setup process it treys to run some kind of Script but fails doing so. When I go to check the Path its empty. What should I do?
![Screenshot from 2024-05-13 16-37-34](https://github.com/bmaltais/kohya_ss/assets/104158296/13f2c370-7468-446f-be10-91fe9ef3273e)
![Screenshot from 2024-05-13 16-36-18](https://github.com/bmaltais/kohya_ss/assets/104158296/271182d8-12e9-4b78-9677-bf358eb7d8b4)

**Comment by bmaltais** [comment]
Did you clone the repo following the instructions on the README or did you download the zip file? You have to use the git clone command.

**Comment by b-7777777** [comment]
simple way for linux if you need to re-do gitclone and want to pull updates without always going into the terminal: 

> sudo wget https://github.com/shiftkey/desktop/releases/download/release-3.3.3-linux1/GitHubDesktop-linux-amd64-3.3.3-linux1.deb

> sudo apt install ./GitHubDesktop-linux-amd64-3.3.3-linux1.deb -y

open github desktop, add repository by url, input 

> https://github.com/bmaltais/kohya_ss.git
(github desktop now cloans it for you)

open terminal 
>cd 'location of your kohya_ss folder'

>source ./setup.sh

**Comment by david-born** [comment]
git clone but sd-scripts is empty too (Ubuntu)

**Comment by bmaltais** [comment]
You did `git clone --recursive https://github.com/bmaltais/kohya_ss.git`

**Comment by david-born** [comment]
missed --recursive ! Thank you!
