### ISSUE TITLE
几处中文文档的改进建议

### ISSUE THREAD

**Issue by liushigit** [bmaltais/kohya_ss#2503]
kohya_ss/docs/train_network_README-zh.md 中：

## 1

> “此外，通过 --network_args 指定例如 --network_args "unit=4" 的参数。 unit 是划分rank的单位。例如，可以指定为 --network_dim=16 --network_args "unit=4" 。请将 unit 视为可以被 network_dim 整除的值( network_dim 是 unit 的倍数)。”

中的

> “请将 unit 视为可以被 network_dim 整除的值”

应改为：“请将 unit 设为可以整除 network_dim 的整数”

## 2

> 在 train_network.py 中，使用 --network_module 选项指定要训练的模块名称。对
> 于LoRA模块，它应该是 network.lora ，请指定它。

这里有两个问题：

- 这里`network.lora`是否是唯一合法的名称？因为文档中用了“应该是”（should be）的表述，是否意味着“should but not must”，还是“should not be anything else”？
- 其后例子里又出现`networks.lora`，单复数变了。

如果需要编辑改进中文文档，我愿意效劳。

**Comment by bmaltais** [comment]
Hi, this is really more a question for kohya, the author of the sd-scripts my GUI is calling. You can open an issue on his repo at: https://github.com/kohya-ss/sd-scripts
