### ISSUE TITLE
sd-scripts merged PR for passing args to WandB into Dev Branch--Please add option into kohya_ss Dev

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2508]
Hi @bernardmaltais 
Finally, kohya merged the PR and the args passing to wandb is available in sd-scripts Dev. 
[(https://github.com/kohya-ss/sd-scripts/pull/1285#event-12857774925)]
thanks
raf

**Comment by rafstahelin** [comment]
@bmaltais heres the thread. I've tried switching to sd-scripts dev but the cli --log_config isn't recognised. I'm running the toml file in cli. Not sure how to use log_config. Maybe in additional args in gui, then print the toml?

**Comment by bmaltais** [comment]
I am not sure what the GUI need to do here... what should it do different vs what it does today for this? It is not clear to me what the purpose of --log_config is and what the GUI need to do about it.

**Comment by bmaltais** [comment]
OK, so all the gui need to do is to set the —log_config CLI option when one would select the new Log Config checkbox in the GUI.

**Comment by rafstahelin** [comment]
> OK, so all the gui need to do is to set the —log_config CLI option when one would select the new Log Config checkbox in the GUI.

@bmaltais 
Apologies for my lack of clarity. This is only available atm in sd-scripts dev branch. But yes, simply by setting this log_config in cli it passes all the parameter args to wandb

**Comment by bmaltais** [comment]
OK, I will implement it in the dev branch to test.

**Comment by bmaltais** [comment]
I have pushed the feature to the dev branch and merged sd-scripts latest dev branch into mine... give it a try.

I also added the other new features that were implemented in kohya's sd-scripts branch.

**Comment by rafstahelin** [comment]
@bmaltais Beautiful. Worked. Thanks Bernard
