### ISSUE TITLE
{Help} Network Rank Slider and No Half VAE checkbox is not showing up in my Kohya_ss after Installation.

### ISSUE THREAD

**Issue by pkdude** [bmaltais/kohya_ss#2525]
I was playing with the software with some online Tutorial, and i found that my software (v24.1.4)  does not have Network Rank Slider and No Half VAE checkbox in the parameter tab.. Tried different vers. but the problem is the same.. and the training time is around 22hrs..but for others it usually takes 30mins.. What am i doing wrong? I need help! Thanks.
![Screenshot 2024-05-23 at 01-38-11 Kohya_ss GUI v24 1 4](https://github.com/bmaltais/kohya_ss/assets/137614825/94878b71-4cf1-4be1-b6ce-d80149d17183)

**Comment by b-fission** [comment]
Look at the tabs at the very top. I think you want to use **Lora**, not Dreambooth.
I know from experience, happens all the time.
