### ISSUE TITLE
No json files on training

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2528]
@bmaltais  Since adoption of toml files, I have suddenly noticed json files aren't created on training launch. Are we only left with Toml file now? 

Seems like the json file was useful to re-use settings 

Is Toml effectively replacing json? Only trouble it doesn't load settings in the gui

**Comment by rafstahelin** [comment]
> I'm seeing both formats, json and toml, being created when I start training. Currently running version 24.1.4

Locally I see json's
On rubbed not

**Comment by bmaltais** [comment]
I am not sure why they are not created in runpod... is there an error message being displayed in the output when it can't create the file? Might point to where the issue is. Since I don't use runpod I can't reproduce the issue and therefore it is hard to solve...

**Comment by rafstahelin** [comment]
Closing, it appears json files are actually showing up on runpod trainings. Dont know what I had off. Thanks
