### ISSUE TITLE
where does the file model_large_caption.pth go?

### ISSUE THREAD

**Issue by riade3788** [bmaltais/kohya_ss#253]
i have it from stable diffusion and I don't wanna redownload it

**Comment by lcolok** [comment]
By default, the model file model_large_caption.pth is saved in the following directory on Windows:

C:\Users\your_username\.cache\torch\hub\checkpoints\

If you have previously downloaded the model file from Stable Diffusion and found it in the default directory, you can move the file to the Kohya_SS project to avoid redownloading. Additionally, if you want to save the model file to a different location, you can modify the code that specifies the save path.

The path information can be inferred from the following code:

- The `download_cached_file()` function in the program downloads the model file and saves it to the cache directory.
- The `get_cache_dir()` function returns the cache directory for the program, which is usually located in `$HOME/.cache/torch/hub` on Linux and macOS, or `C:\Users\your_username\.cache\torch\hub` on Windows.

**Comment by riade3788** [comment]
I want to move the cache folder altogether from c drive to another location ..how do I do that??
this is sloppy programming afaik as it takes important c drive space for stupid reasons

**Comment by lcolok** [comment]
> I want to move the cache folder altogether from c drive to another location ..how do I do that?? this is sloppy programming afaik as it takes important c drive space for stupid reasons

You could try creating a symbolic link that links the cache folder to another location of your choosing. This will allow the program to find the necessary files in the cache folder without taking up too much space on your C drive. On Windows, you can use the mklink command to create symbolic links. Here's an example command:

mklink /D "C:\Users\your_username.cache\torch\hub" "D:\your_new_location\torch\hub"

Please replace "your_username" and "your_new_location" in the command above with your actual username and new location path. Note that you will need to open the command prompt with administrator privileges to create a symbolic link.

Hope this helps!
