### ISSUE TITLE
sdxl training

### ISSUE THREAD

**Issue by yash-lnxct** [bmaltais/kohya_ss#2530]
I have 16GB VRAM even i got CUDA out of memory while training with dreambooth and choosing base model as SDXL 1.0

**Comment by b-fission** [comment]
I don't think 16gb vram can handle SDXL Dreambooth.

Even with the leanest config I can think of (batch size 1, unet only, gradient checkpointing, full fp16 training), I'm seeing almost 19gb of vram used while training.

**Comment by yash-lnxct** [comment]
Thank you for your valuable answer.

**Comment by b-fission** [comment]
@yash-lnxct  ... Actually, it does seem possible to handle dreambooth with 16gb vram.

### Settings
- Train batch size : 1
- Learning rate TE1 & TE2 : 0
- Gradient checkpointing : On
- Optimizer : Adafactor or Lion8bit
- Cache text encoder outputs : On
- Full fp16 (or bf16) training : On

Though as I mentioned before, you'll have to train the Unet only which means setting TE1/TE2 learn-rate to zero. Training the text encoders and Unet takes vram usage above 16gb.

The checkbox for "Cache text encoder outputs" might not be visible in certain versions of the gui, so paste the text `--cache_text_encoder_outputs` in the "Additional parameters" to enable it.

**Comment by yash-lnxct** [comment]
OK. I will try these settings.
