### ISSUE TITLE
pip install argument might be passed incorrectly

### ISSUE THREAD

**Issue by b-fission** [bmaltais/kohya_ss#2538]
I have noticed some weird log files being created while `validate_requirements.py` gets called at startup.

It seems the package version specifier being passed to `pip install` is not quoted, so symbols like > and < will be treated as a pipe symbol.

For example, with the current [requirements file](https://github.com/bmaltais/kohya_ss/blob/master/requirements.txt), a command like
`python -m pip install rich>=13.7.1`
gets executed as 
`python -m pip install rich` and piping stdout to a file called `=13.7.1`

I've observed the behavior happening on Windows and Linux.

And to double-check, change the required version of rich to something fictitious like `rich>=1337.0` and see that the validation seems to pass when it should've failed due to a non-existent version on the package.

**Comment by bmaltais** [comment]
Good catch. I will see where the root cause of this is.

**Comment by bmaltais** [comment]
I have fixed the issue in the `dev` branch
