### ISSUE TITLE
Error when train model

### ISSUE THREAD

**Issue by cabasisijohnrey** [bmaltais/kohya_ss#254]
![image](https://user-images.githubusercontent.com/126302700/222043145-69de9f13-70da-4c51-8244-99a5710249d2.png)
![image](https://user-images.githubusercontent.com/126302700/222043862-9c3c16b2-f208-4bd3-93e7-7ffcfae357f2.png)
It stops at -zero exit status 1. What should I do to solve this error? It won't proceed with the training.

**Comment by lydd8888** [comment]
Same here

**Comment by cabasisijohnrey** [comment]
You still haven't figured out the solution?

**Comment by lydd8888** [comment]
No, I just followed a tutorial here and stuck

**Comment by lydd8888** [comment]
I roll back to v20.7.4 seems work.
You can go `git checkout 39ac6b008662fd99cda9920c4e491aaf07a204a1`

**Comment by cabasisijohnrey** [comment]
do you mean a pip version 20?

**Comment by dimitri-vs** [comment]
@cabasisijohnrey Open command prompt and CD to your `kohya_ss` folder. Or if you are on windows shift + Right-click inside the folder and click "Open command window here". Then just type `git checkout 39ac6b008662fd99cda9920c4e491aaf07a204a1`

Got things working for me until the bug is fixed
