### ISSUE TITLE
ValueError: fp16 mixed precision requires a GPU

### ISSUE THREAD

**Issue by survival93** [bmaltais/kohya_ss#255]
prepare tokenizer
prepare train images.
found directory 7_duoduo contains 19 image files
133 train images with repeating.
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 1216.33it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 126
bucket 1: resolution (512, 384), count: 7
mean ar error (without repeats): 0.00030507008288599717
prepare accelerator
Traceback (most recent call last):
  File "D:\AI\Lora\kohya_ss\train_db.py", line 346, in <module>
    train(args)
  File "D:\AI\Lora\kohya_ss\train_db.py", line 62, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "D:\AI\Lora\kohya_ss\library\train_util.py", line 1817, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "D:\AI\Lora\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "D:\AI\MINconda\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\AI\MINconda\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\AI\Lora\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\AI\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\AI\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\AI\Lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\AI\\Lora\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/AI/openai.wiki/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=D:/AI/train', '--resolution=512,512', '--output_dir=D:/AI/train', '--logging_dir=', '--save_model_as=safetensors', '--output_name=duoduo', '--learning_rate=1', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1064', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=Adafactor', '--clip_skip=2', '--bucket_reso_steps=64', '--shuffle_caption', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

What should I do to solve this error? It won't proceed with the training.

**Comment by bmaltais** [comment]
Try running the `accelerate config` step again. It look like it is not finding your GPU. Do you have more than 1 GPU in your computer? Perhaps this is confusing accelerate and you will need to specify the NVidia GPU ID for it to find it.

**Comment by survival93** [comment]
@bmaltais Thank you for your help,I use a laptop with two GPUs,How should I set up the accelerate config?

**Comment by rsheldiii** [comment]
@survival93 did you find a solution? I have an integrated and discrete GPU and I'm having this same issue - SD has no problem using my GPU but `accelerate test` always uses CPU, and `accelerate configure` doesn't list any GPUs

**Comment by rsheldiii** [comment]
solved this, initial issue was Torch not picking up my GPU. After reinstalling GPU driver and cuda, I needed to select `fp16` when offered in `accelerate config` if I wanted to use it in kohya_ss.

**Comment by 3VwVnts** [comment]
MacBook
One processor, the second discrete GPU

Intel UHD Graphics 630 1536 МБ
AMD Radeon Pro 5300M 4 ГБ
ValueError: fp16 mixed precision requires a GPU
