### ISSUE TITLE
Training is constantly failing to start

### ISSUE THREAD

**Issue by brucew4yn3rp** [bmaltais/kohya_ss#2562]
Why is the below issue preventing me from starting the training? I don't think I'm missing any parameters in the LoRA tab. 

Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/kohya_ss/venv/bin/python', '/workspace/kohya_ss/sd-scripts/sdxl_train_network.py', '--config_file', '/workspace/finished/model/config_lora-20240602-153104.toml']' returned non-zero exit status 1.
15:31:23-041574 INFO     Training has ended.

**Comment by brucew4yn3rp** [comment]
This error comes up if I use a safetensors file other than the stable diffusion base 1.0. Is using that file a requirement?

**Comment by b-fission** [comment]
Your error log doesn't give much useful info. Was there any more log text before that part? 
I would guess there's a conflicting option somewhere in your training config.

> This error comes up if I use a safetensors file other than the stable diffusion base 1.0. Is using that file a requirement?

You can use any safetensors file for training, but make sure to select the "SDXL" checkbox if it is an SDXL model.

**Comment by brucew4yn3rp** [comment]
Thank you for the response. It seems that I was trying to use a turbo model and a LoRA without realizing that only a proper checkpoint can be used for LoRA training.
