### ISSUE TITLE
 To modify sample prompts during training, edit the prompt.txt file in the samples directory.

### ISSUE THREAD

**Issue by DarkAlchy** [bmaltais/kohya_ss#2566]
This is how it was, but the latest version never write that .txt file.

**Comment by DarkAlchy** [comment]
I just looked and it is not writing it to the samples folder it wrote it in the model folder, so one folder higher.

**Comment by bmaltais** [comment]
Humm... is this also causing an issue to prompt the sample images during training? Not many have complained... so I guess it probably work fine... except the file is not in the expected location?

**Comment by DarkAlchy** [comment]
the way this thing does it now makes it extremely cumbersome as it puts it not in the samples folder but one up from it.

**Comment by bmaltais** [comment]
This is now fixed in the dev branch.

**Comment by DarkAlchy** [comment]
> This is now fixed in the dev branch.

Thank you.
