### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: ''

### ISSUE THREAD

**Issue by XinPeiHou** [bmaltais/kohya_ss#2568]
![kohya_error](https://github.com/bmaltais/kohya_ss/assets/31240098/49989fc8-0e2a-4150-9494-47dc5b7b0f75)
What is the cause of this error？Thanks

**Comment by b-fission** [comment]
It looks like the gui can't find the `accelerate` executable, so it's using a blank for it.
The command line should be `accelerate launch ......` and not `  launch .....`

You may need to check if the file `kohya_ss/venv/bin/accelerate` exists and has "execute" permission.

If it doesn't look right, try to uninstall that component by running `./venv/bin/pip uninstall accelerate` and then start the gui  which should automatically reinstall it.

**Comment by XinPeiHou** [comment]
> It looks like the gui can't find the `accelerate` executable, so it's using a blank for it. The command line should be `accelerate launch ......` and not ` launch .....`
> 
> You may need to check if the file `kohya_ss/venv/bin/accelerate` exists and has "execute" permission.
> 
> If it doesn't look right, try to uninstall that component by running `./venv/bin/pip uninstall accelerate` and then start the gui which should automatically reinstall it.
> 
> EDIT: I'm looking again; you're using a conda environment instead of the usual venv? If the uninstall command above didn't work, maybe this command will do instead: `pip uninstall accelerate`

ok,Thanks, the issue solved after install accelerate
