### ISSUE TITLE
when loading saved Preset, Learning Rate always auto-fills

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2576]
Hi @bmaltais 
I never use the top most Learning Rate field. For me text encoder is always 1/10th of unet lr. 
I am saving my presets, but as a rule the learning rate just auto-fills and throws off my my separate lr's.
Is there a way to change this it is very distracting

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/1b7fe702-5005-4602-a95c-800edcf7aab5)

-------
Also, when using preset with custom sdxl model with saved sdxl path, when loading the preset, I loose the v2/v_/SDXl checkboxes. I have to choose a SAI model, then repaste the original custom model path in order for the checkboxes to appear. This is unfortunate, as always train SDXL, and it is not possible to save a custom sdxl model path and keep the SDXL checkbox ticked

![image](https://github.com/bmaltais/kohya_ss/assets/64715158/d1d4307a-6491-4e87-a745-a42b93a20b31)

Thank you dear sir!

**Comment by bmaltais** [comment]
Hummm, thank you for reporting. I will check what is going on with those.

**Comment by bmaltais** [comment]
OK, it is merged... I hope this change will not cause more issues for other users... Worst case I will revert to what it used to be and you might need to endure the issue until a better solution can be implemented... but I the moment I don't have any idea... because thie field is used with other trainers and does not have the same "meaning" as in LoRA... and there is the complexity...

**Comment by rafstahelin** [comment]
> OK, it is merged... I hope this change will not cause more issues for other users... Worst case I will revert to what it used to be and you might need to endure the issue until a better solution can be implemented... but I the moment I don't have any idea... because thie field is used with other trainers and does not have the same "meaning" as in LoRA... and there is the complexity...
> 
> 

Ok got it. Will test in dev. Thanks! 🙏

**Comment by rafstahelin** [comment]
@bmaltais changes seem to be working well for me
Thanks Bernard
