### ISSUE TITLE
how to uninstall kohya_ss completely.

### ISSUE THREAD

**Issue by yuyuzururu** [bmaltais/kohya_ss#2604]
Since my graphics card doesn't support training (AMD, 2GB) and I got a torch incompatibility during the process of entering the GUI, it got worse after downloading the compatible version, so I decided to remove it.But since it installs a lot of things on its own during the installation process, I don't dare to delete the folder directly. Now I would like to sincerely ask for a way to completely delete kohya_ss from those of you who understand computers.

**Comment by yuyuzururu** [comment]
Is it possible to delete the folder directly?

**Comment by bmaltais** [comment]
Yes. Delete the folder and it is gone.

**Comment by yuyuzururu** [comment]
ok,thank you😊
