### ISSUE TITLE
Feature Request: model name = WANDB-run name

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2609]
I expect most trainers logging to WANDB will want to send the model-name to wandb.

If that is the case, it would be helpful to just have an option to set run name same as model name. 

The settings are each at the very top of the GUI and the very bottom. It would save a lot of back and forth

**Comment by bmaltais** [comment]
I will need to think about how best to do this... maybe set the model name as the WANDB only if the WANDB name has not been provided...

**Comment by rafstahelin** [comment]
> Give it a try. Should be working in the `dev` branch.

it doesnt work for me after git pull dev

when is the duplication supposed to trigger? By what?

I changed the model name and have wandb toggle selected and log config

Not sure how to trigger it

**Comment by rafstahelin** [comment]
@bmaltais i hadnt understood your method. Yea works great thanks!
