### ISSUE TITLE
Feature Request : Auto load a config file

### ISSUE THREAD

**Issue by FlowDownTheRiver** [bmaltais/kohya_ss#262]
It shall be great for the program to auto load a configuation file with the settings we define at launch time.So we don't need to load a config file each time we wanna have the same settings manually.Also by this way, we can use the same dataset directory location and we only change the directory name and images from the same location. 1 config file to rule them all.

This is a very convenient way of working I strongly believe .Can we have auto loading configuration feature?

**Comment by bmaltais** [comment]
How do you envision this working? You would want to pass the config file name as an argument to gui.ps1 or to the kohya_gui.py?

**Comment by FlowDownTheRiver** [comment]
Option 1 : It can be passed as an argument for the python files like kohya_gui.py or the other python files.
Option 2 : If you can do this, it is better.Add a checkbox in the gradio UI,like you choose a config file to load first,then click that checkbox to enable auto load the config file selected.In other words it remembers the last config file loaded.
You can also do both,I may have missed if there is a better way of doing this.
