### ISSUE TITLE
ImportError: cannot import name 'train_util' from 'library'

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [bmaltais/kohya_ss#2622]
I'm trying to run a LoRA merge into a checkpoint, but I keep getting this error:

```Traceback (most recent call last):
  File "C:\AI\Tools\Training\kohya_ss\sd-scripts\networks\merge_lora.py", line 7, in <module>
    from library import sai_model_spec, train_util
ImportError: cannot import name 'train_util' from 'library' (C:\AI\Tools\Training\kohya_ss\sd-scripts\library\__init__.py)
```

my `__init__.py` is empty. I assume this is intended.

Any suggestions?

**Comment by bmaltais** [comment]
Did you clone the repo with the --recursive option?

**Comment by MNeMoNiCuZ** [comment]
> Did you clone the repo with the --recursive option?

Good question, I can't recall.

Is there any way of checking after the fact?

**Comment by bmaltais** [comment]
Best is to delete the folder and re clone

**Comment by MNeMoNiCuZ** [comment]
That fixed it. Thank you.
I had missed the instruction to use --recursive on my git clone operation. I have never seen that being needed before!

Good to know that it mostly works without it though (for LoRA training and merging at least).
