### ISSUE TITLE
Lora extract for Flux has been added.

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2731]
https://github.com/kohya-ss/sd-scripts/commit/b0a980844a2e02b1b1ae4cf615ae489dbf8ece67#diff-e348baa4a0aec60294fe1914887f073edc8f510bc8dba3f64c76b781deb777c5

**Comment by bmaltais** [comment]
Just pushed the GUI in the sd3-flux1 branch
