### ISSUE TITLE
Notice: LoCon will not work natively in a1111 sd-webui

### ISSUE THREAD

**Issue by KohakuBlueleaf** [bmaltais/kohya_ss#275]
![image](https://user-images.githubusercontent.com/59680068/222614157-39fc93df-f386-42f7-98fd-78e3b28b49ce.png)
in both a1111 sd-webui and addnet, LoCon need extension to load correctly.
Sd webui will load only part of locon.

(BTW, you can use pip install locon now)

**Comment by FlowDownTheRiver** [comment]
@KohakuBlueleaf Can you share some presets for the training to be used in this webUI not automatic? Like what confuses me most I have trained with these setting but any further information would be nice to know. I mean we need some help about undertstanding what is going on behind the scenes and thanks for developing locon.
![2023-03-05 21_10_31-Window](https://user-images.githubusercontent.com/71787427/222978041-68dc8b18-8e3f-4be6-81f0-6945c56a8387.jpg)

**Comment by KohakuBlueleaf** [comment]
@FlowDownTheRiver network dim=4, locon dim = 2
all alpha = 1
all lr = 2e-4(0.0002)

This is my prefer setup, may not be best for you
