### ISSUE TITLE
Discrepancies betw input args for UI vs CLI?

### ISSUE THREAD

**Issue by carolynsoo** [bmaltais/kohya_ss#2753]
I've noticed some unexpected discrepancies between what is expected via json in the UI vs what the CLI (i.e. the underlying code) likes; e.g.

1. json allows `optimizer_args` to be space-separated pairs of key-value args, like `"scale_parameter=False relative_step=False warmup_init=False"` VS calling train via CLI will call `get_optimizer` which expects optimizer_args to be an iterable of key-value pairs like [`[ "scale_parameter=False", "relative_step=False", "warmup_init=False" ]`](https://github.com/kohya-ss/sd-scripts/blob/25f961bc779bc79aef440813e3e8e92244ac5739/docs/train_SDXL-en.md?plain=1#L66)
2.  json refers to the arg `optimizer` but CLI wants `optimizer_type`

Is there a list of such discrepancies anywhere (are they deliberate?) and/or an easier way of finding them? A little concerned about missing something when running in the UI, vs in the CLI.

**Comment by bmaltais** [comment]
Not really... and those a most probably the only ones. The TOML take the args in a different format... so they are converted when creating it.

**Comment by carolynsoo** [comment]
Thanks for the reply! In general are there known conversions (between json & toml formats) that are always true? e.g. In some jsons I see 0 used to indicate None or False (such as when disabling a particular setting), but I wonder if there are some args for which I cannot just assume a json 0 is the same thing as a toml False/None.

**Comment by bmaltais** [comment]
There most probably are, but there is no compiled list. You pretty much have to study the code from the variable definition, processing and finally toml output. There are indeed some under the hood magic happening for some of them.

**Comment by carolynsoo** [comment]
Gotcha, appreciate the reply. (And hope this thread helps future readers - I didn't find any other discussion of these discrepancies, and the first encounter was quite surprising to us)
