### ISSUE TITLE
Convolution Rank (Dimension) and Convolutoion Alpha for Flux disappear 

### ISSUE THREAD

**Issue by DarkViewAI** [bmaltais/kohya_ss#2757]
Convolution Rank (Dimension) and Convolutoion Alpha for Flux disappear 

they are no longer there, some configs have it when i load, some don't

**Comment by DarkViewAI** [comment]
i think its because its training a lycoris full preset on my older config. 

could you please fix/ make it properly load?

Thank you!

**Comment by bmaltais** [comment]
Flux.1 training doesn't support those features. They were shown initially but ignored by the training script. I removed them to match what the trainer can actually handle.

**Comment by DarkViewAI** [comment]
@bmaltais idk if its placebo, but my results were different with it on, i rolled backed an earlier commit and compared, it even shows up on the config.

like even the samples are different and even when using in comfy its better.

**Comment by bmaltais** [comment]
Remember that the sd-scripts code has also evolved so it is possible some of the changes can be attributed to it. Only way to test would be to train with the latest gui then find a previous toml config file and copy those conv parameters and inject them in the toml then manually run another training to compare the results.

not simple but might work… I will ask kohya but I am pretty sure conv are not applicable to Flux.1

**Comment by bmaltais** [comment]
100% confirmed, conv layers don’t exist in Flux and the parameters had no effect as they are simply ignored.

**Comment by DarkViewAI** [comment]
@bmaltais 

i have no clue why my trainings are completely random now though.

1. I am able to manually change the conv dim and alpha, by loading in the config twice. How I do it, is when i load in my json file, i press the enter button not once but twice, then they show up.

2. i've tested the conv dim and and alpha, i even tried pushing it to 512, and 512 to see if training would be different. and to me it is, results horrible.

3. I then tested with normal level like 8 and 1, 16 and 4

and the training is back to normal.


Here is a comparison

my base dim and alpha is 128 x 64

every thing else is the same, seed, settings all 1 to 1. I did many trainings to confirm this, both on windows and linux.


For these two tests i tried conv and 8 and 1 and the other at 512 and 512

so clearly it is having some sort of an effect.
![8 Dim 1 Alpha](https://github.com/user-attachments/assets/c83d85d4-90cb-4a92-a8d3-5899d7c45ef1)
![512 Dim and 512 Alpha](https://github.com/user-attachments/assets/c1358919-853d-48b1-959c-fa79b377da65)

**Comment by DarkViewAI** [comment]
top is conv and 8 and 1
bottom is 512 and 512

**Comment by DarkViewAI** [comment]
![16 Dim 4 Alpha ](https://github.com/user-attachments/assets/66fe51b5-d614-4bbd-a763-4298f4c7787f)
![512Dim and 512 Alpha](https://github.com/user-attachments/assets/f9608f37-b13e-4c74-873e-a72bac6e2e00)


Here are another test

16 dim and 4 alpha for the conv

and 512 dim and 512 alpha for the conv

**Comment by DarkViewAI** [comment]
I've also tired 1 and 1 for the conv and results also arent as good, the config shows that its training flux as  a full lycoris.

**Comment by DarkViewAI** [comment]
maybe there is a bug or something

**Comment by DarkViewAI** [comment]
my samples are also the same consistent seed across all trainings, i've even tested them in comfy and forge, I can 100% confirm im getting better results with conv training along side my base 128x64 training

**Comment by DarkViewAI** [comment]
![32Conv and 1 Alpha](https://github.com/user-attachments/assets/5f6d2b65-1491-40fb-aa42-3d4dc56b00fc)
![512Conv and 512 Alpha](https://github.com/user-attachments/assets/01f31880-68de-4986-a7fe-31f22abb397c)
Here is another example

**Comment by DarkViewAI** [comment]
Top is 128 Dim and 64 Alpha with Conv Dim 32 and Conv Alpha 1

Bottom is 128 Dim and 64 Alpha with Conv Dim 512 and Conv Alpha 512


Both are step 1000 

same sample seed, also tested both in comfy, top one performed well, bottom struggled and faces were deformed

**Comment by bmaltais** [comment]
> Top is 128 Dim and 64 Alpha with Conv Dim 32 and Conv Alpha 1
> 
> Bottom is 128 Dim and 64 Alpha with Conv Dim 512 and Conv Alpha 512
> 
> Both are step 1000
> 
> same sample seed, also tested both in comfy, top one performed well, bottom struggled and faces were deformed

And both training are using the same seed? Koby himself told me it does not have en effect… 

![image](https://github.com/user-attachments/assets/efeb56ca-a455-470b-b468-58e3ecd7250a)


I suggest you open an issue directly in his sd-scripts repo. Perhaps he is carrying some code causing a bug when conv network values are provided…

**Comment by DarkViewAI** [comment]
@bmaltais i spoke to him in dms as well, said they same thing, but also possibly a bug he mentioned.

can you explain why the training in the json/toml shows that its trainings as a full lycoris with the conv dim and alpha in there, and not just a standard lora? and does the training ignore the json?

**Comment by bmaltais** [comment]
Can you share the json and toml showing it is training as a lyrics? Did you select flux1 as the Lora type?

**Comment by DarkViewAI** [comment]
happy to say now my training is now fixed witht his commit https://github.com/bmaltais/kohya_ss/commit/8a524c7bae9e070ad69deb0389b3b8bc46fc495e

**Comment by DarkViewAI** [comment]
it might of been a bug or something, but i tried 2 trainings now shotgunning 300 steps each on both, and they are consistent now

**Comment by DarkViewAI** [comment]
@bmaltais 
<img width="736" alt="ssss" src="https://github.com/user-attachments/assets/615ea889-fe48-4b33-8c50-e2e4ba5bf780">
json still shows lycoris though

**Comment by DarkViewAI** [comment]
@bmaltais there still seems to be an issue, when i load in the json twice, like i press the enter button once, the conv dim and alpha are not there, but when i i press enter again it reloads the json with the conv dim and alpha present in the gui

**Comment by bmaltais** [comment]
> @bmaltais there still seems to be an issue, when i load in the json twice, like i press the enter button once, the conv dim and alpha are not there, but when i i press enter again it reloads the json with the conv dim and alpha present in the gui

Yeah... this is a Gradio bug... it is a bit "flimsy"

**Comment by bmaltais** [comment]
> @bmaltais <img alt="ssss" width="736" src="https://private-user-images.githubusercontent.com/159950513/363427787-615ea889-fe48-4b33-8c50-e2e4ba5bf780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjM3MDUsIm5iZiI6MTcyNTEyMzQwNSwicGF0aCI6Ii8xNTk5NTA1MTMvMzYzNDI3Nzg3LTYxNWVhODg5LWZlNDgtNGIzMy04YzUwLWUyZTRiYTViZjc4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNjU2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzhmYzMzNzdlOWZjZWM2OTczMmNiMjFjNjYxNTJkMjk1NGRiM2VmZjkyYjFjNTM2NmM5NDI1ZGQyZjZhZjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1-IDNbT_mQMAcQt8QZd6q5vrk0YrxrF4o2iZA5HFCs"> json still shows lycoris though

This is because the GUI contains all the hidden variables and still stores them in the json file... but they are actually not used. The ones that matter are the values present in the toml that actually get used by sd-scripts.

**Comment by DarkViewAI** [comment]
> > @bmaltais <img alt="ssss" width="736" src="https://private-user-images.githubusercontent.com/159950513/363427787-615ea889-fe48-4b33-8c50-e2e4ba5bf780.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjM3MDUsIm5iZiI6MTcyNTEyMzQwNSwicGF0aCI6Ii8xNTk5NTA1MTMvMzYzNDI3Nzg3LTYxNWVhODg5LWZlNDgtNGIzMy04YzUwLWUyZTRiYTViZjc4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNjU2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzhmYzMzNzdlOWZjZWM2OTczMmNiMjFjNjYxNTJkMjk1NGRiM2VmZjkyYjFjNTM2NmM5NDI1ZGQyZjZhZjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O1-IDNbT_mQMAcQt8QZd6q5vrk0YrxrF4o2iZA5HFCs"> json still shows lycoris though
> 
> This is because the GUI contains all the hidden variables and still stores them in the json file... but they are actually not used. The ones that matter are the values present in the toml that actually get used by sd-scripts.

ahhh perfect thank you for the quick help. I'm wondering if there was a bug ?

on this new commit i tried 3 trainings now, all working perfectly. and then i switched to the one i was using and results are bad again.

**Comment by bmaltais** [comment]
> ahhh perfect thank you for the quick help. I'm wondering if there was a bug ?
> 
> on this new commit i tried 3 trainings now, all working perfectly. and then i switched to the one i was using and results are bad again.

Well, the GUI was processing some of the values... but it should not have been. So I just took them out of the flus network list of possible parameters. This ensure only the ones officially supported by sd-scripts are used.
