### ISSUE TITLE
About ip access

### ISSUE THREAD

**Issue by colaKot** [bmaltais/kohya_ss#276]
I put it on the local server. How can I set up IP access? Rather than through https://huggingface.co/spaces

**Comment by bmaltais** [comment]
You should be able to connect locally to the GUI by connecting to your PC network IP at the port shown in the cli when you start kohya_ss. FOr example, if your PC has a LAN ip of `10.10.10.10` and the GUI return `http://127.0.0.1:7860` then just connect to `http://10.10.10.10:7860`

I never tried it but should work in theory... unless the GUI is only listening for connections from 127.0.0.1. Let me now how it goes.

**Comment by fsegouin** [comment]
@bmaltais @colaKot You need to add this in `kohya_gui.py`:
```
launch_kwargs['server_name'] = '0.0.0.0'
```

**Comment by colaKot** [comment]
> @bmaltais @colaKot You need to add this in `kohya_gui.py`:
> 
> ```
> launch_kwargs['server_name'] = '0.0.0.0'
> ```
Sure enough, thank you!

**Comment by corvec** [comment]
Running `python kohya_gui.py --listen 0.0.0.0` (after activating venv) appears to work as well, without any need to change `kohya_gui.py` itself.
