### ISSUE TITLE
【BUG REPORT】Can not save custom model path after Upgrade

### ISSUE THREAD

**Issue by Rika-Mipa** [bmaltais/kohya_ss#277]
Model Quick Pick → 【Custom】
Select my favourite model → 【Save】
When I open the .json
I need to select the model again

**Comment by bmaltais** [comment]
This is annoying... I will look at it tomorrow...

**Comment by bmaltais** [comment]
Issue should now be fixed in the latest merge in master: d30abe5491bd530794d6ff94c21f203d294b4283
