### ISSUE TITLE
[BUG]Error occurred when using the locon training

### ISSUE THREAD

**Issue by dayuii** [bmaltais/kohya_ss#278]
The cmd console displays these errors:
ModuleNotFoundError: No module named 'locon.locon.locon_kohya'; 'locon.locon' is not a package.
Obviously, there is a problem with module name naming in lora_gui.py

**Comment by bmaltais** [comment]
Let me check... I think the author of LoCon has changed how he distribute his code... and as a result he may have broken how the GUI use it...

**Comment by bmaltais** [comment]
OK, problem solved in 29bb8599bb29de1c122f144b0fe9983d87d056e9
