### ISSUE TITLE
[BUG] Flux Lora training - sample image

### ISSUE THREAD

**Issue by kalle07** [bmaltais/kohya_ss#2781]
seems that if i generate sample images while the training, the lora is **not** used
so it works it generates images with the prompt i wrote but the image always the same if i take the same seed
if i use the lora seperate in compfy or webforge it works

**Comment by TheIronDev** [comment]
I am finding that the Lora is being used for me.

I pulled in the latest code from last night, and saw that the lora is used, but the sample images were not as good as what I saw in ai-toolkit.

If you're like me and used the config that SECourses suggested, the learning rate might be too low. I'm running another test but with a higher learning rate to see if the samples converge faster.

# My Samples Screenshot:


## Epoch #10

![Screenshot 2024-09-05 075518](https://github.com/user-attachments/assets/34abfe1a-698a-4661-a209-8d663a953d54)

## Epoch #200

![Screenshot 2024-09-05 075530](https://github.com/user-attachments/assets/44fc89cc-8875-4a74-a036-71d8938de61e)


Another thought, is maybe Guidance_Scale is off? I didn't see a setting in Kohya..
