### ISSUE TITLE
Model is not found as a file or in Hugging Face, perhaps file name is wrong? / Local variable 'Pipe' referenced before assignment

### ISSUE THREAD

**Issue by Dhevenddra** [bmaltais/kohya_ss#279]
Can anyone tell me what's being done wrong?

**warnings.warn(
model is not found as a file or in Hugging Face, perhaps file name is wrong? / 指定したモデル名のファイル、またはHugging Faceのモデルが見つかりません。ファイル名が誤っているかもしれません: runwayml/stable-diffusion-v1-5**
Traceback (most recent call last):
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\train_network.py", line 96, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\library\train_util.py", line 2709, in load_target_model
    text_encoder = pipe.text_encoder
**UnboundLocalError: local variable 'pipe' referenced before assignment**
Traceback (most recent call last):
  File "C:\Users\dhev0\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\dhev0\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\dhev0\OneDrive\Documents\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by hjmhjms** [comment]
the same error

**Comment by bmaltais** [comment]
Never had this error. Did it sudenly started to show up? Did it ever worked for you?

**Comment by Dhevenddra** [comment]
I ran it for the first time , files were being downloaded but it was stopped due to my internet. Later i tried to run the training again and this shows up every time.

**Comment by awcolo1** [comment]
I had the same error, I was able to work around it by manually downloading the model from https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main and then specifying the location in Pretrained model name or path with the local path and filename to the file I downloaded. In this case I just reused the already downloaded model I used in automatic1111 webui.

If you are using a json file to load the settings, you can save it under a new name.  This doesn't resolve the original download problem but it will get you working again.

![image](https://user-images.githubusercontent.com/99512722/222815072-6fb4c25e-4420-4270-b84c-a4357bb1d456.png)

**Comment by Dhevenddra** [comment]
I tried it and ended up with Cuda out of memory error.
Do you know how to resolve cuda out of memory error. I can't find a solution for it.

**Comment by danielpdykes** [comment]
@Dhevenddra check the video at https://www.youtube.com/watch?v=70H03cv57-o for a JSON download (it's in the description) of recommended settings for lower memory training.

**Comment by WiltAndBlush** [comment]
I got the answer, did you put your training model in "sd-models" file?
![Snipaste_2023-03-07_13-42-25](https://user-images.githubusercontent.com/50993837/223331000-dab97e6d-93e2-4f9d-8b76-815acf1a7caf.png)
![Snipaste_2023-03-07_13-42-44](https://user-images.githubusercontent.com/50993837/223331017-738fbd09-c695-48eb-8bcb-f3bdb5207764.png)

**Comment by oiuv** [comment]
> I had the same error, I was able to work around it by manually downloading the model from https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main and then specifying the location in Pretrained model name or path with the local path and filename to the file I downloaded. In this case I just reused the already downloaded model I used in a1111 webui.
> 
> If you are using a json file to load the settings, you can save it under a new name. This doesn't resolve the original download problem but it will get you working again.
> 
> ![image](https://user-images.githubusercontent.com/99512722/222815072-6fb4c25e-4420-4270-b84c-a4357bb1d456.png)

good job

**Comment by sledgehkg** [comment]
I'm getting the same problem. I'm directing Kohya to the directory where my model is, but it still tells me model is not found as a file or in Hugging Face, perhaps file name is wrong?

**Comment by sledgehkg** [comment]
Don't know if this helps, but make sure you have the file type at the end of your model name, IE '.safetensors' or, 'ckpt'
