### ISSUE TITLE
New Installation Promlem

### ISSUE THREAD

**Issue by chnisar515** [bmaltais/kohya_ss#2799]
Hello Experts,
i am trying to install Kohya first time on my windows 11 so i already have installed python 3.11.9, already installed CUDA 11.8 toolkit and Visual Studio 2015, 2017, 2019, and 2022 redistributable so now when i clone Kohya_ss repository and enter the folder kohya_ss and try to run the command (.\setup-3.10.bat) then i got this

Kohya_ss setup menu:

1. Install kohya_ss GUI
2. (Optional) Install CuDNN files (to use the latest supported CuDNN version)
3. (DANGER) Install Triton 2.1.0 for Windows... only do it if you know you need it... might break training...
4. (Optional) Install specific version of bitsandbytes
5. (Optional) Manually configure Accelerate
6. (Optional) Launch Kohya_ss GUI in browser
7. Exit Setup

then i selected Option 1 and then i got this error which is below.

Select an option: 1

13:57:08-714662 INFO     Kohya_ss GUI version: v24.1.7
13:57:08-720664 INFO     Python version is 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit
                         (AMD64)]
13:57:08-722667 ERROR    The current version of python (sys.version_info(major=3, minor=11, micro=9,
                         releaselevel='final', serial=0)) is not appropriate to run Kohya_ss GUI
13:57:08-723667 ERROR    The python version needs to be greater or equal to 3.10.9 and less than 3.11.0
The system cannot find the path specified.

can someone tell me where i am going wrong?

**Comment by nokeyfan** [comment]
You have a newer python version 3.11.9, kohya lora runs on 3.10.11. you can  install 3.10.11 and use the install command like in the documentation:  For systems with only more than one python release installed: .\setup-3.10.bat

**Comment by chnisar515** [comment]
Installed with help of Anaconda. thank you for your reply.

**Comment by azamet90** [comment]
> Installed with help of Anaconda. thank you for your reply.

Kohya_ss setup menu:

1. Install kohya_ss GUI
2. (Optional) Install CuDNN files (to use the latest supported CuDNN version)
3. (DANGER) Install Triton 2.1.0 for Windows... only do it if you know you need it... might break training...
4. (Optional) Install specific version of bitsandbytes
5. (Optional) Manually configure Accelerate
6. (Optional) Launch Kohya_ss GUI in browser
7. Exit Setup

Select an option: 1

00:01:16-897216 INFO     Kohya_ss GUI version: v24.1.7
00:01:16-903724 INFO     Python version is 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
00:01:16-904722 ERROR    The current version of python (sys.version_info(major=3, minor=11, micro=0,
                         releaselevel='final', serial=0)) is not appropriate to run Kohya_ss GUI
00:01:16-905724 ERROR    The python version needs to be greater or equal to 3.10.9 and less than 3.11.0


i have tryed the version of python but still i get this error?
