### ISSUE TITLE
HELP -  bitsandbytes.optim.adamw.AdamW8bit(weight_decay=0.01,eps=1e-08,betas=(0.9, 0.999))

### ISSUE THREAD

**Issue by MIKETUFFIN66** [bmaltais/kohya_ss#2811]
![image](https://github.com/user-attachments/assets/f7ef70bf-558c-4d9b-841e-509731c1adb9)

how to get this in my lora training 
bitsandbytes.optim.adamw.AdamW8bit(weight_decay=0.01,eps=1e-08,betas=(0.9, 0.999)) ?

what am i suppose to write to get it in the KOHYA optimizer ?

thanks in advance

**Comment by MIKETUFFIN66** [comment]
More details when i put this arg : 

![Screenshot 2024-09-14 012603](https://github.com/user-attachments/assets/ce6ea395-0c7d-40f7-bba4-346219dbd09e)

i get this : 

![Screenshot 2024-09-14 012626](https://github.com/user-attachments/assets/2116e027-d140-4f1c-ba1d-be315082b76a)


please tell me what is wrong ?
thanks

**Comment by iamrohitanshu** [comment]
@MIKETUFFIN66 Don't put commas between the arguments, separate them by a space.
Try this `weight_decay=0.01 eps=1e-08 betas=(0.9, 0.999)`

**Comment by MIKETUFFIN66** [comment]
> @MIKETUFFIN66 Don't put commas between the arguments, separate them by a space. Try this `weight_decay=0.01 eps=1e-08 betas=(0.9, 0.999)`

![1111](https://github.com/user-attachments/assets/4a7be1a4-89b6-440b-80d8-ecd5390970f7)


still same thing i tried it ..

**Comment by iamrohitanshu** [comment]
try removing remove the space between `0.9,` and `0.999`

**Comment by MIKETUFFIN66** [comment]
> try removing remove the space between `0.9,` and `0.999`
> 
> Just to be clear, I don't use these arguments with AdamW8bit, so I don't know if they're valid or not. Prodigy uses something similar, so I'm basing my answer based off of that.

Thanks , it worked now ... weight_decay=0.01 eps=1e-08 betas=(0.9,0.999) without space ... 
thanks again
