### ISSUE TITLE
Training gives no errors but also no difference.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [bmaltais/kohya_ss#282]
Trained with images following this guide from the internet: 

https://www.youtube.com/watch?v=70H03cv57-o
Followed every instruction to the letter, doing nothing else. Loaded the end result into SD and it's the same as the SD1.5 checkpoint it is based on; it is not trained on the item of clothing.

Only difference is rather than training it on a character I am training it on clothing. What to do? Again, there are not any errors other than this guy says the training only takes him 6 minutes but for me (and on 100 images) it took about 2 hours on a 3070.

**Comment by bmaltais** [comment]
Did you use the built-in LoRA support in Auto1111 to reference the LoRA? Did you add the trigger word(s) to the prompt?

**Comment by bmaltais** [comment]
Are you using the latest release of auto1111? Have you done a `git pull` recently?

**Comment by TheBitcoinBaron** [comment]
About half an hour ago , it does that code every time it starts up. Although I couldn't confirm the version number because I can't see it in the webUI anywhere.
