### ISSUE TITLE
console Log INFO always shows filepath

### ISSUE THREAD

**Issue by harahara777** [bmaltais/kohya_ss#2822]
Running on Paperspace
It works normally, but after the GUI renewal, the file path is attached to the INFO of the console log, making it very difficult to read.
installed the necessary packages from requirements after git clone, without going through the normal installation procedure.
where should i setting for this?
console log example as bellow
</br>
gradient accumulation steps / 勾配を合計するステップ数 = 1
total optimization steps / 学習ステップ数: 1600
steps:   0%|                                           | 0/1600 [00:00<?, ?it/s]
epoch 1/229
2024-09-14 17:15:50 INFO     epoch is incremented.             ]8;id=650746;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py\train_util.py]8;;\:]8;id=106430;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py#703\703]8;;\
                             current_epoch: 0, epoch: 1                         
steps:   0%|                  | 4/1600 [00:05<34:28,  1.30s/it, avr_loss=0.0185]^C

**Comment by bmaltais** [comment]
Good question… I am not sure why this suddenly changed. Must be due to a module update. I will try to fing why this is happening…

**Comment by harahara777** [comment]
For me, some INFO timestamps only display the time and are working properly. 
The buggy INFO is include date in the timestamp, and in that case, the file path is also attached.

> 19:53:00-589745 INFO     Loading config...                                      
> 19:53:01-700511 INFO     Start training LoRA Standard ...
> 19:53:01-742472 INFO     Command executed.
> 2024-09-14 19:53:07 INFO     Loading settings from            ]8;id=296166;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py\train_util.py]8;;\:]8;id=611504;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py#3744\3744]8;;\
>                              /notebooks/train/output/config_l                   
>                              ora-20240914-195301.toml...                        
>                     INFO     /notebooks/train/output/config_l ]8;id=593832;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py\train_util.py]8;;\:]8;id=326384;file:///notebooks/kohya_ss/sd-scripts/library/train_util.py#3763\3763]8;;\
>                              ora-20240914-195301

**Comment by bmaltais** [comment]
I think those are coming from the sd-scripts from kohya... I can't really fix those...

**Comment by harahara777** [comment]
rich and logging updates do indeed seem to come from sd-script.
I'll try it some more and ask over there, thanks.
