### ISSUE TITLE
Extract Flux LoRA feature is not working

### ISSUE THREAD

**Issue by RayHell** [bmaltais/kohya_ss#2836]
Myself and others tried this feature with a finetuned model and the extracted Lora is not working. The finetuned model produce the right output of the trained person in that case. But here no difference in the output if I use the extracted Lora is there vs not.

**Comment by bmaltais** [comment]
Please report this to kohya on his sd-scripts repo. I do not maintain the sd-scripts used by the GUI. He would be the one that need to look into this issue.
