### ISSUE TITLE
Loaded the config file, but the parameters and args remain the same

### ISSUE THREAD

**Issue by RaySteve312** [bmaltais/kohya_ss#2845]
![屏幕截图 2024-09-21 194445](https://github.com/user-attachments/assets/dec1092d-8ed3-42a5-99b6-7ec70146abe3)
I run the GUI on a cloud computing platform. 
when I load the config file, the parameters and args remain the same. I can save the parameters to a new config file, but can not load any.

**Comment by RaySteve312** [comment]
my bad ,I load configs in the parameters, it works

**Comment by murmurelo111** [comment]
hello!  I encounter the same problem, could you explain in detail how to fix it? Thank you very much
