### ISSUE TITLE
Network parameters missing

### ISSUE THREAD

**Issue by lynrayy** [bmaltais/kohya_ss#2853]
Why i have no network parameters? Rank and others
UI in google colab was also better!

**Comment by lynrayy** [comment]
![image](https://github.com/user-attachments/assets/bef4994e-4ceb-4d48-b092-1f72e03285be)

**Comment by lynrayy** [comment]
I need this one, why i don't have thoose?
![image](https://github.com/user-attachments/assets/d63fe717-8ea2-4fab-814d-7e05f1bffccd)

**Comment by b-fission** [comment]
Network Rank and Alpha are on the Lora tab. Make sure you're not on the Dreambooth tab which is opened by default.

**Comment by lynrayy** [comment]
Yeah, I was on a different tab. It's not very noticeable in this interface, I don't know why. I figured it out right away in the google colab interface.
