### ISSUE TITLE
LoRA Training fails with ponyDiffusionV6XL Model

### ISSUE THREAD

**Issue by samuelkurt** [bmaltais/kohya_ss#2855]
I recently switched from an gtx 1060 to an rtx 3060, for more VRam. I tried to Train a LoRA with 30 Images and the ponyDiffusionV6XL Model, but it fails to even Start. It is fine with other Models. Can anyone help.
I've attached the Log.

[Log.txt](https://github.com/user-attachments/files/17136882/Log.txt)

**Comment by b-fission** [comment]
Pony is still technically SDXL, so make sure the SDXL checkbox is enabled when you choose the model.

**Comment by samuelkurt** [comment]
Thanks, that totally fixed it.
