### ISSUE TITLE
Flux Dreambooth training broke sometime after commit sd3-flux.1 95bf7ff29cade27108a55c49f36f360c7449cde0

### ISSUE THREAD

**Issue by mostlyhuman** [bmaltais/kohya_ss#2871]
If I roll back to 95bf7ff29cade27108a55c49f36f360c7449cde0 it works fine.  I didn't have a chance to test which of the 6 commits after 95bf7ff is where it actually stopped working. Just let me know if you need any info.

**Comment by pAInCREAT0R** [comment]
I was resuming a saved config and had issues as well.  For me the issue was I was using "Double Blocks to Swap".  It looks like now you need to turn that off and just use the "Blocks to Swap" entry.  This allowed my training to run again without OOM errors on the latest commit.

**Comment by mostlyhuman** [comment]
Oh nice! okay thanks, do you know if multi GPU is working yet?  I have a 4090 and 3090 and tried last week and couldnt get it working.

**Comment by pAInCREAT0R** [comment]
I only have one GPU so I do not know.  I have long debated adding my old 1080TI into my current rig, but not convinced the lift is worth it.  (Also, a little concerned if my power supply can maintain it.)

**Comment by mostlyhuman** [comment]
ahh okay, thanks man!

**Comment by mostlyhuman** [comment]
> I was resuming a saved config and had issues as well. For me the issue was I was using "Double Blocks to Swap". It looks like now you need to turn that off and just use the "Blocks to Swap" entry. This allowed my training to run again without OOM errors on the latest commit.

Hey man, I was giving this another shot and for the life of me couldnt find these options you referenced for Double Blocks to Swap and Blocks to Swap.  Where are these located?  Thank you for your time I sincerely appreciate it!

**Comment by pAInCREAT0R** [comment]
They are at the bottom of the Flux.1 specific options. Which resides under the parameters for me.
