### ISSUE TITLE
--help is ignored when --inbrowser used - I want to prevent requirements check

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2883]
I want to prevent requirements check but when called like this only --inbrowser is used

gui.bat --inbrowser --help

@bmaltais

**Comment by bmaltais** [comment]
--help can only be used alone. It will not provide contextualized help.

**Comment by FurkanGozukara** [comment]
> --help can only be used alone. It will not provide contextualized help.

the aim is skipping verification so not possible? perhaps you can add special option for this to gui.bat?

**Comment by bmaltais** [comment]
Not at the moment... But it could be added.

**Comment by bmaltais** [comment]
The sd3-flux.1 branch now support `--noverify` as an option to skip requirements validation.

**Comment by FurkanGozukara** [comment]
> The sd3-flux.1 branch now support `--noverify` as an option to skip requirements validation.

awesome thank you so much

this is useful because i make people to install torch 2.5, brings huge speed boost

**Comment by FurkanGozukara** [comment]
@bmaltais thank you so much
