### ISSUE TITLE
【BUG REPORT】Still Can Not Save Train Model Path !

### ISSUE THREAD

**Issue by Rika-Mipa** [bmaltais/kohya_ss#290]
I delete the old json and create a new one from the begining.
However, when I load the json, the path blank showes [custom] instead of the correct path.
When I press [open] button and close it immediately (I don't select the model), repeat this action severl times, then the direct path will appear automatically (even I don‘t select at all, I just press [open] buttton several times).
It's really strange, please check it again.

**Comment by bmaltais** [comment]
Have you pulled the latest code from the repo? Let me try it on my side... did I forget to merge dev into master...

**Comment by bmaltais** [comment]
OK, I updated the code... I hope this does it thistime. Work fine on my system...

**Comment by Rika-Mipa** [comment]
> OK, I updated the code... I hope this does it this time. Work fine on my system...

OK, the save option works very well now. Thanks for replying and wish you have a good day XD
