### ISSUE TITLE
Urgent fix needed ImportError: cannot import name 'cached_download' from 'huggingface_hub'

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2908]
Hugging face hub has to be 0.25.2 or doesnt work

man these errors always happens to me when recording a tutorial video

@kohya-ss @bmaltais 

![image](https://github.com/user-attachments/assets/ecdaf9cc-9771-4c9f-905b-6f52de60857a)

**Comment by hit-xpf** [comment]
choose a lower version
：  huggingface-hub==0.21.4

**Comment by FurkanGozukara** [comment]
@hit-xpf i already written  0.25.2 works but this needs to be fixed many people dont know how to do

and 21 wont work it is gradio 5 now

**Comment by qqizhao** [comment]
> choose a lower version 选择较低版本 ： huggingface_hub==0.21.4： huggingface_hub==0.21.4

useful, thank you.
