### ISSUE TITLE
Resume for textual inversion broken because of typo

### ISSUE THREAD

**Issue by tvvf** [bmaltais/kohya_ss#2925]
The option '_Resume TI training (Optional. Path to existing TI embedding file to keep training)_' is currently not working, training will just start from scratch. 
'_Print training command_' shows that the correct file will be handed over but via the wrong parameter `weigts = "C:/AI/training/.../mySnapshotName.safetensors"`. This needs to be `weights = ...`.

Correcting the spelling in https://github.com/bmaltais/kohya_ss/blob/e5e8be05fe0475a04e61ef668afffc632aa178f5/kohya_gui/textual_inversion_gui.py#L866 to `"weights": weights,` fixes the issue.

Console output of the training script now correctly contains the line `weighs loaded` (with its own [typo](https://github.com/kohya-ss/sd-scripts/blob/56b4ea963ee745b73be1ad53c602854e3ff7ed16/train_textual_inversion.py#L268) in the message) and the training resume the training from the chosen embedding.

(Additional small hickup for this use case: the file picker for this functionality by default filters for `.json` files, not `.safetensor`)

**Comment by bmaltais** [comment]
Should be fixed in the sd3-flux.1 branch. Thank you for reporting the typo.
