### ISSUE TITLE
Requirements linux broken very urgent fix needed

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2929]
Happened after very recent updates @bmaltais 

sd3-flux.1 branch

i predict related to setup_common py but not sure

how we run is as in instructions

```
source venv/bin/activate

./setup.sh
```

e.g. this commit working : `c258fc1421c577e2097c3fca5eb0763902104d93`

![image](https://github.com/user-attachments/assets/d5cb5c15-3fd0-4d31-9ea8-046d2cb89cf6)

**Comment by bmaltais** [comment]
Fixed.

**Comment by FurkanGozukara** [comment]
@bmaltais thank you so much
