### ISSUE TITLE
We are missing save_last_n_epochs  in the GUI

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2938]
All I see is this option which I believe it saves training state not checkpoints

https://github.com/kohya-ss/sd-scripts/issues/1738

Thank you @bmaltais 

![image](https://github.com/user-attachments/assets/ec366c4d-f939-4896-8d0a-e84286b895bd)

**Comment by bmaltais** [comment]
Added support for it in the last commit.

**Comment by FurkanGozukara** [comment]
> Added support for it in the last commit.

awesome ty so much
