### ISSUE TITLE
Install logs causes Kaggle to get broken so many lines printed

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#2955]
I am trying to install sd3-flux.1 on Kaggle and since it prints literally 10s of 1000s of lines browser freezes

How can i restrict it to display only and or errors or i dont know how can we fix?

How I install as simple as like this

@bmaltais thank you so much

```
!git clone https://github.com/bmaltais/kohya_ss.git

%cd /kaggle/working/kohya_ss

!git checkout sd3-flux.1

!./setup.sh -n
```

![image](https://github.com/user-attachments/assets/4d551496-af67-4c67-9d43-41ddb52ea4a8)

**Comment by bmaltais** [comment]
Hummm... this is the typical output of pip... I could try to hide stuff... but ultimatly why are those lines an actual problem? Do they really need to be hidden?

**Comment by FurkanGozukara** [comment]
> Hummm... this is the typical output of pip... I could try to hide stuff... but ultimatly why are those lines an actual problem? Do they really need to be hidden?

because it is too many not like installing on windows

let me show what i mean

[logs.txt](https://github.com/user-attachments/files/17663947/logs.txt)

**Comment by bmaltais** [comment]
-q (quiet) option added to setup.sh
