### ISSUE TITLE
Fix dependencies for linux  in sd3-flux.1 and sd3-sd3.5-flux branches

### ISSUE THREAD

**Issue by Koudkunstje** [bmaltais/kohya_ss#2959]
When I checkout to sd3-flux.1 or the sd3-sd3.5-flux branch while I'm on linux as soon as I start the app, it's reverting everything back to the  dependencies from the requirements_windows.txt file. This can't be right is it? 

This is not happening when I checkout to master.

**Comment by bmaltais** [comment]
Hummm... let me check what is going on... should not do that...

**Comment by bmaltais** [comment]
I ran `./gui.sh` in my WSL2 env and all was good... how do you run it? Unless I can reproduce the but it is hard to fix.

**Comment by Koudkunstje** [comment]
Not running linux on wsl btw. And default the system is running cuda12.4
with cudnn 8.9 i believe... Not at home at the moment. So, i can't double
check.

**Comment by Koudkunstje** [comment]
And it also does this when installed the regular way through a python env.
I think it's more like native linux vs. Linux through wsl. Installing as
discribed on main page with setup.sh it installs with requirents_linux.txt
but when it starts  kohya then it reverts back to. requirements_windows.txt

**Comment by iqddd** [comment]
I keep reinstating the library package from version 0.0.0 to version 0.0.0 each time I run the GUI.
```
20:08:29-974032 INFO     Installing collected packages: library
20:08:29-976530 INFO     Attempting uninstall: library
20:08:29-978686 INFO     Found existing installation: library 0.0.0
20:08:29-981107 INFO     Uninstalling library-0.0.0:
20:08:31-747685 INFO     Successfully uninstalled library-0.0.0
20:08:31-750356 INFO     Running setup.py develop for library
20:08:32-224841 INFO     Successfully installed library-0.0.0
```
It's not take a long time, but it's still weird.

**Comment by bmaltais** [comment]
Look at gui.sh. you need to specify the requirements file to use when you call kohya_gui.py directly. This is why it install the windows requirements as in the absence of the file to use it will default to windows.

**Comment by iqddd** [comment]
> Look at gui.sh. you need to specify the requirements file to use when you call kohya_gui.py directly. This is why it install the windows requirements as in the absence of the file to use it will default to windows.

No.
```
22:52:35-895783 INFO     Kohya_ss GUI version: v24.2.0

22:52:35-974401 INFO     Submodule initialized and updated.
22:52:35-976212 INFO     nVidia toolkit detected
22:52:37-349015 INFO     Torch 2.5.0+cu124
22:52:37-394326 INFO     Torch backend: nVidia CUDA 12.4 cuDNN 90100
22:52:37-413517 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24154MB Arch 8.6 Cores 82
22:52:37-414693 INFO     Python version is 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
22:52:37-415911 INFO     Installing/Validating requirements from /home/user/kohya_ss/requirements_linux.txt...
22:52:38-066835 INFO     Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu124
22:52:38-068235 INFO     Obtaining file:///home/user/kohya_ss/sd-scripts (from -r /home/user/kohya_ss/requirements.txt
                         (line 37))
22:52:38-069427 INFO     Preparing metadata (setup.py): started
22:52:38-287728 INFO     Preparing metadata (setup.py): finished with status 'done'
22:52:41-376479 INFO     Installing collected packages: library
22:52:41-378972 INFO     Attempting uninstall: library
22:52:41-381191 INFO     Found existing installation: library 0.0.0
22:52:41-383591 INFO     Uninstalling library-0.0.0:
22:52:43-028293 INFO     Successfully uninstalled library-0.0.0
22:52:43-030942 INFO     Running setup.py develop for library
22:52:43-549845 INFO     Successfully installed library-0.0.0
22:52:44-232284 INFO     headless: False
22:52:44-240039 INFO     Using shell=True when running external commands...
```
executing environment is detected correctly.

**Comment by bmaltais** [comment]
try: `kohya_gui.py --requirements=requirements_linux.txt`

**Comment by Koudkunstje** [comment]
Yes, it kinda works. 

2024-11-12 02:14:19.481892: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-11-12 02:14:19.481921: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-11-12 02:14:19.481948: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-12 02:14:19.487396: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-12 02:14:20.090471: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
02:14:22-877933 INFO     Kohya_ss GUI version: v24.2.0                                                 
                                                                                                       
02:14:22-898205 INFO     Submodule initialized and updated.                                            
02:14:22-899110 INFO     nVidia toolkit detected                                                       
02:14:23-875328 INFO     Torch 2.5.0+cu118                                                             
02:14:23-948297 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 90100                                   
02:14:23-977535 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 Ti VRAM 24135MB Arch 8.6 Cores 84 
02:14:23-978462 INFO     Python version is 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]          
02:14:23-979287 INFO     Installing/Validating requirements from requirements_linux.txt...             
02:14:24-262903 INFO     Looking in indexes: https://pypi.org/simple,                                  
                         https://download.pytorch.org/whl/cu118                                        
02:14:24-263759 INFO     Obtaining file:///media/roelof/Github/kohya_ss/sd-scripts (from -r            
                         requirements.txt (line 37))                                                   
02:14:24-264520 INFO     Preparing metadata (setup.py): started                                        
02:14:24-411319 INFO     Preparing metadata (setup.py): finished with status 'done'                    
02:14:25-187516 INFO     Installing collected packages: library                                        
02:14:25-188269 INFO     Attempting uninstall: library                                                 
02:14:25-188892 INFO     Found existing installation: library 0.0.0                                    
02:14:25-189541 INFO     Uninstalling library-0.0.0:                                                   
02:14:25-461667 INFO     Successfully uninstalled library-0.0.0                                        
02:14:25-462660 INFO     Running setup.py develop for library                                          
02:14:25-751405 INFO     Successfully installed library                                                
02:14:26-082649 INFO     headless: False                                                               
02:14:26-085627 INFO     Using shell=True when running external commands...                            
* Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


Now I've got to figure out the last known tensorflow (with gpu support) , pytorch and cuda  thing.  Would be nice if they released a pytorch with cu125 support.  Then I could run tensorflow 2.18.0 .

If i'm right the last know good  setup with gpu support is  tensorflow 2.14 with cuda 11.8  and  cudnn 8.7 and pytorch 2.5.0

**Comment by iqddd** [comment]
> Yes, it kinda works.
> 
> 2024-11-12 02:14:19.481892: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered 2024-11-12 02:14:19.481921: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered 2024-11-12 02:14:19.481948: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered 2024-11-12 02:14:19.487396: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. 2024-11-12 02:14:20.090471: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT 02:14:22-877933 INFO Kohya_ss GUI version: v24.2.0
> 
> 02:14:22-898205 INFO Submodule initialized and updated. 02:14:22-899110 INFO nVidia toolkit detected 02:14:23-875328 INFO Torch 2.5.0+cu118 02:14:23-948297 INFO Torch backend: nVidia CUDA 11.8 cuDNN 90100 02:14:23-977535 INFO Torch detected GPU: NVIDIA GeForce RTX 3090 Ti VRAM 24135MB Arch 8.6 Cores 84 02:14:23-978462 INFO Python version is 3.10.15 (main, Oct 3 2024, 07:27:34) [GCC 11.2.0] 02:14:23-979287 INFO Installing/Validating requirements from requirements_linux.txt... 02:14:24-262903 INFO Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118 02:14:24-263759 INFO Obtaining file:///media/roelof/Github/kohya_ss/sd-scripts (from -r requirements.txt (line 37)) 02:14:24-264520 INFO Preparing metadata (setup.py): started 02:14:24-411319 INFO Preparing metadata (setup.py): finished with status 'done' 02:14:25-187516 INFO Installing collected packages: library 02:14:25-188269 INFO Attempting uninstall: library 02:14:25-188892 INFO Found existing installation: library 0.0.0 02:14:25-189541 INFO Uninstalling library-0.0.0: 02:14:25-461667 INFO Successfully uninstalled library-0.0.0 02:14:25-462660 INFO Running setup.py develop for library 02:14:25-751405 INFO Successfully installed library 02:14:26-082649 INFO headless: False 02:14:26-085627 INFO Using shell=True when running external commands...
> 
> * Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> 
> Now I've got to figure out the last known tensorflow (with gpu support) , pytorch and cuda thing. Would be nice if they released a pytorch with cu125 support. Then I could run tensorflow 2.18.0 .
> 
> If i'm right the last know good setup with gpu support is tensorflow 2.14 with cuda 11.8 and cudnn 8.7 and pytorch 2.5.0

Your console output shows that the script reinstalled the 'library' package (whatever that is) from version 0.0.0 to version 0.0.0.

**Comment by bmaltais** [comment]
> Your console output shows that the script reinstalled the 'library' package (whatever that is) from version 0.0.0 to version 0.0.0.

This is normal unfortunately. It result in sd-scripts using a non versioned and deprecated setup script for the library...

**Comment by bmaltais** [comment]
> Your console output shows that the script reinstalled the 'library' package (whatever that is) from version 0.0.0 to version 0.0.0.

This is normal unfortunately. It result in sd-scripts using a non versioned and deprecated setup script for the library...
