### ISSUE TITLE
Configs that specify custom `pretrained_model_name_or_path` saved before #292 fail to load

### ISSUE THREAD

**Issue by evanjs** [bmaltais/kohya_ss#296]
If a user attempts to load a config saved before #292 (?) and they have a custom model selected for `Pretrained model name or path`, Gradio chokes upon trying to load the config, and endlessly prints the following error.
<details>
<summary>Error from Gradio</summary>

```
Traceback (most recent call last):
  File "...\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "...\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1027, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "...\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 939, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
TypeError: 'NoneType' object is not subscriptable
```
</details>

It seems like we don't handle older configs properly, and the `model`'s value `[]` is passed as is.
Manually updating old configs to specify `"custom"` instead of `[]` seems to work fine.
```diff
- "model_list": [],
+ "model_list": "custom",
```

This seemed to be the only change I needed to make to get things working again.
The lack of a value for `LoRA_type` did not seem to cause any issues.

**Comment by DocShotgun** [comment]
Thanks, fixed it for me lol. Been getting that error on every config load for the past few pulls. Interestingly enough I found that if I just loaded the same config a 2nd time file, it would let me proceed without error.

**Comment by bmaltais** [comment]
Dang... I need to check if I can catch that and properly handle it... Ok, let me look at the code...

**Comment by bmaltais** [comment]
OK,,, this commit should fix the issue. Sorery about that: e93de7f8ea3569200dcf7faddc77e08ea36f40df

**Comment by evanjs** [comment]
Opening old configs now works as intended, and saving sets the `model_list` value to `custom`, which adheres to the new format.

Thank you!
