### ISSUE TITLE
loss=nan issue

### ISSUE THREAD

**Issue by specblades** [bmaltais/kohya_ss#301]
I didn't change anything (i hope), but loss is nan now. No errors. Dont know why.

Using bucketing, grad_accum, the rest is default

<img width="315" alt="image" src="https://user-images.githubusercontent.com/113993746/222936217-9b3d18d9-a64b-42fc-8888-8c6b16f5741c.png">

**Comment by cooperdk** [comment]
@bmaltais please let us know what you're doing about issues!!!
I have this now.
