### ISSUE TITLE
I was doing flux finetune, training based on flux1.dev base model, and then encountered time_embed.0.weight when extract lora.

### ISSUE THREAD

**Issue by hotdogarea** [bmaltais/kohya_ss#3012]
the base model is always flux1.dev

Dec 12 11:46:17 xb2-9992 gui.sh[936]: 11:46:17-686230 INFO     Executing command: /root/kohya_ss/venv/bin/python
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          /root/kohya_ss/sd-scripts/networks/extract_lora_from_mo
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          dels.py --load_precision float --save_precision float
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          --save_to /root/kohya_ss/outputs/lora.safetensors
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          --model_org
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          /mnt/pub_storage/aigc_models/MumuxiTools/SimpleAI/Simpl
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          eModels/checkpoints/flux1-dev.safetensors --model_tuned
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          /root/kohya_ss/outputs/model/xiaoyizi1212-000100.safete
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          nsors --dim 128 --device cuda --clamp_quantile 1
Dec 12 11:46:17 xb2-9992 gui.sh[936]:                          --min_diff 0.01 --conv_dim 128
Dec 12 11:46:19 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
Dec 12 11:46:19 xb2-9992 gui.sh[145413]:   torch.utils._pytree._register_pytree_node(
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
Dec 12 11:46:20 xb2-9992 gui.sh[145413]:   torch.utils._pytree._register_pytree_node(
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
Dec 12 11:46:20 xb2-9992 gui.sh[145413]:   torch.utils._pytree._register_pytree_node(
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.968903: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.968963: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.969994: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.976099: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
Dec 12 11:46:20 xb2-9992 gui.sh[145413]: To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Dec 12 11:46:21 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:21.697124: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Dec 12 11:46:22 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:   torch.utils._pytree._register_pytree_node(
Dec 12 11:46:22 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:22 INFO     loading original SD  extract_lora_from_models.py:72
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              model :
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              /mnt/pub_storage/aig
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              c_models/MumuxiTools
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              /SimpleAI/SimpleMode
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              ls/checkpoints/flux1
Dec 12 11:46:22 xb2-9992 gui.sh[145413]:                              -dev.safetensors
Dec 12 11:46:27 xb2-9992 gui.sh[145413]: Traceback (most recent call last):
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:   File "/root/kohya_ss/sd-scripts/networks/extract_lora_from_models.py", line 360, in <module>
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:     svd(**vars(args))
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:   File "/root/kohya_ss/sd-scripts/networks/extract_lora_from_models.py", line 73, in svd
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:     text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(v2, model_org)
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:   File "/root/kohya_ss/sd-scripts/library/model_util.py", line 1005, in load_models_from_stable_diffusion_checkpoint
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:     converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:   File "/root/kohya_ss/sd-scripts/library/model_util.py", line 267, in convert_ldm_unet_checkpoint
Dec 12 11:46:27 xb2-9992 gui.sh[145413]:     new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
Dec 12 11:46:27 xb2-9992 gui.sh[145413]: KeyError: 'time_embed.0.weight'

我训练时的参数为
![image](https://github.com/user-attachments/assets/ed5013e8-e4c9-4891-8a51-4a5e3dcf233f)
![image](https://github.com/user-attachments/assets/0e1d583c-4b93-4ff4-b690-b6b289f5d559)

**Comment by hotdogarea** [comment]
I am using the training branch of flux. Is it true that the extract lora here does not support flux?

**Comment by Nomination-NRB** [comment]
> the base model is always flux1.dev
> 
> Dec 12 11:46:17 xb2-9992 gui.sh[936]: 11:46:17-686230 INFO Executing command: /root/kohya_ss/venv/bin/python Dec 12 11:46:17 xb2-9992 gui.sh[936]: /root/kohya_ss/sd-scripts/networks/extract_lora_from_mo Dec 12 11:46:17 xb2-9992 gui.sh[936]: dels.py --load_precision float --save_precision float Dec 12 11:46:17 xb2-9992 gui.sh[936]: --save_to /root/kohya_ss/outputs/lora.safetensors Dec 12 11:46:17 xb2-9992 gui.sh[936]: --model_org Dec 12 11:46:17 xb2-9992 gui.sh[936]: /mnt/pub_storage/aigc_models/MumuxiTools/SimpleAI/Simpl Dec 12 11:46:17 xb2-9992 gui.sh[936]: eModels/checkpoints/flux1-dev.safetensors --model_tuned Dec 12 11:46:17 xb2-9992 gui.sh[936]: /root/kohya_ss/outputs/model/xiaoyizi1212-000100.safete Dec 12 11:46:17 xb2-9992 gui.sh[936]: nsors --dim 128 --device cuda --clamp_quantile 1 Dec 12 11:46:17 xb2-9992 gui.sh[936]: --min_diff 0.01 --conv_dim 128 Dec 12 11:46:19 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead. Dec 12 11:46:19 xb2-9992 gui.sh[145413]: torch.utils._pytree._register_pytree_node( Dec 12 11:46:20 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead. Dec 12 11:46:20 xb2-9992 gui.sh[145413]: torch.utils._pytree._register_pytree_node( Dec 12 11:46:20 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead. Dec 12 11:46:20 xb2-9992 gui.sh[145413]: torch.utils._pytree._register_pytree_node( Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.968903: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.968963: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.969994: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered Dec 12 11:46:20 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:20.976099: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. Dec 12 11:46:20 xb2-9992 gui.sh[145413]: To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags. Dec 12 11:46:21 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:21.697124: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT Dec 12 11:46:22 xb2-9992 gui.sh[145413]: /root/kohya_ss/venv/lib/python3.10/site-packages/diffusers/utils/outputs.py:63: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead. Dec 12 11:46:22 xb2-9992 gui.sh[145413]: torch.utils._pytree._register_pytree_node( Dec 12 11:46:22 xb2-9992 gui.sh[145413]: 2024-12-12 11:46:22 INFO loading original SD extract_lora_from_models.py:72 Dec 12 11:46:22 xb2-9992 gui.sh[145413]: model : Dec 12 11:46:22 xb2-9992 gui.sh[145413]: /mnt/pub_storage/aig Dec 12 11:46:22 xb2-9992 gui.sh[145413]: c_models/MumuxiTools Dec 12 11:46:22 xb2-9992 gui.sh[145413]: /SimpleAI/SimpleMode Dec 12 11:46:22 xb2-9992 gui.sh[145413]: ls/checkpoints/flux1 Dec 12 11:46:22 xb2-9992 gui.sh[145413]: -dev.safetensors Dec 12 11:46:27 xb2-9992 gui.sh[145413]: Traceback (most recent call last): Dec 12 11:46:27 xb2-9992 gui.sh[145413]: File "/root/kohya_ss/sd-scripts/networks/extract_lora_from_models.py", line 360, in Dec 12 11:46:27 xb2-9992 gui.sh[145413]: svd(**vars(args)) Dec 12 11:46:27 xb2-9992 gui.sh[145413]: File "/root/kohya_ss/sd-scripts/networks/extract_lora_from_models.py", line 73, in svd Dec 12 11:46:27 xb2-9992 gui.sh[145413]: text_encoder_o, _, unet_o = model_util.load_models_from_stable_diffusion_checkpoint(v2, model_org) Dec 12 11:46:27 xb2-9992 gui.sh[145413]: File "/root/kohya_ss/sd-scripts/library/model_util.py", line 1005, in load_models_from_stable_diffusion_checkpoint Dec 12 11:46:27 xb2-9992 gui.sh[145413]: converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config) Dec 12 11:46:27 xb2-9992 gui.sh[145413]: File "/root/kohya_ss/sd-scripts/library/model_util.py", line 267, in convert_ldm_unet_checkpoint Dec 12 11:46:27 xb2-9992 gui.sh[145413]: new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"] Dec 12 11:46:27 xb2-9992 gui.sh[145413]: KeyError: 'time_embed.0.weight'
> 
> 我训练时的参数为 ![image](https://private-user-images.githubusercontent.com/11146882/395000815-ed5013e8-e4c9-4891-8a51-4a5e3dcf233f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODg0MzEsIm5iZiI6MTczNDA4ODEzMSwicGF0aCI6Ii8xMTE0Njg4Mi8zOTUwMDA4MTUtZWQ1MDEzZTgtZTRjOS00ODkxLThhNTEtNGE1ZTNkY2YyMzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDExMDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjMyNTVhY2QyMzBjMzMzMWQ5MWM5ZmJhNzYzZTI0YjYwOTdjZjUyZWQ0ZjM0NWUzY2NiZjk5YmVkM2QxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DfULklXTYRQ-plL74t63MSkqw0Hv4dtzpvdnURg4jU4) ![image](https://private-user-images.githubusercontent.com/11146882/395000842-0e1d583c-4b93-4ff4-b690-b6b289f5d559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODg0MzEsIm5iZiI6MTczNDA4ODEzMSwicGF0aCI6Ii8xMTE0Njg4Mi8zOTUwMDA4NDItMGUxZDU4M2MtNGI5My00ZmY0LWI2OTAtYjZiMjg5ZjVkNTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDExMDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmM2U1OTg3M2Q3YzdhYjMyYTkyZjNhMzBkNTM2ZmU1MjdlOTM1NzgxZDhiN2YwNmU2ODAyYjBiYWU0YzI3YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SUkOiBQevexYgvgBes56ATbm-WMKBuWs9lELMVy0brw)

hello, how much vram(GPU) you use when you finetune the flux.dev, I use 3090 and it shows out of memory
