### ISSUE TITLE
BLIP Captioning not working, "No files with extension .txt were found in E:\BLIP_Captioning_test..."

### ISSUE THREAD

**Issue by llii2044** [bmaltais/kohya_ss#304]
i'm tryung to use Utilities>Captioning>BLIP Captioning, Even if I fill in the correct location, it still picks out errors when I click "Caption images": "No files with extension .txt were found in E:\BLIP_Captioning_test..."

```
Captioning files in E:\BLIP_Captioning_test...
./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "E:\BLIP_Captioning_test" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"
```
![image](https://user-images.githubusercontent.com/127019204/222954290-b10c2555-56b9-42ea-8a84-eedd9fee3a3a.png)

![image](https://user-images.githubusercontent.com/127019204/222954352-92276ada-7640-485c-895e-300539a8ed24.png)

**Comment by OoAnikioO** [comment]
i have this error and no txt 

./venv/Scripts/python.exe "finetune/make_captions.py" --batch_size="1" --num_beams="1" --top_p="0.9" --max_length="75" --min_length="5" --beam_search --caption_extension=".txt" "C:/***/512" --caption_weights="https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_caption.pth"

'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
...captioning done

traduction
'.' is not recognized as an internal or external command
or external command, an executable program or a command file.

**Comment by poisenbery** [comment]
Same error. It worked the first time and then started doing this.

**Comment by bmaltais** [comment]
This may be related to a recent PR to add support for Linux... I will try to reproduce the issue at me end and fix the issue if I can reproduce.

**Comment by bmaltais** [comment]
OK, the issue is clearly related to the Linux support upgrade. I will fix the issue and update the repo. Thank you for reporting.

**Comment by bmaltais** [comment]
New code version has been push. Upgrade to the latest version. It will fix the issue.

**Comment by ioanacarmenm** [comment]
I actually have the same issue. And i updated to the latest version and it's still not working.

**Comment by bmaltais** [comment]
Hummm, you did run `upgrade.ps1` and it still fail. I will double check but all work fine at my end now.

**Comment by ioanacarmenm** [comment]
Yes, just did it again and same results. I still see the error: "No files with extension .txt were found in"
  If it helps, in command prompt i also see this error: "ModuleNotFoundError: No module named 'fairscale'
...captioning done"

**Comment by bmaltais** [comment]
Work fine now... Perhaps it is a different issue? Have you done a upgrade.ps1 before restarting the app?

**Comment by kodxana** [comment]
Hi there! Madiator here! I created runpod template for GUI though users report similar error in our linux based containers. Training works fine except BLIP Captioning.
