### ISSUE TITLE
LoCon failed to match

### ISSUE THREAD

**Issue by specblades** [bmaltais/kohya_ss#307]
LoCon loads but doesnt work in default automatic1111 configuration
Help me to fix pls

<details>
<summary>Error</summary>
`Failed to match keys when loading Lora D:\AI_WORKPLACE\AUTOMATIC1111\current\stable-diffusion-webui\models\Lora\nekro3locontest.safetensors: ['lora_unet_down_blocks_0_downsamplers_0_conv.alpha', 'lora_unet_down_blocks_0_downsamplers_0_conv.lora_down.weight', 'lora_unet_down_blocks_0_downsamplers_0_conv.lora_up.weight', 'lora_unet_down_blocks_0_resnets_0_conv1.alpha', 'lora_unet_down_blocks_0_resnets_0_conv1.lora_down.weight', 'lora_unet_down_blocks_0_resnets_0_conv1.lora_up.weight', 'lora_unet_down_blocks_0_resnets_0_conv2.alpha', 'lora_unet_down_blocks_0_resnets_0_conv2.lora_down.weight', 'lora_unet_down_blocks_0_resnets_0_conv2.lora_up.weight', 'lora_unet_down_blocks_0_resnets_0_time_emb_proj.alpha', 'lora_unet_down_blocks_0_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_0_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_0_resnets_1_conv1.alpha', 'lora_unet_down_blocks_0_resnets_1_conv1.lora_down.weight', 'lora_unet_down_blocks_0_resnets_1_conv1.lora_up.weight', 'lora_unet_down_blocks_0_resnets_1_conv2.alpha', 'lora_unet_down_blocks_0_resnets_1_conv2.lora_down.weight', 'lora_unet_down_blocks_0_resnets_1_conv2.lora_up.weight', 'lora_unet_down_blocks_0_resnets_1_time_emb_proj.alpha', 'lora_unet_down_blocks_0_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_0_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_1_downsamplers_0_conv.alpha', 'lora_unet_down_blocks_1_downsamplers_0_conv.lora_down.weight', 'lora_unet_down_blocks_1_downsamplers_0_conv.lora_up.weight', 'lora_unet_down_blocks_1_resnets_0_conv1.alpha', 'lora_unet_down_blocks_1_resnets_0_conv1.lora_down.weight', 'lora_unet_down_blocks_1_resnets_0_conv1.lora_up.weight', 'lora_unet_down_blocks_1_resnets_0_conv2.alpha', 'lora_unet_down_blocks_1_resnets_0_conv2.lora_down.weight', 'lora_unet_down_blocks_1_resnets_0_conv2.lora_up.weight', 'lora_unet_down_blocks_1_resnets_0_conv_shortcut.alpha', 'lora_unet_down_blocks_1_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_down_blocks_1_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_down_blocks_1_resnets_0_time_emb_proj.alpha', 'lora_unet_down_blocks_1_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_1_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_1_resnets_1_conv1.alpha', 'lora_unet_down_blocks_1_resnets_1_conv1.lora_down.weight', 'lora_unet_down_blocks_1_resnets_1_conv1.lora_up.weight', 'lora_unet_down_blocks_1_resnets_1_conv2.alpha', 'lora_unet_down_blocks_1_resnets_1_conv2.lora_down.weight', 'lora_unet_down_blocks_1_resnets_1_conv2.lora_up.weight', 'lora_unet_down_blocks_1_resnets_1_time_emb_proj.alpha', 'lora_unet_down_blocks_1_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_1_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_2_downsamplers_0_conv.alpha', 'lora_unet_down_blocks_2_downsamplers_0_conv.lora_down.weight', 'lora_unet_down_blocks_2_downsamplers_0_conv.lora_up.weight', 'lora_unet_down_blocks_2_resnets_0_conv1.alpha', 'lora_unet_down_blocks_2_resnets_0_conv1.lora_down.weight', 'lora_unet_down_blocks_2_resnets_0_conv1.lora_up.weight', 'lora_unet_down_blocks_2_resnets_0_conv2.alpha', 'lora_unet_down_blocks_2_resnets_0_conv2.lora_down.weight', 'lora_unet_down_blocks_2_resnets_0_conv2.lora_up.weight', 'lora_unet_down_blocks_2_resnets_0_conv_shortcut.alpha', 'lora_unet_down_blocks_2_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_down_blocks_2_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_down_blocks_2_resnets_0_time_emb_proj.alpha', 'lora_unet_down_blocks_2_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_2_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_2_resnets_1_conv1.alpha', 'lora_unet_down_blocks_2_resnets_1_conv1.lora_down.weight', 'lora_unet_down_blocks_2_resnets_1_conv1.lora_up.weight', 'lora_unet_down_blocks_2_resnets_1_conv2.alpha', 'lora_unet_down_blocks_2_resnets_1_conv2.lora_down.weight', 'lora_unet_down_blocks_2_resnets_1_conv2.lora_up.weight', 'lora_unet_down_blocks_2_resnets_1_time_emb_proj.alpha', 'lora_unet_down_blocks_2_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_2_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_3_resnets_0_conv1.alpha', 'lora_unet_down_blocks_3_resnets_0_conv1.lora_down.weight', 'lora_unet_down_blocks_3_resnets_0_conv1.lora_up.weight', 'lora_unet_down_blocks_3_resnets_0_conv2.alpha', 'lora_unet_down_blocks_3_resnets_0_conv2.lora_down.weight', 'lora_unet_down_blocks_3_resnets_0_conv2.lora_up.weight', 'lora_unet_down_blocks_3_resnets_0_time_emb_proj.alpha', 'lora_unet_down_blocks_3_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_3_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_down_blocks_3_resnets_1_conv1.alpha', 'lora_unet_down_blocks_3_resnets_1_conv1.lora_down.weight', 'lora_unet_down_blocks_3_resnets_1_conv1.lora_up.weight', 'lora_unet_down_blocks_3_resnets_1_conv2.alpha', 'lora_unet_down_blocks_3_resnets_1_conv2.lora_down.weight', 'lora_unet_down_blocks_3_resnets_1_conv2.lora_up.weight', 'lora_unet_down_blocks_3_resnets_1_time_emb_proj.alpha', 'lora_unet_down_blocks_3_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_down_blocks_3_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_mid_block_resnets_0_conv1.alpha', 'lora_unet_mid_block_resnets_0_conv1.lora_down.weight', 'lora_unet_mid_block_resnets_0_conv1.lora_up.weight', 'lora_unet_mid_block_resnets_0_conv2.alpha', 'lora_unet_mid_block_resnets_0_conv2.lora_down.weight', 'lora_unet_mid_block_resnets_0_conv2.lora_up.weight', 'lora_unet_mid_block_resnets_0_time_emb_proj.alpha', 'lora_unet_mid_block_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_mid_block_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_mid_block_resnets_1_conv1.alpha', 'lora_unet_mid_block_resnets_1_conv1.lora_down.weight', 'lora_unet_mid_block_resnets_1_conv1.lora_up.weight', 'lora_unet_mid_block_resnets_1_conv2.alpha', 'lora_unet_mid_block_resnets_1_conv2.lora_down.weight', 'lora_unet_mid_block_resnets_1_conv2.lora_up.weight', 'lora_unet_mid_block_resnets_1_time_emb_proj.alpha', 'lora_unet_mid_block_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_mid_block_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_0_resnets_0_conv1.alpha', 'lora_unet_up_blocks_0_resnets_0_conv1.lora_down.weight', 'lora_unet_up_blocks_0_resnets_0_conv1.lora_up.weight', 'lora_unet_up_blocks_0_resnets_0_conv2.alpha', 'lora_unet_up_blocks_0_resnets_0_conv2.lora_down.weight', 'lora_unet_up_blocks_0_resnets_0_conv2.lora_up.weight', 'lora_unet_up_blocks_0_resnets_0_conv_shortcut.alpha', 'lora_unet_up_blocks_0_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_0_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_0_resnets_0_time_emb_proj.alpha', 'lora_unet_up_blocks_0_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_0_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_0_resnets_1_conv1.alpha', 'lora_unet_up_blocks_0_resnets_1_conv1.lora_down.weight', 'lora_unet_up_blocks_0_resnets_1_conv1.lora_up.weight', 'lora_unet_up_blocks_0_resnets_1_conv2.alpha', 'lora_unet_up_blocks_0_resnets_1_conv2.lora_down.weight', 'lora_unet_up_blocks_0_resnets_1_conv2.lora_up.weight', 'lora_unet_up_blocks_0_resnets_1_conv_shortcut.alpha', 'lora_unet_up_blocks_0_resnets_1_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_0_resnets_1_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_0_resnets_1_time_emb_proj.alpha', 'lora_unet_up_blocks_0_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_0_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_0_resnets_2_conv1.alpha', 'lora_unet_up_blocks_0_resnets_2_conv1.lora_down.weight', 'lora_unet_up_blocks_0_resnets_2_conv1.lora_up.weight', 'lora_unet_up_blocks_0_resnets_2_conv2.alpha', 'lora_unet_up_blocks_0_resnets_2_conv2.lora_down.weight', 'lora_unet_up_blocks_0_resnets_2_conv2.lora_up.weight', 'lora_unet_up_blocks_0_resnets_2_conv_shortcut.alpha', 'lora_unet_up_blocks_0_resnets_2_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_0_resnets_2_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_0_resnets_2_time_emb_proj.alpha', 'lora_unet_up_blocks_0_resnets_2_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_0_resnets_2_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_0_upsamplers_0_conv.alpha', 'lora_unet_up_blocks_0_upsamplers_0_conv.lora_down.weight', 'lora_unet_up_blocks_0_upsamplers_0_conv.lora_up.weight', 'lora_unet_up_blocks_1_resnets_0_conv1.alpha', 'lora_unet_up_blocks_1_resnets_0_conv1.lora_down.weight', 'lora_unet_up_blocks_1_resnets_0_conv1.lora_up.weight', 'lora_unet_up_blocks_1_resnets_0_conv2.alpha', 'lora_unet_up_blocks_1_resnets_0_conv2.lora_down.weight', 'lora_unet_up_blocks_1_resnets_0_conv2.lora_up.weight', 'lora_unet_up_blocks_1_resnets_0_conv_shortcut.alpha', 'lora_unet_up_blocks_1_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_1_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_1_resnets_0_time_emb_proj.alpha', 'lora_unet_up_blocks_1_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_1_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_1_resnets_1_conv1.alpha', 'lora_unet_up_blocks_1_resnets_1_conv1.lora_down.weight', 'lora_unet_up_blocks_1_resnets_1_conv1.lora_up.weight', 'lora_unet_up_blocks_1_resnets_1_conv2.alpha', 'lora_unet_up_blocks_1_resnets_1_conv2.lora_down.weight', 'lora_unet_up_blocks_1_resnets_1_conv2.lora_up.weight', 'lora_unet_up_blocks_1_resnets_1_conv_shortcut.alpha', 'lora_unet_up_blocks_1_resnets_1_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_1_resnets_1_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_1_resnets_1_time_emb_proj.alpha', 'lora_unet_up_blocks_1_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_1_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_1_resnets_2_conv1.alpha', 'lora_unet_up_blocks_1_resnets_2_conv1.lora_down.weight', 'lora_unet_up_blocks_1_resnets_2_conv1.lora_up.weight', 'lora_unet_up_blocks_1_resnets_2_conv2.alpha', 'lora_unet_up_blocks_1_resnets_2_conv2.lora_down.weight', 'lora_unet_up_blocks_1_resnets_2_conv2.lora_up.weight', 'lora_unet_up_blocks_1_resnets_2_conv_shortcut.alpha', 'lora_unet_up_blocks_1_resnets_2_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_1_resnets_2_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_1_resnets_2_time_emb_proj.alpha', 'lora_unet_up_blocks_1_resnets_2_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_1_resnets_2_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_1_upsamplers_0_conv.alpha', 'lora_unet_up_blocks_1_upsamplers_0_conv.lora_down.weight', 'lora_unet_up_blocks_1_upsamplers_0_conv.lora_up.weight', 'lora_unet_up_blocks_2_resnets_0_conv1.alpha', 'lora_unet_up_blocks_2_resnets_0_conv1.lora_down.weight', 'lora_unet_up_blocks_2_resnets_0_conv1.lora_up.weight', 'lora_unet_up_blocks_2_resnets_0_conv2.alpha', 'lora_unet_up_blocks_2_resnets_0_conv2.lora_down.weight', 'lora_unet_up_blocks_2_resnets_0_conv2.lora_up.weight', 'lora_unet_up_blocks_2_resnets_0_conv_shortcut.alpha', 'lora_unet_up_blocks_2_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_2_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_2_resnets_0_time_emb_proj.alpha', 'lora_unet_up_blocks_2_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_2_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_2_resnets_1_conv1.alpha', 'lora_unet_up_blocks_2_resnets_1_conv1.lora_down.weight', 'lora_unet_up_blocks_2_resnets_1_conv1.lora_up.weight', 'lora_unet_up_blocks_2_resnets_1_conv2.alpha', 'lora_unet_up_blocks_2_resnets_1_conv2.lora_down.weight', 'lora_unet_up_blocks_2_resnets_1_conv2.lora_up.weight', 'lora_unet_up_blocks_2_resnets_1_conv_shortcut.alpha', 'lora_unet_up_blocks_2_resnets_1_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_2_resnets_1_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_2_resnets_1_time_emb_proj.alpha', 'lora_unet_up_blocks_2_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_2_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_2_resnets_2_conv1.alpha', 'lora_unet_up_blocks_2_resnets_2_conv1.lora_down.weight', 'lora_unet_up_blocks_2_resnets_2_conv1.lora_up.weight', 'lora_unet_up_blocks_2_resnets_2_conv2.alpha', 'lora_unet_up_blocks_2_resnets_2_conv2.lora_down.weight', 'lora_unet_up_blocks_2_resnets_2_conv2.lora_up.weight', 'lora_unet_up_blocks_2_resnets_2_conv_shortcut.alpha', 'lora_unet_up_blocks_2_resnets_2_conv_shortcut.lo100%|████████████████████████████████████████| 14/14 [00:21<00:00,  1.56s/it]t', 'lora_unet_up_blocks_2_resne
Total progress: 100%|███████████████████████████████████████████████████████| 14/14 [00:12<00:00,  1.10it/s]l
100%|███████████████████████████████████████████████████████████████████████| 14/14 [00:18<00:00,  1.35s/it]u
Total progress: 100%|███████████████████████████████████████████████████████| 14/14 [00:18<00:00,  1.35s/it]o
100%|███████████████████████████████████████████████████████████████████████| 14/14 [00:12<00:00,  1.13it/s]u
Total progress: 100%|███████████████████████████████████████████████████████| 14/14 [00:12<00:00,  1.11it/s]p
_blocks_3_resnets_0_conv2.lora_down.weight', 'lora_unet_up_blocks_3_resnets_0_conv2.lora_up.weight', 'lora_unet_up_blocks_3_resnets_0_conv_shortcut.alpha', 'lora_unet_up_blocks_3_resnets_0_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_3_resnets_0_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_3_resnets_0_time_emb_proj.alpha', 'lora_unet_up_blocks_3_resnets_0_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_3_resnets_0_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_3_resnets_1_conv1.alpha', 'lora_unet_up_blocks_3_resnets_1_conv1.lora_down.weight', 'lora_unet_up_blocks_3_resnets_1_conv1.lora_up.weight', 'lora_unet_up_blocks_3_resnets_1_conv2.alpha', 'lora_unet_up_blocks_3_resnets_1_conv2.lora_down.weight', 'lora_unet_up_blocks_3_resnets_1_conv2.lora_up.weight', 'lora_unet_up_blocks_3_resnets_1_conv_shortcut.alpha', 'lora_unet_up_blocks_3_resnets_1_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_3_resnets_1_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_3_resnets_1_time_emb_proj.alpha', 'lora_unet_up_blocks_3_resnets_1_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_3_resnets_1_time_emb_proj.lora_up.weight', 'lora_unet_up_blocks_3_resnets_2_conv1.alpha', 'lora_unet_up_blocks_3_resnets_2_conv1.lora_down.weight', 'lora_unet_up_blocks_3_resnets_2_conv1.lora_up.weight', 'lora_unet_up_blocks_3_resnets_2_conv2.alpha', 'lora_unet_up_blocks_3_resnets_2_conv2.lora_down.weight', 'lora_unet_up_blocks_3_resnets_2_conv2.lora_up.weight', 'lora_unet_up_blocks_3_resnets_2_conv_shortcut.alpha', 'lora_unet_up_blocks_3_resnets_2_conv_shortcut.lora_down.weight', 'lora_unet_up_blocks_3_resnets_2_conv_shortcut.lora_up.weight', 'lora_unet_up_blocks_3_resnets_2_time_emb_proj.alpha', 'lora_unet_up_blocks_3_resnets_2_time_emb_proj.lora_down.weight', 'lora_unet_up_blocks_3_resnets_2_time_emb_proj.lora_up.weight'`
</details>

UPD

Found that, but bmaltais/kohya_ss repo says it must work natively
https://github.com/KohakuBlueleaf/LoCon

UPD

Doesn't work, no errors but LoCon gives no effect

**Comment by bmaltais** [comment]
Strange, I create and used LoCon with no issue. Are you loading then via the kohya Additional network extension or by using the native auto1111 LoRA support? Will not work via kohya additional network.

**Comment by specblades** [comment]
> Strange, I create and used LoCon with no issue. Are you loading then via the kohya Additional network extension or by using the native auto1111 LoRA support? Will not work via kohya additional network.

tryed both, with kohya additional network it gives error, yep

**Comment by YinnVI** [comment]
Same Issue here #310
