### ISSUE TITLE
[Feature Request] Implementation of GUI for generation of sample images during training

### ISSUE THREAD

**Issue by DKnight54** [bmaltais/kohya_ss#319]
Kohya has implemented the feature to allow generation of preview images during training. 

It would be very nice if this can be implemented into the GUI, as currently, there is no optional command line entries that can be used to add the required arguments.

Ideally, the GUI would have a field for allowing users to key in the prompts (multiple prompts may be required, to generate different test images, or to test different keyword prompts as allowed by kohya's code), select the sampler, and the image generation parameters. However, even the implementation of a default generation parameter only would be much appreciated!

**Comment by bmaltais** [comment]
The new GUI is up in the dev branch:

`git checkout dev`

**Comment by DKnight54** [comment]
great! testing it out!
A part that tripped me up was that the dimensions of the sample images have to be divisable by 8, ie 512 by 712 etc. I tried feeding in a 512 by 708 dimension, and the training stoped with an error. 

Would be nice if you can implement a checker for --w and --h to prevent users from entering invalid dimensions.

**Comment by bmaltais** [comment]
Interesting... Kohya should round those to the nearest valid values in his code... I think is should be better addressed there. I will let him know.

**Comment by DKnight54** [comment]
reasonable, better to handle the random stuff users(like me) would key in safely, then to have issues. But perhaps it would be a good idea to have the GUI mention that the --h and --w expects values that are multiples of 8, just to reduce user error, and if Kohya changes his code, let users know the expected outcome.

Also, while digging around trying to change the prompts during training (Screwed up and was getting double headed monsters 🤣), realized that it was set up to save and feed a temporary file to the SD-scripts. As a suggestion, can we have the prompt file saved as a txt file in the output folder, mirroring the model name? It would make on the fly amendments much easier instead of having to scroll through the console to find the CLI command and copy the location from there.

Makes life easier for newbies like me who are still learning how to prompt SD. Especially the base model.

**Comment by bmaltais** [comment]
> Also, while digging around trying to change the prompts during training (Screwed up and was getting double headed monsters 🤣), realized that it was set up to save and feed a temporary file to the SD-scripts. As a suggestion, can we have the prompt file saved as a txt file in the output folder, mirroring the model name? It would make on the fly amendments much easier instead of having to scroll through the console to find the CLI command and copy the location from there.

This should like a good idea. I will save it in the same folder as the pictures produced... but that file is only read when the script start... so I am not sure there is any walut in doing that... and since the prompt is part of the GUI it is always re-generated on run of the training and would overwrite any changes made to the file... And this would lead users to complain ;-)

So perhaps it is preferable to just treat it as a temp file that is only viable when the command is run?

**Comment by DKnight54** [comment]
🤔 How hard would it be to have the GUI load the prompts from the txt file if it exists on loading a saved config, or setting an output folder?

Maybe it's just me, but I'm an impatient kind of fella, and I found myself going in to manually edit the temp prompt file to add more things that I forgot about testing, to see if the different training prompts are having an effect or not, or to see if the lora is getting over trained. (yes, yes, inconsistent prompts can lead to confusion about whether it's the model's issue, or if it's the prompt's issue, but it's fun!)

I assume in most cases, if the user sets the output folder manually, it's presumably an empty folder, but if by chance the user has put a sample prompt file there, they would probably be expecting to use it as a default sample prompt.

And incase the prompt file does not exists, or is empty, then the GUI could load any saved prompts from the config json.

However, I just thought of an alternative solution! when the user clicks save in the GUI, update the temp prompt file too! Wait. That only works if the temp prompt file is created even before start is clicked... hrm....

**Comment by bmaltais** [comment]
> Maybe it's just me, but I'm an impatient kind of fella, and I found myself going in to manually edit the temp prompt file to add more things that I forgot about testing, to see if the different training prompts are having an effect or not, or to see if the lora is getting over trained. (yes, yes, inconsistent prompts can lead to confusion about whether it's the model's issue, or if it's the prompt's issue, but it's fun!)

Why not just edit the prompt in the GUI prompt field? Editing the tmp file will not really help... and when you save the GUI config to a json file the prompt is also saved... so when you load the config it will bring back the prompt. If the GUI did not offer an option to create and change the prompt then I could understand the idea of using a file instead of the actual prompt field... but if you use the GUI why not just use the prompt field?

>Part of the issue, is that with the Automatic1111 webui's training, we can see different results based on prompts on the original images, and that gives us a very good idea of how the trained lora matches with the inputs. In this case, as the prompts are... kinda static, being able to go in and easily edit the prompts helps with checking the progress.

But editing the prompt file while training is running will not change the prompt result. My understanding is that kohya lora trainer only load the prompt when you invoke the training... not after it has been started.

**Comment by DKnight54** [comment]
Ah! I think I see where our difference in thought comes in. From my testing, it appears that the file with the prompts is read each time Kohya's code generates a sample (at least for the per epoch sample. The per N iterations appear not to generate when sd-scripts is given both per N epoch and per N iterations. I'd need to do more testing to confirm)

It's quite easy to test, since each line is a different sample image, by adding the number of lines, I can change the number of sample images generated each time. So I'm confident the sample prompt file is being read each time sample images are being generated.

**Comment by bmaltais** [comment]
OK, I have implemented the saving to prompt.txt in the sample folder instead of a temp folder. This should cover the use case of updating the prompts during training by editing the file.

**Comment by bmaltais** [comment]
I just tested and it does indeed read the file on each generation... so certainly worth having access to it to edit during training.

**Comment by DKnight54** [comment]
Appreciate the news! will test it out when I have a chance!

**Comment by tcflying** [comment]
it works now, but i can't find the sample jpg anywhere..

**Comment by DKnight54** [comment]
@unoriginalscreenname hrm... Gotta ask, did you setup an activation keyword? From my experience while messing around with the prompts, if you did setup an activation keyword, then include it in your sample prompt. From what I experience, that should trigger the trained subject and/or style. However, most of my experience has been with training subjects, and I'm less certain about training styles and triggering them, especially if you did not set up a trigger word.

In my use case, I'd been using prompts like "subject_xxx is standing on a beach wearing blue t-shirt and jeans" and seeing if the result matches what I want. I tend to include a couple of "neutral" prompts to see if I've been overtraining the model, eg the next sample prompt would be "man is sitting in a forest wearing a business suit". It might also help to copy one of the prompts from your training images and see if it recreates something similar.

Otherwise, what I'd suggest is to try triggering the style by the closest associated word? for example, if you were training on a specific oil painting style, try including "oil painting" in the prompt and see if that triggers it?

**Comment by DeeeFoo** [comment]
I feel so dumb, where can I view the sample preview images that are generated during Lora training? I set it to generate sample images every 50 steps, but I have no idea how/where to view them.

**Comment by DKnight54** [comment]
Check in the folder you set as output for the model, if it's working correcting (and the cmd would show that it's generating samples), there should be a "sample" folder in the output folder with the prompt.txt file and any images it has generated using those prompts. I... have had an issue where the generate on every 50 steps was not working when I was generating sample images on each epoch.

**Comment by DeeeFoo** [comment]
> Check in the folder you set as output for the model, if it's working correcting (and the cmd would show that it's generating samples), there should be a "sample" folder in the output folder with the prompt.txt file and any images it has generated using those prompts. I... have had an issue where the generate on every 50 steps was not working when I was generating sample images on each epoch.

Thanks, I think I got it! My issue was that I didn't put a sample prompt, so no images were being generated. Any suggestions on what to put as a generic sample prompt for a person's face? I just want to be able to visually track the progress of the training.

**Comment by DKnight54** [comment]
Erm... depending on what you are trying to do, I'd do a couple of prompts with different poses and both with and without the activation keyword, to see if I'm getting the results I wanted, and whether there is any burning going on. I'd also suggest using prompts like you would when generating images.

> photo, medium close-up shot, masterpiece, best quality, solo, example_person, long blonde hair, dark skin, in blue swimsuit, kneeling on beach, from above, facing viewer, looking at viewer --n low quality, worst quality, bad anatomy,bad composition, poor, low effort, extra fingers, fewer digits, extra limbs, extra arms, extra legs, malformed limbs --w 512 --h 712 --l 5.5 --s 20
