### ISSUE TITLE
[Feature Request] Batch Training LoRA

### ISSUE THREAD

**Issue by Susanoo1337** [bmaltais/kohya_ss#329]
Say I have 5 prepared datasets, made 5 different configs, it would be lovely if I could just give the GUI a list of configs to train one after the other. Let it run over night and train 5 different LoRA. If that's even possible to pull off in gradio.

**Comment by bmaltais** [comment]
Technically it could be done. Might get to it some day. One possibility could be to output the command without running it for each config then you can simply put them back to back in a file and run that... This might be an alternative. I would need to add a button to "print trainer command" instread of train...
