### ISSUE TITLE
webui extension?

### ISSUE THREAD

**Issue by space-nuko** [bmaltais/kohya_ss#33]
Would it make sense to have this as an integrated extension to automatic's webui, or is there some reason the two are incompatible? A few things I can see improved:

- automatically setting the output folder, right now the output is overwritten and you have to manually update the folder for each new lora. It would be very comvenient to have the layout similar to the one for the webui's `textual_inversion`
- automatic renaming of each epoch output, instead of just `epoch-X.pt`/`last.pt`
- interrupt feature during training
- progress visible in the UI instead of just the console
- preview images after each epoch, this can currently be accomplished by running txt2img in a separate webui instance with the intermediate epoch outputs, but it's nice to have done automatically
- dropdowns for sd/lora model in the standard webui paths, this is also very important for reproducibility to be able to restore the lora config from the infotext in the future
- single application to run, instead of two separate ones
- automatic setup of dependencies instead of the manual install instructions?

Of course most of these can probably be implemented without it being an extension, I was just curious

**Comment by geocine** [comment]
This has been implement on upstream
> automatic renaming of each epoch output, instead of just `epoch-X.pt`/`last.pt`

**Comment by bmaltais** [comment]
Indeed. Will release an update soon.
