### ISSUE TITLE
fine_tune not working

### ISSUE THREAD

**Issue by tcflying** [bmaltais/kohya_ss#339]
(venv) PS D:\kohya_ss> .\gui.ps1
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
./venv/Scripts/python.exe finetune/merge_captions_to_metadata.py --caption_extension=.txt "D:/xm0/anime/1/50_1" "D:/lora/meta_cap.json" --full_path
found 4 images.
loading existing metadata: D:/lora/meta_cap.json
captions for existing images will be overwritten / 既存の画像のキャプションは上書きされます
merge caption texts to metadata json.
100%|████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<?, ?it/s]
writing metadata: D:/lora/meta_cap.json
done!
./venv/Scripts/python.exe finetune/prepare_buckets_latents.py "D:/xm0/anime/1/50_1" "D:/lora/meta_cap.json" "D:/lora/meta_lat.json" "D:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt" --batch_size=4 --max_resolution=512,512 --min_bucket_reso=256 --max_bucket_reso=1024 --mixed_precision=fp16 --full_path
found 4 images.
loading existing metadata: D:/lora/meta_cap.json
load VAE: D:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
100%|████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.59it/s]
bucket 0 (512, 512): 4
mean ar error: 0.0
writing metadata: D:/lora/meta_lat.json
done!
image_num = 4
repeats = 800
max_train_steps = 1000
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "./fine_tune.py" --train_text_encoder --pretrained_model_name_or_path="D:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt" --in_json="D:/lora/meta_lat.json" --train_data_dir="D:/xm0/anime/1/50_1" --output_dir="D:/stable-diffusion-webui/models/Stable-diffusion" --dataset_repeats=200 --learning_rate=1e-6 --enable_bucket --resolution=512,512 --min_bucket_reso=256 --max_bucket_reso=1024 --save_model_as=safetensors --output_name="v15-xm0-4pcs-fine" --learning_rate="1e-6" --lr_scheduler="constant" --train_batch_size="4" --max_train_steps="1000" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --clip_skip=2 --bucket_reso_steps=64 --flip_aug --shuffle_caption --xformers --persistent_data_loader_workers
prepare tokenizer
loading existing metadata: D:/lora/meta_lat.json
Traceback (most recent call last):
  File "D:\kohya_ss\fine_tune.py", line 351, in <module>
    train(args)
  File "D:\kohya_ss\fine_tune.py", line 33, in train
    train_dataset = train_util.FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "D:\kohya_ss\library\train_util.py", line 1190, in __init__
    caption is not None and len(caption) > 0
AssertionError: caption or tag is required / キャプションまたはタグは必須です:D:/xm0/anime/1/50_1\a.png
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', './fine_tune.py', '--train_text_encoder', '--pretrained_model_name_or_path=D:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--in_json=D:/lora/meta_lat.json', '--train_data_dir=D:/xm0/anime/1/50_1', '--output_dir=D:/stable-diffusion-webui/models/Stable-diffusion', '--dataset_repeats=200', '--learning_rate=1e-6', '--enable_bucket', '--resolution=512,512', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--save_model_as=safetensors', '--output_name=v15-xm0-4pcs-fine', '--learning_rate=1e-6', '--lr_scheduler=constant', '--train_batch_size=4', '--max_train_steps=1000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--clip_skip=2', '--bucket_reso_steps=64', '--flip_aug', '--shuffle_caption', '--xformers', '--persistent_data_loader_workers']' returned non-zero exit status 1.

![WechatIMG684](https://user-images.githubusercontent.com/77509083/223962901-cee5653f-b715-4d2c-9e70-178e6ef505f1.jpeg)

**Comment by ruSauron** [comment]
Check D:/xm0/anime/1/50_1\a.png and its captions, something wrong with it (non ascii symbols for example), looks like it's not an issue

**Comment by tcflying** [comment]
png file is fine to train lora, also the caption is very simple word: a cartoon of a girl with blue hair and a blue shirt that says groovy.

that's it, thanks.

> Check D:/xm0/anime/1/50_1\a.png and it's captions, something wrong with it (non ascii symbols for example) You may just move a.png from trainig folders to exclude it from dataset

**Comment by DKnight54** [comment]
are a.txt and a.caption files having the same content? It may be that the .caption file is empty, and you left the caption file extension field empty, which means that it thinks the captions should be in a.caption (and b.caption etc)
![image](https://user-images.githubusercontent.com/126916963/224129267-126f3a48-7341-4be5-bcda-781f2f7af047.png)

**Comment by tcflying** [comment]
it works with update today,
