### ISSUE TITLE
CUDA out of memory when making LoRA

### ISSUE THREAD

**Issue by AronTW** [bmaltais/kohya_ss#340]
New to this but am getting this error constantly

Folder 100_VRCAron: 2200 steps
max_train_steps = 2200
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/Aron/Documents/ARONVRC LORA/image" --resolution=512,512 --output_dir="C:/Users/Aron/Documents/ARONVRC LORA/model" --logging_dir="C:/Users/Aron/Documents/ARONVRC LORA/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="AronVRC" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="2200" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare train images.
found directory 100_VRCAron contains 22 image files
2200 train images with repeating.
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 1132.66it/s]
prepare dataset
prepare accelerator
Using accelerator 0.15.0 or above.
load Diffusers pretrained models
safety_checker\model.safetensors not found
Fetching 19 files: 100%|███████████████████████████████████████████████████████████████████████| 19/19 [00:00<?, ?it/s]
C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Replace CrossAttention.forward to use FlashAttention (not xformers)
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [00:55<00:00,  2.54s/it]
import network module: networks.lora
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\train_network.py", line 176, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 876, in prepare
    result = tuple(
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 877, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 741, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 912, in prepare_model
    model = model.to(self.device)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\transformers\modeling_utils.py", line 1749, in to
    return super().to(*args, **kwargs)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 927, in to
    return self._apply(convert)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 579, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 602, in _apply
    param_applied = fn(param)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 925, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Aron\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Aron\\Desktop\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/Aron/Documents/ARONVRC LORA/image', '--resolution=512,512', '--output_dir=C:/Users/Aron/Documents/ARONVRC LORA/model', '--logging_dir=C:/Users/Aron/Documents/ARONVRC LORA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=AronVRC', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=2200', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by ruSauron** [comment]
As i know 6 Gb of VRam are minimal system requirements. You may Google collab

**Comment by AronTW** [comment]
> As i know 6 Gb of VRam are minimal system requirements. You may Google collab

Ah, so I'm out of luck cause I don't have that much VRAM?

**Comment by ClashSAN** [comment]
@AronTW actually, you can train textual inversion and LoRA (unet only) on only 4gb. this should be documented, it is a wonderful thing! use the unet only flag and all your additional vram saving flags.

**Comment by AronTW** [comment]
> @AronTW actually, you can train textual inversion and LoRA (unet only) on only 4gb. this should be documented, it is a wonderful thing! use the unet only flag and all your additional vram saving flags.

How do I do that exactly? Apologies, still pretty new to all this

**Comment by AronTW** [comment]
> As i know 6 Gb of VRam are minimal system requirements. You may use Google collab Also you may try to close all programs including chrome. And may be kill explorer process. May be even lowering desktop resolution and switch off 2nd monitor if you have it. It may save some mb of VRam

Tried closing everything and turning the resolution down but got the same result

**Comment by FinaBro69** [comment]
i know how to solve

go to (Training parameters) you can see is (AdamW8bit change to AdamW)
and (Gradient checkpointing, Memory efficient attention) is two also tick it

Hope it helps you

**Comment by AronTW** [comment]
> i know how to solve
> 
> go to (Training parameters) you can see is (AdamW8bit change to AdamW) and (Gradient checkpointing, Memory efficient attention) is two also tick it
> 
> Hope it helps you

Unfortunately I get the same error

**Comment by FinaBro69** [comment]
> > i know how to solve
> > go to (Training parameters) you can see is (AdamW8bit change to AdamW) and (Gradient checkpointing, Memory efficient attention) is two also tick it
> > Hope it helps you
> 
> Unfortunately I get the same error

Then I don’t know about your problem. Only you know what error is happening now.
![FgSxgOqWQAEhw-A](https://user-images.githubusercontent.com/127876242/226078216-548782fd-58ff-4797-96a9-5c51f5d785f6.jpg)

**Comment by AronTW** [comment]
> > > i know how to solve
> > > go to (Training parameters) you can see is (AdamW8bit change to AdamW) and (Gradient checkpointing, Memory efficient attention) is two also tick it
> > > Hope it helps you
> > 
> > 
> > Unfortunately I get the same error
> 
> Then I don’t know about your problem. Only you know what error is happening now. ![FgSxgOqWQAEhw-A](https://user-images.githubusercontent.com/127876242/226078216-548782fd-58ff-4797-96a9-5c51f5d785f6.jpg)

You're probably right

Guess 4gb VRAM isn't enough-

**Comment by FinaBro69** [comment]
Sorry, that's how it is.
Now I'm using a 10 series graphics card with 6gb
Then I recommend you to buy a 10 series graphics card with 6gb

Hope it helps you

**Comment by AronTW** [comment]
> Sorry, that's how it is. Now I'm using a 10 series graphics card with 6gb Then I recommend you to buy a 10 series graphics card with 6gb
> 
> Hope it helps you

Shame, I'll keep that in mind, doubt it'll ever be able to be down with my specs

**Comment by FinaBro69** [comment]
> > Sorry, that's how it is. Now I'm using a 10 series graphics card with 6gb Then I recommend you to buy a 10 series graphics card with 6gb
> > Hope it helps you
> 
> Shame, I'll keep that in mind, doubt it'll ever be able to be down with my specs

Currently I don't know if you are using desktop and laptop
Don't think about it if you are using desktop
Just replace the graphics card and power supply

**Comment by AronTW** [comment]
> > > Sorry, that's how it is. Now I'm using a 10 series graphics card with 6gb Then I recommend you to buy a 10 series graphics card with 6gb
> > > Hope it helps you
> > 
> > 
> > Shame, I'll keep that in mind, doubt it'll ever be able to be down with my specs
> 
> Currently I don't know if you are using desktop and laptop Don't think about it if you are using desktop Just replace the graphics card and power supply

Noted :(
