### ISSUE TITLE
CUDA_SETUP: WARNING! libcudart.so not found

### ISSUE THREAD

**Issue by withb3ar** [bmaltais/kohya_ss#352]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
E:\TWICE\AI\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!

hi, i'm newbie here, how to resolve this?

**Comment by bmaltais** [comment]
When is it spitting this error. This is normal when using tensorboard... but nor when training.

**Comment by withb3ar** [comment]
when i want to start the training
