### ISSUE TITLE
Attribute error even thought I already changed the train_util.py document

### ISSUE THREAD

**Issue by howgermcgredy** [bmaltais/kohya_ss#356]
![image](https://user-images.githubusercontent.com/116721444/224473854-9301517a-7cce-4790-9eb6-4028399deaa1.png)
I have this error after changed the document from sd-scripts-main or kohya_ss-master.
I want to know what happen about my taining, thanks a lot!

**Comment by bmaltais** [comment]
Did you run upgrade.ps1 after switching branch?

**Comment by howgermcgredy** [comment]
> Did you run upgrade.ps1 after switching branch?

Yes, I run the upgrade first and trying training.

**Comment by bmaltais** [comment]
Herd to tell. What is the training command the GUI is trying to run? Maybe there is something that will show up to help understand the issue.

**Comment by howgermcgredy** [comment]
> Hard to tell. What is the training command the GUI is trying to run? Maybe there is something that will show up to help understand the issue.

![image](https://user-images.githubusercontent.com/116721444/224525228-88410c8d-00f5-4349-9cde-df9bd776f0dd.png)
![image](https://user-images.githubusercontent.com/116721444/224525247-7c4e147c-8cd8-49d2-bce2-5b1c6e17ce91.png)
![image](https://user-images.githubusercontent.com/116721444/224525287-b2041557-15f3-464c-8305-70dd14d32e17.png)
Like this, I use the configuration file cause I only have 6 VRAM. I don't change anything in the training parameter advanced configuration.

**Comment by bmaltais** [comment]
Try running upgrade.ps1 again. I published a new update with new validation code that might help sirface issues with the configuration on gui.ps1 or gui.bat startup.

**Comment by howgermcgredy** [comment]
I try to reinstall the gui now, it told me that a new releaseof pip available to 23.0.1, should I upgrate it?

**Comment by howgermcgredy** [comment]
> Try running upgrade.ps1 again. I published a new update with new validation code that might help sirface issues with the configuration on gui.ps1 or gui.bat startup.

![image](https://user-images.githubusercontent.com/116721444/224553342-b85b243e-6e48-49e4-84b8-661e718b2fe8.png)
I have CalledProcessError now...

**Comment by bmaltais** [comment]
OK... look like you don't have enough VRAM for the settings you are usiing. You only have 6GB of VRAM and this is probably not enough. 8 GB is a minimum I would recommand. 6GB is not enough for training models. Some have been able to do it but I don't have a card to test with.

**Comment by howgermcgredy** [comment]
> OK... look like you don't have enough VRAM for the settings you are usiing. You only have 6GB of VRAM and this is probably not enough. 8 GB is a minimum I would recommand. 6GB is not enough for training models. Some have been able to do it but I don't have a card to test with.

So I need to change traing parameters setting to find the suitable for my vram right?
If so, does there have recommand element will be success relatively?

**Comment by bmaltais** [comment]
You have already pretty reasonable values... not sure what else you could try... Maybe try going to LoRA of 64 DIM instead of 128?

**Comment by howgermcgredy** [comment]
> You have already pretty reasonable values... not sure what else you could try... Maybe try going to LoRA of 64 DIM instead of 128?

![image](https://user-images.githubusercontent.com/116721444/224950930-84f7559d-86c8-4320-afd9-2beb19e69c01.png)
It's working now! I change the element you recommand and it work successfully.
Thanks for these days reply!! I am be frustrated at first due to my vram. Already research it about a month but it still didn't working untill today. You are my hero! Thought I use bad English to communicate with you.
