### ISSUE TITLE
"--xformers" not work

### ISSUE THREAD

**Issue by Kotori05** [bmaltais/kohya_ss#359]
in wsl ubuntu the xformers can't run correctly
how to cancel the command “--xformers”, which file should be changed?

**Comment by bmaltais** [comment]
You can simply uncheck the xformers option in the GUI.

**Comment by xinpengzhu** [comment]
I use python3.8.10 in ubuntu20.04， I fix the error by refer to stable diffusion，torch==1.13.1+cu117 and xformers==0.0.16rc425， I modify the ubuntu_setup.sh
`#!/bin/bash
echo installing tk
sudo apt install python3-tk
python3 -m venv venv
source venv/bin/activate
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

pip install --use-pep517 --upgrade -r requirements.txt
pip install xformers==0.0.16rc425

accelerate config

echo -e "setup finished! run \e[0;92m./gui.sh\e[0m to start"
`
and then re-execute the script，so I can train with xformers in ubuntu

**Comment by ProGamerGov** [comment]
@xinpengzhu I just tried your solution, and I still got the following error:



`TypeError: forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'`

**Comment by h3clikejava** [comment]
And...? How to fix it?
