### ISSUE TITLE
Long Pauses Between Epochs

### ISSUE THREAD

**Issue by official-elinas** [bmaltais/kohya_ss#36]
I noticed that there are long pauses between epochs, around 35-40 seconds. What is the reasoning behind this and is there a way to lower it significantly or disable it entirely?

I looked through the code and was not able to find anything specific to pausing between epochs. The other db extension that is for auto's ui has an option to pause between epochs (default 60s) but can be lowered to 1s if desired.

This also applies to native training. 

Edit: Looks like it hangs on line `206` in `train_db.py` every epoch.

Thanks.

**Comment by bmaltais** [comment]
This is something related with the latest accelerate version... I can't do much about it until kohya upgrade accelerate to another version as part of his supported code base... but glad you raised it so others are not taken aback by it ;-)

**Comment by official-elinas** [comment]
So I'm a bit confused. The latest version of `accelerate` is `0.15.0` (https://pypi.org/project/accelerate/). What do you mean by upgrading to another version when this is the latest version?

**Comment by DarkAlchy** [comment]
https://github.com/kohya-ss/sd-scripts/issues/125

**Comment by official-elinas** [comment]
I definitely agree. I also do not want to use repeats as epochs is a better measurement of progress. It almost seems like a workaround for whatever is wrong with the code.
