### ISSUE TITLE
Unicode Text Error in command prompt

### ISSUE THREAD

**Issue by samsonsite1** [bmaltais/kohya_ss#360]
Could you please remove all Japanese or Unicode text from the command prompt?

Older operating systems like Windows 7 can't display Unicode text in the command prompt, so it shows up as question marks or garbage text.  And the script may fail all together for some reason if the user has some kind of Windows Registry regedit hack to modify the codepage whenever a command prompt window is launched.  Thanks.

**Comment by bmaltais** [comment]
Sorry, You need to ask this to the Japanese person who write the actual trainer code... I don't think this will be well received unfortunatly...
