### ISSUE TITLE
Fatal error in launcher when trying to train Lora

### ISSUE THREAD

**Issue by Rkobenia** [bmaltais/kohya_ss#362]
Hello! I'm getting this errow when trying to lauch Lora training. My version is up to date, this happened before and after I installed the CUDNN 8.6, It happened on a 1660 Super, blamed it on that, but I just got a 3060 12 gb and it stil happens. Tried messing with parametres, does not seem to help. Could someone help with solving the issue?
![image](https://user-images.githubusercontent.com/28844167/224519995-e25a9078-1027-4d31-8559-eb91f7b74a85.png)

**Comment by bmaltais** [comment]
If you copy the command that start with accelerate and run it manually in a PowerShell window inside the repo folder does it work?

**Comment by Rkobenia** [comment]
Thank you for a quick response. it gave out this, created a "sample" folder inside the "model" folder and that's it

![image](https://user-images.githubusercontent.com/28844167/224521666-afa87d1b-da67-4fbd-ab4c-ed574a088cb9.png)

**Comment by bmaltais** [comment]
Look like the toml module is not installed. Run the upgrade.ps1 to install the missing module.

**Comment by Rkobenia** [comment]
Same errors after running the file (it said "already up to date and did nothing"), but reinstalling helped, thank you!

**Comment by bmaltais** [comment]
So running upgrade.ps1 and then starting the gui fixed the issue?

**Comment by Rkobenia** [comment]
Sorry, did not see the comment. No, it did not, it did nothing. I deleted the whole folder and reinstalled.
