### ISSUE TITLE
Defaults in GUI different from those suggested by Kohya, any reason? 

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [bmaltais/kohya_ss#37]
Hey. I love this GUI. I have gotten results with training a person. But It makes me wonder if the chosen GUI defaults should be kept that way or changed? Perhaps with the new changes on cloneofsimo's original lora repo, things might have changed?

If anyone can point me to resources where I can learn more about the chosen defaults ( and why they were chosen) and how I can adjust them to better suit my specs and training concept(s), I would really appreciate it! 

Also it would great if ' discussions ' can be opened on this repo.

**Comment by bmaltais** [comment]
Good idea for the discussion. I enabled the feature.
