### ISSUE TITLE
window server multi-GPU don't working

### ISSUE THREAD

**Issue by Bingohong** [bmaltais/kohya_ss#383]
when i run train_network.py by multi GPU, it show :

NOTE: Redirects are currently not supported in Windows or MacOs.
[E C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:793] [c10d] The client socket has timed out after 900s while trying to connect to (127.0.0.1, 29500).

the accelerate config is:

How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you wish to optimize your script with torch dynamo?[yes/NO]:no
Do you want to use DeepSpeed? [yes/NO]: no
Do you want to use FullyShardedDataParallel? [yes/NO]: no
Do you want to use Megatron-LM ? [yes/NO]: no
How many GPU(s) should be used for distributed training? [1]:2
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:[1,2]

How can i solve it ?? help help help.

**Comment by XellyWhy** [comment]
well it says its not supported in Windows, maybe because it uses fork() func, which is unix-only, and afaik gpu IDs starts from 0, so it should be [0,1]. But i can be wrong tho.

**Comment by bmaltais** [comment]
You should open an issue directly on kohya_ss sd-script repo about this as this is related to a trainer code issue and not directly with the GUI: https://github.com/kohya-ss/sd-scripts/issues
