### ISSUE TITLE
Are txt files automatically used during Lora training?

### ISSUE THREAD

**Issue by kyrieru** [bmaltais/kohya_ss#385]
I see the spot where it says "Caption Extension". If you put .txt here, will it use text files in the same way that you use [filewords] for hypernetworks in 1111?

Or are Lora files pretty much only meant for training a single subject, and not sorting out all the individual tags?

**Comment by baesky** [comment]
If my understanding is correct, you need to put the so-called "caption" into the corresponding .txt file, which needs to contain the token. LoRA training in kohya GUI is different from sd-dreambooth-extension in Auto1111. 
About multi-concept, I didn't do any such training, I guess you could put multiple directories (etc. named "[repeat-time]_[token] [class]") in the training data source directory.

**Comment by bmaltais** [comment]
It will indeed use all tags that are part of the .txt files during the training.

**Comment by kyrieru** [comment]
Gotcha, thanks for the info.
