### ISSUE TITLE
Can't Extract Lora if Convolution is set to 1 or Higher

### ISSUE THREAD

**Issue by DamonianoStudios** [bmaltais/kohya_ss#387]
I get the following error when I have convolution set to 1 or higher in the GUI with these settings.  It always stalls out at 300 and uses the exact same amount of memory when throwing the OOM error.
![image](https://user-images.githubusercontent.com/111029881/225320814-2b9877d6-578a-4d7c-abc5-392c87c6cdf1.png)

`./venv/Scripts/python.exe "networks\extract_lora_from_models.py" --save_precision bf16 --save_to "D:AI\StableDiffusion\stable-diffusion-webui-fresh2/models/lora/Zketchy_Locon_v1.safetensors" --model_org "D:/AI/StableDiffusion/stable-diffusion-webui-fresh2/models/Stable-diffusion/illuminatiDiffusionV1_v11.safetensors" --model_tuned "D:/AI/References/Sketchy/model/Zketchy_Lion_v1.safetensors" --dim 128 --conv_dim 1 --v2
loading SD model : D:/AI/StableDiffusion/stable-diffusion-webui-fresh2/models/Stable-diffusion/illuminatiDiffusionV1_v11.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : D:/AI/References/Sketchy/model/Zketchy_Lion_v1.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
create LoRA network. base dim (rank): 128, alpha: 128
apply LoRA to Conv2d with kernel size (3,3). dim (rank): 1, alpha: 1.0
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 278 modules.
create LoRA network. base dim (rank): 128, alpha: 128
apply LoRA to Conv2d with kernel size (3,3). dim (rank): 1, alpha: 1.0
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 278 modules.
calculating by svd
 72%|█████████████████████████████████████████████████████████▋                      | 300/416 [00:31<00:12,  9.52it/s]
Traceback (most recent call last):
  File "D:\AI\kohya_ss\networks\extract_lora_from_models.py", line 183, in <module>
    svd(args)
  File "D:\AI\kohya_ss\networks\extract_lora_from_models.py", line 116, in svd
    U, S, Vh = torch.linalg.svd(mat.to("cuda"))
RuntimeError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 24.00 GiB total capacity; 22.52 GiB already allocated; 0 bytes free; 22.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

**Comment by bmaltais** [comment]
You are running out of GPU memory when trying to extract the LoRA. Switch to `cpu` instead of `cuda` as the device

**Comment by DearDhruv** [comment]
I am having same issue, Can someone explain what is `Convolution` and how it impacts LoRA extraction?

**Comment by 2blackbar** [comment]
yes lora extraction is totally borked, great job not testing comits

**Comment by DamonianoStudios** [comment]
There's no reason I should be running of memory extracting a LoRA with a 3090... I should not be needing to use CPU

**Comment by bmaltais** [comment]
I do not write the extraction tool so this would be something to raise directly Kohya. Hope it will be fixed in a next update. I personally use the lycoeis_extract_locon.py tool under the tool folder it does a much better job. I have not created a GUI yet for it.

**Comment by DamonianoStudios** [comment]
Thanks, I will try that tool out in the meantime and also raise the issue with Kohya.

**Comment by bmaltais** [comment]
I have pushed the GUI for the LyCORIS LoCON extraction tool to the dev branch. You are welcome to try it.

You will fin the extraction tool under the Utilities tab:

![image](https://user-images.githubusercontent.com/7474674/225479210-4cf4a7c5-162c-4ace-92bb-65fa2b374480.png)

**Comment by 2blackbar** [comment]
I wish there was a way to extract the weights which are a bit overtrained when set to 1, currently its too weak for retaining identity of the subjects
