### ISSUE TITLE
returned non-zero exit status 3221225477

### ISSUE THREAD

**Issue by OmarRosaCar** [bmaltais/kohya_ss#390]
I achieve to fix my anterior error but I have a new error in this moment, anyone know how solve it? 
Pd: Sorry for my English
`
Folder 100_test: 600 steps
max_train_steps = 600
stop_text_encoder_training = 0
lr_warmup_steps = 60
accelerate launch --num_cpu_threads_per_process=8 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/models/protogenV22Anime_22.safetensors" --train_data_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/image" --resolution=512,512 --output_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/model" --logging_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --network_args "conv_dim=1" "conv_alpha=1" --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="60" --train_batch_size="1" --max_train_steps="600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="SGDNesterov8bit" --bucket_reso_steps=64 --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\Lora Training Data\Test\image\100_test contains 6 image files
600 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\Lora Training Data\Test\image\100_test"
    image_count: 6
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    is_reg: False
    class_tokens: test
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 501.30it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (192, 256), count: 100
bucket 1: resolution (192, 320), count: 100
bucket 2: resolution (384, 384), count: 100
bucket 3: resolution (448, 448), count: 100
bucket 4: resolution (512, 384), count: 100
bucket 5: resolution (576, 384), count: 100
mean ar error (without repeats): 0.04066859303092898
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
LoRA type changed...
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Archivos personales\Programación y Robotica\Python\Propio\IA\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Archivos personales\\Programación y Robotica\\Python\\Propio\\IA\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/models/protogenV22Anime_22.safetensors', '--train_data_dir=D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/image', '--resolution=512,512', '--output_dir=D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/model', '--logging_dir=D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_args', 'conv_dim=1', 'conv_alpha=1', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=60', '--train_batch_size=1', '--max_train_steps=600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=SGDNesterov8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 3221225477.
`

**Comment by bmaltais** [comment]
The error you're encountering is a subprocess.CalledProcessError, which is raised when a command executed by the subprocess module exits with a non-zero status. In this case, the command that was executed is the train_network.py script, and it exited with a non-zero status 3221225477.

Unfortunately, the error message does not provide enough information to pinpoint the exact issue within the train_network.py script.

What happen if you run the command manually in the powershell terminal:

`accelerate launch --num_cpu_threads_per_process=8 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/models/protogenV22Anime_22.safetensors" --train_data_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/image" --resolution=512,512 --output_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/model" --logging_dir="D:/Archivos personales/Programación y Robotica/Python/Propio/IA/kohya/Lora Training Data/Test/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --network_args "conv_dim=1" "conv_alpha=1" --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="60" --train_batch_size="1" --max_train_steps="600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="SGDNesterov8bit" --bucket_reso_steps=64 --xformers --bucket_no_upscale`

**Comment by K1LL3RPUNCH** [comment]
still a problem

**Comment by bmaltais** [comment]
Can you share the config file so I can try to reproduce the issue? I can’t trigger the specific issue so it is hard to fix something I can’t directly observe.
