### ISSUE TITLE
downloading pytorch_model.bin 1.7G  failed

### ISSUE THREAD

**Issue by ZhangWei5555** [bmaltais/kohya_ss#395]
downloading pytorch_model.bin 1.7G  failed
![image](https://user-images.githubusercontent.com/127751209/226086436-95c0b3e1-de4f-4800-8709-3dfca155810c.png)

**Comment by Pakase** [comment]
hello,have you solved the problem? I got the same problem...

**Comment by bmaltais** [comment]
Did this start with last night update? Was it working before?
