### ISSUE TITLE
What does number in folder name with images mean?

### ISSUE THREAD

**Issue by jnpatrick99** [bmaltais/kohya_ss#398]
I noticed there should be a number in folder name with images, like 100_myimages or 6_myimages, otherwise the training would crash. What does this number mean? Is 100 better than 6 or vice versa?

**Comment by DKnight54** [comment]
That's the number of times you want the model to repeat the images during training per epoch. AFAIK, from my testing, the number of times you repeat the images in training depends on the size of you data set (Fewer sample images means you want higher repeats), and depending on what you are training, you may need more repeats in order for SD to learn what it is you are trying to train.

A somewhat basic rule of thumb I've heard thrown around tho, is that for training faces, you's want to repeat each image at least 100 times, but that's usually with a data set of around 10~22 images.

**[A more detailed guide that I've been looking at](https://rentry.org/59xed3)** should point you in the right direction on this. But do be warned, it goes into a lot of details.
