### ISSUE TITLE
cp: file name, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by healthyfat** [bmaltais/kohya_ss#40]
Looks like it is missing following folders:

.\venv\Lib\site-packages\bitsandbytes\
.\venv\Lib\site-packages\bitsandbytes\cuda_setup

**Comment by bmaltais** [comment]
Hi,

This typically happen if you are installing modules outside the venv... or if you already have installed similar modules outside the venv.

One quick fix is to uninstall everything from the local env and re-install everything in the venv:

Open a new powershell window and run:

```
pip freeze > uninstall.txt
pip uninstall -r uninstall.txt
```

This can be cause if you did not give unrestricted script access to powershell so venv can work:

- Open an administrator powershell window
- Type `Set-ExecutionPolicy Unrestricted` and answer A
- Close admin powershell window

**Comment by healthyfat** [comment]
Thank you. That solved the problem.
