### ISSUE TITLE
Can't get xformers to work in Kohya SS - "Replace CrossAttention.forward to use xformers"

### ISSUE THREAD

**Issue by Lolamombobdoda** [bmaltais/kohya_ss#400]
I can use xformers without any issues in A1111 but when I train my LORA models in Kohya I keep getting this error.
I've tried to reinstall Kohya SS, Python 3.10, all my python modules, but I just can't get it to work.

My LORA training takes about 10 minutes per 1000 steps on my 3070 and I would like to see how much faster I can get it before deciding if I should invest in a new GPU or not.

Anyone else who've had this issue and managed to resolve it?

**Comment by mbastias** [comment]
I have the same issue on a new install that I had to do after an upgrade failed, I was able to use them on a previous version.

`RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 9 argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor? cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)`

**Comment by dionren** [comment]
Same problem, even after rebuild xformers.

TypeError: replace_unet_cross_attn_to_xformers.<locals>.forward_xformers() got an unexpected keyword argument 'encoder_hidden_states'

**Comment by bmaltais** [comment]
Is this on a fresh install of kohya_ss? Everything should be included during the installation to make this work. Are you running on Windows?

**Comment by mbastias** [comment]
Fresh install or updated (with git checkout) for me. Yes, running on Windows.

**Comment by bmaltais** [comment]
This is really strange then... and you use xformers 0.14?

**Comment by bmaltais** [comment]
When you go back a few release make sure to run upgrade.ps1 to install the modules for that release

**Comment by KhSTM** [comment]
i got "Replace CrossAttention.forward to use FlashAttention (not xformers)", what does that mean, my xformers doesn't work ?

**Comment by gitpulled** [comment]
anyone find a solution yet? i have to keep using a colab for this.

**Comment by jryebread** [comment]
Same issue i think, any solution?

Replace CrossAttention.forward to use xformers
ModuleNotFoundError: No module named 'xformers.ops'

**Comment by Lolamombobdoda** [comment]
> i got "Replace CrossAttention.forward to use FlashAttention (not xformers)", what does that mean, my xformers doesn't work ?

I got this when I switched from xformers to "memory efficient attention" instead. So doesn't seem like it's directly related to xformers then.



> Same issue i think, any solution?
> 
> Replace CrossAttention.forward to use xformers ModuleNotFoundError: No module named 'xformers.ops'

I've never gotten the "no module named xformers.ops" error, only the one about CrossAttention.forward.

**Comment by skein12** [comment]
same issue Replace CrossAttention.forward to use xformers, I have multiple Windows installs & 2 PCs every single one has this issue

can't train anything above 512

**Comment by Lolamombobdoda** [comment]
Tried to run upgrade.ps1.
Now nothing works. I get list index out of range error on line 914 in blocks.py of Gradio no matter what action I try. Reinstalling did not help, still not working.

**Comment by bmaltais** [comment]
Try deleting the full kohya_ss folder and start the installation from scratch. Something must be bad with the current venv and causing all kind of issues.

**Comment by jryebread** [comment]
still getting this issue even on a fresh install on a new ubuntu machine with new install of python3.10.6, tried both normal and dev branch, @bmaltais pls help 

RuntimeError: No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?

**Comment by SepticSpoons** [comment]
I'm also getting the same message as OP with a complete fresh install of this repo. When I pip list with venv active, it shows xformers installed, but still says "Replace CrossAttention.forward to use xformers" in the cmd window. Training still happens, but if it's not using xformers and could be faster, I'd very much like to figure that out.

**Comment by crappypatty** [comment]
mine got the same issue after the line: "Replace CrossAttention.forward to use xformers". the error said that xformers module is not found.

**Comment by Kadah** [comment]
I've had to work around this a few times before by compiling xformers from source instead.

xformers is cursed and precompiled wheels are not super portable between systems. It does not help that all the training scripts target a version that does not exist, so your stuck either with old archived dev builds or somebody's own build. The later does not tend to work on any OS different, new, or order than the one used to build the wheel.

I've had some lucky using upstream pre-release dev builds, but the more recent official builds target torch2 and that has its own complications.

If you're gonna try to install xformers from source, the particular commit I have had luck with is [`12c076d8ae9f5e3808842b528530cbbf7e3645ae`](https://github.com/facebookresearch/xformers/commit/12c076d8ae9f5e3808842b528530cbbf7e3645ae). If I remember right, that is the untagged point for the mythical `0.0.14-dev0` non-release. You will likely need to use cuda 11.2 to 11.7 for the compile, and possibly install ninja.

**Comment by crappypatty** [comment]
> I've had to work around this a few times before by compiling xformers from source instead.
> 
> xformers is cursed and precompiled wheels are not super portable between systems. It does not help that all the training scripts target a version that does not exist, so your stuck either with old archived dev builds or somebody's own build. The later does not tend to work on any OS different, new, or order than the one used to build the wheel.
> 
> I've had some lucky using upstream pre-release dev builds, but the more recent official builds target torch2 and that has its own complications.
> 
> If you're gonna try to install xformers from source, the particular commit I have had luck with is [`12c076d8ae9f5e3808842b528530cbbf7e3645ae`](https://github.com/facebookresearch/xformers/commit/12c076d8ae9f5e3808842b528530cbbf7e3645ae). This one is `0.0.17+12c076d.d20230411`. I have no idea what the untagged point is for the mythical `0.0.14-dev0` non-release. You will likely need to use cuda 11.2 to 11.7 for the compile, and possibly install ninja.


> Try deleting the full kohya_ss folder and start the installation from scratch. Something must be bad with the current venv and causing all kind of issues.

I deleted the folder and reinstall it again. I have all the required dependencies installed first on Python 3.10 then boot the Kohya setup. everything worked well and got my first model trained.

**Comment by KingWu** [comment]
I use python 3.10.10. Deleted the whole folder. Still get this error

**Comment by KingWu** [comment]
i am using MacOS with M2. Just modify the function `install_python_dependencies` in `setup.sh` to install xformers

```
"darwin"*) pip install torch==2.0.0 torchvision==0.15.1 \
    -f https://download.pytorch.org/whl/cpu/torch_stable.html >&3 &&
    pip install xformers==0.0.16 >&3 ;;
```

it works

**Comment by potatoker** [comment]
same error here, 0.0.14-dev0 xformer version did not work for me, (ubuntu 20.04, nvidia t4, pytorch  2.0.0+cu117)

**Comment by potatoker** [comment]
I don't think this issue should be closed, no common method to fix was mentioned here

**Comment by potatoker** [comment]
> i am using MacOS with M2. Just modify the function `install_python_dependencies` in `setup.sh` to install xformers
> 
> ```
> "darwin"*) pip install torch==2.0.0 torchvision==0.15.1 \
>     -f https://download.pytorch.org/whl/cpu/torch_stable.html >&3 &&
>     pip install xformers==0.0.16 >&3 ;;
> ```
> 
> run `./setup.sh -n` it works

this works for me,
for my machine( (ubuntu 20.04, nvidia t4, pytorch 2.0.0+cu117)) ,delete the whole venv diretory and edit and re operate the seup.sh , finally get rid of this error

**Comment by idrirap** [comment]
Did not work for me until I set it up with these versions (if it can help someone)
```
"linux-gnu"*) pip install torch==2.0.0 torchvision==0.15.1 \
    -f https://download.pytorch.org/whl/cu117 >&3 &&
    pip install xformers==0.0.17 >&3 ;;
```
ubuntu 20.04, python3.10, nvidia 3090

**Comment by rbs250** [comment]
> 

Did that help? how can do it for Windows?
