### ISSUE TITLE
arrows don't work in powershell

### ISSUE THREAD

**Issue by Nidehoggr** [bmaltais/kohya_ss#401]
during the instalation the gui i want to choose fp166 but when i press down arrow it just gives me the command i used before, and it doesn't choose the different option. (i tried to use numpad, it doesn't work too). I really need help with it! I tried to install this 7 or 8 times i already spent 4 hours trying to resolve this but i can't find any information in the internet.
![Screenshot_1](https://user-images.githubusercontent.com/118722786/226191900-09bd2e21-4af3-40fe-8cf2-304c42f787b1.png)
(it's screenshot from the youtube guide)

**Comment by bmaltais** [comment]
I can't do much about that one as this would require the maintainer of accelerate to fix this issue. I only leverage their module.

**Comment by Nidehoggr** [comment]
> I can't do much about that one as this would require the maintainer of accelerate to fix this issue. I only leverage their module.

So I can't fix it anyway?
