### ISSUE TITLE
Keep on getting this error and can't train Lora

### ISSUE THREAD

**Issue by humongous74** [bmaltais/kohya_ss#402]
Here's the error I get when I want to train a Lora:
Folder 125_Rev: 1500 steps
max_train_steps = 1500
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="E:/pics/Eva/birme-512x512/processed/Rev lora/image" --resolution=512,512 --output_dir="E:/pics/Eva/birme-512x512/processed/EvaG lora/model" --logging_dir="E:/pics/Eva/birme-512x512/processed/Rev lora/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="EvaG" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
usage: train_network.py [-h] [--v2] [--v_parameterization]
                        [--pretrained_model_name_or_path PRETRAINED_MODEL_NAME_OR_PATH]
                        [--train_data_dir TRAIN_DATA_DIR] [--shuffle_caption] [--caption_extension CAPTION_EXTENSION]
                        [--caption_extention CAPTION_EXTENTION] [--keep_tokens KEEP_TOKENS] [--color_aug] [--flip_aug]
                        [--face_crop_aug_range FACE_CROP_AUG_RANGE] [--random_crop] [--debug_dataset]
                        [--resolution RESOLUTION] [--cache_latents] [--enable_bucket]
                        [--min_bucket_reso MIN_BUCKET_RESO] [--max_bucket_reso MAX_BUCKET_RESO]
                        [--bucket_reso_steps BUCKET_RESO_STEPS] [--bucket_no_upscale]
                        [--caption_dropout_rate CAPTION_DROPOUT_RATE]
                        [--caption_dropout_every_n_epochs CAPTION_DROPOUT_EVERY_N_EPOCHS]
                        [--caption_tag_dropout_rate CAPTION_TAG_DROPOUT_RATE] [--reg_data_dir REG_DATA_DIR]
                        [--in_json IN_JSON] [--dataset_repeats DATASET_REPEATS] [--output_dir OUTPUT_DIR]
                        [--output_name OUTPUT_NAME] [--save_precision {None,float,fp16,bf16}]
                        [--save_every_n_epochs SAVE_EVERY_N_EPOCHS] [--save_n_epoch_ratio SAVE_N_EPOCH_RATIO]
                        [--save_last_n_epochs SAVE_LAST_N_EPOCHS]
                        [--save_last_n_epochs_state SAVE_LAST_N_EPOCHS_STATE] [--save_state] [--resume RESUME]
                        [--train_batch_size TRAIN_BATCH_SIZE] [--max_token_length {None,150,225}] [--mem_eff_attn]
                        [--xformers] [--vae VAE] [--max_train_steps MAX_TRAIN_STEPS]
                        [--max_train_epochs MAX_TRAIN_EPOCHS] [--max_data_loader_n_workers MAX_DATA_LOADER_N_WORKERS]
                        [--persistent_data_loader_workers] [--seed SEED] [--gradient_checkpointing]
                        [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS] [--mixed_precision {no,fp16,bf16}]
                        [--full_fp16] [--clip_skip CLIP_SKIP] [--logging_dir LOGGING_DIR] [--log_prefix LOG_PREFIX]
                        [--noise_offset NOISE_OFFSET] [--lowram] [--prior_loss_weight PRIOR_LOSS_WEIGHT]
                        [--no_metadata] [--save_model_as {None,ckpt,pt,safetensors}] [--unet_lr UNET_LR]
                        [--text_encoder_lr TEXT_ENCODER_LR] [--lr_scheduler_num_cycles LR_SCHEDULER_NUM_CYCLES]
                        [--lr_scheduler_power LR_SCHEDULER_POWER] [--network_weights NETWORK_WEIGHTS]
                        [--network_module NETWORK_MODULE] [--network_dim NETWORK_DIM] [--network_alpha NETWORK_ALPHA]
                        [--network_args [NETWORK_ARGS ...]] [--network_train_unet_only]
                        [--network_train_text_encoder_only] [--training_comment TRAINING_COMMENT]
train_network.py: error: ambiguous option: --lr_scheduler=constant could match --lr_scheduler_num_cycles, --lr_scheduler_power
Traceback (most recent call last):
  File "C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "R:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "R:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "R:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "R:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['R:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:/pics/Eva/birme-512x512/processed/Rev lora/image', '--resolution=512,512', '--output_dir=E:/pics/Eva/birme-512x512/processed/Rev lora/model', '--logging_dir=E:/pics/Eva/birme-512x512/processed/Rev lora/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Rev', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 2.
I get the same error if I have the 8bit adam on or off, if use bf16 or fp16. I have a RTX2060 super and it should be strong enough to do a Lora model. Can somebody please help me?

**Comment by bmaltais** [comment]
What happen if you run the command manually in the activated venv:

```
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="E:/pics/Eva/birme-512x512/processed/Rev lora/image" --resolution=512,512 --output_dir="E:/pics/Eva/birme-512x512/processed/EvaG lora/model" --logging_dir="E:/pics/Eva/birme-512x512/processed/Rev lora/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="EvaG" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="1500" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
```

**Comment by humongous74** [comment]
I got this:
[20:59:34] WARNING  The following values were not passed to `accelerate launch` and had defaults used      launch.py:887
                    instead:
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.
C:\Users\sweet\AppData\Local\Programs\Python\Python310\python.exe: can't open file 'B:\\kohya\\kohya_ss\\venv\\train_network.py': [Errno 2] No such file or directory
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:915 in launch_command                                                                     │
│                                                                                                  │
│   912 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   913 │   │   sagemaker_launcher(defaults, args)                                                 │
│   914 │   else:                                                                                  │
│ ❱ 915 │   │   simple_launcher(args)                                                              │
│   916                                                                                            │
│   917                                                                                            │
│   918 def main():                                                                                │
│                                                                                                  │
│ C:\Users\sweet\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:578 in simple_launcher                                                                    │
│                                                                                                  │
│   575 │   process.wait()                                                                         │
│   576 │   if process.returncode != 0:                                                            │
│   577 │   │   if not args.quiet:                                                                 │
│ ❱ 578 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   579 │   │   else:                                                                              │
│   580 │   │   │   sys.exit(1)                                                                    │
│   581                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\sweet\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5',
'--train_data_dir=E:/pics/Eva/birme-512x512/processed/Rev lora/image', '--resolution=512,512',
'--output_dir=E:/pics/Eva/birme-512x512/processed/EvaG lora/model',
'--logging_dir=E:/pics/Eva/birme-512x512/processed/Rev lora/log', '--network_alpha=128', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128',
'--output_name=EvaG', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant',
'--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=bf16',
'--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1',
'--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 2.

**Comment by bmaltais** [comment]
Something appear to be wrong with your setup. Did youo folow all the steps for the installation? It can't find train_db.py... but the path it is listing is wrong... it should not look for that file in venv.

I suggest you delete the full kohya_ss folder and try to install from scratch following the installation instruction again.

**Comment by humongous74** [comment]
I will do that to see if it works. Thank you for your help.

**Comment by humongous74** [comment]
Well I made it work after re-installing kohya. Finally I was able to make a Lora, yay. Thanks again for your help and for creating kohya.
