### ISSUE TITLE
feature request - delete duplicate, similar images with ML

### ISSUE THREAD

**Issue by jonwong666** [bmaltais/kohya_ss#405]
this would be amazing to preprocess a dataset , to locate similar or duplicate images before sending to kohya

**Comment by bmaltais** [comment]
If someone knows of a good tool that could be called by the GUI I could try to add it.

**Comment by jonwong666** [comment]
Im currently using DupliGuru https://github.com/arsenetar/dupeguru on the desktop, it works ok, but I don't think its based on ML , so it can be a bit hit and miss on some similar looking images, it does a good job at find exact duplicates tho.
https://github.com/arsenetar/dupeguru
