### ISSUE TITLE
low vram?

### ISSUE THREAD

**Issue by GeoTronZ** [bmaltais/kohya_ss#407]
![help](https://user-images.githubusercontent.com/32981749/226387340-df5fb036-0bb8-4014-8d75-9bf230a52afa.PNG)
does this show bcz of low vram?

**Comment by 2blackbar** [comment]
its probably 8bit adam, it was possible to disbale it but some smartass  jokester removed it

**Comment by bmaltais** [comment]
If you don't want to use 8bitadam in this new release just select AdamW for the optimized. It is the same as not selecting the checkbox in the previous releases.
