### ISSUE TITLE
Alternative CUDNN install? Files are suspicious.

### ISSUE THREAD

**Issue by GreatSphynx** [bmaltais/kohya_ss#409]
the CUDNN files included in this get flagged as having a trojan. even if it's a false positive i'm a little hesitant now to try installing it using the suggested method. especially after changing the powershell execution policy. I have CUDA toolkit and the CUDNN 8.6.0 official package from Nvidia, I'm just not sure how to get it installed with this package.

**Comment by PlayingKarrde** [comment]
Came here to ask the same thing. Seems a bit too suspect to me...
