### ISSUE TITLE
problem with adamw8bit

### ISSUE THREAD

**Issue by GeoTronZ** [bmaltais/kohya_ss#415]
when I use adamw8bit I get error return 1 but when I use like just adamw it works, but dont get good results is there any way to use adamw8bits?

**Comment by bmaltais** [comment]
The new version of kohya_ss code support multiple options for optimized. AdamW8bit is the same thing as the ole 8bitadam checkbox... but not all card play well with bitsandbytes... so 8bitadam support is not universal.

AdamW actually gives better results than AdamW8bit... but take more VRAM. So if you can use AdamW you are alreade ahead from a quality point of view.

**Comment by rafstahelin** [comment]
> The new version of kohya_ss code support multiple options for optimized. AdamW8bit is the same thing as the ole 8bitadam checkbox... but not all card play well with bitsandbytes... so 8bitadam support is not universal.
> 
> 
> 
> AdamW actually gives better results than AdamW8bit... but take more VRAM. So if you can use AdamW you are alreade ahead from a quality point of view.

@bmaltais how can this optimiser just stop working in full fine tuning ?

**Comment by bmaltais** [comment]
Not sure… this is probably a question for kohya… or other finetuners.

**Comment by rafstahelin** [comment]
> Not sure… this is probably a question for kohya… or other finetuners.

Gotcha
