### ISSUE TITLE
Won't run in runpod - _tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by jcrsantiago** [bmaltais/kohya_ss#419]
When I try to run it as a jupyter notebook in runpod I get this error any time I try to click on buttons in the GUI.

`_tkinter.TclError: no display name and no $DISPLAY environment variable`

If I try to give display a value it says

`_tkinter.TclError: couldn't connect to display ":0"`

**Comment by bmaltais** [comment]
Hummm, I don't use runpod so I can't troubleshoot... but it appear to be related to the lack of $DISPLAY environment variable.

Have you tried to create a fake DISPLAY like this:

`export DISPLAY=:1`

**Comment by HuanchengHu** [comment]
Unfortunately I encountered the same problem. And I am afraid export DISPLAY=:1 doesn't work even though I tried to use Xvfb :1 -screen 0 1024x768x24 & to fake one.

**Comment by Norian11** [comment]
I always just paste the path of the folders as most of the guides says, right click in the folder and copy path, and you have to add a / at the beginning because is always missing that I think. I'm gonna try the new update to see if now works in pods without errors

**Comment by kopyl** [comment]
So any fix for this? Or this is yet another tool which doesn't work?

**Comment by bmaltais** [comment]
Look like if you don't use the file or folder icons but instead type the oath in the corresponding fields you will be ok.

**Comment by jcrsantiago** [comment]
Can this be a feature request? It works on other UIs so there must be a way to get it to work for this.

**Comment by bmaltais** [comment]
> Can this be a feature request? It works on other UIs so there must be a way to get it to work for this.

I will gladly take. PR for code update to make it better on colab if you have an idea on how it could be better on the platform. I wrote it for Windows but others are welcome to contribute for better support on other platforms.

**Comment by bmaltais** [comment]
I have pushed the code to the dev branch. Give it a try. It should no longer try to show the file GUI on Runpod...

**Comment by lucidyan** [comment]
Same problem here, running on remote server with port-forwarding

**Comment by jstayco** [comment]
So this is most likely stemming from the use of Tk to display windows. Right now I'm doing a lot of refactoring and work to get those windows showing in macOS (it's required to be in a different thread than main due to extra OS security policies.). Maybe once we get to that point I can start looking at what it would take to go the rest of the way for containerized uses. I would eventually like to create a Dockerfile for everyone to use, but I have a ways to go to get to that point.

**Comment by lucidyan** [comment]
In the AUTOMATIC1111, there are no modal dialogs at all, only text inputs. I never understood why, but now I understand. Tk relies on an X-server, and forwarding can be problematic. In my situation, the remote machine does not have an X-server, also making the implementation of fake X-servers functioning properly is not easy too.

**Comment by jstayco** [comment]
I did see a few posts about how to forward an X server to get those Tk dialogs working. I don't know what solution (if any) we can come up with, but that definitely won't be it. I'd never expose someone's public server to X forwarding due to security concerns. I think I'll leave that one up to users if they want to go off path.

**Comment by Cyopathic** [comment]
I am experiencing the same problem in jupyter notebook. Has there been any luck in finding a solution?

**Comment by jstayco** [comment]
That exactly. This issue took a backseat, since copy/pasting folder gets the job done and functionality occurs. Right now I'm focusing on getting a nicer installer going to hopefully avoid having all these manual tweaks and setup issues I see.

**Comment by mcmanussean** [comment]
I found this same issue on my setup. I have Kohya running on an Ubuntu server on my network which I access from another machine. I can paste the directories in fine but the issue I'm having is when I click "Train" i get the "no display name...." error and it won't train. I'm guessing there's a modal triggered at that point that is breaking the script and preventing training. Is there a dev branch I can use instead for now?

**Comment by lunar333** [comment]
> I found this same issue on my setup. I have Kohya running on an Ubuntu server on my network which I access from another machine. I can paste the directories in fine but the issue I'm having is when I click "Train" i get the "no display name...." error and it won't train. I'm guessing there's a modal triggered at that point that is breaking the script and preventing training. Is there a dev branch I can use instead for now?

same problem

**Comment by lunar333** [comment]
> I found this same issue on my setup. I have Kohya running on an Ubuntu server on my network which I access from another machine. I can paste the directories in fine but the issue I'm having is when I click "Train" i get the "no display name...." error and it won't train. I'm guessing there's a modal triggered at that point that is breaking the script and preventing training. Is there a dev branch I can use instead for now?

but I found that if I load the config file for training ,this error happened, but if I don't, it won't

**Comment by jstayco** [comment]
Try running it with the --headless option. That should bypass the Tk windows that give the error you're seeing.

**Comment by dcsan** [comment]
is there a way to get this to work with a remote cloud GPU, eg setting $DISPLAY? this is needed for vast and runpod 

common problem much discussion eg 
https://github.com/bmaltais/kohya_ss/issues/760
https://github.com/bmaltais/kohya_ss/issues/713

**Comment by dcsan** [comment]
when running headless, can we point at a config file to just train without any of the UI?
then we can just edit that config file in future.

**Comment by orcinus** [comment]
> Try running it with the --headless option. That should bypass the Tk windows that give the error you're seeing.

It doesn't, at least not everywhere - try clicking on the "Color augmentation" option.
It also doesn't bypass anything, it just removes the GUI elements that would've opened a Tk modal.
For things that have a fallback (i.e. entering the path manually) this works as a solution, for things that don't it doesn't really do anything, unfortunately.
