### ISSUE TITLE
ModuleNotFoundError: No module named 'library.lpw_stable_diffusion' & raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError

### ISSUE THREAD

**Issue by AniMoster** [bmaltais/kohya_ss#429]
I'm getting the following error even after replacing all 3 instances of train.util.py like mentioned [Here](https://github.com/bmaltais/kohya_ss/issues/192#issuecomment-1436305792)

Can someone please help resolve this?

`Traceback (most recent call last): 
File "C:\Users\name\Kohya\kohya_ss\train_network.py", line 16, in <module> 
import library.train_util as train_util File "C:\Users\name\Kohya\kohya_ss\library\train_util.py", line 59, in <module> 
from library.lpw_stable_diffusion import StableDiffusionLongPromptWeightingPipeline 
ModuleNotFoundError: No module named 'library.lpw_stable_diffusion' 
Traceback (most recent call last): 
File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main 
return _run_code(code, main_globals, None, 
File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code 
exec(code, run_globals) 
File "C:\Users\name\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module> 
File "C:\Users\name\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main args.func(args) 
File "C:\Users\name\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command simple_launcher(args) 
File "C:\Users\name\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher 

raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) 
subprocess.CalledProcessError: Command '['C:\\Users\\name\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=C:/Users/name/stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=C:/Users/name/Kohya/LoRA/img', '--resolution=512,512', '--output_dir=C:/Users/name/Kohya/LoRA/model', '--logging_dir=C:/Users/name/Kohya/LoRA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Ayane Sakura', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=4700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers']' returned non-zero exit status 1.`

**Comment by bmaltais** [comment]
Did you run upgrade.ps1

**Comment by AniMoster** [comment]
No. If I have to run it, please leave the command to run it. Thank You

**Comment by AniMoster** [comment]
Even windows powershell gives error:

git pull
fatal: not a git repository (or any of the parent directories): .git

**Comment by bmaltais** [comment]
Delete the kohya_ss folder and start over

**Comment by AniMoster** [comment]
Ok thank you for the help. BTW do you have a version recommendation?

**Comment by bmaltais** [comment]
The latest one is pretty stable at the moment
