### ISSUE TITLE
Regularisation image affect the final train?!

### ISSUE THREAD

**Issue by figurehunt** [bmaltais/kohya_ss#432]
Hi there,

i am training a girl. And i add the some girl with similar clothes(actually not that similar) in the Regularisation folder.
but the result made me comfused. my girl's clothes mix the ones in Regularisation images. 
I thought the Regularisation images will help AI to memorize the original clothes, but it didn't.

And i have tried for at least three times, the problem still existed. pls help and see if any wrong with my configuration.
I use the kohya_ss GUI

tks!

**Comment by bmaltais** [comment]
Regularisation images are not supposed to be images of the model you want to train but rather images of what the model would produce...
