### ISSUE TITLE
Possible solution for loss=nan in 16xx series cards.

### ISSUE THREAD

**Issue by mainsplainer** [bmaltais/kohya_ss#436]
The 16xx series cards do not seem to support fp16 by default (running stable diffusion in fp16 mode generated black images).
This was fixed here > https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4407

![image](https://user-images.githubusercontent.com/46342367/227222344-bd3b1dce-a504-429b-9a97-14f0722a618d.png)

Enabling benchmark mode could potentially fix the issue of loss=nan on these cards.

**Comment by PaperOrb** [comment]
Currently having issues with this myself on a 1660ti 6gb. Let me know what info would be useful to post.

**Comment by yoinked-h** [comment]
author of this pr, i have no clue why it fixes that; you might also need to enable cudnn, TU117 is a cursed mess
