### ISSUE TITLE
Quick questions about caption vs folder name and more

### ISSUE THREAD

**Issue by Norian11** [bmaltais/kohya_ss#440]
I have read in the Collab version that if you choose to give the folders a name token you shouldn't include that same token in your captions because it could create bad results.
Could this be true?

Also whats the function of the argument keep_tokens=" "
It means that it use the tokens of my folder name or also it's referring to the captions, I don't fully understand what I does.

Do you think 32dim 4alpha is enough to train a Lora with 900 images, 32 epoch and 4 repeats? I'm thinking reducing dataset because the results are bad.

Someone have tested if Adaptation or Lion give better results that Adam8Bit, because I saw each one has its own learning rate parameters

**Comment by bmaltais** [comment]
If you have captions files and they are used then the folder name is not used .. so you need to put the token name in the caption in that case.
