### ISSUE TITLE
Can't use lora with StableDiffusionPipeline

### ISSUE THREAD

**Issue by kopyl** [bmaltais/kohya_ss#458]
Do you have any step by step tutorials which could help me run .safetensors Lora the same way i do in WebUI with prompts like

`<lora:100img_1-5:2> smiling robot`

I tried this, but it does not seem to work:

```from diffusers import StableDiffusionPipeline
import torch

device = "cuda"


pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16, safety_checker=None)
lora_path = "100img_1-5.safetensors"
pipe.unet.load_attn_procs(lora_path)
pipe.to("cuda")

prompt = "A pokemon with blue eyes."
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5).images[0]
image.save("pokemon.png")
```

I also tried to convert it to diffusers format, but i either get errors on conversions or a huge diffusers directory (around 5GB), which nobody needs.

**Comment by bmaltais** [comment]
The LoRA created by Kohya are not supported by diffusers. Their implementation of LoRA only work on a subset of layers and will not work properly 

Perhaps Kohya could add an option to create diffuser compatible LoRA... But they would be of lesser fidelity.

**Comment by kopyl** [comment]
Hm... Is there any other way to programmatically generate images with LoRA trained in Kohya GUI?

Or any other way to train/convert LoRA / anything else which would work the same as Kohya LoRA which i could use programmatically to generate images?
