### ISSUE TITLE
what are all settings in default_config.yaml mean?

### ISSUE THREAD

**Issue by komica5566** [bmaltais/kohya_ss#459]
I know this question is very stupid but my powershell can't choose(arrow key can't be function in powershell for some reason)

which setting is for use FP16?

mine is

command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

**Comment by VeyDlin** [comment]
the same problem, the installation script crashed at this stage
