### ISSUE TITLE
UnetLR and TextEnc in Metadata of LoRa

### ISSUE THREAD

**Issue by noseconexoes** [bmaltais/kohya_ss#467]
Hello bmaltais,

First of all, congratulations for the work.
A question: Is it possible to put the informations of UnetLR and TextEnc in metadata of the LoRa files?

Thanks and have a nice week!

**Comment by bmaltais** [comment]
Thank you for your appreciation. It is something that would be best addressed directly with Kohya in his GitHub repo. That way when he add it will be added to the GUI.

**Comment by noseconexoes** [comment]
@bmaltais, sorry bout mixing the topics, but can you "unhide" the base utiization of D-adaptation withe min-snr in a video or explaining how to use?
I´ve already try a lot of configs but LoRa got burn in the first 100 steps....
Thanks!

**Comment by bmaltais** [comment]
> @bmaltais, sorry bout mixing the topics, but can you "unhide" the base utiization of D-adaptation withe min-snr in a video or explaining how to use? I´ve already try a lot of configs but LoRa got burn in the first 100 steps.... Thanks!

This is something that need to be updated within the trainer code itself... essentially under the log section. I find that the current code base is very disparate when it comes to what it logs and how it logs from one trainer to the next. Some major cleanup is needed there... but this is really part of kohya_ss code.

**Comment by noseconexoes** [comment]
Another thing: Is there a way to put a stop button next to the "Train Model"?
