### ISSUE TITLE
Is it possible to use the newest version of sd-scripts with current version of the GUI

### ISSUE THREAD

**Issue by DKnight54** [bmaltais/kohya_ss#472]
Hi, just wondering if it's possible to use the latest releases of Kohya's [SD-Scripts](https://github.com/kohya-ss/sd-scripts) before the GUI has been updated to reflect?

Of course I understand that it means the lastest features (such as the SNR implementation) would not have GUI elements and would need to have the arguements passed in via the Additional parameters field, and there is a risk of breaking the GUI if there are large changes to the training scripts, but is it doable? If so, how should I do it?

**Comment by bmaltais** [comment]
Hi, sometime I will merge the sd-script update without updating the GUI right away. I discovered a bug with the sd-script and reported it to kohya. He has now fixed the issue and I have pushed the latest sd-script code in the last release.

I hope this will address what you were looking at using. The SNR implementation is also done in the GUI ;-)

**Comment by DKnight54** [comment]
LOL. I also noticed that you updated it not too long after I posted. And yup, I was hoping to try out the SNR implementation.
