### ISSUE TITLE
No matching distribution found for lycoris_lora==0.1.4

### ISSUE THREAD

**Issue by zzisme1** [bmaltais/kohya_ss#481]
ERROR: Could not find a version that satisfies the requirement lycoris_lora==0.1.4 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.1.0.dev0, 0.1.0, 0.1.1, 0.1.2, 0.1.3.dev0, 0.1.3)
ERROR: No matching distribution found for lycoris_lora==0.1.4

**Comment by bmaltais** [comment]
Did you run `upgrade.ps1` to install the latest python modules?

**Comment by zzisme1** [comment]
> Did you run `upgrade.ps1` to install the latest python modules? I can install this exact release just fine on my computer.

I used :
git pull

.\venv\Scripts\activate

pip install --use-pep517 --upgrade -r

**Comment by bmaltais** [comment]
I can't reproduce the issue at my end. Let see if others report it. You can go back to the previous release with

git checkout release_name
./Upgrade.ps1

**Comment by zzisme1** [comment]
> I can't reproduce the issue at my end. Let see if others report it. You can go back to the previous release with
> 
> git checkout release_name ./Upgrade.ps1

thanks

**Comment by zzisme1** [comment]
> same error

I rolled back to the previous version and solved the problem

**Comment by bmaltais** [comment]
Humm .. I wonder why some users can download the code and not others...
Need to research...

**Comment by zentlemanx** [comment]
> > same error
> 
> I rolled back to the previous version and solved the problem

metoo
