### ISSUE TITLE
How is num_epochs calculated?

### ISSUE THREAD

**Issue by specblades** [bmaltais/kohya_ss#491]
Cant understand, how is num_epochs calculated. 
I use, for example, 16 repeats, 5 epochs (in gui), 16 grad accum steps. And i get 40 epoch.
Why batches per epoch is 32?
What? 😢
Help me out pls
<img width="286" alt="image" src="https://user-images.githubusercontent.com/113993746/229115467-81d421d9-5251-4a65-8898-0b6ebd9c577b.png">

**Comment by bmaltais** [comment]
Kohya's code is a bit obscure as to how this is calculated... Even I don't totally understand the logic.

I can tell you how I calculate steps I feed to Kohya... But how it handle this to figure out epoch I am not sure

**Comment by specblades** [comment]
Please explain to me your method
