### ISSUE TITLE
what's mean:ModuleNotFoundError: No module named 'library.tensorboard_gui'

### ISSUE THREAD

**Issue by g558800** [bmaltais/kohya_ss#495]
Validating that requirements are satisfied.
All requirements satisfied.
Traceback (most recent call last):
  File "H:\AI\kohya_ss\kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "H:\AI\kohya_ss\dreambooth_gui.py", line 31, in <module>
    from library.tensorboard_gui import (
ModuleNotFoundError: No module named 'library.tensorboard_gui'

**Comment by bmaltais** [comment]
This is a strange one... Really odd. Did it ever worked on your computer?

**Comment by g558800** [comment]
Yes, it was running normally before the update. This will be prompted after the update.

**Comment by bmaltais** [comment]
Weird... I will check the code and see if there is something... But it work fu e at my end so...

**Comment by bmaltais** [comment]
OK, I deleted the venv folder and redid the installation from scratch on my system and I did not have the error.

I suggest you try the same, something must be causing this within the venv... possibly a package that did not install properly. Deleting the venv and redoing the install should fix things up.

**Comment by g558800** [comment]
Okay, I'll try reinstalling.

**Comment by bmaltais** [comment]
Interesting... After reinstalling the wd14 tagger does not work anymore ... Hummm

**Comment by g558800** [comment]
So, he's the problem?

**Comment by bmaltais** [comment]
> So, he's the problem?

Unknown... But hard to tell where the issue is. Each user has a different system with different config and software so weird failure case is to be expected.

**Comment by g558800** [comment]
As you said, I will reinstall it and the software will work properly. And replaced the torch with 1.13.1+cu117, which also works properly.
