### ISSUE TITLE
Error when installing on ubuntu

### ISSUE THREAD

**Issue by elchupacabrinski** [bmaltais/kohya_ss#514]
Seems like some files are not where they are supposed to be:

ERROR: HTTP error 404 while getting https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/downloadlinux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl
ERROR: Could not install requirement xformers==0.0.14.dev0 from https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/downloadlinux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/downloadlinux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl for URL https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/downloadlinux/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl

**Comment by bmaltais** [comment]
I hope @jstayco can help with that one.

**Comment by jstayco** [comment]
@bmaltais Thanks for the ping. Looking into it.
