### ISSUE TITLE
Is it possible to merge the LoRA safetensor file into a checkpoint?

### ISSUE THREAD

**Issue by dpyy** [bmaltais/kohya_ss#519]
Let's say I have an environment that can only use regular checkpoint but I already have this LoRA file in safetensor format trained by Kohya. How can I bake it into a target model?

**Comment by bmaltais** [comment]
Sorry, been busy at work. Yes, you can do it manually at the CLI using the `networks/merge_lora.py` script.

**Comment by Norian11** [comment]
Sorry Bmaltais, could you explain a little how to do this, should we rewrite the parts of that file with our parameters and then run it, or there is a code to do that automatically?

I saw someone using this code:  (myenv) I:\SSD2\sd-scripts\networks>merge_lora.py --sd_model model.ckpt --save_to model_lora_merge.safetensors --models lora.safetensors 0.4

Is it the correct way to merge a lora into a checkpoint?

**Comment by SBlack202** [comment]
Hello. I've been attempting to do this. I can't say I'm the most experienced. When attempting to do so though, I am met with the response that --save and similar commands 'aren't known commands'. I am attempting to do this in a command line. I'm assuming I am just doing something wrong, but I don't know where to go from here. Any advice would be invaluable.
