### ISSUE TITLE
No data found. Please verify arguments 

### ISSUE THREAD

**Issue by healthyfat** [bmaltais/kohya_ss#52]
C:\Programs\bmaltais GUI\kohya_ss\venv\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments / 画像がありません。引数指定を確認してください

**Comment by healthyfat** [comment]
Dreambooth Lora training.

**Comment by bmaltais** [comment]
Try using the tool to prepare the folder structure for dreambooth. This will ensure all is proper for the training as far as folder names and all is concerned.

**Comment by healthyfat** [comment]
I did. Many times, but still getting same error.

**Comment by marmosetjones** [comment]
Same issue and solution for me.
