### ISSUE TITLE
problem when launching ./gui.sh

### ISSUE THREAD

**Issue by uyheangte** [bmaltais/kohya_ss#520]
I try to install kohya_ss on my iMac 27" Intel, and it seems that lots of requirements are missing. This this the logs after entering `./gui.sh `as below:
```
Validating that requirements are satisfied.
ERROR: Could not detect requirement name for 'git+https://github.com/KohakuBlueleaf/LyCORIS.git@c3d925421209a22a60d863ffa3de0b3e7e89f047', please specify one with #egg=your_package_name
Error: The following packages are missing:
 - accelerate==0.15.0
 - albumentations==1.3.0
 - altair==4.2.2
 - bitsandbytes==0.35.0
 - dadaptation==1.5
 - diffusers[torch]==0.10.2
 - easygui==0.98.3
 - einops==0.6.0
 - ftfy==6.1.1
 - gradio==3.23.0; sys_platform == 'darwin'
 - lion-pytorch==0.0.6
 - opencv-python==4.7.0.68
 - pytorch-lightning==1.9.0
 - safetensors==0.2.6
 - tensorboard==2.12.1 ; sys_platform == 'darwin'
 - tk==0.1.0
 - toml==0.10.2
 - transformers==4.26.0
 - voluptuous==0.13.1
 - fairscale==0.4.13
 - timm==0.6.12
 - huggingface-hub==0.13.0; sys_platform == 'darwin'
 - tensorflow-macos==2.12.0; sys_platform == 'darwin'
 - lycoris-lora @ git+https://github.com/KohakuBlueleaf/LyCORIS.git@c3d925421209a22a60d863ffa3de0b3e7e89f047

Run upgrade.sh or pip install -U -r requirements.txt to resolve the missing requirements listed above...
```

Once I run `pip install -U -r requirements.txt` , it returns 
```
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.12.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.12.0
```

I wish anyone could have me solve this! Much appreciated! 🙏

**Comment by suebphatt** [comment]
same problem here, I'm trying to run via runpod.io though

**Comment by bmaltais** [comment]
I wish I could help but I don't have an Intel Mac... Hope @jstayco can shade some light as to why the script is failing on runpod and Intel Mac.

**Comment by uyheangte** [comment]
> Tensorflow-macos is a tensorflow module designed to use the ANE on M1+ Macs. I didn't think anybody would want to run this on an older Intel CPU to be honest. I can see if there is a way to detect that and adjust accordingly, but I'm not sure on that one. I'll get back to you.

Thank you @jstayco, I managed to solve it by creating a virtual environment following #524 . I can run kohya_ss inside the virtual environment.

**Comment by jstayco** [comment]
Glad to hear it! I'm hoping that one isn't a problem going forward with the newer detection in setup.sh.

**Comment by momikiii** [comment]
I have the same problem, even after typing the pip install -U -r requirements.txt command, the same error is reported

**Comment by jstayco** [comment]
Try deleting your kohya_ss/venv folder and rerunning setup.sh. The specific line for tensorflow if you need to do it manually (and you shouldn't) is: `pip install tensorflow==2.12.0`
