### ISSUE TITLE
Multi GPU Koyha Training (lora) 

### ISSUE THREAD

**Issue by EKI-INDRADI** [bmaltais/kohya_ss#521]
prepare dataset
prepare accelerator
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [x-tags.net]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:558] [c10d] The client socket has failed to connect to [x-tags.net]:29500 (system error: 10049 - The requested address is not valid in its context.).
Traceback (most recent call last):
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\train_network.py", line 724, in <module>
    train(args)
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\train_network.py", line 123, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\library\train_util.py", line 2602, in prepare_accelerator
    accelerator = Accelerator(
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 308, in __init__
    self.state = AcceleratorState(
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\venv\lib\site-packages\accelerate\state.py", line 150, in __init__
    torch.distributed.init_process_group(backend="nccl", **kwargs)
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 602, in init_process_group
    default_pg = _new_process_group_helper(
  File "V:\STABLE_DIFFUSION\KOHYA\kohya_ss\venv\lib\site-packages\torch\distributed\distributed_c10d.py", line 727, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16972) of binary: V:\STABLE_DIFFUSION\KOHYA\kohya_ss\venv\Scripts\python.exe

nvidia-smi

Sun Apr  2 21:30:47 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.41                 Driver Version: 531.41       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060       WDDM | 00000000:23:00.0 Off |                  N/A |
|  0%   34C    P8                3W / 170W|      0MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3060       WDDM | 00000000:2D:00.0  On |                  N/A |
|  0%   44C    P8               15W / 170W|    777MiB / 12288MiB |     15%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

default_config.yaml

command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

**Comment by EKI-INDRADI** [comment]
===================
SOLVED
===================
No distributed training  <<< DONT USE

sorry

**Comment by EKI-INDRADI** [comment]
====

SOLVED

 GPU = 0 <<< VRAM +CUDA
 GPU = 1  <<< CUDA only
 
 NOTE : running by default "all" or "0,1"

**Comment by FurkanGozukara** [comment]
Dis you find how to make script use second gpu?

**Comment by aaronkingdom** [comment]
@FurkanGozukara    --gpu_ids=1

**Comment by maxenko** [comment]
I am still unable to get it to train on two GPUs. If monitored with GPUShark, only one GPU is utilized.

I've configured as per @EKI-INDRADI last post. When I start gui.bat the printout is:

```
(venv) D:\stablediffusion\kohya_ss>gui.bat
14:02:31-644822 INFO     Version: 4f0e1f5 Mon Jun 19 19:33:04 2023 -0400
14:02:31-654778 INFO     nVidia toolkit detected
14:02:33-751563 INFO     Torch 2.0.1+cu118
14:02:33-835197 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:02:33-839180 INFO     Torch detected GPU: NVIDIA RTX A6000 VRAM 49140 Arch (8, 6) Cores 84
14:02:33-842169 INFO     Verifying requirements
14:02:36-950506 INFO     headless: False
14:02:36-956480 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860
```

Is the problem perhaps with PyTorch not seeing the multiple GPUs?

I've added:
```
set CUDA_VISIBLE_DEVICES=0,1
```
to gui.bat, which doesn't seem to help.


Any advice would be appreciated.

**Comment by Kiraxrune** [comment]
> ====
> 
> SOLVED
> 
> GPU = 0 <<< VRAM +CUDA GPU = 1 <<< CUDA only
> 
> NOTE : running by default "all" or "0,1"
> 
> .\venv\Scripts\activate accelerate config
> 
> Which type of machine are you using? No distributed training Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]:NO Do you wish to optimize your script with torch dynamo?[yes/NO]:NO Do you want to use DeepSpeed? [yes/NO]: NO What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:0,1 Do you wish to use FP16 or BF16 (mixed precision)? fp16

Thanks followed this and Reinstalled into a new folder and worked!

**Comment by JokerGT** [comment]
i just tried it with 2 A6000

for some reason, i get 1,44s per iteration, regardless if i am using 1 card or 2 cards... 
nvidia-smi shows, that both cards getting utilized, but why i dont see any speed changes here ?
would be nice if someone could explain this 

also both cards load the model into vram and use about 27G of VRAM (out of 48). 
this cannot be correct... i should see changes to the speed. should i ? Also i dont know how to set

```
GPU = 0 <<< VRAM +CUDA
GPU = 1 <<< CUDA only
```
any help would be appreciated. One training otherwise needs 3 hours...

**Comment by kmacmcfarlane** [comment]
@JokerGT I'm also trying to learn about how this is implemented right now. I'm mulling buying a A6000/RTX 6000 ADA/A100 since my training set seems to want 27GB VRAM. I understand there are ways to use pytorch that will split things up (various options as to how) across multiple cards/nodes. I have a 3090ti with 24GB VRAM, and it'd be great if I could buy a second and train on SDXL, but if not I'm willing to buy a card with more VRAM. Also, anyone in the Nvidia Inception program that reads this DM me plz :-)

**Comment by kmacmcfarlane** [comment]
This commit seems to imply that there's some level of multi-gpu support via accelerator/pytorch https://github.com/kohya-ss/sd-scripts/commit/87846c043f344cf153bb1184047c943c153389f0

**Comment by luckiskind** [comment]
> The accelerator use NCCL as default backend, but NCCL has not released a Windows version, you can change it to Gloo by editing `library/train_util.py`.
> 
> * original
> 
> ```python
>     accelerator = Accelerator(
>         gradient_accumulation_steps=args.gradient_accumulation_steps,
>         mixed_precision=args.mixed_precision,
>         log_with=log_with,
>         project_dir=logging_dir,
>     )
> ```
> 
> * edited
> 
> ```python
>     from accelerate.utils import InitProcessGroupKwargs
>     accelerator = Accelerator(
>         gradient_accumulation_steps=args.gradient_accumulation_steps,
>         mixed_precision=args.mixed_precision,
>         log_with=log_with,
>         project_dir=logging_dir,
>         kwargs_handlers=[InitProcessGroupKwargs(backend="gloo")],
>     )
> ```

did this and both cards are running when training, however the results are odd, batch size applies to both devices (8 and 8) and epochs specified double, if not capped. when capped at say 15, the number of steps is cut accordingly, but results are terrible.  also when used to tag datasets, the cards are running the same sets of images simultaneously, which makes me thing the same thing is happening with training as the vram usage climbs in parallel as opposed to sequentially. thoughts?

**Comment by FurkanGozukara** [comment]
> > The accelerator use NCCL as default backend, but NCCL has not released a Windows version, you can change it to Gloo by editing `library/train_util.py`.
> > 
> > * original
> > 
> > ```python
> >     accelerator = Accelerator(
> >         gradient_accumulation_steps=args.gradient_accumulation_steps,
> >         mixed_precision=args.mixed_precision,
> >         log_with=log_with,
> >         project_dir=logging_dir,
> >     )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * edited
> > 
> > ```python
> >     from accelerate.utils import InitProcessGroupKwargs
> >     accelerator = Accelerator(
> >         gradient_accumulation_steps=args.gradient_accumulation_steps,
> >         mixed_precision=args.mixed_precision,
> >         log_with=log_with,
> >         project_dir=logging_dir,
> >         kwargs_handlers=[InitProcessGroupKwargs(backend="gloo")],
> >     )
> > ```
> 
> did this and both cards are running when training, however the results are odd, batch size applies to both devices (8 and 8) and epochs specified double, if not capped. when capped at say 15, the number of steps is cut accordingly, but results are terrible. also when used to tag datasets, the cards are running the same sets of images simultaneously, which makes me thing the same thing is happening with training as the vram usage climbs in parallel as opposed to sequentially. thoughts?

with stable diffusion training i think there is no training split between cards

it duplicates batch count

so instead of batch size 1 you train batch size 2

so your training duplicated. thus trained in lesser time
therefore you need to reduce your total epoch to half

**Comment by JaosonMa** [comment]
> ====
> 
> SOLVED 解决了
> 
> GPU = 0 <<< VRAM +CUDAGPU = 0 <<< 显存 + CUDA GPU = 1 <<< CUDA only GPU = 1 <<< 仅 CUDA
> 
> NOTE : running by default "all" or "0,1"注意：默认运行“all”或“0,1”
> 
> .\venv\Scripts\activate accelerate config  加速配置
> 
> Which type of machine are you using?您使用哪种类型的机器？ No distributed training  无分布式训练 Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]:NO 您是否只想在 CPU 上运行训练（即使有 GPU 可用）？ [是/否]：否 Do you wish to optimize your script with torch dynamo?[yes/NO]:NO 您希望使用 torch dynamo 优化您的脚本吗？[是/否]:否 Do you want to use DeepSpeed? [yes/NO]: NO 您想使用 DeepSpeed 吗？ [是/否]：否 What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:0,1 应该使用什么 GPU（按 id）在这台机器上进行训练（以逗号分隔列表形式）？ [全部]：0,1 Do you wish to use FP16 or BF16 (mixed precision)? fp16 您想使用 FP16 还是 BF16（混合精度）？ FP16

it work well!  赞

**Comment by jppenvose** [comment]
Any luck on running this model with two A6000 gpus?

**Comment by HG2407** [comment]
`In which compute environment are you running?
This machine
-------------------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
multi-GPU
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Should distributed operations be checked while running for errors? This can avoid timeout issues but will be slower. [yes/NO]: yes
Do you wish to optimize your script with torch dynamo?[yes/NO]:no
Do you want to use DeepSpeed? [yes/NO]: no
Do you want to use FullyShardedDataParallel? [yes/NO]: no
Do you want to use Megatron-LM ? [yes/NO]: no
How many GPU(s) should be used for distributed training? [1]:4
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:0,1,2,3
-------------------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?
fp16`

these were my setting but on running ./gui.sh --share

    Torch detected GPU: Tesla T4 VRAM 15102 Arch (7, 5) Cores 40
    
  why is it not detecting other 3 gpus ?

**Comment by jppenvose** [comment]
@HkingAuditore, Do you get the "Redirect" error where redirect is not supported by Windows or MACOS?

**Comment by WorgenZhang** [comment]
> > The accelerator use NCCL as default backend, but NCCL has not released a Windows version, you can change it to Gloo by editing `library/train_util.py`.
> > 
> > * original
> > 
> > ```python
> >     accelerator = Accelerator(
> >         gradient_accumulation_steps=args.gradient_accumulation_steps,
> >         mixed_precision=args.mixed_precision,
> >         log_with=log_with,
> >         project_dir=logging_dir,
> >     )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * edited
> > 
> > ```python
> >     from accelerate.utils import InitProcessGroupKwargs
> >     accelerator = Accelerator(
> >         gradient_accumulation_steps=args.gradient_accumulation_steps,
> >         mixed_precision=args.mixed_precision,
> >         log_with=log_with,
> >         project_dir=logging_dir,
> >         kwargs_handlers=[InitProcessGroupKwargs(backend="gloo")],
> >     )
> > ```
> 
> did this and both cards are running when training, however the results are odd, batch size applies to both devices (8 and 8) and epochs specified double, if not capped. when capped at say 15, the number of steps is cut accordingly, but results are terrible. also when used to tag datasets, the cards are running the same sets of images simultaneously, which makes me thing the same thing is happening with training as the vram usage climbs in parallel as opposed to sequentially. thoughts?

"accelerate config" select distributed training + change backend to gloo works for me, both cards are running, but haven't check the results yet.

**Comment by ariexietrotiv** [comment]
I have two 3090 and when I'm training it only uses one. I will check EKI-INDRADI. Did anyone test it also?
