### ISSUE TITLE
returned non-zero exit status 1.

### ISSUE THREAD

**Issue by healthyfat** [bmaltais/kohya_ss#53]
Traceback (most recent call last):
  File "C:\Programs\bmaltais GUI\kohya_ss\train_db.py", line 337, in <module>
    train(args)
  File "C:\Programs\bmaltais GUI\kohya_ss\train_db.py", line 178, in train
    num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Programs\bmaltais GUI\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Programs\bmaltais GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Programs\bmaltais GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Programs\bmaltais GUI\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Programs\\bmaltais GUI\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--use_8bit_adam', '--xformers', '--pretrained_model_name_or_path=C:/Programs/stable-diffusion-webui/models/Stable-diffusion/sd-v1-4.ckpt', '--train_data_dir=C:/Users/pdept/Desktop/AI pics/training/train_data_dir/zdjecia', '--resolution=512,512', '--output_dir=C:/Users/pdept/Desktop/AI pics/training/train_data_dir/model', '--logging_dir=', '--output_name=last', '--max_data_loader_n_workers=1', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--train_batch_size=1', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--max_data_loader_n_workers=1', '--gradient_checkpointing', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
This is usually the result of a bad folder structure for the training. Did you try to do a dreambooth? If so, did you use the dreambooth folder prep tool to create it?

**Comment by healthyfat** [comment]
Yes. I used Dreambooth Lora prepare data button in Tool tab to create training folders. 

If I don't use prep button and only indicate folders in Folder tab, then I get "No data found. Please verify arguments" error.

**Comment by NaughtDZ** [comment]
Same issue here.I wonder did reg picture need prompt .txt file?

**Comment by bmaltais** [comment]
Usually there is no need for .txt in reg folder

**Comment by qqualia** [comment]
I'm also getting this: 

Folder 40_jewlsotn woman: 560 steps
max_train_steps = 280
stop_text_encoder_training = 0
lr_warmup_steps = 28
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="D:/SD/stable-diffusion-webui/models/Stable-diffusion/uberRealisticPornMerge_urpmv12Inpainting-inpainting.safetensors" --train_data_dir="D:\SD\Training Data\jewlsotn\img" --resolution=512,512 --output_dir="D:/SD/Training Data/jewlsotn/model" --logging_dir="D:/SD/Training Data/jewlsotn/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=1e-3 --network_dim=8 --output_name="jewlsotn" --learning_rate="1e-5" --lr_scheduler="cosine" --lr_warmup_steps="28" --train_batch_size="2" --max_train_steps="280" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --cache_latents --max_data_loader_n_workers="1" --xformers --use_8bit_adam
prepare tokenizer
Use DreamBooth method.
prepare train images.
found directory 40_jewlsotn woman contains 14 image files
560 train images with repeating.
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 1399.60it/s]
make buckets
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (256, 832), count: 0
bucket 1: resolution (256, 896), count: 0
bucket 2: resolution (256, 960), count: 0
bucket 3: resolution (256, 1024), count: 0
bucket 4: resolution (320, 704), count: 0
bucket 5: resolution (320, 768), count: 0
bucket 6: resolution (384, 640), count: 0
bucket 7: resolution (448, 576), count: 0
bucket 8: resolution (512, 512), count: 560
bucket 9: resolution (576, 448), count: 0
bucket 10: resolution (640, 384), count: 0
bucket 11: resolution (704, 320), count: 0
bucket 12: resolution (768, 320), count: 0
bucket 13: resolution (832, 256), count: 0
bucket 14: resolution (896, 256), count: 0
bucket 15: resolution (960, 256), count: 0
bucket 16: resolution (1024, 256), count: 0
mean ar error (without repeats): 0.0
prepare accelerator
Using accelerator 0.15.0 or above.
load StableDiffusion checkpoint
Traceback (most recent call last):
  File "D:\sd\kohya_ss\train_network.py", line 465, in <module>
    train(args)
  File "D:\sd\kohya_ss\train_network.py", line 83, in train
    text_encoder, vae, unet, _ = train_util.load_target_model(args, weight_dtype)
  File "D:\sd\kohya_ss\library\train_util.py", line 1327, in load_target_model
    text_encoder, vae, unet = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.pretrained_model_name_or_path)
  File "D:\sd\kohya_ss\library\model_util.py", line 880, in load_models_from_stable_diffusion_checkpoint
    info = unet.load_state_dict(converted_unet_checkpoint)
  File "D:\sd\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
        size mismatch for conv_in.weight: copying a param with shape torch.Size([320, 9, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 4, 3, 3]).
Traceback (most recent call last):
  File "C:\Users\adaml\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adaml\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\sd\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\sd\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\sd\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/SD/stable-diffusion-webui/models/Stable-diffusion/uberRealisticPornMerge_urpmv12Inpainting-inpainting.safetensors', '--train_data_dir=D:\\SD\\Training Data\\jewlsotn\\img', '--resolution=512,512', '--output_dir=D:/SD/Training Data/jewlsotn/model', '--logging_dir=D:/SD/Training Data/jewlsotn/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=1e-3', '--network_dim=8', '--output_name=jewlsotn', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=28', '--train_batch_size=2', '--max_train_steps=280', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--max_data_loader_n_workers=1', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1

**Comment by mykeehu** [comment]
Same problem here, what is the solution?

```
CUDA SETUP: Loading binary H:\Kohya-DB\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
Traceback (most recent call last):
  File "H:\Kohya-DB\kohya_ss\train_db.py", line 337, in <module>
    train(args)
  File "H:\Kohya-DB\kohya_ss\train_db.py", line 178, in train
    num_train_epochs = math.ceil(args.max_train_steps / num_update_steps_per_epoch)
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "H:\Kohya-DB\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\Kohya-DB\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\Kohya-DB\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "H:\Kohya-DB\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\Kohya-DB\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=H:\\Stable-Diffusion-Automatic\\Dreambooth\\onoffupftv\\train sorted BLIP\\sitting', '--resolution=512,512', '--output_dir=V:\\!SDModels\\Kohya', '--logging_dir=H:\\Stable-Diffusion-Automatic\\Dreambooth\\onoffupftv\\log', '--save_model_as=safetensors', '--output_name=oof16a', '--max_data_loader_n_workers=1', '--learning_rate=1e-5', '--lr_scheduler=constant', '--train_batch_size=2', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.
```

**Comment by marcotrani** [comment]
Not sure but seems same problem, I've tried out some test but can't resolve... This is the error, what can I do?

`CUDA SETUP: Loading binary C:\ai\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit Adam optimizer
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1500
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 750
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 2
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 2
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 750
steps:   0%|                                                                                                                                                                     | 0/750 [00:00<?, ?it/s]epoch 1/1
Error no kernel image is available for execution on the device at line 167 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
Traceback (most recent call last):
  File "C:\Users\i5Desktop7600k\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\i5Desktop7600k\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ai\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\ai\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\ai\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\ai\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\ai\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--bucket_reso_steps=1', '--bucket_no_upscale', '--pretrained_model_name_or_path=C:/ai/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=C:/mauroprellilora/images formatted/150_mauroprelli/img', '--resolution=512,512', '--output_dir=C:/mauroprellilora/images formatted/150_mauroprelli/model', '--logging_dir=C:/mauroprellilora/images formatted/150_mauroprelli/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=test', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=750', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.`

**Comment by healthyfat** [comment]
C:/mauroprellilora/images formatted/150_mauroprelli/img

I think your folder name and structure is wrong.

Create folder named for example 100_uniqueword and place it inside /img folder.

**Comment by Nezara** [comment]
I think something is up with the folder preparation tool, last two times I used it, it continuously created a recursive folder structure until python shut it down.

**Comment by NaughtDZ** [comment]
In fact, I still encountered some problems in the version made by others using this project, but the problem was solved after I adjusted the virtual memory space of this partition to 16G.

**Comment by marcotrani** [comment]
Thank you mate, I've just tried but nothing. Consider when I'm using the same tecnique on other PC with 3080Ti (instead of 1080Ti) all works properly, also with folder like /150_mauro prelli with spaces... I really don't know why it doesn't work on Intel 7700k with 1080Ti updated drivers and same version of all, Python etc etc...

> C:/mauroprellilora/images formatted/150_mauroprelli/img
> 
> I think your folder structure is wrong.
> 
> Maybe try placing folder /150_mauroprelli with images inside /img folder and use the path to the folder that contains folder with images. So for example:
> 
> folder structure should be:
> 
> /img/150_mauroprelli
> 
> and the actual path:
> 
> /img
> 
> That worked in my case.

**Comment by Jocha00001** [comment]
I encountered the same situation as you. If you use json file in lora network weight.
It may be because the json file is not enabled (it should be a bug of koyha, it can be enabled before but it is not working now), and the input of the corresponding parameters needs to be completed manually

You can try to manually enter to solve it.Hope this helps

**Comment by edkenne** [comment]
> This is usually the result of a bad folder structure for the training. Did you try to do a dreambooth? If so, did you use the dreambooth folder prep tool to create it?

Could this error be named a bit different so it is a bit obvious to the casual user?
Aka "returned non-zero exit status of 1: check your folder paths"

**Comment by rotabul** [comment]
I want to share my experiences when solving the same issue. First I didn't notice I was on the Dreambooth tab instead of the Lora tab when starting the training. They seem to be the same but probably are not the same (I'm running it for the first time).

So after I switched to the Lora tab and started the training, the result was the same - an error. So I changed the "Optimizer" to AdamW instead of AdamW8bit (be sure you are on the Lora tab again) and started the training. And now it worked.

I hope it helps you to solve the problem as well.

**Comment by Cali4our** [comment]
I have fixed it by simply moving the folder I put my images, log and output; into my D drive.

For some reason, it doesn't let me train on desktop. Make sure you try to put on your drive, documents or somewhere else other than Desktop and try it like that. It may work.
