### ISSUE TITLE
lora not work on stable diffusion webui

### ISSUE THREAD

**Issue by vlisk** [bmaltais/kohya_ss#530]
lora not work on stable diffusion webui,when i training lora on Kohya_ss GUI, finally get the lora model and copy to stable diffusion specfiy directory. enable lora in stable diffusion and set weight to 1. it seems not work ,what i am wrong

**Comment by bmaltais** [comment]
The latest auto1111 webui has broken LoRA support... they need to fix stuff for things to work again.

**Comment by vlisk** [comment]
i use drax lora like this,did i something wrong?
![1a6ee8b60552c36790a713a7f73b0c3](https://user-images.githubusercontent.com/38219232/229407063-5671774f-e4be-4e3d-b12b-8c92bab6ec0d.png)

the create result is below,no relate to drax lora
![002a9bde127384d214c322f723fa6ef](https://user-images.githubusercontent.com/38219232/229407066-dbc5ab57-d4d4-4683-839c-a9bb55e2fe24.png)

**Comment by vlisk** [comment]
@bmaltais

**Comment by kalonsul** [comment]
I had a similar problem. Using lora that I had trained myself did not work, but downloading lora from another place did

**Comment by vlisk** [comment]
I already installed latest stable diffusion webui and latest kohya_ss webui, I wonder the stable diffusion the latest version is need repair or which extension missing should i install? @bmaltais

**Comment by bmaltais** [comment]
You need to use Drax instead of 1man in the prompt...
