### ISSUE TITLE
Got an error when clicking button on the webgui

### ISSUE THREAD

**Issue by exzonye** [bmaltais/kohya_ss#532]
2023-04-03 15:33:10.965 Python[6095:374671] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001b70351a8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001b6d7fe04 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001b7060128 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00000001b9b43930 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 372
	4   AppKit                              0x00000001b9b2e92c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 948
	5   AppKit                              0x00000001b9b2e56c -[NSWindow initWithContentRect:styleMask:backing:defer:] + 56
	6   libtk8.6.dylib                      0x0000000138c34d84 TkMacOSXMakeRealWindowExist + 524
	7   libtk8.6.dylib                      0x0000000138c34a68 TkWmMapWindow + 56
	8   libtk8.6.dylib                      0x0000000138ba8270 MapFrame + 76
	9   libtcl8.6.dylib                     0x0000000138adcb84 TclServiceIdle + 84
	10  libtcl8.6.dylib                     0x0000000138ac0ee0 Tcl_DoOneEvent + 296
	11  libtk8.6.dylib                      0x0000000138c28a28 TkpInit + 720
	12  libtk8.6.dylib                      0x0000000138ba1278 Initialize + 2292
	13  _tkinter.cpython-310-darwin.so      0x000000012dfc6a98 Tcl_AppInit + 80
	14  _tkinter.cpython-310-darwin.so      0x000000012dfc0a98 Tkapp_New + 592
	15  _tkinter.cpython-310-darwin.so      0x000000012dfc0448 _tkinter_create + 580
	16  Python                              0x0000000105464a0c cfunction_vectorcall_FASTCALL + 88
	17  Python                              0x000000010550cd4c call_function + 128
	18  Python                              0x000000010550a564 _PyEval_EvalFrameDefault + 43100
	19  Python                              0x00000001054feab4 _PyEval_Vector + 376
	20  Python                              0x0000000105412b8c _PyObject_FastCallDictTstate + 96
	21  Python                              0x0000000105488bd8 slot_tp_init + 196
	22  Python                              0x0000000105480ba4 type_call + 288
	23  Python                              0x0000000105412924 _PyObject_MakeTpCall + 136
	24  Python                              0x000000010550cddc call_function + 272
	25  Python                              0x000000010550a564 _PyEval_EvalFrameDefault + 43100
	26  Python                              0x00000001054feab4 _PyEval_Vector + 376
	27  Python                              0x0000000105412b8c _PyObject_FastCallDictTstate + 96
	28  Python                              0x0000000105488bd8 slot_tp_init + 196
	29  Python                              0x0000000105480ba4 type_call + 288
	30  Python                              0x0000000105412924 _PyObject_MakeTpCall + 136
	31  Python                              0x000000010550cddc call_function + 272
	32  Python                              0x000000010550a58c _PyEval_EvalFrameDefault + 43140
	33  Python                              0x00000001054feab4 _PyEval_Vector + 376
	34  Python                              0x0000000105412bfc _PyObject_FastCallDictTstate + 208
	35  Python                              0x0000000105488bd8 slot_tp_init + 196
	36  Python                              0x0000000105480ba4 type_call + 288
	37  Python                              0x0000000105412924 _PyObject_MakeTpCall + 136
	38  Python                              0x000000010550cddc call_function + 272
	39  Python                              0x000000010550a614 _PyEval_EvalFrameDefault + 43276
	40  Python                              0x00000001054feab4 _PyEval_Vector + 376
	41  Python                              0x000000010550cd4c call_function + 128
	42  Python                              0x000000010550a614 _PyEval_EvalFrameDefault + 43276
	43  Python                              0x00000001054feab4 _PyEval_Vector + 376
	44  Python                              0x000000010550cd4c call_function + 128
	45  Python                              0x000000010550a58c _PyEval_EvalFrameDefault + 43140
	46  Python                              0x00000001054feab4 _PyEval_Vector + 376
	47  Python                              0x0000000105525334 _PyObject_VectorcallTstate.4671 + 96
	48  Python                              0x00000001055251e8 context_run + 92
	49  Python                              0x000000010546495c cfunction_vectorcall_FASTCALL_KEYWORDS + 84
	50  Python                              0x000000010550a72c _PyEval_EvalFrameDefault + 43556
	51  Python                              0x00000001054feab4 _PyEval_Vector + 376
	52  Python                              0x000000010550cd4c call_function + 128
	53  Python                              0x000000010550a4ec _PyEval_EvalFrameDefault + 42980
	54  Python                              0x00000001054feab4 _PyEval_Vector + 376
	55  Python                              0x000000010550cd4c call_function + 128
	56  Python                              0x000000010550a4ec _PyEval_EvalFrameDefault + 42980
	57  Python                              0x00000001054feab4 _PyEval_Vector + 376
	58  Python                              0x0000000105415c94 method_vectorcall + 388
	59  Python                              0x00000001055ccc7c thread_run + 120
	60  Python                              0x000000010556babc pythread_wrapper + 48
	61  libsystem_pthread.dylib             0x00000001b6ee826c _pthread_start + 148
	62  libsystem_pthread.dylib             0x00000001b6ee308c thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException
./gui_macos.sh: line 13:  6095 Abort trap: 6           python kohya_gui.py "$@"

**Comment by bmaltais** [comment]
Full macros support is still a ways out...

**Comment by jstayco** [comment]
This one requires a lot of rewriting and refactoring. It's a WIP, but as @bmaltais mentioned it may be a while. Main issue is the way the threading is handled doesn't work with macOS' security model. This is being actively worked, however. 

@bmaltais Maybe you should add macOS to that list where the button doesn't work to avoid user confusion until the PR is ready.

**Comment by bmaltais** [comment]
I could. I will need to find a reliable way to detect MacOS in python to exclude it...

**Comment by jstayco** [comment]
@bmaltais I think this will work. You can cut the version numbers out if needed, but macOS 10.0 is old, so we shouldn't run into anything older:
```python
import platform

def is_macos():
    system = platform.system()
    release = platform.release()
    return system == 'Darwin' and release.startswith('10.') or release.startswith('11.')
```
