### ISSUE TITLE
Incongruent line endings in setup.sh

### ISSUE THREAD

**Issue by A-iko** [bmaltais/kohya_ss#536]
Hello there!

I ran into some small issues when trying to run the setup.sh script.
It's nothing major, but it does stop it from working without a little bit of help:

![image](https://user-images.githubusercontent.com/5442999/229618527-93e59f67-0a06-4f69-9ff9-304a30878ddd.png)

After a bit of poking around, this is caused by using CRLF line endings. All I had to do was switch to LF and replace the enters to fix them.

I'd make a pull request for these, but I imagine this issue might already be solved in https://github.com/bmaltais/kohya_ss/pull/535 since that also touches setup.sh.

Let me know if you'd still like me to make a pull request! Keep up the good work!

**Comment by bmaltais** [comment]
@jstayco is best to respond to this. Will let him assess the need for another PR.

**Comment by jstayco** [comment]
I just checked my merged #535 branch and it looks like setup.sh has LF endings. Sorry about that! That's what I get for messing with these on different operating systems with no gitattributes file in place. I'll fix that on my next round of installer stuff and look out for that.

**Comment by A-iko** [comment]
Sounds good! I know this is probably a different issue, but I figured I'd toss it in here cause it also affects setup.sh, I see that you use the webui compiled version of xformers, that one didn't work for me. I think the python version in the provided venv (kinda feeling that the venv should be gitignored and built on install, but that's neither here not there) doesn't work with that version.

Luckily meta finally made a proper set of artifacts, I suggest switching to those and figuring out which one works: https://pypi.org/project/xformers/ . Let me know which! I couldn't figure it out (Not that I tried very hard to be honest).

**Comment by jstayco** [comment]
@bmaltais I think this one is all you. I don't have an Nvidia GPU and I wouldn't know what to look for anyhow. I'm already working on a brand new installer though for all operating systems, so it's an easy add if you let me know which direction to go.

**Comment by jstayco** [comment]
For reference here is my branch for the new installer: https://github.com/jstayco/kohya_ss/tree/unified_installer

Specifically, pip stuff is in launcher.py right here: https://github.com/jstayco/kohya_ss/blob/unified_installer/launcher.py#L422
(and in requirements.txt of course).

Workflow will be setup.ps1/sh (optional - sets up git, python, python tk)-> launcher.py (kohya launcher with feature to have a config file for automated launches and a few other environment checks/installs) -> kohya_gui.py (you can always still call this one directly to bypass it all and it will pick up the same config file).

This branch is a huge WIP though. It is not ready for anything. Not even testing.
