### ISSUE TITLE
Koyha/Lora Training Error, FP16 no GPU, Accelerate Config not Launching when double clicking.

### ISSUE THREAD

**Issue by Loratraining** [bmaltais/kohya_ss#537]
Hello

I'm experiencing problems with my Kohya installations, I have tried to install it about 3 times and still getting similar errors using the new instructions on the main page, Install, Upgrade, then launching it in browser.
When I try to click on "Accelerate-Config" it crashes as soon as it opens.
I can however use setup.bat to try to reinstall the fp16 but every time I do it still gives me "ValueError: fp16 mixed precision requires a GPU" I don't think its installing.
Would you know why I'm getting this error? I do have two Stable Diffusions v1.5 with Automatic1111 (One Nvidia and the other AMD DirectML, made a mistake and installed Nvidia too, both seperate folders) I just use default settings in Lora settings.
Graphic card is AMD 6600XT.
Python 3.10.10 

Thank you.

Beginning of Code:

Folder 100_test: 24 images found
Folder 100_test: 2400 steps
max_train_steps = 2400
stop_text_encoder_training = 0
lr_warmup_steps = 240
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/Daniel/Lora Training Data/Test Example/image" --resolution=512,512 --output_dir="C:/Users/Daniel/Lora Training Data/Test Example/model" --logging_dir="C:/Users/Lora Training Data/Test Example/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="last" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="240" --train_batch_size="1" --max_train_steps="2400" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory C:\Users\Lora Training Data\Test Example\image\100_test contains 24 image files
2400 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\User\Lora Training Data\Test Example\image\100_test"
    image_count: 24
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: test
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 1919.66it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "C:\Users\Kohya\kohya_ss\train_network.py", line 724, in <module>
    train(args)
  File "C:\Users\Kohya\kohya_ss\train_network.py", line 123, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\Users\Kohya\kohya_ss\library\train_util.py", line 2602, in prepare_accelerator
    accelerator = Accelerator(
  File "C:\Users\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/Lora Training Data/Test Example/image', '--resolution=512,512', '--output_dir=C:/Users/Lora Training Data/Test Example/model', '--logging_dir=C:/Users/Lora Training Data/Test Example/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=240', '--train_batch_size=1', '--max_train_steps=2400', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
This solution is not supported under non NVDIA GPU. This is why it is failing on the AMD GPU.

**Comment by Loratraining** [comment]
> This solution is not supported under non NVDIA GPU. This is why it is failing on the AMD GPU.

Oh I see, does that mean if I were to get a Nvidia GPU it would work fine?

**Comment by bmaltais** [comment]
In theory yes... But get something like a 3090 of 4090 for best chances.

**Comment by 3VwVnts** [comment]
How then to run on ADM, what settings to set?
