### ISSUE TITLE
Save every  n epochs does not match epoch 

### ISSUE THREAD

**Issue by the0ckid82** [bmaltais/kohya_ss#54]
when i used to set epoch to 4 and save ever 1 epoch the result would be 4 models but now it only generates 2, not sure what im doing differently or if something changed  but i cant seem to find anything that would have caused this 

![image](https://user-images.githubusercontent.com/5402500/213149053-910dd55e-7861-40d6-95aa-44b214f20568.png)

![image](https://user-images.githubusercontent.com/5402500/213149228-4e0bd3f1-c07a-4fd0-b57c-2d784b4db9ee.png)

**Comment by bmaltais** [comment]
I think there is a bug in the kohya trainer code... This is not something I can fix in the GUI.
