### ISSUE TITLE
prepare tokenizer (FOR A LONG TIME)

### ISSUE THREAD

**Issue by sunnyhenry123** [bmaltais/kohya_ss#548]
Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 30_FF3: 7 images found
Folder 30_FF3: 210 steps
max_train_steps = 840
stop_text_encoder_training = 0
lr_warmup_steps = 84
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="F:/kohya_ss-21.3.6/model/Butter.safetensors" --train_data_dir="F:/kohya_ss-21.3.6/images" --resolution=512,512 --output_dir="F:/kohya_ss-21.3.6/output" --logging_dir="" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="renge" --lr_scheduler_num_cycles="8" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="84" --train_batch_size="2" --max_train_steps="840" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale  --sample_sampler=euler_a --sample_prompts="F:/kohya_ss-21.3.6/output\sample\prompt.txt" --sample_every_n_steps="200"
prepare tokenizer

**Comment by dreamjz** [comment]
Same problem here, I tried to delete "C:\Users\***\.cache\huggingface\hub\", and expected it to redownload it, but not work.
  I found that it always tries to create "C:\Users\***\.cache\huggingface\hub\models--openai--clip-vit-large-patch14" and 3 subfolders, but all the folder is empty.  
  In the meanwhile, I found that the AUTOMATIC1111 cannot start too, and it does the same thing (try to create these folders but do nothing).
  I think the two problems are the same, but I don't know what happened. (I can use these programs hours ago).  :)

**Comment by dreamjz** [comment]
Found the solution, and it works fine now.
   See [AUTOMATIC1111/stable-diffusion-webui/issues/9394](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9394), [AUTOMATIC1111/stable-diffusion-webui/issues/7901](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7901) for details.
 1. Clear "C:\Users\username\.cache" directory.
 2. Edit : InstallDir:\stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\file_download.py | Line 1262
     to blob_path = os.path.join(storage_folder, "blobs", etag[3:]) 
 3. Restart AUTOMATIC1111/stable-diffusion-webui, check it started successfully.
 4. Restart Kohya_ss, start training models, and now it's working.

I guess how this happens:
  Downloading the "huggingface\hub\models--openai--clip-vit-large-patch14" failed because of the network error.
  -> "stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\file_download.py", this file prevents programs from redownloading the module.
  -> So, the WebUI is stuck at booting and kohya_ss is stuck at "prepare tokenizer".

**I'm new to Python and not sure about this, waiting for a hero to tell me why and more.   :)**

**Comment by kbugstar** [comment]
Same problem, i try to manual run finetune/make_catpions.py and track down,
in func hf_hub_download,  a Filelock wait for download complete,
but the download never start or never finish

**Comment by kbugstar** [comment]
> 

it' work！thanks

**Comment by kbugstar** [comment]
> Found the solution, and it works fine now. See [AUTOMATIC1111/stable-diffusion-webui/issues/9394](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9394), [AUTOMATIC1111/stable-diffusion-webui/issues/7901](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7901) for details.
> 
> 1. Clear "C:\Users\username.cache" directory.
> 2. Edit : InstallDir:\stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\file_download.py | Line 1262
>    to blob_path = os.path.join(storage_folder, "blobs", etag[3:])
> 3. Restart AUTOMATIC1111/stable-diffusion-webui, check it started successfully.
> 4. Restart Kohya_ss, start training models, and now it's working.
> 
> I guess how this happens: Downloading the "huggingface\hub\models--openai--clip-vit-large-patch14" failed because of the network error. -> "stable-diffusion-webui\venv\Lib\site-packages\huggingface_hub\file_download.py", this file prevents programs from redownloading the module. -> So, the WebUI is stuck at booting and kohya_ss is stuck at "prepare tokenizer".
> 
> **I'm new to Python and not sure about this, waiting for a hero to tell me why and more. :)**

It's work，thanks ^^

**Comment by ahjulstad** [comment]
From discussions here: https://github.com/huggingface/huggingface_hub/issues/1423 , this was triggered by a server-side issue at huggingface.

**Comment by dreamjz** [comment]
> From discussions here: [huggingface/huggingface_hub#1423](https://github.com/huggingface/huggingface_hub/issues/1423) , this was triggered by a server-side issue at huggingface.

Thanks ^_^

**Comment by Ru2skov** [comment]
Hi guys, I finally found the solution. Actually, it's related to the download cache. First, put your Windows in developer mode, which is quite easy to do. Then, you simply need to find your cache folder, delete it, and then re-download. After that, you need to look for the file that couldn't be downloaded.

**Me, the path that leads to my cache was this one:**
C:\Users\courr\.cache\huggingface\diffusers\models--runwayml--stable-diffusion-v1-5

Then you go to this link, and there you have all the files that will be installed in the cache.
https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main
I deleted it and then went to this website and restarted Kohya. I restarted a LoRa process, it started downloading and stopped on the largest file. I downloaded it myself, put it in the folder, and now it works.

For me, it was that file that was missing
v1-5-pruned-emaonly
