### ISSUE TITLE
Lora does not appear to be training. 

### ISSUE THREAD

**Issue by Innisfr33** [bmaltais/kohya_ss#549]
I have been unable to train lora models since a recent windows re-install. Stable diffusion in automatic1111 is working fine and all models created prior work perfectly. However when I attempt to train a new model it appears to work and goes through the entire process but the resulting model is not actually trained. When I attempt to use it, the results are not at all close to the training data. A model trained on a person will return a picture of a house or a field. If it does return a person it looks nothing like the person it is supposed to. The one thing I did notice is that the resulting file is VERY small. 9MB instead of 145MB. It looks like it is creating the model but not actually training it.

**Comment by Cragsand** [comment]
Did you figure this out on your own? I'm in the same situation. The LORA model I trained seems to work but I'm not sure about the influences having enough effect as they probably should.
