### ISSUE TITLE
"Uninstalling" Questions

### ISSUE THREAD

**Issue by Switchfoot55** [bmaltais/kohya_ss#550]
I'm attempting to do a full uninstall/reinstall of the program including the files that download when one first runs the training prompt. I cannot seem to locate where these are housed by default. Can anyone confirm the general file path and if it's safe/okay to delete the data files?

**Comment by bmaltais** [comment]
Look in your user home folder in windows. There will be a .cache folder in there. The models should be in the huggingface subfolder.
