### ISSUE TITLE
ERROR: Could not detect requirement name for 'git+ 

### ISSUE THREAD

**Issue by Intorain** [bmaltais/kohya_ss#553]
ERROR: Could not detect requirement name for 'git+https://github.com/KohakuBlueleaf/LyCORIS.git@c3d925421209a22a60d863ffa3de0b3e7e89f047', please specify one with #egg=your_package_name

**Comment by jstayco** [comment]
You can try changing the line in requirements.txt to this:
```
git+https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl #egg=xformers

```
