### ISSUE TITLE
Train model something wrong.

### ISSUE THREAD

**Issue by smithacked** [bmaltais/kohya_ss#560]
![image](https://user-images.githubusercontent.com/75908995/230579529-e959cb65-68cd-4b59-9d49-5de6db4f5779.jpeg)

Someone can help how to fix this process for train model,
I'm try to fix greatly but I can't so this bro plz🙏🏻😭

**Comment by bmaltais** [comment]
Make sure your folder name start with the number of steps followed by an underscore... Like:

100_boston
