### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._dynamo'

### ISSUE THREAD

**Issue by Ceatso** [bmaltais/kohya_ss#567]
Hi, im trying to teach lora but im geting always this lines. What Should i would to do ?
there is the line : import torch._dynamo as dynamo
ModuleNotFoundError: No module named 'torch._dynamo'

Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 100_Cmreatl: 10 images found
Folder 100_Cmreatl: 1000 steps
max_train_steps = 500
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="G:\AI için metaryaller\Cemre Atila\lora\img" --resolution=512,512 --output_dir="G:\AI\Stable Diffusion\stable-diffusion-webui\embeddings" --logging_dir="G:\AI için metaryaller\Cemre Atila\lora\logs" --network_alpha="1024" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=1024 --output_name="cemre_atila_v1.0" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="500" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory G:\AI için metaryaller\Cemre Atila\lora\img\100_Cmreatl contains 10 image files
1000 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "G:\AI için metaryaller\Cemre Atila\lora\img\100_Cmreatl"
    image_count: 10
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Cmreatl
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 464.02it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 512), count: 200
bucket 1: resolution (384, 576), count: 300
bucket 2: resolution (384, 640), count: 200
bucket 3: resolution (448, 512), count: 100
bucket 4: resolution (448, 576), count: 100
bucket 5: resolution (512, 448), count: 100
mean ar error (without repeats): 0.02828135008597079
prepare accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models
text_encoder\model.safetensors not found
Fetching 19 files: 100%|████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 18485.68it/s]
G:\kohya_ss\kohya_ss\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.61it/s]
import network module: networks.lora
create LoRA network. base dim (rank): 1024, alpha: 1024.0
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.

CUDA SETUP: Loading binary G:\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "G:\kohya_ss\kohya_ss\train_network.py", line 748, in <module>
    train(args)
  File "G:\kohya_ss\kohya_ss\train_network.py", line 262, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 876, in prepare
    result = tuple(
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 877, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 741, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 914, in prepare_model
    import torch._dynamo as dynamo
ModuleNotFoundError: No module named 'torch._dynamo'
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "G:\kohya_ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "G:\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=G:\\AI için metaryaller\\Cemre Atila\\lora\\img', '--resolution=512,512', '--output_dir=G:\\AI\\Stable Diffusion\\stable-diffusion-webui\\embeddings', '--logging_dir=G:\\AI için metaryaller\\Cemre Atila\\lora\\logs', '--network_alpha=1024', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=1024', '--output_name=cemre_atila_v1.0', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Make sure not to enable dynamo when you run accelerate config

**Comment by Ceatso** [comment]
Thank you i do when i install "dynamo" as a "NO" and its solved

**Comment by jamesBrosnahan** [comment]
> Make sure not to enable dynamo when you run accelerate config

Can you post a picture of what you are referring to with that?

**Comment by Phando** [comment]
Just running into this myself. Can one of you please provide a little more contest in your answers? I am kinda new at all this windows dev stuff.

**Comment by Ceatso** [comment]
Hi phando, its basically when u installing kohya_ss. U will see some questions. I don't remember what exactly saying but basically like this "Do u want dynamo .... " when u see this kinda question when u installing "kohya_ss" just say "No" and then everything will be fine. I hope this answer will help u.

**Comment by jandolina** [comment]
@Ceatso thanks for the response, I wend back through and got sorted.

**Comment by YongKuHwang** [comment]
I also had the same error. It was a Torch version issue.
try install follow version torch

pip install torch==2.0.1
