### ISSUE TITLE
On MacOS, using python3.10, install tensorflow==2.10.1 error

### ISSUE THREAD

**Issue by yuyang0914** [bmaltais/kohya_ss#570]
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: none)
ERROR: No matching distribution found for tensorflow==2.10.1

**Comment by yuyang0914** [comment]
like this #563

**Comment by Whyjsee** [comment]
remove the venv folder in kohya_ss , and edit setup.sh to make python3.10 create venv priorly in function `install_python_dependencies()`

`
  if ! inDocker; then
    if command -v python3.10 >/dev/null; then
      python3.10 -m venv "$DIR/venv"
    elif command -v python3 >/dev/null; then
      python3 -m venv "$DIR/venv"
    else
      echo "Valid python3 or python3.10 binary not found."
      echo "Cannot proceed with the python steps."
      return 1
    fi

    # Activate the virtual environment
    source "$DIR/venv/bin/activate"
  fi
`
