### ISSUE TITLE
ERROR: Torch not compiled with CUDA enabled...

### ISSUE THREAD

**Issue by GeneralAwareness** [bmaltais/kohya_ss#571]
File "D:\kohya_ss\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

How do I fix that?

**Comment by artemisiaaaa** [comment]
how did you solve it?
