### ISSUE TITLE
Install failing on Windows 10

### ISSUE THREAD

**Issue by infambart** [bmaltais/kohya_ss#572]
Greetings,

Initially, I was able to get most everything installed the first time, however the downloads froze during the first lora build and I had to close the terminal window. I deleted everything assuming a fresh install would work, but the install now throws errors (see attached log). Perhaps I have not deleted everything for a completely fresh install? Thanks for your assistance!

Confirmed - Python 3.10, git 2.40.0.windows.1, and latest visual studio install.

[win10_LOG.txt](https://github.com/bmaltais/kohya_ss/files/11183206/win10_LOG.txt)

**Comment by bmaltais** [comment]
Try deleting the bench folder and redo the full installation

**Comment by infambart** [comment]
Which folder is the bench folder? I've deleted only the koyha_ss folder during previous re-installations.

**Comment by bmaltais** [comment]
OK... this should have deleted the venv... so the problem must be elsewhere. I don't know where the python cache folder might be. There is a cache folder under your home folder that you could try to delete... perhaps the partly downloaded code is in there?

Look for a .cache folder and delete it.

**Comment by infambart** [comment]
I appreciate the quick reply's! After deleting the cache in "~\AppData\Local\pip\cache", It properly downloaded and installed everything. Cheers :)
