### ISSUE TITLE
Very short error when clicking "train model". What am I doing wrong?

### ISSUE THREAD

**Issue by Enslavedpixels** [bmaltais/kohya_ss#575]
Traceback (most recent call last):
  File "E:\diffusion\lora\kohya_ss\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\diffusion\lora\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 1022, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\diffusion\lora\kohya_ss\venv\lib\site-packages\gradio\blocks.py", line 914, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range

**Comment by bmaltais** [comment]
That one is not helpful indeed... gradio is a bit of a challenge to troubleshoot... What are you trying to train? Dreambooth, LoRA, Finetune?

**Comment by Enslavedpixels** [comment]
> That one is not helpful indeed... gradio is a bit of a challenge to troubleshoot... What are you trying to train? Dreambooth, LoRA, Finetune?

"Dreambooth LoRa"

**Comment by bmaltais** [comment]
I just tried training a BD on my system with no error. It is probably related to some config that is not tolerated by the python script. If it help, here are the settings I used for my training. You can compare with yours to see if you can spot the issue:

`accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="D:/quickstart/kohya_dreambooth/img" --resolution=512,512 --output_dir="D:/quickstart/kohya_dreambooth/output" --logging_dir="D:/quickstart/kohya_dreambooth/log" --save_model_as=safetensors --output_name="test4.1" --max_data_loader_n_workers="0" --learning_rate="1" --lr_scheduler="constant" --train_batch_size="4" --max_train_steps="150" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="DAdaptation" --max_data_loader_n_workers="0" --clip_skip=2 --caption_dropout_rate="0.05" --bucket_reso_steps=64 --min_snr_gamma=5 --xformers --bucket_no_upscale --noise_offset=0.05  --sample_sampler=euler_a --sample_prompts="D:/quickstart/kohya_dreambooth/output\sample\prompt.txt" --sample_every_n_steps="25"`

**Comment by Enslavedpixels** [comment]
Tried copying your settings best I could, but am still getting the same error.

Is there some way I could have caused this by installing it (or one of the dependencies) wrong? I might try reinstalling it tomorrow. I am going to bed now, so I won't respond for a while.

**Comment by Enslavedpixels** [comment]
I have reinstalled it, it appears to be fixed now. I am getting a different error now, so I will make a new isseu.
