### ISSUE TITLE
Option to choose device (mps instead of cuda) in lora training on Mac Silicon M1

### ISSUE THREAD

**Issue by TheRealThor** [bmaltais/kohya_ss#577]
When I try to do the lora training, it keeps asking for cuda libraries etc. On Mac Silicon tensor rendering works faster with integrated GPU with "torch.device("mps")". Where can i change the device or disable cuda?

**Comment by vkbest** [comment]
cd kohya_ss
. ./venv/bin/activate
accelerate config 

1. this machine
2. MPS
3. NO
4. NO

In your lora training configuration:

Mixed precision: NO
Save precision: float
Optimizer: Adamw

**Comment by TheRealThor** [comment]
Thank you! This helped and it work. I had to deactivate formers however to make it run on my Mac M2 16GB, because with xformers it gave this "NotImplementedError" error. I presume this could be a configuration error on my side.


```
File "/Users/thor/Dev/kohya_ss/library/train_util.py", line 1790, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 299, in _memory_efficient_attention
    return _fMHA.apply(
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 41, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 324, in _memory_efficient_attention_forward_requires_grad
    op = _dispatch_fw(inp)
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 98, in _dispatch_fw
    return _run_priority_list(
  File "/Users/thor/Dev/kohya_ss/venv/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 73, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 9216, 8, 40) (torch.float32)
     key         : shape=(1, 9216, 8, 40) (torch.float32)
     value       : shape=(1, 9216, 8, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=mps (supported: {'cuda'})
`flshattF` is not supported because:
    device=mps (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
`tritonflashattF` is not supported because:
    device=mps (supported: {'cuda'})
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    Operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
`smallkF` is not supported because:
    device=mps (supported: {'cuda', 'cpu'})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40
```

**Comment by jstayco** [comment]
@vkbest Should those be the default settings for macOS? Or at least aarch64 macOS?

**Comment by vkbest** [comment]
> @vkbest Should those be the default settings for macOS? Or at least aarch64 macOS?
> 
> Edit: Actually, I see you've gotten to the point of training on Mac and solid ideas on default settings. Any chance I could get some notes from you or anything? I'm writing some installer scripts right now and if I can preplace sane defaults for macOS that would be very helpful to people I'm sure. I've got some of them, but I haven't had a chance to get all the way to the point of training anything.

Those settings are for M1 and M2. Fp16 should be work, but throw a exception in execution (not sure if the problem is kohya script or PyTorch MPS backend). I don’t have a Intel Mac, so I can’t tell you if it’s the same for Intel machines.

I have trained 3 Lora currently, this is working in Mac, so ask me every you want.

**Comment by jstayco** [comment]
@vkbest Since you've got it working, here is what I have so far for the Mac setup stuff:
```
# macOS requirements.txt (packages taken from tensorflow-deps conda pkg)
grpcio >=1.37.0,<2.0
h5py >=3.6.0,<3.7
numpy >=1.23.2,<1.23.3
protobuf >=3.19.1,<3.20
tensorflow-macos==$ver # for arm64
tensorflow-metal==$ver # for arm64

tensorflow==$ver             # For x86_64
```


```
# Excerpt from new setup.sh for the install_python portion:
    "macOS")
      if command -v brew >/dev/null 2>&1; then
        ! brew list --versions python@3.10 >/dev/null && missing_packages+=("python@3.10")
        ! brew list --versions tcl-tk >/dev/null && missing_packages+=("tcl-tk")
        [[ ${#missing_packages[@]} -ne 0 ]] && brew install "${missing_packages[@]}"
        brew link --overwrite --force python@3.10
      else
        echo "Please install Homebrew first to continue with Python 3.10 and Tk installation."
        echo "You can find that here: https://brew.sh"
        exit 1
      fi
      ;;
   ```

And then I'll adapt a macos_accel_config to align with the values you provided above (haven't gotten to this step yet).

**Comment by cnscud** [comment]
> cd kohya_ss . ./venv/bin/activate accelerate config
> 
> 1. this machine
> 2. MPS
> 3. NO
> 4. NO
> 
> In your lora training configuration:
> 
> Mixed precision: NO Save precision: float Optimizer: Adamw

great, It works!

**Comment by andupotorac** [comment]
> cd kohya_ss . ./venv/bin/activate accelerate config
> 
> 1. this machine
> 2. MPS
> 3. NO
> 4. NO
> 
> In your lora training configuration:
> 
> Mixed precision: NO Save precision: float Optimizer: Adamw

On my end I don't see the MPS option, but instead only see these:

_Please select a choice using the arrow or number keys, and selecting with enter
 ➔  No distributed training                                                                                                                         
    multi-CPU                                                                                                                                       
    multi-GPU                                                                                                                                       
    TPU_

Can you tell me how I can enable MPS to show up on this list?

**Comment by andupotorac** [comment]
The reason was because accelerate 18 does it automatically. One thing you can do is change the code directly like shown here:
https://planaria.page/blog/?p=671

**Comment by chrismelbourne** [comment]
> The reason was because accelerate 18 does it automatically. One thing you can do is change the code directly like shown here:
> https://planaria.page/blog/?p=671

I got Kohya to work in M1, even trained a few models,  but for some reason, GPU usage is always 0% (whereas generating images in Automatic1111 succeeds in using the GPU).

I've:
1)  installed all the necessary dependencies according to the blog post, 
2)  edited the code in train_util.py to reference "mps" instead of "cuda". 
3) Set up "accelerate config" to NOT choose CPU only, etc. as per the post.
4) The Optimizer is set to AdamW, mixed precision NO, save precision fp16
5) edited requirements_unix.txt to include:
```
tensorflow-macos==2.12.0; sys_platform == 'darwin'
tensorflow-metal==0.8.0; sys_platform == 'darwin'
```

but Kohya still runs as if I've set it as "CPU only".

Otherwise, there are no pertinent error or warning messages.

Any ideas?

**Comment by IEROA7** [comment]
> cd kohya_ss . ./venv/bin/activate accelerate config
> 
> 1. this machine
> 2. MPS
> 3. NO
> 4. NO
> 
> In your lora training configuration:
> 
> Mixed precision: NO Save precision: float Optimizer: Adamw

I tried to do the things mentioned in other comments, but MPS still does not appear. What should I do?

**Comment by illuminatedjavascript** [comment]
The solution provided here is obsolete. The issue remains.
