### ISSUE TITLE
Macbook Pro M2 Only use CPU not GPU, why?

### ISSUE THREAD

**Issue by steveauai** [bmaltais/kohya_ss#578]
Hi, is there anyone having the same issue? In Activity Monitor, I can see only CPU is used %CPU and %GUP is  zero while my LoRA training is running. I assume it should use GPU more. This results in my training running very slow. For 10 pic 512 * 512 training took more than 12 hours.

I am new to this tool, can anyone tell me how to fix this? Thanks!

**Comment by vkbest** [comment]
https://github.com/bmaltais/kohya_ss/issues/577#issuecomment-1501006879

**Comment by steveauai** [comment]
This works, Thanks! I can see it is using GPU now, however, it is still 15 hours for training, is it normal?  I have M2 with 12 core CPU and 19 core GPU, 16G RAM. Thanks!

**Comment by vkbest** [comment]
> This works, Thanks! I can see it is using GPU now, however, it is still 15 hours for training, is it normal? I have M2 with 12 core CPU and 19 core GPU, 16G RAM. Thanks!

Your machine probably is paging as crazy, you need 32GB RAM for training at 512x512. You can try to lower resolution of training

**Comment by wacsai** [comment]
My machine is M1MAX, 64G, maybe this is the speed of the mac chip? I'm not sure, I also think it's too slow.

loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
[Dataset 0]
caching latents.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [00:21<00:00,  6.87it/s]
prepare optimizer, data loader etc.
use AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4380
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 4380
  num epochs / epoch数: 10
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 43800
steps:   0%|                                                                                                                          | 0/43800 [00:00<?, ?it/s]epoch 1/10
steps:   1%|▋                                                                                                 | 288/43800 [07:58<20:04:02,  1.66s/it, loss=0.17]

**Comment by steveauai** [comment]
Can you help to check if epoch is 1, batch: 1 and step of 1500 for 512*512, how long does it take on your machine? I think your one should be much better than mine, Thanks!

**Comment by vkbest** [comment]
> Can you help to check if epoch is 1, batch: 1 and step of 1500 for 512*512, how long does it take on your machine? I think your one should be much better than mine, Thanks!

That is around 30 minutes in my Mac. Probably you don’t have ram enough. Try lower the resolution of training, and watch your memory pressure

**Comment by vkbest** [comment]
> My machine is M1MAX, 64G, maybe this is the speed of the mac chip? I'm not sure, I also think it's too slow.
> 
> loading u-net: loading vae: loading text encoder: [Dataset 0] caching latents. 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [00:21<00:00, 6.87it/s] prepare optimizer, data loader etc. use AdamW optimizer | {} running training / 学習開始 num train images * repeats / 学習画像の数×繰り返し回数: 4380 num reg images / 正則化画像の数: 0 num batches per epoch / 1epochのバッチ数: 4380 num epochs / epoch数: 10 batch size per device / バッチサイズ: 1 total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1 gradient ccumulation steps / 勾配を合計するステップ数 = 1 total optimization steps / 学習ステップ数: 43800 steps: 0%| | 0/43800 [00:00<?, ?it/s]epoch 1/10 steps: 1%|▋ | 288/43800 [07:58<20:04:02, 1.66s/it, loss=0.17]

My M1 Max 32GB ram  with 24 cores GPU is usually 1.25s/it (depends from the images) . Yes, it's slow in Mac, current libraries for training are optimized for Nvidia and Cuda cards, not for Mac. With 64 GB you can try increase your train batch size and maybe gain some time, but yes, training in Mac is slow currently.

**Comment by steveauai** [comment]
Thanks @vkbest  maybe need to consider to get another PC with Nvidia RTX4080, I hope that would be much better

**Comment by vkbest** [comment]
> Thanks @vkbest maybe need to consider to get another PC with Nvidia RTX4080, I hope that would be much better

Sure much faster. 

Anyway, there are people who are using google colab for training loras
