### ISSUE TITLE
[Proposal] Create Collab with this project

### ISSUE THREAD

**Issue by CombainerA19** [bmaltais/kohya_ss#58]
The idea is simple, not everyone is a coder. Will be very nice if somebody creates Collab Notebook with this project. Thank you.

**Comment by bmaltais** [comment]
WOuld be nice. If someone create one I will gladly add it to the repo.

**Comment by CombainerA19** [comment]
Responding to myself: 

1. Setup Drembooth extension in Automatic1111 UI 
https://github.com/d8ahazard/sd_dreambooth_extension

2. Install kohaya_ss extension (you are here)

3. Open the Dreambooth tab in UI and train models (LoRa and CKPT)

4. LoRa models can be uploaded into the corresponding folder in SD folder on drive 

5. When LoRa in a folder - it will be accessible through UI on txt2img and img2img tabs
