### ISSUE TITLE
windows install issues

### ISSUE THREAD

**Issue by 6Dii** [bmaltais/kohya_ss#580]
Validating that requirements are satisfied.
Error: The following packages are missing:
 - accelerate==0.15.0
 - albumentations==1.3.0
 - altair==4.2.2
 - bitsandbytes==0.35.0
 - dadaptation==1.5
 - diffusers[torch]==0.10.2
 - easygui==0.98.3
 - einops==0.6.0
 - ftfy==6.1.1
 - gradio==3.19.1; sys_platform != 'darwin'
 - lion-pytorch==0.0.6
 - opencv-python==4.7.0.68
 - pytorch-lightning==1.9.0
 - safetensors==0.2.6
 - tensorboard==2.10.1 ; sys_platform != 'darwin'
 - tk==0.1.0
 - toml==0.10.2
 - transformers==4.26.0
 - voluptuous==0.13.1
 - fairscale==0.4.13
 - timm==0.6.12
 - huggingface-hub==0.12.0; sys_platform != 'darwin'
 - tensorflow==2.10.1; sys_platform != 'darwin'
 - lycoris_lora==0.1.4

no idea why it ask for darwin, 
is there any other way instead of run scripts for installing cudnn? (\venv\Scripts\activate)

**Comment by Dyi8** [comment]
I followed the instruction for windows installation, at the end it ask questions, did I answer them wrong?
The system cannot find the path specified.
.\bitsandbytes_windows\libbitsandbytes_cuda116.dll
The system cannot find the path specified.
        0 file(s) copied.
The system cannot find the path specified.
        0 file(s) copied.
The system cannot find the path specified.
        0 file(s) copied.
------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
No distributed training
Do you want to run your training on CPU only (even if a GPU / Apple Silicon device is available)? [yes/NO]:no
Do you wish to optimize your script with torch dynamo?[yes/NO]:yes
------------------------------------------------------------------------------------------------------------------------Which dynamo backend would you like to use?
inductor
Do you want to customize the defaults sent to torch.compile? [yes/NO]: no
Do you want to use DeepSpeed? [yes/NO]: yes

**Comment by infambart** [comment]
I had a similar issue, not sure if it's exact, but I deleted the Kohya_ss folder and all the python cache in "~\AppData\Local\pip\cache" and I had a successful re-install. I would try this first.

I also watched this video to help me verify I was doing everything correctly.. https://youtu.be/9MT1n97ITaE

**Comment by bmaltais** [comment]
> I had a similar issue, not sure if it's exact, but I deleted the Kohya_ss folder and all the python cache in "~\AppData\Local\pip\cache" and I had a successful re-install. I would try this first.
> 
> I also watched this video to help me verify I was doing everything correctly.. https://youtu.be/9MT1n97ITaE

Thank you for the tip. I will add it to the README

**Comment by Dyi8** [comment]
Problem solved!  One more thing, do I need those cache files, put them back, maybe?

**Comment by infambart** [comment]
When you reinstall it will re-populate those files correctly...
