### ISSUE TITLE
max_bucket_reso must be equal or greater than resolution / max_bucket_resoは最大解像度より小さくできません

### ISSUE THREAD

**Issue by basiclava** [bmaltais/kohya_ss#581]
When i train lora in resolution=768,1152,it return this error.

     AssertionError: max_bucket_reso must be equal or greater than resolution / max_bucket_resoは最大解像度より小さくできません。解像度を小さくするかmin_bucket_resoを大きくしてください

But i'can set max_bucket_reso in gui.

**Comment by DKnight54** [comment]
@basiclava, the secret is to put it in the optional command line under advanced parameters. 
![image](https://user-images.githubusercontent.com/126916963/230768365-0e8fa995-84b6-412c-850f-50f62bbf9883.png)

**Comment by basiclava** [comment]
OK,i will use it.
