### ISSUE TITLE
All buttons are disabled

### ISSUE THREAD

**Issue by kekakuka** [bmaltais/kohya_ss#582]
<img width="599" alt="Screenshot 2023-04-09 at 11 02 21 PM" src="https://user-images.githubusercontent.com/43231915/230768784-df08a02a-5f29-4b3a-91b1-be8379670ad9.png">

As the img.

All buttons are disabled.

Please help.

**Comment by bmaltais** [comment]
Youo must be using RUnpod of MacOS. The current code base does not work properly on both platform when clicking buttons and cause a crash of the GUI. Until someone contribute a proper fix the buttons were disables to prevent the crash.

**Comment by 0kzh** [comment]
Also getting the same error, followed macOS install instructions not using Runpod. Clicking the buttons doesn't seem to do anything.

**Comment by kekakuka** [comment]
Thanks. Will wait someone. haha

> Youo must be using RUnpod of MacOS. The current code base does not work properly on both platform when clicking buttons and cause a crash of the GUI. Until someone contribute a proper fix the buttons were disables to prevent the crash.
