### ISSUE TITLE
`train_data_dir` only accepts folders of the form `<some_pathes>/<num_of_iteration>_someString`.

### ISSUE THREAD

**Issue by uptown** [bmaltais/kohya_ss#585]
I've got an error below when I try to use train_network.py,

```
...
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
/opt/conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/opt/conda/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
mean ar error (without repeats): nan
No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります）
```

As a result of following the code, I confirmed that only the form `<some_pathes>/<num_of_iteration>_someString` of dir is accepted for `train_data_dir` from [this commit](https://github.com/bmaltais/kohya_ss/commit/7249b0baa835c133bf83fdae8319c6fc9daf0603).

Am I using something wrong or is the documentation not updated?

**Comment by DKnight54** [comment]
To my knowledge it has always worked that way? If you use the tools tab to setup the training folders, that's how it would arrange it for you?

**Comment by uptown** [comment]
I found that [the document of train_network in Japanese](https://github.com/bmaltais/kohya_ss/blob/master/train_network_README-ja.md) is different from [the document of it in English](https://github.com/bmaltais/kohya_ss/blob/master/train_network_README.md).

I haven't tested it, but if I follow the instructions in Japanese, it seems to work what I want. If you are experiencing similar issues, it would be nice to Set a repository with a specific tag or follow the Japanese instructions.
