### ISSUE TITLE
what the hell is wrong with the ui autoupdating ?

### ISSUE THREAD

**Issue by 2blackbar** [bmaltais/kohya_ss#586]
Why it was working fine and next day some errors pops out, is it autoupdating without our permission? I dont see any other way that it self corrupts ?

Crapload of errors that theres no location even tho there is .....

Errno 2] No such file or directory: 'F:/kohya_ss/trening\\\\img/40_bajki painting \\\\97.jpg'"), ('F:\\train\\img animac\\lora\\97.txt', 'F:/kohya_ss/trening\\img/40_bajki painting \\97.txt', "[Errno 2] No such file or directory: 'F:/kohya_ss/trening\\\\img/40_bajki painting \\\\97.txt'")]

Can You disable some shady under the hood downloading ? Thanks

**Comment by bmaltais** [comment]
Unless you manually run upgrade.ps1 or upgrade.bat (at least on windows) it should not auto update. I did not write the Linux/MacOS scripts so it is possible they auto update... but I don't think they do.

What platform are you running on?

**Comment by SepticSpoons** [comment]
You're pathing directly into the img folder:

> Errno 2] No such file or directory: 'F:/kohya_ss/trening\\img/40_bajki painting \\97.jpg'"), ('F:\train\img animac\lora\97.txt', 'F:/kohya_ss/trening\img/40_bajki painting \97.txt', "[Errno 2] No such file or directory: 'F:/kohya_ss/trening\\img/40_bajki painting \\97.txt'")]

Wrong: kohya_ss/training/img/20_name

Correct: kohya_ss/training/img
