### ISSUE TITLE
"setup.bat" is not running 

### ISSUE THREAD

**Issue by julianelihu** [bmaltais/kohya_ss#589]
Hello can YOU HELP ME PLEASE  , is there another way to install Lora,  "setup.bat" is not running despite I give full permission to the folders with,  Set-ExecutionPolicy Unrestricted

setup.bat : The term 'setup.bat' is not recognized as the name of a cmdlet, function, script file, or program
executable. Check if you spelled the name correctly, or if you included a path, check that the path
is correct and try again.
Online: 1 Character: 1

    + CategoryInfo          : ObjectNotFound: (setup.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by julianelihu** [comment]
![image](https://user-images.githubusercontent.com/130317318/231048538-2dd0c61f-87e1-4629-889a-1c607fa0076c.png)
Unfortunately, I have already tried to do it, and this happens to me on 2 computers with Windows 11

**Comment by julianelihu** [comment]
Thanks so much for your time and your help, please take a look at this
images

Using PowerShell with admin privileges and Set-ExecutionPolicy Unrestricted
and answer A

[image: image.png]
[image: image.png]




[image: image.png]

**Comment by bmaltais** [comment]
The images did not made it through.

**Comment by julianelihu** [comment]
Sorry the 3 images are now attach in this mail
Thanks

**Comment by jstayco** [comment]
Try running that .bat file from the regular admin cmd program on Windows and not PowerShell. See if that alleviates the issue.

**Comment by julianelihu** [comment]
Hi Jay , unfortunately same result :(

**Comment by jstayco** [comment]
@bmaltais Did the .ps1 and .bat files get LF endings when I was editing the scripts? If so, those need to be CLRF. That shouldn't be an issue going forward as I added a .gitattributes to enforce the line endings based on file extensions, but his error worries me it might be something like line endings or encodings since it dies on the first character.

**Comment by jstayco** [comment]
@julianelihu You might also try `& 'Path\To\Octo\Batch\Script.bat'`.

**Comment by julianelihu** [comment]
Hi thanks , do you mean

::

python -m venv venv
Path\To\Octo\Batch\Script.bat


pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116
--extra-index-url https://download.pytorch.org/whl/cu116
pip install --use-pep517 --upgrade -r requirements.txt
pip install -U -I --no-deps
https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl

copy /y .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
copy /y .\bitsandbytes_windows\cextension.py
.\venv\Lib\site-packages\bitsandbytes\cextension.py
copy /y .\bitsandbytes_windows\main.py
.\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py

accelerate config

**Comment by julianelihu** [comment]
not working

**Comment by jstayco** [comment]
I know it's silly, but you can check my assumption by copying the contents of the .bat file out, paste them into notepad and save the file as setup2.bat in the directory and run that file instead.

**Comment by julianelihu** [comment]
Hi Jay ,,,sorry for my mistake, my knowledge of Python is not as got as
yours :/ if you please and the line you mention , so I can save as
setup2.bat
Thanks !

@echo off

set PYTHON_VER=3.10.9

REM Check if Python version meets the recommended version
python --version 2>nul | findstr /b /c:"Python %PYTHON_VER%" >nul
if errorlevel 1 (
    echo Warning: Python version %PYTHON_VER% is recommended.
)

IF NOT EXIST venv (
    python -m venv venv
) ELSE (
    echo venv folder already exists, skipping creation...
)
call .\venv\Scripts\activate.bat

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url
https://download.pytorch.org/whl/cu116
pip install --use-pep517 --upgrade -r requirements.txt
pip install -U -I --no-deps
https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl

copy /y .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
copy /y .\bitsandbytes_windows\cextension.py
.\venv\Lib\site-packages\bitsandbytes\cextension.py
copy /y .\bitsandbytes_windows\main.py
.\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py

accelerate config

**Comment by jstayco** [comment]
No problem! No editing needed. Just copy all that stuff out of the file like you did here. Then paste it into a new file named setup2.bat and put it in the same folder as the normal setup.bat. Now run your setup2.bat just like you would the first one and see if that works.

**Comment by julianelihu** [comment]
Thanks for all your help and patience
in this mail include the results ( if I did in the right way )

**Comment by smeethan** [comment]
I had the same problem, turns out I didn't have a python path installed. Look in you C/Program Files and if there is no python on there then reinstall python and check the box to install a path.
