### ISSUE TITLE
There was a problem running the updater

### ISSUE THREAD

**Issue by yezi9527** [bmaltais/kohya_ss#607]
I reported this error when running upgrade, please help me, thank you
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment

**Comment by bmaltais** [comment]
Those warnings are normal as you are not running MacOS (darwin)

```
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment
```

Don't worry about those.
