### ISSUE TITLE
setup.sh using wrong version of python for venv

### ISSUE THREAD

**Issue by phire** [bmaltais/kohya_ss#616]
On my system I have both python 3.10 and 3.11 on my path. 

setup.sh checks that python 3.10 exists and has tkinter, but when it actually goes to create the venv, it checks for and runs `python3` first, before falling back to `python3.10` if `python3` fails. But `python3` is simlinked to python 3.11 on my system.

Looks like the order needs to be inverted. The script needs to run `python3.10` first, before falling back to `python3`.

**Comment by jstayco** [comment]
WIP installer has this for that exact reason.
How we're detecting it now (in a python launcher file after setup.sh):
```python
if command -v python3.10 >/dev/null 2>&1; then
    local PYTHON_EXEC="python3.10"
  elif command -v python3 >/dev/null 2>&1 && [ "$(python3 -c 'import sys; print(sys.version_info[:2])')" = "(3, 10)" ]; then
    local PYTHON_EXEC="python3"
  else
    echo "Error: Python 3.10 is required to run this script. Please install Python 3.10 and try again."
    exit 1
  fi
  ```
