### ISSUE TITLE
Stuck on latents

### ISSUE THREAD

**Issue by Tartoo** [bmaltais/kohya_ss#618]
Hi, I'm stuck on caching latents and I don't know why. I tried to reinstall kohya but it didn't work. I'm on a laptop with a rtx 2070.

![image](https://user-images.githubusercontent.com/71252676/231885840-02b22eca-9d81-4742-acea-02b44b70a247.png)

**Comment by bmaltais** [comment]
I suggest you reach out to kohya on his repo for this issue as it is related to his code. Not much I can do from a GUI perspective and I have not seen this one yet. I have no idea what might be causing this.

**Comment by 0010110000** [comment]
I have the same problem.  If you find a solution, let us know
