### ISSUE TITLE
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet..

### ISSUE THREAD

**Issue by RobCod** [bmaltais/kohya_ss#621]
I copied the steps pasted them in powershell and it failed to copy the dlls/py files because the directories didn't exist, I manually made the directories ran the copy lines and it copied them over and then upon hitting enter on 'accelerate config' gave me the following error:

```
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or a operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ accelerate config
+ ~~~~~~~~
         + Category Info              : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
         + FullyQualifiedErrorId : CommandNotFOundException
```
     

![image](https://user-images.githubusercontent.com/48031674/232177960-23e3f0b5-6f39-4075-a3e8-a74ac594d15a.png)

Git, python, and all the VScode redistribution are installed

**Comment by bmaltais** [comment]
Setup.bat should have installed everything... Delete the full kohya_ss and start the installation with setup.bat

**Comment by AwsMQ** [comment]
same happened with me, I tried to run setup.bat second and third time but i got the same error

**Comment by Slowpoke70** [comment]
I get this error today, Added the accelerate path env variables also.

pip show accelerate
Name: accelerate
Version: 0.0.1
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: c:\users\foo\appdata\local\programs\python\python37-32\lib\site-packages
Requires:
Required-by:
