### ISSUE TITLE
mac m1 pro : NSInternalInconsistencyException

### ISSUE THREAD

**Issue by lustfeind** [bmaltais/kohya_ss#624]
Got immediately this error when hitting the train button. Scripts exits immediately:

2023-04-16 02:08:52.232 python[3759:57764] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a44d719c __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a3ff64d4 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a45003f4 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00000001a769ec14 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 320
	4   AppKit                              0x00000001a768cee8 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 816
	5   AppKit                              0x00000001a768cbac -[NSWindow initWithContentRect:styleMask:backing:defer:] + 48
	6   libtk8.6.dylib                      0x000000011d8ae510 TkMacOSXMakeRealWindowExist + 564
	7   libtk8.6.dylib                      0x000000011d8ae15c TkWmMapWindow + 76
	8   libtk8.6.dylib                      0x000000011d803890 Tk_MapWindow + 168
	9   libtk8.6.dylib                      0x000000011d80c60c MapFrame + 76
	10  libtcl8.6.dylib                     0x000000011d72cf90 TclServiceIdle + 88
	11  libtcl8.6.dylib                     0x000000011d70d8e4 Tcl_DoOneEvent + 120
	12  libtk8.6.dylib                      0x000000011d8a0328 TkpInit + 800
	13  libtk8.6.dylib                      0x000000011d804f60 Initialize + 2432
	14  _tkinter.cpython-39-darwin.so       0x000000011d48e260 Tcl_AppInit + 92
	15  _tkinter.cpython-39-darwin.so       0x000000011d48def8 Tkapp_New + 548
	16  _tkinter.cpython-39-darwin.so       0x000000011d48dcd0 _tkinter_create_impl + 268
	17  _tkinter.cpython-39-darwin.so       0x000000011d48d7ec _tkinter_create + 272
	18  python3.9                           0x000000010275d8a8 cfunction_vectorcall_FASTCALL + 88
	19  python3.9                           0x0000000102826b08 call_function + 128
	20  python3.9                           0x000000010281fca4 _PyEval_EvalFrameDefault + 23340
	21  python3.9                           0x0000000102818bb8 _PyEval_EvalCode + 496
	22  python3.9                           0x0000000102700fc8 _PyFunction_Vectorcall + 192
	23  python3.9                           0x00000001027004ac _PyObject_FastCallDictTstate + 112
	24  python3.9                           0x0000000102787ea4 slot_tp_init + 188
	25  python3.9                           0x0000000102792f80 type_call + 300
	26  python3.9                           0x00000001027001d4 _PyObject_MakeTpCall + 136
	27  python3.9                           0x0000000102826bc0 call_function + 312
	28  python3.9                           0x000000010281fca4 _PyEval_EvalFrameDefault + 23340
	29  python3.9                           0x00000001027010ac function_code_fastcall + 168
	30  python3.9                           0x00000001027004ac _PyObject_FastCallDictTstate + 112
	31  python3.9                           0x0000000102787ea4 slot_tp_init + 188
	32  python3.9                           0x0000000102792f80 type_call + 300
	33  python3.9                           0x00000001027001d4 _PyObject_MakeTpCall + 136
	34  python3.9                           0x0000000102826bc0 call_function + 312
	35  python3.9                           0x000000010281e3ec _PyEval_EvalFrameDefault + 17012
	36  python3.9                           0x0000000102818bb8 _PyEval_EvalCode + 496
	37  python3.9                           0x0000000102700fc8 _PyFunction_Vectorcall + 192
	38  python3.9                           0x0000000102700534 _PyObject_FastCallDictTstate + 248
	39  python3.9                           0x0000000102787ea4 slot_tp_init + 188
	40  python3.9                           0x0000000102792f80 type_call + 300
	41  python3.9                           0x00000001027001d4 _PyObject_MakeTpCall + 136
	42  python3.9                           0x0000000102826bc0 call_function + 312
	43  python3.9                           0x000000010281e470 _PyEval_EvalFrameDefault + 17144
	44  python3.9                           0x0000000102818bb8 _PyEval_EvalCode + 496
	45  python3.9                           0x0000000102700fc8 _PyFunction_Vectorcall + 192
	46  python3.9                           0x0000000102826b08 call_function + 128
	47  python3.9                           0x000000010281e470 _PyEval_EvalFrameDefault + 17144
	48  python3.9                           0x0000000102818bb8 _PyEval_EvalCode + 496
	49  python3.9                           0x0000000102700fc8 _PyFunction_Vectorcall + 192
	50  python3.9                           0x0000000102826b08 call_function + 128
	51  python3.9                           0x000000010281e3ec _PyEval_EvalFrameDefault + 17012
	52  python3.9                           0x0000000102818bb8 _PyEval_EvalCode + 496
	53  python3.9                           0x0000000102700fc8 _PyFunction_Vectorcall + 192
	54  python3.9                           0x00000001028401d0 _PyObject_VectorcallTstate.4574 + 96
	55  python3.9                           0x0000000102840030 context_run + 92
	56  python3.9                           0x000000010275d7b0 cfunction_vectorcall_FASTCALL_KEYWORDS + 84
	57  python3.9                           0x000000010281aa10 _PyEval_EvalFrameDefault + 2200
	58  python3.9                           0x00000001027010ac function_code_fastcall + 168
	59  python3.9                           0x0000000102826b08 call_function + 128
	60  python3.9                           0x000000010281eb84 _PyEval_EvalFrameDefault + 18956
	61  python3.9                           0x00000001027010ac function_code_fastcall + 168
	62  python3.9                           0x0000000102826b08 call_function + 128
	63  python3.9                           0x000000010281eb84 _PyEval_EvalFrameDefault + 18956
	64  python3.9                           0x00000001027010ac function_code_fastcall + 168
	65  python3.9                           0x0000000102704414 method_vectorcall + 388
	66  python3.9                           0x0000000102905598 t_bootstrap + 172
	67  python3.9                           0x0000000102890c18 pythread_wrapper + 48
	68  libsystem_pthread.dylib             0x00000001a437ffa8 _pthread_start + 148
	69  libsystem_pthread.dylib             0x00000001a437ada0 thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
./gui.sh: line 15:  3759 Abort trap: 6           python "$SCRIPT_DIR/kohya_gui.py" "$@"

**Comment by AlbertWang0116** [comment]
I encountered the same issue. Besides that, I'm not able to open Finder to select a path for configuration, pre-trained model, etc.

I tried using an older version (v21.4.2) but the issue still persists.

**Comment by firstfan** [comment]
Same here on M2 MacBook Pro

**Comment by wechoi-hh** [comment]
Don't load config file
Don't save config file

**Comment by ximxim** [comment]
Same here. Any solution yet?

**Comment by andupotorac** [comment]
> float

Has nothing to do with this. I had it selected before and it was working. I still have it selected and it's not working anymore.
