### ISSUE TITLE
Extracted lora is in error.

### ISSUE THREAD

**Issue by GeneralAwareness** [bmaltais/kohya_ss#626]
activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7fd740735b10>, <modules.extra_networks.ExtraNetworkParams object at 0x7fd740736260>]: AssertionError
Traceback (most recent call last):
  File "/home/ga/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/home/ga/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/home/ga/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/../../extensions-builtin/Lora/lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/home/ga/stable-diffusion-webui/extensions/a1111-sd-webui-lycoris/../../extensions-builtin/Lora/lora.py", line 185, in load_lora
    assert False, f'Bad Lora layer name: {key_diffusers} - must end in lora_up.weight, lora_down.weight or alpha'
AssertionError: Bad Lora layer name: lora_unet_down_blocks_0_downsamplers_0_conv.lora_mid.weight - must end in lora_up.weight, lora_down.weight or alpha

Not sure why my extracted loras are coming up like this and not working.

**Comment by bmaltais** [comment]
What type of LoRA is it? You may need to install the LyCORIS extension if it is a LoHA...

https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

**Comment by GeneralAwareness** [comment]
It was extracted and that extension is mandatory for any 2.1 user so I have it, and it is updated too.

**Comment by GeneralAwareness** [comment]
His code or the code of the Lycoris extension?  If the extension I just did and Lycoris just had no answers and decided to ignore it.

**Comment by bmaltais** [comment]
Oh... you are extracting a LyCORIS... then yes, this is something you need to raise to https://github.com/KohakuBlueleaf/LyCORIS

**Comment by GeneralAwareness** [comment]
> Oh... you are extracting a LyCORIS... then yes, this is something you need to raise to https://github.com/KohakuBlueleaf/LyCORIS

No, I wasn't extracting a Lycoris so don't be so fast to jump the gun there.  I extracted a Lora.  You know the extract lora tab?  Yep, that one.  Not your issue anyway, but thanks.
