### ISSUE TITLE
.\venv\Scripts\activate : The term '.\venv\Scripts\activate' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by Isadorewyt** [bmaltais/kohya_ss#629]
.\venv\Scripts\activate : The term '.\venv\Scripts\activate' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ .\venv\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\venv\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bmaltais** [comment]
Was the venv folder created when you ran setup.bat?

**Comment by Isadorewyt** [comment]
where should the venv folder be? or How do I create it?

**Comment by Isadorewyt** [comment]
where should the venv folder be? or How do I create it?

**Comment by bmaltais** [comment]
Just run the .\setup.bat command in the repo folder to configure it. There will be a venv folder created.
