### ISSUE TITLE
Question about Enable_buckets

### ISSUE THREAD

**Issue by jonwong666** [bmaltais/kohya_ss#631]
Just want to check in regarding this function, enable_buckets

If one has this enable it allows training of images larger then 512,512 and in non square ratio correct?

So I don't need to resize my images to 512px and can keep them non-square?

Watching @bmaltais video, it seems he is using fairly hi-res images and non square crop.

Thanks

**Comment by bmaltais** [comment]
This is 100% correct.

**Comment by jonwong666** [comment]
> This is 100% correct.

thanks for confirming.
