### ISSUE TITLE
tensorflow==2.10.1 not found

### ISSUE THREAD

**Issue by brunoavignon** [bmaltais/kohya_ss#638]
Hello, I'm running under windows 10 professionnal,  with a GTX1080Ti 
I tried to install with the setup.bat, as it didn't go through,  I installed 1 by 1 the requirement.txt list in the (venv), everything installed ok except for tensorflow==2.10.1 which seems to be unavailable: 

ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==2.10.1

I tried with tensorflow 2.12.0 but then it says "wrong version":
(venv) F:\DEEP-LEARNING\AI\Kohya\kohya_ss>gui-user.bat
Validating that requirements are satisfied.
Error: The following packages have the wrong version:
 - tensorboard==2.10.1 ; sys_platform != 'darwin' (expected version tensorboard==2.10.1; sys_platform != "darwin", found version 2.12.2)
 - tensorflow==2.10.1; sys_platform != 'darwin' (expected version tensorflow==2.10.1; sys_platform != "darwin", found version 2.12.0)

what can you suggest? many thanks in advance

**Comment by Coca187** [comment]
Same problem here. Win10, RTX 3090

**Comment by bmaltais** [comment]
And you have installed using .\setup.bat? Have you tried deleting the kohya_ss folder and re-install from scratch?

**Comment by brunoavignon** [comment]
Hi Bernard, thanks for your answer, I tried this morning deleting the kohya_ss and the pip cache, choosing "no distributed training", gpu, no dynamo, no deep speed, all gpu, fp16 options. I performed the upgrade.bat just afterwards with the same error at the end : ERROR: Could not find a version that satisfies the requirement
[lora install.txt](https://github.com/bmaltais/kohya_ss/files/11283459/lora.install.txt)
 tensorflow==2.10.1
in fact it does not install any of the requirements on the venv when it falls on this error....
[lora install.txt](https://github.com/bmaltais/kohya_ss/files/11283462/lora.install.txt)
many thanks in advance for your help
kind regards
Bruno

**Comment by Coca187** [comment]
Hi, thank you for your answer. Yes, I have run setup.bat several times and also deleted the folder several times.

May I simply copy the lines from my CMD here. You might discover something that I'm overlooking. I am a complete layman, sorry.

Microsoft Windows [Version 10.0.19045.2846]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

D:\Super Stable Deffusion 2.0\Kohya>git clone https://github.com/bmaltais/kohya_ss.git
Cloning into 'kohya_ss'...
remote: Enumerating objects: 4657, done.
remote: Counting objects: 100% (471/471), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 4657 (delta 366), reused 438 (delta 350), pack-reused 4186
Receiving objects: 100% (4657/4657), 4.23 MiB | 2.88 MiB/s, done.
Resolving deltas: 100% (3181/3181), done.

D:\Super Stable Deffusion 2.0\Kohya>cd kohya_ss

D:\Super Stable Deffusion 2.0\Kohya\kohya_ss>setup.bat
Warning: Python version 3.10.9 is recommended.
Do you want to uninstall previous versions of torch and associated files before installing?
[1] - Yes
[2] - No
Enter your choice (1 or 2): 1
WARNING: Skipping xformers as it is not installed.
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
Please choose the version of torch you want to install:
[1] - v1 (torch 1.12.1)
[2] - v2 (torch 2.0.0)
Enter your choice (1 or 2): 1
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu116 (from versions: 2.0.0)
ERROR: No matching distribution found for torch==1.12.1+cu116

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Ignoring gradio: markers 'sys_platform == "darwin"' don't match your environment
Ignoring tensorboard: markers 'sys_platform == "darwin"' don't match your environment
Ignoring huggingface-hub: markers 'sys_platform == "darwin"' don't match your environment
Processing d:\super stable deffusion 2.0\kohya\kohya_ss
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting accelerate==0.15.0
  Using cached accelerate-0.15.0-py3-none-any.whl (191 kB)
Collecting albumentations==1.3.0
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
Collecting altair==4.2.2
  Using cached altair-4.2.2-py3-none-any.whl (813 kB)
Collecting bitsandbytes==0.35.0
  Using cached bitsandbytes-0.35.0-py3-none-any.whl (62.5 MB)
Collecting dadaptation==1.5
  Using cached dadaptation-1.5.tar.gz (8.3 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting diffusers[torch]==0.10.2
  Using cached diffusers-0.10.2-py3-none-any.whl (503 kB)
Collecting easygui==0.98.3
  Using cached easygui-0.98.3-py2.py3-none-any.whl (92 kB)
Collecting einops==0.6.0
  Using cached einops-0.6.0-py3-none-any.whl (41 kB)
Collecting ftfy==6.1.1
  Using cached ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting gradio==3.27.0
  Using cached gradio-3.27.0-py3-none-any.whl (17.3 MB)
Collecting lion-pytorch==0.0.6
  Using cached lion_pytorch-0.0.6-py3-none-any.whl (4.2 kB)
Collecting opencv-python==4.7.0.68
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
Collecting pytorch-lightning==1.9.0
  Using cached pytorch_lightning-1.9.0-py3-none-any.whl (825 kB)
Collecting safetensors==0.2.6
  Using cached safetensors-0.2.6-cp311-cp311-win_amd64.whl (268 kB)
Collecting tensorboard==2.10.1
  Using cached tensorboard-2.10.1-py3-none-any.whl (5.9 MB)
Collecting tk==0.1.0
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting toml==0.10.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting transformers==4.26.0
  Using cached transformers-4.26.0-py3-none-any.whl (6.3 MB)
Collecting voluptuous==0.13.1
  Using cached voluptuous-0.13.1-py3-none-any.whl (29 kB)
Collecting fairscale==0.4.13
  Using cached fairscale-0.4.13.tar.gz (266 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting requests==2.28.2
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting timm==0.6.12
  Using cached timm-0.6.12-py3-none-any.whl (549 kB)
Collecting huggingface-hub==0.13.3
  Using cached huggingface_hub-0.13.3-py3-none-any.whl (199 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow==2.10.1

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip
.\bitsandbytes_windows\libbitsandbytes_cpu.dll
Das System kann den angegebenen Pfad nicht finden.
.\bitsandbytes_windows\libbitsandbytes_cuda116.dll
Das System kann den angegebenen Pfad nicht finden.
        0 Datei(en) kopiert.
Das System kann den angegebenen Pfad nicht finden.
        0 Datei(en) kopiert.
Das System kann den angegebenen Pfad nicht finden.
        0 Datei(en) kopiert.
Der Befehl "accelerate" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(venv) D:\Super Stable Deffusion 2.0\Kohya\kohya_ss>

**Comment by brunoavignon** [comment]
@Coca187  it seems we have exactly the same problem...

**Comment by Coca187** [comment]
@brunoavignon Unfortunately, yes, but the positive is. If @bmaltais  can help one of us, it will help both of us and possibly a few others. I am hopeful 😄

**Comment by brunoavignon** [comment]
can it be linked to the python version? I just noticed that the install uses the python 3.11 instead of python 3.10.9 ...

**Comment by brunoavignon** [comment]
a issue in MAC OS world suggest me this, however they solved the problem by uninstalling python 3.11 which is impossible in my case as I only have 3.10.9 installed... it seems the setup.bat chooses the wrong python version for the venv...

**Comment by brunoavignon** [comment]
yes! this time it is ok I just changed the setup.bat on line 12 to put python310 instead of python, it appears that I had python 3.11 installed and this wrong version was taken by default...
so to summerize you definitely have to make sure you are not using python 3.11 as the version for tensorflow is not the good one for this version of python...

**Comment by brunoavignon** [comment]
sorry I should have been more explanatory, when you install Python 3.10.9 note the location where it stands, then you can either rename python.exe into python310.exe or make a copy with teh same name, do the same with python 3.dll (I'm not sure I've done it on purpose but on my directory I have python310.dll and python310.exe) 
you then can check: open cmd window, type python: it should show the wrong version (3.11?) , type exit(), then type python310 it should be the good one

**Comment by Coca187** [comment]
Thank you a lot! It works now, have a great day :)
