### ISSUE TITLE
After update, a new error raised, "fp16 mixed precision requires a GPU"

### ISSUE THREAD

**Issue by powerdoom** [bmaltais/kohya_ss#639]
After update, a new error raised, "fp16 mixed precision requires a GPU". Cannot work.

prepare accelerator
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ F:\AI\kohya_ss\train_network.py:773 in <module>                                                  │
│                                                                                                  │
│   770 │   args = parser.parse_args()                                                             │
│   771 │   args = train_util.read_config_from_file(args, parser)                                  │
│   772 │                                                                                          │
│ ❱ 773 │   train(args)                                                                            │
│   774                                                                                            │
│                                                                                                  │
│ F:\AI\kohya_ss\train_network.py:140 in train                                                     │
│                                                                                                  │
│   137 │                                                                                          │
│   138 │   # acceleratorを準備する                                                                │
│   139 │   print("prepare accelerator")                                                           │
│ ❱ 140 │   accelerator, unwrap_model = train_util.prepare_accelerator(args)                       │
│   141 │   is_main_process = accelerator.is_main_process                                          │
│   142 │                                                                                          │
│   143 │   # mixed precisionに対応した型を用意しておき適宜castする                                │
│                                                                                                  │
│ F:\AI\kohya_ss\library\train_util.py:2742 in prepare_accelerator                                 │
│                                                                                                  │
│   2739 │   │   log_prefix = "" if args.log_prefix is None else args.log_prefix                   │
│   2740 │   │   logging_dir = args.logging_dir + "/" + log_prefix + time.strftime("%Y%m%d%H%M%S"  │
│   2741 │                                                                                         │
│ ❱ 2742 │   accelerator = Accelerator(                                                            │
│   2743 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   2744 │   │   mixed_precision=args.mixed_precision,                                             │
│   2745 │   │   log_with=log_with,                                                                │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\acce │
│ lerator.py:355 in __init__                                                                       │
│                                                                                                  │
│    352 │   │   if self.state.mixed_precision == "fp16" and self.distributed_type != Distributed  │
│    353 │   │   │   self.native_amp = True                                                        │
│    354 │   │   │   if not torch.cuda.is_available() and not parse_flag_from_env("ACCELERATE_USE  │
│ ❱  355 │   │   │   │   raise ValueError(err.format(mode="fp16", requirement="a GPU"))            │
│    356 │   │   │   kwargs = self.scaler_handler.to_kwargs() if self.scaler_handler is not None   │
│    357 │   │   │   if self.distributed_type == DistributedType.FSDP:                             │
│    358 │   │   │   │   from torch.distributed.fsdp.sharded_grad_scaler import ShardedGradScaler  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: fp16 mixed precision requires a GPU
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in               │
│ _run_module_as_main                                                                              │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code      │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\comm │
│ ands\accelerate_cli.py:45 in main                                                                │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\comm │
│ ands\launch.py:1104 in launch_command                                                            │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\comm │
│ ands\launch.py:567 in simple_launcher                                                            │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=F:\\AI\\stableDiffusionWeb\\stable-diffusion-webui\\models\\Stable-diffusion\\chilloutm
ix_NiPrunedFp32Fix.safetensors', '--train_data_dir=F:\\AI\\Kohya_Lora_Train\\image', '--resolution=512,512',
'--output_dir=F:\\AI\\Kohya_Lora_Train\\model', '--logging_dir=F:\\AI\\Kohya_Lora_Train\\log', '--network_alpha=1',
'--training_comment=TaurusAldebaran', '--save_model_as=safetensors', '--network_module=networks.lora',
'--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=saintSeiyaTaurusAldebaran_v10',
'--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1',
'--max_train_steps=4000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16',
'--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--clip_skip=2', '--bucket_reso_steps=64',
'--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Try going back to the previous release. Kohya has done a lot of update to his code that is now part of the latest release. Perhaps it is causing an issue with your configuration?
