### ISSUE TITLE
Getting errors with Dreambooth LoRA

### ISSUE THREAD

**Issue by The-Mer0vingian** [bmaltais/kohya_ss#640]
Hello, i'm getting errors when i'm trying to train model with Dreambooth Lora. 

> Folder 187_Matthias: 8 images found
> Folder 187_Matthias: 1496 steps
> max_train_steps = 748
> stop_text_encoder_training = 0
> lr_warmup_steps = 0
> accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --v2 --v_parameterization --pretrained_model_name_or_path="stabilityai/stable-diffusion-2" --train_data_dir="K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/image" --resolution=512,512 --output_dir="K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/model" --logging_dir="K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="Matth" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="748" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers --bucket_no_upscale
> WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
> Error caught was: No module named 'triton'
> v2 with clip_skip will be unexpected / v2でclip_skipを使用することは想定されていません
> prepare tokenizer
> Use DreamBooth method.
> prepare images.
> found directory K:\Outils et Ressources IA\images pour training\mattkohya\image\MATTHIAS\image\187_Matthias contains 8 image files
> 1496 train images with repeating.
> 0 reg images.
> no regularization images / 正則化画像が見つかりませんでした
> [Dataset 0]
>   batch_size: 2
>   resolution: (512, 512)
>   enable_bucket: False
> 
>   [Subset 0 of Dataset 0]
>     image_dir: "K:\Outils et Ressources IA\images pour training\mattkohya\image\MATTHIAS\image\187_Matthias"
>     image_count: 8
>     num_repeats: 187
>     shuffle_caption: False
>     keep_tokens: 0
>     caption_dropout_rate: 0.0
>     caption_dropout_every_n_epoches: 0
>     caption_tag_dropout_rate: 0.0
>     color_aug: False
>     flip_aug: False
>     face_crop_aug_range: None
>     random_crop: False
>     token_warmup_min: 1,
>     token_warmup_step: 0,
>     is_reg: False
>     class_tokens: Matthias
>     caption_extension: .txt
> 
> 
> [Dataset 0]
> loading image sizes.
> 100%|██████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 1223.94it/s]
> prepare dataset
> prepare accelerator
> Using accelerator 0.15.0 or above.
> loading model for process 0/1
> load Diffusers pretrained models
> text_encoder\model.safetensors not found
> Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████| 16/16 [00:00<?, ?it/s]
> C:\Users\Mad\kohya_ss\venv\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
>   warnings.warn(
> Replace CrossAttention.forward to use xformers
> [Dataset 0]
> caching latents.
> 100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:02<00:00,  3.69it/s]
> import network module: networks.lora
> create LoRA network. base dim (rank): 128, alpha: 128.0
> create LoRA for Text Encoder: 138 modules.
> create LoRA for U-Net: 192 modules.
> enable LoRA for text encoder
> enable LoRA for U-Net
> prepare optimizer, data loader etc.
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
> ================================================================================
> CUDA SETUP: Loading binary C:\Users\Mad\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
> use 8-bit AdamW optimizer | {}
> running training / 学習開始
>   num train images * repeats / 学習画像の数×繰り返し回数: 1496
>   num reg images / 正則化画像の数: 0
>   num batches per epoch / 1epochのバッチ数: 748
>   num epochs / epoch数: 1
>   batch size per device / バッチサイズ: 2
>   gradient accumulation steps / 勾配を合計するステップ数 = 1
>   total optimization steps / 学習ステップ数: 748
> steps:   0%|                                                                                   | 0/748 [00:00<?, ?it/s]epoch 1/1
> WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
> Error caught was: No module named 'triton'
> Traceback (most recent call last):
>   File "C:\Users\Mad\kohya_ss\train_network.py", line 773, in <module>
>     train(args)
>   File "C:\Users\Mad\kohya_ss\train_network.py", line 604, in train
>     noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
>     return convert_to_fp32(self.model_forward(*args, **kwargs))
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
>     return func(*args, **kwargs)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
>     sample, res_samples = downsample_block(
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
>     hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
>     hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
>     hidden_states = self.attn1(norm_hidden_states) + hidden_states
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "C:\Users\Mad\kohya_ss\library\train_util.py", line 1837, in forward_xformers
>     out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
>     return _memory_efficient_attention(
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 299, in _memory_efficient_attention
>     return _fMHA.apply(
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 41, in forward
>     out, op_ctx = _memory_efficient_attention_forward_requires_grad(
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 327, in _memory_efficient_attention_forward_requires_grad
>     out = op.apply(inp, needs_gradient=True)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
>     out, lse, rng_seed, rng_offset = cls.OPERATOR(
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
>     return self._op(*args, **kwargs or {})
> RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 13 argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor? cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)
> steps:   0%|                                                                                   | 0/748 [00:04<?, ?it/s]
> Traceback (most recent call last):
>   File "C:\Users\Mad\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\Mad\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Mad\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
>     simple_launcher(args)
>   File "C:\Users\Mad\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['C:\\Users\\Mad\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--v2', '--v_parameterization', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2', '--train_data_dir=K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/image', '--resolution=512,512', '--output_dir=K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/model', '--logging_dir=K:/Outils et Ressources IA/images pour training/mattkohya/image/MATTHIAS/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Matth', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=748', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

Someone can help me?

**Comment by sandbb30** [comment]
Iam having this same issue can anyone help
