### ISSUE TITLE
REQUEST: add Merge LoCon2Model & Extract DyLORA in utilities

### ISSUE THREAD

**Issue by YKefasu** [bmaltais/kohya_ss#641]
REQUEST utilities features : 
1. Merge LoCon to Checkpoint
2. Extract Spesific Rank from DyLORA

**Comment by bmaltais** [comment]
I will see if I can add them soon...

**Comment by bmaltais** [comment]
I have added the ability to merge to a checkpoint. In the dev branch at the moment if you want to try.

**Comment by bmaltais** [comment]
OK, THe Extract DyLoRA GUI has been added under Utilities.

**Comment by YKefasu** [comment]
Ok thankyou

**Comment by YKefasu** [comment]
@bmaltais the utilities menu are gone in 2023/05/01 (v21.5.7) ??

**Comment by YKefasu** [comment]
i mean the Merge LoCon and extract dylore tab
