### ISSUE TITLE
train stops on the way.

### ISSUE THREAD

**Issue by radiceradice** [bmaltais/kohya_ss#647]
It  stop in the following situations.
----------------------------------------------------------
Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading config...
Folder 10_yos yuko : 500 steps
Regularisation images are used... Will double the number of steps required...
max_train_steps = 8000
stop_text_encoder_training = 0
lr_warmup_steps = 800
accelerate launch --num_cpu_threads_per_process=16 "train_db.py" --v2 --v_parameterization --enable_bucket --pretrained_model_name_or_path="D:/SD_hinanojyo/v2-1_768-ema-pruned.safetensors" --train_data_dir="C:\kohya_ss 2\kohya_ss-21.5.4\train\sozai" --reg_data_dir="C:\kohya_ss 2\kohya_ss-21.5.4\train\saisoku" --resolution= --output_dir="D:\SD_hozon\model_souko\v2-1_768-ema-pruned" --logging_dir="C:\kohya_ss_GUI_0421\kohya_ss\train\Logging" --save_model_as=safetensors --output_name="v2-1_768-ema-pruned_50p10st8ep_512_V1" --max_data_loader_n_workers="0" --learning_rate="1e-5" --lr_scheduler="cosine" --lr_warmup_steps="800" --train_batch_size="1" --max_train_steps="8000" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --bucket_no_upscale
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "C:\kohya_ss 2\kohya_ss-21.5.4\train_db.py", line 437, in <module>
    train(args)
  File "C:\kohya_ss 2\kohya_ss-21.5.4\train_db.py", line 30, in train
    train_util.prepare_dataset_args(args, False)
  File "C:\kohya_ss 2\kohya_ss-21.5.4\library\train_util.py", line 2684, in prepare_dataset_args
    args.resolution = tuple([int(r) for r in args.resolution.split(",")])
  File "C:\kohya_ss 2\kohya_ss-21.5.4\library\train_util.py", line 2684, in <listcomp>
    args.resolution = tuple([int(r) for r in args.resolution.split(",")])
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\radic\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\radic\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_db.py', '--v2', '--v_parameterization', '--enable_bucket', '--pretrained_model_name_or_path=D:/SD_hinanojyo/v2-1_768-ema-pruned.safetensors', '--train_data_dir=C:\\kohya_ss 2\\kohya_ss-21.5.4\\train\\sozai', '--reg_data_dir=C:\\kohya_ss 2\\kohya_ss-21.5.4\\train\\saisoku', '--resolution=', '--output_dir=D:\\SD_hozon\\model_souko\\v2-1_768-ema-pruned', '--logging_dir=C:\\kohya_ss_GUI_0421\\kohya_ss\\train\\Logging', '--save_model_as=safetensors', '--output_name=v2-1_768-ema-pruned_50p10st8ep_512_V1', '--max_data_loader_n_workers=0', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=800', '--train_batch_size=1', '--max_train_steps=8000', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--bucket_no_upscale']' returned non-zero exit status 1.

----------------------------------------------------------
I unzipped the v21.5.4 zip file and installed from setup.bat.
----------------------------------------------------------

Do you want to uninstall previous versions of torch and associated files before installing?
[1] - Yes
Found existing installation: xformers 0.0.17
Uninstalling xformers-0.0.17:
  Successfully uninstalled xformers-0.0.17
Found existing installation: torch 2.0.0+cu118
Uninstalling torch-2.0.0+cu118:
  Successfully uninstalled torch-2.0.0+cu118
Found existing installation: torchvision 0.15.1+cu118
Uninstalling torchvision-0.15.1+cu118:
  Successfully uninstalled torchvision-0.15.1+cu118

Please choose the version of torch you want to install:
[2] - v2 (torch 2.0.0)
Successfully installed torch-2.0.0+cu118 torchvision-0.15.1+cu118

Successfully built library
Installing collected packages: library
  Attempting uninstall: library
    Found existing installation: library 1.0.3
    Uninstalling library-1.0.3:
      Successfully uninstalled library-1.0.3
Successfully installed library-1.0.3

Installing collected packages: xformers
Successfully installed xformers-0.0.17

---------------------------------------------------------------------------------------------------------------Which type of machine are you using?
No distributed training
Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]:no
Do you wish to optimize your script with torch dynamo?[yes/NO]:no
Do you want to use DeepSpeed? [yes/NO]: no
What GPU(s) (by id) should be used for training on this machine as a comma-seperated list? [all]:all
------------------------------------------------------------------------------------------------------------------------Do you wish to use FP16 or BF16 (mixed precision)?                                                                                                             * bf166
-----------------------------------------
using  GeForce RTX 4080
-----------------------------------------
Any advice would be appreciated.

**Comment by Lsun009** [comment]
same problem
