### ISSUE TITLE
How can I localize/translate this project into Chinese?

### ISSUE THREAD

**Issue by FayeValentineSSS** [bmaltais/kohya_ss#649]
As the title suggests
Can kohya_ss's WebUI not be merged into Stable Diffusion and can it only exist as a standalone WebUI page?

**Comment by bmaltais** [comment]
Good question. I have never planned for locallisation of the UI... so I am not sure where I would need to start with this... If someone want to propose the localisation PR that would make thing easy to maintain I am not against it,

**Comment by burashixi** [comment]
I'm planning to do the localization things. I have no coding background and do a little research on localization in Python. I need to change some Python codes I do not want to mess up. so my first plan is to use javascript to modify the web page. Then I will move on to the Python files for "real localization"
