### ISSUE TITLE
cuDNN update is not working

### ISSUE THREAD

**Issue by SergeySypalo** [bmaltais/kohya_ss#650]
Hi there, thanks for the great GUI first of all!

I tried to update cuDNN to the recently released 8.9, but files are not copied, even though I'm getting message that they are successfully copied.
Steps to reproduce:
Same as in manual, downloaded cuDNN from NVidia, put files into cudnn_windows folder
```
PS L:\kohya_ss> .\venv\Scripts\activate
(venv) PS L:\kohya_ss> python .\tools\cudann_1.8_install.py
[ ] xformers version 0.0.16 installed.
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.10.2 installed.
[+] transformers version 4.26.0 installed.
[!] torch version 1.13.1+cu117 installed.
[!] torchvision version 0.14.1+cu117 installed.
Checking for CUDNN files in L:\kohya_ss\venv\Lib\site-packages\torch\lib
Copied CUDNN 8.6 files to destination
(venv) PS L:\kohya_ss> python -c "import torch; print(torch.backends.cudnn.version())"
8500
```
While it should be 8900
Also, this link on the repo's main page is broken: https://github.com/bmaltais/kohya_ss#optional--cudnn-86

**Comment by bmaltais** [comment]
Don't worry about the version listed... the script had `Copied CUDNN 8.6` hardcoded inside and this is why it is reporting the wrong version.

**Comment by SergeySypalo** [comment]
Hm, but why it returns previous version 8.5 and not 8.6?
It just confusing.

**Comment by bmaltais** [comment]
Yeah, I did not write the code for that one (borrowed from another project) and I think it is due for a rewrite/ replacement... Might look into it if I can stop playing with bayesian merge:-)
