### ISSUE TITLE
I have a 3060 and a 3090ti and a 3090ti.

### ISSUE THREAD

**Issue by nofacedeepfake** [bmaltais/kohya_ss#653]
I have a 3060 and a 3090ti and a 3090ti. Running it sees only the 3060. All tried, torn down again, put up. did not help, moved the hdmi cord did not help. what to do?

**Comment by nofacedeepfake** [comment]
the problem is in the tools folder debug_info.py rolled back to version 21.5.4 and everything works with one card 3090

**Comment by nofacedeepfake** [comment]
how to prescribe the selection of a specific video card?

**Comment by Dragoy** [comment]
Same thing, have two cards 3090 and 2080Ti, for some reason he chose the weaker card 2080Ti by default. Perhaps there should be an argument that allows you to choose the device? @bmaltais
<img width="353" alt="image" src="https://user-images.githubusercontent.com/4968313/233853113-3b1a672b-ee30-4448-9f5a-a1ca9679e637.png">

**Comment by FurkanGozukara** [comment]
I am also trying to start second card but command succeeds @bmaltais

**Comment by Dragoy** [comment]
I checked the video card load everything works just the opposite 3090 under load and 2080 is not involved in the learning process. It's just that the console inscription is confusing.

**Comment by FurkanGozukara** [comment]
I found a solution for this

Hopefully will show in upcoming tutorial

**Comment by nofacedeepfake** [comment]
> I found a solution for this
> 
> Hopefully will show in upcoming tutorial


How to run a specific video card ?

**Comment by noxiouscardiumdimidium** [comment]
//Prelauncher script: Formatted for Linux Xunbuntu - Tesla M40 on GPU1; If you need windows equivalent  - I dont speak that!!! xD I'm messing with you, change topline "#!/bin/bash"  to "@echo off", and replace the terms "export" with "set" - run this to launch gui.sh (or .bat) with only the selected gpus, with listed arch# available for cuda computing
Be sure to set YOUR gpu's arch rating, and the appropriate gpu slot #

###
#!/bin/bash

export TORCH_CUDA_ARCH_LIST=5.2
export CUDA_VISIBLE_DEVICES=1
		
./gui.sh 
###

//FROM TERM/WSL-CMD enter command: "accelerate config"
environment?: "This Machine"
Type?: "no distributed training"
on cpu?: "no"
dynamo?: "no"
deepspeed?: "no"
gpus by id?: "1"
mixed precision?: (depends on if BF16 gives you errors, else opt FP16)
!!!DONE!!!

**Comment by FurkanGozukara** [comment]
> > I found a solution for this
> > Hopefully will show in upcoming tutorial
> 
> How to run a specific video card ?

here explained in this video

30.) Kohya Web GU - Automatic1111 Web UI - PC - Free

[**Generate Studio Quality Realistic Photos By Kohya LoRA Stable Diffusion Training - Full Tutorial**](https://youtu.be/TpuDOsuKIBo)

[![image](https://user-images.githubusercontent.com/19240467/235155355-83ff14e5-a3c8-4ae8-83a5-6d2573189a22.png)](https://youtu.be/TpuDOsuKIBo)
