### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by Havasiz** [bmaltais/kohya_ss#654]
Hello, whenever I try to run BLIP captioning, I get this error

`GIT captioning files in C:/Users/HAVASIZ/Downloads/testfolder...
./venv/Scripts/python.exe finetune/make_captions_by_git.py --batch_size="1" --max_data_loader_n_workers="2" --max_length="75" --caption_extension=".txt" "C:/Users/HAVASIZ/Downloads/testfolder"
Traceback (most recent call last):
  File "C:\Users\HAVASIZ\Desktop\Kohya\kohya_ss\finetune\make_captions_by_git.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'`

And when I try to run pip install Pillow I get this:
`Requirement already satisfied: Pillow in c:\users\havasiz\appdata\local\programs\python\python310\lib\site-packages (9.4.0)`

I tried running another codes that contained `from PIL import Image` and it worked perfectly but when I try to use kohya it says PIL not found?

Isn't there a way where I can see where the code looks for the module named "PIL" because I have it installed in `C:\\Users\\HAVASIZ\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PIL` but maybe the code looks somewhere else?

**Comment by Havasiz** [comment]
I fixed the issue by installing the packages inside the env folder inside kohya_ss. The issue was that I installed Pillow into Appdata but the code was searching inside the env folder.

**Comment by TElu22** [comment]
How did you install the packages inside the venv folder?
