### ISSUE TITLE
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

### ISSUE THREAD

**Issue by keke1990-2013** [bmaltais/kohya_ss#658]
raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['G:\\SDAI\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=G:/lora_train/image', '--resolution=768,768', '--output_dir=G:/lora_train/model', '--logging_dir=G:/lora_train/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=zhuzijing', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=1800', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 2.

please~~~help~~
o(╥﹏╥)o

**Comment by wangwenqiao666** [comment]
set Memory efficient attention=true and select Optimizer = AdamW

**Comment by Zoltekk** [comment]
> set Memory efficient attention=true and select Optimizer = AdamW

Doesn't help
