### ISSUE TITLE
The coexistence problem of multiple versions of Python

### ISSUE THREAD

**Issue by JoeanAmier** [bmaltais/kohya_ss#660]
I have Python 3.11 and Conda (Python 3.10) installed on my computer, and when I run setup.bat the virtual environment created is for Python 3.11, how do I get it to use conda (Python 3.10) to create the virtual environment when I run setup.bat? My computer is Windows

**Comment by 1r00t** [comment]
I'm on linux so I'm not 100% sure about windows. But I guess you have to edit this file:
https://github.com/bmaltais/kohya_ss/blob/master/setup.bat#L12
to point to your python3.10.exe or whatever.
