### ISSUE TITLE
ValueError:no metadata   F:/Aimage/trainjason/meta_lat.json

### ISSUE THREAD

**Issue by yohancehu** [bmaltais/kohya_ss#664]
I'm trying to finetune but face this error. 
![a8e3f4ba5a1fafe21988fb4d4a2323e](https://user-images.githubusercontent.com/89084968/234235845-81d2b412-cc4b-4523-a56d-27ed93081937.png)

**Comment by FurkanGozukara** [comment]
we are trying this and same error with fine tuning

lora training working tested

@bmaltais

**Comment by lendrick** [comment]
I only dabble in python, so this probably isn't the correct way to fix this, but it works:

At the top of ./finetune/merge_captions_to_metadata.py and ./finetune/prepare_buckets_latents.py, add:

```
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
```

And then remove any "import.os" and "import sys" that occur later.  Those scripts are failing because the library path doesn't seem to be set correctly.

**Comment by hypervoxel** [comment]
I am getting this same error, even though the meta_lat.json file is in the correct location

**Comment by bmaltais** [comment]
The same code is actually used for both dreambooth and fine-tune. The fine tune meta caption prep is a real pain. You can use Dreambooth along with a dataset toml if you need more control over dataset parameters.

**Comment by hypervoxel** [comment]
> The same code is actually used for both dreambooth and fine-tune. The fine tune meta caption prep is a real pain. You can use Dreambooth along with a dataset toml if you need more control over dataset parameters.

I have Dreambooth running ok and have created checkpoints.
The issue seems to be at one of the last steps after the metadata files have been created. It tries to load them and fails

**Comment by hypervoxel** [comment]
@bmaltais I might have found the issue! In the config_finetune.toml that is written out. In line 12,  The path to the meta_lat.json has an extra "/" before the filepath and I think this is creating the metadata missing error. See here....
Any simple fix I can use on my end to fix this?

in_json = "/D:/Stable_Diffusion/kohya_ss/Training/SDXL_Finetuning/metadata/meta_lat.json"

**Comment by hypervoxel** [comment]
> The same code is actually used for both dreambooth and fine-tune. The fine tune meta caption prep is a real pain. You can use Dreambooth along with a dataset toml if you need more control over dataset parameters.

@bmaltais I might have found the issue! In the config_finetune.toml that is written out. In line 12, The path to the meta_lat.json has an extra "/" before the filepath and I think this is creating the metadata missing error. See here....
Any simple fix I can use on my end to fix this?

in_json = "/D:/Stable_Diffusion/kohya_ss/Training/SDXL_Finetuning/metadata/meta_lat.json"

**Comment by bmaltais** [comment]
I just did a quick test and the issue might be that you have an extra / in front of the train dir name? Mine looked like that and the in_json was fine:

![image](https://github.com/user-attachments/assets/3780fbaa-47d5-484b-85a8-3f296214419b)

**Comment by hypervoxel** [comment]
> I just did a quick test and the issue might be that you have an extra / in front of the train dir name? Mine looked like that and the in_json was fine:
> 
> ![image](https://private-user-images.githubusercontent.com/7474674/363346471-3780fbaa-47d5-484b-85a8-3f296214419b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTYzOTQsIm5iZiI6MTcyNTA1NjA5NCwicGF0aCI6Ii83NDc0Njc0LzM2MzM0NjQ3MS0zNzgwZmJhYS00N2Q1LTQ4NGItODVhOC0zZjI5NjIxNDQxOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMjIxNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA4NGM3ZjA3YjFhNzc2MGE3NGYxOTc5MmRiZTRlZmQxMjI3MzU3ZTI3YmNjZjZkOTBiYTYxYjVkODAxZjI3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B4DOfEYxt5wvG_Xd9BMgdIETfWD1TFfKmj3C3zmCw9k)

I actually didn't have that filled out (it was blank). Is this for the entire training directory (I thought it was just config files)? I will put a path in here and try again.

**Comment by hypervoxel** [comment]
> I just did a quick test and the issue might be that you have an extra / in front of the train dir name? Mine looked like that and the in_json was fine:
> 
> ![image](https://private-user-images.githubusercontent.com/7474674/363346471-3780fbaa-47d5-484b-85a8-3f296214419b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTYzOTQsIm5iZiI6MTcyNTA1NjA5NCwicGF0aCI6Ii83NDc0Njc0LzM2MzM0NjQ3MS0zNzgwZmJhYS00N2Q1LTQ4NGItODVhOC0zZjI5NjIxNDQxOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMjIxNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTA4NGM3ZjA3YjFhNzc2MGE3NGYxOTc5MmRiZTRlZmQxMjI3MzU3ZTI3YmNjZjZkOTBiYTYxYjVkODAxZjI3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B4DOfEYxt5wvG_Xd9BMgdIETfWD1TFfKmj3C3zmCw9k)

I added a path in config directory and still got an error. It seems to add that path to the others incorrectly:

ValueError: no metadata / メタデータファイルがありません: D:/Stable_Diffusion/kohya_ss/Training/SDXL_Finetuning/D:/Stable_Diffusion/kohya_ss/Training/SDXL_Finetuning/metadata/meta_lat.json

**Comment by bmaltais** [comment]
Darn... it looks like the finetuning code is broken. I'll talk to Kohya about what to do with the meta caption because, honestly, the finetuning code is basically the Dreambooth code. Both will give the same result, but the finetune syntax and steps are a headache.

It is unclear if there are any benefits in keeping both tabs alive since dreambooth is much easier to use.

Also, I never finetune... hence why I never get those errors ;-)

**Comment by hypervoxel** [comment]
I think I fixed it. I then changed the metadata path to metadata/meta_cap.json and it's working!! (But got another error but I think I can fix it)

**Comment by hypervoxel** [comment]
@bmaltais It seems to be running! Thanks for your help! I though this was Kohya github? How some you've never run finetuning? What is the difference between finetuning and Dreambooth? I had heard that finetuning is newer / better?

**Comment by bmaltais** [comment]
In the kohya_ss sd-scripts both dreambooth and finetuning are using the same flux_train.py code. At this point finetuning and dreambooth are just using different parameters to load the images dataset... finetuning used to be different than dreambooth but kohya said they were essentially doing the exact same and just unified the code.
