### ISSUE TITLE
Generation error with Lora (AdamW or Adafactor) but Lion is OK - Mac Silicon M1

### ISSUE THREAD

**Issue by wml-299** [bmaltais/kohya_ss#674]
Hi, I have recently started using Kohya_ss with Mac Silicon M1, and find these issue pages very helpful and informative. 
I hope someone can give me advice on my error.

I get an image generation error with my own Lora, the error occurs when Lora's Optimizer is AdamW or Adafactor, and the generation succeeds when Optimizer is Lion.

The error log is as follows.

> modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.

In addition to the WebUI, I tried Lora with an application (Draw Things) and got the same error.
I changed some settings and the difference between successful and error generation is as follows.
For some reason, even AdamW, generation succeeded when the number of steps was small.

**success**--------------------------------------------------

- AdamW - 3files 2repeat 2epoch
- AdamW - 3files 10repeat 3epoch
- AdamW - 24files 1repeat 3epoch
- Lion      - 10files 2repeat 5epoch
- Lion      - 10files 10repeat 5epoch
- Lion      - 24files 31repeat 2epoch

**error**------------------------------------------------------

- AdamW - 10files 2repeat 5epoch
- AdamW -  3files 30repeat 10epoch
- AdamW -  24files 3repeat 2epoch
- Adafactor - 24files 3repeat 2epoch
- DAdaptation - 24files 3repeat 2epoch
- SGDNesterov - 24files 3repeat 2epoch

-------------------------------------------------------------

How can I make a Lora that can be used properly in AdamW with a large number of steps?

**Comment by PaperOrb** [comment]
Did you ever figure this out? Suffering from this myself currently.

**Comment by wml-299** [comment]
Unfortunately, no.
I have tried and researched many things, but have not been able to solve the problem due to the lack of information.

Are you also using Apple Silicon (M1 or M2)?
