### ISSUE TITLE
Install Stopped

### ISSUE THREAD

**Issue by XarHD** [bmaltais/kohya_ss#675]
I have followed the instructions to install Kohya_SS GUI in my Windows 11 machine, and everything is fine until the installation script gives me this message: 

In which compute environment are you running?
Please select a choice using the arrow or number keys, and selecting with enter
 * This machine
    AWS (Amazon SageMaker)

The problem is that if I use the arrows, I can move the cursor, but not the selection asterisk. If I hit Enter with "This machine" selected, or if I press number 1 (which I assume should be the same thing), the script just... does nothing. Nothing more runs, and no command prompt appears (so I cannot do anything else afterwards). The cursor remains and I can even type in the shell, but since it's not a command prompt, nothing happens. 

Not sure if I'm doing something wrong - I followed all the instructions and installed the appropriate dependencies. Was I supposed to select torch 2.0.0 instead of 1.12?

Any help would be welcome - thank you!

**Comment by codTango** [comment]
I just experienced the same issue, running the cmd in Git Bash on windows 10.
