### ISSUE TITLE
Regulation images, best resolution

### ISSUE THREAD

**Issue by jonwong666** [bmaltais/kohya_ss#677]
Hi There, 

- is it possible to use non square 512x512 images for regulization image sets? 
- is it better to have a mix of different image ratios?

I've been finding training art style Lora works better when using reg images, just trying to find the best workflow.

thank you

**Comment by johnciavarella** [comment]
I've found best results to use 512,512 images.

**Comment by jonwong666** [comment]
ok thanks, the problem with square ratio is the terrible cropping, uneven with negatives.
