### ISSUE TITLE
UserWarning: TypedStorage is deprecated

### ISSUE THREAD

**Issue by sashaok123** [bmaltais/kohya_ss#678]
Dear @bmaltais,

According to a warning message I recently received, the 'TypedStorage' class in PyTorch is being deprecated and will be removed in the future. It is suggested to use the 'untyped_storage()' method instead of 'storage()' for accessing storage classes directly. If your code uses storage classes directly, it would be beneficial to adjust it according to these new guidelines to avoid potential issues in future versions of PyTorch.
![image](https://user-images.githubusercontent.com/27728380/235189617-2022f7ce-549e-4119-8bc3-1710aaf6dffd.png)

**Comment by bmaltais** [comment]
Yeah... not much I can do about this warning. Hopefully when xformers is upgraded they will update their code so the warning is not shown anymore.
