### ISSUE TITLE
Why "python -m venv --system-site-packages venv"

### ISSUE THREAD

**Issue by NaughtDZ** [bmaltais/kohya_ss#68]
If virtualenv to have access to my systems site-packages,other already  installed torchvision,safetenson and other dependent will cuse multiple versions conflict.
Can I use "python -m venv  venv" To get a cleaner environment and avoid running the following commands?
cp .\bitsandbytes_windows\*.dll .\venv\Lib\site-packages\bitsandbytes\
cp .\bitsandbytes_windows\cextension.py .\venv\Lib\site-packages\bitsandbytes\cextension.py
cp .\bitsandbytes_windows\main.py .\venv\Lib\site-packages\bitsandbytes\cuda_setup\main.py

**Comment by bmaltais** [comment]
I have updated the readme in the latest release and removed this annoying parameter. Thanks for reporting.
