### ISSUE TITLE
raise ValueError(err. format(mode="fp16", requirement="a GPU"))

### ISSUE THREAD

**Issue by mikumikuEgg** [bmaltais/kohya_ss#691]
System Information:
System: Windows, Release: 10, Version: 10.0.19045, Machine: AMD64, Processor: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD

Python Information:
Version: 3.10.10, Implementation: CPython, Compiler: MSC v.1929 64 bit (AMD64)

Virtual Environment Information:
Path: F:\Lora Tyaining\kohya_ss\venv

GPU Information:
Name: NVIDIA GeForce RTX 4090, VRAM: 24564 MiB

Validating that requirements are satisfied.
All requirements satisfied.
Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Folder 30_ModelMIX: 24 images found
Folder 30_ModelMIX: 720 steps
max_train_steps = 720
stop_text_encoder_training = 0
lr_warmup_steps = 72
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="F:/Stable Diffusion-WebUI/sd-webui-aki-v4/models/Stable-diffusion/Human/majicmixRealistic_v4.safetensors" --train_data_dir="G:/Lora Database/Model Tyaining_01/image" --resolution=512,768 --output_dir="G:/Lora Database/Model Tyaining_01/model" --logging_dir="G:/Lora Database/Model Tyaining_01/log" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=8 --output_name="ModelMIX" --lr_scheduler_num_cycles="1" --learning_rate="0.0001" --lr_scheduler="cosine" --lr_warmup_steps="72" --train_batch_size="1" --max_train_steps="720" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW8bit" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale  --sample_sampler=euler_a --sample_prompts="G:/Lora Database/Model Tyaining_01/model\sample\prompt.txt" --sample_every_n_steps="20"
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100%|██████████████████████████████████████████| 961k/961k [00:00<00:00, 1.71MB/s]F:\Lora Tyaining\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Admin\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Downloading (…)olve/main/merges.txt: 100%|███████████████████████████████████████████| 525k/525k [00:00<00:00, 925kB/s]Downloading (…)cial_tokens_map.json: 100%|█████████████████████████████████████████████| 389/389 [00:00<00:00, 430kB/s]Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████| 905/905 [00:00<00:00, 977kB/s]Use DreamBooth method.
prepare images.
found directory G:\Lora Database\Model Tyaining_01\image\30_ModelMIX contains 24 image files
720 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 768)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "G:\Lora Database\Model Tyaining_01\image\30_ModelMIX"
    image_count: 24
    num_repeats: 30
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: ModelMIX
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 24/24 [00:00<00:00, 1201.86it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 768), count: 720
mean ar error (without repeats): 0.00030815158674372956
prepare accelerator
Traceback (most recent call last):
  File "F:\Lora Tyaining\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "F:\Lora Tyaining\kohya_ss\train_network.py", line 140, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "F:\Lora Tyaining\kohya_ss\library\train_util.py", line 2742, in prepare_accelerator
    accelerator = Accelerator(
  File "F:\Lora Tyaining\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Lora Tyaining\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\Lora Tyaining\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "F:\Lora Tyaining\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "F:\Lora Tyaining\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\Lora Tyaining\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=F:/Stable Diffusion-WebUI/sd-webui-aki-v4/models/Stable-diffusion/Human/majicmixRealistic_v4.safetensors', '--train_data_dir=G:/Lora Database/Model Tyaining_01/image', '--resolution=512,768', '--output_dir=G:/Lora Database/Model Tyaining_01/model', '--logging_dir=G:/Lora Database/Model Tyaining_01/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=ModelMIX', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=72', '--train_batch_size=1', '--max_train_steps=720', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--sample_sampler=euler_a', '--sample_prompts=G:/Lora Database/Model Tyaining_01/model\\sample\\prompt.txt', '--sample_every_n_steps=20']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Do you have more than one GPU in your system? I wonder if it is picking the wrong one and fail.
