### ISSUE TITLE
lr only unavailable

### ISSUE THREAD

**Issue by kakaruYH03** [bmaltais/kohya_ss#692]
<img width="280" alt="스크린샷 2023-05-01 174344" src="https://user-images.githubusercontent.com/54255373/235430740-5d19d954-28f8-4440-bfbb-1128a40d6c8f.png">

<img width="552" alt="스크린샷 2023-05-01 173644" src="https://user-images.githubusercontent.com/54255373/235430731-500666f3-2cd1-461d-94fe-9895af3825fc.png">

unet lr/text encoder
if left blank
I know that only LR is recognized and learned.

However, if you leave unet lr and text encoder blank, learning will not proceed.

**Comment by bmaltais** [comment]
Should be fixed in latest release
