### ISSUE TITLE
Kohyass installation failed

### ISSUE THREAD

**Issue by HMjemmyFAN** [bmaltais/kohya_ss#693]
Before explaining the issue, please forgive me for using a translator to communicate with you. In some places, there may be words that are not clear. I am a computer novice and I am located in China. As you know, I cannot connect to GitHub well on the Chinese network. I failed to download using the git command in the power shell, So I directly copied the file and ran setup.bat, prompting me to install torch-2.0.0+cu118-cp311-cp311- failed. Then, after downloading some files, the program exited. I downloaded this file at a friend's house, which is approximately 2.6GB, and then copied it to the root directory of kohyass. After using pip install torch-2.0.0+cu118-cp311-cp311-win_ The amd64.whl command was installed, but after the installation was completed, the GUI still flickered and couldn't run. I also tried to run upgrade, but the GUI still couldn't run. I want to know how to solve it, thank you!

**Comment by bmaltais** [comment]
Your best bet is to delete the full kohya_ss folder, clone it again from github and run setup.bat again. Also, make sure you hape properly installed python 3.10.9+.

**Comment by jstayco** [comment]
"the GUI still flickered and couldn't run." 娜不是Torch. Torch用于训练。不适用于GUI. Do you have an old web browser? 试试Firefox或Edge。
