### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by CGMikeG** [bmaltais/kohya_ss#695]
Hi,

Hopefully, you can see the image. But I got a message from McAfee that one of the file have a virus. Are you able to check if this is correct?

![KohyaVirus](https://user-images.githubusercontent.com/65123386/235443232-ef0bbb06-fa14-4400-b699-8d8b49257dd6.JPG)

**Comment by bmaltais** [comment]
No idea. Probably a false positive caused by the gradio library. Windows has not complained on my end. What AV are you using?

**Comment by bmaltais** [comment]
The latest release use a newer version of the gradio module. Hope that one does not trigger the false positive.

**Comment by johnciavarella** [comment]
I got the same caught by Avast

**Comment by bmaltais** [comment]
Must be an Avast bug

**Comment by cooperdk** [comment]
Avast, like Windows Defender and others, make a bit too much use of AI in recognizing malware.
This is one of the cases.

Set an exclusion to the kohya directory in your antivirus or choose something better. (BTW Windows Defender is excellent and does NOT complain about anything in this project).
