### ISSUE TITLE
Suggestion - /log and /model auto-creation?

### ISSUE THREAD

**Issue by deeplearner5** [bmaltais/kohya_ss#7]
Just running for first time, and got a "FileNotFoundError: [Errno 2] No such file or directory:" error on last.yaml, and worked out /log and /model subdirectories weren't auto-created when I set up via Utilities.

I know it's not technically part of copying data to the relevant directories, and will now know to make sure they exist in any new models I finetune, but might it be a useful QOL addition to auto-create those directories as part of the "Copy Info to Directories Tab" action?

Thanks
Al

**Comment by bmaltais** [comment]
I agree... I will check if they exist and create them if they don't.

**Comment by bmaltais** [comment]
Fixed via: https://github.com/bmaltais/kohya_ss/pull/11
