### ISSUE TITLE
JSON config load does not load the "save trained model as" setting properly

### ISSUE THREAD

**Issue by alchemzy** [bmaltais/kohya_ss#71]
Save appears to update the JSON config, but it does not load the value which remains as "same as parent"

**Comment by alchemzy** [comment]
git diff master
diff --git a/lora_gui.py b/lora_gui.py
index 2a7421a..9645216 100644
--- a/lora_gui.py
+++ b/lora_gui.py
@@ -158,7 +158,7 @@ def open_configuration(
     stop_text_encoder_training,
     use_8bit_adam,
     xformers,
-    save_model_as_dropdown,
+    save_model_as,
     shuffle_caption,
     save_state,
     resume

**Comment by bmaltais** [comment]
Good catch. I will push a fix for it. If you "git checkout dev ; git pull" you will get the fix. I will release it in the master branch once I have a few of those lined up... but for now you can use the dev branch code to make use of it.

Thank you for reporting this!
