### ISSUE TITLE
Merge LyCORIS & Extract DyLORA Tab are Gone??

### ISSUE THREAD

**Issue by YKefasu** [bmaltais/kohya_ss#712]
Merge LyCORIS & Extract DyLORA Tab are missing in the new update 2023/05/01 (v21.5.7) ?? @bmaltais

**Comment by bmaltais** [comment]
Really? I will check why

**Comment by bmaltais** [comment]
I just checked and the options are still there:

![image](https://user-images.githubusercontent.com/7474674/236341012-3169031f-d0a6-4afc-944f-5e93965179eb.png)

**Comment by YKefasu** [comment]
Browser Cache prob, sorry for bothering
