### ISSUE TITLE
Error runpy.py", line 196, in _run_module_as_main after error "site-packages\accelerate\commands\launch.py", line 579, in simple_launcher"

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [bmaltais/kohya_ss#723]
Hello, I am running the latest build on torch2 with cudnn.

Organized all files + text in the 100_Supi directory. Set up everything like recommended in the youtube tutorial that is linked in this repo. And then it throws me this error when I try to start the LORA training. Already looked around on git and reddit but all I could find was for a lot older versions and even there they weren't quite sure what the issue was. 
Already tried deleting and recloning + re-setup-ing but always same result, also tested variations between adam8bit which seems to give other people issues, changed to lion8bit, but always keep getting errors, so I believe it might be a setting that I have overlooked. 

prepare tokenizer
Use DreamBooth method.
prepare images.
found directory D:\ZZ Lora Taining\100_Supi contains 13 image files
1300 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "D:\ZZ Lora Taining\100_Supi"
    image_count: 13
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Supi
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 501.35it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (384, 576), count: 1000
bucket 1: resolution (576, 384), count: 300
mean ar error (without repeats): 0.0
prepare accelerator
D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint
D:\kohya_ss\venv\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
D:\kohya_ss\venv\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
D:\kohya_ss\venv\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Replace CrossAttention.forward to use xformers
[Dataset 0]
caching latents.
  0%|                                                                                                                       | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 773, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 157, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "D:\kohya_ss\library\train_util.py", line 1399, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "D:\kohya_ss\library\train_util.py", line 812, in cache_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 566, in encode
    h = self.encoder(x)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\charl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/SD Repo/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors', '--train_data_dir=D:\\ZZ Lora Taining', '--resolution=512,512', '--output_dir=D:/VLADautomatic/models/embeddings', '--logging_dir=', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=SupiTest', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--lr_warmup_steps=-6', '--train_batch_size=2', '--max_train_steps=650', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.08']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Was it working bofore on torch1?

**Comment by TheOnlyHolyMoly** [comment]
I did not have it before. I tried now running it on torch 1, same error.

**Comment by bmaltais** [comment]
Have you tried going back to the previous release and see if it is fixed? Might be related to code update done by Kohya in his last update.

**Comment by TheOnlyHolyMoly** [comment]
Just rolled back to 21.5.2 as a friend of mine reported that to work very well for him. It caused issues as I only had cuda 12 while asking for cuda 11, so now I parallel installed cuda 11.8. So it's coming past this point now, but again stops with some error. Looking at it the error SEEMS (imho) to always happen when the optimizer is getting called, it there a way calling it without optimizer so I can test if I can get it to work at all?

create LoRA network. base dim (rank): 8, alpha: 1.0
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
prepare optimizer, data loader etc.
use Lion optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 1300
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 1300
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 1300
steps:   0%|                                                                                                     | 0/1300 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 760, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 591, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya_ss\library\train_util.py", line 1792, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "D:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "D:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 299, in _memory_efficient_attention
    return _fMHA.apply(
  File "D:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 41, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "D:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 327, in _memory_efficient_attention_forward_requires_grad
    out = op.apply(inp, needs_gradient=True)
  File "D:\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "D:\kohya_ss\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 13 argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor? cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)
steps:   0%|                                                                                                     | 0/1300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\charl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\charl\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=D:/VLADautomatic/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors', '--train_data_dir=D:/ZZ Lora Taining/', '--resolution=512,512', '--output_dir=D:/VLADautomatic/models/embeddings', '--logging_dir=', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=130', '--train_batch_size=1', '--max_train_steps=1300', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=Lion', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
This sound like something related to your specific setup. There are many variable and it is almost impossible to pinpoint what the issue is without having access to the exact same system.

You always need an optimizer... Try selecting AdamW as your optimizer. It will remove possible bitsandbytes issues with 8bit optimizers

**Comment by TheOnlyHolyMoly** [comment]
Thanks, AdamW also is not working either. I'm putting in some debugging lines now to see if I can help narrow down the problem some more. Will report here if I spot anything

**Comment by bmaltais** [comment]
I suggest you delete the full kohya_ss folder, git clone a fresh copy and re-run setup.bat. chose to install torch 2

**Comment by TheOnlyHolyMoly** [comment]
SOLVED. had already recloned repo but then with torch 1 and had not recloned it with torch 2 after providing CUDA 11.8 on top of CUDA 12.
In training now, thank you so MUCH!!!

**Comment by Deph1** [comment]
> SOLVED. had already recloned repo but then with torch 1 and had not recloned it with torch 2 after providing CUDA 11.8 on top of CUDA 12. In training now, thank you so MUCH!!!

I'm sorry to pester you, I'm having the same problem and I'm unsure of what the fix is? I haven't recloned the directory though, although I have done about 3 times and still the same issue.

**Comment by TheOnlyHolyMoly** [comment]
> > SOLVED. had already recloned repo but then with torch 1 and had not recloned it with torch 2 after providing CUDA 11.8 on top of CUDA 12. In training now, thank you so MUCH!!!
> 
> I'm sorry to pester you, I'm having the same problem and I'm unsure of what the fix is? I haven't recloned the directory though, although I have done about 3 times and still the same issue.

Can you check on C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA if you find v11.x subfolder? If not then go and pull 11.8 from https://developer.nvidia.com/cuda-toolkit-archive. Also make sure you have the VS tools properly installed (see repo requirements). Then try deleting and recloning the repo and run setup with torch2 option (first question: dont uninstall, second question torch2, and then for the speedoptimizers such as deepspeed etc, all NO) > the idea is getting it to run in first place, once you got that managed you can play with options.
