### ISSUE TITLE
GPU not recognized on Apple Silicon Macs

### ISSUE THREAD

**Issue by EraserCN** [bmaltais/kohya_ss#725]
I ran into "ValueError: fp16 mixed precision requires a GPU" error while running Dreambooth LoRA on my M1 Pro powered MacBook Pro, and failed to train any models.

**Comment by EraserCN** [comment]
<img width="1392" alt="2023-05-06 11 05 20" src="https://user-images.githubusercontent.com/79615365/236595398-ab793e6a-7fc6-4f54-9310-414a4cfaf672.png">

**Comment by bmaltais** [comment]
Mac support is very immature.somw users have contributed code but it is far from great at the moment. Hopefully more people with mac will work with Kohya to add better MacOS support

**Comment by jstayco** [comment]
New installer handles this, but you should answered "This machine", "MPS", and no for all other options during accelerate config screen.

**Comment by andupotorac** [comment]
> 

And if you don't see that option, it means you're using a version of accelerate that does it by default (see their github with the issues by looking for MPS). So you can either edit that config file manually, or change the code that is using it directly.

See this
https://planaria.page/blog/?p=671 (translate to English)

Might need this stuff:
`conda install -n base conda=23.1.0`

Don’t forget to activate before config:
`. ./venv/bin/activate`

Then
`accelerate config`

**Comment by rovo79** [comment]
I have this same issue. When I ran ./setup.sh it didn't ask me any questions and then just made a copy of /default_config.yaml for me. Is there anything I can change in there to indicate MPS?

This is my current default_config.yaml

command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: 'NO'
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

**Comment by andupotorac** [comment]
Feel free to use my settings:
https://rentry.org/xbm3dz

**Comment by andupotorac** [comment]
> I have this same issue. When I ran ./setup.sh it didn't ask me any questions and then just made a copy of /default_config.yaml for me. Is there anything I can change in there to indicate MPS?
> 
> This is my current default_config.yaml
> 
> command_file: null commands: null compute_environment: LOCAL_MACHINE deepspeed_config: {} distributed_type: 'NO' downcast_bf16: 'no' dynamo_backend: 'NO' fsdp_config: {} gpu_ids: all machine_rank: 0 main_process_ip: null main_process_port: null main_training_function: main megatron_lm_config: {} mixed_precision: 'no' num_machines: 1 num_processes: 1 rdzv_backend: static same_network: true tpu_name: null tpu_zone: null use_cpu: false

Feel free to use my settings:
https://rentry.org/xbm3dz

**Comment by organicmind-pixel** [comment]
> > I have this same issue. When I ran ./setup.sh it didn't ask me any questions and then just made a copy of /default_config.yaml for me. Is there anything I can change in there to indicate MPS?
> > This is my current default_config.yaml
> > command_file: null commands: null compute_environment: LOCAL_MACHINE deepspeed_config: {} distributed_type: 'NO' downcast_bf16: 'no' dynamo_backend: 'NO' fsdp_config: {} gpu_ids: all machine_rank: 0 main_process_ip: null main_process_port: null main_training_function: main megatron_lm_config: {} mixed_precision: 'no' num_machines: 1 num_processes: 1 rdzv_backend: static same_network: true tpu_name: null tpu_zone: null use_cpu: false
> 
> Feel free to use my settings: https://rentry.org/xbm3dz

could U also share the basic setting for training LORA ?    LoraBasicSettings.json

**Comment by andupotorac** [comment]
> 

Sure. I tried several settings, but the two that give the best results are these. Note I train LORAs on A1111, mainly for styles. See my Twitter @andupotorac for some style examples. For clothing and faces I use embeddings, and I train those on InvokeAI.

Option 1: https://rentry.org/fvw69
Option 2: https://rentry.org/kigps

**Comment by organicmind-pixel** [comment]
> > 
> 
> Sure. I tried several settings, but the two that give the best results are these. Note I train LORAs on A1111, mainly for styles. See my Twitter @andupotorac for some style examples. For clothing and faces I use embeddings, and I train those on InvokeAI.
> 
> Option 1: https://rentry.org/fvw69 Option 2: https://rentry.org/kigps
> 
> Make sure the number you set in the folder * epochs is greater than 100. Example for 2 epochs:
> 
> <img alt="Screenshot 2023-07-02 at 18 32 51" width="742" src="https://user-images.githubusercontent.com/3269738/250370795-d07411fd-0a81-4672-914a-27fa167f2281.png">

Thank U

**Comment by andupotorac** [comment]
> > > 
> > 
> > 
> > Sure. I tried several settings, but the two that give the best results are these. Note I train LORAs on A1111, mainly for styles. See my Twitter @andupotorac for some style examples. For clothing and faces I use embeddings, and I train those on InvokeAI.
> > Option 1: https://rentry.org/fvw69 Option 2: https://rentry.org/kigps
> > Make sure the number you set in the folder * epochs is greater than 100. Example for 2 epochs:
> > <img alt="Screenshot 2023-07-02 at 18 32 51" width="742" src="https://user-images.githubusercontent.com/3269738/250370795-d07411fd-0a81-4672-914a-27fa167f2281.png">
> 
> Thank U

No problem. Note I removed one of the links and kept the one with 128 for network dim. I recently tested the other one on a new LORA style and I decided it's just not as good. So go with the 128 settings.
