### ISSUE TITLE
tpu_env

### ISSUE THREAD

**Issue by AbramovS1** [bmaltais/kohya_ss#726]
How to fix it ?
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\acc │
│ elerate_cli.py:45 in main                                                                        │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\lau │
│ nch.py:1000 in launch_command                                                                    │
│                                                                                                  │
│    997 │   warned = []                                                                           │
│    998 │   # Get the default from the config file.                                               │
│    999 │   if args.config_file is not None or os.path.isfile(default_config_file) and not args.  │
│ ❱ 1000 │   │   defaults = load_config_from_file(args.config_file)                                │
│   1001 │   │   if (                                                                              │
│   1002 │   │   │   not args.multi_gpu                                                            │
│   1003 │   │   │   and not args.tpu                                                              │
│                                                                                                  │
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\con │
│ fig\config_args.py:64 in load_config_from_file                                                   │
│                                                                                                  │
│    61 │   │   │   │   config_class = ClusterConfig                                               │
│    62 │   │   │   else:                                                                          │
│    63 │   │   │   │   config_class = SageMakerConfig                                             │
│ ❱  64 │   │   │   return config_class.from_yaml_file(yaml_file=config_file)                      │
│    65                                                                                            │
│    66                                                                                            │
│    67 @dataclass                                                                                 │
│                                                                                                  │
│ C:\Users\mrjek\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\con │
│ fig\config_args.py:122 in from_yaml_file                                                         │
│                                                                                                  │
│   119 │   │   if "dynamo_backend" not in config_dict:                                            │
│   120 │   │   │   config_dict["dynamo_backend"] = DynamoBackend.NO                               │
│   121 │   │                                                                                      │
│ ❱ 122 │   │   return cls(**config_dict)                                                          │
│   123 │                                                                                          │
│   124 │   def to_yaml_file(self, yaml_file):                                                     │
│   125 │   │   with open(yaml_file, "w", encoding="utf-8") as f:                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'tpu_env'

**Comment by bmaltais** [comment]
Have you tried activating the bench before running the GUI.

Otherwise, delete the complete kohya_gui folder, clone fresh and redo the setup.bat

**Comment by AbramovS1** [comment]
> Have you tried activating the bench before running the GUI.
> 
> Otherwise, delete the complete kohya_gui folder, clone fresh and redo the setup.bat

There are no problems now! Everything is super !

**Comment by edgartaor** [comment]
> There are no problems now! Everything is super !

How did you fix it? Fresh install?
