### ISSUE TITLE
Installation Error -  couldn't open temporary file ./sedvaigod: Permission denied

### ISSUE THREAD

**Issue by jannichorst** [bmaltais/kohya_ss#728]
While trying to install I encounter the following error. Couldn't find a solution to the issue yet. 

` => ERROR [13/13] RUN sed -i 's/import library.huggingface_util/# import library.huggingface_util/g' train_network.py &&     sed -i 's/import library.huggingface_util/# import   0.3s`

`> [13/13] RUN sed -i 's/import library.huggingface_util/# import library.huggingface_util/g' train_network.py &&     sed -i 's/import library.huggingface_util/# import library.huggingface_util/g' library/train_util.py:
#0 0.303 sed: couldn't open temporary file ./sedvaigod: Permission denied`

`failed to solve: process "/bin/sh -c sed -i 's/import library.huggingface_util/# import library.huggingface_util/g' train_network.py &&     sed -i 's/import library.huggingface_util/# import library.huggingface_util/g' library/train_util.py" did not complete successfully: exit code: 4`

Any idea what could be the issue here?

System: Win 11

**Comment by bmaltais** [comment]
Are you running the `.\setup.bat` script?
