### ISSUE TITLE
Linux Deploy Guide?

### ISSUE THREAD

**Issue by narugo1992** [bmaltais/kohya_ss#73]

**Comment by martinobettucci** [comment]
Currently porting it (still WIP): https://github.com/P2Enjoy/kohya_ss

**Comment by narugo1992** [comment]
Ok, I may contribute code in the future as well.

**Comment by martinobettucci** [comment]
I've created the repo tandem of the linux version here: it's a docker https://github.com/P2Enjoy/kohya_ss-docker

**Comment by bmaltais** [comment]
Awesome, I will add the info to the readme to point users to it.

**Comment by runner22k** [comment]
Wow! I want Linux version. As it is based on Python, I tried to run it in Linux. But it is unable to find files. I am not a developer. But if I get to see a reference code or given a specific python script to convert to Linux. Then I can try to help with correcting and testing.

**Comment by developer90210brr** [comment]
would be nice if someone can make a notebook for it on paperspace as i only have a 1070 and i dont have enough vram (8gb) even as much optimized as i can get still run out on lora training so would be super nice to be able to use a quadro rtx5000 on paperspace or something

**Comment by martinobettucci** [comment]
Hello everybody, we added more instructions and we updated to the last updates as they all passed our quality control.
Feel free to ask for any help in the issues panel of the linux repository.

**Comment by martinobettucci** [comment]
Linux docker have been updated with latest changes

**Comment by devNegative-asm** [comment]
I just ran everything in ubuntu and it requires very little changes to get it to work properly. There's just 2 lines of code needed
```
-    run_cmd = f'accelerate launch --num_cpu_threads_per_process={num_cpu_threads_per_process} "train_network.py"'
+    run_cmd = f'accelerate launch --num_cpu_threads_per_process={num_cpu_threads_per_process} train_network.py'
```
```
-    subprocess.run(run_cmd)
+    subprocess.run(run_cmd,shell=True)
```
and a new file gui.sh
```
#!/bin/bash
source venv/bin/activate
python kohya_gui.py $@
```

In the setup, skip copying bitsandbytes files and replacing windows commands with the linux counterpart can get it working.
If you haven't already `sudo apt install python3-tk`

**Comment by devNegative-asm** [comment]
I incorporated everything I mentioned into a script here https://github.com/bmaltais/kohya_ss/pull/288
Rather than using that commit as-is, I recommend taking that, removing the sed commands, and merging it together with https://github.com/bmaltais/kohya_ss/pull/272
