### ISSUE TITLE
model is not found as a file or in Hugging Face

### ISSUE THREAD

**Issue by JoeanAmier** [bmaltais/kohya_ss#747]
model is not found as a file or in Hugging Face, perhaps file name is wrong? / 指定したモデル名のファイル、またはHugging Faceのモデルが見つかりません。ファイル名が誤っているかもしれません: runwayml/stable-diffusion-v1-5
How can I solve it? Can I manually download the files and place them in the correct location?

**Comment by LycoPan** [comment]
i had the same ploblem。The first time I ran the training, the system automatically downloaded the model, but it was interrupted due to network problems. After that the same error kept appearing. Even if I delete the entire directory and reinstall it, it won't work.

**Comment by arthurb123** [comment]
I fixed this issue by manually downloading the missing model from an older branch located [here](https://huggingface.co/openai/clip-vit-large-patch14/tree/refs%2Fpr%2F5). After downloading the _model.safetensors_ file, place the file in the folder `kohya_ss\venv\Lib\site-packages\transformers\models\openai`. Make sure to rename the file from _model.safetensors_ to _clip-vit-large-patch14.safetensors_ and you should be good to go.

**Comment by bmaltais** [comment]
I am also experiencing this issue after deleting the cached models from those directories:

```
C:\Users\<username>\.cache\huggingface\hub
C:\Users\<username>\.huggingface
```

Not sure whatis going on... Investigating...

**Comment by bmaltais** [comment]
https://twitter.com/huggingface/status/1655760648926642178

**Comment by bmaltais** [comment]
Look like it is working again now.

**Comment by LycoPan** [comment]
> Look like it is working again now.

This took me spent all night trying to figure this out, so frustrating
