### ISSUE TITLE
Unable to install bitsandbytes ,training failed.

### ISSUE THREAD

**Issue by dayuii** [bmaltais/kohya_ss#750]
Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2): 2
Please choose the version of torch you want to install:
[1] - v1 (torch 1.12.1) (Recommended)
[2] - v2 (torch 2.0.0) (Experimental)
Enter your choice (1 or 2): 2
WARNING: Skipping bitsandbytes as it is not installed.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.0+cu118

**Comment by bmaltais** [comment]
THat warning it telling that bitsandbytes was not installed and it could not uninstall before redoing the setup of thr torch2.0.0 modules. Unless it complain during the installation of bitsandbytes afterward it is all good.
