### ISSUE TITLE
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors

### ISSUE THREAD

**Issue by liuchunyu524** [bmaltais/kohya_ss#758]
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://huggingface.co/openai/clip-vit-large-patch14/resolve/main/model.safetensors

**Comment by Trojaner** [comment]
This error is caused by hugging face, not by kohya_ss gui

**Comment by wyong2017** [comment]
how to resolve?
