### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by 24mlight** [bmaltais/kohya_ss#760]
```
Traceback (most recent call last):
File "/data/7082/venv/lib/python3.8/site-packages/gradio/routes.py", line 399, in run_predict
output = await app.get_blocks().process_api(
File "/data/7082/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1299, in process_api
result = await self.call_function(
File "/data/7082/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1022, in call_function
prediction = await anyio.to_thread.run_sync(
File "/data/7082/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
return await get_asynclib().run_sync_in_worker_thread(
File "/data/7082/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
return await future
File "/data/7082/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
result = context.run(func, *args)
File "/data/7082/library/common_gui.py", line 240, in get_folder_path
root = Tk()
File "/usr/lib/python3.8/tkinter/init.py", line 2270, in init
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

I have tried almost every method, but still can not fix it.......

**Comment by 24mlight** [comment]
解决方案：
sudo apt-get install xvfb # 安装xvfb
# 启动虚拟显示器
Xvfb :99 -screen 0 1024x768x16 &
export DISPLAY=:99
ps aux | grep Xvfb # 查看是否开启xvfb，下图是成功开启xvgb的输出
 
![image](https://github.com/bmaltais/kohya_ss/assets/45850482/dc36470a-4a87-4968-b21c-28370c1f2ffc)

然后看报错，哪个文件报了和tkinter或者Tkinter有关的错，哪个文件就加上：
import os
os.environ['DISPLAY'] = ':99'
（注意，如果有文件的路径在usr下，千万别去主机那里找，而是要去找通过命令行进入docker后的那个usr目录）


You can translate the text above to English, and I wish this solution will help.

**Comment by potatoker** [comment]
> Try starting the gui with --headless as an option... for example:
> 
> `.\gui.sh --headless`

not work for me(remote server ubuntu run kohya, but display on local mac)

**Comment by potatoker** [comment]
> （注意，如果有文件的路径在usr下，千万别去主机那里找，而是要去找通过命令行进入docker后的那个usr目录） 不太熟悉docker,请问这里是什么意思啊，我直接改了本地git仓库的对应报错文件，还是没有解除这个display问题

**Comment by cvv-student** [comment]
> 

我是远程服务器，装完后直接点train model直接没有反应了

**Comment by 24mlight** [comment]
> 

我上面给了指令呀，进入容器后执行我给的指令试试

**Comment by 24mlight** [comment]
> > （注意，如果有文件的路径在usr下，千万别去主机那里找，而是要去找通过命令行进入docker后的那个usr目录）
> 
> 不太熟悉docker,请问这里是什么意思啊，我直接改了本地git仓库的对应报错文件，还是没有解除这个display问题 @24mlight

我上面给了指令呀，进入容器后执行我给的指令试试

**Comment by 24mlight** [comment]
> > 
> 
> 我是远程服务器，装完后直接点train model直接没有反应了
![image](https://github.com/bmaltais/kohya_ss/assets/45850482/cef1f251-1ba6-4315-b0cb-c7798bcd7a6d)
设置了为0.0.0.0了嘛

**Comment by potatoker** [comment]
> os.environ['DISPLAY'] = ':99'

这里是进入container修改文件之后commit然后再执行新的container吗，我这里发现

> Try starting the gui with --headless as an option... for example:
> 
> `.\gui.sh --headless`

I missed the step to re compose build the container, it worked

**Comment by cvv-student** [comment]
> > > 
> > 
> > 
> > 我是远程服务器，装完后直接点train model直接没有反应了
> > ![image](https://user-images.githubusercontent.com/45850482/238235168-cef1f251-1ba6-4315-b0cb-c7798bcd7a6d.png)
> > 设置了为0.0.0.0了嘛

 奇奇怪怪又行了，用的是headless绕过了TK

**Comment by 24mlight** [comment]
> > > > 
> > > 
> > > 
> > > 我是远程服务器，装完后直接点train model直接没有反应了
> > > ![image](https://user-images.githubusercontent.com/45850482/238235168-cef1f251-1ba6-4315-b0cb-c7798bcd7a6d.png)
> > > 设置了为0.0.0.0了嘛
> 
> 奇奇怪怪又行了，用的是headless绕过了TK

哈哈哈那就好

**Comment by ashleykleynhans** [comment]
> Try starting the gui with --headless as an option... for example:
> 
> `.\gui.sh --headless`

This doesn't work for me on linux.  I can access the Kohys_ss GUI perfectly, in my web browser, but as soon as I click the `Train model` button:

```
Traceback (most recent call last):
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
    output = await app.get_blocks().process_api(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/dreambooth_gui.py", line 379, in train_model
    output_message(
  File "/workspace/kohya_ss/library/common_gui.py", line 83, in output_message
    msgbox(msg=msg, title=title)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by Jiangcat8301** [comment]
> > Try starting the gui with --headless as an option... for example:
> > `.\gui.sh --headless`
> 
> This doesn't work for me on Linux. I can access the Kohys_ss GUI perfectly in my web browser, but as soon as I click the `Train model` button:
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/routes.py", line 427, in run_predict
>     output = await app.get_blocks().process_api(
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
>     result = await self.call_function(
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
>     return await future
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
>     result = context.run(func, *args)
>   File "/workspace/kohya_ss/dreambooth_gui.py", line 379, in train_model
>     output_message(
>   File "/workspace/kohya_ss/library/common_gui.py", line 83, in output_message
>     msgbox(msg=msg, title=title)
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
>     return buttonbox(msg=msg,
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
>     bb = ButtonBox(
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
>     self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
>   File "/workspace/kohya_ss/venv/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
>     self.boxRoot = tk.Tk()
>   File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
>     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
> _tkinter.TclError: no display name and no $DISPLAY environment variable
> ```

same here. The GUI shows perfectly without working "file and folder button", but it's not much of a problem copy&paste the paths. However, as I click start training, the tkinter error pops.

Any fix or work arounds yet? Thanks!

**Comment by dcsan** [comment]
this is probably because the example tutorials are for running a local version.
I am trying to get going on runpod, which this tutorial _SHOULD_ help with this, but apparently not.
https://www.youtube.com/watch?v=3uzCNrQao3o&ab_channel=SECourses

like others, after finishing and setting params, the error above still comes up.
the $DISPLAY env var should be of format 
`hostname:D.S`

problem is we don't know the external hostname until the startups script is running. eg when it spits out:
```
17:27:54-114415 INFO     headless: False                                                                                                     
17:27:54-124014 INFO     Load CSS...                                                                                                         
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://d54467195133cxyz123.gradio.live
```

otherwise we could do something like: 
`export DISPLAY=https://d54467195133cxyz123.gradio.live:0.0`

this seems to be a bug in the scripts for running remotely.

**Comment by dcsan** [comment]
@potatoker 
> I missed the step to re compose build the container, it worked

which step is that?

I did try restarting the runpod pod after the install process and going through the whole process again. so it seems repeatable bug.

update this seems to work thanks @24mlight xiexie nin!

```
apt-get install xvfb 
Xvfb :99 -screen 0 1024x768x16 &
export DISPLAY=:99
# check it works
ps aux | grep Xvfb 

# gives result:
root        1163  0.3  0.0 198672 63124 pts/0    S    18:04   0:00 Xvfb :99 -screen 0 1024x768x16
root        1183  0.0  0.0   3840  2028 pts/0    S+   18:04   0:00 grep --color=auto Xvfb
```

then i can start training.

**Comment by kieranxsomer** [comment]
I got this again:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "/opt/conda/lib/python3.10/site-packages/gradio/blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/opt/conda/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/workspace/kohya_ss/library/dreambooth_folder_creation_gui.py", line 52, in dreambooth_folder_preparation
    msgbox('Class prompt missing...')
  File "/opt/conda/lib/python3.10/site-packages/easygui/boxes/derived_boxes.py", line 230, in msgbox
    return buttonbox(msg=msg,
  File "/opt/conda/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 95, in buttonbox
    bb = ButtonBox(
  File "/opt/conda/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 147, in __init__
    self.ui = GUItk(msg, title, choices, images, default_choice, cancel_choice, self.callback_ui)
  File "/opt/conda/lib/python3.10/site-packages/easygui/boxes/button_box.py", line 263, in __init__
    self.boxRoot = tk.Tk()
  File "/opt/conda/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

All i'm doing is setting a training folder lmao.
I can get the UTILITIES to work it's JUST this tab that's a pain XD 

I'll go ask some nerd buddies

**Comment by kieranxsomer** [comment]
<img width="270" alt="Screenshot 2023-06-21 at 19 26 49" src="https://github.com/bmaltais/kohya_ss/assets/58930427/d2fbf735-d8ee-4098-b943-f86214efac91">
Ok forgot to mention it's ONLY THE ONE SECTION i've struggled with,
Last time?
I got it to group the images - but i tink that was the OTHER utilities tab...
it's ONLY the lora section

**Comment by kieranxsomer** [comment]
> > os.environ['DISPLAY'] = ':99'
> 
> 这里是进入container修改文件之后commit然后再执行新的container吗，我这里发现
> 
> > Try starting the gui with --headless as an option... for example:
> > `.\gui.sh --headless`
> 
> I missed the step to re compose build the container, it worked

I think tehy're talking about using docker, where i can't get docker to work

**Comment by kieranxsomer** [comment]
Update: Tried the vast installer, that won't even get to opening the gui - I get "rich' and conda errors on that one.
Using the normal install i get the captioning done, which isn't useful because i'm trying to move off colab LOL 

I'm getting the display error again, and headless didn't work, it messes up the Gui, and like i said i can get tagging to work - largely i've just ad-hoc installed unzip and zipped stuff up and shoved it in a semi private HF repo, and then wget the zip files, unzip thmem et-c that's fine, 

Just it's when i go to "Dataset balancing" or the dataset prep it goes bonkers.

FYI: I also attempted to do the gui-less kohya-ss and that just ... my brain just about exploded because that takes a whole other level of cuda and torch, and just -- wow, XD vast is. great yes -- but i wanted to get off colab for lora training XD

**Comment by kolingv** [comment]
> 解决方案： 为了防止其他问题发生，一定要先进入docker容器并进入venv环境。 apt-get install xvfb //安装xvfb // 启动虚拟显示器 Xvfb :99 -screen 0 1024x768x16 & export DISPLAY=:99 ps aux | grep Xvfb // 查看是否开启xvfb，下图是成功开启xvgb的输出
> 
> ![image](https://user-images.githubusercontent.com/45850482/237272659-dc36470a-4a87-4968-b21c-28370c1f2ffc.png)
> 
> 然后点击webui上的Train model按钮进行测试，看报错，哪个文件报了和tkinter或者Tkinter有关的错，哪个文件就加上： import os os.environ['DISPLAY'] = ':99' （注意，如果有文件的路径在usr下，千万别去主机那里找，而是要去找通过命令行进入docker后的那个usr目录）
> 
> You can translate the text above to English, and I wish this solution will help.

你好，我进入docker后，哪里进入venv环境呀？我跑 ./gui.sh --headless 会报错：
./gui.sh: line 34: /app/venv/bin/activate: No such file or directory

![image](https://github.com/bmaltais/kohya_ss/assets/18081891/c98120a6-3497-467d-b502-796c27ace1bd)

**Comment by mjwyr** [comment]
报这个错还可能是因为你输入的outPutPath,也就是Lora保存路径中,已存在同名lora文件,删除即可
This error may also be due to the outPutPath you entered, which is the Lora save path where a Lora file with the same name already exists. Simply delete it

**Comment by jonahclarsen** [comment]
> 报这个错还可能是因为你输入的outPutPath,也就是Lora保存路径中,已存在同名lora文件,删除即可 This error may also be due to the outPutPath you entered, which is the Lora save path where a Lora file with the same name already exists. Simply delete it

This was it for me (with textual inversion), thanks! There should definitely be some sort of check as to whether the output file already exists, so it can give a human readable error message if it does. I never would've thought of that!
