### ISSUE TITLE
docker compose run --service-ports kohya-ss-gui

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [bmaltais/kohya_ss#763]
Hello again, 

I have a question/iusse around the docker installation, rather a question I guess: 

So I was able to bring docker to life and paddle around wsl and hypervisor
My first issue (which I was able to resolve) was an error in the docker build "failed to fetch anonymous token" > found out docker actually needs an NVIDIA Api key, >> I would suggest adding the requirement of an API key to the Docker Installation Process. 

The second thing (and I am stuck here) is that I worked through "docker compose run --service-ports kohya-ss-gui" ... it is starting up and coming to "Running on local URL:  http://0.0.0.0:7860   To create a public link, set `share=True` in `launch()`."

How do I access this now? Sorry if I am asking a probably obvious thing.

**Comment by TheOnlyHolyMoly** [comment]
Update: Docker App > containers and then be happy to see the link!

Leaving this here for others that might struggle like me newby to bring this up. iusse solved

**Comment by bestbad777** [comment]
When I open link then I try to click any button but is not work like gui web is have some issue, I can't press load config load file

can you help me, 

thank you.
