### ISSUE TITLE
ModuleNotFoundError: No module named 'xformers' on Mac M1

### ISSUE THREAD

**Issue by mikecastrodemaria** [bmaltais/kohya_ss#764]
HI, this what i get on trainning on Mac M1

/kohya_ss/venv/lib/python3.10/site-packages/transformers/modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
/kohya_ss/venv/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/kohya_ss/venv/lib/python3.10/site-packages/torch/storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
/kohya_ss/venv/lib/python3.10/site-packages/safetensors/torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Replace CrossAttention.forward to use xformers
Traceback (most recent call last):
  File "/kohya_ss/library/train_util.py", line 1817, in replace_unet_cross_attn_to_xformers
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kohya_ss/train_network.py", line 773, in <module>
    train(args)
  File "/kohya_ss/train_network.py", line 149, in train
    train_util.replace_unet_modules(unet, args.mem_eff_attn, args.xformers)
  File "/kohya_ss/library/train_util.py", line 1771, in replace_unet_modules
    replace_unet_cross_attn_to_xformers()
  File "/kohya_ss/library/train_util.py", line 1819, in replace_unet_cross_attn_to_xformers
    raise ImportError("No xformers / xformersがインストールされていないようです")
ImportError: No xformers / xformersがインストールされていないようです
Traceback (most recent call last):
  File "/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/kohya_ss/venv/bin/python', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/Users/UX/Downloads/loraTraining/images', '--resolution=768,768', '--output_dir=/Users/UX/Downloads/loraTraining/model', '--logging_dir=/Users/UX/Downloads/loraTraining/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=290', '--train_batch_size=1', '--max_train_steps=2900', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=float', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

xformers is already instaled  :

#pip install xformers
Requirement already satisfied: xformers in ..../miniconda3/lib/python3.10/site-packages (0.0.16)
Requirement already satisfied: torch>=1.12 in ..../miniconda3/lib/python3.10/site-packages (from xformers) (1.13.1)
Requirement already satisfied: numpy in ..../miniconda3/lib/python3.10/site-packages (from xformers) (1.24.3)
Requirement already satisfied: pyre-extensions==0.0.23 in ..../miniconda3/lib/python3.10/site-packages (from xformers) (0.0.23)
Requirement already satisfied: typing-inspect in ..../miniconda3/lib/python3.10/site-packages (from pyre-extensions==0.0.23->xformers) (0.8.0)
Requirement already satisfied: typing-extensions in ..../miniconda3/lib/python3.10/site-packages (from pyre-extensions==0.0.23->xformers) (4.5.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in ..../miniconda3/lib/python3.10/site-packages (from typing-inspect->pyre-extensions==0.0.23->xformers) (1.0.0)

What can I do ? Thanks

**Comment by Trojaner** [comment]
Try:

venv/scripts/activate
python3 -m pip install xformers

**Comment by mikecastrodemaria** [comment]
> 
 I'm on M1 Mac
