### ISSUE TITLE
Get Desaturated images with trained lora

### ISSUE THREAD

**Issue by 15ky3** [bmaltais/kohya_ss#766]
Hi,

tryed the base SD1.5 image and RealisticVision to Train my own Lora but everytime i get desaturated images when creating in Automatic1111 and use the Lora. Without the Lora its all normal.
Enabled and Disabled VAE in Automatic but no luck. Someone have an idea?

**Comment by bmaltais** [comment]
Have you tried setting the Noise Offset to 0.1? It might help.

**Comment by 15ky3** [comment]
You mean on kohya or automatic1111?

**Comment by bmaltais** [comment]
It is an option under Advanced Training in the GUI.

**Comment by 15ky3** [comment]
Set noise offset to 0.1 but the same problem. Generated images with Lora are desaturated

**Comment by 15ky3** [comment]
Tryed it with Version 21.4.2 and this works without problems and i got perfect images (for my first trys haha :D )

Seems that the newer Versions have Problems with Linux? I dont know, dont have Windows to test it.

**Comment by 15ky3** [comment]
You had this with the actual version? Only one time? 
Tested 4 trainings with different models and different Datasets and this happened every time to me.

**Comment by bmaltais** [comment]
Hummmm maybe some of the newer version of modules are introducing issues .. I will have to run some test myself this weekend to try to pinpoint where this might be coming from ... Either updates made to kohya_ss code of python modules .. or both.

**Comment by 15ky3** [comment]
Hm now that happens every time to me, no matter what machine i use. When i use my lora the images are Desaturated. No matter if i use vae or not. Also the Sample images that i create during training are desaturated.
