### ISSUE TITLE
KeyError: 'time_embed.0.weight'

### ISSUE THREAD

**Issue by UnstableJail** [bmaltais/kohya_ss#774]
I reinstalled everything several times. I have no idea what'S causing this error. Can anyone please help ?

The error: To create a public link, set `share=True` in `launch()`.
./venv/Scripts/python.exe "networks\extract_lora_from_models.py" --save_precision fp16 --save_to "C:/Users/paulv/stable-diffusion-webui/models/Lora/under.safetensors" --model_org "C:/Users/paulv/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors" --model_tuned "C:/Users/paulv/stable-diffusion-webui/models/Stable-diffusion/UnderV1.safetensors" --dim 128 --device cuda --conv_dim 128
loading SD model : C:/Users/paulv/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned.safetensors
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
loading SD model : C:/Users/paulv/stable-diffusion-webui/models/Stable-diffusion/UnderV1.safetensors
Traceback (most recent call last):
  File "C:\Users\paulv\kohya_ss\networks\extract_lora_from_models.py", line 189, in <module>
    svd(args)
  File "C:\Users\paulv\kohya_ss\networks\extract_lora_from_models.py", line 45, in svd
    text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.model_tuned)
  File "C:\Users\paulv\kohya_ss\venv\lib\site-packages\library\model_util.py", line 860, in load_models_from_stable_diffusion_checkpoint
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(v2, state_dict, unet_config)
  File "C:\Users\paulv\kohya_ss\venv\lib\site-packages\library\model_util.py", line 236, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'

**Comment by bmaltais** [comment]
Does it do that with all checkpoint or just UnderV1.safetensors?

**Comment by UnstableJail** [comment]
With all of them

**Comment by UnstableJail** [comment]
Right now I am installing Linux because I am so frustrated. Hopefully it works with another OS

**Comment by AdinLee09** [comment]
Same here

**Comment by yangdeai** [comment]
I have the same error! and the base mode is : https://civitai.com/models/101026/cocoxcohen-europeanstyle
Anyone help?

sd-scripts's commit:
commit cf8021020f82398b3338019b72e15fe293863be6 (HEAD -> main, origin/main, origin/HEAD)
Merge: fb1054b 4a1b92d
Author: Kohya S <52813779+kohya-ss@users.noreply.github.com>
Date:   Sat Jul 29 14:53:04 2023 +0900

    Merge pull request #688 from Noyii/main
    
    fix typo


ERROR:
│ /test/yda-sd-scripts/library/model_util.py:236 in convert_ldm_unet_checkpoint                    │
│                                                                                                  │
│    233 │                                                                                         │
│    234 │   new_checkpoint = {}                                                                   │
│    235 │                                                                                         │
│ ❱  236 │   new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.wei  │
│    237 │   new_checkpoint["time_embedding.linear_1.bias"] = unet_state_dict["time_embed.0.bias"  │
│    238 │   new_checkpoint["time_embedding.linear_2.weight"] = unet_state_dict["time_embed.2.wei  │
│    239 │   new_checkpoint["time_embedding.linear_2.bias"] = unet_state_dict["time_embed.2.bias"  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'time_embed.0.weight'
