### ISSUE TITLE
Bitsandbytes 0.38.1 

### ISSUE THREAD

**Issue by ryuphobia** [bmaltais/kohya_ss#775]
Can we upgrade from 0.35 to 0.38.1?

**Comment by bmaltais** [comment]
I tried but it is causing issues... do you have instructions that are know to work for windows? I could try them and if all is good I could upgrade to 0.38.1.

**Comment by ryuphobia** [comment]
> I tried but it is causing issues... do you have instructions that are know to work for windows? I could try them and if all is good I could upgrade to 0.38.1.

I've no idea. just tried this and crash when run gui.bat
`pip install https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.38.1-py3-none-any.whl
`

**Comment by bmaltais** [comment]
Exactly... it is not working properly for windows... until there is a compatible version will have to stick to 0.35.0
