### ISSUE TITLE
.\venv\Scripts\activate

### ISSUE THREAD

**Issue by AdinLee09** [bmaltais/kohya_ss#779]
Heyho o7

I followed the instruction on how to install it on windows but after .\venv\Scripts\activate it puts out:

 "The system cannot find the path specified." . 
 
 Does anyone know what that is ?

**Comment by bmaltais** [comment]
Did you run setup.bat?

**Comment by AoZhora** [comment]
I'm running into the same issue. I have run setup.bat, deleted pycache, and reinstalled the _ss file.

**Comment by davehornik** [comment]
Unable to install. Also. Setup auto-close itself after spitting few lines on me - so I dont even know whats wrong.

**Comment by AoZhora** [comment]
@davehornik  @AdinLee09 I figured this out. It's because you most likely have python 3.11 installed. Go back to 3.10.6+ and it should fix itself.

**Comment by davehornik** [comment]
https://github.com/bmaltais/kohya_ss/issues/806

I've got 3.10.11 and 3.11.3 on pc.
IF the script doesn't know which right version to pick and is picking the higher one and it is the issue, then it is not MY problem. :) 
I could not even find an argument or something to set my own py dir.

**Comment by jremb** [comment]
Same issue. I have Python 3.10 and 3.11 installed. I manually created the venv with 3.10, activated the environment. Checked version with `py --version` and result is `Python 3.10.10`. Try to start gui with `./gui.bat` and get the error `ModuleNotFoundError: No module named 'packaging'`. 

So I ran `pip install packaging` and get the result `Requirement already satisfied: packaging in c:\...\appdata\roaming\python\python310\site-packages (23.1)`. Yet it still can't find the module.

**Comment by rafstahelin** [comment]
> Same issue. I have Python 3.10 and 3.11 installed. I manually created the venv with 3.10, activated the environment. Checked version with `py --version` and result is `Python 3.10.10`. Try to start gui with `./gui.bat` and get the error `ModuleNotFoundError: No module named 'packaging'`. 
> 
> 
> 
> So I ran `pip install packaging` and get the result `Requirement already satisfied: packaging in c:\...\appdata\roaming\python\python310\site-packages (23.1)`. Yet it still can't find the module.

Did you figure this out? Same issue. Thinking of reverting to 3.10.6

**Comment by xupapa** [comment]
Same issue when running setup.bat
PowerShell 7.3.4
PS C:\Users\xuzt> cd D:
PS D:> cd .\kohya_ss
PS D:\kohya_ss> ..dockerignore^C
PS D:\kohya_ss> .\setup.bat
Warning: Python version 3.10.9 is recommended.
The system cannot find the path specified.
Do you want to uninstall previous versions of torch and associated files before installing? Usefull if you are upgrading from torch 1.12.1 to torch 2.0.0 or if you are downgrading from torch 2.0.0 to torch 1.12.1.
[1] - Yes
[2] - No (recommanded for most)
Enter your choice (1 or 2):

thx for a reply
