### ISSUE TITLE
No module named 'tkinter'

### ISSUE THREAD

**Issue by VeyDlin** [bmaltais/kohya_ss#782]
Ubuntu 20.04.3 

I am renting a new bare virtual machine with V100, I keep getting this error when trying to start, the installation process did not show any errors

I also tried another hosting and got the same result

```
Traceback (most recent call last):
  File "/home/ubuntu/kohya_ss/kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "/home/ubuntu/kohya_ss/dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "/home/ubuntu/kohya_ss/library/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
ModuleNotFoundError: No module named 'tkinter'
```

Here are my steps after the first ubuntu launch

```
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt install -y python3.10 python3-pip python3.10-venv
sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python3.10 3

sudo git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
sudo ./setup.sh
sudo ./gui.sh 
```
I also tried installing python3-tk

`sudo apt-get install python3-tk`

**Comment by creepysnake** [comment]
Try 
sudo apt-get install python3.10-tk

**Comment by DigOrDog** [comment]
> Eventually I get the error No module named 'tkinter' I have already tried about 6 different hosting sites and more than 10 system builds
You can use conda to configure enviroment instead of python3.10-venv.I use this method to solve the issue.
