### ISSUE TITLE
Is it possible to add script to reduce LoRA file sizes?

### ISSUE THREAD

**Issue by vizsumit** [bmaltais/kohya_ss#785]
I came across [this](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts) repo, it has scripts to resize LoRA. Can we have something similar in Kohya_ss ?

No worries if you are occupied. Take your time, 
You are already doing great.

**Comment by bmaltais** [comment]
Look under the Utilities tab, there is already a Resize Lora tool to do that.

**Comment by vizsumit** [comment]
You are Amazing! Thanks!
