### ISSUE TITLE
May version finetuning degrades models capabilities. April version works nice.

### ISSUE THREAD

**Issue by kgonia** [bmaltais/kohya_ss#786]
So I have April version on my local machine and on AWS AMI

```
commit 1e645deebec16ea5c3740ed0903ebbe21f273e1b
Merge: af0df34 cd8f85d
Author: bmaltais <bernard@ducourier.com>
Date:   Sat Apr 1 16:52:37 2023 -0400

    Merge pull request #512 from bmaltais/dev

    v21.4.0
```

with this version I'm able to finetune with specific topic without degrading model capabilities.

Recently I updated code base to newer version

```
 commit 959ef18e2dec8cbdefa3571bbb84cd0d01ff9890 (origin/master, origin/HEAD)
Merge: fa41e40 eb2ca44
Author: bmaltais <bernard@ducourier.com>
Date:   Wed May 3 13:22:06 2023 -0400

    Merge pull request #706 from chiragjn/patch-1

    Add `--no-cache-dir` to reduce image size
```

and it's degrades model capability.

I'm using same data and same configuration but got totally different result. 

Below example of test generation from same prompt during training after first epoch

new code base
![hands_new_with_gradient_20230512084052_000150_00](https://github.com/bmaltais/kohya_ss/assets/4281421/7bd65748-6911-4db9-b3bb-62c27c006d76)

old code base
![hands_new_with_old_20230512105236_000150_00](https://github.com/bmaltais/kohya_ss/assets/4281421/3cbe0065-a296-4eea-ab0e-d024d2e3f02e)

Was there any changes that can affect finetuning?

**Comment by bmaltais** [comment]
Indeed Kohya constantly update his code... Probably a change that is having a negative side effect. Really hard to pinpoint what it might be....

**Comment by rafstahelin** [comment]
> So I have April version on my local machine and on AWS AMI
> 
> 
> 
> ```
> 
> commit 1e645deebec16ea5c3740ed0903ebbe21f273e1b
> 
> Merge: af0df34 cd8f85d
> 
> Author: bmaltais <bernard@ducourier.com>
> 
> Date:   Sat Apr 1 16:52:37 2023 -0400
> 
> 
> 
>     Merge pull request #512 from bmaltais/dev
> 
> 
> 
>     v21.4.0
> 
> ```
> 
> 
> 
> with this version I'm able to finetune with specific topic without degrading model capabilities.
> 
> 
> 
> Recently I updated code base to newer version
> 
> 
> 
> ```
> 
>  commit 959ef18e2dec8cbdefa3571bbb84cd0d01ff9890 (origin/master, origin/HEAD)
> 
> Merge: fa41e40 eb2ca44
> 
> Author: bmaltais <bernard@ducourier.com>
> 
> Date:   Wed May 3 13:22:06 2023 -0400
> 
> 
> 
>     Merge pull request #706 from chiragjn/patch-1
> 
> 
> 
>     Add `--no-cache-dir` to reduce image size
> 
> ```
> 
> 
> 
> and it's degrades model capability.
> 
> 
> 
> I'm using same data and same configuration but got totally different result. 
> 
> 
> 
> Below example of test generation from same prompt during training after first epoch
> 
> 
> 
> new code base
> 
> ![hands_new_with_gradient_20230512084052_000150_00](https://github.com/bmaltais/kohya_ss/assets/4281421/7bd65748-6911-4db9-b3bb-62c27c006d76)
> 
> 
> 
> old code base
> 
> ![hands_new_with_old_20230512105236_000150_00](https://github.com/bmaltais/kohya_ss/assets/4281421/3cbe0065-a296-4eea-ab0e-d024d2e3f02e)
> 
> 
> 
> Was there any changes that can affect finetuning?

My Kohya can't even fine tune. Lora is fine, but get error message when I start fine tune message.
Should I be on 3.10.6 Python rather than 3.10.9?
