### ISSUE TITLE
$MyInvocation.MyCommand.Path sometimes returns null

### ISSUE THREAD

**Issue by ukiyocode** [bmaltais/kohya_ss#788]
$MyInvocation.MyCommand.Path in the 1st line of gui.ps1 can sometimes return null, and then when you try to run wd14 captioning it returns error about not finding cudart64_110.dll. My system is: Windows 11; Windows Terminal
Version: 1.16.10261.0; PowerShell 7.3.4. This code seems to work better:
```
if ($MyInvocation.MyCommand.CommandType -eq "ExternalScript")
{ 
   $ScriptPath = Split-Path -Parent -Path $MyInvocation.MyCommand.Definition 
}
else
{ 
   $ScriptPath = Split-Path -Parent -Path ([Environment]::GetCommandLineArgs()[0]) 
   if (!$ScriptPath){ $ScriptPath = "." } 
}
$env:PATH += ";$($ScriptPath)\venv\Lib\site-packages\torch\lib"
```

**Comment by bmaltais** [comment]
Is this using the new setup.bat script in the dev branch or the master branch?

**Comment by ukiyocode** [comment]
This is master branch but it has nothing to do with setup.bat, it's in gui.ps1
