### ISSUE TITLE
AssertionError: resolution is required / resolution（解像度）指定は必須です

### ISSUE THREAD

**Issue by StableDiffusionHub** [bmaltais/kohya_ss#79]
I'm testing training using Dreambooth LoRA
when i start the training i get this error
checked the issues and couldn't find a previous similar issue

`Folder 1: 7 steps
max_train_steps = 7
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="D:/martin AUTO1111/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt" --train_data_dir="D:\jason512newBG\" --resolution=512,512 --output_dir="D:\jason512newBG\" --logging_dir="" --network_alpha="128" --save_model_as=ckpt --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="last" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="7" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents --max_data_loader_n_workers="1" --clip_skip=2 --xformers --use_8bit_adam
prepare tokenizer
Use DreamBooth method.
Traceback (most recent call last):
  File "D:\Kohya\kohya_ss\train_network.py", line 465, in <module>
    train(args)
  File "D:\Kohya\kohya_ss\train_network.py", line 55, in train
    train_dataset = DreamBoothDataset(args.train_batch_size, args.train_data_dir, args.reg_data_dir,
  File "D:\Kohya\kohya_ss\library\train_util.py", line 484, in __init__
    assert resolution is not None, f"resolution is required / resolution（解像度）指定は必須です"
AssertionError: resolution is required / resolution（解像度）指定は必須です
Traceback (most recent call last):
  File "C:\Users\person\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\person\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:/martin AUTO1111/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=D:\\jason512newBG" --resolution=512,512 --output_dir=D:\\jason512newBG"', '--logging_dir=', '--network_alpha=128', '--save_model_as=ckpt', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=last', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=7', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.`

**Comment by bmaltais** [comment]
This is usually because the `--train_data_dir=D:\\jason512newBG"` does not point to the right folder. Make sure to point to the folder name that contain, say, the subfolder called `100_somethiong something`.

**Comment by StableDiffusionHub** [comment]
@bmaltais thank you for the reply!
It's working now :D 
I renamed the folders using the tools section in the UI, but didn't change the folder structure. This might be what fixed the issue

**Comment by bmaltais** [comment]
Glad you find the fix!
