### ISSUE TITLE
AttributeError: module 'bitsandbytes.optim' has no attribute 'Lion8bit'. Did you mean: 'LAMB8bit'?

### ISSUE THREAD

**Issue by zark119** [bmaltais/kohya_ss#791]
Reinstalled the whole repo, but still can not use Lion8bit. Did I miss something?

**Comment by bmaltais** [comment]
Yeah, the bitsandbytes version for that option does not work well under windows at the moment... Hope a fix will be found eventually.

**Comment by sdbds** [comment]
i made a simple version to use 0.38.1,but for optical it cant merge directly.

**Comment by sdbds** [comment]
> Yeah, the bitsandbytes version for that option does not work well under windows at the moment... Hope a fix will be found eventually.

If you don't mind using the latest version 0.38.1, I can submit a separate PR for this repository.
