### ISSUE TITLE
Trash multicolor result when using my Lora

### ISSUE THREAD

**Issue by novitae** [bmaltais/kohya_ss#800]
Hello @bmaltais , I am facing an issue: every time I use a Lora I made, from the "Additional network" or directly in the prompt, I get the following result:
![00022-1259993015](https://github.com/bmaltais/kohya_ss/assets/85891169/72c0075b-bd28-45e7-a14c-7cd4b0a98d03)

I trained my lora following exactly [this video](https://youtu.be/70H03cv57-o), using the [same configuration file](https://mega.nz/file/ndFRwTIB#-T-6AKXtK8Xa8VZGzNAjARNUyGTj2qEYSLp7zePDOIs). The only thing I changed is the precision to `fp16`, since the distant linux computer I used for the task wasn't supporting the `bf16`

I retrained my Lora an put `Mixed precision` and `Save precision` respectively on `no` `float`, and now the result I get is a dark image:
![00030-1654272522](https://github.com/bmaltais/kohya_ss/assets/85891169/72a924b4-eab7-49f1-a604-4666eb0ab59b)

The training is made on the `runwayml/stable-diffusion-v1-5` model, and I run its Lora result on the [v1-5-pruned.ckpt](https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned.ckpt) from [runwayml/stable-diffusion-v1-5 from hugging faces](https://huggingface.co/runwayml/stable-diffusion-v1-5)

I am running the Lora on a Mac m2, which might cause issues, but I tried other Loras (that were probably generated with `bf16`), and I works with them. Where am I going wrong ? Thanks !

**Comment by rushuna86** [comment]
have you tried just not loading his config file? i remember that video being very old and the old config files from that version not working with the new version, ie naming change etc. hell even my config file going from pre multires/noise offset to version after ddint work let alone config file that old.
