### ISSUE TITLE
Sample Images are black screen

### ISSUE THREAD

**Issue by usmancheema89** [bmaltais/kohya_ss#807]
Training a lora on custom data for face images. 
When the sample images are saved as black images. 
During training I am getting the following message when saving an output:

RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")

**Comment by Ethorbit** [comment]
@bmaltais Please reopen, I'm still getting black samples without any errors.

For now I am switching to a different trainer because this is too much of a headache.
