### ISSUE TITLE
My LORA doesn't seem to do anything

### ISSUE THREAD

**Issue by Atomicbomb248** [bmaltais/kohya_ss#809]
After creating my LORA, I found that it seems to basically have no affect on the resulting image, no matter how high I make the weight. 
With a normal LORA that someone else has created, writing <lora:normalLORA:100> will either create an error, or just give me an image of multicolored pixels, as it probably should. With the LORA I create however, I could go as far as<lora:myLORA:9999999999> and the image will still turn out fine, with just some very minor changes (and in some models having no effect at all). 
I don't seem to be getting any errors anywhere when training or anything. Is there something I forgot to install or run or something that is making my LORAs not learn next to nothing? 
If it helps at all, I'm using 15 images with 100 steps each and the safetensors file comes out to 9,328 KB, which is way lower than the other LORAs I just downloaded form other people.

**Comment by tomi0911** [comment]
Try to change the option: Network Rank (Dimension)
8 it generates 9,328 KB file
128 it generates 143MB file

**Comment by Atomicbomb248** [comment]
Yeah that changed the size of the LORA, but that didn't fix the issue of it doing next to nothing. I just mentioned the small size because I thought that maybe it meant that the LORA hadn't learned anything.

**Comment by Hivemind11** [comment]
if you are hand copying the lora name from the model folder it won't work. try handwriting the name. i think there is a hidden character in the file name.

**Comment by GirthQuake20** [comment]
I am having the same problem, trained my Lora on the faces of a specific person and it doesn't impact any of my outcomes at all, I tried prompts with and without the Lora on the same seed and it gave me the same picture.

**Comment by evanheckert** [comment]
I'm getting the same now, too. I've trained several Lora's successfully, but after a recent update, now the loras don't seem to be learning (Torch 1 or 2, on Windows 11, RTX 3070). FWIW, mine are also about 100x slower to train in the seconds per item.
