### ISSUE TITLE
Unclear instructions for installing CUDNN & no indication of failure

### ISSUE THREAD

**Issue by CodeZombie** [bmaltais/kohya_ss#81]
The readme section for installing CUDNN currently says:

`To install simply unzip the directory and place the cudnn_windows folder in the root of the kohya_diffusers_fine_tuning repo.`

It's unclear what is meant by `kohya_diffusers_fine_tuning repo`. The code looks for the `cudnn_windows` folder inside the root of the `kohya_ss` folder though, so this should be changed in the README.

Additionally, if the install script can't find the `cudnn_windows` folder in the repo root, it just silently ends with no indication of failure.
Some failure modes should be added to the installer(s) to give the user more useful feedback so they won't think cudnn is working when it's not. Even something simple like:
```
if os.path.exists(cudnn_src):
   # ...
else: 
    print(f"Installation Failed: \"{cudnn_src}\" could not be found. ")
```

**Comment by bmaltais** [comment]
Thanks. I have fixed the readme and added the proposed else statement to provide feedback.
