### ISSUE TITLE
nohup docker stucked

### ISSUE THREAD

**Issue by potatoker** [bmaltais/kohya_ss#812]
I can run docker kohya-ss-gui correctly, but when I use nohup prefix to make the docker container running on background, it get stuck.

my cmd is:

`nohup sudo docker compose run --service-ports kohya-ss-gui`

and it get stuck after print the log 

```
NOTE: CUDA Forward Compatibility mode ENABLED.
  Using CUDA 12.1 driver version 530.30.02 with kernel driver version 470.82.01.
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

```

what could be the cause

**Comment by Trojaner** [comment]
You can use `docker compose up -d` instead
