### ISSUE TITLE
Renaming Lora after creation?

### ISSUE THREAD

**Issue by Cragsand** [bmaltais/kohya_ss#821]
After creating my lora it's named "last" even though I named the file cragsand.safetensor
Is there a way to rename the metadata of the file after it's creation?
I did not see an option for naming the model in the GUI
![bild](https://github.com/bmaltais/kohya_ss/assets/49168045/a8955247-1f32-4f91-b89f-390eee7884da)

Best Regards

**Comment by Xyem** [comment]
The `Model output name` is set on the `Folders` tab.

**Comment by slashedstar** [comment]
I think this website allows you to do this (among other things)
https://xypher7.github.io/lora-metadata-viewer/

 Scroll down to "ss_output_name" change change the name in there

**Comment by tetsuoo-online** [comment]
> I think this website allows you to do this (among other things) https://xypher7.github.io/lora-metadata-viewer/
> 
> Scroll down to "ss_output_name" change the name in there

omg I needed that, thank you !!!
