### ISSUE TITLE
mixing path separators on windows

### ISSUE THREAD

**Issue by Centurion-Rome** [bmaltais/kohya_ss#832]
On Windows  wrong directory separators are beeing used - mixing "\" with "/".

![image](https://github.com/bmaltais/kohya_ss/assets/75789136/c62651ef-a775-4575-ad1c-ab841925de4f)
or from command line args generated by UI:
"--train_data_dir="F:/Temp/kohya/dst\img"
"--output_dir="F:/Temp/kohya/dst\model""

**Comment by bmaltais** [comment]
Yeah... they don't cause actually issue but it is ugly to look at... One day I may tackle that one... but since it is only cosmetic there is not much value and it will be a lot of work to fix.
