### ISSUE TITLE
something wrong when run setup.bat

### ISSUE THREAD

**Issue by xupapa** [bmaltais/kohya_ss#834]
System Information:
System: Windows, Release: 10, Version: 10.0.19045, Machine: AMD64, Processor: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD

Python Information:
Version: 3.10.9, Implementation: CPython, Compiler: MSC v.1934 64 bit (AMD64)

Virtual Environment Information:
Path: D:\kohya_ss\venv

GPU Information:
Name: NVIDIA GeForce RTX 2080 SUPER, VRAM: 8192 MiB

Traceback (most recent call last):
  File "D:\kohya_ss\tools\validate_requirements.py", line 5, in <module>
    from packaging.requirements import Requirement
ModuleNotFoundError: No module named 'packaging'

thx for a reply

**Comment by bmaltais** [comment]
This is odd... Try installing the module with:

```
activate.ps1
pip install packaging==23.1
```

**Comment by Gaurang-1402** [comment]
I got the same error. It is because setup.bat is not correctly installing everything. The window shuts mysteriously before the installation finishes. How to deal with that?

**Comment by Gaurang-1402** [comment]
This is the error I 

```
System Information:
System: Windows, Release: 10, Version: 10.0.22621, Machine: AMD64, Processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel

Python Information:
Version: 3.11.0, Implementation: CPython, Compiler: MSC v.1933 64 bit (AMD64)

Virtual Environment Information:
Path: C:\Users\gaura\Desktop\CV and Generative AI\kohya_ss\venv

GPU Information:
Name: NVIDIA GeForce RTX 3070 Ti Laptop GPU, VRAM: 8192 MiB
Traceback (most recent call last):
  File "C:\Users\gaura\Desktop\CV and Generative AI\kohya_ss\tools\validate_requirements.py", line 5, in <module>
    from packaging.requirements import Requirement
ModuleNotFoundError: No module named 'packaging'
```
