### ISSUE TITLE
Cant use fp16 to Train Lora Model with AMD GPU on Ubuntu

### ISSUE THREAD

**Issue by MarekLeet** [bmaltais/kohya_ss#839]
I installed Ubuntu cause i could get it to work under Win10 with AMD Grafik Card RX6900XT
I used this Guide https://initialxy.com/lesson/2023/03/31/training-stable-diffusion-lora-with-kohya-on-amd-gpu
step by step but still getting this error below
i tryed to get help with chatgpt it  said something like:
There is an error occurred during the execution of the command you provided. The error message suggests that there is an issue with the "slow_conv2d_cpu" implementation for the 'Half' datatype in the code. 

please help to solve that problem

Here is it:

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Folder 100_Abey Ja: 16 images found
Folder 100_Abey Ja: 1600 steps
max_train_steps = 1600
stop_text_encoder_training = 0
lr_warmup_steps = 160
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --enable_bucket --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="/home/marek/Schreibtisch/Abey/images" --resolution=512,512 --output_dir="/home/marek/Schreibtisch/Abey" --logging_dir="/home/marek/Schreibtisch/Abey" --network_alpha="1" --save_model_as=safetensors --network_module=networks.lora --network_dim=8 --output_name="Abey" --lr_scheduler_num_cycles="1" --learning_rate="1e-05" --lr_scheduler="cosine" --lr_warmup_steps="160" --train_batch_size="1" --max_train_steps="1600" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --caption_extension=".txt" --cache_latents --optimizer_type="Lion" --max_data_loader_n_workers="0" --bucket_reso_steps=64 --shuffle_caption --bucket_no_upscale
2023-05-24 17:38:11.701466: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-24 17:38:13.589786: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
prepare tokenizer
Use DreamBooth method.
prepare images.
found directory /home/marek/Schreibtisch/Abey/images/100_Abey Ja contains 16 image files
1600 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "/home/marek/Schreibtisch/Abey/images/100_Abey Ja"
    image_count: 16
    num_repeats: 100
    shuffle_caption: True
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Abey Ja
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 4740.67it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 1600
mean ar error (without repeats): 0.0
prepare accelerator
/home/marek/kohya_ss/venv/lib/python3.10/site-packages/accelerate/accelerator.py:249: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Fetching 15 files: 100%|███████████████████████████████████████████████████████| 15/15 [00:00<00:00, 132731.14it/s]

/home/marek/kohya_ss/venv/lib/python3.10/site-packages/transformers/modeling_utils.py:402: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(checkpoint_file, framework="pt") as f:
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
[Dataset 0]
caching latents.
  0%|                                                                                       | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/marek/kohya_ss/train_network.py", line 783, in <module>
    train(args)
  File "/home/marek/kohya_ss/train_network.py", line 157, in train
    train_dataset_group.cache_latents(vae, args.vae_batch_size, args.cache_latents_to_disk, accelerator.is_main_process)
  File "/home/marek/kohya_ss/library/train_util.py", line 1399, in cache_latents
    dataset.cache_latents(vae, vae_batch_size, cache_to_disk, is_main_process)
  File "/home/marek/kohya_ss/library/train_util.py", line 812, in cache_latents
    latents = vae.encode(img_tensors).latent_dist.sample().to("cpu")
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/vae.py", line 566, in encode
    h = self.encoder(x)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/diffusers/models/vae.py", line 130, in forward
    sample = self.conv_in(sample)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
Traceback (most recent call last):
  File "/home/marek/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 923, in launch_command
    simple_launcher(args)
  File "/home/marek/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/marek/kohya_ss/venv/bin/python', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/home/marek/Schreibtisch/Ichiro/images', '--resolution=512,512', '--output_dir=/home/marek/Schreibtisch/Ichiro', '--logging_dir=/home/marek/Schreibtisch/Ichiro', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--network_dim=8', '--output_name=Ichiro', '--lr_scheduler_num_cycles=1', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=160', '--train_batch_size=1', '--max_train_steps=1600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=Lion', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--shuffle_caption', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by MarekLeet** [comment]
If i change the Training Parameters "Mixed Precision" to no and "Save Precision" to float and deactivate cache latens 
then it starts training with like 16.5/it
doese anyone know what the problem is?

**Comment by MarekLeet** [comment]
It took approximately 6 hours and 42 minutes to complete 1600 training steps without using mixed precision, saving the model with float precision, and deactivating the cache latents option. Well at least it worked but using that parameters would save a lot of time. Someone has an idea how to fix that problem?

**Comment by tornado73** [comment]
install-https://github.com/bmaltais/kohya_ss/discussions/762

Caption Extension - .txt

Optimizer - AdamW

LR Scheduler - constant

Network Rank (Dimension) 128

Network Alpha 128

Enable buckets - uncheck

Max resolution - 
resolution of the photos on which you train


Advanced Configuration
-------------------------------
Use xformers - uncheck

Memory efficient attention - check

Clip skip- 2

Max num workers for DataLoader- 1

[15_3.zip](https://github.com/bmaltais/kohya_ss/files/11582279/15_3.zip) -config file

![Screenshot from 2023-05-27 18-00-54](https://github.com/bmaltais/kohya_ss/assets/58679489/4648c6aa-312d-4b3f-b774-fe203f576ea0)
768*768
![Screenshot from 2023-05-27 18-03-07](https://github.com/bmaltais/kohya_ss/assets/58679489/33149fd7-70e5-48ec-8c49-2245177f4f81)
640*640

**Comment by MarekLeet** [comment]
Unfortunately that didnt helped, anyway i found the solution!

make sure you have ubunto 2.04.xx (_you can check with uname -m && cat /etc/*release)_

_we need some packages_
sudo apt install wget gnupg2 gawk curl
sudo apt install libnuma-dev libncurses5

**reboot**

_make username belong to the group render and video_
sudo usermod -a -G render $LOGNAME
sudo usermod -a -G video $LOGNAME


**then you need to install rocm**
sudo apt-get update

wget https://repo.radeon.com/amdgpu-install/5.4.2/ubuntu/focal/amdgpu-install_5.4.50402-1_all.deb

sudo apt-get install ./amdgpu-install_5.4.50402-1_all.deb

sudo amdgpu-install --usecase=rocm --no-dkms

then **reboot**


**well that worked for me now i can use fp16 to train a lora model**
