### ISSUE TITLE
Extracted lora not working 

### ISSUE THREAD

**Issue by CarlosReyes99** [bmaltais/kohya_ss#850]
trying to extract the lora, it gives me this error, currently running on paperspace, i have also tried on colab and it shows the same

File "/notebooks/kohya_ss/networks/extract_lora_from_models.py", line 189, in <module>
    svd(args)
  File "/notebooks/kohya_ss/networks/extract_lora_from_models.py", line 45, in svd
    text_encoder_t, _, unet_t = model_util.load_models_from_stable_diffusion_checkpoint(args.v2, args.model_tuned)
  File "/notebooks/kohya_ss/venv/lib/python3.9/site-packages/library/model_util.py", line 871, in load_models_from_stable_diffusion_checkpoint
    info = vae.load_state_dict(converted_vae_checkpoint)
  File "/notebooks/kohya_ss/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.value.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.proj_attn.bias". 
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_query.weight", "encoder.mid_block.attentions.0.to_query.bias", "encoder.mid_block.attentions.0.to_key.weight", "encoder.mid_block.attentions.0.to_key.bias", "encoder.mid_block.attentions.0.to_value.weight", "encoder.mid_block.attentions.0.to_value.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_query.weight", "decoder.mid_block.attentions.0.to_query.bias", "decoder.mid_block.attentions.0.to_key.weight", "decoder.mid_block.attentions.0.to_key.bias", "decoder.mid_block.attentions.0.to_value.weight", "decoder.mid_block.attentions.0.to_value.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_out.0.bias".

**Comment by hosein-moayedi** [comment]
Hi @bmaltais !
I have this problem also...
My base model is ckpt file of Deliberat model: https://huggingface.co/XpucT/Deliberate/tree/main
and I used from this script for train and save the result with .ckpt format (save with float32 not half like float16): https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py

And when I am using from this script "extract_lora_from_models.py" I am getting same error like @CarlosReyes99 

What do you think about this problem?

**Comment by nayan-dhabarde** [comment]
got more info on this, only happens when i do base model - RealisticVision, tuned-model: model trained from realisitc vision

Script works for sd1.5 as base and tuned model as realistic vision

Can you please help us solve this for models trained on realistic vision
