### ISSUE TITLE
kohya_ss/venv/bin/python: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by Flaegster** [bmaltais/kohya_ss#856]
When I want to train a model with kohya I get the following error:

sh: /Users/XXXi/VLADDiffusion/kohya_ss/venv/bin/accelerate: /Users/dflagmei/VLATDiffusion/kohya_ss/venv/bin/python: bad interpreter: No such file or directory

whats the problem?

**Comment by venshine** [comment]
I also encountered the same problem. May I ask how you solved it?

**Comment by Flaegster** [comment]
Try to delete the "venv" folder and run it again. 

<img width="666" alt="Bildschirm­foto 2023-06-19 um 07 55 49" src="https://github.com/bmaltais/kohya_ss/assets/131164428/790a79b6-7512-4fb5-b0bf-9911762af705">
