### ISSUE TITLE
It won't tag my pictures.

### ISSUE THREAD

**Issue by BobSmith2022** [bmaltais/kohya_ss#867]
I've used this program successfully before, but it suddenly decided not to tag anything, despite the fact that I didn't make any changes to it.  

I get this when I attempt to use WD14 Captioning:

Captioning files in C:/Users/BobsA/Downloads/img...
accelerate launch "./finetune/tag_images_by_wd14_tagger.py" --batch_size=8 --general_threshold=0.35 --character_threshold=0.35 --caption_extension=".txt" --model="SmilingWolf/wd-v1-4-convnextv2-tagger-v2" --max_data_loader_n_workers="2" --debug --remove_underscore --frequency_tags "C:/Users/BobsA/Downloads/img"
using existing wd14 tagger model
2023-05-29 03:40:10.980970: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-29 03:40:11.839060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9580 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:01:00.0, compute capability: 8.6
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
found 0 images.
0it [00:04, ?it/s]

Tag frequencies:
done!
...captioning done 

It's not an empty folder.  It has nothing but pictures in it.  The name of the folder is a number followed by an underscore followed by the actual name.  That folder is in a folder called img and I'm directing the program to img.  In other words, I've done everything I'm supposed to.  

As I said, I've successfully used the program before.  But now it won't work.  

I tried completely reinstalling koyha.  No change.

**Comment by kulichenko1** [comment]
@BobSmith2022 how did you fix it? I have similar problem

**Comment by BobSmith2022** [comment]
I wish I could help you, but I don't remember how I fixed it.

I remember it was something stupid that I had done wrong, but beyond that,
I honestly don't have a clue.

I haven't even used the program for months.  My copy is corrupted, it won't
run at all, and my internet connection has become too slow for me to
re-download it.
