### ISSUE TITLE
Venv issues installing?

### ISSUE THREAD

**Issue by Mousewrites** [bmaltais/kohya_ss#87]
Trying to get the gui installed and working, the install asks for python 10 (which i have) and pip upgrades, (which i did), but it doesn't seem to 'see' them.

I've been told it's probably a venv issue, but to be frank, I have no real idea how to fix this. I'm new to python in general (most of the time i use it in Maya to script), and new to github and all of the backend stuff, so please assume I know nothing. 😁 

Auto1111 works fine, gradio and extensions and all that. I know there was a question about this being a auto extension, which I'd love if possible; then everything is in the same space? 

This is what I get when I run the install

![image](https://user-images.githubusercontent.com/114956889/215854703-84e02d62-f52b-467f-8870-a4f10ed1eaa0.png)

I can do that pip upgrade it asks for
![image](https://user-images.githubusercontent.com/114956889/215854896-d84ca25f-f591-48da-af46-1d5ef5d051bd.png)

And if I run the initialization script again, i get the same errors. 

![image](https://user-images.githubusercontent.com/114956889/215855492-31335205-1bfc-4760-af72-36f92a062881.png)

So, it's got to be that the venv i'm in (?) is the wrong one? Venv is a virtual environment, like a little dummy machine running virtually, right?  How the heck do I a) tell 'which' venv i'm in, and b) how do I tell this script to use the right venv?

I love all the lora i see people making and would like to make some myself. 

Thank you so much for any help!

**Comment by bmaltais** [comment]
Try deleting the venv folder and starting from scratch. Close your powershell terminal, use windows explorer to delete the venv, then start fresh with the install.

Also, create the new venv with this command... in case you have an older readme: `python -m venv venv`

**Comment by bmaltais** [comment]
It is also possible you have python modules installed outside the venv that are causing issues... try removing them with:

```
pip freeze > uninstall.txt
pup ininstall -y -r uninstal.txt
```

Note that the above will break other solutions that might depend on non venv based python modules... but it might be the price to pay to get things going.

**Comment by Mousewrites** [comment]
Yup, it was a venv issue. Ended up uninstalling ALL python copies, reinstalling conda to the default location, and now the install worked. Thank you for your help!
