### ISSUE TITLE
No module named '_tkinter'

### ISSUE THREAD

**Issue by sunilw** [bmaltais/kohya_ss#873]
Apologies, I don't have a particularly masterful understanding of python environmental settings.

I'm on Ubuntu 22.04.
I've cloned the kohya_ss repo, entered the newly created directory and run the setup script.

When running gui.sh, I get this:

```
Validating that requirements are satisfied.
All requirements satisfied.
Traceback (most recent call last):
  File "/home/mantis/opt/kohya_ss/kohya_gui.py", line 4, in <module>
    from dreambooth_gui import dreambooth_tab
  File "/home/mantis/opt/kohya_ss/dreambooth_gui.py", line 13, in <module>
    from library.common_gui import (
  File "/home/mantis/opt/kohya_ss/library/common_gui.py", line 1, in <module>
    from tkinter import filedialog, Tk
  File "/home/mantis/.pyenv/versions/3.10.6/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```

Within the newly created kohya directory, If I do 'python --version', I get back 'Python 3.10.6'.

I see that there is a requirements file in the folder root, so I do 'pip install -U -r requirements.txt'

After that I try to launch the gui again, but I get the same error as above.

**Comment by cbstyle** [comment]
the same problem.

**Comment by KoshiGlitch** [comment]
Same issue here on M1 Mac.

**Comment by sunilw** [comment]
I completely uninstalled kohya and went back to using Automatic1111. I've also been running ComfyUI successfully.
I've come back to kohya today and installed from scratch.
The same error prevents kohya from running on my setup.

**Comment by Steenos** [comment]
I'm on Mac as well and had this error, I got it working by running  `brew install python-tk@3.10`

**Comment by rchennau** [comment]
For linux debian (ex: ubuntu) running the command
 sudo apt-get install python3.10-tk worked for

**Comment by netcob64** [comment]
same issue, on windows 10 after kohya successful installation 
![Capture d’écran 2023-09-23 110019](https://github.com/bmaltais/kohya_ss/assets/33779884/a308bc74-3d23-4f1c-8190-4318ac962bd2)

**Comment by netcob64** [comment]
Fixed for me
I've updated my python 3.10.8 installation adding tcl/tk and IDLE option. 
Now Kohya come in my browser.

**Comment by blekknajt** [comment]
Pfff, what a ride. I compiled python from source (ubuntu) - and very important one - You have to have tk-dev also installed on your system. So first "sudo apt install tk-dev" - and then "sudo make install".

**Comment by lijian-zt** [comment]
> Pfff, what a ride. I compiled python from source (ubuntu) - and very important one - You have to have tk-dev also installed on your system. So first "sudo apt install tk-dev" - and then "sudo make install".

worked for me !

**Comment by EhsaantechEngineering** [comment]
> For linux debian (ex: ubuntu) running the command sudo apt-get install python3.10-tk worked for

This worked for me on ubuntu 24 `sudo apt-get install python3.11-tk`
