### ISSUE TITLE
error when installing kohya_ss

### ISSUE THREAD

**Issue by GOLDENLULUZ** [bmaltais/kohya_ss#876]
2023-05-30 20:24:01.120348: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-05-30 20:24:01.120721: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

The same error also jump up when trying to train lora.

i‘m using a new bought asus 4070 dual. please tell me how to fix this.

**Comment by rjorekit** [comment]
same for me. been trying to get it working the past 24 hrs. even cloning a new repo from scratch doesn't fix it. tried reinstalling xformers, cuda dev kit, gpu drivers, different torch versions.. everything I can think of

**Comment by rushuna86** [comment]
it's actually the update, that's causing this error just revert back to the previous version.

**Comment by GOLDENLULUZ** [comment]
> it's actually the update, that's causing this error just revert back to the previous version.

thank you.
It's my first installing and I don't have a previous version. Where can I find it?

**Comment by rushuna86** [comment]
https://github.com/bmaltais/kohya_ss/releases

**Comment by GOLDENLULUZ** [comment]
> https://github.com/bmaltais/kohya_ss/releases

thank you, I will try later.

**Comment by rushuna86** [comment]
@bmaltais for whatever reason, doing a clean clean install using experimental 2.0.1+cu118 from update isn't installing the requirements to \venv\Lib\site-packages\torch\lib

completely missing cublas64_11.dll and all the related files associated with cu118
