### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2]

### ISSUE THREAD

**Issue by viik420** [bmaltais/kohya_ss#878]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\scrocle\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\bitsandbytes\\__init__.py'

I run the setup.bat and everything starts downloading but in the end I get the error above.
The first thing I noticed was that it skips installing bitsandbytes because there is no directory for it, but why not just create it if it's not there or install it if it's not installed. 

One more thing I noticed was that the setup script uninstalls the torch 2.0.1 and installs torch 2.0.0 and later in the script it is expecting torch 2.0.1 that it uninstalled itself, as you can see in the image below.
![Screenshot (6)](https://github.com/bmaltais/kohya_ss/assets/49725890/9b3f9660-a024-4886-b3aa-54aa842eeb03)

**Comment by zuksoon** [comment]
+1

**Comment by bmaltais** [comment]
Have you tried deleting the venv folder and redo the full setup.bat?

Also, you might have installed modules outside the venv that are conflicting... If you run `pip freeze` do you get a list of modules... If yes you probably have conflicts there. Best is to uninstall all non venv based modules and only install modules in the venv.

To do that simply run:

```
pip freeze > uninstall.txt
pip uninstall -y -r uninstall.txt
```

Then delete the venv and run setup again.

**Comment by zuksoon** [comment]
I had a similar error, I forgot to write it there. Everything works now. Thx
