### ISSUE TITLE
Error while running on MacBook M1

### ISSUE THREAD

**Issue by natl-set** [bmaltais/kohya_ss#879]
2023-05-31 17:57:12.183 Python[74867:3022567] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a3ce719c __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a38064d4 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a3d103f4 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00000001a6eaec14 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 320
	4   AppKit                              0x00000001a6e9cee8 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 816
	5   AppKit                              0x00000001a6e9cbac -[NSWindow initWithContentRect:styleMask:backing:defer:] + 48
	6   libtk8.6.dylib                      0x0000000125ca0d84 TkMacOSXMakeRealWindowExist + 524
	7   libtk8.6.dylib                      0x0000000125ca0a68 TkWmMapWindow + 56
	8   libtk8.6.dylib                      0x0000000125c14270 MapFrame + 76
	9   libtcl8.6.dylib                     0x0000000125b48b84 TclServiceIdle + 84
	10  libtcl8.6.dylib                     0x0000000125b2cee0 Tcl_DoOneEvent + 296
	11  libtk8.6.dylib                      0x0000000125c94a28 TkpInit + 720
	12  libtk8.6.dylib                      0x0000000125c0d278 Initialize + 2292
	13  _tkinter.cpython-310-darwin.so      0x00000001229d633c Tcl_AppInit + 80
	14  _tkinter.cpython-310-darwin.so      0x00000001229d033c Tkapp_New + 592
	15  _tkinter.cpython-310-darwin.so      0x00000001229cfcec _tkinter_create + 580
	16  Python                              0x00000001012e4834 cfunction_vectorcall_FASTCALL + 88
	17  Python                              0x000000010138cc7c call_function + 128
	18  Python                              0x000000010138a494 _PyEval_EvalFrameDefault + 43104
	19  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	20  Python                              0x0000000101292904 _PyObject_FastCallDictTstate + 96
	21  Python                              0x00000001013089c4 slot_tp_init + 196
	22  Python                              0x0000000101300990 type_call + 288
	23  Python                              0x000000010129269c _PyObject_MakeTpCall + 136
	24  Python                              0x000000010138cd0c call_function + 272
	25  Python                              0x000000010138a494 _PyEval_EvalFrameDefault + 43104
	26  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	27  Python                              0x0000000101292904 _PyObject_FastCallDictTstate + 96
	28  Python                              0x00000001013089c4 slot_tp_init + 196
	29  Python                              0x0000000101300990 type_call + 288
	30  Python                              0x000000010129269c _PyObject_MakeTpCall + 136
	31  Python                              0x000000010138cd0c call_function + 272
	32  Python                              0x000000010138a4bc _PyEval_EvalFrameDefault + 43144
	33  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	34  Python                              0x0000000101292974 _PyObject_FastCallDictTstate + 208
	35  Python                              0x00000001013089c4 slot_tp_init + 196
	36  Python                              0x0000000101300990 type_call + 288
	37  Python                              0x000000010129269c _PyObject_MakeTpCall + 136
	38  Python                              0x000000010138cd0c call_function + 272
	39  Python                              0x000000010138a544 _PyEval_EvalFrameDefault + 43280
	40  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	41  Python                              0x000000010138cc7c call_function + 128
	42  Python                              0x000000010138a544 _PyEval_EvalFrameDefault + 43280
	43  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	44  Python                              0x000000010138cc7c call_function + 128
	45  Python                              0x000000010138a544 _PyEval_EvalFrameDefault + 43280
	46  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	47  Python                              0x000000010138cc7c call_function + 128
	48  Python                              0x000000010138a544 _PyEval_EvalFrameDefault + 43280
	49  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	50  Python                              0x00000001013a526c _PyObject_VectorcallTstate.4671 + 96
	51  Python                              0x00000001013a5120 context_run + 92
	52  Python                              0x00000001012e4784 cfunction_vectorcall_FASTCALL_KEYWORDS + 84
	53  Python                              0x000000010138a65c _PyEval_EvalFrameDefault + 43560
	54  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	55  Python                              0x000000010138cc7c call_function + 128
	56  Python                              0x000000010138a41c _PyEval_EvalFrameDefault + 42984
	57  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	58  Python                              0x000000010138cc7c call_function + 128
	59  Python                              0x000000010138a41c _PyEval_EvalFrameDefault + 42984
	60  Python                              0x000000010137e9e0 _PyEval_Vector + 376
	61  Python                              0x0000000101295a0c method_vectorcall + 388
	62  Python                              0x000000010144cc08 thread_run + 120
	63  Python                              0x00000001013eba28 pythread_wrapper + 48
	64  libsystem_pthread.dylib             0x00000001a3b8ffa8 _pthread_start + 148
	65  libsystem_pthread.dylib             0x00000001a3b8ada0 thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
./gui.sh: line 22: 74867 Abort trap: 6           python "$SCRIPT_DIR/kohya_gui.py" "$@"

**Comment by bobpuffer1** [comment]
I'm getting this also trying to train on Dreambooth LoRA using a MBP M2 Max
