### ISSUE TITLE
ERROR: xformers-some numbers is not a supported wheel on this platform

### ISSUE THREAD

**Issue by Wutislife0022** [bmaltais/kohya_ss#88]
I am on the CUDNN 8.6 step and it won't install for some reason. I can't seem to figure out why. Any help is appreciated.

NVIDIA 3060
AMD Ryzen 7 5800X
16GB RAM

```PS D:\ai\kohya_ss> .\venv\Scripts\activate
(venv) PS D:\ai\kohya_ss> python .\tools\cudann_1.8_install.py
[!] xformers NOT installed.
Installing xformers with: pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl
Installing xformers
Traceback (most recent call last):
  File "D:\ai\kohya_ss\tools\cudann_1.8_install.py", line 82, in <module>
    check_versions()
  File "D:\ai\kohya_ss\tools\cudann_1.8_install.py", line 73, in check_versions
    run(f"pip install {x_cmd}", desc="Installing xformers")
  File "D:\ai\kohya_ss\tools\cudann_1.8_install.py", line 30, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl
Error code: 1
stdout: <empty>
stderr: ERROR: xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.```

**Comment by bmaltais** [comment]
You may want to try this troubleshooting tip as this is usually related to conflicting modules installed loally that take precedence over the modules in the venv: https://github.com/bmaltais/kohya_ss#filenotfounderror

**Comment by manilovefeet** [comment]
Any resolution on this? I'm having this error when installing the xformers step, and the filenotfounderror tip didn't fix this

**Comment by bmaltais** [comment]
I have no idea. If you followed aitrepreneur instructions and it still does not work then it might be something specific with your PC and this is hard to troubleshoot. Try uninstalling kohya, uninstall python and then start from scratch.

This might put things back where the belong and make it work.

**Comment by BoBoBiBop** [comment]
Same issue here.

**Comment by fifth-dimensional** [comment]
I had the same issue, but found a solution here: https://stackoverflow.com/questions/2812520/dealing-with-multiple-python-versions-and-pip?rq=1

Issue seemed to originate from a conflict from having multiple versions of python.

I ran the following command to confirm that I had multiple versions of python on my machine (I had both 3.9 and 3.10)
`py --list` 

Then I re-ran I prefixed the python version in front of the commands:
`py -3.10 -m pip install --use-pep517 --upgrade -r requirements.txt
py -3.10 -m pip install -U -I --no-deps https://github.com/C43H66N12O12S2/stable-diffusion-webui/releases/download/f/xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl`

**Comment by Wutislife0022** [comment]
Sorry I haven't responded in so long, haven't been working on stable because of some technical difficulties with my pc. fifth-dimensional's solution worked for me.

**Comment by gt9797** [comment]
To anyone who comes to this at a later date.... Start all the way from the beginning, change python to py -3.10 in the install commands seen in the Readme.md. And also for the Optional: CUDNN 8.6 install if you got a 30x/40x series.
