### ISSUE TITLE
is cosine with restarts wrong?

### ISSUE THREAD

**Issue by udterry** [bmaltais/kohya_ss#881]
I set LR number of cycles=2
![QQ图片20230601154249](https://github.com/bmaltais/kohya_ss/assets/49636060/0c9e1ba9-757f-4c8c-9d02-4851cabad7cd)

**Comment by Xyem** [comment]
How are you getting those graphs? I had very bad results using Cosine with Restarts too and might be getting the same issue.

**Comment by bmaltais** [comment]
This might be an issue with kohya_ss code I am afraid... unless my gui is not outputing the right parameters to do cosine with restart... I will do a quick check...

**Comment by bmaltais** [comment]
Yeah... the GUI is outputing the right parameters... the issue is with kohya's code...
