### ISSUE TITLE
After last update training speed slow down

### ISSUE THREAD

**Issue by SileNTViP** [bmaltais/kohya_ss#884]
After last update with update.bat on 3080... 715 steps with batch 8 ~5h (2k+ steps show ~31h). Roll back on version 21.5.12 and rerun setup.bat with same parameters ~1h
Win 11 x64

System: Windows, Release: 10, Version: 10.0.22621, Machine: AMD64, Processor: Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
Python Information: Version: 3.10.10, Implementation: CPython, Compiler: MSC v.1929 64 bit (AMD64)
Virtual Environment Information: Path: D:\kohya_ss\venv
GPU Information: Name: NVIDIA GeForce RTX 3080, VRAM: 10240 MiB

**Comment by bmaltais** [comment]
Have you tried reinstalling the previous release? Is the speed back to normal? I suspect a recent code update in the kohya's repo might be causing this for a few users. No idea why that is :-(

**Comment by sumirecccp** [comment]
Did you updated to Nvidia driver 535.98? It's driver's bug, try to rollback.

**Comment by SileNTViP** [comment]
> Did you updated to Nvidia driver 535.98? It's driver's bug, try to rollback.

Yes. Try downgrade driver.

**Comment by bmaltais** [comment]
Oh... is there a known driver issue? Any link to the issue?

**Comment by SileNTViP** [comment]
> Oh... is there a known driver issue? Any link to the issue
After updating GUI and downgrade driver on 532.03 version - solve problem. Thanx
