### ISSUE TITLE
GUI.bat just closes after "Validating requirements are satisfied" 

### ISSUE THREAD

**Issue by itslukebond** [bmaltais/kohya_ss#886]
Hi all,

Whenever I attempt to launch gui.bat, the terminal window abruptly closes following the 'Validating requirements are satisfied' message.

I've undertaken exhaustive troubleshooting steps in an effort to rectify this issue, including a complete reinstallation of Kohya and its corresponding environment. Despite going through the setup process from scratch, the problem persists.

In addition, I tried reinstalling all the local Python modules using the scripts provided (i.e., 'pip freeze > uninstall.txt' and 'pip uninstall -r uninstall.txt'). Unfortunately, this did not yield any positive results.

For context, I'm operating on Windows 11 and using the recommended Python 3.10.9 release.

**Comment by bmaltais** [comment]
Try deleting the venv folder and re-run .\setup.bat

Hope this will help fix the issue. You could also try to run .\gui.ps1 instead of .\gui.bat to see the error message.

**Comment by alexdingfelder** [comment]
running into the exact same problem - the above solution didn't work for me at all

**Comment by alexdingfelder** [comment]
ran into the same issue - it seems like the setup script doesn't install the right version of torch (2.0.1) that fixed it for me.

**Comment by rehvka** [comment]
Hello, facing the same issue. After updating the script, CMD just closes after one second. I try reinstalling and same happens. I tried deleting venv and running /setup.bat, same.

**Comment by rehvka** [comment]
.ps1 causes same error

**Comment by rehvka** [comment]
ok, I Re-installed in a different disk and that solved it ¯\_(ツ)_/¯
