### ISSUE TITLE
Error: The following packages are missing

### ISSUE THREAD

**Issue by farpit** [bmaltais/kohya_ss#887]
How can i fix this?

`Validating that requirements are satisfied.
Error: The following packages are missing:
 - accelerate==0.18.0
 - albumentations==1.3.0
 - altair==4.2.2
 - bitsandbytes==0.35.0; sys_platform == 'win32'
 - dadaptation==3.1
 - diffusers[torch]==0.10.2
 - einops==0.6.0
 - ftfy==6.1.1
 - gradio==3.32.0; sys_platform != 'darwin'
 - lion-pytorch==0.0.6
 - opencv-python==4.7.0.68
 - pytorch-lightning==1.9.0
 - tensorboard==2.10.1 ; sys_platform != 'darwin'
 - toml==0.10.2
 - transformers==4.26.0
 - wandb==0.15.0
 - fairscale==0.4.13
 - timm==0.6.12
 - huggingface-hub==0.13.3; sys_platform != 'darwin'
 - tensorflow==2.10.1; sys_platform != 'darwin'
 - lycoris_lora==0.1.4
Error: The following packages have the wrong version:
 - requests==2.28.2 (expected version requests==2.28.2, found version 2.31.0)

Run ←[33mupgrade.ps1←[0m or ←[33mpip install -U -r requirements.txt←[0m to resolve the missing requirements listed above...`

**Comment by farpit** [comment]
i tried to run pip install -U -r requirements.txt and this happened after a while:


ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'D:\\ai\\stable-diffusion-webui\\kohya_ss\\venv\\Lib\\site-packages\\bitsandbytes\\__init__.py'

**Comment by bmaltais** [comment]
Try deleting the full venv folder and then run .\setup.bat again

**Comment by alexdingfelder** [comment]
getting the same issue - tried deleting the venv and reinstalling but the same issue keeps popping up.

**Comment by bmaltais** [comment]
I wonder if you have modules installed outside the venv causing conflicts... The latest version of the app should warn you if it is the case and instruct you on how to uninstall them.

**Comment by farpit** [comment]
> Try deleting the full venv folder and then run .\setup.bat again

it's working know. thanks 😍
