### ISSUE TITLE
Error when trying to train a LoRA

### ISSUE THREAD

**Issue by NoneIQalt** [bmaltais/kohya_ss#89]
`subprocess.CalledProcessError: Command '['C:\\Users\\Myusername\\Desktop\\sd\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/Myusername/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/image', '--resolution=512,512', '--output_dir=C:/Users/Myusername/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/model', '--logging_dir=C:/Users/Myusername/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=MapleLoRA', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=4950', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.`

**Comment by bmaltais** [comment]
I don't see anything obviously wrong with the command that is failing... really not sure why it is not going. It should have written the full command it is executing at the beginning... can you try to copy and paste that in the venv that you use to run the gui?

Does it return a different error?

**Comment by NoneIQalt** [comment]
`Folder 100_Maple Style: 9900 steps
max_train_steps = 4950
stop_text_encoder_training = 0
lr_warmup_steps = 0
accelerate launch --num_cpu_threads_per_process=2 "train_network.py" --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" --train_data_dir="C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/image" --resolution=512,512 --output_dir="C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/model" --logging_dir="C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/log" --network_alpha="128" --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-5 --unet_lr=0.0001 --network_dim=128 --output_name="Addams" --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2" --max_train_steps="4950" --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents --max_data_loader_n_workers="1" --clip_skip=2 --xformers --use_8bit_adam
`

**Comment by NoneIQalt** [comment]
this is the command

**Comment by NoneIQalt** [comment]
This is the full error:
`Traceback (most recent call last):
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\train_network.py", line 538, in <module>
    train(args)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\train_network.py", line 143, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\library\train_util.py", line 1286, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 370, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "C:\Users\Myusername\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Myusername\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\Myusername\Desktop\sd\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\ליאור\\Desktop\\sd\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/image', '--resolution=512,512', '--output_dir=C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/model', '--logging_dir=C:/Users/ליאור/Desktop/sd/Kohya/maple story LoRA/MAPLE STORY LORA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Addams', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=4950', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--xformers', '--use_8bit_adam']' returned non-zero exit status 1.`

**Comment by NoneIQalt** [comment]
> 

Wdym Venv? which one of them?

**Comment by bmaltais** [comment]
I think your nvidia card does not support bf16... try training with fp16 instead. Also, if your card does not support bf16 you will probably need to disable 8bitadam as well.

**Comment by sajmon83** [comment]
Yes it helped. Just had to adjust "Mixed Precision" and "Save Precision" to "FP16" instead of "BF16" and select "AdamW" in the "Optimizer" dropdown instead of "AdamW8bit".

**Comment by LowDelta** [comment]
> Yes it helped. Just had to adjust "Mixed Precision" and "Save Precision" to "FP16" instead of "BF16" and select "AdamW" in the "Optimizer" dropdown instead of "AdamW8bit".

thanks! worked!

**Comment by moodorama** [comment]
I confirm! thank you very much! "AdamW8bit" doesn't work for some reason... But "AdamW" is just right!

**Comment by Danterv52** [comment]
i followed all the step but keep getting this:


running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 7000
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 7000
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 1
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 7000
steps:   0%|                                                                | 0/7000 [00:00<?, ?it/s]
epoch 1/1
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Stable Diffusion\kohya_ss\train_db.py:481 in <module>                                         │
│                                                                                                  │
│   478 │   args = parser.parse_args()                                                             │
│   479 │   args = train_util.read_config_from_file(args, parser)                                  │
│   480 │                                                                                          │
│ ❱ 481 │   train(args)                                                                            │
│   482                                                                                            │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\train_db.py:335 in train                                            │
│                                                                                                  │
│   332 │   │   │   │                                                                              │
│   333 │   │   │   │   loss = loss.mean()  # 平均なのでbatch_sizeで割る必要なし                   │
│   334 │   │   │   │                                                                              │
│ ❱ 335 │   │   │   │   accelerator.backward(loss)                                                 │
│   336 │   │   │   │   if accelerator.sync_gradients and args.max_grad_norm != 0.0:               │
│   337 │   │   │   │   │   if train_text_encoder:                                                 │
│   338 │   │   │   │   │   │   params_to_clip = itertools.chain(unet.parameters(), text_encoder   │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1743 in backward   │
│                                                                                                  │
│   1740 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1741 │   │   │   return                                                                        │
│   1742 │   │   elif self.scaler is not None:                                                     │
│ ❱ 1743 │   │   │   self.scaler.scale(loss).backward(**kwargs)                                    │
│   1744 │   │   else:                                                                             │
│   1745 │   │   │   loss.backward(**kwargs)                                                       │
│   1746                                                                                           │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\torch\_tensor.py:487 in backward             │
│                                                                                                  │
│    484 │   │   │   │   create_graph=create_graph,                                                │
│    485 │   │   │   │   inputs=inputs,                                                            │
│    486 │   │   │   )                                                                             │
│ ❱  487 │   │   torch.autograd.backward(                                                          │
│    488 │   │   │   self, gradient, retain_graph, create_graph, inputs=inputs                     │
│    489 │   │   )                                                                                 │
│    490                                                                                           │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\torch\autograd\__init__.py:200 in backward   │
│                                                                                                  │
│   197 │   # The reason we repeat same the comment below is that                                  │
│   198 │   # some Python versions print out the first line of a multi-line function               │
│   199 │   # calls in the traceback and some print out the last line                              │
│ ❱ 200 │   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the bac   │
│   201 │   │   tensors, grad_tensors_, retain_graph, create_graph, inputs,                        │
│   202 │   │   allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to ru   │
│   203                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 8.00 GiB total capacity;
7.09 GiB already allocated; 0 bytes free; 7.34 GiB reserved in total by PyTorch) If reserved memory is
>> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for
Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                | 0/7000 [00:02<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\dante\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\dante\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in  │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in         │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ C:\Stable Diffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in         │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Stable Diffusion\\kohya_ss\\venv\\Scripts\\python.exe',
'./train_db.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048',
'--pretrained_model_name_or_path=C:/Users/dante/Downloads/realisticVisionV51_v20Novae.safetensors',
'--train_data_dir=C:/Users/dante/OneDrive/Documents/Lora Training Data/Liz Elizondo/Image',
'--resolution=512,512', '--output_dir=C:/Users/dante/OneDrive/Documents/Lora Training Data/Liz
Elizondo/Model', '--logging_dir=C:/Users/dante/OneDrive/Documents/Lora Training Data/Liz
Elizondo/Log', '--save_model_as=safetensors', '--output_name=Liz00', '--lr_scheduler_num_cycles=1',
'--max_data_loader_n_workers=0', '--learning_rate=1e-05', '--lr_scheduler=cosine',
'--lr_warmup_steps=700', '--train_batch_size=1', '--max_train_steps=7000', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW',
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale',
'--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by movchy** [comment]
bonjour a tous, bon j'ai tout suivi a la lettre j'ai changé les paramètres les resultat est le meme error : CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\lucas\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', './sdxl_train_network.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=C:/AI/stable-diffusion-webui/models/Stable-diffusion/photon_v1.safetensors', '--train_data_dir=C:/Users/lucas/Desktop/nouveau/destination\\img', '--reg_data_dir=C:/Users/lucas/Desktop/nouveau/destination\\reg', '--resolution=1024,1024', '--output_dir=C:/Users/lucas/Desktop/nouveau/destination\\model', '--logging_dir=C:/Users/lucas/Desktop/nouveau/destination\\log', '--network_alpha=1', '--training_comment=3 repeats. More info: https://civitai.com/articles/1771', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=5e-05', '--network_dim=256', '--output_name=ludivinnyia', '--lr_scheduler_num_cycles=20', '--no_half_vae', '--learning_rate=5e-05', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=17600', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--optimizer_type=AdamW', '--max_train_epochs=50', '--max_data_loader_n_workers=0', '--caption_dropout_rate=0.05', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Try removing the comment… I have a feeling the comment is not properly escaping the url… just a guess

**Comment by movchy** [comment]
desoler mais je ne comprend pas
