### ISSUE TITLE
Modules installed outside?

### ISSUE THREAD

**Issue by DiggyDre** [bmaltais/kohya_ss#893]
I have absolutely no clue as to what is going on. I keep getting this message and then if I try to continue the installation, the window just closes.  I have attached a screenshot of the window that I see.
![Kohya install](https://github.com/bmaltais/kohya_ss/assets/127576526/4ecad7de-8d3c-4541-a998-7df38a5e7bd4)

**Comment by bmaltais** [comment]
Humm... I might have introduced a logic issue in the setup code that result in this error... Sorry about that... I will fix it today.

**Comment by kkklo** [comment]
I have same issue.

**Comment by bmaltais** [comment]
The latest v21.6.3 fixes the issue. A bit of a bat file logic issue. Fixed now.

**Comment by bmaltais** [comment]
I am reworking how the GUI is installed. I don't like all the questions and answers steps. I think I will split things in two different setup files. One for torch1 and one for torch2. Requirements are different for both so I will also use torch version specific requirements files.

**Comment by SilverRider76** [comment]
just reinstalled now, still having this issue

**Comment by zethfoxster** [comment]
15:43:51-612217 INFO     nVidia toolkit detected
15:43:52-496136 INFO     Torch 2.0.0+cu118
15:43:52-507136 ERROR    Could not load torch: cuDNN version incompatibility: PyTorch was compiled  against (8, 7, 0)
                         but found runtime version (8, 6, 0). PyTorch already comes bundled with cuDNN. One option to
                         resolving this error is to ensure PyTorch can find the bundled cuDNN.

**Comment by bmaltais** [comment]
It is possible you might have python modules installed outside the venv... and this is what it is reporting. There was an issue with previous releases where it would report modules outside the venv even when it was not the case it should be fixed not.

If you have python modules installed outside the venv it it possible they can conflict with the ones in the venv... so this is warning about potential future comflicts and how to uninstall all modules found outside the venv.

**Comment by bmaltais** [comment]
> 15:43:51-612217 INFO nVidia toolkit detected 15:43:52-496136 INFO Torch 2.0.0+cu118 15:43:52-507136 ERROR Could not load torch: cuDNN version incompatibility: PyTorch was compiled against (8, 7, 0) but found runtime version (8, 6, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.

Have you tried deleting the venv folder and do a full re-install?

**Comment by zethfoxster** [comment]
i posted the errors im getting for this above...was working yesterday, i upgraded today to latest version of the gui using the provided upgrade bat...and it gave me this error...nothing else on my end changed. ill delete the venv and see what happens

**Comment by SilverRider76** [comment]
> It is possible you might have python modules installed outside the venv... and this is what it is reporting. There was an issue with previous releases where it would report modules outside the venv even when it was not the case it should be fixed not.
> 
> If you have python modules installed outside the venv it it possible they can conflict with the ones in the venv... so this is warning about potential future comflicts and how to uninstall all modules found outside the venv.

I've already try uninstall and reinstall (like told the script)

I've try a clean installI've altro try the dev one .

Also the same problem

**Comment by zethfoxster** [comment]
delete venv folder, ran the setup.bat...it reinstalled everything from the venv...now it opens again for me.

**Comment by SilverRider76** [comment]
> delete venv folder, ran the setup.bat...it reinstalled everything from the venv...now it opens again for me.

Thank you, I'll try tomorrow.

**Comment by zethfoxster** [comment]
> > 15:43:51-612217 INFO nVidia toolkit detected 15:43:52-496136 INFO Torch 2.0.0+cu118 15:43:52-507136 ERROR Could not load torch: cuDNN version incompatibility: PyTorch was compiled against (8, 7, 0) but found runtime version (8, 6, 0). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.
> 
> Have you tried deleting the venv folder and do a full re-install?

this worked for me. deleted venv folder, ran setup.bat...anwsered the questions again as normal...started right up and im running a training now.

**Comment by SilverRider76** [comment]
Just tryied... also deleting Feng and setup again... Same problem

**Comment by bmaltais** [comment]
> Just tryied... also deleting Feng and setup again... Same problem

Have you pulled the latest release? Try running option 0 to clean the venv. Do you get a warning about modules installed outside the venv?

**Comment by SilverRider76** [comment]
I've again do a fresh install, now it works!
