### ISSUE TITLE
Could not load torch

### ISSUE THREAD

**Issue by Aresisok** [bmaltais/kohya_ss#898]
![Screenshot_56](https://github.com/bmaltais/kohya_ss/assets/132152388/90c34059-a0bf-4f37-93e5-4e17c3c68b82)
when i run the gui.bat it shows this error then closes

**Comment by Aresisok** [comment]
ok it working now for some reason

**Comment by Talles2222** [comment]
I have the exact same problem but it hasn't resolved itself yet.
