### ISSUE TITLE
Dreambooth LoRA not giving same results anymore 

### ISSUE THREAD

**Issue by zaaz321** [bmaltais/kohya_ss#901]
Dreambooth LoRa training is making vastly different lora models compared to 2 days ago.

dataset and settings are the exact same.

**Comment by bmaltais** [comment]
No sure why that would be. Kohya keep updating his code so it is possible it come from there. You can always go back to a previously known to work release with

git checkout releasename

**Comment by zaaz321** [comment]
> I have tried the previous releases and still same issue

I've tried v21.6.0 and v21.5.14

**Comment by bmaltais** [comment]
If the previous release is also showing the issue then it is most likely something else that changed on your system... Like a driver update.

**Comment by zaaz321** [comment]
it does not seem like a driver update

I have tried on different systems and can confirm that training quality is down for some reason

Runpod and local system are giving same results 

Training was perfectly fine a couple of days ago

**Comment by bmaltais** [comment]
BEst is to go back to what worked for you. Probably caused by code update in kohya_ss sd-scripts. Not much I can do as I keep the repo aligned with kohya's code base.
