### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by ToneC137** [bmaltais/kohya_ss#902]
after update, unable to create captions or train models. get following message

CalledProcessError: Command '['D:\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe'

**Comment by bmaltais** [comment]
What release is this? I have not checked captioning but I checked training DB, TI, LoRA and fine-tune and they all work with my last release.

Can you provide more details?

**Comment by ToneC137** [comment]
> What release is this? I have not checked captioning but I checked training DB, TI, LoRA and fine-tune and they all work with my last release.
> 
> Can you provide more details?
the exact issue another user, he provides more detail
https://github.com/bmaltais/kohya_ss/issues/904
