### ISSUE TITLE
After update training is not working

### ISSUE THREAD

**Issue by dtxn** [bmaltais/kohya_ss#908]
Hi, after update training stopped working. I just load random older configuration files, press train and get this message:
![image](https://github.com/bmaltais/kohya_ss/assets/132169795/77b7c386-789e-4914-8597-824d51ec03b9)

**Comment by bmaltais** [comment]
One fix is to delete the venv and reinstall. I am currently rewriting the whole setup in Python for better handling. It should reduce the risk of update issues in the future.

**Comment by sumirecccp** [comment]
#904
