### ISSUE TITLE
Could not load torch: No module named 'torch'

### ISSUE THREAD

**Issue by botduster** [bmaltais/kohya_ss#917]
I get this error when I try to install kohya_ss gui after the intial menu.

Kohya_ss GUI setup menu:

0. Cleanup the venv
1. Install kohya_ss gui [torch 1]
2. Install kohya_ss gui [torch 2]
3. Start Kohya_ss GUI in browser
4. Quit

Enter your choice: 1

Be patient, this can take quite some time to complete...

23:13:07-437191 INFO     Python 3.10.9 on Windows
23:13:07-455170 INFO     nVidia toolkit detected
23:13:07-458163 ERROR    Could not load torch: No module named 'torch'

I have the torch module installed locally so I don't know what the issue is.

Any help would be greatly appreciated, thanks

**Comment by bmaltais** [comment]
Sound like the setup is unable to find the module. Is is just reporting the error and continuing?

**Comment by bmaltais** [comment]
I will update the code to not report on it during setup as it can be missleading... since when you 1st run the setup there is no torch installed... so no point in telling users.

**Comment by tkittich** [comment]
I got the same error as OP's on release v21.7.3 and v21.7.2 . setup.bat in Release v21.7.1 does work fine without any error.

**Comment by bmaltais** [comment]
> I got the same error as OP's on release v21.7.3 and v21.7.2 . setup.bat in Release v21.7.1 does work fine without any error.

The code logic was changed between those release... Is it failing the install or just reporting it for you?

**Comment by bmaltais** [comment]
@tkittich Try downloading the latest release. It should fix this issue.

**Comment by tkittich** [comment]
> @tkittich Try downloading the latest release. It should fix this issue.

The latest release fixed the setup.bat problem. Thanks a lot. ^^

**Comment by botduster** [comment]
Yes it would fail to install after that, but I just tried the new update and it works, thanks!

**Comment by leonyp** [comment]
I'm getting same error

**Comment by Ehtz** [comment]
I had the same problem even with cloning the new koya repo.
What fixed it for me was to clone the repo and in the setup, make sure to press 1 so it can download localy the missing files.

**1. Install kohya_ss gui**
2. (Optional) Install cudann files (avoid unless you really need it)
3. (Optional) Install specific bitsandbytes versions
4. (Optional) Manually configure accelerate
5. (Optional) Start Kohya_ss GUI in browser
6. Quit

After pressing 1 and files downloaded, restart the setup file and koya opened

**Comment by filipemeneses** [comment]
Had this issue because I was running on a conda environment, kohya was using the wrong accelerate, to solve it I forced a install to update the path:

```sh
conda activate myenv
pip install accelerate==0.25.0 --force-reinstall --no-deps
```
