### ISSUE TITLE
Dreambooth LoRA not work

### ISSUE THREAD

**Issue by caomfan** [bmaltais/kohya_ss#919]
```
WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.                     redirects.py:27
```
The program runs on windows server 2016
When I press the Train button, the console displays this warning, and then nothing happens.

**Comment by bmaltais** [comment]
What warning does it display? Not sure if windows server work to run the GUI as I have never tested it.

**Comment by caomfan** [comment]
[https://github.com/microsoft/DeepSpeed/issues/2492](url)
As with this issue, I suspect the DeepSpeed module is the cause
