### ISSUE TITLE
MacBook Pro M1 not work；Any plan？

### ISSUE THREAD

**Issue by faithgithub** [bmaltais/kohya_ss#924]
Dear @bmaltais  ：
     Thank you for your hard work; I think it's a great training tool; I'm already running it on windows; But I still want to run it on my own MacBook. According to my review of the Issues; I find that most mac users have the same problem as me. I wonder if the community has any plans for this? Or if a user has posted some fixes; I can test it with you. Hopefully this will work on the mac

My environment：
Mac OS 13；MacBook pro 14 m1
Python 3.10 

When click  button ’Train model‘ or ’Print training command‘;The program just exited
The error like：

To create a public link, set `share=True` in `launch()`.
21:25:22-112909 INFO     Start training LoRA Standard ...                                                                                                                            
2023-06-05 21:25:22.261 python[6495:3509558] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000018c7a03e8 __exceptionPreprocess + 176
        1   libobjc.A.dylib                     0x000000018c2eaea8 objc_exception_throw + 60
        2   CoreFoundation                      0x000000018c7c9800 _CFBundleGetValueForInfoKey + 0
        3   AppKit                              0x000000018f9cc65c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 320
        4   AppKit                              0x000000018f9ba94c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 816
        5   AppKit                              0x000000018f9ba610 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 48
        6   libtk8.6.dylib                      0x00000001410fd91c TkMacOSXMakeRealWindowExist + 564
        7   libtk8.6.dylib                      0x00000001410fd568 TkWmMapWindow + 76
        8   libtk8.6.dylib                      0x0000000141052408 Tk_MapWindow + 168
        9   libtk8.6.dylib                      0x000000014105b1a0 MapFrame + 76
        10  libtcl8.6.dylib                     0x0000000140f80e6c TclServiceIdle + 88
        11  libtcl8.6.dylib                     0x0000000140f61998 Tcl_DoOneEvent + 120
        12  libtk8.6.dylib                      0x00000001410ef1d4 TkpInit + 800
        13  libtk8.6.dylib                      0x0000000141053ad8 Initialize + 2432
        14  _tkinter.cpython-310-darwin.so      0x00000001402e60a4 Tkapp_New + 876
        15  _tkinter.cpython-310-darwin.so      0x00000001402e5ac8 _tkinter_create + 596
        16  python3.10                          0x00000001020d9624 cfunction_vectorcall_FASTCALL + 200
        17  python3.10                          0x0000000102174d4c call_function + 524
        18  python3.10                          0x0000000102170adc _PyEval_EvalFrameDefault + 26388
        19  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        20  python3.10                          0x0000000102086094 _PyObject_FastCallDictTstate + 320
        21  python3.10                          0x0000000102086c8c _PyObject_Call_Prepend + 164
        22  python3.10                          0x00000001020fd1a4 slot_tp_init + 116
        23  python3.10                          0x00000001020f5ad8 type_call + 340
        24  python3.10                          0x0000000102085de0 _PyObject_MakeTpCall + 612
        25  python3.10                          0x0000000102174de4 call_function + 676
        26  python3.10                          0x0000000102170adc _PyEval_EvalFrameDefault + 26388
        27  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        28  python3.10                          0x0000000102086094 _PyObject_FastCallDictTstate + 320
        29  python3.10                          0x0000000102086c8c _PyObject_Call_Prepend + 164
        30  python3.10                          0x00000001020fd1a4 slot_tp_init + 116
        31  python3.10                          0x00000001020f5ad8 type_call + 340
        32  python3.10                          0x0000000102085de0 _PyObject_MakeTpCall + 612
        33  python3.10                          0x0000000102174de4 call_function + 676
        34  python3.10                          0x0000000102170b4c _PyEval_EvalFrameDefault + 26500
        35  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        36  python3.10                          0x0000000102085ff0 _PyObject_FastCallDictTstate + 156
        37  python3.10                          0x0000000102086c8c _PyObject_Call_Prepend + 164
        38  python3.10                          0x00000001020fd1a4 slot_tp_init + 116
        39  python3.10                          0x00000001020f5ad8 type_call + 340
        40  python3.10                          0x0000000102085de0 _PyObject_MakeTpCall + 612
        41  python3.10                          0x0000000102174de4 call_function + 676
        42  python3.10                          0x0000000102170bbc _PyEval_EvalFrameDefault + 26612
        43  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        44  python3.10                          0x0000000102174d4c call_function + 524
        45  python3.10                          0x0000000102170bbc _PyEval_EvalFrameDefault + 26612
        46  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        47  python3.10                          0x0000000102174d4c call_function + 524
        48  python3.10                          0x0000000102170bbc _PyEval_EvalFrameDefault + 26612
        49  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        50  python3.10                          0x0000000102174d4c call_function + 524
        51  python3.10                          0x0000000102170bbc _PyEval_EvalFrameDefault + 26612
        52  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        53  python3.10                          0x000000010218d87c context_run + 348
        54  python3.10                          0x00000001020d94e8 cfunction_vectorcall_FASTCALL_KEYWORDS + 112
        55  python3.10                          0x0000000102170e54 _PyEval_EvalFrameDefault + 27276
        56  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        57  python3.10                          0x0000000102174d4c call_function + 524
        58  python3.10                          0x0000000102170ab4 _PyEval_EvalFrameDefault + 26348
        59  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        60  python3.10                          0x0000000102174d4c call_function + 524
        61  python3.10                          0x0000000102170ab4 _PyEval_EvalFrameDefault + 26348
        62  python3.10                          0x0000000102169ad0 _PyEval_Vector + 2056
        63  python3.10                          0x0000000102089544 method_vectorcall + 336
        64  python3.10                          0x000000010223cd98 thread_run + 180
        65  python3.10                          0x00000001021d8144 pythread_wrapper + 48
        66  libsystem_pthread.dylib             0x000000018c64606c _pthread_start + 148
        67  libsystem_pthread.dylib             0x000000018c640e2c thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException

**Comment by faithgithub** [comment]
> Try running it with the `--headless` parameter... should take care of those errors.

All works！ Thanks~ By the way；How to becaome a contributor？

**Comment by bmaltais** [comment]
If you want to contribute code updates you simply need to use a github fork, make the change and then submit a pull request from your github form back into this repo: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by andupotorac** [comment]
> > Try running it with the `--headless` parameter... should take care of those errors.
> 
> All works！ Thanks~ By the way；How to becaome a contributor？

I'm getting the same error (oddly it was working perfectly last week). How did you run it with the --headless parameter so that it works?
