### ISSUE TITLE
Docker installation Linux system requirement

### ISSUE THREAD

**Issue by yqyqyq-W** [bmaltais/kohya_ss#926]
The base image `nvcr.io/nvidia/pytorch:23.04-py3` uses cuda 12 with Nvidia driver >= 530.30. I am using a linux server with cuda 11.4 and Nvidia driver 470.42. I find that `nvcr.io/nvidia/pytorch:21.07-py3` fits my system. So would there be a problem if I switch to lower version? If I can't switch, does that mean the minimum system requirement is cuda 12 with driver >= 530.30?

**Comment by Trojaner** [comment]
You should be able to switch to a lower version without issues
