### ISSUE TITLE
Lora training not reading caption files

### ISSUE THREAD

**Issue by Byron-Zoomry** [bmaltais/kohya_ss#927]
I've noticed the last few Lora's I've tried to train don't seem to learn my characters or styles. When I compare it to past Lora's that did, when I click the Lora info button in Auto1111 gui, I notice that there's no list of captions, whereas the last ones do have those. So it seems that Kohya is not reading the txt files and that's why it's not learning? not sure, anyone else having trouble with training notice this?

**Comment by bmaltais** [comment]
Are you specifying the caption extension as .txt in the gui? The default in kohya's software is .caption

**Comment by Byron-Zoomry** [comment]
this was 100% it, thank you!

**Comment by FinFanFin** [comment]
> Are you specifying the caption extension as .txt in the gui? The default in kohya's software is .caption

I've found the problem.

**Comment by Pinkmoth419** [comment]
I've been having the same issue and haven't been able to fix it despite troubleshooting for about 4 hours. Has anyone found a workable solution?
