### ISSUE TITLE
I have errors when training a lora model 

### ISSUE THREAD

**Issue by IstheChosen** [bmaltais/kohya_ss#931]
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ryosu\OneDrive\Documents\Kohya SS\kohya_ss\train_network.py:864 in <module>             │
│                                                                                                  │
│   861 │   args = parser.parse_args()                                                             │
│   862 │   args = train_util.read_config_from_file(args, parser)                                  │
│   863 │                                                                                          │
│ ❱ 864 │   train(args)                                                                            │
│   865                                                                                            │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya SS\kohya_ss\train_network.py:253 in train                │
│                                                                                                  │
│   250 │   │   )                                                                                  │
│   251 │   │   trainable_params = network.prepare_optimizer_params(args.text_encoder_lr, args.u   │
│   252 │                                                                                          │
│ ❱ 253 │   optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable   │
│   254 │                                                                                          │
│   255 │   # dataloaderを準備する                                                                 │
│   256 │   # DataLoaderのプロセス数：0はメインプロセスになる                                      │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya SS\kohya_ss\library\train_util.py:2623 in get_optimizer  │
│                                                                                                  │
│   2620 │                                                                                         │
│   2621 │   if optimizer_type == "AdamW8bit".lower():                                             │
│   2622 │   │   try:                                                                              │
│ ❱ 2623 │   │   │   import bitsandbytes as bnb                                                    │
│   2624 │   │   except ImportError:                                                               │
│   2625 │   │   │   raise ImportError("No bitsand bytes / bitsandbytesがインストールされていない  │
│   2626 │   │   print(f"use 8-bit AdamW optimizer | {optimizer_kwargs}")                          │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py:6 in <module>                        │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py:5 in <module>             │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ ❱   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py:13 in <module>                     │
│                                                                                                  │
│     10 from typing import Tuple                                                                  │
│     11 from torch import Tensor                                                                  │
│     12                                                                                           │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     14 from functools import reduce  # Required in Python 3                                      │
│     15                                                                                           │
│     16 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:41 in <module>                     │
│                                                                                                  │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                                              │
│   42 try:                                                                                        │
│   43 │   lib.cadam32bit_g32                                                                      │
│   44 │   lib.get_context.restype = ct.c_void_p                                                   │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:37 in get_instance                 │
│                                                                                                  │
│   34 │   def get_instance(cls):                                                                  │
│   35 │   │   if cls._instance is None:                                                           │
│   36 │   │   │   cls._instance = cls.__new__(cls)                                                │
│ ❱ 37 │   │   │   cls._instance.initialize()                                                      │
│   38 │   │   return cls._instance                                                                │
│   39                                                                                             │
│   40                                                                                             │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py:31 in initialize                   │
│                                                                                                  │
│   28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   29 │   │   else:                                                                               │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")                           │
│ ❱ 31 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                                     │
│   32 │                                                                                           │
│   33 │   @classmethod                                                                            │
│   34 │   def get_instance(cls):                                                                  │
│                                                                                                  │
│ C:\Users\ryosu\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:452 in LoadLibrary │
│                                                                                                  │
│   449 │   │   return getattr(self, name)                                                         │
│   450 │                                                                                          │
│   451 │   def LoadLibrary(self, name):                                                           │
│ ❱ 452 │   │   return self._dlltype(name)                                                         │
│   453 │                                                                                          │
│   454 │   __class_getitem__ = classmethod(_types.GenericAlias)                                   │
│   455                                                                                            │
│                                                                                                  │
│ C:\Users\ryosu\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py:364 in __init__    │
│                                                                                                  │
│   361 │   │   │   else:                                                                          │
│   362 │   │   │   │   import nt                                                                  │
│   363 │   │   │   │   mode = nt._LOAD_LIBRARY_SEARCH_DEFAULT_DIRS                                │
│ ❱ 364 │   │   │   │   if '/' in name or '\\' in name:                                            │
│   365 │   │   │   │   │   self._name = nt._getfullpathname(self._name)                           │
│   366 │   │   │   │   │   mode |= nt._LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR                           │
│   367                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: argument of type 'WindowsPath' is not iterable
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\ryosu\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\ryosu\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:1104 in launch_command          │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ C:\Users\ryosu\OneDrive\Documents\Kohya                                                          │
│ SS\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:567 in simple_launcher          │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['C:\\Users\\ryosu\\OneDrive\\Documents\\Kohya SS\\kohya_ss\\venv\\Scripts\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=C:/Users/ryosu/OneDrive/Documents/SD/stable-diffusion-webui/models/Stable-diffusion/3moonNIReal_3moonNIRealV2.safetensors', '--train_data_dir=C:\\Users\\ryosu\\OneDrive\\Documents\\Lora Training Data\\Nuin
Azahari2\\image', '--resolution=512,512', '--output_dir=C:\\Users\\ryosu\\OneDrive\\Documents\\Lora Training Data\\Nuin
Azahari2\\model', '--logging_dir=C:\\Users\\ryosu\\OneDrive\\Documents\\Lora Training Data\\Nuin Azahari2\\log',
'--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05',
'--unet_lr=0.0001', '--network_dim=8', '--output_name=Nuin_Azahari2.0', '--lr_scheduler_num_cycles=1',
'--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=500', '--train_batch_size=1',
'--max_train_steps=5000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16',
'--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64',
'--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by IstheChosen** [comment]
Help is appreciated. I am wondering why I have errors when creating lora model. Please teach me step by step as a beginner on how to solve this issue.  Thanks

**Comment by bmaltais** [comment]
What happen if you run the command manually with `'C:\Users\ryosu\OneDrive\Documents\Kohya SS\kohya_ss\venv\Scripts\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=C:/Users/ryosu/OneDrive/Documents/SD/stable-diffusion-webui/models/Stable-diffusion/3moonNIReal_3moonNIRealV2.safetensors', '--train_data_dir=C:\Users\ryosu\OneDrive\Documents\Lora Training Data\Nuin
Azahari2\image', '--resolution=512,512', '--output_dir=C:\Users\ryosu\OneDrive\Documents\Lora Training Data\Nuin
Azahari2\model', '--logging_dir=C:\Users\ryosu\OneDrive\Documents\Lora Training Data\Nuin Azahari2\log',
'--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05',
'--unet_lr=0.0001', '--network_dim=8', '--output_name=Nuin_Azahari2.0', '--lr_scheduler_num_cycles=1',
'--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=500', '--train_batch_size=1',
'--max_train_steps=5000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16',
'--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64',
'--xformers', '--bucket_no_upscale'`

If it fail then it is probably an issue with kohya_ss code...

**Comment by IstheChosen** [comment]
> What happen if you run the command that is shown when the training start...
> 
> If it fail then it is probably an issue with kohya_ss code...
it shows this 
![image](https://github.com/bmaltais/kohya_ss/assets/127720145/9039452b-87cd-4e5f-952c-a541ec49cc95)

**Comment by bmaltais** [comment]
So running that accelerate launch command manually goves the same error? It can either be a bug with kohya_ss code, an issue with the version of Torch you use (kohya_ss only officially support Torch 1... so you might want to install that to be sure it is kohya_ss software) and lastly something is not right with your dataset or with some combination of settings.

Not easy to troubleshoot. I would try installing torch1 1st... then perhaps try a simple dataset with only a few parameters tuned. Then is that work start changing more things until you find the one that make it fail.

**Comment by IstheChosen** [comment]
how to check the torch that i use for kohya ? I also updated my web ui to latest one which is this 
![image](https://github.com/bmaltais/kohya_ss/assets/127720145/0e849c2a-d3f0-4914-abcc-9689b38754a7)

So what am i suppose to do now ?

**Comment by IstheChosen** [comment]
![image](https://github.com/bmaltais/kohya_ss/assets/127720145/aaa2ac1d-98ce-4d68-a874-1378d4a804c9)
Also here is the version in my kohya please reply ASAP
