### ISSUE TITLE
Missing Triton from new Installer for Torch 2

### ISSUE THREAD

**Issue by rushuna86** [bmaltais/kohya_ss#934]
As per Title Torch 2 install missing triton.

**Comment by bmaltais** [comment]
It is not missing. There is no triton module available for torch 2.0.1. The only triton module is for torch 2.0.0 and that version no longer work with some recent modules. There is only an error message but no actual side effect

**Comment by aearone** [comment]
> ohhh i see, i just command to force install the older triton just to get rid of the error it was annoying.

How did you do that? If I understood correctly, you opened cmd in vevn folder in kohya_ss and entered command "`activate`" and then entered `-m pip install triton-2.0.0-cp310-cp310-win_amd64.whl`? Can you share exactly what I need to do to install triton.

**Comment by rushuna86** [comment]
yes exactly

**Comment by Hurricane190** [comment]
> yes exactly

Sorry, new to this. How do you open cmd in the venv folder?
