### ISSUE TITLE
run setup.bat Error,Still stuck in step three,Date 2023.6.6

### ISSUE THREAD

**Issue by BingcaiOfficial** [bmaltais/kohya_ss#938]
Do you have a new version of the usage document? I think these issues are very tricky
when I install and use kohya_ss,there is the problem:
1.select menu 1,then choice 2,warming
![image](https://github.com/bmaltais/kohya_ss/assets/135701214/02c99cda-19c8-40a9-b580-fbe1cfa9e1b4)
2.select menu 2,error
![image](https://github.com/bmaltais/kohya_ss/assets/135701214/bfa16ae8-7970-4064-a2ee-cf0143a03023)
3.select menu 3,module could not found
![image](https://github.com/bmaltais/kohya_ss/assets/135701214/b7517dea-fcbf-4664-829a-9e7dcc809638)
4.select menu 4,Could not load torch:
 Error loading
"D:\openai.wiki\kohya_ss\venv\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of
 its dependencies.

Do you have a new version of the usage document? I think the above issues are very tricky

**Comment by BingcaiOfficial** [comment]
1.close -- powershell ,remove and reinstall

**Comment by BingcaiOfficial** [comment]
1.close -- powershell ,remove and reinstall

**Comment by BingcaiOfficial** [comment]
1.powershell run:
pip freeze > uninstall.txt
pip uninstall -r uninstall.txt

**Comment by BingcaiOfficial** [comment]
2.read the document and install cuddn.zip and remove to this floder"kohya_ss", then choice 2,success

**Comment by BingcaiOfficial** [comment]
After install CUDA tooltik,Cudnn,Zlib, Above error change:OSError: [WinError 193]% 1 is not a valid Win32 application. 
I still didn't resolve all problem today.
![image](https://github.com/bmaltais/kohya_ss/assets/135701214/a12e8e9a-ed05-4b05-b15c-62c71facc7e9)

To solve problem 3, I try install evns like https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows:
1.[Installing the CUDA Toolkit for Windows] (But I didn't have folder name 'C:/NVIDIA',so confus)
2.Installing Cuda Toolkit
 - https://developer.nvidia.com/cuda-downloads
 - Visual Studio 2022
3.installing Cudnn
 - https://developer.nvidia.com/rdp/cudnn-download
4. installing Zlib
 - https://www.dllme.com/getfile.php?file=38308&id=9b45296e316cdf31b9bace739e22ca7a
 - copy bin|include|lib folder to "CUDA folder" and "torch folder" because I didn't have folder name 'C:/NVIDIA'
 - add Path

**Comment by bmaltais** [comment]
I think you have torch 1 installed before and are installing torch 2 on to. Delete the venv and redo the installation with the torch version desired.

This should straighten things up.

Also, no need to manually configure accelerate unless you really need to.

**Comment by BingcaiOfficial** [comment]
> I think you had torch 1 installed before and are installing torch 2 on top. Delete the venv and redo the installation with the torch version desired.
> 
> This should straighten things up.
> 
> Also, no need to manually configure accelerate unless you really need to.

Thanks. if I didn't resolve the problem, I can't choice 4 to "Start Kohya_ss GUI in browser",the same error like I choice 3.If I can't start it,how can I use "Kohya" to training model like Lora?

**Comment by BingcaiOfficial** [comment]
finally It works:
- CMD Run: pip freeze > uninstall.txt    pip uninstall -r uninstall.txt
- Delete the venv
- copy cudnn_windows to root
- CMD Run:.\setup.bat.choice1:then 2,download torch2.0 success.In here choice 4 ,the service start sucess!
- Extral: Cuddn configure accelerate, choice 2,install success.then choice 3, 'Enter' default,inner 'no','all',config success.Start success

**Comment by BingcaiOfficial** [comment]
> I think you had torch 1 installed before and are installing torch 2 on top. Delete the venv and redo the installation with the torch version desired.
> 
> This should straighten things up.
> 
> Also, no need to manually configure accelerate unless you really need to.

Thanks,It works after I try to delete venv
