### ISSUE TITLE
How do I run this while offline? 

### ISSUE THREAD

**Issue by RandomInternetPreson** [bmaltais/kohya_ss#94]
I've got the base models downloaded and can train a Lora, but I can only do it while connected to the internet.  There are no additional data downloaded while I'm connected to the internet though.

**Comment by Odawgthat** [comment]
How did you get the commands to work???

**Comment by RandomInternetPreson** [comment]
I'm not sure what you mean, I followed these instructions and everything worked fine.
https://www.youtube.com/watch?v=70H03cv57-o

**Comment by RandomInternetPreson** [comment]
I think I asked this in the wrong place, sorry.
