### ISSUE TITLE
TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'tpu_env'

### ISSUE THREAD

**Issue by skydam** [bmaltais/kohya_ss#942]
Did a clean Windows installation. The GUI starts up as expected, but when I start training, this message appears: TypeError: ClusterConfig.__init__() got an unexpected keyword argument 'tpu_env'
<img width="563" alt="CleanShot 2023-06-06 at 21 03 23@2x" src="https://github.com/bmaltais/kohya_ss/assets/73529516/2abf1fa1-dee6-4a30-985e-514c4e7e8efb">

**Comment by MrAdamBlack** [comment]
> try running `setup.bat` and then select `3. Manually configure accelerate`.
> 
> Shooting in the dark but can only help.

This worked for me (Linux though).
https://pypi.org/project/accelerate/

then in the venv:

accelerate config

**Comment by scooller** [comment]
Worked 4 me too in win11 RTX3060
