### ISSUE TITLE
rl-diffusion training

### ISSUE THREAD

**Issue by nicolai256** [bmaltais/kohya_ss#946]
any chance you could implement this?
https://github.com/vinhkhuc/ddpo/tree/support_gpu
it's for RLHF type of stuff, [check the paper ](https://rl-diffusion.github.io/)
could be really interesting for lora and finetuning

**Comment by bmaltais** [comment]
You should bring this directly with the sd-scripts author, kohya_ss on his repo: https://github.com/kohya-ss/sd-scripts/issues

I only create the GUI wrapper around his code.
