### ISSUE TITLE
Feature Request:  "Print Training Command" in Dreambooth Tab

### ISSUE THREAD

**Issue by quid246** [bmaltais/kohya_ss#949]
The button for "Print Training Command" exists in the Dreambooth LoRA tab, but not in the Dreambooth or Dreambooth TI tabs.

The button is useful to preview the training command, especially the number of steps.  Without it in the other tabs, I have to click on train and then terminate the batch file and relaunch the GUI if I don't see something I like.

As such, would request this tab be replicated in all training modes.

**Comment by bmaltais** [comment]
Hi, Sure, I can certainly add it there. I will put that in the next release.

**Comment by bmaltais** [comment]
Feature implemented.

**Comment by quid246** [comment]
Thanks for the quick implementation... and great software.

Cheers from Toronto!
