### ISSUE TITLE
DAdaptation not working

### ISSUE THREAD

**Issue by zaaz321** [bmaltais/kohya_ss#950]
DAdaptation is not working or is there something that need to be done to make it work?

**Comment by bmaltais** [comment]
Make sure to use 1 for all Learning Rates. I should work with that... unless there is a bug I have not seen...

**Comment by Oggelboggel** [comment]
> DAdaptation is not working or is there something that need to be done to make it work?

Haven't found the time to play around with it myself, but friend sent me a link to this guide that seems to advocate setting extra optimizer arguments and additional parameters:
https://rentry.org/LazyDAdaptationGuide

**Comment by sumire608** [comment]
DAdaptation works not well with Dylora currently, I can confirm. Use it on lora/locon now.
