### ISSUE TITLE
Keep getting resolution error today

### ISSUE THREAD

**Issue by KingsLukeSmith** [bmaltais/kohya_ss#952]
Any idea how to fix? The resolution is set at 768,768 but it says no resolution is given. Tried other resolutions - it's worked before, but latest update seems to not like my saved config, but not sure what to change to fix it. 

22:38:04-726388 INFO     Start training LoRA Standard ...
22:38:04-727387 INFO     Folder 5_superDFX: 50 images found
22:38:04-728389 INFO     Folder 5_superDFX: 250 steps
22:38:04-729386 INFO     Total steps: 250
22:38:04-730386 INFO     Train batch size: 1
22:38:04-731386 INFO     Gradient accumulation steps: 1
22:38:04-731386 INFO     Epoch: 6
22:38:04-732386 INFO     Regulatization factor: 1
22:38:04-733386 INFO     max_train_steps (250 / 1 / 1 * 6 * 1) = 1500
22:38:04-734386 INFO     stop_text_encoder_training = 0
22:38:04-735386 INFO     lr_warmup_steps = 0
22:38:04-736386 INFO     accelerate launch --num_cpu_threads_per_process=2 "train_network.py"
                         --pretrained_model_name_or_path="D:/ai/models/photon_v1.safetensors"
                         --train_data_dir="d:\ai\train\images\" --resolution=768,768 --output_dir="d:\ai\train\output"
                         --logging_dir="d:\ai\train\logs" --network_alpha="128" --save_model_as=safetensors
                         --network_module=networks.lora --text_encoder_lr=5e-05 --unet_lr=0.0001 --network_dim=128
                         --output_name="superDFX" --lr_scheduler_num_cycles="6" --learning_rate="0.0001"
                         --lr_scheduler="constant" --train_batch_size="1" --max_train_steps="1500"
                         --save_every_n_epochs="1" --mixed_precision="bf16" --save_precision="bf16" --seed="1234"
                         --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit"
                         --max_data_loader_n_workers="1" --clip_skip=2 --bucket_reso_steps=64 --xformers
                         --bucket_no_upscale
prepare tokenizer
Using DreamBooth method.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\ai\kohya_ss\train_network.py:864 in <module>                                                  │
│                                                                                                  │
│   861 │   args = parser.parse_args()                                                             │
│   862 │   args = train_util.read_config_from_file(args, parser)                                  │
│   863 │                                                                                          │
│ ❱ 864 │   train(args)                                                                            │
│   865                                                                                            │
│                                                                                                  │
│ D:\ai\kohya_ss\train_network.py:130 in train                                                     │
│                                                                                                  │
│   127 │   │   │   }                                                                              │
│   128 │                                                                                          │
│   129 │   blueprint = blueprint_generator.generate(user_config, args, tokenizer=tokenizer)       │
│ ❱ 130 │   train_dataset_group = config_util.generate_dataset_group_by_blueprint(blueprint.data   │
│   131 │                                                                                          │
│   132 │   current_epoch = Value("i", 0)                                                          │
│   133 │   current_step = Value("i", 0)                                                           │
│                                                                                                  │
│ D:\ai\kohya_ss\library\config_util.py:375 in generate_dataset_group_by_blueprint                 │
│                                                                                                  │
│   372 │     dataset_klass = FineTuningDataset                                                    │
│   373 │                                                                                          │
│   374 │   subsets = [subset_klass(**asdict(subset_blueprint.params)) for subset_blueprint in d   │
│ ❱ 375 │   dataset = dataset_klass(subsets=subsets, **asdict(dataset_blueprint.params))           │
│   376 │   datasets.append(dataset)                                                               │
│   377                                                                                            │
│   378   # print info                                                                             │
│                                                                                                  │
│ D:\ai\kohya_ss\library\train_util.py:1028 in __init__                                            │
│                                                                                                  │
│   1025 │   ) -> None:                                                                            │
│   1026 │   │   super().__init__(tokenizer, max_token_length, resolution, debug_dataset)          │
│   1027 │   │                                                                                     │
│ ❱ 1028 │   │   assert resolution is not None, f"resolution is required / resolution（解像度）指  │
│   1029 │   │                                                                                     │
│   1030 │   │   self.batch_size = batch_size                                                      │
│   1031 │   │   self.size = min(self.width, self.height)  # 短いほう                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: resolution is required / resolution（解像度）指定は必須です

**Comment by bmaltais** [comment]
Hummm... I see there are no " around the resolution... might be an issue with the gui... let me check this

**Comment by bmaltais** [comment]
Nah... it has always been like that... Not sure why your old config will not load... Might have to recreate it. I will test a DB on my side to confirm I don't have any issue with the resolution.

**Comment by bmaltais** [comment]
Just tried training a DB and it worked fine with 768,768 as the resolution... no idea why it is failing like that. Have you pulled the latest version recently? Don't think it is related but who knows.

**Comment by KingsLukeSmith** [comment]
My old config won't work, even if I change the resolution and retype it, but running a new empty config and putting my settings in again did work. Strange. Thanks for help.

**Comment by VeMeth** [comment]
This might not just be a config file issue. I create a new config file and typed everything by hand. But it's still missing the "" for the resolution. I check the newly created config file and it's there with ""

`  "output_dir": "C:\\Users\\User\\Pictures\\40k-Style\\Training\\V2\\model",
  "max_resolution": "512,512",
  "learning_rate": 0.0001,`

Output shows the same problem with no "" around the resolution. Did a git pull 10 minutes ago, CTRL-F5 for a full reload.

**Comment by VeMeth** [comment]
Ok I finally found the error... it's a bit tricky...

so the parameter right before the resolution is a directory path, if you end that directory path under windows with something like "C:\Training\img\" the last \ will escape the " and then invalidate the whole --resolution parameter which will now be seen as text until the next ". 

Maybe for input validation remove all \ at the end of directory paths to prevent more such weird errors.
