### ISSUE TITLE
RuntimeError: Setting different lr values in different parameter groups is only supported for values of 0

### ISSUE THREAD

**Issue by zhixideyu** [bmaltais/kohya_ss#953]
![image](https://github.com/bmaltais/kohya_ss/assets/39975240/b305e2d9-eeed-4420-917b-5702ac2cdeb8)
As a newcomer, how can I solve this problem

**Comment by bmaltais** [comment]
what LR are you using? DB ot LoRA?

**Comment by sd2530615** [comment]
i got same error when training LoRA with optimizer D-adaptAdam, LR/TE-lr/Unet-lr=1.
But i set different block weight lr in advanced configuration TAb,i guess DA didt support seperate block weight lr yet,

**Comment by Jinouga311** [comment]
Hi,

Anyone found a solution?
I have the same problem with D-AdaptAdam, it's very embarrassing.
