### ISSUE TITLE
How to solve this error ? I'm on rtx3070 mobile and torch 2.0.1. I did a fresh install today.

### ISSUE THREAD

**Issue by anto18671** [bmaltais/kohya_ss#956]
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary D:\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\kohya_ss\train_network.py:864 in <module>                                                     │
│                                                                                                  │
│   861 │   args = parser.parse_args()                                                             │
│   862 │   args = train_util.read_config_from_file(args, parser)                                  │
│   863 │                                                                                          │
│ ❱ 864 │   train(args)                                                                            │
│   865                                                                                            │
│                                                                                                  │
│ D:\kohya_ss\train_network.py:292 in train                                                        │
│                                                                                                  │
│   289 │                                                                                          │
│   290 │   # acceleratorがなんかよろしくやってくれるらしい                                        │
│   291 │   if train_unet and train_text_encoder:                                                  │
│ ❱ 292 │   │   unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = acceler   │
│   293 │   │   │   unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler         │
│   294 │   │   )                                                                                  │
│   295 │   elif train_unet:                                                                       │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1143 in prepare                     │
│                                                                                                  │
│   1140 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│ ❱ 1143 │   │   │   result = tuple(                                                               │
│   1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1144 in <genexpr>                   │
│                                                                                                  │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│   1143 │   │   │   result = tuple(                                                               │
│ ❱ 1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│   1147                                                                                           │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:995 in _prepare_one                 │
│                                                                                                  │
│    992 │   │   │   if isinstance(obj, torch.utils.data.DataLoader):                              │
│    993 │   │   │   │   return self.prepare_data_loader(obj, device_placement=device_placement)   │
│    994 │   │   │   elif isinstance(obj, torch.nn.Module):                                        │
│ ❱  995 │   │   │   │   return self.prepare_model(obj, device_placement=device_placement)         │
│    996 │   │   │   elif isinstance(obj, torch.optim.Optimizer):                                  │
│    997 │   │   │   │   optimizer = self.prepare_optimizer(obj, device_placement=device_placemen  │
│    998 │   │   │   │   return optimizer                                                          │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1290 in prepare_model               │
│                                                                                                  │
│   1287 │   │   if self.state.dynamo_plugin.backend != DynamoBackend.NO:                          │
│   1288 │   │   │   if not is_torch_version(">=", "2.0"):                                         │
│   1289 │   │   │   │   raise ValueError("Using `torch.compile` requires PyTorch 2.0 or higher."  │
│ ❱ 1290 │   │   │   model = torch.compile(model, **self.state.dynamo_plugin.to_kwargs())          │
│   1291 │   │   return model                                                                      │
│   1292 │                                                                                         │
│   1293 │   def _prepare_deepspeed(self, *args):                                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\__init__.py:1441 in compile                             │
│                                                                                                  │
│   1438 │   │   mode = "default"                                                                  │
│   1439 │   if backend == "inductor":                                                             │
│   1440 │   │   backend = _TorchCompileInductorWrapper(mode, options, dynamic)                    │
│ ❱ 1441 │   return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic,   │
│   1442                                                                                           │
│   1443                                                                                           │
│   1444 def _register_device_module(device_type, module):                                         │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\_dynamo\eval_frame.py:413 in optimize                   │
│                                                                                                  │
│   410 │   │   def toy_example(a, b):                                                             │
│   411 │   │   │   ...                                                                            │
│   412 │   """                                                                                    │
│ ❱ 413 │   check_if_dynamo_supported()                                                            │
│   414 │   # Note: The hooks object could be global instead of passed around, *however* that wo   │
│   415 │   # for a confusing API usage and plumbing story wherein we nest multiple .optimize ca   │
│   416 │   # There is some prior art around this, w/r/t nesting backend calls are enforced to b   │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\torch\_dynamo\eval_frame.py:375 in check_if_dynamo_supported  │
│                                                                                                  │
│   372                                                                                            │
│   373 def check_if_dynamo_supported():                                                           │
│   374 │   if sys.platform == "win32":                                                            │
│ ❱ 375 │   │   raise RuntimeError("Windows not yet supported for torch.compile")                  │
│   376 │   if sys.version_info >= (3, 11):                                                        │
│   377 │   │   raise RuntimeError("Python 3.11+ not yet supported for torch.compile")             │
│   378                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Windows not yet supported for torch.compile
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Anthony\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Anthony\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code            │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main              │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in launch_command           │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in simple_launcher          │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=D:/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors',
'--train_data_dir=C:/Users/Anthony/Desktop/output/img', '--reg_data_dir=C:/Users/Anthony/Desktop/output/reg',
'--resolution=512,512', '--output_dir=C:/Users/Anthony/Desktop/output/model',
'--logging_dir=C:/Users/Anthony/Desktop/output/log', '--network_alpha=1', '--save_model_as=ckpt',
'--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128',
'--output_name=HotFallingDevil', '--lr_scheduler_num_cycles=30', '--learning_rate=0.0001', '--lr_scheduler=cosine',
'--lr_warmup_steps=17760', '--train_batch_size=1', '--max_train_steps=177600', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=2',
'--bucket_reso_steps=64', '--gradient_checkpointing', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Try using AdamW instead of AdamW8bit... might help for your card.

**Comment by Little-God1983** [comment]
Same Error here.
Switching the optimizier does nothing. I have a 4080 RTX.

**Comment by bmaltais** [comment]
Have you tried deleting the bench and setup with torch 1?
