### ISSUE TITLE
kohya_ss DOESN'T WORK since a while

### ISSUE THREAD

**Issue by Djanghost** [bmaltais/kohya_ss#959]
Kohya was a great tool for training Loras and other models. For many days impossible to train. After multiple unresolved errors I uninstalled the repo and reinstalled it today, telling myself that the latest updates had probably solved the problems.

For my part here is the error I get when I try to create a Lora model:

![koyaerror](https://github.com/bmaltais/kohya_ss/assets/129005283/0ef9dfe1-8e4a-4a50-bcf1-6cabb8b61bce)

@bmaltais I've seen this error before in other issues here but no right solutons. Could you please find a solution?

Thanks in advance and sorry for the tone of this thread. I really liked this repo and it's quite frustrating not being able to use it anymore.

I'm using windows 11 with an RTX4090 and a kohya installation with torch v2

**Comment by bmaltais** [comment]
Are you sure the folder structure for your images is right? This is what kohya's script is complaining about...

**Comment by Djanghost** [comment]
> Are you sure the folder structure for your images is right? This is what kohya's script is complaining about...

Yes i do the same thing than before, having images (jpg) and captions (txt) in the folder "images"

**Comment by bmaltais** [comment]
I wish I could fix the issue but until I can reproduce it it is impossible... And I suspect it is probably not even in my code but in kohya's code. Have you tried running the training command manually and tweaking the parameters?

Kohya is complaining about the folder where the images are... Something around that is most certainly the issue.

**Comment by bmaltais** [comment]
If you find what is causing the issue let me k own and if I can do something in the code to avoid it I will

**Comment by bmaltais** [comment]
I also noticed one of the lines in your screen capture is not lining up with the rest... I wonder if some extra hidden character is not present in your folder parameters ... Try deleting the image folder path and reselect it using the folder icon...

**Comment by bmaltais** [comment]
I have pushed an update to the dev2 branch that will report if your image folder contain badly formed subfolder names.

You can test it with:

`git checkout dev2`

It should clearly point out to an issue with your image folder content.

**Comment by sumire608** [comment]
If you are not using tom1 file, then you should specify train data folder to "x:\jeroen" , and put image files like "x:\jeroen\1_foobar\image1.jpg".

**Comment by Valen-H** [comment]
I get the same error.

**Comment by bmaltais** [comment]
This is weird. No idea what is causing this beside bad folder dataset structure or some issue recently introduced by kohya's code.

**Comment by Djanghost** [comment]
@bmaltais I've already tried regarding the folder structure, I've tried a lot of things actually. Well let's wait again, in the meantime there is still the Dreambooth extension

@sumire608 I don't know what you're talking about when you're saying "tom 1 file", I'm just linking all the folders in the right place like before

**Comment by sumire608** [comment]
> @bmaltais I've already tried regarding the folder structure, I've tried a lot of things actually. Well let's wait again, in the meantime there is still the Dreambooth extension Should i post this issue in here too ? https://github.com/kohya-ss/sd-scripts
> 
> @sumire608 I don't know what you're talking about when you're saying "tom 1 file", I'm just linking all the folders in the right place like before

Kohya ss script supports tom1 config file to do more elaborated settings. If you are not use that, that's Ok. Could you please give a screenshot that show you how to put the image files.

**Comment by bmaltais** [comment]
Have you tried pulling the dev2 branch and try running it? It will report back if the image folder structure for dreambooth is wrong and stop the process.

**Comment by Djanghost** [comment]
@bmaltais @sumire608 i just looked at the test\img folder, this is the same structure, excepted that i have a " " instead of "_" in the name of my files. Like :

subject (1).jpg     subject (1).txt

In the test\img, example  is like subject_1.jpg     subject_1.txt

This is the only difference, going to test asap

**Comment by bmaltais** [comment]
OK... so your directory structure is most certainly wrong. In your `images` folder you need a subfolder called something like `30_green costume`

You then put all you images in the 30_green costume folder.

30 mean you will do 30 repeats of all images of green costume in the folder.

Since you use caption the `green costume` part won't be used since the .txt file caption will superseed it.

**Comment by bmaltais** [comment]
Kohya use a special folder structure to provide the repeat value for the images. Make to abide by the structure otherwise the training will fail.

Here is an example where we would train two concepts for 30 repeats each. Let's call the 1st concept `cat` and the 2nd concept `dog`. You need a minimum of one concept for training but can use as many as you want.

THe folder structure for those would be:

images
|
> 30_cat
| |
| > image1.jpg
| > image1.txt
| > image2.png
| > image2.txt
> 30_dog
  |
  > image1.jpg
  > image1.txt
  > image2.png
  > image2.txt

The same structure is required for regularization images.

**Comment by bmaltais** [comment]
I have pushed an update to the repo with the above as a document and reference to it in the error message that will be displayed to users.

**Comment by Djanghost** [comment]
Thank you @bmaltais, all work fine now. I think it's been too long since I've used Kohya and had the Dreambooth workflow in mind. I close the issue now.
