### ISSUE TITLE
Error while training LORA, CUDA not working

### ISSUE THREAD

**Issue by Odawgthat** [bmaltais/kohya_ss#96]
![image](https://user-images.githubusercontent.com/122664491/216729848-0de0413e-81f2-4afc-992a-b0d0c50d0e5b.png)

**Comment by bmaltais** [comment]
I see some reference to anaconda. Are you using the windows python 3.10.9 installation? This will not work with anaconda.

**Comment by Odawgthat** [comment]
> I see some reference to anaconda. Are you using the windows python 3.10.9 installation? This will not work with anaconda.

Oh, that is the exact version that I am using! I fixed it by copying the folder of bits and bytes from stable diffusion, I never thought about changing the python version though. Thank you for your feedback :)
