### ISSUE TITLE
Cannot select folders

### ISSUE THREAD

**Issue by xpluscal** [bmaltais/kohya_ss#967]
When trying to select any folder in the GUI, nothing happens.

Expected Behaviour: A Dialog appears to select files / folders.

I tried manually pasting the path to the folder in the input fields (e.g. for Lora the source folder of images), but then get the following error ( so it seems to not pick it up ):

`No data found. Please verify arguments (train_data_dir must be the parent of folders with images) / 画像がありません。引数指定を確認してください（train_data_dirには画像があるフォルダではなく、画像があるフォルダの親フォルダを指定する必要があります`

**Comment by bmaltais** [comment]
What OS are you using? Windows?

**Comment by ruiboy1919** [comment]
Think of [] as a folder name.

[test]-[1_image].
Instead of specifying the folder path of [1_image], specify the folder path of [test].
