### ISSUE TITLE
A weird gradient_checkpoint issue.

### ISSUE THREAD

**Issue by GeneralAwareness** [bmaltais/kohya_ss#97]
If I do not use this option I get an OOM, but if I do I then get this message where it seems to work (how well I do not know).
![image](https://user-images.githubusercontent.com/124339252/216742751-1651d800-5bbb-469d-86a3-a16486fb0661.png)

**Comment by GeneralAwareness** [comment]
I ran it and Auto1111 refuses to load it and the network extension gave me this nonsense

dimension: 128, alpha: 128.0, multiplier_unet: 1, multiplier_tenc: 1
create LoRA for Text Encoder: 138 modules.
create LoRA for U-Net: 192 modules.
original forward/weights is backed up.
enable LoRA for text encoder
enable LoRA for U-Net
shapes for 64 weights are converted.
LoRA model Cyl0n(43d73015bcd1) loaded: <All keys matched successfully>

![image](https://user-images.githubusercontent.com/124339252/216751057-6613a90c-5123-476f-a9b0-856d186e5cb3.png)

**Comment by bmaltais** [comment]
This is an issue that should be reported directly to the author of the script I use via the gui. His repo is at: https://github.com/kohya-ss/sd-scripts

**Comment by GeneralAwareness** [comment]
> This is an issue that should be reported directly to the author of the script I use via the gui. His repo is at: https://github.com/kohya-ss/sd-scripts

Yes, but I trained with yours.  Which is the problem this or that considering even Automatic1111 had an issue with it.

**Comment by bmaltais** [comment]
It might not be obvious but the code that does the actual training is written by kohya_ss. I only wrap the cli with a GUI. What happen if you train using the cli commands only? Does it work better?

**Comment by GeneralAwareness** [comment]
Which script do I call?
