### ISSUE TITLE
Lora trained on 2.1 with 768 px resolution, result in blurry images with almost no colors.

### ISSUE THREAD

**Issue by JasonS09** [bmaltais/kohya_ss#970]
Hello. Not much to explain. I tried to train a Lora using 2.1 768px as base model. When trying to run it on Automatic1111, no error shows and seems that the Lora is indeed working, but images are brownish with no color.

I have tried used both normal prompt and additional networks extension, locally and in the cloud. The results are the same. Which makes me believe the problem lies in the lora itself, but who knows. Maybe someone can shed some light here? Here are two of the resulting images for the Lora:

![00000-446612613](https://github.com/bmaltais/kohya_ss/assets/47617351/95501e5d-228d-4899-81c2-c1e79e25faa6)
![00000-170508518](https://github.com/bmaltais/kohya_ss/assets/47617351/b72b4240-4422-4812-978e-b321733c4bf1)

This is how they look with the sample prompt from the training script:

![im_20230611232710_000_534146437](https://github.com/bmaltais/kohya_ss/assets/47617351/3298e0e9-924c-4678-a182-d0d8b257fc29)

None of them are the intended result. I had previously trained a lora with the exact dataset (but with lower resolution) for 1.5 model and worked fine. 

Resolution training was set to 768px.

**Comment by bmaltais** [comment]
Wish I could help... But I never get good results myself training SD2.1 so I avoid it.
