### ISSUE TITLE
Is there a way to hide the metadata?

### ISSUE THREAD

**Issue by R5021** [bmaltais/kohya_ss#976]
When creating a LoRA, you don't want to include metadata information in the LoRA.
Is it possible to hide metadata in the Kohya_ss gui?

If it is possible, in which item and what command should I use?

**Comment by bmaltais** [comment]
Add `--no_metadata` to the optional arguments in the Training advanced accordion.

**Comment by wzgrx** [comment]
> 添加到“培训高级”折叠式折叠式中的可选参数。`--no_metadata`

I couldn't find this option

**Comment by wzgrx** [comment]
> > 添加到"培训高级"折叠式折叠式中的可选参数。`--no_metadata`
> 
> 我找不到
![Snipaste_2023-06-15_07-19-22](https://github.com/bmaltais/kohya_ss/assets/39661556/00e67386-e939-4f92-8a10-c58b6305976d)
此选项

**Comment by bmaltais** [comment]
It is right here:

![image](https://github.com/bmaltais/kohya_ss/assets/7474674/9d4cc6c3-840c-43d3-84ec-ffb736b40542)

**Comment by wzgrx** [comment]
Thank you.
