### ISSUE TITLE
Huggingface_hub cache-system error +  TypedStorage is deprecated error

### ISSUE THREAD

**Issue by aearone** [bmaltais/kohya_ss#977]
When I install Torch 2.0, I get this error: 

```
Downloading (…)olve/main/vocab.json: 100%|███████████████████████████████████████████| 961k/961k [00:01<00:00, 928kB/s]
G:\kohya_ss\kohya_ss\venv\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in G:\SDCache\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
```
I manually changed the location of the cache, but this has no effect on the error, as it appears even with the default cache location on the C drive. 

This error only appears on Torch 2.0. How do I fix it?  Or just ignore it? 

I also wanted to know about the error:
```
UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
```
Should I ignore this error or is it a problem with my computer/wrong installation? Because I have noticed that this error appears in many people.

**Comment by bmaltais** [comment]
Best is to enable developer mode as instructed... or simply ignore the warning. Things will still work fine.

**Comment by aearone** [comment]
> Best is to enable developer mode as instructed... or simply ignore the warning. Things will still work fine.
Running gui-user.bat as administrator solved the Huggingface_hub cache-system problem, thanks! But this error is still there: 
```
kohya_ss\venv\lib\site-packages\xformers\ops\fmha\flash.py:339: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  and inp.query.storage().data_ptr() == inp.key.storage().data_ptr()
```
As well as the warning about not having Triton installed. Do you think these errors are related to xformers on torch 2.0 when the program is still trying to access it? Does it make sense then to enable xformers in the training settings?

Also this is a little off topic, but I manually installed a newer version of CuDNN 8.8.0 and my training speed went from 1.48 to 2.0 it.s when training 768x768 images. I can post a zip archive with CuDNN 8.8.0 so you can install and check for yourself. If it really does give even more speed, you can update the CuDNN download link on the kohya_ss installation tutorial page:).

**Comment by bmaltais** [comment]
Nothing I can do about that. I get that also. It is something part of xformers. Facebook will need to fix it.

**Comment by aearone** [comment]
> Nothing I can do about that. I get that also. It is something part of xformers. Facebook will need to fix it.

I understand, thank you for your answer! In that case, I will just ignore this error/warning. Will wait for torch updates:)
