### ISSUE TITLE
Keep getting error

### ISSUE THREAD

**Issue by wrknce98** [bmaltais/kohya_ss#979]
**Hi! I've been getting this error consistently whenever I try to train. I'm working from Linux Mint 21, fresh install.
Already tried adding bitsandbytes to LD_LIBRARY_PATH.**

/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib64: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/wrknce98-MS-7C91'), PosixPath('@/tmp/.ICE-unix/1374,unix/wrknce98-MS-7C91')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/518c89f4_0835_4954_8931_418d8b8c96d6')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
  warn(
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda121.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/wrknce98/kohya_ss/train_network.py:864 in <module>                         │
│                                                                              │
│   861 │   args = parser.parse_args()                                         │
│   862 │   args = train_util.read_config_from_file(args, parser)              │
│   863 │                                                                      │
│ ❱ 864 │   train(args)                                                        │
│   865                                                                        │
│                                                                              │
│ /home/wrknce98/kohya_ss/train_network.py:253 in train                            │
│                                                                              │
│   250 │   │   )                                                              │
│   251 │   │   trainable_params = network.prepare_optimizer_params(args.text_ │
│   252 │                                                                      │
│ ❱ 253 │   optimizer_name, optimizer_args, optimizer = train_util.get_optimiz │
│   254 │                                                                      │
│   255 │   # dataloaderを準備する                                             │
│   256 │   # DataLoaderのプロセス数：0はメインプロセスになる                  │
│                                                                              │
│ /home/wrknce98/kohya_ss/library/train_util.py:2623 in get_optimizer              │
│                                                                              │
│   2620 │                                                                     │
│   2621 │   if optimizer_type == "AdamW8bit".lower():                         │
│   2622 │   │   try:                                                          │
│ ❱ 2623 │   │   │   import bitsandbytes as bnb                                │
│   2624 │   │   except ImportError:                                           │
│   2625 │   │   │   raise ImportError("No bitsand bytes / bitsandbytesがイン  │
│   2626 │   │   print(f"use 8-bit AdamW optimizer | {optimizer_kwargs}")      │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__. │
│ py:6 in <module>                                                             │
│                                                                              │
│    3 # This source code is licensed under the MIT license found in the       │
│    4 # LICENSE file in the root directory of this source tree.               │
│    5                                                                         │
│ ❱  6 from .autograd._functions import (                                      │
│    7 │   MatmulLtState,                                                      │
│    8 │   bmm_cublas,                                                         │
│    9 │   matmul,                                                             │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/ │
│ _functions.py:5 in <module>                                                  │
│                                                                              │
│     2 import warnings                                                        │
│     3                                                                        │
│     4 import torch                                                           │
│ ❱   5 import bitsandbytes.functional as F                                    │
│     6                                                                        │
│     7 from dataclasses import dataclass                                      │
│     8 from functools import reduce  # Required in Python 3                   │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functiona │
│ l.py:13 in <module>                                                          │
│                                                                              │
│     10 from typing import Tuple                                              │
│     11 from torch import Tensor                                              │
│     12                                                                       │
│ ❱   13 from .cextension import COMPILED_WITH_CUDA, lib                       │
│     14 from functools import reduce  # Required in Python 3                  │
│     15                                                                       │
│     16 # math.prod not compatible with python < 3.8                          │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextensio │
│ n.py:41 in <module>                                                          │
│                                                                              │
│   38 │   │   return cls._instance                                            │
│   39                                                                         │
│   40                                                                         │
│ ❱ 41 lib = CUDALibrary_Singleton.get_instance().lib                          │
│   42 try:                                                                    │
│   43 │   lib.cadam32bit_g32                                                  │
│   44 │   lib.get_context.restype = ct.c_void_p                               │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextensio │
│ n.py:37 in get_instance                                                      │
│                                                                              │
│   34 │   def get_instance(cls):                                              │
│   35 │   │   if cls._instance is None:                                       │
│   36 │   │   │   cls._instance = cls.__new__(cls)                            │
│ ❱ 37 │   │   │   cls._instance.initialize()                                  │
│   38 │   │   return cls._instance                                            │
│   39                                                                         │
│   40                                                                         │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextensio │
│ n.py:27 in initialize                                                        │
│                                                                              │
│   24 │   │   │   if not binary_path.exists():                                │
│   25 │   │   │   │   print('CUDA SETUP: CUDA detection failed. Either CUDA d │
│   26 │   │   │   │   print('CUDA SETUP: If you compiled from source, try aga │
│ ❱ 27 │   │   │   │   raise Exception('CUDA SETUP: Setup Failed!')            │
│   28 │   │   │   self.lib = ct.cdll.LoadLibrary(binary_path)                 │
│   29 │   │   else:                                                           │
│   30 │   │   │   print(f"CUDA SETUP: Loading binary {binary_path}...")       │
╰──────────────────────────────────────────────────────────────────────────────╯
Exception: CUDA SETUP: Setup Failed!
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/wrknce98/kohya_ss/venv/bin/accelerate:8 in <module>                        │
│                                                                              │
│   5 from accelerate.commands.accelerate_cli import main                      │
│   6 if __name__ == '__main__':                                               │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])     │
│ ❱ 8 │   sys.exit(main())                                                     │
│   9                                                                          │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/ac │
│ celerate_cli.py:45 in main                                                   │
│                                                                              │
│   42 │   │   exit(1)                                                         │
│   43 │                                                                       │
│   44 │   # Run                                                               │
│ ❱ 45 │   args.func(args)                                                     │
│   46                                                                         │
│   47                                                                         │
│   48 if __name__ == "__main__":                                              │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/la │
│ unch.py:1104 in launch_command                                               │
│                                                                              │
│   1101 │   elif defaults is not None and defaults.compute_environment == Com │
│   1102 │   │   sagemaker_launcher(defaults, args)                            │
│   1103 │   else:                                                             │
│ ❱ 1104 │   │   simple_launcher(args)                                         │
│   1105                                                                       │
│   1106                                                                       │
│   1107 def main():                                                           │
│                                                                              │
│ /home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/la │
│ unch.py:567 in simple_launcher                                               │
│                                                                              │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                  │
│    565 │   process.wait()                                                    │
│    566 │   if process.returncode != 0:                                       │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.return │
│    568                                                                       │
│    569                                                                       │
│    570 def multi_gpu_launcher(args):                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['/home/wrknce98/kohya_ss/venv/bin/python', 
'train_network.py', '--enable_bucket', 
'--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', 
'--train_data_dir=/home/wrknce98/Documents/LORAs/Jane/image', 
'--resolution=512,512', '--output_dir=/home/wrknce98/Documents/LORAs/Jane/log', 
'--logging_dir=/home/wrknce98/Documents/LORAs/Jane/log', '--network_alpha=1', 
'--save_model_as=safetensors', '--network_module=networks.lora', 
'--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', 
'--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', 
'--lr_scheduler=cosine', '--lr_warmup_steps=630', '--train_batch_size=1', 
'--max_train_steps=6300', '--save_every_n_epochs=1', '--mixed_precision=fp16', 
'--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', 
'--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', 
'--bucket_no_upscale']' returned non-zero exit status 1.
^CKeyboard interruption in main thread... closing server.

**python -m bitsandbytes output:**
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/wrknce98-MS-7C91'), PosixPath('@/tmp/.ICE-unix/1374,unix/wrknce98-MS-7C91')}
  warn(msg)
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}
  warn(msg)
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(msg)
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}
  warn(msg)
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
  warn(msg)
/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/518c89f4_0835_4954_8931_418d8b8c96d6')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...

python -m bitsandbytes output:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cu.so
/home/wrknce98/kohya_ss/venv/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/wrknce98/.local/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'

**Comment by wrknce98** [comment]
Okay, so I've been testing around and I thinks its an issue with bits and bytes. I think bits and bytes 0.35 its not compatible with CUDA 12.1, but Kohya doesn't work with bits and bytes 0.39. I might be way off here, I'm not super technical. Any help its appreciated.

**Comment by bmaltais** [comment]
This is correct, anything above 0.35 will not work with kohya_ss sd-scripts... So we have to stay at 0.35. Your best bet is to try to run the non 8bit optimizers. They produce better results anyway... so you don't lose anything by using them.
