### ISSUE TITLE
Unable to start training. Please help

### ISSUE THREAD

**Issue by HotRod888** [bmaltais/kohya_ss#984]
**Keep getting this runtime error and Calledprocesserror. Wonder what is wrong with it?**

08:46:31-033261 INFO     Start training LoRA Standard ...
08:46:31-033261 INFO     Valid image folder names found in:
                         X:/Training/123\img
08:46:31-033261 INFO     Valid image folder names found in:
                         X:/Training/123\reg
08:46:31-041264 INFO     Folder 40_tutorial_ryyc_test man: 8 images found
08:46:31-041264 INFO     Folder 40_tutorial_ryyc_test man: 320 steps
08:46:31-041264 INFO     [94mRegularisation images are used... Will double
                         the number of steps required...[0m
08:46:31-041264 INFO     Total steps: 320
08:46:31-041264 INFO     Train batch size: 1
08:46:31-041264 INFO     Gradient accumulation steps: 1
08:46:31-041264 INFO     Epoch: 10
08:46:31-041264 INFO     Regulatization factor: 2
08:46:31-041264 INFO     max_train_steps (320 / 1 / 1 * 10 * 2) = 6400
08:46:31-041264 INFO     stop_text_encoder_training = 0
08:46:31-041264 INFO     lr_warmup_steps = 640
08:46:31-049262 INFO     accelerate launch --num_cpu_threads_per_process=1
                         "train_network.py" --enable_bucket
                         --pretrained_model_name_or_path="X:/StableDiffusion
                         /stable-diffusion-webui/models/Stable-diffusion/v1-
                         5-pruned-emaonly.ckpt"
                         --train_data_dir="X:/Training/123\img"
                         --reg_data_dir="X:/Training/123\reg"
                         --resolution="512,512"
                         --output_dir="X:/Training/123\model"
                         --logging_dir="X:/Training/123\log"
                         --network_alpha="1" --save_model_as=safetensors
                         --network_module=networks.lora
                         --text_encoder_lr=5e-05 --unet_lr=0.0001
                         --network_dim=128 --output_name="test1"
                         --lr_scheduler_num_cycles="10"
                         --learning_rate="0.0001" --lr_scheduler="cosine"
                         --lr_warmup_steps="640" --train_batch_size="1"
                         --max_train_steps="6400" --save_every_n_epochs="1"
                         --mixed_precision="fp16" --save_precision="fp16"
                         --optimizer_type="AdamW8bit"
                         --max_data_loader_n_workers="0"
                         --resume="X:/Training" --bucket_reso_steps=64
                         --mem_eff_attn --xformers --bucket_no_upscale
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory X:\Training\123\img\40_tutorial_ryyc_test man contains 8 image files
No caption file found for 8 images. Training will continue without captions for these images. If class token exists, it will be used. / 8枚の画像にキャ プションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
X:\Training\123\img\40_tutorial_ryyc_test man\1.jpg
X:\Training\123\img\40_tutorial_ryyc_test man\2.jpg
X:\Training\123\img\40_tutorial_ryyc_test man\3.jpg
X:\Training\123\img\40_tutorial_ryyc_test man\4.jpg
X:\Training\123\img\40_tutorial_ryyc_test man\5.jpg
X:\Training\123\img\40_tutorial_ryyc_test man\6.jpg... and 3 more
found directory X:\Training\123\reg\1_man contains 351 image files
No caption file found for 351 images. Training will continue without captions for these images. If class token exists, it will be used. / 351枚の画像に キャプションファイルが見つかりませんでした。これらの画像についてはキャプションなしで学習を続行します。class tokenが存在する場合はそれを使います。
X:\Training\123\reg\1_man\00000-1368595603.png
X:\Training\123\reg\1_man\00001-2377048836.png
X:\Training\123\reg\1_man\00002-2377048837.png
X:\Training\123\reg\1_man\00003-2377048838.png
X:\Training\123\reg\1_man\00004-2377048839.png
X:\Training\123\reg\1_man\00005-2377048840.png... and 346 more
320 train images with repeating.
351 reg images.
some of reg images are not used / 正則化画像の数が多いので、一部使用されない正則化画像があります
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: True
  min_bucket_reso: 256
  max_bucket_reso: 1024
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "X:\Training\123\img\40_tutorial_ryyc_test man"
    image_count: 8
    num_repeats: 40
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: tutorial_ryyc_test man
    caption_extension: .caption

  [Subset 1 of Dataset 0]
    image_dir: "X:\Training\123\reg\1_man"
    image_count: 351
    num_repeats: 1
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: True
    class_tokens: man
    caption_extension: .caption

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████| 328/328 [00:00<00:00, 3079.97it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含 む）
bucket 0: resolution (384, 512), count: 40
bucket 1: resolution (512, 512), count: 600
mean ar error (without repeats): 0.0002381859756097561
preparing accelerator
Using accelerator 0.15.0 or above.
loading model for process 0/1
load StableDiffusion checkpoint: X:/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt
╭─────────────────── Traceback (most recent call last) ────────────────────╮
│ X:\StableDiffusion\kohya_ss\train_network.py:864 in <module>             │
│                                                                          │
│   861 │   args = parser.parse_args()                                     │
│   862 │   args = train_util.read_config_from_file(args, parser)          │
│   863 │                                                                  │
│ ❱ 864 │   train(args)                                                    │
│   865                                                                    │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\train_network.py:160 in train                │
│                                                                          │
│   157 │   weight_dtype, save_dtype = train_util.prepare_dtype(args)      │
│   158 │                                                                  │
│   159 │   # モデルを読み込む                                             │
│ ❱ 160 │   text_encoder, vae, unet, _ = train_util.load_target_model(args │
│   161 │                                                                  │
│   162 │   # モデルに xformers とか memory efficient attention を組み込む │
│   163 │   train_util.replace_unet_modules(unet, args.mem_eff_attn, args. │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\library\train_util.py:3061 in                │
│ load_target_model                                                        │
│                                                                          │
│   3058 │   │   if pi == accelerator.state.local_process_index:           │
│   3059 │   │   │   print(f"loading model for process {accelerator.state. │
│   3060 │   │   │                                                         │
│ ❱ 3061 │   │   │   text_encoder, vae, unet, load_stable_diffusion_format │
│   3062 │   │   │   │   args, weight_dtype, accelerator.device if args.lo │
│   3063 │   │   │   )                                                     │
│   3064                                                                   │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\library\train_util.py:3027 in                │
│ _load_target_model                                                       │
│                                                                          │
│   3024 │   load_stable_diffusion_format = os.path.isfile(name_or_path)   │
│   3025 │   if load_stable_diffusion_format:                              │
│   3026 │   │   print(f"load StableDiffusion checkpoint: {name_or_path}") │
│ ❱ 3027 │   │   text_encoder, vae, unet = model_util.load_models_from_sta │
│   3028 │   else:                                                         │
│   3029 │   │   # Diffusers model is loaded to CPU                        │
│   3030 │   │   print(f"load Diffusers pretrained models: {name_or_path}" │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\library\model_util.py:856 in                 │
│ load_models_from_stable_diffusion_checkpoint                             │
│                                                                          │
│    853                                                                   │
│    854 # TODO dtype指定の動作が怪しいので確認する text_encoderを指定形式 │
│    855 def load_models_from_stable_diffusion_checkpoint(v2, ckpt_path, d │
│ ❱  856 │   _, state_dict = load_checkpoint_with_text_encoder_conversion( │
│    857 │                                                                 │
│    858 │   # Convert the UNet2DConditionModel model.                     │
│    859 │   unet_config = create_unet_diffusers_config(v2, unet_use_linea │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\library\model_util.py:833 in                 │
│ load_checkpoint_with_text_encoder_conversion                             │
│                                                                          │
│    830 │   │   checkpoint = None                                         │
│    831 │   │   state_dict = load_file(ckpt_path)  # , device) # may caus │
│    832 │   else:                                                         │
│ ❱  833 │   │   checkpoint = torch.load(ckpt_path, map_location=device)   │
│    834 │   │   if "state_dict" in checkpoint:                            │
│    835 │   │   │   state_dict = checkpoint["state_dict"]                 │
│    836 │   │   else:                                                     │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\serialization.p │
│ y:712 in load                                                            │
│                                                                          │
│    709 │   │   │   │   │   │   │   │     " silence this warning)", UserW │
│    710 │   │   │   │   │   opened_file.seek(orig_position)               │
│    711 │   │   │   │   │   return torch.jit.load(opened_file)            │
│ ❱  712 │   │   │   │   return _load(opened_zipfile, map_location, pickle │
│    713 │   │   return _legacy_load(opened_file, map_location, pickle_mod │
│    714                                                                   │
│    715                                                                   │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\serialization.p │
│ y:1049 in _load                                                          │
│                                                                          │
│   1046 │                                                                 │
│   1047 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)   │
│   1048 │   unpickler.persistent_load = persistent_load                   │
│ ❱ 1049 │   result = unpickler.load()                                     │
│   1050 │                                                                 │
│   1051 │   torch._utils._validate_loaded_sparse_tensors()                │
│   1052                                                                   │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\serialization.p │
│ y:1019 in persistent_load                                                │
│                                                                          │
│   1016 │   │                                                             │
│   1017 │   │   if key not in loaded_storages:                            │
│   1018 │   │   │   nbytes = numel * torch._utils._element_size(dtype)    │
│ ❱ 1019 │   │   │   load_tensor(dtype, nbytes, key, _maybe_decode_ascii(l │
│   1020 │   │                                                             │
│   1021 │   │   return loaded_storages[key]                               │
│   1022                                                                   │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\serialization.p │
│ y:997 in load_tensor                                                     │
│                                                                          │
│    994 │   def load_tensor(dtype, numel, key, location):                 │
│    995 │   │   name = f'data/{key}'                                      │
│    996 │   │                                                             │
│ ❱  997 │   │   storage = zip_file.get_storage_from_record(name, numel, t │
│    998 │   │   # TODO: Once we decide to break serialization FC, we can  │
│    999 │   │   # stop wrapping with _TypedStorage                        │
│   1000 │   │   loaded_storages[key] = torch.storage._TypedStorage(       │
╰──────────────────────────────────────────────────────────────────────────╯
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:81] data.
DefaultCPUAllocator: not enough memory: you tried to allocate 52428800
bytes.
╭─────────────────── Traceback (most recent call last) ────────────────────╮
│ C:\Users\rodne\AppData\Local\Programs\Python\Python310\lib\runpy.py:196  │
│ in _run_module_as_main                                                   │
│                                                                          │
│   193 │   main_globals = sys.modules["__main__"].__dict__                │
│   194 │   if alter_argv:                                                 │
│   195 │   │   sys.argv[0] = mod_spec.origin                              │
│ ❱ 196 │   return _run_code(code, main_globals, None,                     │
│   197 │   │   │   │   │    "__main__", mod_spec)                         │
│   198                                                                    │
│   199 def run_module(mod_name, init_globals=None,                        │
│                                                                          │
│ C:\Users\rodne\AppData\Local\Programs\Python\Python310\lib\runpy.py:86   │
│ in _run_code                                                             │
│                                                                          │
│    83 │   │   │   │   │      __loader__ = loader,                        │
│    84 │   │   │   │   │      __package__ = pkg_name,                     │
│    85 │   │   │   │   │      __spec__ = mod_spec)                        │
│ ❱  86 │   exec(code, run_globals)                                        │
│    87 │   return run_globals                                             │
│    88                                                                    │
│    89 def _run_module_code(code, init_globals=None,                      │
│                                                                          │
│ in <module>:7                                                            │
│                                                                          │
│   4 from accelerate.commands.accelerate_cli import main                  │
│   5 if __name__ == '__main__':                                           │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0]) │
│ ❱ 7 │   sys.exit(main())                                                 │
│   8                                                                      │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\a │
│ ccelerate_cli.py:45 in main                                              │
│                                                                          │
│   42 │   │   exit(1)                                                     │
│   43 │                                                                   │
│   44 │   # Run                                                           │
│ ❱ 45 │   args.func(args)                                                 │
│   46                                                                     │
│   47                                                                     │
│   48 if __name__ == "__main__":                                          │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\l │
│ aunch.py:1104 in launch_command                                          │
│                                                                          │
│   1101 │   elif defaults is not None and defaults.compute_environment == │
│   1102 │   │   sagemaker_launcher(defaults, args)                        │
│   1103 │   else:                                                         │
│ ❱ 1104 │   │   simple_launcher(args)                                     │
│   1105                                                                   │
│   1106                                                                   │
│   1107 def main():                                                       │
│                                                                          │
│ X:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\l │
│ aunch.py:567 in simple_launcher                                          │
│                                                                          │
│    564 │   process = subprocess.Popen(cmd, env=current_env)              │
│    565 │   process.wait()                                                │
│    566 │   if process.returncode != 0:                                   │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.re │
│    568                                                                   │
│    569                                                                   │
│    570 def multi_gpu_launcher(args):                                     │
╰──────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command
'['X:\\StableDiffusion\\kohya_ss\\venv\\Scripts\\python.exe',
'train_network.py', '--enable_bucket',
'--pretrained_model_name_or_path=X:/StableDiffusion/stable-diffusion-webui/m
odels/Stable-diffusion/v1-5-pruned-emaonly.ckpt',
'--train_data_dir=X:/Training/123\\img',
'--reg_data_dir=X:/Training/123\\reg', '--resolution=512,512',
'--output_dir=X:/Training/123\\model', '--logging_dir=X:/Training/123\\log',
'--network_alpha=1', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=5e-05',
'--unet_lr=0.0001', '--network_dim=128', '--output_name=test1',
'--lr_scheduler_num_cycles=10', '--learning_rate=0.0001',
'--lr_scheduler=cosine', '--lr_warmup_steps=640', '--train_batch_size=1',
'--max_train_steps=6400', '--save_every_n_epochs=1',
'--mixed_precision=fp16', '--save_precision=fp16',
'--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0',
'--resume=X:/Training', '--bucket_reso_steps=64', '--mem_eff_attn',
'--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by bmaltais** [comment]
Look like your dataset structure for the image is wrong. Grab the latest release and when you run it it will stop and point to a document that explain how you need to structure things.

**Comment by smhoff** [comment]
Does that mean for windows it MUST run at c:\images?

**Comment by bmaltais** [comment]
No, wherever is the images folder... like `D:\some_folder\images`
