### ISSUE TITLE
pyenv-win issue with Windows batch files

### ISSUE THREAD

**Issue by OmbraRD** [bmaltais/kohya_ss#985]
On Windows, while running pyenv to manage Python versions, batch files don't execute.

**How to reproduce:**
-Install Python 3.11 (with PATH option selected)
-Install PyEnv (https://github.com/pyenv-win/pyenv-win)
-Install Python 3.10.X using the command `pyenv install 3.10.9` (or any other 3.10 version)
-Browse to the kohya_ss folder in cmd/terminal
-Set local python version using `pyenv local 3.10.9`
-Run any batch files like `setup.bat`, `gui-user.bat` or `gui.bat`

**Current workaround**
Replacing `python` and `python.exe` inside `setup.bat`, `gui.bat` and `upgrade.bat` with the full path from the venv like `.\venv\Scripts\python.exe`, fixes the issue.

**Note**
Issue is not present from PowerShell but there isn't a setup script in that format

**Comment by bmaltais** [comment]
Python 3.11 is not supported. Only 3.10.9 is

**Comment by OmbraRD** [comment]
> Python 3.11 is not supported. Only 3.10.9 is

I know. pyenv allows to specify which version of python to use within a local folder/package/project (kinda like nvm for node). Even if 3.11 is installed globally, 3.10 is used locally within the kohya_ss folder. This is not a python version issue.

**Comment by OmbraRD** [comment]
I ran a few tests and by the looks of it, replacing `python` or `python.exe` with the full path from the venv like `.\venv\Scripts\python.exe`, fixes the issue.

**Comment by OmbraRD** [comment]
Setup also does not deactivate venv on exit.

Here is a quick `setup.ps1`:

`$PYTHON_VER = "3.10.9"

# Check if Python version meets the recommended version
$pythonVersion = & .\venv\Scripts\python.exe --version 2>$null
if ($pythonVersion -notmatch "^Python $PYTHON_VER") {
    Write-Host "Warning: Python version $PYTHON_VER is recommended."
}

if (-not (Test-Path -Path "venv")) {
    Write-Host "Creating venv..."
    python -m venv venv
}

# Create the directory if it doesn't exist
$null = New-Item -ItemType Directory -Force -Path ".\logs\setup"

# Deactivate the virtual environment
& .\venv\Scripts\deactivate.bat

# Calling external python program to check for local modules
& .\venv\Scripts\python.exe .\tools\check_local_modules.py

& .\venv\Scripts\activate.bat

& .\venv\Scripts\python.exe .\tools\setup_windows.py

# Deactivate the virtual environment
& .\venv\Scripts\deactivate.bat`

**Comment by PresTrembleyIIIEsq** [comment]
Is there a version of this workaround for Linux? I'm on Manjaro, and using pyenv to install and use 3.10.9, but setup.sh still throws errors about my main 3.11.5 system install version.
