### ISSUE TITLE
 Not all images folders have proper name patterns Issue in Kohya

### ISSUE THREAD

**Issue by IvanDurak1** [bmaltais/kohya_ss#986]
I'm trying to train my LORA, but as soon as I run khoya_ss I get the error : ERROR    Not all images folders have proper name patterns in C:/AI StableDiff/LORA/10_girl/images. Please follow the folder structure documentation found at docs\image_folder_structure.md ...

I checked the folder and a bunch of youtube videos so I'm pretty sure I'm naming everything correctly. Here's how I'm naming my file I tried the version with pic1, pic2 as well as pic (1), pic (2) but for both I get an error. Below are screenshots of how i tried naming my pictures
<img width="717" alt="Screenshot 2023-06-13 164321" src="https://github.com/bmaltais/kohya_ss/assets/136514007/75cffa40-fc80-4435-89c9-52bab5f04059">
<img width="645" alt="Screenshot 2023-06-13 164443" src="https://github.com/bmaltais/kohya_ss/assets/136514007/737db1f6-2d5c-4a08-9a32-fc7f94dee498">
Please help what should i do to fix this?

**Comment by bmaltais** [comment]
Your forder structure is backward. All your images need to be in the 10_girl folder.

The 10_girl need to be in the images folder

THe path to the image folder is what you put in the GUI.

**Comment by zjc2233** [comment]
> Your forder structure is backward. All your images need to be in the 10_girl folder.你的 forder 结构落后了。您所有的图片都需要放在 10_girl 文件夹中。
> 
> The 10_girl forder need to be in the images folder10_girl forder 需要在 images 文件夹中
> 
> Tge path to the images folder is what you put in the GUI.图像文件夹的路径是您在 GUI 中放置的路径。

I set the path according to the required folder directory, but there is still an error prompt. Why is this?
<img width="706" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/43945226/783cdbbc-f819-4223-8643-f3718757a756">

**Comment by zjc2233** [comment]
> > Your forder structure is backward. All your images need to be in the 10_girl folder.你的 forder 结构落后了。您所有的图片都需要放在 10_girl 文件夹中。
> > The 10_girl forder need to be in the images folder10_girl forder 需要在 images 文件夹中10_girl forder 需要在images 文件夹中10_girl forder 需要在images 文件夹中
> > Tge path to the images folder is what you put in the GUI.图像文件夹的路径是您在 GUI 中放置的路径。
> 
> I set the path according to the required folder directory, but there is still an error prompt. Why is this?我按照需要的文件夹目录设置路径，还是有错误提示。为什么是这样？ <img alt="image" width="706" src="https://user-images.githubusercontent.com/43945226/245698432-783cdbbc-f819-4223-8643-f3718757a756.png">

Docs  image_ Folder_ The requirements for structure.md are as follows
<img width="710" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/43945226/2f1f943d-8bb8-45e2-a89b-34dd483e5fb1">

**Comment by zjc2233** [comment]
> > > Your forder structure is backward. All your images need to be in the 10_girl folder.你的 forder 结构落后了。您所有的图片都需要放在 10_girl 文件夹中。
> > > The 10_girl forder need to be in the images folder10_girl forder 需要在 images 文件夹中10_girl forder 需要在images 文件夹中10_girl forder 需要在images 文件夹中
> > > Tge path to the images folder is what you put in the GUI.图像文件夹的路径是您在 GUI 中放置的路径。
> > 
> > 
> > I set the path according to the required folder directory, but there is still an error prompt. Why is this?我按照需要的文件夹目录设置路径，还是有错误提示。为什么是这样？ <img alt="image" width="706" src="https://user-images.githubusercontent.com/43945226/245698432-783cdbbc-f819-4223-8643-f3718757a756.png">
> 
> Docs image_ Folder_ The requirements for structure.md are as follows <img alt="image" width="710" src="https://user-images.githubusercontent.com/43945226/245699109-2f1f943d-8bb8-45e2-a89b-34dd483e5fb1.png">

Why my folder is `len(matching_subfolders) != (len(os.listdir(folder_path)) - 1)`? 
<img width="1170" alt="image" src="https://github.com/bmaltais/kohya_ss/assets/43945226/1e023597-f1af-4472-bc96-4e8a534ad46a">

**Comment by Fatima-Mujahid** [comment]
Hi, I resolved this issue by viewing the output of the matching_subfolders and os.listdir(folder_path) and found out the problem was due to a hidden file .DS_Store which caused length mismatch in my case. After removing this file, it worked for me.

**Comment by zjc2233** [comment]
> Hi, I resolved this issue by viewing the output of the matching_subfolders and os.listdir(folder_path) and found out the problem was due to a hidden file .DS_Store which caused length mismatch in my case. After removing this file, it worked for me.

Soga！ Thanks very much.
