### ISSUE TITLE
Out of Memory Error. Supposed fixes not working

### ISSUE THREAD

**Issue by xomega100** [bmaltais/kohya_ss#990]
- I am currently using a laptop with an Nvidia GTX 1070 Max-Q 8GB
- I am trying to run Dreambooth LoRA training with 35 images 512x512px
- I am getting an out of CUDA memory error despite having enough VRAM.
- There are other errors as well but im unsure of whether these are significant
- I have tried the fix that was mentioned previously for 10 series users which worked for others, but haven't worked for me: [1](https://github.com/kohya-ss/sd-scripts/issues/44#issuecomment-1375690372) - [2](https://github.com/bmaltais/kohya_ss/issues/61#issuecomment-1409435548) 
- I have had no success and restarted Kohya-ss multiple times to make sure i was doing it right
- pls bare with me as my understanding of computing is very weak

18:13:29-778844 INFO     Loading config...
18:14:18-247360 INFO     Start training LoRA Standard ...
18:14:18-249945 INFO     Valid image folder names found in: E:/StableDiffusion/TRAINING
                         IMAGES/N9HEH/pre-processed/holexohal lora/image
18:14:18-252913 INFO     Folder 100_holexohal: 35 images found
18:14:18-254914 INFO     Folder 100_holexohal: 3500 steps
18:14:18-256948 INFO     Total steps: 3500
18:14:18-260467 INFO     Train batch size: 1
18:14:18-262470 INFO     Gradient accumulation steps: 1
18:14:18-263468 INFO     Epoch: 1
18:14:18-265469 INFO     Regulatization factor: 1
18:14:18-267468 INFO     max_train_steps (3500 / 1 / 1 * 1 * 1) = 3500
18:14:18-269984 INFO     stop_text_encoder_training = 0
18:14:18-270981 INFO     lr_warmup_steps = 0
18:14:18-273019 INFO     accelerate launch --num_cpu_threads_per_process=2 "train_network.py"
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="E:/StableDiffusion/TRAINING IMAGES/N9HEH/pre-processed/holexohal lora/image"
                         --resolution="512,512" --output_dir="E:/StableDiffusion/TRAINING
                         IMAGES/N9HEH/pre-processed/holexohal lora/model" --logging_dir="E:/StableDiffusion/TRAINING
                         IMAGES/N9HEH/pre-processed/holexohal lora/log" --network_alpha="128"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=128 --output_name="holexohal1" --lr_scheduler_num_cycles="1"
                         --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="1"
                         --max_train_steps="3500" --save_every_n_epochs="1" --mixed_precision="fp16"
                         --save_precision="fp16" --seed="1234" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW8bit" --max_data_loader_n_workers="1" --clip_skip=2
                         --bucket_reso_steps=64 --mem_eff_attn --gradient_checkpointing --xformers --bucket_no_upscale
[18:14:29] WARNING  The following values were not passed to `accelerate launch` and had defaults used      launch.py:890
                    instead:
                            `--num_processes` was set to a value of `1`
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run
                    `accelerate config`.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory E:\StableDiffusion\TRAINING IMAGES\N9HEH\pre-processed\holexohal lora\image\100_holexohal contains 35 image files
3500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 1
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "E:\StableDiffusion\TRAINING IMAGES\N9HEH\pre-processed\holexohal lora\image\100_holexohal"
    image_count: 35
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: holexohal
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 1825.49it/s]
prepare dataset
preparing accelerator
E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:258: FutureWarning: `logging_dir` is deprecated and will be removed in version 0.18.0 of 🤗 Accelerate. Use `project_dir` instead.
  warnings.warn(
Using accelerator 0.15.0 or above.
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
text_encoder\model.safetensors not found
Fetching 19 files: 100%|████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 19106.16it/s]
E:\StableDiffusion\kohya_ss\venv\lib\site-packages\safetensors\torch.py:98: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
CrossAttention.forward has been replaced to FlashAttention (not xformers)
import network module: networks.lora
[Dataset 0]
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 35/35 [00:14<00:00,  2.45it/s]
create LoRA network. base dim (rank): 128, alpha: 128.0
neuron dropout: p=None, rank dropout: p=None, module dropout: p=None
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 192 modules.
enable LoRA for text encoder
enable LoRA for U-Net
preparing optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary E:\StableDiffusion\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
use 8-bit AdamW optimizer | {}
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\StableDiffusion\kohya_ss\train_network.py:864 in <module>                                     │
│                                                                                                  │
│   861 │   args = parser.parse_args()                                                             │
│   862 │   args = train_util.read_config_from_file(args, parser)                                  │
│   863 │                                                                                          │
│ ❱ 864 │   train(args)                                                                            │
│   865                                                                                            │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\train_network.py:292 in train                                        │
│                                                                                                  │
│   289 │                                                                                          │
│   290 │   # acceleratorがなんかよろしくやってくれるらしい                                        │
│   291 │   if train_unet and train_text_encoder:                                                  │
│ ❱ 292 │   │   unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = acceler   │
│   293 │   │   │   unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler         │
│   294 │   │   )                                                                                  │
│   295 │   elif train_unet:                                                                       │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1143 in prepare     │
│                                                                                                  │
│   1140 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:                        │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│ ❱ 1143 │   │   │   result = tuple(                                                               │
│   1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1144 in <genexpr>   │
│                                                                                                  │
│   1141 │   │   │   result = self._prepare_megatron_lm(*args)                                     │
│   1142 │   │   else:                                                                             │
│   1143 │   │   │   result = tuple(                                                               │
│ ❱ 1144 │   │   │   │   self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d i  │
│   1145 │   │   │   )                                                                             │
│   1146 │   │   │   result = tuple(self._prepare_one(obj, device_placement=d) for obj, d in zip(  │
│   1147                                                                                           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:995 in _prepare_one │
│                                                                                                  │
│    992 │   │   │   if isinstance(obj, torch.utils.data.DataLoader):                              │
│    993 │   │   │   │   return self.prepare_data_loader(obj, device_placement=device_placement)   │
│    994 │   │   │   elif isinstance(obj, torch.nn.Module):                                        │
│ ❱  995 │   │   │   │   return self.prepare_model(obj, device_placement=device_placement)         │
│    996 │   │   │   elif isinstance(obj, torch.optim.Optimizer):                                  │
│    997 │   │   │   │   optimizer = self.prepare_optimizer(obj, device_placement=device_placemen  │
│    998 │   │   │   │   return optimizer                                                          │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py:1218 in             │
│ prepare_model                                                                                    │
│                                                                                                  │
│   1215 │   │   │   │   │   "You can't train a model that has been loaded in 8-bit precision wit  │
│   1216 │   │   │   │   )                                                                         │
│   1217 │   │   elif device_placement and not has_hf_device_map:                                  │
│ ❱ 1218 │   │   │   model = model.to(self.device)                                                 │
│   1219 │   │                                                                                     │
│   1220 │   │   if self.distributed_type == DistributedType.MULTI_GPU:                            │
│   1221 │   │   │   if any(p.requires_grad for p in model.parameters()):                          │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1145 in to         │
│                                                                                                  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│   1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│ ❱ 1145 │   │   return self._apply(convert)                                                       │
│   1146 │                                                                                         │
│   1147 │   def register_full_backward_pre_hook(                                                  │
│   1148 │   │   self,                                                                             │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:797 in _apply      │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:797 in _apply      │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:797 in _apply      │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:797 in _apply      │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:797 in _apply      │
│                                                                                                  │
│    794 │                                                                                         │
│    795 │   def _apply(self, fn):                                                                 │
│    796 │   │   for module in self.children():                                                    │
│ ❱  797 │   │   │   module._apply(fn)                                                             │
│    798 │   │                                                                                     │
│    799 │   │   def compute_should_use_set_data(tensor, tensor_applied):                          │
│    800 │   │   │   if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):           │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:820 in _apply      │
│                                                                                                  │
│    817 │   │   │   # track autograd history of `param_applied`, so we have to use                │
│    818 │   │   │   # `with torch.no_grad():`                                                     │
│    819 │   │   │   with torch.no_grad():                                                         │
│ ❱  820 │   │   │   │   param_applied = fn(param)                                                 │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)       │
│    822 │   │   │   if should_use_set_data:                                                       │
│    823 │   │   │   │   param.data = param_applied                                                │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1143 in convert    │
│                                                                                                  │
│   1140 │   │   │   if convert_to_format is not None and t.dim() in (4, 5):                       │
│   1141 │   │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() els  │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                │
│ ❱ 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No  │
│   1144 │   │                                                                                     │
│   1145 │   │   return self._apply(convert)                                                       │
│   1146                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 8.00 GiB total capacity; 915.37 MiB already
allocated; 5.53 GiB free; 962.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\gjass\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\gjass\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in   │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in          │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ E:\StableDiffusion\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in          │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['E:\\StableDiffusion\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py',
'--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:/StableDiffusion/TRAINING
IMAGES/N9HEH/pre-processed/holexohal lora/image', '--resolution=512,512', '--output_dir=E:/StableDiffusion/TRAINING
IMAGES/N9HEH/pre-processed/holexohal lora/model', '--logging_dir=E:/StableDiffusion/TRAINING
IMAGES/N9HEH/pre-processed/holexohal lora/log', '--network_alpha=128', '--save_model_as=safetensors',
'--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=128',
'--output_name=holexohal1', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant',
'--train_batch_size=1', '--max_train_steps=3500', '--save_every_n_epochs=1', '--mixed_precision=fp16',
'--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit',
'--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn',
'--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by xomega100** [comment]
> It is a subtle point. If your data is too big for the GTX 1070 Max-Q 8GB, give up because it won't work.

i'm not convinced this is the case. firstly i am running xformers and medvram in the webui-user.bat file. secondly, this is what the error message says:

`OutOfMemoryError: CUDA out of memory. Tried to allocate 58.00 MiB (GPU 0; 8.00 GiB total capacity; 915.37 MiB already
allocated; 5.53 GiB free; 962.00 MiB reserved in total by PyTorch)`

THERES 5.5GiB free! The allocation of 58MiB should be a walk in the park given theres so much space available.

**Comment by ruiboy1919** [comment]
taskkill /im cmd.exe
Try to free up memory space with this command.

**Comment by FurkanGozukara** [comment]
8 gb works

here a full tutorial readme read it and watch every step

https://github.com/FurkanGozukara/Stable-Diffusion/blob/main/Tutorials/Generate-Studio-Quality-Realistic-Photos-By-Kohya-LoRA-Stable-Diffusion-Training-Full-Tutorial.md
