### ISSUE TITLE
How to realize your own custom face-changing image

### ISSUE THREAD

**Issue by esbug** [bmaltais/kohya_ss#992]
### demand
**Provide one or several portrait pictures (upper body photos) by yourself, and then generate new pictures based on the pictures. I want the face to look very similar to what I provided (main problem), and then by setting prompt words, you can It is a full-body photo, which can be different scenes and different clothes.**

### my thinkings

1. mask painting.   (But there is no good realization result, and the face only has the appearance provided by myself, so it can't be more agile).
2. controlnet.  canny and openpose .(But it doesn't seem to be useful. I studied it for a while, but I didn't achieve good results.).
3. train own lora model. ( This is my most optimistic solution, but there are not many online tutorials, and the web ui also has version differences, which leads to training failure, and it is difficult to find the reason ).

### description

- I am a programming developer, but I have not been in contact with stable diffusion for a long time, but the demand is very urgent, so I need expert guidance.
- This is my contact information.
```
3407795834@qq.com 
or
w1468946038@gmail.com
```
- If anyone can help me, I will pay you, thank you very much.

**Comment by bmaltais** [comment]
What you are describing is exactly what LoRAs are for. You can literally train a LoRA on a few face images and generate outputs from that... I have never done a very small dataset of 1, 2 or 4 pictures... but I bet a 4 picture dataset using LoHA should produce pretty good results.

**Comment by bmaltais** [comment]
I created a model from roughly 24 pictures of myself. Results are pretty good using the Kohya LoCon with Prodigy optimizer.

Two sample outputs:

![02929-1414261381-bmaltais, Relaxed Sitting Pose, Coastal Horizon View, Classic Tuxedo, Miami Beach, Semi-Formal Dress Code, Diagonal Composition,](https://github.com/bmaltais/kohya_ss/assets/7474674/b2d1f7ba-eb91-4591-9e8e-58dc64da2179)

![02934-3267842218-bmaltais, Thoughtful Sitting Pose, Historical Cityscape, Classic Three-Piece Suit, Paris City, Black Tie Dress Code, Symmetrical](https://github.com/bmaltais/kohya_ss/assets/7474674/2f3b471e-e931-4a9c-ae1c-632c1b2ef6fc)

I used ChatGPT4 to help create the prompt to generate those.

**Comment by esbug** [comment]
> 您所描述的正是 LoRA 的用途。你可以在一些人脸图像上训练 LoRA 并从中生成输出......我从来没有做过 1、2 或 4 张图片的非常小的数据集......但我敢打赌使用 LoHA 的 4 图片数据集应该会产生相当好的结果结果。
Thanks for your answer. Now that the lora method is feasible, I will use dreambooth to try training. In fact, I have tried to use dreambooth training before, but there are few related tutorials, and the training failed. I will continue to read the documentation and try training. Thanks for the direction provided, let me avoid detours.
