### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by AAaabo** [bmaltais/kohya_ss#999]
` D:\Software\Python3109\lib\runpy.py:196 in _run_module_as_main                                   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ D:\Software\Python3109\lib\runpy.py:86 in _run_code                                              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\AI Image\kohya_train\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 │
│ in main                                                                                          │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\AI Image\kohya_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in     │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ D:\AI Image\kohya_train\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in     │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\AI Image\\kohya_train\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py', '--v2',
'--v_parameterization', '--enable_bucket', '--pretrained_model_name_or_path=D:/AI
Image/kohya_train/v1-5-pruned.safetensors', '--train_data_dir=D:/AI Image/kohya_train/factory_buildings/images',
'--resolution=512,512', '--output_dir=D:/AI Image/kohya_train/factory_buildings/model', '--logging_dir=D:/AI
Image/kohya_train/factory_buildings/log', '--save_model_as=safetensors', '--output_name=last',
'--max_data_loader_n_workers=0', '--learning_rate=1e-05', '--lr_scheduler=cosine', '--lr_warmup_steps=300',
'--train_batch_size=1', '--max_train_steps=3000', '--save_every_n_epochs=1', '--mixed_precision=fp16',
'--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0',
'--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.`
![1](https://github.com/bmaltais/kohya_ss/assets/127364775/f323ee95-429e-49de-9819-57f4443bbfdc)
![2](https://github.com/bmaltais/kohya_ss/assets/127364775/5ebbc273-3ef5-40a2-b1fc-99bcaf6d06ad)

**Comment by caesar311** [comment]
Please try with Memory efficient attention in advanced configuration.

**Comment by StockiChan** [comment]
> Please try with Memory efficient attention in advanced configuration.

how can you do this?

**Comment by caesar311** [comment]
> > Please try with Memory efficient attention in advanced configuration.
> 
> how can you do this?

Under Training Parameters > Advanced Configuration > Check Memory efficient attention and Gradient checkpointing for low vram machine.

**Comment by dfghsderftgerdf** [comment]
try this it helped me, I had the same issue download the latest cuda toolkit:

https://developer.nvidia.com/cuda-downloads?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exe_local

**Comment by evgebrtwjhr** [comment]
> 

I did that and it didn't help
